### PR TITLE
4548 - Fix custom tooltip data with bar grouped and column grouped chart

### LINKED ISSUE #4548: Column/Bar Grouped Chart: Custom Tooltip function not getting all group data
**Description:**
When hovered on any dataset first, shows the same tooltip in another dataset. In below case consider 2019, 2020 as datasets.

**Issue1:** This issue arises when tooltip is given to each data point in the dataset of 2019 and 2020 respectively.
image
image

2019 chart dataset has tooltips 25, 60, 70 80, 90 and 2020 chart dataset has tooltips 35, 55, 65, 45, 75.
Initially when hovered on 2019 columns, show correct tooltips, the same tooltips seen when hovered on 2020 columns.
In the same way, Initially when hovered on 2020 columns, show correct tooltips the same tooltips seen when hovered on 2019 columns.
The issue is recorded in small video. Please find the ppt- Issue1 and open, play the video in it.

**Issue2:**  This issue arises when tooltip is given at html level.
When tooltip is given like [tooltip] = “tooltip” in html and assigned custom tooltip to it, will get only one tooltip for entire chart.
Then same tooltip seen for 2019 and 2020 datasets.
image

Please the attachment ppt-Issue2.

The same issue was seen in Bar Grouped chart.
[Issue1.pptx](https://github.com/infor-design/enterprise/files/5445799/Issue1.pptx)
[Issue 2.pptx](https://github.com/infor-design/enterprise/files/5445800/Issue.2.pptx)

**Conclusion:**
When hovered on any dataset first, shows the same tooltip in another dataset in Column/Bar Grouped charts.

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed custom tooltip data with bar grouped and column grouped chart.

**Related github/jira issue (required)**:
Closes #4548

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4000/components/bar-grouped/test-custom-tooltip.html
- http://localhost:4000/components/column-grouped/example-custom-tooltip.html
- Open developer tools
- Hover on any bar in chart
- See in console for data info
- Should have right data in tooltip
- Hover over few times on each bar and each group
- It should have right data log in console and tooltip every time

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@deep7102 the data looks correct but in this situation should the tooltip point to the item at the moment it's still in the center

http://localhost:4000/components/column-grouped/example-custom-tooltip.html

Im wondering if we need a setting to get it to point at the bar that has the data being shown.


Screen Shot 2021-01-27 at 10 40 52 AM

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Requesting changes to wait for the tooltip's directional change as mentioned on the previous comment

**Comment by deep7102** [comment]
Hi @tmcconechy updated now, with target element

**Review by tmcconechy — DISMISSED** [review]
❤️  it!

**Review by ericangeles — APPROVED** [review]
Perfecto! 🎉

**Pull request merged**
