### PR TITLE
6977 - Style Changes for Existing Buttons and New Destructive Buttons

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will change style and features of existing buttons and added destructive buttons.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6977

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/button/example-index.html

Please refer to the requirements on:
- https://github.com/infor-design/enterprise/issues/6977
- https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=701%3A1222&t=2eRdbDDXoBLYCBwt-1

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by yohannahbautista** [comment]
Hello, there might need to be an adjustment in hover color when it's in different color modes as the text is hard to read
Screen Shot 2022-12-14 at 3 03 45 PM

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks pretty good.

- minor but it sort of looks like you added a while set of rules. Maybe some of the previous rules should actually be removed. But this might take too long so just a note.

the only issue i see is
- the hover state is missing on the enabled icon button
- the hover state is missing on the "btn-link" example on the tertiary icon
- when you look at the buttons on http://localhost:4000/ the new labels look out of place and out of the grid alignment. Maybe make it use the same classes as "Form Action Buttons" and contain it in the responsive grid:

Screen Shot 2022-12-14 at 10 40 28 AM

- also looking at http://localhost:4000/ -> the menu button should work like the new "tertiary"

**Review by tmcconechy — APPROVED** [review]
This looks very good to me :) Thanks @tjamesallen15

**Review by deep7102 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 can you just check the two tests. If something broke? Or if they need updating? Or maybe we just skip them?

**Comment by ericangeles** [comment]
I noticed this from a mobile perspective. I don't think we have a design for this yet. This is where the visual test fails.

Screen Shot 2022-12-17 at 4 06 20 AM

**Comment by ericangeles** [comment]
Think we can skip it for now.

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
