### PR TITLE
5253 - Add Cards' single and multiple selection state

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR implements single and multi-selection of cards.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5253

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Single Selection
- Go to http://localhost:4000/components/cards/example-single-select.html
- Click any of the cards
- It should be selectable and highlighted
- It should only select single card
- Test the UI across all themes and modes

2.) Multi-Selection
- Go to http://localhost:4000/components/cards/example-multi-select.html
- Compare to a single selection, multi-select should have checkboxes
- Click the cards, it should be selectable and the checkbox should be checked
- Clicking either the checkbox or the card itself should work the same
- Unselect the currently selected card/s
- It should unchecked and unhighlighted the card/s
- Test the UI across all themes and modes

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks great @ericangeles 👍🏻  Only one small thing:

- In both single and multiselect when you select the border comes on and expands the size. I think to solve this just set the default border to `border: 2px solid transparent;` so it does "jump"

**Comment by ericangeles** [comment]
@tmcconechy you mean the default card border? does it change the look of the card?

**Comment by ericangeles** [comment]
@tmcconechy, I pushed a solution on moving card/s when selected. Let me know if that works for you.

**Review by tmcconechy — DISMISSED** [review]
Ok i see @ericangeles . Yes that works well now 👍🏻 
Thanks all looks good here.

We may need to add the NG types.

**Comment by ericangeles** [comment]
Expecting this to fail because of the visual image. I will update once it failed.

**Comment by ericangeles** [comment]
> Ok i see @ericangeles . Yes that works well now 👍🏻
> Thanks all looks good here.
> 
> We may need to add the NG types.

Okay, the same ticket as well?

**Comment by tmcconechy** [comment]
yeah might as well just pr the new types quick in there so we dont forget (on the same ticket)

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
