### PR TITLE
NG1659 - Monthview Add Day

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix monthview not updating after changing activeDate.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1659

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/monthview/test-add-day.html
- Click `Add Day` button to modify selected date by 1 day.
- Open the Component to see the day is updated

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 the monthview isnt visible on the example?

Screenshot 2024-05-09 at 10 18 53 AM

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://github.com/infor-design/enterprise/assets/102151352/218fff6b-3189-4b7e-86e8-e0136249418a

It is not working accordingly in RTL.

https://github.com/infor-design/enterprise/assets/102151352/d5e1ea7e-7bf6-480d-9598-adfa4aef64e4

**Review by janahintal — CHANGES_REQUESTED** [review]
Also not working in RTL on my end
image

**Comment by n-ace-ancog** [comment]
@tjamesallen15 does it add days on only today's date or any selected date? Seems like its only doing the 1st one. Let me know if this is expected.

https://github.com/infor-design/enterprise/assets/156752175/ef35dc62-5bbd-4642-8edd-a593052f766b

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:

https://github.com/infor-design/enterprise/assets/156752175/c3fc09f4-c075-4ea4-bde8-daf5fc24b8f8

https://github.com/infor-design/enterprise/assets/156752175/67fb30a9-99d6-4350-b22b-a00704b31807

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
Approving. nice work!
Large GIF (940x554)
Large GIF (940x554)

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
