### PR TITLE
7297/7304 - Border on Search Field in Tabs Module Header

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the border in search field in the header in tabs module

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7297
Closes https://github.com/infor-design/enterprise/issues/7304

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=BB5500
- Check the searchfield component (it should be white)
- Hover the `Go` Button
- Switch on the Modes and Colors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by s-werking** [comment]
Hi @tjamesallen15, I noted a few things that may need some additional changes:

1. When you hover the close icon there is circle of the current theme color that appears
2. When the dark theme is used, the searchfield is the dark theme color but the category and go buttons are white
3. When the window is resized smaller and you type something into the searchfield and then backspace the whole entry, the two buttons to the right of the searchfield disappear

Here is a gif of these scenarios for reference:
Hover close icon and dark theme

**Comment by tmcconechy** [comment]
cc @tjamesallen15

**Comment by tjamesallen15** [comment]
Will do this on Monday. Thanks @s-werking @tmcconechy

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good but two suggestions to make it prettier

1) can you move the arrow icon next to the search over a couple pixels to the left so its not so close to the border?
2) try holding down the mouse on the go button and see the pressed state. its showing some extra borders that look a little off

**Review by tmcconechy — DISMISSED** [review]
Looks good! But if you want to further improve it i notice when you press the as earch button side it has a nice animation. But if you press the go button side it doesn't show the animation ripple. But this is minor so approving

**Review by tmcconechy — DISMISSED** [review]

**Comment by s-werking** [comment]
Hi @tjamesallen15,

I'm seeing the "x" button misaligned in the searchfield when I type:
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
