### PR TITLE
8243 - Calendar Slide Select

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add new setting `slideSelect` to allow users to select from span of range in creating an event.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8243

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-slide-select.html
- Try to slide select a span of date for creating an event

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Selecting multiple dates works, but found some issues

1. Selecting multiple days is only possible within the week

https://github.com/infor-design/enterprise/assets/156752175/e3960222-bef1-47bd-b6b3-6dee8089745a

2. Unable to correct selected days (go back) during selection

https://github.com/infor-design/enterprise/assets/156752175/634adcd8-6179-4642-be69-4ecfc354f85d

3. Border selection looks off in RTL

https://github.com/infor-design/enterprise/assets/156752175/05084941-b8b6-4fe8-a164-87750b4d284e

4. Modal is appearing on the first day selected rather than the last day (its blocking the view of the selected days)

image

**Nice to have**

1. Selecting current day to previous days
2. Selecting days vertically will select all days in between

**Comment by ericangeles** [comment]
@tjamesallen15, it looks good when slide dragging with a mouse, but it doesn't work using the keyboard as stated in the Figma document. Also, the selected dates are missing bluish background color. All in figma design, btw.

**Comment by jbrcna** [comment]
border is cut off in RTL
image
selecting multiple dates only applies with mouse

**Review by jbrcna — DISMISSED** [review]
image

**Comment by ericangeles** [comment]
@tjamesallen15, is this ready to review again? Looks like the keyboard is now working.

**Comment by tjamesallen15** [comment]
> @tjamesallen15, is this ready to review again? Looks like the keyboard is now working.

Yes. Forgot to remove wip

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The modal doesn't show after using the keyboard to select days.

https://github.com/infor-design/enterprise/assets/156752175/b665e01b-6baa-47d4-a7a2-032fb2ad4b44

**Comment by tmcconechy** [comment]
@tjamesallen15 @ericangeles @n-ace-ancog - anything left here?

**Comment by ericangeles** [comment]
Think we’re good in here, Tim. @n-ace-ancog, if you shift + dbl click in the last cell, the modal shows up. I think thats how it works. Lets just create a ticket if its really a bug, or we can enhance it.

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working on my side.

https://github.com/infor-design/enterprise/assets/156752175/dedbffb2-15a0-491d-8ac5-0e6487ade8bb

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
