### PR TITLE
7928 - Datagrid ToolbarFlex Setting

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add option to use for flex toolbar.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7928

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-toolbar-options.html
- Open `Developer Console`
- See if it is in flex toolbar

image

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Looks good. I did notice the animation on the expandable search field looks really weird when you expand it as it animates both ways. 

That could be another issue or can you think of a quick fix? Maybe no animation would be better? I think i should make another issue

**Review by yohannahbautista — APPROVED** [review]

**Comment by tjamesallen15** [comment]
> Looks good. I did notice the animation on the expandable search field looks really weird when you expand it as it animates both ways.
> 
> That could be another issue or can you think of a quick fix? Maybe no animation would be better? I think i should make another issue

I remember there was a searchfield animation from a previous ticket that I fixed. The same thing you mentioned back then. Here is the link, I fixed it here.
https://github.com/infor-design/enterprise/pull/7809

It seems that the animation was broken again. Yep, we should make another ticket specifically for this one

**Comment by tmcconechy** [comment]
@tjamesallen15 ok done - made it here for later: https://github.com/infor-design/enterprise/issues/8076

**Review by tmcconechy — APPROVED** [review]

**Comment by max-hizon** [comment]
Horizontal scrollbar not showing anymore

Works on Windows Edge
image
image

Windows Chrome
image
image


Windows Firefox
image
image

**Comment by tjamesallen15** [comment]
> Horizontal scrollbar not showing anymore
> 
> Works on Windows Edge image image
> 
> Windows Chrome image image
> 
> Windows Firefox image image

Hello. Thanks. Could you tag it `approved changes` if no issue was found?

**Review by jbrcna — APPROVED** [review]

**Review by max-hizon — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
