### PR TITLE
5997 - Windows10 Chrome Process Indicator Double Line

### LINKED ISSUE #5997: Process indicator separator has a double line.
**Describe the bug**
The border CSS for separators in process indicator appears to be creating a double line.

**To Reproduce**

1. Go to http://localhost:4000/components/processindicator/example-index.html
2. Observe separator. Notice white in middle. (see screenshot)

**Expected behavior**
Should be a solid line

**Version**

- 4.57.1

**Screenshots**
double-line

**Platform**
 - Windows 10
 - Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The `.separator` in `.process-indicator` looks like two lines on Windows10 Chrome.
This PR also converts the protractor visual regression tests to puppeteer tests and removes the old test file and old baseline images.

**Related github/jira issue (required)**:
Fixes #5997 

**Steps necessary to review your pull request (required)**:

- Pull, run, build
- visit /components/processindicator/example-index.html on Windows10 Chrome

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
Not sure why this is failing on a modal test? `test/components/modal/modal.puppeteer-spec.js`

**Comment by tmcconechy** [comment]
@davidcarlsonberg i saw this too and improved the test on https://github.com/infor-design/enterprise/pull/6132 once approved and merged it could fix it

**Comment by tmcconechy** [comment]
@davidcarlsonberg looks good - just need to update those image tests. And FYI we are now able too use puppetteer for this and will slowly migrate so maybe you can delete those two tests and make 2 new image ones for puppetteer instead https://github.com/infor-design/enterprise/pull/6112

**Comment by davidcarlsonberg** [comment]
@ericangeles Ever see this before?: `thrown: "Exceeded timeout of 9000 ms for a hook`

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by davidcarlsonberg** [comment]
Wow, triple approved, nice.

**Review by tjamesallen15 — APPROVED** [review]

**Comment by tmcconechy** [comment]
Previously all approved (quadruple approved :)

**Pull request merged**
