### PR TITLE
7046 - Landmark Test Results

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in tabs header and swatch personalize colors.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7046

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-header/example-index.html
- Header labels should be seen
- Go to http://localhost:4000/components/personalize/example-color-theme-api.html
- Default color should be white

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
The selected state looks a little funny 

Screenshot 2022-12-22 at 10 39 48 AM

I think this should be like this ...  https://4700-enterprise.demo.design.infor.com/components/tabs-header/example-index.html with it all the way filled (not alternate)


http://localhost:4000/components/personalize/example-color-theme-api.html?colors=0066D4 looks good 👍🏻

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good except for one thing. If you go to http://localhost:4000/components/tabs-header/example-index.html?colors=BB5500 (or any color). There is a problem with the color of the "blend effect" And also the states on the overflow button could be fixed.

Screenshot 2022-12-23 at 10 15 27 AM

And the failing test can either be skipped or fixed

**Comment by tmcconechy** [comment]
@tjamesallen15 still see a couple things.

a) any of the colors like http://localhost:4000/components/tabs-header/example-index.html?colors=535353 and http://localhost:4000/components/tabs-header/example-index.html?colors=BB5500 the overflow error down icon are a wrong color
b) also http://localhost:4000/components/tabs/example-index.html the tab color is white so not visible. This is on main but critical and related so please have a look.

**Comment by EdwardCoyle** [comment]
@tjamesallen15 I found a couple things too:
- http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=contrast -- When no personalization colors are assigned, the high contrast header variant has mixed background colors.  I'm not sure if the gray or the white is correct here, need to reference the designs.

Screen Shot 2023-01-03 at 9 37 55 AM

- On the page Tim called out: http://localhost:4000/components/tabs/example-index.html -- if you shrink the browser viewport's width so the overflow menu becomes visible, the dropdown icon is either missing or has no fill color.

Screen Shot 2023-01-03 at 9 38 14 AM

Tested everything else and it looks good otherwise 👍

**Comment by tmcconechy** [comment]
@tjamesallen15 still a few issues 

1. Classic theme is messed up 
http://localhost:4000/components/tabs-header/example-index.html?theme=classic&mode=light
- text color
- tabs focus state

1. classic dark is off http://localhost:4000/components/tabs-header/example-index.html?theme=classic&mode=dark
- header color
- tabs focus state
- ... button hover state

1. classic contrast http://localhost:4000/components/tabs-header/example-index.html?theme=classic&mode=contrast
- header color
- tabs focus state
- ... button hover state

1. http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=contrast
- missing the bar line next to the arrow dropdown

1. http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=dark&colors=0066D4
- missing button hover state

1. http://localhost:4000/components/tabs-header/example-index.html
- missing the bar line next to the arrow dropdown

just test all versions/modes and colors... and should be good. all should just look passable.

Thanks getting close 👍🏻

**Comment by tmcconechy** [comment]
http://localhost:4000/components/tabs-header/example-index.html?theme=classic&mode=light 
- now the focus on the button is wierd / dimmed

Screenshot 2023-01-06 at 9 47 39 AM

Last and final issue i can see :) I would fix but not certain where the fix should go at this time

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
Looks good now @tjamesallen15, thank you!

**Pull request merged**
