### PR TITLE
6918 - datagrid add row frozen columns

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where add row is not working properly when using frozen columns.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6918

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-addrow-with-frozen-columns
- Click on `Add Row`
- Enter a value for Product Name on the added row
- Click on the lookup icon for Product Id on the added row
- Choose a Product and Click Apply

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks like some things broke as evident by the test failures.

**Comment by ericangeles** [comment]
Can you check these errors @tjamesallen15 https://github.com/infor-design/enterprise/actions/runs/3376476760/jobs/5604244632#step:8:2468?

**Comment by tjamesallen15** [comment]
I'm still checking it.

**Comment by tmcconechy** [comment]
Ok, I think it might be a bit risky to change the main generator function. Unless we really have to but if we can get it to work thats ok. One thing to keep in mind is a previous fix broke this.

**Comment by tjamesallen15** [comment]
> Ok, I think it might be a bit risky to change the main generator function. Unless we really have to but if we can get it to work thats ok. One thing to keep in mind is a previous fix broke this.

Do you have the link of the said fix, so I can reference?

**Comment by tmcconechy** [comment]
No I wasnt able to track down which fix... But it was something. @claudenbach between what two versions did this break?

**Comment by claudenbach** [comment]
This last worked on 4.64.6.  We've moved to 4.67.2 for what will be our Jan release.

image

**Comment by tjamesallen15** [comment]
Will try to look for a more less risky fix.

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
