### PR TITLE
6074/6541 - Fix VPAT accessibility in bar chart

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR enhances the VPAT accessibility in Bar Chart.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/6074
Closes https://github.com/infor-design/enterprise/issues/6541

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/bar/example-index.html
- turn on voice over (or any screen reader)
- caps lock + left/right arrow (or screen reader nav key)
- do it until you hit the page
- For #6541, you should be able to tab from the toolbar element in the header to the main elements

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles not quite try https://main.wc.design.infor.com/ids-bar-chart/example.html

- Using voice over the sequence is to
  - Navigate to the parent element above it  or parent page
  - Hold <kbd>caps lock + left/right arrow</kbd>
  - You will hear the title , followed by number of items and then each list item
  - Proceed to use <kbd>caps lock + left/right arrow</kbd> will move through the list items announcing the values

You will see it announces that its a list/group and then you can arrow through the list items (the bars).
But this one has two issues:

1) it just says "bar graphic" not list so might need to remove that part
2) the numbers at the bottom are navigable (to fix this i added `aria-hidden="true"` in the WC one

**Comment by tmcconechy** [comment]
@ericangeles still having troubles with this i raised https://github.com/infor-design/enterprise/issues/6541 as i cant get from the toolbar down.

But if i select the title text above the card and navigate from there using caps-lock+left/down then all i hear is "bar Graphic empty" im not hearing the list?

**Comment by ericangeles** [comment]
@tmcconechy am having a hard time going to the bar section (from the title of the card) but I can confirm that the "bar graphic empty" is mentioned in the voice-over.

**Review by tmcconechy — COMMENTED** [review]
Looking a Lot better. 

a) does it still work without the tabindex? Problem with that is either we have to style the focus state or take it off and just use the virtual cursor like: https://main.wc.design.infor.com/ids-bar-chart/example.html
b) i think maybe we need a aria-label on the group as it just goes to "list" but doesnt tell you what the list topic is like https://main.wc.design.infor.com/ids-bar-chart/example.html

**Comment by ericangeles** [comment]
> Looking a Lot better.
> 
> a) does it still work without the tabindex? Problem with that is either we have to style the focus state or take it off and just use the virtual cursor like: https://main.wc.design.infor.com/ids-bar-chart/example.html b) i think maybe we need a aria-label on the group as it just goes to "list" but doesnt tell you what the list topic is like https://main.wc.design.infor.com/ids-bar-chart/example.html

It does work  but had hard time to tab to the chart. I knew it will have a focus style that's why I added css fix for that.

**Comment by tmcconechy** [comment]
@ericangeles when i turn off the voice over. and tab to it I'm not seeing anything. If we put that on and add an additiional aria-label for the chart title i think this will work?

**Comment by ericangeles** [comment]
@tmcconechy what aria-label value should we put?

**Comment by tmcconechy** [comment]
@ericangeles what i did was:

a) add a chart title (notice two titles this is so the browser tooltip doesnt show)
b) add an aria-label that is the legend text (so you know the chart items are about that)
Screen Shot 2022-06-13 at 11 28 47 AM

**Review by tmcconechy — APPROVED** [review]
Ok lets move this further to test. I think its working pretty well 👍🏻

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
