### PR TITLE
2298 - Fix for default personalize and tab scroller fixes [v4.19.x]

### LINKED ISSUE #2298: Tabs: Having some issues with tab fadeout boundary colors and default color
**Describe the bug**
Having some issues with tabs and personalize-header (landmark context form) defaulting the color.

**To Reproduce**
1. Go to http://localhost:4000/components/personalize/example-form3.html
1. Reduce the menu so the tabs overflow 
1. Pick a color in the menu
1. Notice the tab left and right have a wrong color

Also
1. Go to http://localhost:4000/components/personalize/example-form3.html
2. Type `Soho.personalization.setColorsToDefault()` in the console.

**Expected behavior**
Setting the color should work in the tabs example. And setColorsToDefault should add the azure colored header classes
for uplift or soho respectedly. We would set our style sheet and then call either `setColor('800000')` `setColorstoDefault()`.
So use setColor to set a color and setColorstoDefault to default back to azure with a dark app menu in the light theme for example.

**Version**
- ids-enterprise: [v4.19.0]

**Screenshots**
uplift with default color both left and right fade out pseudo elements look correct
image

Change to a different color (other than azure) and the left and right fade out pseudo elements look incorrect. Left seems to change to azure and right seems to keep the default.
image

The theme doesn't seem to matter (soho or uplift), just the color. Here's soho light with emerald color chosen.
image

**Additional context**
http://localhost:4000/components/personalize/example-form.html
http://localhost:4000/components/personalize/example-form2.html work ok

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This issue fixes the tab container sides when personalized. It also fixes the default for the contextual/personalized header so it defaults to the primary color on page load, or reseting to default.

Also fixed the animation when setting the color as it was only half animating

**Related github/jira issue (required)**:
Fixes #2298 

**Steps necessary to review your pull request (required)**:

http://localhost:4000/components/personalize/example-classes.html?theme=uplift
http://localhost:4000/components/personalize/example-classes.html
- page should load in the default primary color
- set a color in the .. menu
- set back to default and should look colored still in the primary color

Same With
http://localhost:4000/components/personalize/example-form.html?theme=uplift
http://localhost:4000/components/personalize/example-form.html
- page should load in the default primary color
- set a color in the .. menu
- set back to default and should look colored still in the primary color

Same With
http://localhost:4000/components/personalize/example-form2.html?theme=uplift
http://localhost:4000/components/personalize/example-form2.html
- page should load in the default primary color
- set a color in the .. menu
- set back to default and should look colored still in the primary color

Same With
http://localhost:4000/components/personalize/example-form3.html?theme=uplift
http://localhost:4000/components/personalize/example-form3.html
- page should load in the default primary color
- set a color in the .. menu
- set back to default and should look colored still in the primary color

NEW EXAMPLE
http://localhost:4000/components/personalize/example-form4.html
http://localhost:4000/components/personalize/example-form4.html?theme=uplift
- page should load in the default primary color
- resize so the the tabs are cut off and check the color
- set a color in the .. menu -> should look ok
- set back to default and should look colored still in the primary color
- also notice the disabled tabs color is nicer now and the inputs and labels are white background

### CODE REVIEW

**Comment by tmcconechy** [comment]
@nickwynja which part of that? You mean the tab edges? Its a linear gradient so have to investigate that one

**Comment by clepore** [comment]
Are you sure it wasn’t my commit that made it “clunky”?

**Comment by clepore** [comment]
@nickwynja are you sure my commit wasn’t what made things “clunky”?

**Comment by tmcconechy** [comment]
Pushed a new example 4 and an update to remove the animation. Hopefully good  now!

**Comment by janahintal** [comment]
QA Failed for all uplift theme in IE 11 browser. Please se below screen shot. 
Change the personalization to Emerald, then the mode to Dark Mode. 
Screen Shot 2019-06-06 at 4 49 52 PM

**Pull request merged**
