### PR TITLE
8035 - Fixed regression bug for personalize button hover stylings.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This is to address a regression bug where hover stylings are still incorrect for certain themes.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/8035
Closes https://github.com/infor-design/enterprise/issues/8191

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/button/example-index.html
- Hover over buttons.
- Test different themes.
- Hover styling should be more consistent under the different themes.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@RJ-Csc i see one issue in normal color. The hover color doesnt look correct anymore should be like https://4880-enterprise.demo.design.infor.com/components/button/example-index.html

**Comment by tmcconechy** [comment]
@RJ-Csc see https://github.com/infor-design/enterprise/issues/8191 as well i added to this issue

**Review by tmcconechy — APPROVED** [review]
Looks good. Lets pass this over to QA

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/93cfab46-455f-43f4-94cc-ab41800ae146

**Pull request merged**
