### PR TITLE
7804 - Add mobile nav features and fixes

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds mobile settings and mobile behavior to hang the module nav component over the header on mobile. It also fixes:

- some errors in card
- an alignment issue
- a sizing issue of the page-container

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/7823
Fixes https://github.com/infor-design/enterprise/issues/7804
Fixes https://github.com/infor-design/enterprise/issues/7934

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- notice the settings are reduced as some are now redundant
- click the hamburger to toggle the expanded menu
- clicking the page will not close it / click the hamburger again to close the page
- resize the page to a mobile/small tablet width
- click the hamburger to toggle the expanded menu
- clicking the page now close it
- click the hamburger to toggle the expanded menu again
- click the hamburger again will also close the page
- at the various states of the page open and close (including the detailView) check the width of the page-container is "correct"
- for the alignment issue notice that the dropdown is level with the hamburger

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
Looks great! 🍌

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Content of the body looks off when 'Preview 'showDetailView' setting' is checked.

Steps to reproduce:

1. Tick the 'Preview 'showDetailView' setting' checkbox
2. Adjust the page/view the page in mobile
3. Notice the Display mode dropdown

image

https://github.com/infor-design/enterprise/assets/102151352/11a90628-6264-4dc8-8ce1-43df8580a173

image

**Comment by tmcconechy** [comment]
@glenlieorillo when the dropdown is that small there isnt so much i can do with it so the text may overlap. Maybe we can make a new issue for the future for dropdown as it could be improved but is a minor edge case.

For the new issue it would be simpler to mention you can reproduce it on https://main-enterprise.demo.design.infor.com/components/dropdown/example-index.html

With the resizable mobile option.

Screenshot 2023-09-26 at 10 03 50 AM

So new issue please?

**Comment by glenlieorillo** [comment]
Alright, @tmcconechy. I will create a new ticket for this issue. Thanks!

**Review by glenlieorillo — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
