### PR TITLE
3041 - Fix incorrect disabled/readonly text colors due to CSS changes

### LINKED ISSUE #3041: Remove usage of `-webkit-text-fill-color` in favor of a CSS reset
**Describe the bug**
We utilize `-webkit-text-fill-color;` in a lot of places alongside the standard text color definition. We shouldn't be using this so prevalently because:

- MDN states that [it's non-standard technology](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color)
- Some browsers accidentally accept it over top of other valid color definitions, causing unexpected results (see the personalization bug with tooltips in #3011 as an example).

**Solution**
We currently have 30+ spots in IDS styles that use this property.  We should:
- [x] Remove it from all places where it's used.
- [x] Fix any broken visual regressions
- [x] Make some "reset" style rules specifically for any place where Chrome would be using this property to override standard text colors (for example, anchor tags, and `::selected` pseudo styles should probably have a rule that `unset`s this property).

**Version**
Tested as of v4.23.x-dev

**Screenshots**
Screen Shot 2019-10-28 at 2 45 57 PM

**Platform**
- n/a

### LINKED ISSUE #3199: Input: Text doesn't appear if used with the Builder Actions class and the Soho Dark theme
**Describe the bug**
The textbox value doesn't appear if used with the "builder-actions" class and the Soho Dark theme.

**To Reproduce**
1. Go to [http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark](http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark)
2. Enter value in Company Address/Phone Number/Website textboxes.
3. Notice the entered text is not shown in the textbox.

**Expected behavior**
The text entered should be shown clearly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Replicate the issue on fly
Soho Dark Theme issue with Builder Action - Live Demo

[http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark](http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark)
Soho Dark Theme issue with Builder Action

**Platform** 
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version: Version 78.0.3904.97 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a handful of issues found by Q/A after the changes in #3041.

**Related github/jira issue (required)**:
Fixes #3041
Fixes #3199

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the demoapp. Then...

_To test #3041:_
Double check the placeholder color text on disabled and readonly fields in the following example pages.  Specifically, check Mac OSX Safari:
- Standard Inputs: http://localhost:4000/components/input/example-index.html?theme=uplift&variant=contrast
- Colorpicker (Soho): http://localhost:4000/components/colorpicker/test-states.html
- Colorpicker (Vibrant): http://localhost:4000/components/colorpicker/test-states.html?theme=uplift&variant=contrast
- File Uploader (Soho): http://localhost:4000/components/fileupload/example-index.html?theme=soho&variant=light
- File Uploader (Vibrant): http://localhost:4000/components/fileupload/example-index.html?theme=uplift&variant=contrast
- Listview Searchfield: http://localhost:4000/components/listview/test-search-disabled.html?theme=uplift&variant=contrast
- Personalized Searchfield: http://localhost:4000/components/personalize/example-index.html?theme=uplift&variant=contrast&colors=9279a6
- Spinbox: http://localhost:4000/components/spinbox/example-disabled.html

_To test #3199:_
- Open http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark
- Ensure the background color on the Builder Actions area is not bright white.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Might this also fix https://github.com/infor-design/enterprise/issues/3199 ?

**Comment by EdwardCoyle** [comment]
@tmcconechy I pushed a fix for that

**Comment by tmcconechy** [comment]
@EdwardCoyle Just see two small things.

1) on http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark the dropdown arrow isnt alligned..(both the arrow and with the other field

Screen Shot 2019-12-04 at 2 15 38 PM

2)on http://localhost:4000/components/listview/test-search-disabled.html?theme=uplift&variant=contrast the searc field icon is also out of alignment (on both chrome
 and safari but more on safari)

Screen Shot 2019-12-04 at 2 16 19 PM

**Comment by jbrcna** [comment]
QA **PASSED**

Verified in http://4240-beta0-enterprise.demo.design.infor.com/examples/saleshub/edit-profile.html?theme=soho&variant=dark

**Pull request merged**
