### PR TITLE
Remove unnecessary setTimeout function

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Remove unnecessary setTimeout function in disable method and add consistency of disabled look in spinbox.

**Related github/jira issue (required)**:

N/A

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/form/example-disabled-field.html
- Hit `Click to Enable`
- Also check  http://localhost:4000/components/spinbox/example-disabled.html
- It should greyed-out the label and the spinbox

### CODE REVIEW

**Comment by deep7102** [comment]
Looks good! found few with disable spinbox (tested chrome)
- Buttons showing effect on click
- Sometime if you hit the corner of `+` the button, it add the box shadow around
image

**Comment by ericangeles** [comment]
Nice catch! All good now, @deep7102 @tmcconechy

**Comment by deep7102** [comment]
Hi @ericangeles still see the blue bubble effect soon you click on the `+/-` buttons

IDS Enterprise

**Comment by tmcconechy** [comment]
@ericangeles  and @deep7102 i fixed the spinbox issue - the tests will be fixed when https://github.com/infor-design/enterprise/pull/4329 is merged

**Comment by ericangeles** [comment]
> @ericangeles and @deep7102 i fixed the spinbox issue - the tests will be fixed when #4329 is merged

Thanks, @tmcconechy. Was about to look at it.

**Pull request merged**
