### PR TITLE
8618 - Autocomplete Keydown

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix autocomplete not properly highlighted on key down.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8618

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/autocomplete/example-index.html
- In the input field, type "ne" and wait for the results to appear.
- Hit the down arrow to nav down the list (notice the highlighted record is BLUE and FOCUS remains in the input field, which is correct behavior)
- Start over (clear the field or refresh the page)
- In the input field, type "ne" and WAIT for the results to appear (don't nav down).
- Now type another character "w" (for "new") and wait for the results to update.
- Hit the down arrow to nav down the list (should be blue focus too)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.
Blue - selected using arrow keys
Gray - hover state

**Latest**
image

**Current branch**
image

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/f6ce3204-d314-494a-83e7-9eeb6661b3e4

**Review by janahintal — APPROVED** [review]
https://www.loom.com/share/eecbb8dbca87477d882edd1e5e466cf0?sid=730949b3-5593-4e6c-b597-2e8c2824e422

**Comment by tjamesallen15** [comment]
Merging this now, I just fixed the merge issue on changelog. This was already approved. See above.

**Pull request merged**
