### PR TITLE
7850 - Fix on focus border being off in chart legend items

### LINKED ISSUE #7850: Donut: Legend highlight issue
**Describe the bug**
Legend highlight looks off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html
2. Click on legend
3. See error

**Expected behavior**
Legend highlights should be rendered properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/3d4bb880-cde7-4263-a3d5-60fa2c3c7ea7

image

**Platform**
 - All major browsers

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added styling to adjust focus border on legend items

**Related github/jira issue (required)**:

Closes #7850 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/donut/example-legend-bottom-single-widget.html
- Click on the chart items
- Focus border should look okay

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Comment by ericangeles** [comment]
Looks good! @yohannahbautista can you move the changelog to `4.88`?

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Focus border has different sizes.

Steps to reproduce:

1. Click the legend on 'Pie Chart'
2. Then click the legend on 'Pie Chart Two'
3. Compare the focus border on each legend

https://github.com/infor-design/enterprise/assets/102151352/b9c2734b-d513-45eb-9da7-f48e0f1d8370



Screenshot 2023-09-07 at 6 41 23 PM

image

----

Bug still exists in Classic Version.

image

**Comment by tmcconechy** [comment]
I'm not sure that im seeing the issues @glenlieorillo noticed but have a look @yohannahbautista 

Really minor but

- could improve centering a bit here (top vs bottom space
- could add 4px border radius

Screenshot 2023-09-07 at 9 39 00 AM

**Review by jbrcna — APPROVED** [review]
this is now working as expected. however, in classic the bottom spacing of legend is off. i wasn't certain if the fix also applies in classic version
image

[legend jumps out of the widget ](https://github.com/infor-design/enterprise/issues/7850#issuecomment-1690041608) -this is also fixed
image

**Comment by tmcconechy** [comment]
@jbrcna classic mode is much less important (deprecated). But can take a quick look @yohannahbautista ?

**Comment by ericangeles** [comment]
It appears to be positioned slightly above and not vertically centered. Can you adjust a bit, @yohannahbautista ?

**Review by tmcconechy — APPROVED** [review]
Looks good to me. 
cc @glenlieorillo for approval?

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected. Thanks, @yohannahbautista!

image

https://github.com/infor-design/enterprise/assets/102151352/c2e0ae77-4b72-466c-9ad2-9c72f10311bc

**Pull request merged**
