### PR TITLE
NG1590 - Fixed missing headers in frozen columns

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Colgroups weren't inserted when the datagrid is only frozen columns (which resulted in the headers not being inserted because colgroup didn't exist). Added colgroups in rendering

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1590

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-frozen-only.html
- Headers should exist

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**
image

**Mac Firefox**
image

**Safari**
image

**RTL**
image

**Review by ericangeles — APPROVED** [review]
Looks good! Thanks, @yohannahbautista.

**Review by janahintal — APPROVED** [review]
Screenshot 2024-03-22 at 12 30 54 PM

**Review by jbrcna — APPROVED** [review]
image
image
image

**Pull request merged**
