### PR TITLE
2569 - Fix range selection with datepicker [v4.20.x]

### LINKED ISSUE #2569: Datepicker: selection issues in range
**Describe the bug**
Datepicker: selection issues in range.

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Open the date picker in "Range - No Initial value"
3. Select July 30, 2019 to August 3, 2019
4. Open the date picker again
5. Click the left arrow to go to July 2019 view
6. See issue: there are issues in selection
7. Also, try to go to other months beyond August 2019, selections are also applied.
8. Issues are also encountered in all fields with range in the page

**Expected behavior**
Selections should be correct after selecting a range in should not be applied to other months.

**Version**
- ids-enterprise: v4.20.0-beta1

**Screenshots**
image

**Platform**
  - All devices, OS, and browsers

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed range selection was not working with datepicker.

**Related github/jira issue (required)**:
Closes #2569

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to http://localhost:4000/components/datepicker/example-range.html
- Open date picker as title `Range - No Initial value`
- Select July 30, 2019 to August 3, 2019
- It will select dates and close the picker
- Open the picker again
- It will open with month of `August 2019`
- Click the left arrow button to go to `July 2019` view
- See range selection should be correct

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Something about this isn't quite right.  I think it's because I didn't navigate back to July before selecting July 30.  Instead I selected it from the "August" page.

Aug-1-2019-3_44-PM

Also seems like the range isn't correct if you:
- Select the primary range.
- List closes.
- Click to reopen the datepicker.
- Navigate to a later month with the current range still selected.

Also:  It looks like only the last date in the range makes it to the input field when pressing "Select" in this mode.

**Comment by tmcconechy** [comment]
FYI - i don't think im seeing what @EdwardCoyle saw
- I closed some other range tickets and this is the last one left  https://github.com/infor-design/enterprise/issues/1306 but we can do that later. Just noting.

**Comment by deep7102** [comment]
Hi @EdwardCoyle I just retest as your steps above. I did not see that issue either. Please make sure you running the right branch and test again.

**Comment by EdwardCoyle** [comment]
I retested and it looks like I hadn't pulled the latest copy of this branch... my mistake!  The issue with the weird selection state is no longer present.

The only thing I'm still seeing is:
- Select a date range, allow the picker to close.
- Open the picker
- Click the "Select" button without choosing any new dates.
- The picker closes with only the second date in the range present

Aug-2-2019-9_10-AM

**Comment by tmcconechy** [comment]
@deep7102  will make a new issue for @EdwardCoyle last point and fix it in RC2 as is this is working much better.

**Pull request merged**
