### PR TITLE
6105 - Add jest image snapshot for visual regression testing in Puppeteer

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds a jest image snapshot for the visual regression testing together with the puppeteer.

I've encountered an issue where the regression tests keep failing in CI but in the local environment, it passed. If we wanted to pass the test in the CI, we still need to use docker for the VM since the environment of our pipeline works on ubuntu.

If you run the visual tests it would probably fail due to the image being generated from a different environment.

Also, I removed some unused codes.

Feel free to add any setting that will suit our needs.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/6105

**Steps necessary to review your pull request (required)**:
- Go to the travis-debug instance via docker to test the script
- Pull this branch, install the dependency, build, and run the app
- Run via `npm run e2e:puppeteer modal`
- It should pass all the tests

Still open to finding a way to not use the docker instance, but probably it would take a while to fix?

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles had another idea i am trying to see if i can change the build to run on mac-os maybe we dont need to use a VM then. Not sure why i didnt think of it before  

PR https://github.com/infor-design/enterprise/pull/6119

Might impacts documentation and this PR so mentioning. Will finish tomorrow

**Comment by ericangeles** [comment]
@tmcconechy I'll be updating the documentation once we are able to fix the #6119

**Comment by tmcconechy** [comment]
ok still trying - having a hard time getting all the tests to pass at once...

**Comment by tmcconechy** [comment]
@ericangeles i cant get building on mac working either it runs and times out in the functional tests or it fails in 7-10 puppetteer tests so seems flaky.

I guess go with the VM for now. Unless you have any ideas? https://github.com/infor-design/enterprise/pull/6119 
I'll try a few more things but running out of ideas right now

**Review by tmcconechy — APPROVED** [review]

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
