### PR TITLE
8675 - Calendar Event Popup Mobile View

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix calendar event popup render in mobile view.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8675

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-start-end-hour.html
- Toggle mobile view
- Click on any events

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 see a couple of problems:


a) can it be centered
b) the bottom looks cut off (should maybe scroll inside and fit)
c) there is too much space between some of the inputs

**Review by jbrcna — APPROVED** [review]
image
image
image

**Comment by tjamesallen15** [comment]
> @tjamesallen15 see a couple of problems:
> 
> a) can it be centered b) the bottom looks cut off (should maybe scroll inside and fit) c) there is too much space between some of the inputs

i cant see the (b) and (c) notes when I checked the UI. for A, do you want the it centered on mobile screen?

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Focus state looks off
- Bottom border is cut off

image

**Comment by tmcconechy** [comment]
@tjamesallen15 yes i think it will look better centered on mobile. Could therefore also hide the arrow. When you test it try cycling through all the "Iphone*" similulators in chrome tools.

We never had a good functionality here so while improving it we should make it look good as this is going forward now for a long time of maintenance.

**Comment by tjamesallen15** [comment]
> Bottom still looks off image

Where is the location of this should be exactly? @janahintal

**Review by n-ace-ancog — DISMISSED** [review]
Thanks for the clarification @ericangeles. Working on my side.

https://github.com/infor-design/enterprise/assets/156752175/595cc55a-0514-474c-a34e-e3ba163a0a1c


### **EDIT: Responded on a the wrong PR. Disregard this comment.**

**Comment by tjamesallen15** [comment]
> * Focus state looks off
> * Bottom border is cut off
> 
> image

This is not reproducible on my end. How do I reproduced this one using dev tools in chrome, mac and firefox? What device.

**Comment by glenlieorillo** [comment]
> > * Focus state looks off
> > * Bottom border is cut off
> > 
> > image
> 
> This is not reproducible on my end. How do I reproduced this one using dev tools in chrome, mac and firefox? What device.

Hi @tjamesallen15, I tested in BrowserStack - iPhone 15 ProMax - Chrome.

**Comment by tjamesallen15** [comment]
> > > * Focus state looks off
> > > * Bottom border is cut off
> > > 
> > > image
> > 
> > 
> > This is not reproducible on my end. How do I reproduced this one using dev tools in chrome, mac and firefox? What device.
> 
> Hi @tjamesallen15, I tested in BrowserStack - iPhone 15 ProMax - Chrome.

I dont have an access to browser stack unfortunately. cc @ericangeles @tmcconechy

**Comment by tmcconechy** [comment]
@tjamesallen15 try now i set your access

**Comment by tjamesallen15** [comment]
> @tjamesallen15 try now i set your access

thanks tim!

**Review by n-ace-ancog — APPROVED** [review]
Working on my side.

image

image

image

image

image

**Review by jbrcna — COMMENTED** [review]
image
image
image
image
image
image

--------------
just a minor observation: 
checkbox is cut off
image
image

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
