### PR TITLE
6615 - Fix styling of searchfield toolbar in alternate style

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the styling of alternate searchfield toolbar.

**Related github/jira issue (required)**:

Closes
- #6615 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbarsearchfield/example-alternate-style-with-categories.html
- Category button should not have any borders
- Click the category button
- Category button and searchfield should have borders

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — DISMISSED** [review]

**Comment by yohannahbautista** [comment]
Hi, the right border is cut off in my end
image

**Comment by ericangeles** [comment]
@yohannahbautista, how did you able to reproduce it? I remember seeing this but I fixed that too.

**Comment by tmcconechy** [comment]
@ericangeles i see it too on http://localhost:4000/components/toolbarsearchfield/example-alternate-style-with-categories.html when i expand the search by clicking it (in chrome)
Screen Shot 2022-07-14 at 9 55 00 AM

**Comment by ericangeles** [comment]
@yohannahbautista @tmcconechy am actually don't see it. It looks okay on my end.

**Comment by tmcconechy** [comment]
Im seeing weird stuff with it. I was able to see it cut off when i move it between monitors:

- start on a good monitor (dont open it)
- drag it over to macbook monitor
- open it and type in it
Screen Shot 2022-07-18 at 9 54 59 AM
- resize page
Screen Shot 2022-07-18 at 9 55 55 AM


I also once saw the x outside the field. Maybe try on the mac monitor and try resizing the page less wider gradually each time opening it and typing and hitting X ?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Marking as needs changes due to above comments? Did that help you see it?

**Comment by tmcconechy** [comment]
For later after these patches i see a new thing thats a bit funny behaviorally.

- make the page in chrome as little width as the page allows
- try to click the icon to expand
- you will notice in this case the input doesnt have focus

Screen Shot 2022-07-21 at 10 40 07 AM

**Comment by tmcconechy** [comment]
@ericangeles still seeing the last point i mentioned. Also if you do the following i see another small problem:

- start with browser wide
- click in the field and type so the x shows
- resize to the smallest width chrome allows

Screen Shot 2022-07-22 at 9 31 50 AM

**Comment by ericangeles** [comment]
@tmcconechy I can't replicate the close icon on the edge of the input field.

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
