### PR TITLE
7554 - Date column filter locale setting

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add a test page for column filter locale settings.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7554

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-filter-custom-date.html
- Try to use the filter in the `Order Date`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@tjamesallen15, could you please add a datepicker to the 'Order Date' field just to test if it's functioning correctly with the datepicker?

**Comment by tmcconechy** [comment]
@tjamesallen15 see one conflict and also im wondering where the fix is? Is a fix not needed for #7554 ? cc @s-werking

**Comment by tjamesallen15** [comment]
> @tjamesallen15 see one conflict and also im wondering where the fix is? Is a fix not needed for #7554 ? cc @s-werking

yep. I made no fix, I just made a correct example from what the user wants.

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

image


https://github.com/infor-design/enterprise/assets/102151352/c5dbb90c-49a1-465c-824e-7c11c5ef0fa3

**Review by janahintal — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving image

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
