### PR TITLE
6936 - Checkbox convert to pptr script

### LINKED ISSUE #6936: Checkbox: Convert Protractor tests to Puppeteer
**Is your feature request related to a problem or use case? Please describe.**
Convert Checkbox component protractor tests to puppeteer.

**Describe the solution you'd like**
Convert all test scenarios in protractor to puppeteer. The naming can be, {component}.puppeteer-spec.js

### PR DESCRIPTION
**Pull request by jbrcna**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes #6936 
**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer checkbox
4. It should pass.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Open for review @jbrcna?

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — COMMENTED** [review]
Looks good - but something is failing. And make sure you merge with main as well 👍🏻

**Comment by ericangeles** [comment]
All good to me! Please add log under 4.70 @jbrcna thanks!

**Review by ericangeles — DISMISSED** [review]

**Review by yohannahbautista — CHANGES_REQUESTED** [review]
Delete the old checkbox images as well

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
