### PR TITLE
5234 - Fix vertical tabs not showing on ios devices landscape mode

### LINKED ISSUE #5234: ContextualActionPanel: Add example with left side menu navigation
**Is your feature request related to a problem or use case? Please describe.**
Bringing over ticket from JIRA, 
Requirements:
1. Content will be displayed inside CAP but we need navigation in CAP
2. Navigation is realized using left-hand side vertical menu
3. Menu position can have: title, subtitle, icon, badge, etc.
4. Menu items separator is needed to group menu positions.

**Additional context**
https://www.figma.com/file/hN1MJ3HuJqEKF4QJd4wD1I/M3-App-Builder-IDS-Components?node-id=1%3A995 

JIRA Ticket: 
https://jira.infor.com/browse/UXD-2431

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes issues on iOS devices (iPhone 11 and up) that were not showing the vertical tabs when in landscape mode.

**Related github/jira issue (required)**:

Closes #5234

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/contextualactionpanel/example-cap-tabs-vertical.html
- Open in Browserstack or in actual device (iPhone 11 and above)
- Make it landscape
- Open the CAP
- You should be able to see the vertical tabs

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
~~- [ ] A note to the change log.~~

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by EdwardCoyle — COMMENTED** [review]
@ericangeles this looks good, but had a suggestion about the sample page itself.  The size of the CAP is pretty small when opened on a device/simulator browser.  It might be good to make the CAP fullsize on small breakpoints on that page, similar to this example: http://localhost:4000/components/contextualactionpanel/test-fullsize-responsive.html

Relevant setting code (maybe needs to become `data-options` depending on how you implement): https://github.com/infor-design/enterprise/blob/main/app/views/components/contextualactionpanel/test-fullsize-responsive.html#L149-L150

I'd be OK punting on this though

**Comment by ericangeles** [comment]
@EdwardCoyle was thinking of maybe we make it a default for the vertical tabs to behave full-size responsive on smaller viewport? Since tabs will definitely have tons of info.

**Comment by tmcconechy** [comment]
@ericangeles maybe we should keep the default as is but just make the example show it at full screen

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@ericangeles i dont think this works for responsive mode because the vertical tab is missing...

Screen Shot 2021-07-02 at 9 24 37 AM

Maybe just let it take up some space like 20% or whatever works

**Comment by EdwardCoyle** [comment]
@tmcconechy is that Chrome?  I tried the same thing and was seeing the responsive behavior work as expected (changes to horizontal tabs on small-width views, changes back to vertical tabs when growing the viewport):

Screen Shot 2021-07-02 at 9 31 28 AM

**Review by tmcconechy — APPROVED** [review]
Oh wierd i see it now too. Maybe my branch is out of sync

**Review by EdwardCoyle — APPROVED** [review]
:banana: Looks good @ericangeles!

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
