### PR TITLE
5048 - Fix selectable setting from mixed to single to remove checkboxes

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the listview selectable setting from mixed to single to remove the checkboxes.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5048

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/test-changing-selectable-setting.html
- Click the button actions to change from `single` to `mixed` or `multiple`
- There should be a checkboxes appear when changing to `mixed` or `multiple`
- It should reset everything once change the selectable setting

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@ericangeles i think there is two things we could improve here...

- turn on multi select
- select 3 rows
- turn on single select -> problem is three rows are selected but only one can be...

@claudenbach is it ok if the selections are reset when you change selection mode?

Also in mixed mode when you click the checkbox it is also activating the row. It ideally should not do this. Only the checkbox should check in that case.

**Comment by claudenbach** [comment]
Yes, it's okay to reset the selections when the selection mode changes to match the mode.

**Comment by ericangeles** [comment]
@tmcconechy looks like it doesn't activating the row when clicking the checkbox, but I noticed it has border.

**Comment by tmcconechy** [comment]
@ericangeles not sure what you mean? I think we just need to:

- reset all selections if changing this option (in updated)
- in mixed mode make sure the click of the checkbox doesnt activate the row (if possible?)

**Comment by ericangeles** [comment]
I meant in mixed mode, checking the checkbox doesn't affect the row to be activated.

**Comment by tmcconechy** [comment]
Ok i see - it works better here https://master-enterprise.demo.design.infor.com/components/listview/example-mixed-selection.html 
Maybe we need to set or have a showHoverState (like datagrid)

**Comment by ericangeles** [comment]
@tmcconechy I added a more better test page to test this. I also updated the details of the PR above.

Test here: http://localhost:4000/components/listview/test-changing-selectable-setting.html

**Review by tmcconechy — APPROVED** [review]
Ok approving. I see we have a hoverable setting in list view. I think maybe in the example they could turn that on but its optional. SO this is working as expected 👍🏻

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
