### PR TITLE
NG1549 - Additional check for select row when datagrid has grouping and filter

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added check to avoid undefined error. Found the same bug here: https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1549

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-grouping-filter.html
- Insert a filter
- Select a row
- No errors should appear in console

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — DISMISSED** [review]

**Review by jbrcna — DISMISSED** [review]
image

**Review by janahintal — COMMENTED** [review]
Hi @yohannahbautista, I was unable to expand & hide the groups after using filter and selecting a row. 
image

**Review by jbrcna — APPROVED** [review]
great work. approving
image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

image

**Review by ericangeles — APPROVED** [review]
reapproving. Thanks, @yohannahbautista!

**Review by max-hizon — APPROVED** [review]
Error no longer appearing in console

Windows Edge
image


Windows Firefox
image

Windows Chrome
image

**Pull request merged**
