### PR TITLE
2343 - Add HTTP Error handling to Demoapp / Improve routing

### LINKED ISSUE #2343: Demo App: Crashes node on a bad URL
**Describe the bug**
With a faulty URL its possible to bring down the Node JS demo app.

**To Reproduce**
1. Start Demo App
1. Go to a link like http://localhost:4000/components/idontexist/example-index.html
1. See error:
```
_http_outgoing.js:469
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:469:11)
    at Array.write (/Users/tmcconechy/Dev/master/node_modules/finalhandler/index.js:285:9)
    at listener (/Users/tmcconechy/Dev/master/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/tmcconechy/Dev/master/node_modules/on-finished/index.js:100:5)
    at callback (/Users/tmcconechy/Dev/master/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/tmcconechy/Dev/master/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Also:
http://localhost:4000/components/idontexist/ -> Does a 404
http://localhost:4000/components/idontexist -> Shows the component index page
http://localhost:4000/components/idontexist/anything -> Has the error
http://localhost:4000/components/area/sss-test -> Shows the component sample index page

**Expected behavior**
Should be more resilient.Either :
- show a 404 like http://localhost:4000/components/idontexist bonus: Maybe show a blank page with an ids message box in the middle instead or
- just show the index components page

**Version**
- ids-enterprise: [v4.19.0]

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes some incorrect usage of the ExpressJS Router in the Demoapp, which was causing uncaught errors in some cases, and in one specific case would cause the app to crash.  This PR also reworks the router order in general, adding some catch-all routes that provide helpful 404/500 error pages with hyperlinks where necessary.

**Related github/jira issue (required)**:
Closes #2343 

**Steps necessary to review your pull request (required)**:
Pull the branch and run the Demoapp.  Better logging is helpful to see the requests and errors, so I suggest using `npx grunt demo && node app/server.js --verbose` to run the app instead of the standard way.

Test the following pages to ensure error pages are present.  Make sure the hyperlink on these pages points to either the closest-level directory list, or the kitchen sink page at root `/`:
- http://localhost:4000/ss (link should point to kitchen sink)
- http://localhost:4000/components/idontexist
- http://localhost:4000/components/idontexist/
- http://localhost:4000/components/idontexist/anything (link should point to components list)
- http://localhost:4000/components/area/sss-test (link should point to area component list)
- http://localhost:4000/components/area/sss/sss/sss/sss (link should point to the area component list)
- http://localhost:4000/patterns/ss (link should point to patterns list)
- http://localhost:4000/examples/s3/xx (should point to S3 examples list)
- http://localhost:4000/api/xx (link should point to kitchen sink -- API listing doesn't exist for this folder by design)

Also try retesting the links above after running `npm run documentation`. On pages in the `components` folder, the hyperlinks will point to generated documentation pages where available.

Test the following data routes to ensure they all still work.  Any test page that implements one of these should not throw an `ENOENT` missing file error in the Demoapp console when using that `--verbose` flag.  All of these routes return JSON by default, so a JSON-friendly client or browser plugin is helpful:
- http://localhost:4000/api/compressors
- http://localhost:4000/api/construction-cart-items
- http://localhost:4000/api/construction-orders
- http://localhost:4000/api/dummy-dropdown-data
- http://localhost:4000/api/fruits
- http://localhost:4000/api/garbage
- http://localhost:4000/api/lookupInfo
- http://localhost:4000/api/my-projects
- http://localhost:4000/api/nav-items
- http://localhost:4000/api/orgstructure-children
- http://localhost:4000/api/orgstructure-large
- http://localhost:4000/api/orgstructure-lazy
- http://localhost:4000/api/orgstructure-paging
- http://localhost:4000/api/orgstructure
- http://localhost:4000/api/product
- http://localhost:4000/api/servicerequests
- http://localhost:4000/api/states
- http://localhost:4000/api/tree-tasks

In general, just click around in the Demoapp and make sure all hyperlinks between listings and example pages works as intended.

Also, taking suggestions on the error page design.  We never had them in the app before, so the layout is basic and maybe not the best.

**Included in this PR:**
- A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@nickwynja would it be possible to deploy this branch for testing?

**Comment by EdwardCoyle** [comment]
@tmcconechy they shouldn't automatically route to those pages.  I was saying that the hyperlinks on the 404 pages should point to what's in the parenthesis

**Comment by EdwardCoyle** [comment]
I'll check out the mobile view, didn't look closely at that before

**Comment by tmcconechy** [comment]
Ah i see, then i think the text should say something like "Click here to see similar pages" (something like that to make it "generally" clear the link would take you to "related" pages?

**Comment by tmcconechy** [comment]
Also do you think it matters if you see an error like. 
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
```
At least its not restarting the server but i dont really understand what that "means"

**Comment by tmcconechy** [comment]
@EdwardCoyle as noted we should check this on windows as @Sovia noticed it not working right there. She did rebuild and restart.

http://localhost:4000/components
- you get a 404 and the path is duplicated in the message so pulling a wrong path.

**Comment by EdwardCoyle** [comment]
I re-opened #2343, will fix shortly

**Pull request merged**
