### PR TITLE
3006 - Fix focus state for action button formatter with datagrid

### LINKED ISSUE #3006: Datagrid: The focus border is shown on the second last clicked menu
**Describe the bug**
We've found a minor issue with the focus border around the Actions (...) menus in datagrids that when you click a ... menu the border focus styling remains on the previously clicked menu.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-contextmenu.html
2. Scroll to the Actions column
3. Click the third ... menu
4. Click the last ... menu
(... 5. Click another ... menu)

**Expected behavior**
When the last ... menu is clicked that one should get the focus border (or atleast the previous one should not have it)

**Version**

- ids-enterprise: v 4.21.3

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
-

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed focus state for action button formatter was not working correctly with Datagrid.

**Related github/jira issue (required)**:
Closes #3006

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to http://localhost:4000/components/datagrid/test-contextmenu.html
- Scroll to the column `Actions`
- Click the third row `...` menu
- Now click the last row `...` menu
- The focus state should not be on third row `...` menu

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Hi @tmcconechy updated now, for both cases you find.

**Comment by tmcconechy** [comment]
@deep7102 - might look better if the focus state is on the cell (even tho the button takes action when the cell is focused)

**Comment by deep7102** [comment]
Hi @tmcconechy updated now focus border for action buttons

**Comment by tmcconechy** [comment]
See a bit of a bug.
- just open the page http://localhost:4000/components/datagrid/test-contextmenu.html
- then click any of the actions cell parts outside the button
- then cell is not getting focused
- this only works if you click the button then click outside the cell.

**Comment by deep7102** [comment]
Hi @tmcconechy updated now to fix focus to cell parts if clicked outside the button

**Pull request merged**
