### PR TITLE
8334 - Fixed alignment issues in go button

### LINKED ISSUE #8334: ToolbarSearchfield: x icon is not in proper position in responsive view
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
2. Switch/adjust to responsive
3. Verify each searchfield
5. Notice that the x icon in `Non-Collapsible Searchfield Toolbar Flex - With Go Button` is off

**Expected behavior**
should be properly aligned

**Version**

- ids-enterprise: 4.90.0-beta.0

**Screenshots**
Large GIF (1182x736)

**Platform**
All

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Fixed alignment issues in go button
- Removed categories in example page

**Related github/jira issue (required)**:

Closes #8334 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app 
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
- Check each searchfield
- Check in mobile too

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

failing in classic
image

**Comment by tmcconechy** [comment]
@yohannahbautista not sure if your done but i see

1) a gap on desktop

2) on mobile i still see a wierd collapsed icon and if you open and close non collapsed it stays expanded

Screenshot 2024-02-28 at 10 56 04 AM

**Review by tmcconechy — APPROVED** [review]
Looks good. Would be nice if these were the same width:

Screenshot 2024-02-29 at 1 16 32 PM

But opening up to QA good enough for me

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still failing in mobile (BrowserStack - iPhone 15 ProMax)

image

**Comment by ericangeles** [comment]
@infor-design/qa fyi

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Failing in RTL.

Mac Chrome
image

Mac Firefox
image

**Comment by ericangeles** [comment]
Please create a new issue for RTL, @glenlieorillo @n-ace-ancog.

**Comment by tmcconechy** [comment]
Merging these for beta. Can we just make sure to make an issue for any issues left for later?

**Comment by glenlieorillo** [comment]
Hello @tmcconechy, I already have created an issue for the bug in RTL. Refer to this link: [8505](https://github.com/infor-design/enterprise/issues/8505)

cc @ericangeles

**Pull request merged**
