### PR TITLE
QA - SOHO-8034 - Remove vertical scrolling from horizontal tab lists

### PR DESCRIPTION
**Pull request by EdwardCoyle**
> Explain the **details** for making this change. What existing problem does the pull request solve?

In Firefox, there used to be no overflow limit on vertical scrolling on Horizontal Tab lists, which was causing scrollbars to appear.  This PR removes vertical scrolling from inside of these tabs lists.

> **Related issue (required)**:

https://jira.infor.com/browse/SOHO-8034

> **Steps necessary to review your pull request (required)**:

- Pull down this branch and run the demoapp
- Open http://localhost:4000/components/tabs/example-index in Firefox on Mac.
- Ensure that it's no longer possible to scroll vertically inside the tab list (horizontal scrolling is allowed).

> Other Details:

Closes SOHO-8034

### CODE REVIEW

**Comment by tmcconechy** [comment]
Can you just test the comp form pattern https://jira.infor.com/browse/SOHO-7812. I remember something about this being an issue maybe not releated but worth a check.

**Comment by EdwardCoyle** [comment]
@tmcconechy I checked http://localhost:4000/components/compositeform/example-no-summary against the changes here and can confirm that there is no vertical scrolling on the responsive display.

**Comment by tmcconechy** [comment]
@EdwardCoyle I meant the swiping not the overflow, As this issue https://jira.infor.com/browse/SOHO-7812 took this out as you can see here:

http://git.infor.com/projects/SOHO/repos/controls/pull-requests/2707/overview

Try this url to see 
http://localhost:4000/components/tabs/example-index.html
http://localhost:4000/components/compositeform/example-no-summary

I pull this branch down after next PR and double check.

**Comment by EdwardCoyle** [comment]
@tmcconechy seems ok:  
may 29 2018 3_18 pm

**Pull request merged**
