### PR TITLE
7379 - widget/card design changes

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles want me to review this yet? Unclear on that right now.

**Comment by ericangeles** [comment]
@tmcconechy I've made some progress, but it's not quite ready for testing yet. But you can check if you want.

**Comment by tmcconechy** [comment]
I can wait until you put the steps and such in there. No problem. Just let me know when you need us to.

**Comment by ericangeles** [comment]
Closing this PR over a new branch name.

**Pull request closed without merging**
