### PR TITLE
2058 - Bar chart color changes

### LINKED ISSUE #1066: Scatter: Example Series 02 Color Code Not Appearing In the Tooltip
**Describe the bug**
 Scatter Chart Example Series 02 Color Code Not Appearing In the Tooltip

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/#
2. Scroll down to Scatter Chart Example
4. Click inside the chart to view the tooltip 
5. The light green Series 02 is not appearing in the tooltip. Only the blue series 01 is appearing in the tooltip.

**Expected behavior**
Both Series 01 and Series 02 should appear in the tooltip

**Screenshots**
scatter plot chart series 02

**Platform**
- All Browsers

**Additional context**
None

### LINKED ISSUE #1679: Alerts Component: Dirty tracker color is cut off on high/dark contrast
**Describe the bug**
Alerts Component: Dirty tracker color is cut off on high/dark contrast

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/alerts/example-index.html
2. Click on High Contrast
3. The Dirty tracker color is cut off
4. Please see screen shot attached

**Expected behavior**
The dirty tracker color should appear correctly

**Version**
n/a

**Screenshots**
bs_win10_ie_11 0 2

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

### LINKED ISSUE #2058: Personalization: Chart colors aren't updating when switching to the uplift theme
**Describe the bug**
When switching to the uplift theme colors in charts are not switching to the uplift color palette colors.

**To Reproduce**
1. Go to http://localhost:4000/components/bar/example-colors.html
2. Note soho colors (which is correct here).
3. Go to http://localhost:4000/components/bar/example-colors.html?theme=uplift
4. Notice colors of chart haven't changed.

**Expected behavior**
Colors for charts should use the themes color palette when switching to uplift.

**Version**
4.19-dev

**Screenshots**
image

**Platform**
 - PC
 - Window 10
 - Chrome
 - Version 74.0.3729.108 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Made fixes so charts would show the update colors in uplift mode. While doing that fixed any other minor color related issues.

**Related github/jira issue (required)**:
Fixes #2058  
Fixes #1679
Fixes #1066

**Steps necessary to review your pull request (required)**:
- For all of the links below compare the page in normal mode to uplift mode
- For each of these charts you can also spot check a few other examples (i tested them ALL and they now all work)
- on http://localhost:4000/components/scatterplot/example-index.html?theme=uplift - on this example hover the two colored dots and the toolitip should now show the right color
- List of relevant Chart test Pages:
http://localhost:4000/components/alerts/example-index.html
http://localhost:4000/components/alerts/example-index.html?theme=uplift
http://localhost:4000/components/area/example-index.html
http://localhost:4000/components/area/example-index.html?theme=uplift
http://localhost:4000/components/bar/example-index.html
http://localhost:4000/components/bar/example-index.html?theme=uplift
http://localhost:4000/components/bar-stacked/example-index.html
http://localhost:4000/components/bar-stacked/example-index.html?theme=uplift
http://localhost:4000/components/bar-grouped/example-index.html
http://localhost:4000/components/bar-grouped/example-index.html?theme=uplift
http://localhost:4000/components/bubble/example-index.html
http://localhost:4000/components/bubble/example-index.html?theme=uplift
http://localhost:4000/components/bullet/example-index.html
http://localhost:4000/components/bullet/example-index.html?theme=uplift
http://localhost:4000/components/column/example-index.html
http://localhost:4000/components/column/example-index.html?theme=uplift
http://localhost:4000/components/column-grouped/example-index.html
http://localhost:4000/components/column-grouped/example-index.html?theme=uplift
http://localhost:4000/components/column-stacked/example-index.html
http://localhost:4000/components/column-stacked/example-index.html?theme=uplift
http://localhost:4000/components/completion-chart/example-index.html
http://localhost:4000/components/completion-chart/example-index.html?theme=uplift
http://localhost:4000/components/donut/example-index.html
http://localhost:4000/components/donut/example-index.html?theme=uplift
http://localhost:4000/components/hierarchy/example-index.html
http://localhost:4000/components/hierarchy/example-index.html?theme=uplift
http://localhost:4000/components/line/example-index.html
http://localhost:4000/components/line/example-index.html?theme=uplift
http://localhost:4000/components/pie/example-index.html
http://localhost:4000/components/pie/example-index.html?theme=uplift
http://localhost:4000/components/positive-negative/example-index.html
http://localhost:4000/components/positive-negative/example-index.html?theme=uplift
http://localhost:4000/components/radar/example-index.html
http://localhost:4000/components/radar/example-index.html?theme=uplift
http://localhost:4000/components/scatterplot/example-index.html
http://localhost:4000/components/scatterplot/example-index.html?theme=uplift
http://localhost:4000/components/stepchart/example-index.html
http://localhost:4000/components/stepchart/example-index.html?theme=uplift
http://localhost:4000/components/targeted-achievement/example-index.html
http://localhost:4000/components/targeted-achievement/example-index.html?theme=uplift
http://localhost:4000/components/treemap/example-index.html
http://localhost:4000/components/treemap/example-index.html?theme=uplift

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/hierarchy/example-index.html?theme=uplift
Not related to this issue but Icon to text alignment is off.
icon-text-alignment

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/positive-negative/example-index.html
Is there a reason some of these are capitalized and others not?
capitalization

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/radar/example-index.html
http://localhost:4000/components/radar/example-index.html?theme=uplift
Unrelated but icon to text alignment is off on mobile.
alignment
alignment-uplift

**Comment by tmcconechy** [comment]
@davidcarlsonberg ok good call. I'll check a couple of these. Put request changes and i'll post back after.

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/targeted-achievement/example-index.html
http://localhost:4000/components/targeted-achievement/example-index.html?theme=uplift
Unrelated but there is a small gap between the solid blue and the striped blue.
small-gap
small-gap-uplift

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/treemap/example-index.html
http://localhost:4000/components/treemap/example-index.html?theme=uplift
Unrelated and not sure how much can be done but at mobile sometimes the text or percentage is cut off.
text-cutoff
text-cutoff-uplift

**Comment by tmcconechy** [comment]
@davidcarlsonberg I fixed all comments except the treemap one. Im not really able to fix that easily but the user can make the chart in a bigger parent or widget if they want to depending on their application so its somewhat flexible that way.

**Comment by tmcconechy** [comment]
This is now free from conflicts

**Pull request merged**
