### PR TITLE
optimize-regexp-for-url

### PR DESCRIPTION
**Pull request by eaenriquez**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
refactor the stringUtil method to validate a url
use a regexp literal instead of instantiating a new RegExp object and concatenating strings

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/8935

**Steps necessary to review your pull request (required)**:
Render a lot of datagrids (more than 50) with a filter on the header

**Included in this Pull Request**:
- [x] A refactor of the StringUtils.isValidUrl()

Please change the target branch if needed.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
@eaenriquez can you just add a change log entry (new section starting up 4.99.0)
Does this solve all the concerns on ttps://github.com/infor-design/enterprise/issues/8935 ?

**Comment by tmcconechy** [comment]
@n-ace-ancog similar here see command line instructions

**Comment by eaenriquez** [comment]
> @eaenriquez can you just add a change log entry (new section starting up 4.99.0) Does this solve all the concerns on ttps://github.com/[/issues/8935](https://github.com/infor-design/enterprise/issues/8935) ?

I just added into the changelog and added a new section v4.99.0.
Yes, the change addresses all the concerns on #8935

**Comment by eaenriquez** [comment]
@tmcconechy could we also patch this change to v4.90.x? This is for M3 and M3 ExD ..

**Comment by tmcconechy** [comment]
Yes now there is an error in lint. We can patch once this is merged. Just remind me if i dont get to it right away after this is tested and merged

**Comment by eaenriquez** [comment]
@tmcconechy the ci has now passed, I'm letting you take this one now :)

**Comment by eaenriquez** [comment]
> @eaenriquez QQ does #8939 need to be in the same patch?

Yes, I think so :)

**Comment by n-ace-ancog** [comment]
I tried to search for the repository in GitLab - stated in the [issue](https://github.com/infor-design/enterprise/issues/8935) steps, but seems I can't find it.  Might be the repository is set to private?

**Comment by eaenriquez** [comment]
> I tried to search for the repository in GitLab - stated in the [issue](https://github.com/infor-design/enterprise/issues/8935) steps, but seems I can't find it. Might be the repository is set to private?

I just added you as a member, can you try accessing it again ?

**Review by n-ace-ancog — APPROVED** [review]
Currently tested the following:

**Platform Tested:**
**Machine**: Mac Book Pro M3 14.5 (23F79)
**Browser**: Chrome
**CPU**: 6x slowdown

**Baseline test 1** - 2 seconds
image

**Baseline test 2** - 2 seconds
image

Test with fixes:

**Test 1** - 1.6ms
image

**Test 2** - 1ms
image

**Test 3** - 0.7ms
image

Tried to test it via other platforms, like windows, via BrowserStack, but failing to get the stats.

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@eaenriquez this and https://github.com/infor-design/enterprise/pull/8939 have been patched:

 ids-enterprise-ng@17.1.8 (contains 4.90.7 with the patch)

**Pull request merged**
