### PR TITLE
8285 - Fixed cell value replacing special characters on cell change

### LINKED ISSUE #8285: Datagrid: Backslash in edited cell is replaced with "&bsol;"
**Describe the bug**
In Datagrid, when typing Backslash in editable cell it replace with `&bsol;`

**To Reproduce**

1. Go to [https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html)
2. Click on of the cells
3. Type or paste a text with backslash, for instance `c:\windows\temp`
4. See that it changed into `c:&bsol;windows&bsol;temp`

**Expected behavior**
backslash should remain backslash.

It worked fine in v4.82.0 - but I don't know now how to reproduce it because design.infor.com was changed

**Version**

- ids-enterprise: v4.90.0

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
Thanks!

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed cell value replacing special characters on cell change

**Related github/jira issue (required)**:

Closes #8285 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-editable.html
- Enter `c:\windows\temp` in a cell
- Value should stay the same

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Review by ericangeles — DISMISSED** [review]

**Comment by ericangeles** [comment]
@yohannahbautista, could you check the failing test?

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@yohannahbautista can you just check the test something strange with it there https://github.com/infor-design/enterprise/actions/runs/7810119568/job/21303037889?pr=8425#step:9:282

**Comment by whernebrink** [comment]
We at M3 (Experience Designer) too see this issue. Can we test the following string to make sure it will stay as is?

`
related:[BALMAS1("TX60:\{IndexList_Items.TX60}")]
`
When entering that today it becomes:
`related:[BALMAS1(&quot;TX60:&bsol;{IndexList_Items.TX60}&quot;)]`

**Comment by tmcconechy** [comment]
@whernebrink yes i think this fix works for that string, you can test it here https://8285-datagrid-enterprise.demo.design.infor.com/components/datagrid/example-editable.html this is this branch posted up.

@yohannahbautista seems like just the test left

**Review by janahintal — CHANGES_REQUESTED** [review]
Failing on a link cell. 
image

**Comment by tmcconechy** [comment]
@janahintal what i see in the screen shot looks ok to me. Can you tell us the steps/behavior your seeing?
@glenlieorillo maybe your branch isnt upd to date can you try on https://8285-datagrid-enterprise.demo.design.infor.com/components/datagrid/example-editable.html ?

**Comment by whernebrink** [comment]
> @janahintal what i see in the screen shot looks ok to me. Can you tell us the steps/behavior your seeing? @glenlieorillo maybe your branch isnt upd to date can you try on https://8285-datagrid-enterprise.demo.design.infor.com/components/datagrid/example-editable.html ?

I tested in the link you had there @tmcconechy and it does not work in the hyperlink field:
image

**Comment by tmcconechy** [comment]
@yohannahbautista can you check the link field?

**Review by glenlieorillo — DISMISSED** [review]
image

**Comment by tjamesallen15** [comment]
@infor-design/qa can we test this again? thanks

**Review by jbrcna — APPROVED** [review]
image

**Review by janahintal — APPROVED** [review]
Approving. Now working as expected on my end. 
https://8285-datagrid-enterprise.demo.design.infor.com/components/datagrid/example-editable.html 
image

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@whernebrink, is this working on you now?

**Comment by whernebrink** [comment]
> @whernebrink, is this working on you now?

I copied in the fix in sohoxi.js locally and it seems to work on our end, thanks! 

@tmcconechy Since we're using enterprise-ng 17.1.1 which uses enterprise 4.90, is there anyway to do a patch on 4.90 with only this fix, and a patch from 17.1.1 to use that enterprise patch version? That would be really help us out for the April release.

**Comment by tmcconechy** [comment]
@whernebrink no problem. Its patched into https://www.npmjs.com/package/ids-enterprise-ng/v/17.1.3 for you.
For the main patch I'm waiting for one other issue (for anyone watching 👀 )

**Comment by whernebrink** [comment]
Hi @tmcconechy , 

Seems like the underlying value is still getting "encoded". It is no longer encoding what is actual in the editable field, but the actual rowData one get is. Could anyone else please confirm? 
image

**Pull request merged**
