### PR TITLE
7125 - modal validation tooltip

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix alignment of tooltip error in modal.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7125

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/modal/test-validation-error-tooltip.html
- Press `Add Context`
- Intentionally blank the required fields so that the error tooltip will popout

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — DISMISSED** [review]

**Review by andriivarhanov — COMMENTED** [review]
looks good, the only thing I see is this default outline around the icon on focus in Chrome
image 
could you please check?

**Comment by s-werking** [comment]
Hi @tjamesallen15, when I test this in the classic theme, the icon is not completely red but the alignment looks good:
image

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I'll request changes but i see only @andriivarhanov 's issue not @s-werking 
Screenshot 2023-02-16 at 12 03 14 PM

**Comment by s-werking** [comment]
You're right @tmcconechy, I think I was seeing the icon issue due to the issue @awbuboltz just posted in teams when switching themes. If I enter the url directly to test on the classic theme, the icons look good.

**Review by ericangeles — CHANGES_REQUESTED** [review]
`Required` text color under textarea is not changing to red when there's no text. (Dark mode New)

http://localhost:4000/components/modal/test-validation-error-tooltip.html?theme=new&mode=dark&colors=0066D4

Screen Shot 2023-02-20 at 1 14 16 PM

**Review by andriivarhanov — COMMENTED** [review]
could you please also change `Required` text color in new contrast theme http://localhost:4000/components/modal/test-validation-error-tooltip.html?theme=new&mode=contrast

image

it looks like it should be `ruby-90`

**Comment by tmcconechy** [comment]
One issue i see is if i hover the icon i do not see the tooltip. @s-werking did it always work this way?

**Comment by s-werking** [comment]
@tmcconechy I think it did always work that way. The tooltip should show when the field is focused again.

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
> could you please also change `Required` text color in new contrast theme http://localhost:4000/components/modal/test-validation-error-tooltip.html?theme=new&mode=contrast
> 
> image
> 
> it looks like it should be `ruby-90`

Once this one's been fixed, we can merge it now.

**Review by ericangeles — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]

**Pull request merged**
