### PR TITLE
8453 - Calendar Event Tooltips

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add new setting `showTooltip` and `tooltipSettings` to display event information on event hover.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8453

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-event-tooltips.html
- Hover one of the events

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@tjamesallen15 looks good just check the lint

**Review by ericangeles — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working on my side.

image

image

image

**Review by jbrcna — APPROVED** [review]
image
image

**Review by janahintal — APPROVED** [review]
Working as expected.
image

**Pull request merged**
