### PR TITLE
8448 - Fixed misalignment in card header icon

### LINKED ISSUE #8448: Counts: Misaligned info icon
**Describe the bug**
Misaligned info icon.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/counts/example-widget-count.html
2. Notice the info icon under GRC Violation Count

**Expected behavior**
Info icon should be aligned accordingly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

image

image

**Platform**
 - All major browsers

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed misalignment in card header icon

**Related github/jira issue (required)**:

Closes #8448 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/counts/example-widget-count.html
- Check icons

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
It seems that the icon in the header is too far away on smaller viewports.

- Resize the page to smaller/mobile viewport
- Check the icon in the header

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Icon is missing in RTL.
https://8448-count-enterprise.demo.design.infor.com/components/counts/example-widget-count.html?locale=ar-SA

image

- Too much space between the text and the icon in mobile view.
image

**Review by janahintal — CHANGES_REQUESTED** [review]
image

Info icon in Card title is not displaying in RTL 
image

**Review by jbrcna — APPROVED** [review]
image
image
image
image

**Comment by tmcconechy** [comment]
Everything seems fixed now 👍🏻

**Pull request merged**
