### PR TITLE
5988 - monthview: ability to update legend

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add the monthview an ability to update legend on month change.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5988

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/monthview/test-legend-loaded.html
- Change the month to `February`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
I see the events firing but im not seeing the legend change when i change months. Maybe you can update the example so it changes the legend items? I think thats the use case so would be good to see that working

**Comment by tmcconechy** [comment]
@tjamesallen15 for the example I'm still not seeing that the legend is changing values when i change months?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 for the example I'm still not seeing that the legend is changing values when i change months?

weird. its changing on my end. 
image

then change to feb.
image

**Comment by tmcconechy** [comment]
Oh i mean the items in the bottom. (Public Holidays ... Full Days) was expecting from the issue that they would load both the legend values and the dates matching the legends

**Comment by tjamesallen15** [comment]
> Oh i mean the items in the bottom. (Public Holidays ... Full Days) was expecting from the issue that they would load both the legend values and the dates matching the legends

Oh! My bad! I'll be checking on that. I misunderstood it.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
