### PR TITLE
5256 - Action Sheet design Q/A changes

### LINKED ISSUE #5256: Popupmenu: Add an option to show mobile menus
**Is your feature request related to a problem or use case? Please describe.**
Add a setting to popupmenu 

**Describe the solution you'd like**

- [x] Add the setting
- [x] Test it works on android and iphone (r-2)
- [ ] Add some code to the Web Component (later is fine)

**Designs**
(Not really a design use the OS menu)

Screen Shot 2021-06-01 at 1 36 31 PM

**Additional context**
See section "bottom action sheet"
https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR addresses items brought to us during design Q/A (@kevinwhitedesign).  Also included in this PR:
- Fixed a minor lifecycle bug I discovered while testing that would accidentally render the menu markup multiple times if the trigger button was clicked multiple times.
- Moved some code around from the recent work on the new card design from #5295 to enable use of the "vertical" actions button everywhere. (@ericangeles) 

**Related github/jira issue (required)**:
Closes #5256
Related to #5305 

**Steps necessary to review your pull request (required)**:
- Pull, Run, Build!
- Open http://localhost:4000/components/actionsheet/example-index.
- Make sure the trigger button's icon is vertically-aligned (per Figma designs)
- Click on the trigger button.  It should produce the ripple effect (called "pulse" in the Figma designs)
- If the action sheet isn't open, close the popupmenu, shrink the page down very small, and click the trigger button again. 
- Ensure the Actions inside the Action Sheet are center-aligned
- Either click the cancel button, or click inside the dark overlay area.  When the action sheet is cancelled, no toast should display.
- Check all examples in http://localhost:4000/components/actionsheet and make sure vertical actions button is being used.

_To test lifecycle bug:_
- Open http://localhost:4000/components/actionsheet/example-index
- Make sure the page is large enough to open the Popupmenu and click the trigger button
- Click the trigger button again.  No stray HTML markup should be generated and placed in the page.

_To test moved Cards code:_
- Open http://localhost:4000/components/cards/example-expandable-cards.html
- Make sure the icon looks correct

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good but tell me if this is out of scope, i think we should change the way http://localhost:4000/components/cards/example-variations-hitboxes.html is done for the vertical icon button to match yours and refactor that? As we are doing it two ways and his is way more specific to cards.

**Comment by EdwardCoyle** [comment]
@tmcconechy I think the actual implementation is the same between both.  The visual style of the trigger button is changed when it's used within the "touchable" card.  Otherwise, outside a card, it's a standard action button like the ones we'd see on toolbars, etc.  The only thing missing on the Card samples is a `$('button').button()` constructor (which would add the pulse effect).  What would we change, you think?

**Comment by tmcconechy** [comment]
I guess i just mean using the "vertical" class on the icon on  http://localhost:4000/components/cards/example-variations-hitboxes.html instead of having it "hard coded" under https://github.com/infor-design/enterprise/blob/main/src/components/cards/_cards.scss#L128 a specific dom specification..

```
  .card-buttonset {
      .card-content-action {
```

**Comment by EdwardCoyle** [comment]
I did actually change that in this PR, generalizing `.vertical` to be used anywhere:

- Added to the Button SCSS: https://github.com/infor-design/enterprise/pull/5367/files#diff-219fe0da08ec1768ffa7f1f249b3ec17a37edf92588a2f2207e8ceff77a00a0bR512
- Removed from the Card SCSS: https://github.com/infor-design/enterprise/pull/5367/files#diff-f34afaae4808dee69eb9770babf3049116c53dec96169e92310ad235c08be257L174

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
