### PR TITLE
8332 - Fixed misalignment in clear icon on mobile

### LINKED ISSUE #8332: ToolbarFlex: x icon position is off in smaller viewport
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html?theme=classic&mode=light&colors=ffffff
2. Switch to mobile viewport
3. Type in searchfield

**Expected behavior**
x icon should have enough spacing

**Version**

- ids-enterprise: 4.90.0-beta.0

**Screenshots**
image

iOS
image

Android
image

**Platform**
mobile

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed misalignment in clear icon on mobile

**Related github/jira issue (required)**:

Closes #8332 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- In mobile, go to: http://localhost:4000/components/toolbar-flex/example-searchfield-collapsible.html?theme=classic&mode=light
- Type in searchfield
- Clear icon should be aligned

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
'x' icon is not aligned and overlapping on texts in responsive view. 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Galaxy Z Fold 5**

- Fold
image

- Unfold _Bug still exists_
image

**iPhone 15 Pro Max**

image

**Review by jbrcna — APPROVED** [review]
image
image
image

**Review by janahintal — DISMISSED** [review]
image
image

**Review by glenlieorillo — APPROVED** [review]
**Galaxy Z Fold 5**
image

image

**Galaxy S24 Ultra**
image

**Pull request merged**
