### PR TITLE
4820 - Lookup/Timepicker/Datepicker accessibility improvements

### LINKED ISSUE #4820: Lookup, date picker and time picker field does not have accessible labels, role and state info.
**Describe the bug**
[VPAT] Lookup, time and date picker button in fields does not have accessible labels and role and state info..

**To Reproduce**
1. open screenreader
1. go to: https://master-enterprise.demo.design.infor.com/components/field-options/example-index
1. hover over the lookup, date or timepicker buttons, the buttons are not announced.
1. Also do this in web components...

**Expected behavior**
VPAT Recommendation:
Ensure the following information is conveyed for each control:
1. A meaningful label describing the function/purpose of the control (e.g. "Look up").
2. A role to inform users of how the control functions (e.g. by wrapping the control in a <button> element, or in an element with role="button"). 
see example compliant code for the lookup control:

```
<span class="lookup-wrapper sm">
    <input>
    <button class="trigger">
        <span class=sr-only">Look up</span>
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            ...
        </svg>
    </button>
</span> 

```

**Version**

- ids-enterprise: v4.36.2 and v4.38.0-dev

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - Device: (if applicable) : NA
 - OS Version: Windows 10 
 - Browser Name: firefox
 - Browser Version: 85.0 (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34219

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR makes some changes to some trigger field components (Lookup, Datepicker, Timepicker) to convert the "trigger" from just an icon to a button, along with adding various missing ARIA roles, descriptive text, and other minor improvements to improve detection of these components by screen readers.

To test this issue, please pre-install Chrome Vox or another screen reader application.

**Related github/jira issue (required)**:
Closes #4820 

**Steps necessary to review your pull request (required)**:

_Test Lookup_:
- Open http://localhost:4000/components/lookup/example-index?layout=nofrills
- Enable Chrome Vox (or other screen reader)
- Focus the first input field.  The screen reader should speak "Products Lookup.  Press Down Arrow to Select. Edit Text, Required"
- Press the tab key.  The Lookup icon is now focusable and should appear focused.  The screen reader should speak "Lookup Trigger Button"
- Test RTL and check for icon/button alignment: http://localhost:4000/components/lookup/example-index?layout=nofrills&locale=ar-SA
- Test classic theme:  http://localhost:4000/components/lookup/example-index?theme=classic&mode=light&layout=nofrills
- Test non-tabbable example - the new second tabstop should be disabled, and the keyboard behavior should work like before this change: http://localhost:4000/components/lookup/example-not-tabbable?theme=new&mode=light&layout=nofrills

_Test Datepicker_:
- Open http://localhost:4000/components/datepicker/example-index?theme=new&mode=light&layout=nofrills
- Enable Chrome Vox (or other screen reader)
- Focus the first input field:.  The screen reader should speak "Date Field. Press Down Arrow to Select. Combo Box Collapsed".
- Press the Tab key.  The trigger icon is now focusable and should appear focused.  The screen reader should speak "Date Picker trigger button"
- Test RTL and check for icon/button alignment: http://localhost:4000/components/datepicker/example-index?theme=new&mode=light&layout=nofrills&locale=ar-SA
- Test classic theme: http://localhost:4000/components/datepicker/example-index?theme=classic&mode=light&layout=nofrills
- Test non-tabbable example - the new second tabstop should be disabled, and the keyboard behavior should work like before this change: http://localhost:4000/components/datepicker/example-not-tabbable?theme=new&mode=light&layout=nofrills
- Test Calendar Toolbar: http://localhost:4000/components/calendar-toolbar/example-index.html
- 
	
_Test Timepicker_:
- Open http://localhost:4000/components/timepicker/example-index?theme=new&mode=light&layout=nofrills
- Enable Chrome Vox
- Focus the first input field.  The screen reader should speak "Timepicker. Use Arrow Keys to Select. Combobox Collapsed."
- Press the Tab Key.  The trigger icon is now focusable and should appear focused. The screen reader should speak "Time picker trigger button"
- Test RTL and check for icon/button alignment: http://localhost:4000/components/timepicker/example-index?theme=new&mode=light&layout=nofrills&locale=ar-SA
- Test classic theme: http://localhost:4000/components/timepicker/example-index?theme=classic&mode=light&layout=nofrills
- Test non-tabbable example - the new second tabstop should be disabled, and the keyboard behavior should work like before this change:  http://localhost:4000/components/timepicker/example-not-tabbable?theme=new&mode=light&layout=nofrills

_Test Datagrid Filter Row:_
- Open https://localhost:4000/components/datagrid/example-filter.html
- Check the Datepicker, Timepicker, and Lookup fields and ensure the icon placement looks right
- Check RTL: https://localhost:4000/components/datagrid/example-filter.html?locale=ar-EG
- Check Classic Theme: http://localhost:4000/components/datagrid/example-filter.html?theme=classic&mode=light

_Test Short Fields_:
- Open http://localhost:4000/components/form/example-compact-mode.html
- Check button/icon alignments on Lookup, Datepicker, and Timepicker. Ensure focus state appears to be within the boundaries of the field.
- Check RTL: http://localhost:4000/components/form/example-compact-mode.html?locale=ar-SA
- Check Classic Theme: http://localhost:4000/components/form/example-compact-mode.html?theme=classic&mode=light&locale=ar-SA

Test any other examples of these components you think may be missing from the list above (I'm sure I missed some)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@JBismonte if you're able to test this branch against a live environment, please let us know if you think we missed anything in the new trigger button implementation.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
A couple small things

- on the normal size ones date/lookup/time - i feel like the button area is a bit small (on some it looks like the icon isnt centered in it. Can we make the button area a bit bigger?
- i'm also not sure about the message - it feels a bit redundant long (im getting: datepicker trigger button - hit enter to select - button) - i did some quick research and think its probably ok to just have "Date Picker": in the text so it just says "Date Picker Button" at the end of it all

**Comment by EdwardCoyle** [comment]
@tmcconechy calling this one "done" for now

**Review by tmcconechy — APPROVED** [review]

**Comment by rob2d** [comment]
checking into this -- small heads up that I am not the most well versed in the ARIA/accessibility standards, so will look at things included with a time budget, but might not be very thorough.

**Comment by tmcconechy** [comment]
@rob2d main thing is the actual tab stop - but give it a test with Chrome Vox for a bit

**Comment by rob2d** [comment]
@EdwardCoyle @tmcconechy  not sure if we should open a new issue for this but found an issue visually with the close button:

image

**Comment by rob2d** [comment]
(this was also partly on me -- had not known to test this on that alignment issue  😅

**Review by rob2d — APPROVED** [review]

**Comment by rob2d** [comment]
approved since it's quite a bit out of scope on this issue, as everything else works -- at least for the search button, we have made a lot of progress in other cases.

**Comment by EdwardCoyle** [comment]
@rob2d yeah we'll open a new issue for that, thanks for checking it out

**Comment by awbuboltz** [comment]
Hey guys, this is a major change, right? Is there a way to disable this? Our product, as well as most others, are data entry heavy. This change is doubling the amount of keystrokes that users will now take, correct? We're actually trying to put a fix out currently for Seattle Children's because they noticed one single extra tab key on one form and we then came across this when pulling.

**Comment by tmcconechy** [comment]
Yes, Although not sure how major it is. We did default it to true as thats the most correct from an accessibility standpoint.

But if you want it off you just need to set the option `tabbable: false`

**Comment by awbuboltz** [comment]
Based on my experience with users on an ERP product, this would be.. huge. Heads down data entry people would probably lose their minds over something like this, ha.

We can go through and `tabbable: false` I suppose... does that need to be on every single control?

**Comment by tmcconechy** [comment]
yeah we debated the option - but the correct thing i think is leaning towards accessibility. This failed landmarks VPAT as high priority. So its correct like this but we let you disable it.

Its on searchfield, timepicker, datepicker and lookup now

**Comment by awbuboltz** [comment]
Ok, those three aren't too bad, we should be able to do that easy enough as we have wrappers around them. Thanks!

**Pull request merged**
