### PR TITLE
8639 - Add `buttonsetTextWidth` setting in Modal with tooltip when truncated

### LINKED ISSUE #8639: Modal: Dialog should take into consideration the length of the button text
**Describe the bug**
If we have a modal dialog with a fairly long button text, it would be truncated, this would affect how we display action buttons in a modal with long translations on a different language

**Expected behavior**
We should be considering the length of the button text when we display a modal dialog so that it would not be truncated.

**Version**
- ids-enterprise-ng: 16.4.1

**Screenshots**
modal dialog button

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds `buttonsetTextWidth` setting to set width in buttonset and add tooltip when text is truncated.

**Related github/jira issue (required)**:

Closes #8639 

**Steps necessary to review your pull request (required)**:
- Pull this branch build, and run the app
- Go to http://localhost:4000/components/modal/test-long-buttonset-text.html
- Open the modal
- Notice the first buttonset, text should be truncated
- When you hover, it should show the tooltip

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Seeing a couple problems with the tooltip.

1. It shows both browser and normal one
2. tooltip seems missing some padding on the bottom

Also wondering if we can add "auto" as an example. I think from the original ask we could use that as well and if the text is a little bigger then normal the modal button could adjust to fit the text size?

**Comment by ericangeles** [comment]
@tmcconechy, I don't see the double tooltip on my end.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Another tooltip appeared while doing my test as mentioned by @tmcconechy.

**Steps to reproduce:**
1. Click `Show Modal` button
2. Hover over on first buttonset
3. Click `Save` button
4. Click again the `Show Modal` button
5. Hover over again on first buttonset
6. See error

image


https://github.com/infor-design/enterprise/assets/102151352/8a55341b-1d6d-4731-aac8-a0b70792cd10

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/1baa7909-c319-4523-823b-25acb3167cd1

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:
image

image

**Review by tmcconechy — COMMENTED** [review]
@ericangeles did you add the option to make it `auto` width?

**Comment by ericangeles** [comment]
Yes, @tmcconechy

**Comment by ericangeles** [comment]
@tmcconechy Actually, I wanted to rename the option to `buttonsetTextWidth` since we're targeting the text, not the button, to change the width.

**Review by tmcconechy — DISMISSED** [review]
👍🏻

**Review by glenlieorillo — APPROVED** [review]
Re-tested and approved.

https://github.com/infor-design/enterprise/assets/102151352/667f550f-5974-4f49-8b2a-b9be8ef5d408

**Review by n-ace-ancog — APPROVED** [review]
Still working as expected:

image

image

**Pull request merged**
