### PR TITLE
Chore: Fix Chrome and Stylint

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Set the chrome to use chrome 97 again. Removing the hard coding. In addition i noticed that the style lint plugin no longer worked. Also that the command was not testing every file.

So updated the stylelint version and fixed any errors, ignoring more complicated ones and only fixing safe things. If using visual code with the https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint it will pick this up in your editor so this is recommended.

May also need to update tests - seems like 2 in particular are failing.

**Related github/jira issue (required)**:
N/A

**Steps necessary to review your pull request (required)**:
- all checks pass
- install https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint if you dont have already
- restart and try and edit some .scss files and see errors

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@tmcconechy while using the plugin, am always getting a pop-up error message while typing saying `stylelint: Undefined rule alpha-value-notation`. It's kinda annoying. Have you encountered this?

issue

**Comment by tmcconechy** [comment]
no i didnt did you get it on a specific line? usually the appear in the bottom like this...

Did you try
```
rm -rf node_modules && npmi
```
- then reinstall the plugin and check for updates in visual code and restart it?

**Comment by ericangeles** [comment]
@tmcconechy am still getting the same error after doing that. What version of VSCode are you in?

**Comment by tmcconechy** [comment]
Version: 1.63.2 (Universal) - did u try also updating all extensions?

these are all the extensions i have...
Screen Shot 2022-01-13 at 11 20 10 AM
Screen Shot 2022-01-13 at 11 20 04 AM
Screen Shot 2022-01-13 at 11 19 56 AM

**Comment by ericangeles** [comment]
@tmcconechy Fixed it! It has something to do with another stylelint plugin. I did remove it anyway.

**Pull request merged**
