### PR TITLE
8248 - Update Disabled Days and Legend

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add feature of updating legends and disabled dates on before render of month.

Features: Event `beforemonthrendered` and method `updateMonthDetails()`

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8248

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-disabled-on-render.html
- Go to next month
- It should render the other legend and days

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
One wierd thing is if you go on mobile size you see the mobile legend combined with the "Special Holiday" Legend:

Screenshot 2024-01-18 at 3 41 49 PM

I would fix this by placing the top legend closer so it looks like its part of the other legend or otherwise combining them.. A bit of a gap between them and i think it looks a little strange

**Review by tmcconechy — DISMISSED** [review]

**Review by janahintal — APPROVED** [review]
All months without any legends has 'Special Holiday' legend at the bottom. Also, the days and legends from December 2023 disappears after switching months. 


https://8248-update-disabled-and-legend-enterprise.demo.design.infor.com/components/calendar/test-disabled-on-render.html
image
image
image



Expected: Legends and Days for December should render
image

**Review by janahintal — CHANGES_REQUESTED** [review]
All months without any legends has 'Special Holiday' legend at the bottom. Also, the days and legends from December 2023 disappears after switching months. 


https://8248-update-disabled-and-legend-enterprise.demo.design.infor.com/components/calendar/test-disabled-on-render.html
image
image
image



Expected: Legends and Days for December should render
image

**Review by jbrcna — DISMISSED** [review]
special holiday is displayed even if there is no special holiday event created.
image

holidays/events on December 2023 was removed after switching months.
steps
1. go to next month
2. go back to prev month
3. see error
Large GIF (1606x764)

**Comment by tjamesallen15** [comment]
@janahintal @jbrcna I think this is irrelevant. The example just shows a hardcoded added event on render for the next month. That's why it always display the special holiday below regardless of the month.

See the code below for that test page.
image

**Comment by tmcconechy** [comment]
Ok i agree. Lets just go with this for now. Merging, the remaining issue was just a non implemented extension to the example.

**Comment by jbrcna** [comment]
> @janahintal @jbrcna I think this is irrelevant. The example just shows a hardcoded added event on render for the next month. That's why it always display the special holiday below regardless of the month.
> 
> See the code below for that test page. What it does is replaces it the current settings to a new ones (replacing the previous settings) when the user calls this method. image
> 
> In reality, that code will changed on what the user wants. For that test page, its just a hardcoded one.

okay @tjamesallen15 thanks clarifying. test passed.

**Pull request merged**
