### PR TITLE
4341 - Make Switch Disabled State Contrasted from Unchecked

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Switch disabled visual state was not contrasted vs checked + disabled.

**Related github/jira issue (required)**:

Partially addresses #4341.
(Need to address on `enterprise-wc` as well to close out)

**Steps necessary to review your pull request (required)**:

- pull `4341-disabled-vs-unchecked-switch-contrast`
- run demo server
- visit http://localhost:4000/components/switch/example-index.html?theme=new&mode=light&colors=7928E1
- you should see via the top-right menu that the switch that is checked+disabled has an off-blue tint with grey outline.
- be sure to switch between all 6 variants of: 
-- new/classic + 
-- high contrast/light/dark

image
image
image
image

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Minor suggestions:
- Lets try azure20 instead of 30 (if you tried and think its no good thats fine - its up for debate)
- also in the two dark modes i noticed the bar part is slate but in all other cases its azure

**Comment by rob2d** [comment]
@tmcconechy for the first I actually had tried `azure20` at first. It seemed to blend into the white background quite a bit/low contrast, so that's why I didn't use that in the PR. 

For the second, I think you're referencing dark + disabled + checked?  did this to differentiate from disabled + unchecked.

Actually did try both and realize what you're saying -- the inconsistency felt a little bit dirty there. 

On the second case (dark + disabled + checked), I wasn't sure how to stay in the palette but keep things looking disabled e.g. if the bar was floating, which is similar to the original issue but for dark mode. 

I have found that some people especially WFH environments may have low contrast settings on their monitors or low brightness on non OLED, so the saturation loss for the bar in disabled can help that a tiny bit.

^ thats super subjective though, just a heads up that I did try it/consider it and it's your call with that said to change it or not.

**Comment by tmcconechy** [comment]
OK lets forget about the first part if you tried it and it doesnt seem as good. But this is still an issue:
In the two dark modes i noticed the bar part is slate but in all other cases its azure..

Screen Shot 2021-04-02 at 9 36 34 AM

In all but the dark themes the ---- part of the switch is azure

**Comment by rob2d** [comment]
@tmcconechy that was intentional to differentiate from the non-disabled/active on the dark mode because of the high contrast vs the bg -- but its subjective so will address that.

**Comment by rob2d** [comment]
adjusted:
image

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
Looks great :banana:

**Pull request merged**
