### PR TITLE
SOHO-7799 added tooltip on the dropdown

### PR DESCRIPTION
**Pull request by LarryAmisola**
Added a tooltip option feature in the dropdown component

> **Steps necessary to review your pull request (required)**:
- Open this link http://localhost:4000/components/dropdown/test-multiselect-with-tooltip
- Select any options on the dropdown or you may select all
- Close the dropdown then hover on the numbers selected
- A tooltip containing options/texts that you selected should be display

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@LarryAmisola, looks like several Dropdown tests are failing after this change:  https://travis-ci.com/infor-design/enterprise/builds/73114937

Can you check and see what might be causing it?

**Comment by LarryAmisola** [comment]
Hi @EdwardCoyle , sorry for the late reply. I was out for 2 days. I have pushed my fixes on the dropdown test build. Thanks Ed for reviewing.

**Comment by LarryAmisola** [comment]
Ok Tim, I'll apply the necessary changes. Thanks

**Comment by tmcconechy** [comment]
Do you still have updates coming for this? Hoping we can get this in the release soon for testing.
Just let me know if you need any help?

**Comment by LarryAmisola** [comment]
Fixed is now pushed. 

1. Tooltip is now working both for the dropdown and multiselect. 

http://localhost:4000/components/dropdown/test-multiselect-with-tooltip.html
http://localhost:4000/components/multiselect/example-index.html

2. Start selecting as many items as you can in the dropdown options then close the list. A tooltip will show when a number of selected items is no longer fits in the dropdown

**Comment by tmcconechy** [comment]
Tested manually, passed :check: - Good to merge

**Pull request merged**
