### PR TITLE
8019 - ModuleNav Added click out to collapse

### LINKED ISSUE #8019: MobileNav: Additional Issues (close on mobile / resize)
**Describe the bug**

The mobile nav is missing 2 things which need to be patched in 4.84 and 4.88. Namely:

- on mobile when you click an item it should close
- when you resize the page it should activate the breakpoint change

**To Reproduce**

1. Go to  https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
2. Expand
3. Resize To mobile
4. Should fold to mobile mode
5. Click a menu item -> should close

**Expected behavior**
- `autoCloseOnMobile` - will be set to true and will close the menu when clicked

**Additional context**
MS Teams "Module Nav..." Channel

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added a setting `autoCollapseOnMobile` to close the mobile menu when its on mobile. Not could not reproduce the other part (test steps below). Aiming to patch this into 4.84 and 4.88.

NOTE: New Mobile Behavior

Mobile - Phone -> Can only be hidden or expanded with the fold over
Bigger Than Mobile -> Can only be collapsed or expanded (with no folder over)

**Related github/jira issue (required)**:
Fixes #8019 

**Steps necessary to review your pull request (required)**:
- pull build and start
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- on desktop width, expand with the hamburger button
- try and select menu items and the menu should not collapse
- on mobile width, expand with the hamburger button
- try and select menu items and the menu should collapse
- open a device emulator in chrome tools like iphone XR
- expand the menu item
- switch to landscape mode and it should toggle between mobile mode hanging over with the overlay and non mobile mode
- try resizing between desktop and mobile on regular browser window and when the menu is expanded it should toggle between hanging over with the over lay and not. try various combos

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
After review needs edits

**Review by ericangeles — DISMISSED** [review]
Looks great! I was just wondering, do we still need the `autoChangeBreakpoint` setting? I don't see it in here. Also, just confirming, is the behavior on mobile landscape the same as in a desktop/larger viewport?

**Comment by tmcconechy** [comment]
@ericangeles where do you see the `autoChangeBreakpoint`? I dont see it anywhere either. I did decide to call this `autoCollapseOnMobile` tho.

Yes that behavior is correct on landscape it can show the side bar if the device is big enough.

**Comment by ericangeles** [comment]
@tmcconechy in the ticket issue. It’s indicated there.

**Comment by tmcconechy** [comment]
@ericangeles in this ticket? I still dont see it. But i think i just changed the name to autoCollapseOnMobile

**Comment by tmcconechy** [comment]
@ericangeles in this ticket? I still dont see it. But i think i just changed the name to autoCollapseOnMobile

**Review by ericangeles — APPROVED** [review]

**Comment by janahintal** [comment]
Hi Team, noticed the ff. while testing.

Desktop: 
Hamburger button disappears when in responsive view 
image

Mobile: 
Arrow is pointing the other way 
Steps: 
1. Click the hamburger icon 
2. Play with accordion 
3. Open again and check if the arrow is pointing the right way 
image

**Comment by tmcconechy** [comment]
@janahintal on mobile it will overhang the hamburger and you click out to close so thats as designed.

As for the other issue with the arrow. I tried to replicate but could not. Can u make a new issue?

**Comment by tmcconechy** [comment]
FYI: Waiting for Landmark QA Monday

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
