### PR TITLE
2674 - Fix x-axis labels for small viewport with line chart

### LINKED ISSUE #2674: Homepage: chart y axis description is not visible when widget width is 1 unit
**Describe the bug**
Chart y axis description is not visible when widget width is 1 unit (360px). See screenshots. Something wrong in transform: translate(), like 62 for x translate seems more accurate.

**To Reproduce**
1. Enter longer strings for y axis values in https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-filled

**Expected behavior**
Should be aligned properly and y axis labels should be visible

**Version**
4.20.0

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed x-axis labels were overlapping for small viewport on homepage widget with Line Chart.

**Related github/jira issue (required)**:
Closes #2674

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to http://localhost:4000/components/homepage/test-linechart-x-axis.html
- See the x-axis labels, should not overlap

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by hohnzy** [comment]
My ticket was complaining about y-axis labels. Those are also fixed by this?

**Comment by tmcconechy** [comment]
@hohnzy - we came up with this test page showing a few options https://master-enterprise.demo.design.infor.com/components/homepage/test-linechart-x-axis.html but we didnt see the y axis pushing over in any example we created. So basically could not reproduce that.

**Comment by hohnzy** [comment]
why is the ticket closed by this one then? You could just ask for a data to reproduce. its super easy to make the y-axis label long enough!
image

**Comment by tmcconechy** [comment]
OK make a new issue - that was not mentioned in that way. We copied the values you had and didnt see that massively long labels were added like that. This was not clear to me.

Sorry for not asking... Just wasnt entirely obvious we had a question about that. I'm honestly not sure what we could do to fix it? Maybe truncate your text for you? Lets discuss on a new issue

**Pull request merged**
