### PR TITLE
5544 - Changed line and icon alignment in hierarchy

### LINKED ISSUE #5544: Heirarchy: expand and collapse buttons are missing on rtl
**Describe the bug**

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/hierarchy/example-single.html?locale=ar-sa
2. expand and collapse button are missing and lines are not laid out correctlly

**Expected behavior**
Expand and collapse button should be visible

**Version**

- ids-enterprise: 4.51

**Screenshots**
LTR:
image

RTL:
image

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 91.0.1

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-36710

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated rtl css to align icon and lines in hierarchy.

**Related github/jira issue (required)**:

Closes #5544 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/hierarchy/example-single.html?locale=ar-sa
- Buttons and lines should be laid out correctly

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Looks good to me 👍🏻

**Comment by ericangeles** [comment]
Looks good now! Great work, @yohannahbautista! I just noticed and QAs might find it a bug/issue. The deep level hierarchy doesn't connect to its parent branch. Also saw this from a non-RTL view. Your thoughts @tmcconechy 

hierarchy

**Comment by tmcconechy** [comment]
@yohannahbautista can take a quick look but this was a known issue so it may not be needed as we decided only 3 levels max is the way to go so these are the key examples cc @ericangeles. I.E. we only support 2/3 but left the code in for now so might be fine to leave this as well.

https://main-enterprise.demo.design.infor.com/components/hierarchy/example-single.html
https://main-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html

**Comment by ericangeles** [comment]
Scanning through all the test pages, can we fix also minor positioning here?

http://localhost:4000/components/hierarchy/test-multi-root.html?locale=ar-EG

root

**Comment by ericangeles** [comment]
Also on http://localhost:4000/components/hierarchy/example-stacked.html?locale=ar-EG

Minor UI issues that can fix really quick

caret-1
caret-2

**Review by tmcconechy — APPROVED** [review]
Nice 💯  looks good 👍🏻

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
