### PR TITLE
3918 - Process Indicator Enhancements

### LINKED ISSUE #3918: ProcessIndicator: Visual Enhancements Needed
**Is your feature request related to a problem or use case? Please describe.**
A clear and concise description of what the problem is. [e.g. {Component Name} has a problem when {...}]
Use Case: Requisition Process flows, other approval processes.
Users need a visual way to see where an object is in its approval lifecycle—where has it been; where is it currently; how many steps to go
Users need to see detail information for steps in order to inquire/follow-up with the approver

**Describe the solution you'd like**
A clear and concise description of what you want to happen. [e.g. {Component Name} would work better if {...}]
Using elements of the timeline and process indicator controls to show approval process horizontally

- 100% width, including responsive behavior
- Ability to show statuses via the indicator point (fills, colors, icons, etc)
- Labels on process indicator points
- Datagrid formater version with tooltips (for details of the field)
- Listview version
- Form version

**Describe alternatives you've considered**
Have looked at prev. mentioned existing controls

[LMCLIENT-28994](https://jira.lawson.com/browse/LMCLIENT-28994)
[Wireframe Design](https://github.com/infor-design/enterprise/files/4629075/Process.Indicator.WIP-050720.pdf)

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds enhancements to process indicator to make it responsive, add labels and a content area and support more icons. In addition added a datagrid formatter.

**Related github/jira issue (required)**:
Fixes #3918

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/processindicator
- look at the two new examples with icons
- test this in RTL, and all themes
- go to http://localhost:4000/components/processindicator/example-labels.html
- test this in RTL, and all themes
- resize and only one will be shown at a smaller breakpoint. labels will wrap 
- go to http://localhost:4000/components/datagrid/test-all-formatters.html
- see the new process indicator formatter
- try it in all themes/row sizes

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
This is ready to review however i see some css changes require all datagrid images to be updated so working on that but should not have any great effect

**Comment by deep7102** [comment]
All looks good, just one small thing see icon misaligned in dark mode
http://localhost:4000/components/processindicator/example-index.html?theme=soho&variant=dark&colors=2578a9

image

**Comment by ericangeles** [comment]
I am also seeing the issue that @deep7102 mentioned.

I saw it on
Theme: Subtle | Variant: Dark & High Contrast
Theme: Vibrant | Variant: Dark

**Comment by tmcconechy** [comment]
Missed that comment. Fixing this now.

**Comment by tmcconechy** [comment]
ok @deep7102 all fixed now. I removed the white background as it looked better on dark mode

**Review by deep7102 — APPROVED** [review]
🍌 Looks good!

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
