### PR TITLE
NG1524 - Expandable Rows Remove Custom Width

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix bug with week numbers not aligned properly with first day of week.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1524

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-expandable-row-no-layout.html
- Open `Developer Console`
- Open an expandable row
- Inspect the elements inside it, the outer parent shouldn't have `datagrid-cell-layout`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — DISMISSED** [review]
image

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

`addCellLayoutClass: false`
image

`addCellLayoutClass: true`
image

**Review by jbrcna — APPROVED** [review]
image

**Pull request merged**
