### PR TITLE
7750 - Datagrid Filter List Intermittent

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix datagrid column filter not open after a series of simultaneous clicking of column filters.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7750

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-filter?theme=uplift&variant=light
- Start selecting the filter icon on any one of the column simultaneously.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@tjamesallen15 this looks good but i see a really bad regression with the dropdown icon position. can you add a fix for that too?

Screenshot 2023-08-18 at 11 39 03 AM

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Working now as expected. However, I encountered some issues.

1. The filter and dropdown arrow are overlapped.
2. Border between 'Clear' and 'Apply' is not visible upon hovering the 'Clear' button.

image

image



https://github.com/infor-design/enterprise/assets/102151352/6136d151-bd09-419c-8171-760cbdd3eb7f

**Comment by tjamesallen15** [comment]
> Working now as expected. However, I encountered some issues.
> 
> 1. The filter and dropdown arrow are overlapped.
> 2. Border between 'Clear' and 'Apply' is not visible upon hovering the 'Clear' button.
> 
> image
> 
> image
>  Screen.Recording.2023-08-22.at.4.51.31.PM.mov

Can we just make another ticket for that? It's been existing in https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter?theme=uplift&variant=light prior to my fix so I think the one you found are not related or caused by my fix. :)

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/645b8880-d17d-4a20-8523-4a1418518c51

**Comment by tmcconechy** [comment]
Also i fixed the icon issue on the dropdown. I think i did it here https://github.com/infor-design/enterprise/pull/7816

**Pull request merged**
