### PR TITLE
NG1759 - Fixed selected filters being cleared when changing row size

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed selected filters being cleared when changing row size

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1759

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-filter.html
- Use filters and change row height
- Filters on header should not be cleared

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/b5aa44fb-f63d-4dd9-8be0-bbc7e7a79c2e

**Review by ericangeles — DISMISSED** [review]
Nice fix! 🍌

**Review by jbrcna — CHANGES_REQUESTED** [review]
this seems to not work in Activity(multi) filter
Large GIF (1310x714)

**Comment by ericangeles** [comment]
@jbrcna, can you retest it again?

**Comment by jbrcna** [comment]
> @jbrcna, can you retest it again?

yes absolutely.

**Review by jbrcna — APPROVED** [review]
works as expected. 
image
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
