### PR TITLE
6253 - validation error message toolbar button

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug where toolbar error message still appears after error is removed.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6253

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html
- Click `Show Error`
- Click `Hide Error`
- go to http://localhost:4000/components/datagrid/test-editable-paging-validation.html
- edit a cell and make it blank
- go to page 2 -> error should show on the toolbar

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 the fix i was expecting would be that it doesnt even add the icon to the toolbar anymore. I think it should only add it to tabs (because you can switch the tab and need to know the hidden tab has errors)

But it should also work in this case:
http://localhost:4000/components/datagrid/test-editable-paging-validation.html
- edit a cell and make it blank
- go to page 2

In this case nothing is hidden. So is it possible to change the logic further so it only adds to tabs and datagrid toolbar?

**Comment by tmcconechy** [comment]
There is a couple things wrong here.

1. an error: https://github.com/infor-design/enterprise/runs/6383440778?check_suite_focus=true
2. to clarify on http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html it should not show the icon on the toolbar but on datagrid it still should show it http://localhost:4000/components/datagrid/test-editable-paging-validation.html (on the datagrid its not)
3. on http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html when you click the button the error tooltip is showing in the wrong place?

**Comment by tmcconechy** [comment]
@tjamesallen15 i. think the only thing wrong is something on this example isnt right the error is not showing on the field. This is what i expect:

http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html
- click show error or tab out of the field or tab out to get a validation error
- error should show on the field but not on the toolbar
- hide error should remove it from the field

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Comment by s-werking** [comment]
Hi @tmcconechy @tjamesallen15 , I think there is a misunderstanding about this ticket. I still would like the ability to add an error message to a toolbar to let a user know that they need to select something from a toolbar menu. With these changes in place I am unable to add/remove an error message on a toolbar. Is there any way this can still be an option?

**Comment by tmcconechy** [comment]
The way i thought about it was that if you don't change the page there is no reason to put the validation message in two places (on the field and also on the toolbar). But in the datagrid example it makes sense? Plus we had these problems https://github.com/infor-design/enterprise/issues/6290

What exactly do you want to do? Echo the validation error in two places? Or manually add some error to the toolbar? If its just manually adding an error / maybe we just need an example for that as i dont think echoing the validation message would be the right way to do it.

**Comment by tmcconechy** [comment]
Ok i was'nt aware that worked. @tjamesallen15 can you take another look? I think we should:

- modify / copy the example to just have a show message/hide message button you call that it sets the message on button and that works
- keep what we modified before - as its separate issue 

So just need an example of an error on a button?

**Comment by tjamesallen15** [comment]
> Ok i was'nt aware that worked. @tjamesallen15 can you take another look? I think we should:
> 
> * modify / copy the example to just have a show message/hide message button you call that it sets the message on button and that works
> * keep what we modified before - as its separate issue
> 
> So just need an example of an error on a button?

Will do.

**Pull request merged**
