### PR TITLE
5250 - Update on Card Variations (Single Action)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR is a follow update on Card Variations and Hitboxes

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5250

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
- Check the cards

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Just noticed something i did not see before.

- try tabbing the page
- notice the ... buttons do not have tab stops? they should
- also the "hit box" on the call icon button is backed right up to the edge. should be a bit of space to the end so that looks better

Screen Shot 2021-06-15 at 9 15 28 AM

**Comment by ericangeles** [comment]
To adds @tmcconechy mentioned, also fix,

- the alignment of the button when focused (tabbed) e.g. screenshot above's Tim comment
- The spacing of link when focused (too much i think, and it's too close to the text above)

focus

**Comment by tmcconechy** [comment]
regarding the focus on the links that was the current state https://main-enterprise.demo.design.infor.com/components/hyperlinks/example-index.html but we could reduce the top padding a little if that helps?

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
The only thing im wondering @EdwardCoyle ? Is if this should be a change to all buttons. But i guess that would be too problematic so ok with this for now

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
