### PR TITLE
NG1401 - Added paste event listener for textarea

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added paste event listener for textarea

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1401

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/textarea/example-index
- In 'Notes (maxlength)' textarea, copy-paste the following string:
```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec

rutrum hendrerit nunc sed mollis...
```
- Should not paste the entire string
- Delete a character and type it back
- Should be able to type

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Looks good, one thing saw when text area already have some value, then paste new stuff if its value reach to max. It replace the old content thinking it should let it paste the new content at its caret place then check if need to trim it should begin trim from the end of the value.

**Comment by tmcconechy** [comment]
Seems good - aside from @deep7102 's comment. Maybe its just a logic issue here test/baseline-images/diff/

**Review by deep7102 — APPROVED** [review]
Looks good 🍌

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
Some tests seem a little suspicions. I would check them but feel free to disable if irrelevent.

**Pull request merged**
