### PR TITLE
2281 - Fix some demo app issues with sorting

### LINKED ISSUE #2281: Datagrid: Time filter does not filter correctly client side.
**Describe the bug**

**To Reproduce**
1. Go to 'components/datagrid/test-filter-datetime-client-side.html'
2. Filter by the time field, eg greater than 1:00 AM, 1:00 PM

**Expected behavior**
The filtering is based on just the time 

**Version**
4.19.x

**Screenshots**
image
image

**Platform**
All devices and browsers

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes two minor field qa issues.

**Related github/jira issue (required)**:
Fixes #2281 
Fixes a comment on https://github.com/infor-design/enterprise/issues/2301?email_source=notifications&email_token=AAGGZS5AYZLMH3HQKEGG2VTP3IA4JA5CNFSM4HS4SEV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYBMIVQ#issuecomment-503497814

**Steps necessary to review your pull request (required)**:
- in the console type `localStorage.clear()` and hit enter and then reload the page
- go to http://localhost:4000/components/datagrid/test-save-settings-serverside.html
- type 1.5 the quantity field (decimal will be allowed)
- go to http://localhost:4000/components/datagrid/test-filter-datetime-client-side.html
- should be no alerts on page load

### CODE REVIEW

**Comment by tmcconechy** [comment]
Try resetting the columns. I had this at first and some of the columns may be cached.

**Comment by davidcarlsonberg** [comment]
decimal

**Comment by tmcconechy** [comment]
Try `localStorage.clear()` i had this issue, something is being cached. Now i cant reproduce it

**Comment by janahintal** [comment]
Hi @tmcconechy, decimal is still not working in Windows10 Chrome browser for https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html

**Pull request merged**
