### PR TITLE
6990 - Tabs Module like Tabs

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add setting called `equalTabWidth` to make tabs equal of width.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6990

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs-module/example-index.html
- See that it behaves like normal tabs (scrollable swipe and fade)
- More button same behavior with normal tabs.

New Setting `equalTabWidth`
- Go to http://localhost:4000/components/tabs-module/test-not-equal-width.html
- Similar with normal tabs, module tabs don't have universal tab width size, user can set this to false to trigger (default to true)
- Try adding more tabs until you see the more button
- See that it behaves like normal tabs (scrollable swipe and fade)
- More button same behavior with normal tabs.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 minor thing.

a) can you move the x over a bit so its not so close to the ... text
b) can you add the tooltip setting in example.html so you see the tooltip when its cut off (like http://localhost:4000/components/tabs-module/test-max-width.html)

Opening this up for QA

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

Failing in RTL, observe x icon
image

Also filed a separate issue for classic mode issue. https://github.com/infor-design/enterprise/issues/8606

**Review by janahintal — CHANGES_REQUESTED** [review]
Active Tab looks off in Classic 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Classic RTL**
- Fade looks off 
- x button overlaps text
- Active label is hard to read (both LTR and RTL)

image


image

**Comment by tmcconechy** [comment]
@tjamesallen15 maybe an adjustment there for classic mode? Also can you check the conflict (i introduced with a merge sorry)

**Review by janahintal — CHANGES_REQUESTED** [review]
Looks off in Responsive view
https://6990-tabs-module-like-tabs-enterprise.demo.design.infor.com/components/tabs-module/example-index.html#order-1
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
same issue on my end
image

**Comment by tmcconechy** [comment]
this looks good to me except for one thing (minor) in RTL mode the "fade effect" is showing on the right side when its already scrolled over.

Screenshot 2024-04-18 at 10 50 36 AM

Will just have to get QA to look again @yohannahbautista

**Review by glenlieorillo — COMMENTED** [review]
Looks good on my end, except for the fade effect in RTL mentioned by @tmcconechy. It should be the same as the fade effect in LTR.

**LTR**

https://github.com/infor-design/enterprise/assets/102151352/f0dcd724-8765-4c15-b0c2-29aec3f6ab9c

**RTL**

https://github.com/infor-design/enterprise/assets/102151352/21f020a2-727e-4363-b51e-cb3c7729908f

**Comment by jbrcna** [comment]
> image
> Failing in RTL, observe x icon image
> 
> Also filed a separate issue for classic mode issue. #8606

the issues mentioned  above were now fixed. However, the gradient now looks transparent.
https://6990-tabs-module-like-tabs-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?theme=new&mode=light&colors=default#order-1
image

**Review by janahintal — CHANGES_REQUESTED** [review]
More tabs button looks off in Mobile view 
https://6990-tabs-module-like-tabs-enterprise.demo.design.infor.com/components/tabs-module/example-index.html

image

image

**Review by janahintal — CHANGES_REQUESTED** [review]
Looks off in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?theme=classic&mode=contrast&colors=default 
image

image

image
image

**Comment by jbrcna** [comment]
when you remove the hover on more actions the color becomes white and not visible.
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Fade is still off in smaller viewport.


https://github.com/infor-design/enterprise/assets/102151352/3d9cb01c-a350-4e5f-b9f6-6e6468f85287

**Review by janahintal — CHANGES_REQUESTED** [review]
Issue still exists in responsive view
image
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
In responsive/mobile view, the more button takes more space and may block clicking the next tab

In the image below, tabs width are equal - looks like the button is overlapping on the next tab.
image

In the not equal width, the more button completely block the next tab if the title is long
image

and the previous tab is not visible to be clicked anymore once reached the last tab
image

**Review by janahintal — COMMENTED** [review]
Still looks off in 
image
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/f7ad4447-5fa3-49e0-897e-9cc858090519


https://github.com/infor-design/enterprise/assets/102151352/e72d763c-8c21-485a-a91a-4e506465940b

image

**Review by jbrcna — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Very nice! 👍😎🎉
http://localhost:4000/components/tabs-module/example-index.html
Animation

http://localhost:4000/components/tabs-module/test-not-equal-width.html
Animation

**Comment by jbrcna** [comment]
image
image

Large GIF (1086x678)


Large GIF (1086x678)

**Review by janahintal — APPROVED** [review]
https://www.loom.com/share/7a10b159cf0a486c8469993e6c8a7058?sid=0b696a03-73fd-4a14-9c92-c566494b420b

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@tmcconechy, anything on your end? Looks good to me now.

**Comment by tmcconechy** [comment]
@ericangeles nope im good with it if QA is now.

**Pull request merged**
