### PR TITLE
3718 - Fix datagrid selection issues

### LINKED ISSUE #2230: Datagrid Paging Indeterminate: Checkbox Column Header not working after changing a page
**Describe the bug**
Datagrid Paging Indeterminate: Checkbox Column Header not working properly after changing a page.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html#
2. Select the Checkbox column header
3. Click Next Page button, then Click Previous Page button
4. See issue: Try to select and unselect Checkbox column header, now is not working properly.

**Expected behavior**
Checkbox column header should still work properly after changing a page.

**Version**
- ids-enterprise: v4.17.0 - v4.19.0-beta0

**Screenshots**
paginginde1

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

### LINKED ISSUE #2564: Datagrid Grouping: Misalignment on Totals after personalizing columns
**Describe the bug**
Datagrid Grouping: Misalignment on Totals after personalizing columns.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html
2. Open ... menu then select Personalize Columns
3. Hide the "Customer Id" column
4. See issue: Totals will now be at the leftmost of the row
5. Hide the "Location" column
6. See issue: "Total" labels will be hidden
7. Hide the "First Name" column
8. See issue: Both total and the amounts will be hidden
9. Try hiding other columns as well, different behaviors are encountered whenever a column is hidden

**Expected behavior**
Alignment of total labels should be correct even after hiding columns.

**Version**
- ids-enterprise: v4.6.0 to v4.20.0-beta1

**Screenshots**
If applicable, add screenshots to help explain your problem
image

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

### LINKED ISSUE #3043: Pager: Select all is not working as expected
**Describe the bug**
Pager: Select all is not working as expected 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/pager/example-datagrid.html?theme=uplift&variant=light&colors=0563C2
2. Click Select all 
3. Click Next Page button

**Expected behavior**
All records should be selected

**Version**
Beta 4.23

**Screenshots**
image

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

### LINKED ISSUE #3718: Datagrid: Load data is not properly clearing selected rows
Describe the bug
When calling loadData() to load the next set of records into the datagrid, the method unSelectAllRows() is not correctly clearing the selected rows.  Occurs when the  new dataset is smaller than the existing dataset.   

1. Using the attached test-loaddata-selected-rows.html
2. Select all records by clicking on the checkbox on the grid header
3. Click on the 'Selected Rows' button - notice the count
4. Click on 'Load Next Records' button
5. Notice that no records are visually selected
6. Click on 'Selected Rows' button - notice the count

Expected behavior
When loading a new dataset into the grid, unselected rows is cleared

Version
v4.28.0-dev

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR addresses four issues in datagrid (mostly around selection). See notes below. All these steps to reproduce are covered by tests as well.

**Related github/jira issue (required)**:
Fixes #3718
Fixes #2564
Fixes #2230
Fixes #3043

**Steps necessary to review your pull request (required)**:
**Issue 3718**
- go to http://localhost:4000/components/datagrid/test-loaddata-clear-selected-rows
- hit select all checkbox on the header
- click "show selected row count" - should show 7
- click "load other records"
- click "show selected row count" - should show 0

**Issue 2564**
- go to http://localhost:4000/components/datagrid/example-grouping-totals.html
- try and hide some columns in the personalization dialog
- 1) some columns that cannot be hidden are disabled
- 2) you can now hide columns without the layout borking

**Issue 2230**
- go to http://localhost:4000/components/datagrid/example-paging-indeterminate.html
- select all on page one
- go to page two (next button) -> no rows should be selected changing page
- select all on page two
- go to back to page one (next previous) -> no rows should be selected changing page

**Issue 3043**
- go to http://localhost:4000/components/datagrid/example-paging.html
- select all in page one
- go to page two -> header checkbox should be unchecked
- go to back to page one -> header checkbox should be checked

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Looks good to me. Just an observation on this,

I believe this is the correct behavior
- Go to http://localhost:4000/components/datagrid/test-loaddata-clear-selected-rows
- Hit select all checkbox on the header
- Click `Load Other Records` button
- Two items will show unchecked
- Then click `Load Original Records` button
- It will show the original records unchecked

But testing this one,
- Hit select all checkbox on the header
- Click `Load Other Records` button
- Hit all checkbox on the header
- Then click `Load Original Records` button
- The original records were checked (I guess it shouldn't?)
- Click `Show Selected Row Counts` -> Will prompt 0 count

**Comment by EdwardCoyle** [comment]
@tmcconechy Everything else looked good but I'm curious about the one @ericangeles found too.

**Comment by tmcconechy** [comment]
Yeah thats another variation on the original problem. Good catch @ericangeles im taking a look

**Comment by tmcconechy** [comment]
@EdwardCoyle and @ericangeles - i fixed the last issue you noted

**Comment by ericangeles** [comment]
Sweet! 🍌

**Pull request merged**
