### PR TITLE
3747 - Tooltip on Load

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add support setting for the tooltip to show on load in slider.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/3747

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/slider/example-tooltip-onload-and-textbox.html
- See the `tooltip`
- Scroll the `sidebar` to see the `textbox` changing value.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
I'm not much sure if I got this correctly. Feel free to comment here. I'm thinking at first to make a setting for the textbox but I rather did it only in the example by listening to the events in the slider.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Can you adjust the centering so its centered as in the design:

Screen Shot 2021-11-18 at 9 09 01 AM

Also the design shows it enabled for entering (but i suppose thats possible either way).

And maybe we can link the input in the component by an id setting so the updating happens as part of the component?

**Comment by tjamesallen15** [comment]
> Can you adjust the centering so its centered as in the design:
> 
> Screen Shot 2021-11-18 at 9 09 01 AM
> 
> Also the design shows it enabled for entering (but i suppose thats possible either way).
> 
> And maybe we can link the input in the component by an id setting so the updating happens as part of the component?

Thank you for the comments @tmcconechy

**Review by tmcconechy — COMMENTED** [review]
Looks good. But one more thing is i think if you type in the input the expectation is that it would update the slider. Also you could put a number mask on the input.

Thanks James 👍🏻

**Review by EdwardCoyle — COMMENTED** [review]
@tjamesallen15 This looks really clean!  One thing -- I think before we merge the keyboard usability of the input needs some tweaking:

IDS-Enterprise

Could be we try one of the items below:

**Comment by tjamesallen15** [comment]
Is this okay now, @EdwardCoyle ? :)

**Comment by EdwardCoyle** [comment]
@tjamesallen15 It looks a lot better but I think there's one more piece missing.  When you Tab/Shift+Tab away from the input field, it doesn't commit the value (which I'd expect), but the value in the field becomes mismatched from the value on the slider.  This also happens when the field is blurred, or the user clicks outside the field.  

I think in these cases, the input field should set itself back to the slider's current value.

IDS-Enterprise-_1_

**Comment by tmcconechy** [comment]
@tjamesallen15 i took another look as i saw additions. But the only issue i still see is that if i type in the input and tab it doesnt update the slider.

**Comment by tjamesallen15** [comment]
> @tjamesallen15 i took another look as i saw additions. But the only issue i still see is that if i type in the input and tab it doesnt update the slider.

I've just followed what @EdwardCoyle said that it should revert back to old value. Should I update it once tabbed out?

**Comment by tmcconechy** [comment]
I think we did say the same thing. I.E. just go only in the input and type "50" then hit enter and it updates but go only in the input and type "50" then hit tab and it doesnt

**Comment by tjamesallen15** [comment]
> I think we did say the same thing. I.E. just go only in the input and type "50" then hit enter and it updates but go only in the input and type "50" then hit tab and it doesnt

okay tim! my bad :)

**Review by tmcconechy — APPROVED** [review]
LGTM now 🚀

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Pull request merged**
