### PR TITLE
3702 - Add support to ellipsis for yaxis labels with bar and line chart

### LINKED ISSUE #3702: Bar/Line: If using long y axis labels the chart will render poorly
**Describe the bug**
When y axis labels are very long. The text is cut off. Should come up with a solution. This was a point that was mentioned on https://github.com/infor-design/enterprise/issues/2674 but missed when fixing that issue.

Also in some cases in the bar chart if the data valueis longer (say 800000) the axis will move too far to the left side.

**To Reproduce**
1. Go to http://localhost:4000/components/bar/example-index.html
2. Edit the chart data in this example to the code below

**Example One Bar Chart**
```
<script id="test-script">
$('body').on('initialized', function () {

 var dataset = [{
      data: [{
          name: 'Category AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
          value: 373,
          url: 'test',
          tooltip: 'Tooltip by Data <br> Component A <br> Information'
      }, {
          name: 'Category B',
          value: 372
      }, {
          name: 'Category C',
          value: 236.35
      }],
      name: ''  //Can be optionally passed in makes less sense with one: Group 1
    }];

  $('#bar-example').chart({type: 'bar', dataset: dataset, animate: false});

});
</script>
```

**Example Two Line Chart**
```
lineData = [{
  data: [
    {name: 'Jan | 2018', value: 12000000000000, depth: 4},
    {name: 'Jan | 2018', value: 11},
    {name: 'Jan | 2018', value: 14},
    {name: 'Jan | 2018', value: 10},
    {name: 'Jan | 2018', value: 14},
    {name: 'Jan | 2018', value: 8}
  ],
  name: 'Component A',
  id: '1'
}, {
  data: [
    {name: 'Jan', value: 22},
...
```

**Expected behavior**
Case One (line):
We need to discuss what an appropriate fix would be. ideas:
- Show the first N characters that will fit and truncate to ellipsis at a max. Show tooltip for ellipsis text
- Implement 3 size labels (long, short, abbreviated) - like we have in other charts

Case Two (Bar):
- check the code so that the `g` tag doesnt shift over

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**
Screen Shot 2020-04-02 at 9 57 20 AM

**Alternatives/Workarounds**
- Just use a shorter label in the code when sending it in that will fit.

**Platform**
 - Any

**Additional context**
Originally mentioned on https://github.com/infor-design/enterprise/issues/2674
cc @hohnzy

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added support to ellipsis for yaxis labels with Bar and Line Chart.

**Related github/jira issue (required)**:
Closes #3702

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4000/components/bar/test-axis-y.html
- http://localhost:4000/components/line/test-axis-y.html
- Resize browser window to small viewport
- See the y-axis 1st label, should show `...` three dots ellipsis
- Hover on it, tooltip should show with full content for this label
- Triple click on `...` three dots, should select the text
- Right click then copy, or use keys `cmd + c` to copy
- Paste copied content to somewhere
- See it should be full content for this label

FYI:
- Copy/paste feature is not supported in IE11

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@hohnzy would you be willing to test this branch on your app scenarios as well. Thanks

**Comment by hohnzy** [comment]
@tmcconechy can I somehow test with ids-ng repository?

**Comment by tmcconechy** [comment]
Yes, usually what i do is..
1. clone proj https://github.com/infor-design/enterprise
1. switch to this branch `3702-bar-line-chart-yaxis`
1. `npm i && npm run build`
1. clone proj https://github.com/infor-design/enterprise-ng
1. go on branch master (default)
1. `npm i && npm run build`
1. copy contents of `dist` from folder where you cloned in step 1
1. past contents to `node_modules/ids-enterprise` to folder where you cloned in step 4

Aside from that i can make a new dev build but this can only take place after i merge this all, so test after the fact

**Comment by deep7102** [comment]
@tmcconechy Updated now, for tooltip position to be adjusted.

**Comment by EdwardCoyle** [comment]
@hohnzy assuming you're on a linux/mac machine, and your `enterprise` and `enterprise-ng` projects are in the same parent folder, you can also do a symbolic link:

```
rm -rf enterprise-ng/node_modules/ids-enterprise
ln -s enterprise/ enterprise-ng/node_modules/ids-enterprise
```
This way when you rebuild the enterprise project it will get picked up in future enterprise-ng builds (until you do a fresh install).

**Comment by hohnzy** [comment]
Can't succesfully finish npm install:
image

**Comment by tmcconechy** [comment]
We are still on node 10 as of now suggest version for example version 10.16.3 you can use https://github.com/coreybutler/nvm-windows to swap node versions easily (I can see in the error u are on node 12.x)

**Pull request merged**
