### PR TITLE
Misc - Fix datepicker to work with AM/PM in locales and with the today button

### LINKED ISSUE #3202: Datepicker: Today is changing PM/AM value
**Describe the bug**
Hi! 
We want a way to allow the user to set the time they want and then select todays date by clicking Today if that is wanted. This works fine for some time periods (especially in he morning) but not for 12:00 - 12:59 **AM** when it changes to 12:XX PM And for 1:00-11:59 **PM** which changes to XX:XX **AM**. 

**If the user click the current date, then it works fine. It is just when clicking Today that this issue occur.**

**Note** that we do not want it to choose current time as in this issue https://github.com/infor-design/enterprise/issues/2575. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/test-12hr-time.html
2. Click on the datepicker
3. Change the time to "11:55 AM"
4. Click Today
5. Note that the time remains 11:55 (which is what we want)
6. Click on the datepicker icon again 
7. Change the time to "12:10 AM"
8. Click Today
=> Time changes to 12:10 **PM**
9. Click on the datepicker
10. Change the time to "6:55 PM"
11. Click Today
=> Time changes to "6:55 **AM**"

**Expected behavior**
I think this could be handled differently depending on the value of useCurrentTime option,  If useCurrentTime is false I do not think current time should be used while clicking Today (If useCurrentTime is true then Today should change to current time). 

When "useCurrentTime" setting is false, the Time should not change at all when clicking Today (just as when you click todays date). So the "12:XX AM" should stay "12:XX **AM**" after clicking Today and PM should stay PM for all afternoon values.

**Version**

- ids-enterprise: v. 4.23.0

**Screenshots**
image

image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Currently the sample in the steps to reproduce does not have the "useCurrentTime" option set, but I think it should have been false by design according to spec? I've also tried to add the "useCurrentTime" option and set it to false. But still have issues with AM/PM changes.

### LINKED ISSUE #3470: Datepicker: Korean doesn't work in datepicker
**Describe the bug**
When I select a time in the datepicker (Or click Today) and then unfocus the field the field becomes invalid.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=ko-KR'
2. Click on the calendar icon in the second field
3. Click Today
4. Click outside the field (not in another field, for some reason it doesn't validate then)
5. Notice that it becomes invalid.

**Expected behavior**
The field should keep the format (or have the correct format which I do not know) and it should not be invalid

**Version**

- ids-enterprise: 4.23 but reproducible in 4.25.2

**Screenshots**
image

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

### LINKED ISSUE #3473: Datepicker: Chinese cannot be used in datepicker with time
**Describe the bug**
When I select a time in the datepicker (Or click Today) and then unfocus the field the field becomes invalid.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=zh-CN' or 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=zh-TW'
2. Click on the calendar icon in the second field
3. Click Today
4. Click outside the field (not in another field, for some reason it doesn't validate then)
5. Notice that it becomes invalid.

**Expected behavior**
The field should keep the format (or have the correct format which I do not know) and it should not be invalid

**Version**

- ids-enterprise: 4.23 but reproducible in 4.25.2

**Screenshots**
image

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
This issue can be related to https://github.com/infor-design/enterprise/issues/3470
All these 3 language codes (ko-KR, zh-Ch and zh-TW) gets the same error.

### LINKED ISSUE #3474: Datepicker: AM/PM doesn't work correctly for locale hi-IN
**Describe the bug**
When I try to switch between AM and PM in Hindi it changes back to a value dependent on the time. 

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=hi-IN'
2. Click on the calendar icon for the second datepicker that will use the time 12:00
3. For the am/pm dropdown select the first option
4. Click The apply button
5. Notice that the time is still shown correctly with the correct am/pm option
6. Click outside of the field
7. Notice that the am/pm value changes (Expected result: The value is not changed)
8.  Click on the calendar icon for the third datepicker that will use the current time
9. For the am/pm dropdown select the second option
10. Click the apply button
11. Notice that the time is still shown correctly with the correct am/pm option
12. Click outside of the field
13. Notice that the am/pm value changes (This could perhaps depend on if it is currently am or pm time? I'm in pm for my time zone when testing?) (Expected result: The value is not changed)

**Expected behavior**
The am/pm value should not change in step 7 and 13

**Version**

- ids-enterprise: Found in v 4.25.2

**Screenshots**
Testing datepicker hi-IN

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

There was a series of related issues on setting AM/PM. In respects to using some custom locales and having it remember the AM and PM in the time.

**Related github/jira issue (required)**:
Fixes #3470
Fixes #3473
Fixes #3474
Fixes #3202

**Steps necessary to review your pull request (required)**:
**Issue 3470**
- go to http://localhost:4000/components/datepicker/example-timeformat.html?locale=ko-KR
- click the icon in the second field
- click today
- tab out of the field
- should be a valid date/time now

**Issue 3473**
- go to http://localhost:4000/components/datepicker/example-timeformat.html?locale=zh-TW
- click the icon in the second field
- click today
- tab out of the field
- should be a valid date/time now

**Issue 3474**
- go to http://localhost:4000/components/datepicker/example-timeformat.html?locale=hi-IN
- click the icon in the second field
- click today
- tab out of the field
- should be a valid date/time now
- reopen the dropdown and select "PM" (second option) and hit apply
- should be a valid date/time now with selected /localized values for AM/PM

**Issue 3202**
- go to http://localhost:4000/components/datepicker/test-12hr-time.html
- click the icon and open the calendar
- click today (time is 12:00 AM)
- open the calendar again
- set time to anything (12:00 PM was a problem)
- click today -> the selected time should work
- try to click another date and the try the thing with today again and make sure the time stays and the date changes

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
All looks good, see one thing getting js error
- http://localhost:4000/components/datepicker/example-timeformat.html?locale=hi-IN
- click the icon in the second field
- click today
- tab out of the field
- should be a valid date/time now
- reopen the dropdown and select "PM" (second option) and hit apply
- tab out of the field
- see console the error

**Comment by ericangeles** [comment]
I'm still able to replicate the issue in period. (Not changing the AM to PM when selecting it)
- Select other date
- Change time
- Select PM 


I also seeing what @deep7102 mentioned above.

**Comment by tmcconechy** [comment]
Can you be more specific @ercangeles ? Which page? Select which date first before going to pm? Thought this was working

**Comment by ericangeles** [comment]
> Can you be more specific @ercangeles ? Which page? Select which date first before going to pm? Thought this was working

Sorry, my bad @tmcconechy. 

Go to
- http://localhost:4000/components/datepicker/example-timeformat.html?locale=ko-KR
- Open the date picker
- Select other date then change the hour to 8, select 오후
- Click 적용
- Then click outside of the input field or unfocus it

It is still changing to 오전 instead of 적용

**Comment by tmcconechy** [comment]
OK thanks guys, pushed fixes for those two issues.

**Comment by ericangeles** [comment]
The first issue that I saw is fix now. But I see another one.

Go to
- http://localhost:4000/components/datepicker/example-timeformat.html?locale=zh-TW
- Open the datepicker in the second field
- Select `9` in Hour, then select the period `下午`
- Click the `Apply/应用` button
- Then tab out
- See the console. There's an error, stating `setHours` undefined.
- Also, the value is incorrect. Instead `2020/3/4 上午9:00` it outputs `2020/3/4 上午90:0` and getting error message.

See also the capture video


dp_err

**Comment by tmcconechy** [comment]
Good catch @ericangeles . Fixed this as well.

**Comment by tmcconechy** [comment]
Everyone was approved before merging a conflict - so this is good to go

**Pull request merged**
