### PR TITLE
7769 - Updated selected header text color

### LINKED ISSUE #7769: Accordion: Header text is not visible when expanded
**Describe the bug**
Header text is not visible when expanded.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html
2. Click on 'Notes'
3. Click on 'Skills'
4. Click on 'Compliance Training'
6. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/6d276970-8755-41f4-b492-511f79315fd6

**Platform**
 - All major browsers

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated selected header text color

**Related github/jira issue (required)**:

Closes #7769 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/accordion/example-disabled.html
- Click on 'Notes', then 'Skills'
- Text should be seen

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
Merging to test updates to main are working. But please confirm on main or local @glenlieorillo

**Review by glenlieorillo — COMMENTED** [review]
Hello @tmcconechy, working now as expected in local. However, the bug still exists in main (Light Mode).

http://localhost:4000/components/accordion/example-disabled.html

https://github.com/infor-design/enterprise/assets/102151352/35479398-282b-4993-976b-1d341ab59054

https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html


https://github.com/infor-design/enterprise/assets/102151352/1f7fbfe4-606b-48b6-9045-c9262316755b

**Comment by ericangeles** [comment]
@tmcconechy, I think we need to talk to Artem again about the issue in every environment.

**Comment by jbrcna** [comment]
issue still exist

image

see also classic light
image

**Comment by tmcconechy** [comment]
@jbrcna sorry i have @corpulent looking at the updating problem. Just check main for now or the issue specific branch and we will have it fixed soon enough. Thanks!

**Pull request merged**
