### PR TITLE
6113 - Donut Chart Legends Overlapping

### LINKED ISSUE #6113: Legends of Donut chart are overlapping with Legend color when legends placed at bottom.
**Describe the bug**
Legends of Donut chart are overlapping with Legend color when legends placed at bottom. This issue is reproduced when window is resized/responsive.

**To Reproduce**
Kept code in stackblitz ,here is the url.
https://stackblitz.com/edit/ids-quick-start-1301-dn2uzm?file=src%2Fapp%2Fapp.component.html

**Expected behavior**
Legends should not overlap with legend color.

**Version**

- ids-enterprise: v4.58.3

**Screenshots**
image

**Platform**
 - Infor LN
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 98.0.4758.82 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Legend text is colliding with color blocks.

**Related github/jira issue (required)**:
Fixes #6113 

**Steps necessary to review your pull request (required)**:

Visit http://localhost:4000/components/donut/example-legend-bottom.html
Resize browser and notice legend text will not collide with color blocks.

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@davidcarlsonberg while fixing this can you center up the text with the swatch (just to be perfect :)

Screen Shot 2022-03-03 at 10 18 52 AM
h

**Comment by davidcarlsonberg** [comment]
Not sure what is going on with this test. It passes in my local travis-debug docker container. Any ideas?

**Comment by tmcconechy** [comment]
@davidcarlsonberg it looks like because you change the legend those images need updating. Sometimes i will do this.. To clean the docker image to get things in sync/versions ect

```
  rm -rf node_modules
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo dpkg -i google-chrome*.deb
  rm google-chrome-stable_current_amd64.deb
  npm i
```

**Comment by davidcarlsonberg** [comment]
Oh I see, the Protractor tests are still running for visual regression. Now that these have been moved over to Puppeteer, can we remove the Protractor ones?

**Comment by tmcconechy** [comment]
Yep if they are covered in puppetteer we dont need both..

**Comment by davidcarlsonberg** [comment]
The homepage this is failing on in CI is passing in my local `travis-degug` container.

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
Looks good @davidcarlsonberg

**Pull request merged**
