### PR TITLE
5346 - Added tooltip in targeted achievement and completion chart

### LINKED ISSUE #5346: TargetedAchievement: Requesting tooltip feature
**Is your feature request related to a problem or use case? Please describe.**
Tooltip on 'targeted-achievement' chart is not working. See https://stackblitz.com/edit/ids-quick-start-940-dlsyjf

**Describe the solution you'd like**
 We need tooltip on this 'targeted-achievement' chart .

**Describe alternatives you've considered**
No.

**Additional context**
We work on Infor LN Homepage Widgets.

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added tooltip in targeted achievement and completion chart (changes in targeted also change completion). Tooltip text can be assigned using property "tipText" when creating the chart, default is the bar values. Tooltip implementation is based on progress bar component: http://localhost:4000/components/progress/example-index.html

**Related github/jira issue (required)**:

Close #5346 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/targeted-achievement/example-index.html
   - Mouse over the colored bars
- Go to: http://localhost:4000/components/completion-chart/test-updated.html
   - Mouse over the colored bars
   - Click update
   - Mouse over the spent bar

**Included in this Pull Request**:
- [ ] A note to the change log.
- [ ] Updated baseline images

### CODE REVIEW

**Comment by tmcconechy** [comment]
I think this could work but im wondering if they meant that they could put any text in the tooltip (so pass a tooltip in the dataset or show percent by default).

Also i think the tooltip placement seems a bit incorrect? Should we try and center it over the section.

Screen Shot 2021-08-31 at 10 35 37 AM

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Lets go ahead and make it work that

- it centers on the section hovered
- it shows the percent but if they pass in "tooltip: 'something'" on the datapoint it shows that

**Comment by tmcconechy** [comment]
@yohannahbautista this looks good now 👍🏻  just wondering about these tests https://github.com/infor-design/enterprise/pull/5563/checks?check_run_id=3504942583#step:12:3036

I wouldnt think the images would change for this. But maybe they just need an update?

**Review by ericangeles — APPROVED** [review]

**Comment by bveerabathini** [comment]
Hi Tim,
When the support is extended to angular component?

**Comment by tmcconechy** [comment]
@ericangeles @yohannahbautista We should add this to the completion chart example in 

But i think reviewing this if we change `tipText` to `tooltip` then the type is already thee in SohoChartData types. So maybe make a change for that and this would also make it more consistent.

https://github.com/infor-design/enterprise/pull/5563/files?file-filters%5B%5D=.html&file-filters%5B%5D=.js&file-filters%5B%5D=.png#diff-6e7ed319a7da291c55d71a30710058a009a6de21998b80d7ad7bb34c9c5c534fR315

But should probably try it in the NG as well.

**Comment by ericangeles** [comment]
@yohannahbautista I'll let you do the adjustments and add examples to the NG wrapper.

**Pull request merged**
