### PR TITLE
4930 - Colorpicker Text Newline in min views

### LINKED ISSUE #4930: Colorpicker: Text and dropdown icon are hidden in small modal/container
**Describe the bug**
Observed that colorpicker's text and dropdown icon became hidden when the modal/container width became smaller, it is also not possible to open the colorpicker menu to select color.

Colorpicker dropdown icon is missing when scrollbar is display in the dialog

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-sizes'
2. Resize the browser to the smallest width.
3. Zoom in few times. (browser zoom)

**Expected behavior**
The colorpicker retains the text and dropdown icon.

**Version**
- ids-enterprise: 4.37.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10, Big Sur
 - Browser Name: Chrome, Safari
 - Browser Version: Chrome/Version 88.0.4324.190 (Official Build) (64-bit), Safari/Version 14.0.3 (16610.4.3.1.4)

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes an issue explained in #4930 where text cuts off in color picker when window is resized. Also improves how resizing is handled in these edge cases (a bit).

**Related github/jira issue (required)**:
Closes #4930

**Steps necessary to review your pull request (required)**:

- Visit http://localhost:4000/components/colorpicker/example-sizes.html#maincontent
- Example of issue:
4930-responsiveness-issue
- Example of fix to verify:
edge-case-color-picker-responsiveness

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

### CODE REVIEW

**Comment by rob2d** [comment]
I think the changes to try to improve the layout may have triggered visual regression errors -- not quite sure how to deal with those yet but can check it out tomorrow AM.

**Comment by tmcconechy** [comment]
Yeah probably the color picker ones need updating - when you get your mac you can follow these steps https://github.com/infor-design/enterprise/blob/master/docs/TESTING.md#working-with-visual-regression-tests

**Comment by tmcconechy** [comment]
@rob2d looks like we might need a quard around the code on https://github.com/infor-design/enterprise/pull/5005/checks?check_run_id=2204078241#step:9:1239 - the new event handler is giving an error. Maybe?

```
    this.icon.parent()?.on('click.colorpicker', () => this.toggleList());
    this.swatch?.on('click.colorpicker', () => this.toggleList());
```

**Comment by rob2d** [comment]
@tmcconechy not quite sure what a quard is but will check this out thanks. Was following the steps for regression testing and found there were other dev tools needed this AM for running those which I was setting up.

**Comment by tmcconechy** [comment]
By guard i just mean some coding protection around it being null...

```
if (not null)
  do this
```

But in this case we can maybe use the the optional chaining thing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Review by tmcconechy — APPROVED** [review]

**Comment by rob2d** [comment]
@tmcconechy thanks for the help so far. Unfortunately am still having issues to upload the visual regression tests. Mentioned this in PM but: 

Followed all of the steps mentioned in the document @ https://github.com/infor-design/enterprise/pull/5005#issuecomment-808319844. When running the e2e via docker command prompt (making sure node_modules are clear, with latest Chrome binary, etc), certain tests are repeatedly failing. I had hoped to just push the changed images to git since all are running, but the files do not get added to the local `test/baseline` directory.

Stumping me at the moment so may move on to other issues in the meantime.

**Comment by rob2d** [comment]
update: after a small adventure sorting out docker and some quirks such as npm + vscode terminal, found that style testing was currently in a bad state (previously known issue).

Am up to speed now though and will try to generate the new baselines tomorrow or when things are good.

**Review by tmcconechy — APPROVED** [review]

**Comment by rob2d** [comment]
Thanks for the updated images @tmcconechy . Passed (🎉)

**Comment by tmcconechy** [comment]
BTW didnt mean to add that doc change - but its valid. I was testing the git command password and it got in but its fine so i left it.

**Pull request merged**
