### PR TITLE
7542 - Add new design with splitter

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added new design changes and more examples with splitter.
Designs: https://www.figma.com/file/7ekYTGePkNrgm4zCeyEi1b/Splitter?type=design&node-id=0-1&t=dT6W3AOyTaghwlKv-0

**Related github/jira issue (required)**:
Fixes Half of #7542
Fixes https://github.com/infor-design/enterprise/issues/7322
Fixes https://github.com/infor-design/enterprise/issues/7027 (no collapse button)

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- http://localhost:4000/components/splitter/example-index.html
- http://localhost:4000/components/splitter/test-horizontal.html
- See new design should match

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — DISMISSED** [review]

**Review by jbrcna — COMMENTED** [review]
https://7542-splitter-design-change-enterprise.demo.design.infor.com/components/splitter/test-content.html - notice that there are 2 scroll bars
image

https://7542-splitter-design-change-enterprise.demo.design.infor.com/components/splitter/example-searchfield.html - there's a bit of a delay when dragging to the left

**Comment by tmcconechy** [comment]
@jbrcna fixed those two items. The search field one isnt perfect but not a priority. Fixed the animation and the double scroll bar

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Splitter is cut off.

https://7542-splitter-design-change-enterprise.demo.design.infor.com/components/splitter/test-content.html


https://github.com/infor-design/enterprise/assets/102151352/79946da7-d74f-4738-9af9-167e36f4ba09


image

image

**Comment by jbrcna** [comment]
> @jbrcna fixed those two items. The search field one isnt perfect but not a priority. Fixed the animation and the double scroll bar

the scroll bar is now fixed. however, the [searchfield EP ](https://7542-splitter-design-change-enterprise.demo.design.infor.com/components/splitter/example-searchfield.html)is missing.
image

Also, the line  (div) is not full or cut.
image

**Comment by tmcconechy** [comment]
@glenlieorillo @jbrcna 
1. I removed the search example (check the links in the PR comments again). Not going to support that exact example right now
2. Fixed the issue with the cut off splitter

@talkaboutdesign
Fixed the size issues https://github.com/infor-design/enterprise/issues/7542#issuecomment-1589959089 my mistake.

Have yet another look please

**Review by jbrcna — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Comment by talkaboutdesign** [comment]
Some minor feedback. @tmcconechy 

We should have min and max size for page sections that splitter can size to. In general I don’t think we need to do many different examples for this control. Vertical and horizontal examples with some dummy content should be enough. 


Remove this example: 
https://fix-splitter-enterprise.demo.design.infor.com/components/splitter/test-modal.html

Is there a way to combine these two examples: 
https://fix-splitter-enterprise.demo.design.infor.com/components/splitter/test-scrollbar-display.html

iFrame example, while dragging the content becomes invisible? Is this intentional?
https://fix-splitter-enterprise.demo.design.infor.com/components/splitter/test-iframes.html

Fix size parent (issue with button peaking under the splitter). 
This should never happen as splitter is supposed to be a barrier and a divider for the page. 
https://fix-splitter-enterprise.demo.design.infor.com/components/splitter/test-fixed-size-parent.html

**Comment by tmcconechy** [comment]
@talkaboutdesign ok...

1. we have a maxWidth but should have a minWidth too. I'll have to add it later. The newer component is better done and i'll make sure its there
2. Removed examples test-modal.html test-iframes.html and test-fixed-size-parent. They are all odd test cases that dont need to be there and could be brought back if needed.
3. The iframes one had to do that due to the way they work. But now its gone from site
4. What do you want to combine https://fix-splitter-enterprise.demo.design.infor.com/components/splitter/test-scrollbar-display.html with. i kept it as it seemed an ok example. I will make better examples on the new component. Just getting this one in a decent place for now

**Pull request merged**
