### PR TITLE
1742 - Calendar: missing field validation 

### LINKED ISSUE #1742: Calendar: Missing field validation
**Describe the bug**
The validator will not run any rule when there is any item visible on the page with the class "calendar-popup" and the Calendar modal has this class. This then means you can not set any validation like a field is required within this modal.

This requires an alteration to the page to add the required validation to a field eg subject

**To Reproduce**
1. Go to '/components/calendar/example-index.html'
2. Clear the value from the subject
3. The required message should show

**Expected behavior**
This modal should allow for validation rules to be added.

**Version**
v4.17.0

### PR DESCRIPTION
**Pull request by marknolaninfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Allow Validation when entering or modifying a calendar event. 

**Related github/jira issue (required)**:
Closes #1742 

**Steps necessary to review your pull request (required)**:
1. Goto 'http://localhost:4000/components/calendar/example-index.html'
2. Double Click on a date to add an event 
3. type an invalid date in to the datepicker eg 33/33/3333

Also re-test 'http://localhost:4000/components/modal/example-validation.html'

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Not sure if its just me doing something wrong but i pulled the branch and i did not see the validation when i typed an invalid date. I do see the changes on the markup but the validation error isnt showing up.

**Comment by tmcconechy** [comment]
I’m still not seeing any message popup when I pull and run this branch. Confused 😐 as to why that is...

**Comment by marknolaninfor** [comment]
@tmcconechy 

What browser are you using? Assume safari on a Mac 

I removed the styling change that corrected the position in case that caused the issue.

**Comment by tmcconechy** [comment]
@EdwardCoyle please test again. Looks like @marknolaninfor  fixed your comment.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA failed. The Cancel and Submit are not appearing correctly.  Please see screen shot attached.  This was tested using URL: http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
Calendar Submit and Cancel button

**Comment by tmcconechy** [comment]
@CindyMercadoReyes Can you add any more info? I tested this quickly on http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html in mac chrome and did not see any issue. i did this

- dbl click a day so the calendar popups up
- type a value like 3/33 in and tab out of the date field

**Pull request merged**
