### PR TITLE
8510 - Add timeline fixes

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Additional fixes to the timeline layouts.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/8510
Fixes https://github.com/infor-design/enterprise/issues/8586

**Steps necessary to review your pull request (required)**:
- check http://localhost:4000/components/timeline/example-index.html and layout should look nice again
- check http://localhost:4000/components/timeline/example-index.html?locale=ar-SA and last item should connect
- retest  http://localhost:4000/components/timeline/test-on-widget.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image
image

image

image

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Issue still exists.

**Mac Chrome - Classic**
image

image

**Mac Firefox - Classic**
image

**local-host**
image

image

**Comment by tmcconechy** [comment]
@janahintal @glenlieorillo @jbrcna 

Please check again, i fixed the issue in classic

**Review by janahintal — APPROVED** [review]
Thanks Tim, looks good on both classic and new theme.  

image
image

image
image

**Review by ericangeles — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by jbrcna — CHANGES_REQUESTED** [review]
in smaller viewport the line at the bottom is doubled.
image
in firefox the line is not fully connected.
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Line is doubled in mobile view.

- Galaxy Z Fold 5

image

- iPhone 15 Pro Max
image

**Review by janahintal — APPROVED** [review]
image
image
image
image

**Review by glenlieorillo — APPROVED** [review]
image

image

image

**Comment by jbrcna** [comment]
> in smaller viewport the line at the bottom is doubled. image in firefox the line is not fully connected. image


$\textcolor{green}{\textsf{Double line is now fixed.}}$
image


However, $\textcolor{red}{\textsf{the issue in firefox still exists}}$ 

image

**Review by tmcconechy — COMMENTED** [review]
@jbrcna im not seeing the issue in Firefox (or its so minor i cant tell). I suggest we make a new issue if you see anything more thats very obvious?

**Pull request merged**
