### PR TITLE
5062/5063 - Time/Datepicker icon placement improvements [v4.50.x]

### LINKED ISSUE #5062: Lookup: "editable: false" (readonly) lookups do not allow clicking of the lookup button
**Describe the bug**
Using `editable: false` has always made the input field readonly, it suddenly makes the button disabled.

**To Reproduce**

Create a lookup with `editable: false` and noticed it is not clickable. Here is an example: https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-not-tabbable.html

**Expected behavior**
The input should not be editable, but the lookup should be actionable.

**Version**

- ids-enterprise: 4.51

**Additional context**
This was broken with this commit: #https://github.com/infor-design/enterprise/commit/b90bb8e8406baac8c842932af039991cfcbb8339

**Platform**
Infor Application/Team Name: lawson
Device: (if applicable) N/A
OS Version: Windows10
Browser Name: chrome
Browser Version: 89.0.4389.114 (Official Build) (64-bit)

### LINKED ISSUE #5063: Datagrid: Icon misalignment on a filter field for a datagrid with small rowheight
**Describe the bug**
For a datagrid with the class "small-rowheight", the lookup, datepicker, and timepicker icons are misaligned with the fields.

This seems to be caused by this commit from issue #5030:
https://github.com/infor-design/enterprise/commit/3a22ee7af6bec545454bb185ab904fb4624ccc09

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html
2. Add the class "small-rowheight" to the datagrid
3. Note that the datagrid filter fields with icons overlap

**Expected behavior**
It is expected that the icon is inside of the datagrid filter field.

**Version**
- ids-enterprise: v.4.51.0-dev

**Screenshots**
Misalignment seen in this sample:
Filter Icon Misalignment

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.114 (Official Build) (64-bit)

### LINKED ISSUE #5087: Lookup: editable strict cannot open lookup
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html
2. Click on Lookup icon
3. Notice that the look up is not shown

**Expected behavior**
should be able to open lookup

**Version**

- ids-enterprise: 4.50.0-main

**Screenshots**

**Platform**
all major browsers

**Additional context**

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR resolves the following:
- Changes from #5030 applied a trigger button in places where only an icon used to exist.  On the smaller-sized datagrid filter fields, these buttons weren't properly aligned anymore.  This is now fixed.
- Changes in #5030 accidentally altered the behavior of readonly Lookup fields, which should still allow for the user to enter a lookup field by clicking the icon.  The behavior of lookup buttons in this PR has been altered to allow the button to be clicked, but not focused by keyboard.
- Changes from #5022 improved the alignment of the close button on Searchfield inputs, but the alignment was altered specifically on non-collapsible Searchfields inside of Lookups.  This alignment is now fixed.

**Related github/jira issue (required)**:
- Related to #5022 
- Related to #5030
- Closes #5062 
- Closes #5063
- Closes #5087

**Steps necessary to review your pull request (required)**:
Pull, build, run

_Test #5062:_
- open http://localhost:4000/components/lookup/example-not-tabbable.html
- click the Readonly Lookup field's trigger button.  It should activate the Lookup as expected

_Test #5063:_
- open http://localhost:4000/components/datagrid/example-filter.html
- Using the "..." button, examine the datagrid headers' filter fields, specifically the Lookup, Timepicker, and Datepicker, on the "Short" and "Extra Short" grid sizes.  The icons in these filter fields should be center-aligned vertically and close to the right-most edge.
- Open Datepickers within the grid and ensure when focusing the cell, their icons do not disappear or become misaligned.  Also ensure the Popup opens in the correct place.
- Test Timepicker Fields: http://localhost:4000/components/datagrid/test-editable-time.html
- Test Lookup Fields: http://localhost:4000/components/datagrid/test-editable-lookup.html
- Test RTL: http://localhost:4000/components/datagrid/example-filter.html?locale=ar-EG
- Test Classic theme: http://localhost:4000/components/datagrid/example-filter.html?theme=classic&mode=light
- Test Classic theme + RTL: http://localhost:4000/components/datagrid/example-filter.html?theme=classic&mode=light&locale=ar-EG

_Test "X" misalignment:_
- open http://localhost:4000/components/datagrid/test-lookup-filter.html.  Examine the lookup field (labelled "Product ID).  The X button should be center-aligned vertically and close to the right-most edge.
- open http://localhost:4000/components/lookup/example-not-tabbable.html and open the Lookup.  Enter some text in the Searchfield.  When the "X" appears, it should be center-aligned vertically and close to the right-most edge.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Holding off until we fix additional issues reported: 
- https://github.com/infor-design/enterprise/issues/5063#issuecomment-816934188
- https://github.com/infor-design/enterprise/issues/5063#issuecomment-816959248

**Comment by EdwardCoyle** [comment]
@tmcconechy this one should be good now.

@awbuboltz @s-werking I think we've fixed all the regressions related to the trigger buttons.  Please let us know if you think we missed anything here.

**Comment by tmcconechy** [comment]
One issue we saw testing is http://localhost:4000/components/datagrid/test-editable-time.html and click the time pickers in the grid. The layout and positioning is off.

**Comment by EdwardCoyle** [comment]
Notes for improvements:
- [ ] check [here](https://github.com/infor-design/enterprise-wc/blob/main/src/ids-popup/ids-popup.js#L159) to see if we can use `super` instead

**Review by tmcconechy — COMMENTED** [review]
@EdwardCoyle - looks good. I fixed the build be hard coding the chrome version for now.
I did see a couple of things but feel free to punt on any of them...But im ordering them in order of importance

1. I think that all the cells with editors and filter field should maybe set the trigger fields to not tabbable. The problem is a bit worse in the datagrid editors for example http://localhost:4000/components/datagrid/test-editable-time.html click a time cell, then tab and the tab again -> in this case focus is lost and returned out of the page (focus trap)

I think this can be fixed by setting all the options to tabbable: false by default for example here....
https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.editors.js#L744

2. on http://localhost:4000/components/datagrid/test-editable-time.html and http://localhost:4000/components/datagrid/example-filter.html all of the datepicker and timepicker cells are missing arrows

Screen Shot 2021-04-14 at 9 48 55 AM

3. In http://localhost:4000/components/datagrid/example-filter.html some of the dropdown icons are not centered and this happens in 3/4 row heights

Screen Shot 2021-04-14 at 9 48 12 AM

**Comment by EdwardCoyle** [comment]
@tmcconechy everything should be covered now (Time/Date/Lookup fields are all aligned).  Let me know if you see any we missed... but we may want to push any others off for time's sake.

Per your comments:
- I did use the editor settings to disable Time/Date/Lookup editor's `tabbable` setting by default
- I didn't change the arrow/placement logic for these... I think it's been broken since before this changeset and need to punt that for times' sake.

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
Wow! looks great 🍌

**Comment by awbuboltz** [comment]
This will be going into main as well, right?

**Comment by tmcconechy** [comment]
Yes working on it now....

**Comment by tmcconechy** [comment]
Its merged to main but will build out to the sample app in a like 30mins

**Comment by s-werking** [comment]
Hi! When testing the fixes I noticed that if I click on the icon buttons inside a datagrid and then click outside of the table and hover over other cells in the same row, the icon area seems to turn white. Should this be opened as a separate ticket?
image

**Comment by tmcconechy** [comment]
yeah please - this has been cropping up and is a seperate and more minor issue

**Pull request merged**
