### PR TITLE
8460 - Fix 6th level accordion header position (Module Nav)

### LINKED ISSUE #8460: ModuleNav: misaligned level6 header and + icon
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/module-nav/example-six-levels-icons.html
2. Click on Level 1 Outbound Links
3. Expand to six levels deep

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

image

**Platform**
Firefox

**Additional context**
with other browsers  e.g., safari, chrome, the header text was misaligned when collapsed (Default) or not yet clicked to expand
image

the issue also exists in https://main-enterprise.demo.design.infor.com/components/module-nav/example-six-levels.html

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the position of level 6 header accordion in module nav.

**Related github/jira issue (required)**:

Closes #8460 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/module-nav/example-six-levels-icons.html
- Click on Level 1 Outbound Links
- Expand to six levels deep
- Header should inline with the icon

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://github.com/infor-design/enterprise/assets/102151352/bb7080c2-7b56-4706-89ca-f9ce70cdeef3

**RTL**
Level 3 Header is not properly rendered.
https://8460-module-nav-levels-enterprise.demo.design.infor.com/components/module-nav/example-six-levels-icons.html?locale=ar-SA

- Mac Chrome

https://github.com/infor-design/enterprise/assets/102151352/07e82312-3c8f-48fb-ba90-b670986b5b08

- Mac Firefox
image

- Mac Edge
image

- Safari
image

**Comment by ericangeles** [comment]
Fixed the RTL issue. Please review it again. @infor-design/qa

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/39199a21-dfc9-4ba6-86af-b1d30ae9526d

image


**RTL**

- Mac Chrome

https://github.com/infor-design/enterprise/assets/102151352/c7fb7c46-2795-4f96-a155-4041de4bf681

- Mac Firefox


https://github.com/infor-design/enterprise/assets/102151352/a4d218d9-5d6f-462c-a1f0-e7b9c1bf5cfb

- Safari


https://github.com/infor-design/enterprise/assets/102151352/4f0b58c0-9914-4c19-ae09-b1cefb6d3ca3

- Edge


https://github.com/infor-design/enterprise/assets/102151352/136ec55d-b6a5-42b3-a544-d05aae5d5dd5

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
