### PR TITLE
NG#1671 -  Fix `charts.setSelected` method to work with different charts in a single page

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Upon reviewing this issue, I identified a collision in `[[FunctionLocation]]` when multiple types of charts are present on a single page. Specifically, in the `Line` chart, the `charts.setSelected` method is also being called by different chart types. To prevent collisions, we need to relocate it within the charts.

cc: @tjamesallen15 for further testing. Please continue if more fixes are needed.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1671

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/charts/multiple-charts.html
- Click the `Set Selected` button in each of every charts
- It should select the correct bar/line charts (it should be working)
- You can also compare it to http://localhost:4000/components/charts/multiple-charts.html vs https://main-enterprise.demo.design.infor.com/components/charts/multiple-charts.html

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Looks good to me. Just a looks like one lint issue

**Review by tjamesallen15 — DISMISSED** [review]

**Comment by tjamesallen15** [comment]
Thank you @ericangeles, I added area charts in the mix as well, saw in the failing lint.

**Review by jbrcna — APPROVED** [review]
image
image

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

image

**Review by glenlieorillo — DISMISSED** [review]
image

image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
