### PR TITLE
650 - Fix xss issues in dropdown

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The xss was not working when doing a backspace in dropdown. (There were CSP errors).

**Related github/jira issue (required)**:
Fixes infor-design/enterprise-ng#650

**Steps necessary to review your pull request (required)**:

**Test One**
- pull this and restart the demo app
- go to http://localhost:4000/components/dropdown/test-xss.html
- type a and make sure it filters
- make sure you can select the <> formatted items
- backspace to clear
- make sure no console errors (CSP Error will happen if it injects)

**Test Two**
- go to http://localhost:4000/components/dropdown/test-special-chars.html
- make sure you can select all the items especially `<test>`

**Test Three**
- go to http://localhost:4000
- check the console and make sure there are no CSP errors

**Test Four**
- go to http://localhost:4000/components/dropdown/example-icons.html
- type anything to search
- backspace to clear
- ensure this example is working

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

cc @anhallbe

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
All the tests appear to work just fine, but I noticed that if you start the demoapp with `npm run quckstart:livereload`, the inclusion of the Livereload script causes a CSP error:

Screen Shot 2019-10-29 at 12 47 35 PM

Maybe `script-src 'self'` doesn't include localhost?

**Comment by tmcconechy** [comment]
ok @EdwardCoyle i've fixed liverload. good catch

**Comment by deep7102** [comment]
Looks good, few things saw as
http://localhost:4000/components/dropdown/test-xss.html
- select item with <>, see the tooltip is show as inner node text only
- if you type`t` to filter, it convert `<` to `&lt;`

http://localhost:4000/components/dropdown/example-icons.html
- type a and see the swatches not show with filter list

**Comment by tmcconechy** [comment]
@EdwardCoyle this change is big enough that it should be retested fully.

**Comment by EdwardCoyle** [comment]
~Found an issue in the Dropdown filtering regarding the icon, but I think we address it in a separate issue.  Note the icon change when text is entered/removed from the filter:~

Untitled_-Nov-5-2019-9_50-AM

I just realized this is probably by design because "no matching result" wouldn't have an icon associated with it.

**Comment by tmcconechy** [comment]
Yes, at the time i told @ericangeles to use that icon as the "empty" icon or the text was mismatched. I think it works ok

**Pull request merged**
