### PR TITLE
7933 - Add legend title in donut and pie charts

### LINKED ISSUE #7933: Donut chart: Require a title over Legends
**Is your feature request related to a problem or use case? Please describe.**
Design need to acheive
image

What we are getting:
image

**Describe the solution you'd like**
Require something so that we can add title for the legends

Reference component:
https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-index?theme=uplift&variant=light

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR introduces a feature legend title in donut and pie charts. This will only support the `right` legend position.

**Related github/jira issue (required)**:

Closes #7933

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to 
  - http://localhost:4000/components/donut/example-legend-with-title (Donut)
  - http://localhost:4000/components/pie/example-legend-with-title (Pie)
- Both examples should have a legend title

**Included in this Pull Request**:
~~- [] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@ericangeles looks like it needs

- a bit of padding
- text is not bold

Side by Side
Screenshot 2024-02-07 at 9 24 48 AM

**Comment by ericangeles** [comment]
Should we also change the font color of the legends?

**Comment by ericangeles** [comment]
@tmcconechy, I don't think the title is in bold; it's just that the color really stands out over the legend items.

**Comment by tmcconechy** [comment]
Yeah i see, I made a comment on the figma. it looks like it has no hierarchy. My suggestion was make the legend items font-weight: 300 or one color lower.

Maybe 1-2px padding under the title? Otherwise looks good.

**Comment by jbrcna** [comment]
image
image


image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
legend title not visible in smaller viewport
image

**Comment by tmcconechy** [comment]
@ericangeles i think this is the new version with a bit of change between legend items and title https://www.figma.com/file/e6CLlhP1Bq8DYV6OE8Vxqi/2024-SoHo-Update?type=design&node-id=44454-35748&mode=design&t=bgsq0rstBcW6kEvu-4

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**
image

image


**Mac FF**
image

image


**BrowserStack**
- Android
image

image



- iOS
image

image

**Review by tmcconechy — APPROVED** [review]
@ericangeles anything else to fix? Looks good to me

**Comment by ericangeles** [comment]
This is all good, @tmcconechy.

**Pull request merged**
