### PR TITLE
8653 - Remove Duplicates css in the Build

### LINKED ISSUE #8653: General: Multiple rules in build system
**Describe the bug**
Due to removing node-sass-once-importer

**To Reproduce**

1. Run `npm run build`
2. Open dist/css/theme-new-light.css
3. Search for a rule like `.btn-icon .notification-badge-container .notification-dot.notification-dot-upper-right`
4. See error -> should only be 2 (one is RTL) but there is 22

**Expected behavior**
Should be only one rule

a) Remove redundant imports
b) Change to using `use`
c) try this http://4waisenkinder.de/blog/2014/03/06/import-once-in-sass-the-foundation-way/
d) Other?

**Screenshots**
Can also see this in the debugger
Screenshot 2024-04-26 at 2 02 32 PM

**Additional context**
This has the consequence of dramatically increasing the size of the css file (1.8, 3.1 MB)

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Due to recent changes to chnage from node-sass to sass package. I found that there is duplicate css rules. In order to fix it I removed all imports in component sass files. Also fixed missing comments and any sass warnings as i went through every file.

**Related github/jira issue (required)**:
Fixes #8653

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/button/example-index.html
- inspect any button in the page and should not be dupicates in the css (see screen shots)
- smoke test http://localhost:4000/ vs https://main-enterprise.demo.design.infor.com/
- should not see any differences

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
Looking at the code, I think this is the appropriate fix for this issue, @tmcconechy. 👍🏼

**Review by jbrcna — APPROVED** [review]
image

**Review by janahintal — APPROVED** [review]
image

**Review by n-ace-ancog — APPROVED** [review]
No changes seen compared to main.
image

image

image

image

image

**Review by glenlieorillo — APPROVED** [review]
image

_main-enterprise_
image

**Pull request merged**
