### PR TITLE
7209 - header components alignment

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix header components not aligned and visibly shown properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7209

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html
- Check the alignments (should be visibly shown properly)
- Test it on smaller viewport
- Collapse Button should be shown properly

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I see a bit of a wierd thing going on and i wonder if its https://github.com/infor-design/enterprise/issues/7421 cc @ericangeles 

1. resize smallest possible in chrome
Screenshot 2023-04-13 at 11 59 05 AM

2. resize back see how its centered?
Screenshot 2023-04-13 at 11 59 14 AM

Might want to wait for https://github.com/infor-design/enterprise/issues/7421

**Comment by tmcconechy** [comment]
Lets see if issues are solved once https://github.com/infor-design/enterprise/issues/7421 is done.

**Comment by tjamesallen15** [comment]
> I see a bit of a wierd thing going on and i wonder if its #7421 cc @ericangeles
> 
> 1. resize smallest possible in chrome
>    Screenshot 2023-04-13 at 11 59 05 AM
> 2. resize back see how its centered?
>    Screenshot 2023-04-13 at 11 59 14 AM
> 
> Might want to wait for #7421

Hi @tmcconechy , I saw that the related PR is merged already and I checked it. It's working fine now.

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
Ok looks good. Still WIP @tjamesallen15 or done?

**Comment by tjamesallen15** [comment]
> Ok looks good. Still WIP @tjamesallen15 or done?

Hello. This is done. My bad forgot to remove wip.

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@CindyMercadoReyes ready for QA

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
QA Approved.

Tested in: http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html


https://user-images.githubusercontent.com/102151352/233878165-3cd6dafa-dab8-4149-82fc-86f11eb27f19.mov


https://user-images.githubusercontent.com/102151352/233877895-0cd0bfe9-75ac-4b6c-bdfd-644e54d37d71.mov

**Pull request merged**
