### PR TITLE
Datagrid: Misaligned icons across Datagrid component

### PR DESCRIPTION
**Pull request by sesbrenosienna**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes the bug where search and x icons are misaligned across the Datagrid component. This also fixes the bug where there is an extra margin space present in the modal in Firefox. 

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6418

**Steps necessary to review your pull request (required)**:
1st Issue (Search Icon and X icon misalignment in Datagrid Toolbar): 
1. Go to these pages (Chrome, Firefox, Edge)
  - http://localhost:4000/components/datagrid/example-compact-mode.html
  - http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
  - http://localhost:4000/components/datagrid/example-custom-toolbar.html
  - http://localhost:4000/components/datagrid/example-drilldown.html
  - http://localhost:4000/components/datagrid/example-expandable-row.html
  - http://localhost:4000/components/datagrid/example-full-width.html
  - http://localhost:4000/components/datagrid/example-paging-client-side.html
  - http://localhost:4000/components/datagrid/example-grouped-headers.html 
  - http://localhost:4000/components/datagrid/example-key-row-select.html
  - http://localhost:4000/components/datagrid/example-keyword-search.html 
2. Click and input text in search field 
3. Also check in responsive view

2nd Issue (Extra Margin Space at Example Modal Datagrid Tabbing): 
- Go to http://localhost:4000/components/datagrid/example-modal-datagrid-tabbing.html?theme=classic&mode=light&colors=2578a9 in Firefox
- Click “Open Modal” 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Everything looks good to me i think we might have to update this test tho : https://github.com/infor-design/enterprise/runs/6856990451?check_suite_focus=true#step:8:2634

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — CHANGES_REQUESTED** [review]
Looks all good,
just one thing is clearable icon not aligned in some case

image

**Comment by sesbrenosienna** [comment]
Hello @deep7102! 😄 

I tried checking http://localhost:4000/components/datagrid/example-full-width.html again and cannot seem to reproduce the issue. May I know what you did to reproduce this?

**Review by ericangeles — APPROVED** [review]
Looks good to me! 🍌

**Review by tjamesallen15 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@deep7102 can you check again? I wasnt seeing that..

**Review by tmcconechy — APPROVED** [review]

**Comment by deep7102** [comment]
> Hello @deep7102! 😄
> 
> I tried checking http://localhost:4000/components/datagrid/example-full-width.html again and cannot seem to reproduce the issue. May I know what you did to reproduce this?

@sesbrenosienna 
Not sure what happens, saw now and it looks all working -thanks 🍌

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
