### PR TITLE
2072 - Fix position of editor icons

### PR DESCRIPTION
**Pull request by nickwynja**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes editor toolbar icon alignment after updates in icon set

**Related github/jira issue (required)**:
https://github.com/infor-design/design-system/issues/364

**Steps necessary to review your pull request (required)**:

See http://localhost:4000/components/editor/example-index.html?theme=uplift

**soho (current)**:

Screen Shot 2019-05-20 at 5 59 24 PM

**uplift (master)**:

Screen Shot 2019-05-20 at 5 59 45 PM

**uplift (fixed)**:

Screen Shot 2019-05-20 at 5 59 16 PM

### CODE REVIEW

**Comment by tmcconechy** [comment]
Can we do anything better with this set of font style icons. I always thought they looked a little off.
There may be some editor.scss "corrections" in there to adjust for old icon set?

Screen Shot 2019-05-21 at 11 03 17 AM

**Comment by tmcconechy** [comment]
Also the focus state is off 
Screen Shot 2019-05-21 at 11 10 39 AM

**Comment by clepore** [comment]
I think that's the style we are going with for design, currently. A bit bigger with more of an "outline" feel.

**Comment by tmcconechy** [comment]
OK maybe revise it to have a more padded toolbar on top or bottom as a future suggestion. I wont block this based on that tho.

**Pull request merged**
