### PR TITLE
7565 - border color accordion header

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix bottom border color cannot be seen properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7565

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
- Open the navigation menu, see the borders

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Still seeing part of the issue as follows.

1. go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
2. tab into the menu
3. tab again to manager
4. down arrow to my team
5. up arrow

Or just click "my team" 
Screenshot 2023-06-27 at 9 40 01 AM
Screenshot 2023-06-27 at 9 40 06 AM

**Review by EdwardCoyle — APPROVED** [review]

**Review by ericangeles — DISMISSED** [review]

**Review by clayinfor — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]
Thanks looks good. Moving to QA

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
When the accordion is expanded, menu item border is cut off/looks off.

Steps to reproduce:

1. Expand 'Employee'
2. Expand 'Manager'
3. Compress 'Manager'
4. See upper border of 'Manager'





https://github.com/infor-design/enterprise/assets/102151352/3d58e74b-6fd1-42b4-9ea7-03b873e080a4

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Comment by tjamesallen15** [comment]
Can we retest this ? @jbrcna @glenlieorillo Thanks

**Review by jbrcna — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
Approved.

image

**Pull request merged**
