### PR TITLE
6273 - Badges: Fix Alignment

### PR DESCRIPTION
**Pull request by iamjamesreyracho**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug on Badges Icon/Number alignment.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6273

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go http://localhost:4000/components/badges/example-index.html?theme=new&mode=contrast&colors=003876
- Check the badges

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Hello @iamjamesreyracho ,

The `High Contrast` was fixed however the `Light` Version is not aligned. See the screenshot below.
image

**Comment by tjamesallen15** [comment]
@iamjamesreyracho  please fix the lint issue.

**Review by tmcconechy — APPROVED** [review]
Looks good. But could we also add a change log entry? And maybe a visual puppetteer test?

**Comment by tjamesallen15** [comment]
> Looks good. But could we also add a change log entry? And maybe a visual puppetteer test?

I'll be the one updating this one right now since we will be having a long weekend starting tomorrow.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
