### PR TITLE
5955 - Datagrid DateField Issue in Medium Row Height

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix edit input date field on medium row height in datagrid.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5955

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-disabled-rows.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 this his works perfectly in medium row height but in the other three (xs, sm, large) either the icon is not 100% centered or it "shifts" when you go into edit mode.

Can you check all 4 row heights?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 this his works perfectly in medium row height but in the other three (xs, sm, large) either the icon is not 100% centered or it "shifts" when you go into edit mode.
> 
> Can you check all 4 row heights?

Sure sure. i forgot to add WIP tag last night for this one.

**Comment by tjamesallen15** [comment]
Will fix all of the visual test once this is approved.

**Review by tmcconechy — COMMENTED** [review]
Looking a lot better except for

- datepicker - icon a bit low in large mode
- dropdown - icon a bit low in medium and extra small

Thanks!

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
Am seeing failing visual tests in the build

failed-visual-tests

**Comment by tjamesallen15** [comment]
> Am seeing failing visual tests in the build
> 
> failed-visual-tests

will fix this.

**Review by tmcconechy — DISMISSED** [review]

**Review by yohannahbautista — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
