### PR TITLE
4877 - Improve Horizontal/Header Tabs focus indicator placement

### LINKED ISSUE #4877: Tab highlight not matching the tab's actual size for RTL locales only
**Describe the bug**
When using arrow keys to traverse tabs, the highlight box is not matching in size to the actual tab. i see this only happening in RTL i.e. locale=ar-SA

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?locale=ar-SA
2. Click on any header tab
3. Use arrow keys to traverse focus.
4. This is more evident further down (left)

**Expected behavior**
Highlight box should match the actual tab dimensions

**Version**
- ids-enterprise: 4.38.0-dev

**Screenshots**
RTL-tabs

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable) N/A
 - OS Version: Win 10 Ent
 - Browser Name: Chrome
 - Browser Version: Version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
Might be related to https://github.com/infor-design/enterprise/issues/2929
Original ticket https://jira.lawson.com/browse/LMCLIENT-34431

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a couple issues related to Header Tabs: 
- In RTL Mode, the placement of the focus indicator within the tab container was way off.  The placement has been improved.
- In RTL Mode, the faded edges were not facing the correct direction, and were not responding correctly to the container's scrolling (if it's possible to scroll left, the left edge should appear "faded" and visually cut off the contents, and vice-versa).  This has been fixed.
- A regression was discovered while testing in Safari where it wasn't possible to navigate the tabs with the arrow keys.  This has been fixed.

**Related github/jira issue (required)**:
- Closes #4877 
- Related to #4763 (caused the regression)

**Steps necessary to review your pull request (required)**:
_To test #4877:_
- Pull, build, run
- Open http://localhost:4000/components/tabs-header/example-index.html?locale=ar-SA
- Click on any tab, then navigate with the arrow keys.  The white box (focus indicator) should appear to be placed correctly over top of the tabs receiving focus.
- Press enter to select some tabs, and ensure the white line (selected indicator) closely lines up with the focus indicator.
- Check the edges of the tab container while scrolling and make sure the faded blue edges don't appear to be facing the wrong direction.
- Also check in-page tabs on RTL mode (as well as standard mode):
  - http://localhost:4000/components/tabs/example-dismissible-tabs.html
  - http://localhost:4000/components/tabs/example-dismissible-tabs.html?locale=ar-SA

_To test the regression:_
- Open http://localhost:4000/components/tabs/example-dismissible-tabs.html on an iPad (or simulator) running iOS 13+
- Try to dismiss the tabs by clicking the "X".  They should be removed as expected.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
ONe thing @EdwardCoyle 

the first tab is a bit off on initial load

Screen Shot 2021-03-26 at 11 34 13 AM


1. go to http://localhost:4000/components/tabs-header/example-index.html?locale=ar-SA
1. click the text in the tab (#1) 
1. shift + tab to focus the first tab

**Comment by EdwardCoyle** [comment]
@tmcconechy should be good now 👍

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
Looks good! I just seeing a super minor issue in RTL with dismissible. A pixel short?

rtl-dsmsble
rtl2-dsmsble

**Comment by ericangeles** [comment]
Looks good! I just saw a super minor issue in RTL with dismissible. A pixel short?

- Go to http://localhost:4000/components/tabs/example-dismissible-tabs.html?locale=ar-SA
- Click `Firefox` tab to show the border
- See a pixel short on left and over a pixel on the right

rtl-dsmsble
rtl2-dsmsble

**Comment by deep7102** [comment]
Looks good! only saw
- same pixel off as @ericangeles 
- popup arrow off I think that already has PR https://github.com/infor-design/enterprise/pull/5008 with different issue
image

**Comment by tmcconechy** [comment]
That is fixed on this pr https://github.com/infor-design/enterprise/pull/5008 @deep7102 
I just merged now.

**Comment by deep7102** [comment]
Thanks! @tmcconechy yes, same that I thought.

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
