### PR TITLE
8812 - Badge Toolbar Mobile

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix notification badge disappearance in toolbar on mobile view.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8812

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/toolbar/test-notification-badge.html
- Open `Developer Console`
- Switch to `Responsive` resize up to first break point `767px`
- Notification Badge should be there

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Looks good. Note those test issues i will fix

**Review by janahintal — APPROVED** [review]
Looking good on both Classic and New theme for Responsive and Mobile view. Thanks!
Test Data: 
[screen-capture.webm](https://github.com/infor-design/enterprise/assets/45757016/e2b1c4f0-9634-48d9-beee-f892ba6342d0)

**Review by jbrcna — APPROVED** [review]
image
image

**Review by glenlieorillo — APPROVED** [review]
image

**Pull request merged**
