### PR TITLE
703 - Add message modal status icon and color options

### LINKED ISSUE #703: Warning, Success, Error on messages/modals
**Is your feature request related to a problem? Please describe.**
I want to use a YesOrNo message dialog with a warning similar to https://github.com/infor-design/enterprise/blob/master/app/views/components/message/example-index.html but with a warning icon. Ability to add an errors exists here but no warning.

**Describe the solution you'd like**
I would like to have an enum property to establish.
```
1-success/confirm
2-warning/alert
3-error (exist)
4-info
```

**Describe alternatives you've considered**
I have solved the issue by setting a custom class to the modal that changes the color of the modal-title.

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Creates a setting that allows the choice of a status for a message modal and styles accordingly. Some mild refactoring occurred during this PR to reduce overhead and promote semantic class naming.

**Related github/jira issue (required)**:
Closes #703 .

**Steps necessary to review your pull request (required)**:
- Pull branch
- Run app
- Browse to http://localhost:4000/components/message/example-index
- Click Error, Warning, and Success buttons and ensure new styling is in effect and appropriate. Styling is appearance of SVG of appropriate color and color of `modal-title`

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
Should class names adhere to previously existing semantics? E.g., should `.is-warning` actually be `.is-alert` to match existing icon name? Should `.is-success` be `.is-confirm`?

**Comment by davidcarlsonberg** [comment]
As the nomenclature spans many files and components, I would suggest a new issue to address changing `confirm` to `success` across IDS.

**Comment by davidcarlsonberg** [comment]
New issue related to [comment](https://github.com/infor-design/enterprise/pull/952#issuecomment-428268054) above: #963 .

**Comment by davidcarlsonberg** [comment]
I agree a new issue is in order to address the colors.

**Comment by tmcconechy** [comment]
Sure I thought of that, maybe make it about message component accessibility. We probably want to make sure that the message announces the status properly but different then the error one. Possibly for this case the icon is colored but the text is dark so in contrast. So accessibility could use more testing here

**Comment by EdwardCoyle** [comment]
raised #964 for addressing accessibility concerns

**Pull request merged**
