### PR TITLE
3417-textarea row height

### LINKED ISSUE #3417: The textarea formatter is not the expected height when the row height is set to 'Short' or 'Medium''
**Describe the bug**
The textarea formatter is not the expected height when the row hieght is not set to 'Normal', eg. Short or Medium

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-editable-long-text.html'
2. Set the row height to 'Short'
3. Edit the Product Id in the second row 

**Expected behavior**
Single lined textara formatters should be the correct size that matches the row height. This works as expected when the row height is set to normal. 

**Version**
v4.26.x

**Screenshots**
image

**Platform**
 - OS Version: Windows 10 
 - Browser Name: chrome

**Additional context**
There are other issues with the textarea editor, but they should be done as part of #1643

### PR DESCRIPTION
**Pull request by marknolaninfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Correct the row height when the textarea formatter is used.

**Related github/jira issue (required)**:
Closes #3417 3417

**Steps necessary to review your pull request (required)**:
Go to 'http://localhost:4000/components/datagrid/test-editable-long-text.html'
Set the row height to 'Short'
Edit the Product Id in the second row

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by marknolaninfor** [comment]
'Datagrid Align Header Text Toggle Tests Should not visual regress' fails as it contains a textarea formatter that is viewed with the Short row height.

**Comment by tmcconechy** [comment]
Do you think that the problem that when you click in the comment (Textarea) cell it collapses can be fixed? Its not really part of https://github.com/infor-design/enterprise/issues/1643 or is it?

Feel like we should just fix up this editor entirely. Let me know if you want to take a stab at it? If not i can help. And i will fix the images when this is ready 100%

**Comment by marknolaninfor** [comment]
The textarea editor, now displays as an ids text area, and allows for the text editor options to be set. The activity column will show the remaining characters, and the status column is just a standard text area.

The autogrow does not work correctly as the heights are not calculated correctly. This ticket is a start on #1643 , but I was not able to implement.

**Comment by marknolaninfor** [comment]
@tmcconechy 

The focus issue caused by the click has been corrected, and the character count will not display by default, (different from the textarea control)

The editor uses the textarea ids control, over just a standard textarea, so you get all the additional functionality of the textarea control, eg autogrow.

I think the behaviour should be the same to be consistant, similar to the other editors like the datepicker.
http://localhost:4000/components/textarea/example-index.html

**Pull request merged**
