### PR TITLE
7012 - Updated font and icon colors for actionsheet

### LINKED ISSUE #7012: Actionsheet: label/text not readable in dark mode
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/actionsheet/example-index.html
2. Switch to dark mode
3. Click image
5. Test also in classic theme

**Expected behavior**

**Version**

- ids-enterprise: v4.70.0-dev

**Screenshots**
image

image

**Platform**
mobile

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated colors in actionsheet

**Related github/jira issue (required)**:

Closes #7012 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Minimize screen to be smaller than 700px (or switch to mobile)
- Go to: http://localhost:4000/components/actionsheet/example-index.html
- Click on more button to pop up actionsheet
- Text and icons in options should be visible
- Hover over options, text and icons should be visible
- Test on every version and mode

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista the only issue i see is in dark mode the action sheet is not dark.
@EdwardCoyle do you recall if there is a design file for this one?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I know the style should just be the same as the popup menu... So for dark mode can make the action sheet match the popup menu (when its not desktop).

Just in terms of background color/icon colors i mean...

**Comment by tmcconechy** [comment]
For some reason i noticed the color of the in dark mode button looks disabled http://localhost:4000/components/actionsheet/example-index.html?theme=new&mode=dark&colors=0066D4

http://localhost:4000/components/button/example-index.html?theme=new&mode=dark&colors=0066D4

But its ok on main.. Just a heads up i think it might have changed.

**Comment by EdwardCoyle** [comment]
This was the only design I could find, and unfortunately doesn't have Dark Mode colors defined: https://www.figma.com/file/KMCdcFsKVDZjdPFClAS5OF/WFM-Mobile-Components-Master-File?node-id=1172%3A6097&t=kq0CWHb5ry7z0Fsn-0

Our Figma file for 4.5 components doesn't currently contain any specs for Action Sheet.  I agree the background/text colors of the Action Sheet should probably match the colors of the Popupmenu for consistency.  Actually the button color adjustments @yohannahbautista look good, but would look way better against those background colors.

**Comment by tmcconechy** [comment]
Looks ~ good. I know its extra but maybe we can fix dark mode to make it perfect

**Comment by tmcconechy** [comment]
@yohannahbautista can you set the colors in dark mode? If you dont want to add that let me know and i'll make a second issue?

**Comment by yohannahbautista** [comment]
> @yohannahbautista can you set the colors in dark mode? If you dont want to add that let me know and i'll make a second issue?

Sorry, was a bit confused, do you mean having it look similar to this?
image

**Comment by tmcconechy** [comment]
No i just mean the action sheet should not be white when its open in dark mode. It should have the same colors and states as the popup menu https://main-enterprise.demo.design.infor.com/components/popupmenu/example-index.html?theme=new&mode=dark&colors=0066D4

example

So basically theme the action menu for dark mode. This is added scope so if you want to do it later thats fine too but shouldnt be too hard to fix 👍🏻

**Review by tmcconechy — APPROVED** [review]
Awesome. Thanks for the extra work on this 👍🏻

**Review by ericangeles — APPROVED** [review]
Looks great! Thanks @yohannahbautista!

**Pull request merged**
