### PR TITLE
Misc - Fix bug in RTL dropdown

### LINKED ISSUE #8790: SinkPage: Hierarchy - 'More' button is missing upon expanding the hierarchy - BETA 4.96
**Describe the bug**
'More' button is missing upon expanding the hierarchy.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/
2. Scroll down to the `Hierarchy` component
3. Notice and click the More button
4. Expand the hierarchy, click the arrow button
5. Notice that the more button is missing upon expanding the hierarchy

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**
image

https://github.com/infor-design/enterprise/assets/102151352/cf17fe45-0a4c-49f4-a56f-a9616475dfca

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8791: SinkPage: Generative AI buttons are not working in RTL - BETA 4.96
**Describe the bug**
Generative AI buttons are not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Generative AI` component
3. Click the buttons

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/800f0636-74f8-4341-bae8-0f1f2bc88783

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8792: SinkPage: Context Menu on Input Fields - right click is not working in RTL - BETA 4.96
**Describe the bug**
`right` click is not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Context Menu on Input Fields` component
3. Hover on the text field then click the right key of the mouse/trackpad

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/86f0da01-afbb-4d38-b3a5-caecadd12822

**_LTR_**
image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8793: SinkPage: All required fields are not working properly in RTL - BETA 4.96
**Describe the bug**
All required fields are not working properly in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to any required fields
3. Click the text field and leave it blank

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/46f4f6d4-693d-4f01-8aa8-1ca3afa21b16

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8794: SinkPage: Date Picker - Missing calendar button in RTL - BETA 4.96
**Describe the bug**
Missing calendar button in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Date Picker` component
3. Click the field under `Date Field`
4. Notice that there's no calendar button

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

https://github.com/infor-design/enterprise/assets/102151352/0662e85f-5849-4db8-9d5b-500f5fc66a55

**_LTR_**

image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8795: SinkPage: Time Picker - Missing timepicker button in RTL - BETA 4.96
**Describe the bug**
Missing timepicker button in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Time Picker` component
3. Click the field under `Timepicker`
4. Notice that there's no timepicker button

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**_LTR_**
image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8796: SinkPage: Multiselect Standard and With Tags are not working properly in RTL - BETA 4.96
**Describe the bug**
Multiselect Standard and With Tags are not working properly in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Multiselect` component
3. Explore the Multiselect, click and choose under dropdown
4. Notice that there are missing dropdowns under Towns (Max 5) and Fruits (disabled) under `Multiselect (with Tags)`

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/f7344f42-1b23-4699-b734-518f908b4b28

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8797: SinkPage: Checkboxes Issues in RTL - BETA 4.96
**Describe the bug**
RTL Issues:

Issue 1. Dirty Tracker is not working
Issue 2. The checkbox under required is misaligned
Issue 3: Required fields are not working

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Checkboxes` component
3. Click the checkbox with dirty tracker
4. Click the checkbox with required indicator
5. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**
image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8798: SinkPage: Toolbar Actions RTL Issues - BETA 4.96
**Describe the bug**
RTL Issues:

Issue 1: dropdown menu Items are exposed in the Toolbar
Issue 2: Search icon is not visible
Issue 3: Search bar is not appearing upon clicking the Search icon

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Toolbar Actions` component
3. Compare the Toolbar of LTR vs RTL
4. Hover over search icon
5. Try to click the search icon

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/226b8446-b743-42b6-a4e3-e618ec960fb8

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8799: SinkPage: Dropdown Menus are not working properly in RTL - BETA 4.96
**Describe the bug**
Dropdown Menus are not working properly in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to any dropdown menu
3. Try to click an item from the dropdown

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/182ead61-bcf3-45f1-b01d-395d72d22b27

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8800: SinkPage: Message - Buttons are not working in RTL - BETA 4.96
**Describe the bug**
Message component is not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to the `Message` component
3. Click the button

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/ae76c8c8-fe9c-49d8-8983-7325373b3932

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8801: SinkPage: CAP contents/items are exposed on the page in RTL - BETA 4.96
**Describe the bug**
CAP content is exposed on the page in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Contextual Action Panel` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/e4771615-b46a-465d-930e-f0f5c9bcae96

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8802: SinkPage: Pager is not working in RTL - BETA 4.96
**Describe the bug**
Pager is not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Pager` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/e6b50904-f2ab-4b97-acd2-46c481e171e9

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8803: SinkPage: ListView is empty in RTL - BETA 4.96
**Describe the bug**
ListView is empty in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `ListView` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**
image

**_LTR_**
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### LINKED ISSUE #8804: SinkPage: Datagrid is missing in RTL - BETA 4.96
**Describe the bug**
Datagrid is missing in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA#
2. Scroll down to `Datagrid` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**
image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8805: SinkPage: Accordion is not working in RTL - BETA 4.96
**Describe the bug**
Accordion is not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Accordion` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/7ff2751c-27e8-4b61-a551-3cb7cc324eda

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8806: SinkPage: Tags RTL Issues - BETA 4.96
**Describe the bug**
`x` and `arrow` are missing in the tags.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com
2. Scroll down to `Tags` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**
image

**_LTR_**
image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8807: SinkPage: Busy Indicator is not working in RTL - BETA 4.96
**Describe the bug**
Busy Indicator is not working in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Busy Indicator` component
3. Click the `Submit` button

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/44d407a1-f786-47af-8917-554f9385288a

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8808: SinkPage: All charts are missing in RTL - BETA 4.96
**Describe the bug**
All charts are missing in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA#
2. Scroll down to Charts
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/e99e366b-5622-4e76-a6a6-e1d445484e55

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8809: Sink Page: 'x' button looks off on mobile view in File Upload
**Describe the bug**
Sink Page: 'x' button looks off on mobile view in File Upload section

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/
2. Go to File Upload section 
3. Upload a File 

**Expected behavior**
'x' button should be centered 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image
 
**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### LINKED ISSUE #8810: SinkPage: Lookup icon is missing in RTL - BETA 4.96
**Describe the bug**
Lookup icon is missing in RTL.

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Scroll down to `Single-Select Lookup` component
3. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.96

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/f18c58c4-1f06-4030-8935-1a3b3e075305

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8811: Toolbar: looks different in RTL - BETA 4.96
**Describe the bug**

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Ensure RTL is on
3. Scroll down to '.Toolbar Actions'

**Expected behavior**
image

**Version**

- ids-enterprise: v4.96.0-beta0

**Screenshots**
image

**Platform**
All

**Additional context**
in general, sink page is broken in RTL. a lot of components is not working properly
error in console
image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed an error in multiselect that causes some things on the kitchen sink page to incorrectly load during smoke testing

cc @glenlieorillo 

**Related github/jira issue (required)**:
Fixes #8811
Fixes #8810
Fixes #8809
Fixes #8808 
Fixes #8807
Fixes #8806
Fixes #8805
Fixes #8804 
Fixes #8803 
Fixes #8802 
Fixes #8801 
Fixes #8800 
Fixes #8799 
Fixes #8798 
Fixes #8797 
Fixes #8796 
Fixes #8795 
Fixes #8794 
Fixes #8793 
Fixes #8792
Fixes #8791 
Fix #8790 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/multiselect/example-tags.html?locale=ar-SA -> should not error
- also try http://localhost:4000/components/multiselect/example-tags.html
- go to http://localhost:4000/?locale=ar-SA and retest the following
- #8811 and #8798 -> toolbar work look ok again
- #8810 -> lookup icon should appear
- #8809 -> file upload should look ok
- #8808 -> charts should be back
- #8807 -> busy indicator should work
- #8806 -> tags should have x again
- #8802 -> page should work again
- #8805 -> accordion should work
- #8804 -> datagrid should be back
- #8803 -> list view should be back
- #8801 -> CAP example should work
- #8800 -> message example should work
- #8799 -> dropdown example should work
- #8797 -> checkboxes should work again
- #8796 -> multiselect with tags should work again
- #8795 -> time picker should work again
- #8794 -> date picker should work again 
- #8793 -> required fields should work
- #8792 -> context menu should work again
- #8791 -> gen AI buttons should be ok
- #8790 -> more button should work

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Comment by jbrcna** [comment]
multi select with tags is working.. However, standard multiselect is not working properly.
 items were not displayed. try to select items. still not displayed.
image

**Comment by jbrcna** [comment]
gen ai is working
image

look up icon is now displayed
image

tool bar is now working
image

file upload is now working
image

charts  is now working
image

busy indicator is now working
image

pager  is now working
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Time Picker**
- Still not working properly, selected time is not displaying.

https://github.com/infor-design/enterprise/assets/102151352/fd443f23-6c3d-4497-a8ed-9ad555cbae05

**Multiselect (Standard)**
- Selected item/s are not displaying.

https://github.com/infor-design/enterprise/assets/102151352/c14951ed-ac7c-49b4-9e36-1ae290936331

**Color Picker**
- Misaligned color box.
image

**Editor**
- Misaligned color picker.
image

**Toolbar Actions**
- Search icon disappears when the user type in any word.

https://github.com/infor-design/enterprise/assets/102151352/76a08f36-f478-40e9-b2b8-068eb3cc86c6

**Modal**
- Dropdown menu still not working properly, selected item is not displaying.

https://github.com/infor-design/enterprise/assets/102151352/09dd3a08-7e48-4fe3-9dcf-38ada93e6390

**CAP**
- Dropdown issue.

https://github.com/infor-design/enterprise/assets/102151352/086dcabd-eaf0-47c7-9ad9-06897562a054

_Other components have been tested and working as expected. Thanks, @tmcconechy!_

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Some of the issues still persist, same findings from @glenlieorillo, such as with the time picker value and dropdowns.

image

https://github.com/infor-design/enterprise/assets/156752175/2884df62-93c2-4402-8ea0-c65541cdf0cd

https://github.com/infor-design/enterprise/assets/156752175/785da680-31f6-4550-aead-f9f649fe819f

**Comment by tmcconechy** [comment]
@jbrcna @glenlieorillo @n-ace-ancog 

I think i fixed everything noted (most important was the dropdowns not showing the value which was the fix originally and this impacted the modal/cap/multiselect examples)

Please retest those latest items.

**Review by jbrcna — DISMISSED** [review]
thanks @tmcconechy , the multi select standard now displays the items
image
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still seeing some errors in Toolbar Actions.

Steps to reproduce:
1. Scroll down to `Toolbar Actions`
2. Click the `search` icon
3. Type in any phrase
4. Then click the page
5. Notice that the `search` icon disappears
6. Find, hover and click the disappeared `search` icon
7. Delete the phrase
8. Click the page again

https://github.com/infor-design/enterprise/assets/102151352/3cbe8f49-85a1-469e-97c2-7108682a6054

However, the dropdown menu issues are now resolved. Thanks, @tmcconechy!

image

**Comment by n-ace-ancog** [comment]
I've checked https://latest-enterprise.demo.design.infor.com/?locale=ar-SA and it seems that the issue already exists pre-beta @glenlieorillo. We can create a separate issue regarding this or would you also fix this in this PR @tmcconechy?

**Comment by tmcconechy** [comment]
@n-ace-ancog yeah lets make a new issue for that one

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

image

https://github.com/infor-design/enterprise/assets/156752175/27ecd575-1e62-4831-a975-eb34b7807b50

image

**Comment by tmcconechy** [comment]
@n-ace-ancog merging this. just add an issue for the toolbar/collapsing search issue

**Pull request merged**
