### PR TITLE
4763 - Re-enable dismissing Tabs with taps on iOS

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes an issue that was causing iOS's "Link Preview" feature to conflict with Dismissible Tabs, causing them to become impossible to be dismissed.  We were able to fix it by reworking the CSS on tabs to prevent direct clicks on the anchor, causing events to be handled at the tab level as intended.

**Related github/jira issue (required)**:
#4763

**Steps necessary to review your pull request (required)**:
- Pull, build, run
- Open an iOS simulator (iPad and iPhone and a recent iOS version were requested)
- Open http://localhost:4000/components/tabs-module/example-index.html
- Try to dismiss either/both of the dismissible tabs.  It should now be possible.
- Also try standard in-page Tabs to smoke test (or any other tabs sample): http://localhost:4000/components/tabs/example-dismissible-tabs.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@aaronpikkarainen Please let us know if this fixes your issue

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]
LGTM unless you want to use https://github.com/infor-design/enterprise/pull/4856

**Comment by EdwardCoyle** [comment]
I'm fine with keeping this one to Safari, seems to not affect the desktop site at all

**Comment by aaronpikkarainen** [comment]
@EdwardCoyle, yes this seems to fix our issue well. At first I thought the ".is-safari" would mean Chrome on iOS would still be broken, but I tested Chrome on an iPhone and it works. Looks like Chrome on iOS is just re-skinned Safari.

Thank you for the fix!

**Review by ericangeles — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
