### PR TITLE
NG1478 - Homepage Component Resize

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix height calculation of homepage.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1478

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/homepage/test-pager.html
- Try to resize the window, pager should not have a space between it and the homepage
- smoke test http://localhost:4000/components/homepage/

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
NO

**Review by janahintal — CHANGES_REQUESTED** [review]
Wide space between the widget and pager is now fixed for responsive view. However, the pager is not centered when in Responsive and Mobile view 
image
image

**Comment by tjamesallen15** [comment]
> Wide space between the widget and pager is now fixed for responsive view. However, the pager is not centered when in Responsive and Mobile view image image

I think that's intended? @tmcconechy @ericangeles

**Comment by tmcconechy** [comment]
@tjamesallen15 i saw that too. It might be better if it stayed in the same position. But this is not an official example or pattern we wanted. So maybe only take a brief look and if not possible/easy we can leave it

**Review by janahintal — CHANGES_REQUESTED** [review]
Homapage widgets looks cut off and when you switch to responsive view.

- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html

image

When you resize the following page, only the first widget is being displayed. 

- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-calendars.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-monthviews.html

E.g
image
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Failing on https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/test-pager.html 
image
image
image



**Still failing on the ff:**
Homapage widgets looks cut off when you switch to responsive view and now even on full screen. 
image
image

https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-calendars.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-monthviews.html

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

Failing in chrome and firefox
 - resize and add widgets
image



working in safari 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
image


https://github.com/infor-design/enterprise/assets/102151352/193aae77-cb30-44e8-b473-6722f41b640b

Focus state is cut-off
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The bugs still exist on my end.

Mac Chrome
https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/test-pager.html

https://github.com/infor-design/enterprise/assets/102151352/3e72bbab-ca57-4c7c-ae16-5ef2f5b077dd

**Review by janahintal — CHANGES_REQUESTED** [review]
Cards looks cut off when in responsive view. Notice the last cards only displays half of its content. 

- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-calendars.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-filled.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-index.html
- https://ep1478-homepage-component-resize-enterprise.demo.design.infor.com/components/homepage/example-monthviews.html
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The focus state is still cut off.


https://github.com/infor-design/enterprise/assets/102151352/11da2396-e859-421a-bcf4-65210de3f863

**Review by jbrcna — APPROVED** [review]
this issue is now working https://github.com/infor-design/enterprise/pull/8544#pullrequestreview-1948460989
image
image

**Comment by tmcconechy** [comment]
Everything appears resolved now

**Pull request merged**
