### PR TITLE
8515 - Fixed search icon misalignment in dropdown cells

### LINKED ISSUE #8515: Dropdown: Search icon is not aligned in the datagrid's cell
**Describe the bug**
When I have a datagrid and type something I can see that the "search" icon is not aligned when the row height is set to small or extra small.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Change the row height to small (or extra small).
3. See the cell with the value "Shipped" on the column named "Action". When you hover it you can see that it is a dropdown.
4. Click on the cell and type a letter "o" or "s".
5. You can see that the search icon is not aligned.

**Expected behavior**
The search icon is aligned when the row height is small or extra small.

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed search icon misalignment in dropdown cells

**Related github/jira issue (required)**:

Closes #8515 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-editable.html
- Check dropdown cell (Action) in all sizes. Type on cell to show search icon

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good. But can you check the arrow too (in all row heights) in especially short it is a bit off..

Screenshot 2024-04-04 at 11 21 02 AM

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in firefox
image
image

**Review by glenlieorillo — APPROVED** [review]
Working as expected. However, the `Validate` dropdown is not displaying correctly in Safari. I have filed an issue for this bug: [8608](https://github.com/infor-design/enterprise/issues/8608)
image

- Chrome
image

- Firefox
image

- Safari
image

**Review by janahintal — APPROVED** [review]
image

**Review by jbrcna — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
