### PR TITLE
Create SVG icon HTML files from ids-identity assets

### PR DESCRIPTION
**Pull request by clepore**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

*Use Icon assets from ids-identity@2.1*
- Create the svg icon files (`svg.html`, `svg-extended.html`, `svg-empty.html`) dynamically from the svg files in the ids-identity node module.
- **Most of the file changes are from this**->  Icons will use the `color` css property to change their stroke color, as `fill` will actually refer to the non-stroke color (background, etc). This will be nice as we can then use css color inheritance and probably remove some instances where we specify icon `color` (previously `fill`).

*Icon Examples*
- Icon example files are now dynamically created from the assets in ids-dentity. We no longer have manually update these files.

**Related github/jira issue (required)**:
https://github.com/infor-design/design-system/issues/247

**Steps necessary to review your pull request (required)**:
1. `npm i && npm run start`
2. Test the following pages and make sure all icons show up and compare to the current release:
    - [index.html - 195 icons](http://localhost:4000/components/icons/example-index.html)
    - [extended.html - 194 icons](http://localhost:4000/components/icons/example-extended.html)
    - [empty-widgets.html - 12 icons](http://localhost:4000/components/icons/example-empty-widgets.html)
3. Examine other icon heavy examples to make sure they colorize and hover as they should.
    - [kitchen sink](http://localhost:4000/)
    - [calendar](http://localhost:4000/components/calendar/example-index.html)
    - [ratings](http://localhost:4000/components/rating/example-index.html)

### CODE REVIEW

**Comment by clepore** [comment]
This is also `on hold` because it needs some changes in ids-identity to continue.

**Comment by tmcconechy** [comment]
Should we wait on testing this out? Or is it good to at least check?

**Comment by nickwynja** [comment]
@tmcconechy Chris and I are going to review together shortly and push some updates with a new build of icons. Hold tight.

**Comment by nickwynja** [comment]
The only remaining issue I see is the above issue with the rating component. We might need to make some changes to the behavior of the component since I can't seem to make the icon build in a way like it used to.

**Comment by clepore** [comment]
@nickwynja Can you retest the rating stuff per your checklist from earlier? (you maybe need to re-checkout the branch).

**Comment by nickwynja** [comment]
Rating component looks good now. We just need to sort out the visual regressions on the test.

**Comment by tmcconechy** [comment]
We added some docs in making a Travis vim so you can update baselines.
It’s in this section: 
https://github.com/infor-design/enterprise/blob/master/docs/TESTING.md#creating-baseline-screenshots

If you have more questions or want me to help with it just let me know.

**Comment by clepore** [comment]
Closing in favor of a cleaner pull request: https://github.com/infor-design/enterprise/pull/1628

**Pull request closed without merging**
