### PR TITLE
5474 added display date range feature in calendar

### PR DESCRIPTION
**Pull request by edinfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

https://github.com/infor-design/enterprise/issues/5474

- added show range in calendar month view
- added test cases for new feature
- added new parameter in the settings: displayRange

**Steps necessary to review your pull request (required)**:

```
displayRange: {
        start: '07/11/2021',
        end: '09/30/2021',
      },
```

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Didnt have time for a full review yet but i see a couple tests failed here https://github.com/infor-design/enterprise/pull/5500/checks?check_run_id=3263647018#step:11:3027 you could look at meanwhile

**Comment by edinfor** [comment]
> Didnt have time for a full review yet but i see a couple tests failed here https://github.com/infor-design/enterprise/pull/5500/checks?check_run_id=3263647018#step:11:3027 you could look at meanwhile

should be good now, thanks!

**Review by EdwardCoyle — DISMISSED** [review]
@edinfor Thanks for the contribution!  For the reference of anyone else testing, I tested this page:  http://localhost:4000/components/monthview/test-range-in-month.html and simply checked that the selectable dates on the Monthview lined up to these: https://github.com/infor-design/enterprise/blob/432710b9dad0db4f9ca4d4f55fb6a4965aa6a5b5/app/views/components/monthview/test-range-in-month.html#L14-L15

Also did a smoke test of both regular Calendar and Datepicker, wasn't seeing anything off:
- http://locahost:4000/components/calendar/list
- http://locahost:4000/components/datepicker/list

Looks good 👍

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Some small changes..

1. Can you make the month text bold (font-weight: 600) (September 1 ect..)
2. The bottom border is cut off

Screen Shot 2021-08-09 at 11 34 38 AM

Otherwise not seeing any issues with this.

**Comment by deep7102** [comment]
Looks very nice! just few recommendations 
 - Example page can be move to `calendar` directory instead of `monthview`
 - It looks `handleEvents()` get called twice, [one here](https://github.com/infor-design/enterprise/pull/5500/files#diff-c68fb1988c6c9915e16a14e755fd3fa041f9d5dbe15d88b0dbf57cd1b19acc4cR171) `this.buildRange().handleEvents();` and [another inside](https://github.com/infor-design/enterprise/pull/5500/files#diff-c68fb1988c6c9915e16a14e755fd3fa041f9d5dbe15d88b0dbf57cd1b19acc4cR450) that `buildRange()`
- It this example will need two wrapper in [markup](https://github.com/infor-design/enterprise/pull/5500/files#diff-dd791f30b8598b1daed20f6de5047920fb648478ec0a161ba6b7ad813fc50116R2)? most of the time used single wrapper `<div class="calendar" data-init="false"></div>`

**Comment by edinfor** [comment]
> Looks very nice! just few recommendations
> 
> * Example page can be move to `calendar` directory instead of `monthview`
> * It looks `handleEvents()` get called twice, [one here](https://github.com/infor-design/enterprise/pull/5500/files#diff-c68fb1988c6c9915e16a14e755fd3fa041f9d5dbe15d88b0dbf57cd1b19acc4cR171) `this.buildRange().handleEvents();` and [another inside](https://github.com/infor-design/enterprise/pull/5500/files#diff-c68fb1988c6c9915e16a14e755fd3fa041f9d5dbe15d88b0dbf57cd1b19acc4cR450) that `buildRange()`
> * It this example will need two wrapper in [markup](https://github.com/infor-design/enterprise/pull/5500/files#diff-dd791f30b8598b1daed20f6de5047920fb648478ec0a161ba6b7ad813fc50116R2)? most of the time used single wrapper `<div class="calendar" data-init="false"></div>`

1. will move to calendar example
2. will remove handleEvents for both build and buildRange
3. Yes, I believe it needs the monthview wrapper inside of calendar view, see example here: https://github.com/infor-design/enterprise/blob/main/app/views/components/calendar/test-ajax-events.html#L20 and calendar component will look for different wrappers to build different calendars: https://github.com/infor-design/enterprise/blob/main/src/components/calendar/calendar.js#L239


@tmcconechy the bottom border is missing seems to be an existing issue, I tried tackling it, it requires some changes to responsive behavior of the component depending on the position of the legend, I suggest not to mix the responsiveness fix in this feature request, unless I'm mistaken. Please see the public example here: https://design.infor.com/code/ids-enterprise/latest/demo/components/calendar/example-index?theme=uplift&variant=light

image

**Review by deep7102 — APPROVED** [review]
🍌 Great, changes looks good @edinfor Thanks!

**Review by tmcconechy — APPROVED** [review]
Ok im good with this to then now

**Review by EdwardCoyle — APPROVED** [review]
Thanks again @edinfor 👍

**Pull request merged**
