### PR TITLE
7719 - Module Nav Fixes

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This issue solves a second round of QA and smaller improvements in the module nav menu. 

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/7719
Fixes https://github.com/infor-design/enterprise/issues/7662
Fixes https://github.com/infor-design/enterprise/issues/7654

**Steps necessary to review your pull request (required)**:
- expand items in http://localhost:4000/components/module-nav/example-six-levels-icons.html and http://localhost:4000/components/module-nav/example-six-levels-icons.html and check the indentation looks ok
- on http://localhost:4000/components/module-nav/example-index?colors=fff you can now use the hamburger menu and some colors and states are updated
- on http://localhost:4000/components/module-nav/example-index?colors=fff open the dropdown at the top and type XXX -> should see no results found
- on http://localhost:4000/components/module-nav/example-index?colors=fff type in the search and get results and also type in so you do not get results -> should so an empty message
- on http://localhost:4000/components/module-nav/example-index?colors=fff click the pin button and redo the search test. Items should stay pinned

Note: Can check over all points on https://github.com/infor-design/enterprise/issues/7719

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@infor-design/qa FYI

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
All fixes already applied. However, search bar is unreadable in Dark Mode.

http://localhost:4000/components/module-nav/example-index?theme=new&mode=dark&colors=fff

image

https://github.com/infor-design/enterprise/assets/102151352/0e1e0a26-240e-4ee2-ae79-af7fc3e10441




**1st item:**

image

image

**2nd item:**


https://github.com/infor-design/enterprise/assets/102151352/c1a560b5-d3b3-4472-80d4-7c6a87e6db08

**3rd item:** 

image

**4th item:**

image

image

**5th item:**

image

image

**Comment by tmcconechy** [comment]
@glenlieorillo i fixed item 1 with the color in dark mode. But I dont understand the other issues. Since this is high priority im going to merge this anyways. Can you make a new issue for those items and we can address them later (one issue for all items with steps to reproduce). I dont see anything other than the dropdown color thats obvious. Also do note we changed the azure color by design. (if thats the problem).

**Comment by glenlieorillo** [comment]
> @glenlieorillo i fixed item 1 with the color in dark mode. But I dont understand the other issues. Since this is high priority im going to merge this anyways. Can you make a new issue for those items and we can address them later (one issue for all items with steps to reproduce). I dont see anything other than the dropdown color thats obvious. Also do note we changed the azure color by design. (if thats the problem).

Hello @tmcconechy All other items are already passed. I just posted all my test evidence. The only issue I found was the search bar in dark mode. Thanks!

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
