### PR TITLE
8216 - Fixed dropdown icon misalignment in extra small rowheight

### LINKED ISSUE #8216: Datagrid: Dropdown icon incorrect alignment
**Describe the bug**
The dropdown icon is not properly aligned.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
2. Change the row height to Extra Small
3. Hover over the cells under the Action column

**Expected behavior**
The dropdown icon should be rendered properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - All major browsers

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed dropdown icon misalignment in extra small rowheight

**Related github/jira issue (required)**:

Closes #8216 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Hover over dropdown cells
- Arrow icon should be seen

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — DISMISSED** [review]
The issue has now been fixed. Thanks, @yohannahbautista!

However, I found some bugs while testing. See details below:


https://github.com/infor-design/enterprise/assets/102151352/f1bfdb5b-e072-4871-9e9e-8cd07be0ac37

1. Asterisk is not properly aligned inside the cell. (Row Height: _Extra small, Small, Medium_) Also, the size of the asterisk is different from the LTR view.

image

2. Sort-filled icon and drag icon are not properly placed.

image

3. Focus state color is broken.

image

image

_I will create a new issue for these found bugs._

**Comment by ericangeles** [comment]
Yes please, @glenlieorillo. Thanks!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista can you check (medium I think it is) row height

Here the dropdown is padded too much and not centered

Screenshot 2024-01-03 at 9 50 58 AM

Also i see something went wrong with the astericks/required indicator its too big in RTL should be the same size as http://localhost:4000/components/datagrid/example-editable.html but inverted in direction

Screenshot 2024-01-03 at 9 51 02 AM

**Comment by ericangeles** [comment]
@yohannahbautista, let's address the items that @tmcconechy mentioned above, and then we'll be good to go.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
There should be a space between 'Activity' and asterisk. Also, as per @tmcconechy, it should be inverted in direction.
image

http://localhost:4000/components/datagrid/example-editable.html
image

**Comment by ericangeles** [comment]
Please review this PR @infor-design/qa

**Review by tmcconechy — APPROVED** [review]
Looks good to me.

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@glenlieorillo will merge this just make a new issue

**Review by glenlieorillo — COMMENTED** [review]
The issue has now been fixed.

image

**Comment by glenlieorillo** [comment]
> @glenlieorillo will merge this just make a new issue

@tmcconechy I have created a new issue for the found bugs. Refer to this link [https://github.com/infor-design/enterprise/issues/8293](https://github.com/infor-design/enterprise/issues/8293)

**Comment by ericangeles** [comment]
Thanks, @glenlieorillo

**Pull request merged**
