### PR TITLE
8524 - Timeline Alignment

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will update example page of card workspace to include timeline.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8524

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/timeline/test-on-widget.html
- Check Timeline

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
image


failing in RTL
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Mobile View**

- Card should be center-aligned
- Broken line is cut-off

image

**Review by ericangeles — DISMISSED** [review]

**Review by glenlieorillo — COMMENTED** [review]
For clarification. I just noticed that the two cards are not aligned. Is it the expected outcome?

image

**Review by janahintal — CHANGES_REQUESTED** [review]
Lines are still cut off in RTL 
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Lines are cut off in https://8524-timeline-alignment-enterprise.demo.design.infor.com/components/timeline/test-on-widget.html responsive view this time 
image

RTL - fixed
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
same observation with @janahintal 
https://github.com/infor-design/enterprise/pull/8563#pullrequestreview-1959884636

**Comment by tmcconechy** [comment]
@tjamesallen15 the only thing to add is the card looks stuck to the side of the page. For the example maybe put the widget in a home page like http://localhost:4000/components/cards/example-workspace-widgets.html so its more representative of the actual case.

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
image

image

**Review by jbrcna — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
