### PR TITLE
6850 - datagrid alternate row shading (2)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where row shading is not rendered properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6850

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-alternate-row-shading.html
- Click on a cell with shading

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
@s-werking what do you think?

**Comment by s-werking** [comment]
Hi @tjamesallen15, I'm seeing a darker color around the datepicker's icon on non-shaded cells in the Classic High Contrast and Classic Dark themes. This can also be seen by clicking a lookup cell on this sample (http://localhost:4000/components/datagrid/test-editable-lookup.html?theme=classic&mode=contrast&colors=133c59).

Here is a screenshot for reference:
image

**Comment by tjamesallen15** [comment]
> Contributor

I think that's a box-shadow already. Correct me, if I'm wrong @tmcconechy

**Comment by tmcconechy** [comment]
Is it the `ripple-effect`? It is hard to see maybe we could disable it in this case.. With a rule like

```
  .ripple-effect {
    background-color: transparent;
  }
  ```

Or similar? That targets the button in this case

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
