### PR TITLE
7892 - Add fileupload-advanced in a homepage widget and forms

### LINKED ISSUE #7892: FileUploadAdvanced: Ability to resize responsively
**Describe the bug**
unable to resize the attachment component for both multi attachment and attachment component and dropdown component also

**To Reproduce**
image 

image

**Possible Specs (TJM)**

- by default has 300px width like an input field
- in responsive forms will take the save of the responsive column
- other fixed sizes?
- may have issues with very small sized and text wrapping so may need a changing height as well

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds an example of fileupload-advanced in homepage widget and forms.

**Related github/jira issue (required)**:

Closes #7892

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to 
  - http://localhost:4000/components/fileupload-advanced/example-in-a-homepage-widget.html
  - http://localhost:4000/components/fileupload-advanced/example-in-forms.html
- Check the responsiveness of the layout in different sizes
- Height should be responsive
- Play around the page

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good 👍🏻 

a) What about making it work in a field in a grid http://localhost:4000/components/form/example-inputs-simple.html so more options that just widget will work?

b) What about making the height responsive/adjustable too?

I think is more worth considering because maybe they dont do it in a widget and want it to be sizable

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
http://localhost:4000/components/fileupload-advanced/example-in-forms.html, when resizing the window: 
1. the last row 1st component is not the same size as the other. 
2. the upload status overshoots the rectangle

image

https://github.com/infor-design/enterprise/assets/156752175/59316dc6-1cf5-4056-ad1f-5aac6283c9ea

Not sure if this is nit picking, but In http://localhost:4000/components/fileupload-advanced/example-in-a-homepage-widget.html, the bottom of each horizontal bars some how overlaps

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Galaxy Z Fold 5 - Text overflows outside the border

image

image

RTL
image



iPhone 15 Pro Max - Passed

image

image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The status of the upload is now within the rectangle.

The first component on the last row is still not aligned when resizing.

image

In RTL, same scenario and the right padding while resizing vanishes
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
image

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:

image

image

image

**Review by jbrcna — APPROVED** [review]
great work!
issues were now fixed
image
image
image
image

**Pull request merged**
