### PR TITLE
6311 - Removed overflow none style for dropdown modal

### LINKED ISSUE #6311: Datagrid: Modal mouse scrolling not available after clicking Dropdown
**Describe the bug**
Hi, when running Datagrid inside Modal and one of the fields is Dropdown, after clicking it, the mouse scroll event on Datagrid is not scrolling.

**To Reproduce**

1. Run a Datagrid with many items on Modal causing it to have a scrollbar.
2. Add a `Formatters.Dropdown` field
3. Open the modal, see that mouse scroll is working
4. Click on one of the Drop down fields focus back to the grid
5. Try scrolling again with the mouse

Please see an example: [https://jsfiddle.net/sebulbajoe/hx1z0kat/9/show](https://jsfiddle.net/sebulbajoe/hx1z0kat/9/show)

**Expected behavior**
Mouse scroll event should scroll on datagrid even when dropdown was clicked

**Version**

- ids-enterprise: v4.61.1

**Screenshots**
Code when loading the modal:
image
After clicking on Dropdown this style (surrounded yellow) is added:
image

**Platform**
 - Browser Name: Chrome/Firefox 
 - Browser Version: Latest

**Additional context**
Thanks

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed overflow none style for dropdown modal

**Related github/jira issue (required)**:

Closes #6311 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-dropdown-scroll.html
- Open modal
- Open dropdown cell
- Hover out and scroll
- Should scroll

Overflow none looks to be related to a [previous fix](https://github.com/infor-design/enterprise/pull/4911), on checking it doesn't seem to affect it. Test also these just in case:
- Check scroll for this: http://localhost:4000/components/dropdown/example-virtual-scroll.html
- Go to multiselect in: http://localhost:4000/
   - Check if dropdowns work correctly
   - Check that no jittering happens

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Fix looks good 🍌 only thing saw is confusing

http://localhost:4000/components/datagrid/test-dropdown-scroll.html
- example page since it has check boxes (first column) but its not select able
- so either make them select able -or- remove that column from this example

**Comment by tmcconechy** [comment]
Yeah this example is a bit wierd. Is this the one that the developer on the issue gave? I think what should happen different is

a) the data grid should have its own scrollbar not on the modal (might be tricky but can manually set the height of the grid?
b) when you open the dropdown and then click out and scroll the list should close?

cc @jonathanamiran  can you test this fixes it and/or comment

**Comment by yohannahbautista** [comment]
Hello, I haven't been able to run the JSFiddle so I'm basing this on the code I see in the editor and the screenshot in the ticket. It looks to be based on one of the example pages in IDS so I used that as a base and edited the settings. The html in JSFiddle doesn't show any adjustments to the height, just an increase in data pushed so that the scroll will appear.
image

**Comment by jonathanamiran** [comment]
Hi, I've updated the JSFiddle code with latest version 
[https://jsfiddle.net/sebulbajoe/hx1z0kat/12/show](https://jsfiddle.net/sebulbajoe/hx1z0kat/12/show)

It seems that the issue still exists.
Thanks

**Comment by tmcconechy** [comment]
@jonathanamiran did you include the fix on this PR somehow? Its not in a released version yet

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — COMMENTED** [review]
I noticed that when I do horizontal scrolling the dropdown closes. is this also expected?

**Comment by jbrcna** [comment]
thanks for clarifying. approving now

**Review by jbrcna — APPROVED** [review]

**Comment by janahintal** [comment]
Approved. Verified working in http://localhost:4000/components/datagrid/test-dropdown-scroll.html, http://localhost:4000/components/dropdown/example-virtual-scroll.html & http://localhost:4000/

**Pull request merged**
