### PR TITLE
8225 - Changed selected border color for link card

### LINKED ISSUE #8225: Link: Has a wrong selected state
It should mirror what we have in KPIs.

https://main-enterprise.demo.design.infor.com/components/link/example-index.html

**Should be identical in the way cards look like:**
https://main-enterprise.demo.design.infor.com/components/stats/example-index.html

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changed selected border color for link card

**Related github/jira issue (required)**:

Closes #8225 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/link/example-index.html
- Select a card
- Border should be similar to: http://localhost:4000/components/stats/example-index.html

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
image

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still failing in Dark Mode. 

https://github.com/infor-design/enterprise/assets/102151352/a3812750-b7eb-4eb6-8b8d-f035dd888752



image


image

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
image

**Review by ericangeles — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Pull request merged**
