### PR TITLE
7657 - Change to title case and remove console log

### LINKED ISSUE #7657: Stats: Update copy to sentence case
Please update Stats component examples copy to sentence case. See image below that highlights where to do the updates. 

CleanShot 2023-06-29 at 08 41 59@2x

https://localhost:4000/components/stats/example-index.html

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes
- a stray console log
- missing event in example
- add sentence case to the new stat example
- fix card box shadow

NOTE: Already has a change log for stats. This is just an update

**Related github/jira issue (required)**:
Fixes #7657

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/stats/example-index.html
- ensure all text other than titles is in sentence case
- see that the stat card and normal card have same box shadow now
- be on the lookout for this in future examples you touch

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by clayinfor — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Changes already applied. However, one item missed fixing 'All KPIs' under 'Actionable Stats'. I believed it should be 'All stats'. See highlighted items:

image

image

**Review by jbrcna — DISMISSED** [review]
working as expected. However, i noticed that the other `All KPIs` is not changed
image

**Review by janahintal — DISMISSED** [review]

**Comment by tmcconechy** [comment]
ok @jbrcna fixed that text as well.

**Comment by jbrcna** [comment]
thank you, @tmcconechy

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
