### PR TITLE
8112 - CAP Back Arrow

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add content details and back button arrow.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8112

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/contextualactionpanel/test-back-button.html
- Press the button `Additional Information`
- See the next set of fields
- Press the back button on the header to go back to the main fieldsets.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Still finishing RTL view

**Review by jbrcna — DISMISSED** [review]
image
image
image

**Review by ericangeles — CHANGES_REQUESTED** [review]
@tjamesallen15, when I resize it to a smaller size, the detailed content becomes visible.

**Review by jbrcna — COMMENTED** [review]
image

**Review by tmcconechy — DISMISSED** [review]
@tjamesallen15 nice work here. I like it. Only one nit-pick. Can you review the padding on RTL it seems a little more cramped than LTR (just a bit)

Screenshot 2024-02-23 at 11 32 41 AM

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in smaller viewport in classic
image
image

**Review by tmcconechy — DISMISSED** [review]
Looks good to me. If we want we can disable this example for classic mode as we are less and less needing to spend time on it but it does look ok to me.

If you need to on this or any other add this line: https://github.com/infor-design/enterprise/blob/main/app/views/components/module-nav/example-index.html#L373

**Review by janahintal — APPROVED** [review]
Approving. Looks good on my end. Thanks
image
image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

**Mac Chrome**

https://github.com/infor-design/enterprise/assets/102151352/e51e200c-5a28-4b6c-ba38-b999f2135a70

**Mac Firefox (mobile view)**

https://github.com/infor-design/enterprise/assets/102151352/86b5f4d5-7c47-4b0c-96b0-03069da26aba

**Comment by ericangeles** [comment]
@tjamesallen15, could you also create a PR for NG for its typing definition and working example? Great work on this! 👍🏼

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
