### PR TITLE
7112 - Searchfield Non Collapsible Mobile View

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix border line of search field in mobile view non collapsible.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7112

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/header/example-non-collapsible-searchfield.html
- Open with mobile view
- Click the searchfield
- Click outside

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 

When you click out i think it should go to collapsed state again like any of these http://localhost:4000/components/searchfield/test-conflicting-collapsible-settings.html

Shouldnt stay expanded. But the css can probably stay that fixes that just in case something wierd happens

**Comment by tjamesallen15** [comment]
> @tjamesallen15
> 
> When you click out i think it should go to collapsed state again like any of these http://localhost:4000/components/searchfield/test-conflicting-collapsible-settings.html
> 
> Shouldnt stay expanded. But the css can probably stay that fixes that just in case something wierd happens

I'm confused. I tried to play around with the link you gave me.

This is the initial
image

After trying to remove the initial text inside the searchfield, it didn't collapse now
image

Same behavior as the one stated in this PR. So what should be the fix for this? I'm confused with the non-collapsible term here in mobile view.

**Comment by tmcconechy** [comment]
Yes neither of those is correct. Simply put the collapsable search field should expand when focused and collapse back to a simple icon when not.

https://main-enterprise.demo.design.infor.com/components/header/example-index.html works. But the mobile behavior is slightly off 

a) the animation is mixing directions
b) maybe we need to rethink the collapse button but can ignore that for now.

**Comment by ericangeles** [comment]
@infor-design/qa

**Review by jbrcna — APPROVED** [review]
image
image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/e9db0167-143f-43e8-b985-85b59e73ae3b


https://github.com/infor-design/enterprise/assets/102151352/4406c61a-3492-4553-81af-efd9ecb4fda0

**Review by janahintal — APPROVED** [review]
image
image

Observation: 'x' button on search field looks off
Classic:
image
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
