### PR TITLE
5478 - Accordion Performance Issue

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the performance issue on filter/unfilter function

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5478

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/applicationmenu/example-performance.html
- Type `Role` on the searchfield
- Click the `X` to clear

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 not seeing any major improvement here?

**Comment by tjamesallen15** [comment]
By removing the expand animation. The freezing is tolerable. I just pushed a draft updates but I haven't fix all of the bugs yet. I just made some changes for this expanding animation.

Video here.
https://drive.google.com/file/d/1QnpSIGnZI4oWVV1FZ7UFlXqjKNIhUZEj/view

I'll wait for the comments on this one to see if I will push through removing the expand/collapse animation.
@tmcconechy  @ericangeles

**Comment by tmcconechy** [comment]
@EdwardCoyle can you take a look at this one when you have a moment?

**Comment by tmcconechy** [comment]
What should we do with this one? @EdwardCoyle @tjamesallen15 @ericangeles ?

**Comment by tmcconechy** [comment]
@tjamesallen15 will taking out the animation work? i dont think it did?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 will taking out the animation work? i dont think it did?

Will review this one.

**Review by tmcconechy — APPROVED** [review]
Ok lets go with this 👍🏻  Its a lot faster. Not perfect but works and seems faster.

Thanks @tjamesallen15 
Cc @EdwardCoyle

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
