### PR TITLE
5795 - Modal Close Button Overlap

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a close button overlapped when title is long.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5795

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/modal/test-modal-datagrid-title-overlap.html
- Open Modal

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
I tried checking E2E in my local. And its working fine.

**Comment by ericangeles** [comment]
@tjamesallen15 I see that it has something to do with the visual tests?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 I see that it has something to do with the visual tests?

Oh. I'll push another update. Thanks! :)

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks a little funny too me.

1. Maybe change `.modal-header` padding to bring it up so the x is centered with it.. This looks close. I know this is a design change but the text seems pretty far down.
```
modal-header {
    padding: 16px 16px 0;
```
2. Also do i have to resize the page to a specific size? As im not sure how to verify the issue. The text never seems to go to ...

**Comment by tmcconechy** [comment]
Also FYI i merged http://localhost:4000/components/modal/test-modal-datagrid-escape-closing.html which shows the overlap as well. Might want to test this page too with this fix and pull that on and make sure...

Screen Shot 2021-12-14 at 10 05 07 AM

**Comment by tjamesallen15** [comment]
> http://localhost:4000/components/modal/test-modal-datagrid-escape-closing.html

Hello, @tmcconechy , I tried clicking this link and it shows 404. I also pulled the latest version of this branch,

**Comment by ericangeles** [comment]
@tjamesallen15 can you fix the conflict and try it again?

**Comment by tjamesallen15** [comment]
A89FB90B-CDFC-4224-A8B3-A46D8419EB85

Fix the UI already.

**Review by tmcconechy — APPROVED** [review]
Looks good now @tjamesallen15 - just need to update the images related to it but approving 👍🏻

**Review by deep7102 — APPROVED** [review]

**Review by ericangeles — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
