### PR TITLE
5487 - Datagrid: Tree list indentation is not left aligned

### LINKED ISSUE #5487: Datagrid: Tree list indentation is not left aligned when row has no children and datagrid row height is extra small
**Describe the bug**
Tree list indentation is off when row has no children and datagrid row height is extra small.

**To Reproduce**

1. Modify test-post-renderer-tree.html and add the following option. `rowHeight: 'extra-small'`
2. Go to test-post-renderer-tree.html
3. Notice the left alignment is off when a row has no children. It makes it appear as if they are children of the previous row when they aren't.

**Expected behavior**
Row values should left align properly.

**Version**
4.38.0-dev,  4.52.2

**Screenshots**
extra-small-row-height-tree-indent-issue
extra-small-row-height-tree-indent-issue-1

**Platform**
 - Landmark
 - Windows 10 
 - Chrome
 - 92.0.4515.131

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Changed `short` to small/extra small in row tab size condition

**Related github/jira issue (required)**:
Closes #5487

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/datagrid/example-tree.html or http://localhost:4000/components/datagrid/test-tree-editable.html or http://localhost:4000/components/datagrid/test-tree-export.html any nested tree with row height option control
- Toggle row height options
- See rows with +/- icon are aligned with rows without the icon

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@andriivarhanov seems like we need to update a few visual regression images https://github.com/infor-design/enterprise/pull/5516/checks?check_run_id=3341251354#step:12:3041

For ino on setting that up use the https://github.com/infor-design/enterprise/blob/main/docs/TESTING.md#working-with-visual-regression-tests section

**Comment by andriivarhanov** [comment]
@tmcconechy thanks, I've added regression images

**Comment by ericangeles** [comment]
@andriivarhanov looks good! One more thing, can you add a log for the fix?

**Comment by andriivarhanov** [comment]
@ericangeles sure, added

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
