### PR TITLE
4940 - Dropdown Scroll Bar Creates Overflow in Classic Theme

### LINKED ISSUE #4940: Dropdown: Scroll bar creates dropdown option overflow in Classic themes
**Describe the bug**
For a dropdown that allows two digits (width of 54px) and in a classic theme, when there are enough dropdown options to have a scroll bar the options will have one digit and the start of an ellipsis as overflow. This issue does not occur with a new theme and the same dropdown sizing.

**To Reproduce**
1. Go to the attached html page
2. Select a new theme
3. Select the dropdown
4. Note that the two digit numbers appear
5. Select a classic theme
6. Select the dropdown
7. Note that the two digit numbers now have an overflow

[example-widths.zip](https://github.com/infor-design/enterprise/files/6125952/example-widths.zip)

**Expected behavior**
For a dropdown with a width large enough for two digits, that the options will appear without overflow in both the new and classic themes.

**Version**
- ids-enterprise: v4.38.0

**Screenshots**
Dropdown with a classic theme:
Dropdown Classic Theme

Dropdown with a new theme:
Dropdown New Theme

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.82 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Dropdown select inputs are not fully visible in Windows 10 Chrome.

**Related github/jira issue (required)**:

Resolves #4940 

**Steps necessary to review your pull request (required)**:

- Pull, build, run
- Visit new test pages in Windows 10 Chrome
  - http://localhost:4000/components/dropdown/test-widths.html?theme=classic&mode=light&colors=0066D4
  - http://localhost:4000/components/dropdown/test-short-field-with-scrollbar.html?theme=classic&mode=light&colors=0066D4
- Look at New and Classic themes and ensure there is no overflow as described in the issue

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@davidcarlsonberg would it work to make the padding smaller instead of zero? Maybe 4px? ish.. Seems to be a little close too the arrow
Screen Shot 2022-03-18 at 9 41 42 AM

What do you think @s-werking ?

**Comment by s-werking** [comment]
I think historically the input has been pretty close to the arrow when the dropdown is closed, but it wouldn't hurt to move it out a bit. I also noticed that the scroll bar overlaps the dropdown list when in Firefox (classic and new themes) when the scroll bar is hovered:
image

**Comment by ericangeles** [comment]
I did a test on Mac (mobile using emulator chrome) and it's too close with the icon close. See screenshot. 

mobile-view

**Comment by tmcconechy** [comment]
Yeah i agree lets give it more space

**Comment by tmcconechy** [comment]
padding looks good. what do you think @s-werking ?
the only question i have is on http://localhost:4000/components/dropdown/test-short-field-with-scrollbar.html?theme=classic&mode=light&colors=0066D4 the field looks right aligned but when i open it the list is right aligned? Is that wrong?

**Comment by s-werking** [comment]
Looks good to me!

The styling in http://localhost:4000/components/dropdown/test-short-field-with-scrollbar.html?theme=classic&mode=light&colors=0066D4 forces a left text alignment when the dropdown is open and the fix looks good (in my opinion) on there as well.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
