### PR TITLE
4933 - removed unnecessary css top property calls to fix select look up component alignment

### PR DESCRIPTION
**Pull request by danielortiz1982**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Removed scss/css top from the **<svg class="close icon" focusable="false" aria-hidden="true" role="presentation">** DOM element to reposition it properly inside the input field. 

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/4933

**Steps necessary to review your pull request (required)**:
Include:
- Open up a browser window and navigate to the following URL 
(http://localhost:4000/components/lookup/example-index.html)
- Open up the modal window by clicking on the magnifying glass on the right side of the input field.
- Once opened you can type inside the search input, the X icon should now appear and be completely functional. 
- Browser testing Images below. The OS and version details are included in the screenshots as follow 
(Windows os_version=8 1 browser=Edge browser_version=89 0)
FireFox_86_local
os=android os_version=11 0
os=iOS os_version=13 0
os=Windows os_version=10 browser=Chrome browser_version=89 0
os=Windows os_version=10 browser=Edge browser_version=89 0
os=Windows os_version=10 browser=Firefox browser_version=86 0
os=Windows os_version=10 browser=Opera browser_version=74 0
safari_14_local

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
FYI - mentioned "offline" to @danielortiz1982 that we should also look at the button + icon issue reported here

**Comment by EdwardCoyle** [comment]
@tmcconechy I reviewed this with @danielortiz1982 and we aren't sure about the icon + text misalignment on buttons.  From what we can tell everything seems fine on both master and this branch (no failing visual regressions either).  Are you aware of any specific examples of misalignment on a page/browser/os combo?

**Comment by tmcconechy** [comment]
Cindy mentioned https://user-images.githubusercontent.com/39101346/110693128-18332200-81b5-11eb-8863-9da5c14f190a.png

I was seeing that the triangle icon is slightly low in the primary button. (maybe 1 px) but if you guys say its actually centered and its an illusion or something we can definitely let that part go?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I see two minor issues (i think maybe we want to try and move the button around not the icon).

- test page http://localhost:4000/components/tabs-module/example-category-searchfield.html you will see if you type in the X that the X is not 100% aligned in the middle vertically you can see this on http://localhost:4000/components/lookup/example-index.html as well but only maybe 1px there
- on http://localhost:4000/components/lookup/example-index.html
1. type in the field
2. hit tab -> notice the button is focused but the X is invisible

**Comment by tmcconechy** [comment]
1. Just a lint error and then this looks good https://github.com/infor-design/enterprise/pull/4955/checks?check_run_id=2142432853#step:8:62
2. Still see the issue when you tab that its not visible. looks like
- its this rule -> perhpas it needs to be set to display:block when focus is on
```
.toolbar-searchfield-wrapper:not(.active) .icon.close {
  display: none;
}
```
- note that to debug you might need to remove the hide-focus class (this is an old thing we are getting rid of where you dont show focus on clicking)
- once you do that its still slightly low in alignment

**Comment by danielortiz1982** [comment]
@tmcconechy Thanks, I was looking for that scss/css prop... I will fix the lint error and edit that property to see if that does the trick.

**Comment by ericangeles** [comment]
Looks good @danielortiz1982 . I just saw an issue on searchfield component where the search icon goes to the top section of the search field. 

Screen Shot 2021-03-19 at 10 08 30 PM

Maybe change the approach of making the clear icon center instead of removing the,

```
    .icon.close {
        top: 12px;
    }
```

**Review by ericangeles — CHANGES_REQUESTED** [review]
Looks good @danielortiz1982 . I just saw an issue on searchfield component where the search icon goes to the top edge section of the search field. 

Screen Shot 2021-03-19 at 10 08 30 PM

Maybe change the approach of making the clear icon center instead of removing the,

```
    .icon.close {
        top: 12px;
    }
```

**Comment by danielortiz1982** [comment]
> Looks good @danielortiz1982 . I just saw an issue on searchfield component where the search icon goes to the top edge section of the search field.
> 
> Screen Shot 2021-03-19 at 10 08 30 PM
> 
> Maybe change the approach of making the clear icon center instead of removing the,
> 
> ```
>     .icon.close {
>         top: 12px;
>     }
> ```

Hi @ericangeles 
Thanks for the heads up. I am not seeing this on my feature branch, I just merged in master and can't seem to reproduce the error above. I will look through all of the components that use that icon. 
Screen Shot 2021-03-22 at 10 48 54 AM

**Comment by tmcconechy** [comment]
@danielortiz1982 i think he's testing this related page https://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html so try and test there. Looks like your css may have unintentionally moved another icon

**Comment by danielortiz1982** [comment]
> @danielortiz1982 i think he's testing this related page https://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html so try and test there. Looks like your css may have unintentionally moved another icon

I see. Will have a look. Thanks @tmcconechy

**Pull request closed without merging**
