### PR TITLE
8272 - Adjusted icon alignment and color for searchfield in tabs

### LINKED ISSUE #8272: Tabs Module: search icon is not visible on Light and High Contrast mode New version and misaligned 'x' button
**Describe the bug**
Tabs Module: search icon is not visible on Light and High Contrast mode New version and misaligned 'x' button 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html?theme=new&mode=light&colors=default 
2. Try on all modes 
3. Play around with the search field 
4. Notice that the search icon looks off on Light and High contrast mode 
5. Notice that the 'x' icon is misaligned after populating the search field 

**Expected behavior**

- 'x' icon should not be misaligned 
- search icon should be visible on all modes and versions

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted icon alignment and color for searchfield in tabs

**Related github/jira issue (required)**:

Closes #8272 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/tabs-module/example-category-searchfield.html
- Check icons in searchfield (category, clear, etc) are viewable and aligned right
- Check in all modes

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista this looks good but the input field looks like it sits a little height in the tab. I think it should be the full height (no blue showing)

Screenshot 2024-01-08 at 10 36 39 AM

**Comment by ericangeles** [comment]
@yohannahbautista need also to adjust the height of the `add-tab-button`, and adjust the icon.

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]
Looks good! Thanks, @yohannahbautista 🍌

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
image

image

- Close button is still misaligned in Classic

image

- Hover state color issue

image

- Close button in tabs is misaligned


**RTL**
image

- Missing border between search and dropdown button
- More button should placed on the left most of the page

image

- Tab title alignment issue
- Close button on the dropdown menu should be placed on the left
- Dropdown text alignment should be right-aligned

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
image

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in Firefox
 '+'  icon not centered.
image

image

image

**Comment by tmcconechy** [comment]
@yohannahbautista FYI i merged the new icons stuff so the icons changed. I do see a couple minor this as described by QA 

a) tab text indenting:

Screenshot 2024-01-12 at 10 16 45 AM

b) some extra borders on RTL

Screenshot 2024-01-12 at 10 16 35 AM

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
I believe, the `more` icon should be placed in the left-most corner of the page in RTL.
image

_For reference only_:
image

**Comment by jbrcna** [comment]
+ icon is now fixed in new theme
**firefox browser** 
image

failing in classic
image

the searchfield has a gap at the bottom in new theme
image
compare to classic theme
image

**Comment by yohannahbautista** [comment]
> I believe, the `more` icon should be placed in the left-most corner of the page in RTL. image
> 
> _For reference only_: image

@glenlieorillo @ericangeles 
This isn't an actual header component so it doesn't behave exactly like it when switching LTR to RTL. More button is in a normal toolbar that was placed next to the searchfield. 
https://github.com/infor-design/enterprise/blob/main/app/views/components/tabs-module/example-category-searchfield.html#L10

I can change it to follow this, but this would only be in the example page (probably some if-else situation where I have two html templates that swap) and not in any component which is why I didn't bother with it.

**Comment by tmcconechy** [comment]
im ok with just changing this in the example @yohannahbautista - just so QA can pass the example 👍🏻

**Comment by jbrcna** [comment]
the issue in firefox is now fixed. 

image

classic
image

**observation:**
when using firefox browser with classic theme, the x icon is moving when hovered.

Large GIF (1110x444)

**Review by tmcconechy — APPROVED** [review]
Good for me. Pending QA

**Review by glenlieorillo — APPROVED** [review]

**Review by janahintal — DISMISSED** [review]
image
Observation
There's a lot of space from the search field and tabs
image

Can't focus on 'x' icon when hovered or using key press (tab key)
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
