### PR TITLE
7957 - Fix slider console error.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Slider produces error when used in mobile/responsive view. Added handling of slider touch events.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7957

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/slider/example-vertical.html
- Switch to responsive/mobile view.
- Ensure overflow/scroll is active.
- Use sample sliders.
- There should be no console error and page should not scroll while using a slider.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — CHANGES_REQUESTED** [review]
image

Sample of the labels cannot be seen in the mobile view

**Review by jbrcna — COMMENTED** [review]
this is now working as expected. However, the text is cut
image

**Review by tmcconechy — DISMISSED** [review]

**Review by tjamesallen15 — APPROVED** [review]

**Review by max-hizon — APPROVED** [review]
Works as expected

https://github.com/infor-design/enterprise/assets/79514236/ed5c90df-183a-4f94-b0d7-3358c18e0478

Labels no longer crop
image

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
I just noticed that the tick and labels are not properly aligned.

image

image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected. Thanks, @RJ-Csc!

image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
