### PR TITLE
8159 - Charts legend color alignment

### LINKED ISSUE #8159: Sinkpage: Charts - Legend color positioning issue
**Describe the bug**
Focus state overlaps with legend color (Classic).

**To Reproduce**

1. Go to https://4890-beta0-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default
2. Scroll down to Charts: Vertical Bar Chart, Stacked Bar - Vertical, Stacked Bar - Vertical 100%, Grouped Bar Chart, Line Chart, and Area Chart
3. Click on legends

**Expected behavior**
Focus state and legend color should not overlap.

**Version**

- ids-enterprise: 4890-beta0

**Screenshots**
image

image

**Platform**
 - All major browsers

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Flex alignment was added to the legend items on the charts

**Related github/jira issue (required)**:
Closes #8159

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/?theme=classic&mode=light&colors=default
- scroll down to Charts: Vertical Bar Chart, Stacked Bar - Vertical, Stacked Bar - Vertical 100%, Grouped Bar Chart, Line Chart, and Area Chart
- click on legends
- see that the legend color is aligned with the focus border

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
See above... Comment

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — DISMISSED** [review]
image
image

image
image
image
image
image
image
image

**Comment by ericangeles** [comment]
@tmcconechy you want this to push on 4.90?

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/92e3ac0a-3077-4590-be81-721ba441ca27

**Review by jbrcna — CHANGES_REQUESTED** [review]
sorry I noticed that the legend label is not centered in firefox
image

**Review by tmcconechy — DISMISSED** [review]

**Comment by andrivarhanov** [comment]
> sorry I noticed that the legend label is not centered in firefox image

should be fixed for Firefox

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]
image

local
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
