### PR TITLE
7079 - Searchfield design fixes

### LINKED ISSUE #7079: Searchfield: new design issues
**Describe the bug**
some issues have been found while testing #6707 

**To Reproduce**

**Issue 1**
`light dark theme can’t see the border when hovered.`
1. Go to 'https://main-enterprise.demo.design.infor.com/components/listview/example-search.html?theme=classic&mode=dark&colors=2578a9'
2. hover over the searchfield
3. See error

**Issue 2**
`new high contrast hover is blue`
1. Go to 'https://main-enterprise.demo.design.infor.com/components/listview/example-search.html?theme=new&mode=contrast&colors=003876'
2. hover over the searchfield
3. See error

**Issue 3**
`New dark hover is not visible but when not hovered it is highlighted. same with classic theme`
1. Go to 'https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html?theme=new&mode=dark&colors=0066D4'
2. hover over the searchfield
3. See error

**Expected behavior**
should be slate10 stroke on hover

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
**Issue 1**
light dark theme can’t see the border when hovered.
image

**Issue 2**
image

**Issue 3**
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated colors in contrast and dark modes for searchfield

**Related github/jira issue (required)**:

Closes #7079 and #7089

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/listview/example-search.html?theme=classic&mode=dark&colors=2578a9
- Hover on searchfield, should see hover border
- Go to: http://localhost:4000/components/listview/example-search.html?theme=new&mode=contrast&colors=003876
- Hover on searchfield, hover border should not be blue
- Go to: http://localhost:4000/components/lookup/example-index.html?theme=new&mode=dark&colors=0066D4
- Open lookup
- Unfocus searchfield and hover, hover border should be seen

To check width:
- Go to: 
   - http://localhost:4000/components/listview/example-filters.html
   - http://localhost:4000/components/listview/example-search.html
- Searchfield width should not be short

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
A couple suggestions... from design

1. on http://localhost:4000/components/listview/example-search.html?theme=classic&mode=dark&colors=2578a9 lets make the hover lighter (slate 01 instead of white)
2. on http://localhost:4000/components/listview/example-search.html?theme=classic&mode=dark&colors=2578a9 when focusing the field it only shows the shadow effect should also add a border (also slate 01) 
3. on http://localhost:4000/components/listview/example-search.html?theme=new&mode=contrast&colors=003876 the hover effect is only on two sides.
4. also on http://localhost:4000/components/listview/example-search.html?theme=new&mode=contrast&colors=003876 the focus effect should be the same as the hover effect but with a box shadow like http://localhost:4000/components/input/example-index.html?theme=new&mode=contrast&colors=003876
5. is also missing http://localhost:4000/components/listview/example-search.html?theme=new&mode=light&colors=003876 the focus state with boxshadow and border

Generally all search field hover and focus should be like http://localhost:4000/components/input/example-index.html but a small change to the dark mode one as its missing the focus state border and lower the border form white to slate 01

**Comment by tmcconechy** [comment]
Also can skip any visual tests for now based on https://github.com/infor-design/enterprise/pull/6731

**Comment by tmcconechy** [comment]
@yohannahbautista the only issue i still see is on 

http://localhost:4000/components/lookup/example-index.html?theme=new&mode=dark&colors=0066D4
1. the focus state on the lookup should be slate01 with the blur -> its only showing the blur
2. if you open the lookup and focus the search on the lookup it has an azure border. I think they both should be slate01 so the same.

Then i would accept

**Review by EdwardCoyle — DISMISSED** [review]
@yohannahbautista considering Tim's comments, all looks good now!

**Review by deep7102 — DISMISSED** [review]
LGTM 🍌

**Comment by tmcconechy** [comment]
I still see issue https://github.com/infor-design/enterprise/pull/7087#issuecomment-1381964756 ~ in that the main input fields do not match the focus state of the search field. So i guess we need the same focus state for all inputs and triggered.

Also i figure the focus state blue can be toned down a bit (the focus state blue effect on search). For both inputs and search

```
.lookup-modal .toolbar-searchfield-wrapper.has-focus.active.toolbar-searchfield-wrapper:focus-within {
    box-shadow: 0 0 4px 2px rgb(255 255 255 / 10%);
}
```

Also if you open the modal on http://localhost:4000/components/lookup/example-index.html?theme=new&mode=dark and unfocus the search it looks to be missing the back color in dark mode

Screenshot 2023-01-17 at 9 49 57 AM

Just try all 2 modes and themes in your testing after.

**Comment by ericangeles** [comment]
I am still getting darker focus state on trigger button. It should be slate10.

Screen Shot 2023-01-18 at 3 33 59 PM

**Review by tmcconechy — DISMISSED** [review]
minor but the hover state could be white instead of azure in dark. but i beat this one up enough so just a suggestion.

Screenshot 2023-01-18 at 1 21 55 PM

Feel free to skip any tests for now.

**Review by tmcconechy — APPROVED** [review]
I think i fixed the test issue on this PR. https://github.com/infor-design/enterprise/pull/7122

**Review by ericangeles — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
