### PR TITLE
7922 - Alabaster Cleanup Round 4

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix alabaster design issues in headers, tabs, tab-headers, tabs-module, tabs-multi components.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7922

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to the following links below
- Header -> http://localhost:4000/components/header/example-index.html?colors=ffffff
- Module tabs -> http://localhost:4000/components/tabs-module/example-index.html?colors=ffffff
- Multi Tabs -> http://localhost:4000/components/tabs-multi/example-index.html?colors=ffffff
- Header Tabs -> http://localhost:4000/components/tabs-header/example-index.html?colors=ffffff
- Vertical Tabs -> http://localhost:4000/components/tabs-vertical/example-index.html?colors=ffffff
- Test in Alabaster, Light, Dark and High Contrast (New Theme)

Branch Urls:
- Header -> https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/header/example-index.html?colors=ffffff
- Module tabs -> https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=ffffff
- Multi Tabs -> https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html?colors=ffffff
- Header Tabs -> https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=ffffff
- Vertical Tabs -> https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?colors=ffffff

Figma:
- Test Issues on https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=1029-1967&mode=design&t=YeLzMP16lxrXwxKu-0

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@talkaboutdesign one thing i am wondering is on http://localhost:4000/components/tabs-vertical/example-index.html?colors=ffffff the selection state is pretty hard to differentiate between the grey slate normal color. Is that something we want to re-consider? 

And when module tabs or multi tabs is colored http://localhost:4000/components/tabs-multi/example-index.html?colors=7928E1 i think that the non active state would look better if one color lighter?

**Comment by talkaboutdesign** [comment]
@tmcconechy the urls are not working for some reason. I believe SSL certificate issue.

**Comment by ericangeles** [comment]
@talkaboutdesign, it was just the wrong branch environment name. I've just updated it.

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
cc @infor-design/qa

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 i got one note from @talkaboutdesign can you look? what seems to be happening in this video

https://watch.screencastify.com/v/Lyj9IMaN1QxIg6RkY5JA

When you change the multi tabs:

a) you see the header height shift up and down (maybe a transition?)
b) slight 2-4 px gap between the header and edge

**Comment by tjamesallen15** [comment]
> @tjamesallen15 i got one note from @talkaboutdesign can you look? what seems to be happening in this video
> 
> https://watch.screencastify.com/v/Lyj9IMaN1QxIg6RkY5JA
> 
> When you change the multi tabs:
> 
> a) you see the header height shift up and down (maybe a transition?) b) slight 2-4 px gap between the header and edge

I found that error before and fix it during Alabaster Round 3. I'll check it again later.

**Comment by laurensteiger** [comment]
@tmcconechy doing the last QA now, the module tabs link is not working. Can it be updated thanks.

**Comment by ericangeles** [comment]
@laurensteiger here's the correct link for module tabs.

https://7922-alabaster-cleanup-round4-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=ffffff

**Comment by hey-yall** [comment]
Design QA ticket in Jira: https://jira.infor.com/browse/IDS-1748

**Comment by laurensteiger** [comment]
@tmcconechy @ericangeles Everything is good! Thank you.

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
Let's start testing this @infor-design/qa. Let me know if you have any questions.

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
