### PR TITLE
3588/3615/3616 - Modal Q/A Fixes [v4.27.x]

### LINKED ISSUE #3588: Modal - Close Tooltips attached to Toolbar Buttons when closing the Modal
Originally discovered here: https://github.com/infor-design/enterprise/pull/3582#pullrequestreview-370379804

**Describe the bug**
When clicking the close button to close a Modal, sometimes an attached Tooltip stays open for much longer than the modal does.

**To Reproduce**
1. Go to 'http://localhost:4000/components/modal/example-close-btn.html
2. Click on "Show Modal"
3. Hover the (X) Button and wait for the "Close" tooltip to appear
4. Click the Close button
5. Watch carefully.  When the modal disappears, the Tooltip will remain in the empty page space for up to a few seconds before it also disappears.

**Expected behavior**
The Tooltip should disappear right away.

**Version**
- v4.25.x

**Screenshots**
Screen Shot 2020-03-06 at 4 32 22 PM

### LINKED ISSUE #3615: Modal : Close / Cancel button is not working
**Describe the bug**
Modal : Close / Cancel button is not working

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/modal/example-cancel-close.html
2. Click on Cancel or Save button to close the modal

**Expected behavior**
Modal should close

**Version**
IDS beta 4.270-dev

**Screenshots**

**Platform**
All platform Mobile & Desktop. 

**Additional context**
N/a

### LINKED ISSUE #3616: Modal: Not opening after closing it in iOS device
**Describe the bug**
Modal is not opening after closing it in iOS device.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
2. Open the Show Modal button 
3. Close the button or Click Cancel
4. Click “Show Modal” button 

**Expected behavior**
Modal will open again

**Version**
IDS Beta 4.270dev

**Screenshots**
N/a

**Platform**
IOS Mobile Devices 
Tested in Iphone 11

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes some regressions that appear to be the result of the Modal Buttonset changes and other Modal adjustments as of v4.27.x:
- Some Modal examples were not closing as expected when clicking their close buttons, or "Cancel" buttons inside the Modal Buttonset. This was due to a change made in Modals overall, because previously, clicking almost any buttons within the Modal Buttonset that had no callback functions associated with them would cause the Modal to incorrectly close.
- Some Modal examples configured not to destroy themselves would close, but unexpectedly not reopen on iOS devices.

**Related github/jira issue (required)**:
- Closes #3588
- Closes #3615
- Closes #3616

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the demoapp.  Then:

_To test #3588:_
- Open http://localhost:4000/components/modal/example-close-btn.html in any browser
- Click the "Show Modal" button.  The Modal should open.
- Hover the "X" button.  It has a tooltip that should display.
- Click the "X" button.  When the modal closes, the tooltip should also immediately close.
- Re-open the Modal, and try to close it again by clicking the "X" button right before the tooltip appears.  The tooltip should never be visible when the modal is in the middle of closing, or is closed.

_To test #3615:_
- Open http://localhost:4000/components/modal/example-cancel-close.html in any browser
- Click the "Show Modal" button. The Modal should open.
- Clicking either button in the buttonset should cause a toast to fire, notifying the user that closing the Modal has been vetoed.
- Check the box above the buttonset labelled "Allow this Modal to close"
- Clicking either button in the buttonset should now close the Modal.

_To test #3616:_
- Open http://localhost:4000/components/modal/example-close-btn.html on an iOS device/simulator/browserstack.
- Click the "Show Modal" button. The Modal should open.
- Click either the "X" button, or either of the Modal Buttonset buttons.  The Modal should close.
- Click the "Show Modal" button again. The Modal should open again as expected.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@tmcconechy your second bullet has an open issue: https://github.com/infor-design/enterprise/issues/3588.  I believe I punted on changing this as part of another PR because of the effect it's going to have on pretty much every single Modal visual regression test;

**Comment by EdwardCoyle** [comment]
The first issue's something that I think we're only seeing now because of the test change, but's been there a bit... good to fix that one

**Comment by tmcconechy** [comment]
Ok thanks for https://github.com/infor-design/enterprise/issues/3588 seen it enough now we shuold probably get rid of it. I was thinking maybe in button.js we just actively hide `#tooltip` on click? I thought it might do that

**Comment by EdwardCoyle** [comment]
Adding WIP status for a sec, while I fix the Tooltip issue as part of this PR

**Comment by EdwardCoyle** [comment]
@tmcconechy #3588 is now fixed in this PR

**Comment by tmcconechy** [comment]
Sorry :( One new thing im seeing now

1) http://localhost:4000/components/modal/example-cancel-close.html
- open the modal
- click save (it cancels)
- now click cancel (it doesnt cancel)
- open the modal
- click cancel (it cancels)
- now click save (it doesnt cancel)
(Seems like the second one doesnt work)

**Comment by EdwardCoyle** [comment]
@tmcconechy just fixed that - was an issue in the test itself

**Pull request merged**
