### PR TITLE
4403 - Fix accessibility issue and missing audible labels

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes accessibility issue, correct the locale of time period and add missing audible labels.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4403

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/timepicker/example-index.html
- Click the timepicker icon to trigger the popup
- Open Axe in developers tool
- Click the `Analyze` button to check if there's an issue
- There should be no issue
- Check the audible labels of minutes, hours, seconds, and time period. Should be there.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
A few improvements needed here.

a) you dont need to translate all the files. the translation team will do that, i usually just translate es-ES for testing
b) Some tests appear to need adjusting
c) the issue that it " its attached to the hidden select" is still the case. the new label you added isnt read by the screen reader since both are disabled. need to put this label in the dropdown div for example

```
<div class="dropdown" role="button" aria-haspopup="listbox" tabindex="0">
<span><span class="audible">Hours </span>1</span></div>
```

And i I think that they labels can stay hours, minutes second instead of Time Period as that is more clear. I tested this in chrome vox BTW.

**Comment by ericangeles** [comment]
All good, @tmcconechy. One thing tho, I don't see the last issue that you mentioned, I see it as `role="option"`.

**Review by tmcconechy — COMMENTED** [review]
Im just rereading this...

`The Hour, Minutes, and Meridian inputs in time picker controls do not have valid labels, but instead rely on the current value of the input and its formatting to convey its purpose.
Although a <label> element is correctly associated with the hidden <select> element associated with these controls, the label is not announced because users are not interacting with the hidden <select>, but instead the visible custom controls.
[Code Reference]
<div class="time-parts">
    <label for="timepicker-hours-timepicker-11-id" class="audible">Hours</label>
    <select id="timepicker-hours-timepicker-11-id" data-options="{'noSearch': 'true'}" class="hours dropdown">
        ...
    </select>
    <div class="dropdown-wrapper">
        <div class="dropdown" data-options="{'noSearch': 'true'}" role="button" aria-haspopup="listbox" tabindex="0">
            <span>7</span>
        </div>
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use xlink:href="#icon-dropdown"></use>
        </svg>
    </div>
    <span class="label colons">:</span>
    ...
</div>
[Recommendation]
Consider whether it is possible to use native html <select> elements or text inputs instead of custom controls here. If this is not possible, ensure that the visible custom controls have valid labels.`

So actually the problem is more complicated i think. What im seeing with the screen reader seems incorrect.

a) its not a role="textbox" so maybe we didnt need to change that (even if it is correct then its already an input so i think we need to check the dropdown).

It acts like a button but its really a combobox/dropdown. And when i open it and arrow down i dont get read the values.

Think it should look and act like "Example 2: List Autocomplete with Automatic Selection" on 
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html when using the screen reader on the dropdowns in the picker

**Comment by ericangeles** [comment]
Was also thinking maybe we wrap the input to a div element that has a combobox role? Since the combobox role requires child element. What do you think?

**Comment by ericangeles** [comment]
So something like this,
```
<div role="combobox" aria-expanded="true" aria-haspopup="listbox">
    <input id="timepicker-main" class="timepicker" type="text" data-validate="time" aria-autocomplete="list" data-validation-events="{&quot;time&quot;:&quot;blur change enter&quot;}" aria-activedescendant>
</div>
```

**Comment by tmcconechy** [comment]
Yes i think it should work like https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html but i think we may have had it this way. And for some reason we changed it @EdwardCoyle for details? Keep in mind there a lot of functionality around the dropdown and multiselect to test for this if we do it.

**Comment by EdwardCoyle** [comment]
@tmcconechy I don't remember it being this way before, but maybe it was earlier on.  As far as the new functionality goes in the Dropdown/Multiselect, we should try to keep the current behavior as default, and maybe make automatic selection "opt-in" (boolean setting in Dropdown API).

**Comment by tmcconechy** [comment]
@EdwardCoyle i think your talking about a different issue. This one is to do with only accessibility and the reason we dont have an input element for the select and use a DIV

**Comment by EdwardCoyle** [comment]
I see, I misunderstood.  We did have the in-page element as an `<input>` before, but we moved to the `<div>` because:
- I think originally there was an accessibility problem the other way around - there was an input in the page that wasn't actually the one used, because the one that the user actually interacts is inside the dropdown list.  IIRC this was causing some other wonky things in the screen reader, but not 100% sure.
- When we adopted the tag list in the Multiselect, the display of these wouldn't be possible inside an `<input>` element.

**Comment by tmcconechy** [comment]
ok right it was the tag list stuff. Ok @ericangeles see if you can make it like https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html with aria changes but the div should stay as a div that acts like an input.

**Comment by tmcconechy** [comment]
@ericangeles i put the label in WIP as i wasnt sure if this was done. But if you think its ready to review again, please remove the label.

**Comment by ericangeles** [comment]
> @ericangeles i put the label in WIP as i wasnt sure if this was done. But if you think its ready to review again, please remove the label.

Yes, this is still WIP. Am still getting error on axe. Still finding a way to fix it.

**Comment by tmcconechy** [comment]
Can you reraise a PR when done? The change logs are all out of sorting so keep getting conflicts

**Pull request closed without merging**
