### PR TITLE
2908/2958 - Fix get modified rows method with datagrid

### LINKED ISSUE #2908: Datagrid: getModifiedRows() has duplicate entries for the same row
Describe the bug
The method getModifiedRows() may contain more than one entry for the same row.  Expect that a single entry would exist for a modified row.

1. Go to 'http://localhost:4000/components/datagrid/test-dirty-change-cell-externally.html
2. Click on 'Change Cell' button on the toolbar
3. Open the browser's debugger and examine the array returned from getModifiedRows()

Expected behavior
A modified row would appear in the returned array once

Version
v4.23.0-dev

### LINKED ISSUE #2958: Datagrid: getModifiedRows() are not correct when tabbing across row cells
Describe the bug
Tabbing across the cells of a new row, without making a change, are showing up in the results from calling the method getModifiedRows().

To Reproduce
1. Using the attached test-new-row-dirty-indicators.html
2. Click on 'Add Row' toolbar button
3. Click on 'Get Modified Rows' toolbar button
4. Examine the console to get the results returned from getModifiedRows() - are correct at this point
5. Tab across the cells of the new row without making any cell changes
6. Click on 'Get Modified Rows' toolbar button
7. Examine the console to get the results returned from getModifiedRows()

Expected behavior
Method getModifiedRows should only include rows that have been modified.

Version
v4.23.0-dev

Additional context
Related to https://github.com/infor-design/enterprise/issues/2091

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed getModifiedRows() method was not working with Datagrid. It had duplicate entries for the same row.
Added support to get Only Changed Values as return array for get modified rows method.

**Related github/jira issue (required)**:
Closes #2908
Closes #2958

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app

issue# 2908
- Navigate to http://localhost:4000/components/datagrid/test-dirty-change-cell-externally.html
- Open developer tools
- Click on button `Change Cell` on top of grid
- See in console, should return only one entry in results array

issue# 2958
- Navigate to http://localhost:4000/components/datagrid/test-new-row-dirty-indicators.html
- Open developer tools
- Click on `Add Row` toolbar button
- Tab across all the cells in new row without making any cell changes
- Click on `Get Modified Rows` toolbar button
- See in console, should return empty array
- Edit any cells and 
- Click on `Get Modified Rows` toolbar button
- See in console, should return the modified entry in results array(with data + other info type, row, col etc.)
- Click on `Get Modified Rows(onlyChangedValues)` toolbar button
- See in console, should return the modified entry in results array(with Only Changed Values)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Im not sure i understand what DataNodes only means?

**Comment by deep7102** [comment]
> Im not sure i understand what DataNodes only means?

@tmcconechy It's just the modify rows data only without other info. https://github.com/infor-design/enterprise/issues/2958#issuecomment-540666016

**Comment by tmcconechy** [comment]
Its "just what's changed" right? Maybe we need a better name for it before we commit the API.
Maybe something like "onlyChangedValues". What do you think @deep7102 @EdwardCoyle ?

**Comment by deep7102** [comment]
yes, `onlyChangedValues` looks good to me.

**Pull request merged**
