### PR TITLE
5350 - Fix Unnecessary Vertical Scroll

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the vertical scroll showing when it is really unnecessary.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5350

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/monthview/example-index.html
- Check the vertical scroll if it now hidden

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 there is a trick to this. it does need to scroll in some cases for example try http://localhost:4000/components/calendar/example-index.html and this should be possible:

Screen Shot 2021-07-06 at 9 25 18 AM

So i think the fix needs to be something where it fixes it just when its at full size and still showing (why does it show for 1/2 extra pixels)

**Comment by tjamesallen15** [comment]
@tmcconechy Not much sure if I done it correctly. I will wait for you guys to review this one tonight on your time. Open for suggestions.

**Comment by tmcconechy** [comment]
@tjamesallen15 I think i found a better /  safe fix. Can you try to add `overflow: hidden` to this rule and see if that is a better fix?

Screen Shot 2021-07-08 at 10 10 15 AM

**Comment by tjamesallen15** [comment]
Hello @tmcconechy , I tried your suggestion. It looks much better than my fix.

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
