### PR TITLE
7136 - Hero adjustments and fixes

### LINKED ISSUE #7136: Hero: Needs color adjustments and fixes
**Describe the bug**
Some of the colors and states on https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html are behaving odd now.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
2. Notice the tab colors are hard to read and states are strange
3. Click the button in top left in the header (states are weird)
4. Change colors
5. In some colors the circle pager should change

**Expected behavior**
Better color coordination - use the new design colors https://www.figma.com/file/epOdvMMse6clzIL52ymsrF/Portal-V2%3A-Component-Library?node-id=43%3A3462&t=CIXC15jacU8BGooK-0

The new design attached will change the secondary color. Also this will apply on examples like https://main-enterprise.demo.design.infor.com/components/page-patterns/test-saleshub-builder.html?colors=BB5500 with the subheader color changing there as well. Note this example isn't working https://main-enterprise.demo.design.infor.com/components/page-patterns/test-saleshub-builder.html?colors=BB5500 with color change (header stays white).

**Priorities**

- [ ] On desktop fix the tab states -> make them just use https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=1F9254
- [ ] on mobile make the circle page white in some colors 
- [ ] fix the hover state on the button -> can use tertiary button as used on header
- [ ] tabs should not disappear on mobile?
- [ ] add header + subheader example to header page
- [ ] Same issue on this page https://main-enterprise.demo.design.infor.com/components/personalize/example-form.html?colors=BB5500 ?

**Screen shots**
Screenshot 2023-01-26 at 1 29 41 PM
Screenshot 2023-01-26 at 1 29 44 PM
Screenshot 2023-01-26 at 1 29 50 PM

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates the homepage hero widget, builder header, and other section of tabs with the new design and color combination.

**Related github/jira issue (required)**:

Closes #7136 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Hero Widget
- Go to http://localhost:4000/components/homepage/example-hero-widget.html
- Check every elements/components in different colors and modes
- Quick Link tabs should be the same as the new tabs design in here http://localhost:4000/components/tabs-header/example-index.html including its states
- In non-default color, the `hero widget top` should follow this color combination in this [Figma](https://www.figma.com/file/epOdvMMse6clzIL52ymsrF/Portal-V2%3A-Component-Library?node-id=0%3A1&t=wn7fldBQp2bP639l-0) design
- Resize the page to show the circlepager. In default color, the circlepager should be dark, the rest of the colors should be white

2.) Personalize Form
- Go to http://localhost:4000/components/personalize/example-form.html
- Tabs should be the same as the new design tabs http://localhost:4000/components/tabs-header/example-index.html

3.) Sales Builder
- Go to http://localhost:4000/components/page-patterns/test-saleshub-builder.html
- Default color should be both white (header and builder header)
- Test in different colors and modes
- Remaining colors -- header should be darker than the builder header

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
looks good, the only issue I see is hero title is invisible (new light/contrast theme, default color) here http://localhost:4000/components/homepage/example-hero-widget.html
image

**Review by andriivarhanov — COMMENTED** [review]
some issue with top hero default background in classic theme, steps to reproduce:
- go to http://localhost:4000/components/homepage/example-hero-widget.html
- select classic theme, light/contrast mode, colors -> default
image

**Review by tmcconechy — DISMISSED** [review]
Aside from @andriivarhanov 's comments i'll approve based on this looking good to me. Might also want to pull main and retest due to similar fixes just merged. And there is a merge conflict

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks pretty good but this seems like the tabs are a different style (missing bottom border ect). I think we should get rid of this difference and they should look like header tabs... Or regular personalized tabs.

http://localhost:4000/components/homepage/example-hero-widget.html?colors=BB5500
http://localhost:4000/components/homepage/example-hero-widget.html

Vs https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=BB5500

I.E. should be a bottom border in default mode and same states. And if any different code / classes maybe we can make it the same

**Comment by ericangeles** [comment]
@tmcconechy am not sure if I get you Tim. The only thing that is missing compare to the new tabs are the states. The hero widget tabs doesn't have is-selected class if selected etc. Do you want to add that too?

Hover states looks the same with the new tabs design and that's the only thing I did.

**Review by tjamesallen15 — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
