### PR TITLE
6866 - datagrid icon button cut off (extra small and small row height)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where icon is not rendering properly in small and extra small row height.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6866

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-icon-buttons.html
- Select Small row height from the toolbar menu
- Change the Scale to 125%

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Review by yohannahbautista — DISMISSED** [review]

**Comment by s-werking** [comment]
Hi @tjamesallen15,
I'm seeing the bottom of some of the icons cut off now, particularly the extra-small rowheight in both 100% and 125% scale and the small rowheight in 100% scale. This can be seen better by replacing one of the column's icon with icon: 'document'.

**Review by tmcconechy — COMMENTED** [review]
I didnt see what @s-werking is seeing but it does look like it could be 1 pixel up in extra small

Screen Shot 2022-10-07 at 9 33 46 AM

**Comment by tjamesallen15** [comment]
Will fix the E2E if this PR is approved.

**Comment by ericangeles** [comment]
@tjamesallen15 it looks okay to me now. Please update the visual test.

**Comment by s-werking** [comment]
Looks good to me! Thanks @tjamesallen15

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Review by ericangeles — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
