### PR TITLE
7228 - Fix npm commands

### LINKED ISSUE #7228: Build: Cannot Run the Build on Windows
**Describe the bug**
Since making changes on #6634 the build system wont work on windows. The problem seems to be the 

```
npm run clean
```

Which errors with "Error: Illegal characters in path."

**To Reproduce**

1. On a windows machine 
2. Clone the repo
3. Cd to the cloned project
4. `npm run start` or more isolated `npm run clean`

**Expected behavior**
Should work

**Additional context**
Seems to be https://github.com/isaacs/rimraf/issues/249

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The clean commands did not work due to https://github.com/isaacs/rimraf/issues/249

**Related github/jira issue (required)**:
Fixes #7228 

**Steps necessary to review your pull request (required)**:
- pull this on a windows machine
- make sure you `npm i` from before
- test commands:

```
npm run clean:docs
npm run clean
npm run start
```

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by danielortiz1982 — APPROVED** [review]
Tested on a HP running Windows 10 all good.

**Comment by tmcconechy** [comment]
@awbuboltz your right the ids-website should be cleared. I made an update. But i think this command is almost not really needed but just in case.

**Comment by awbuboltz** [comment]
Changes make sense to me and it now works on Windows.

**Review by danielortiz1982 — DISMISSED** [review]

**Comment by tmcconechy** [comment]
cool - considering this approved but a wierd thing with the tests happened. Cant be related so retrying

**Pull request merged**
