### PR TITLE
3115 - Required long labels and field alignment

### LINKED ISSUE #443: Responsive Form: Layout multi line labels better
**Describe the bug**
When labels go over 2 lines because of screen width the input boxes underneath no longer align up and makes the screen look messy.

**To Reproduce**
1. Run the attached example markup
2. See error

**Expected behavior**
Somehow layout the labels and fields even.

**Version**
- ids-enterprise [e.g. v4.9.0 and up]

**Screenshots**
2017-09-12 15_35_24-System i Workspace - Administration (WS2016RP) - Internet Explorer

**Platform**
 - Chrome

**Additional context**
Formerly https://jira.infor.com/browse/SOHO-6799 see attached files

[Archive.zip](https://github.com/infor-design/enterprise/files/3842817/Archive.zip)

### LINKED ISSUE #987: Forms: Two-column form input field alignment issue with static text
**Describe the bug**
When using a 2-column form, the input fields across from static text do not share the same spacing or alignment.

**To Reproduce**
1. See screenshot

**Expected behavior**
they should lineup with similar spacing to keep the columns even in height.

**Screenshots**
screen shot 2018-10-11 at 9 16 55 am

**Platform**
- Web

**Additional context**
n/a

### LINKED ISSUE #3115: Forms: Responsive required field is missing the required asterisk when label overflows
**Describe the bug**
When using the responsive styling, required fields lose the asterisk when the label is too long

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/input/example-index'
2. In dev tools, add the form-responsive class to the div with the page-container class
3. In dev tools, edit the email address field's label to be something long like 'Email Address with a much longer caption that will overflow and it probably needs to be longer than this'
4. The asterisk does not appear:
image

**Expected behavior**
I would expect to see the asterisk after the ellipsis when the label of a required field is long enough to overflow

**Version**
4.22.1

**Screenshots**
image

**Platform**
chrome version  78.0.3904.87

**Additional Comments**
We're looking to fix this in our next release.  Even if the fix won't be happening right away, any information on how you would fix the styling would be appreciated for us to implement it while waiting for a fix.  Normally we wouldn't recommend having a long caption, but our customers can put whatever text they want into their UI.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Added the ability to line up data labels with inputs by adding class `field-height` to the `data` element and placing it in a responsive grid. 
-  Added the ability to use standalone required spans, this will help on responsive fields if they are cut off.
- Added the ability to add a class to rows to align the fields on the bottom, this will line up fields if they have wrapping labels or long labels with required fields. To enable this add class `flex-align-bottom` to the grid `row`. 
- Removed some team names

**Related github/jira issue (required)**:
Fixes #987
Fixes #3115
Fixes #443

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/form/example-align-field-bottoms.html
- resize the page and the labels will stay aligned until they drop even if they wrap
- click compact mode and test
- try all themes
- try also http://localhost:4000/components/form/test-wrapped-labels.html this is an older more complex example like example-align-field-bottoms so do the same tests
- go to http://localhost:4000/components/form/test-field-size-data-labels.html and see that the readonly fields align with the text fields
- try compact mode here
- test all the examples in http://localhost:4000/components/form -> should all be working the same

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Working on the e2e tests..

**Comment by ericangeles** [comment]
Noticed a small issue. When it's in `768px` browser, the icon ovelap to the next column when `compact mode` is not activated. This issue occurs also in uplift theme and different variants.

Screen Shot 2020-01-30 at 7 35 26 PM

In http://localhost:4000/components/form/example-inputs.html?theme=uplift&variant=contrast, the checkbox seems to look cutoff at the bottom area in uplift theme only.

Screen Shot 2020-01-30 at 7 48 31 PM
Screen Shot 2020-01-30 at 7 48 25 PM

**Comment by tmcconechy** [comment]
@ericangeles I fixed those two issues. Just waiting on the tests as there could be a visual regression test that needs adjusting now

**Comment by EdwardCoyle** [comment]
Not sure if this is related to these changes or not, but on http://localhost:4000/components/form/test-flex-field.html, between the fully "stretched out" mode and the responsive mode, sometimes the fields become misaligned if the label wraps:

Screen Shot 2020-01-30 at 12 23 46 PM

Everything else looked good to me

**Comment by tmcconechy** [comment]
Lets skip that page @EdwardCoyle for now - it was already there. Dont think its widely used also i dont think i added the align-bottom to that one.

**Comment by janahintal** [comment]
Hello, Issue still exists in 
image whenever there is a field validation.

**Pull request merged**
