### PR TITLE
4590/4952 - App Menu trigger button/filtering improvements

### LINKED ISSUE #4590: AppMenu: Not able to set module tabs appMenuTriggerText to empty string
**Describe the bug**
For the module tabs you can provide options to have and set the application menu trigger text:
```typescript
const TABS_DEFAULT = {
  ...otherStuff,
  appMenuTrigger: false,
  appMenuTriggerText: undefined,
  ...moreStuff,
};
```
If `appMenuTrigger` is true but `appMenuTriggerText` is not set, it will default to `Locale.translate('AppMenuTriggerText')`. We would like to be able to not have a title text i.e. "" (blank). Currently, if we provide empty string it defaults to 'Menu' due to the following on line 543 in tabs.js:
```html
<span>${this.settings.appMenuTriggerText || Locale.translate('AppMenuTriggerText')}</span>
```
So we currently specify `" "` a space which won't evaluate false, but has the side effect of the icon becomes misplaced.

**To Reproduce**
1. Set appMenuTrigger to true and appMenuTriggerText to "" (empty)
2. You will have 'Menu' as the trigger text

**Expected behavior**
When provide empty string i.e. `""` there shouldn't be a default.

**Version**
- ids-enterprise: 4.35.0-dev

**Screenshots**
The menu icon becomes misplaced by adding the space:
Screenshot 2020-11-09 at 20 15 14

**Platform**
 - All

**Additional context**
Using the nullish coalescing operator (??) ([CanIuse](https://caniuse.com/mdn-javascript_operators_nullish_coalescing)) instead of the logical or (||) would let empty string through, but at the same time set the default text appMenuTriggerText 
 is null or undefined.
```html
<span>${this.settings.appMenuTriggerText ?? Locale.translate('AppMenuTriggerText')}</span>
```

### LINKED ISSUE #4592: Application Menu: If search finds children then the parent is not expanded
**Describe the bug**
In some search conditions the results is not expanding.

**To Reproduce**
- Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/example-filterable?theme=uplift&variant=light
 -Search for "Task #3"
- Results is collpased

**Expected behavior**
Results should be expanded

**Version**
V 4.34.0

**Platform**
- Chrome Version 86.0.4240.183

I think the problem it is in done method.

### LINKED ISSUE #4952: Tree: Issue with parent nodes when deselecting in multiselect mode
**Describe the bug**
We are seeing an issue deselecting child nodes. The parent nodes become deselected incorrectly. This can be seen using IDS Example at https://master-enterprise.demo.design.infor.com/components/tree/test-plus-minus-multiselect.html

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/test-plus-minus-multiselect.html
2. Expand all nodes and select Node 2.2 (as per shot1)
3. Next, select Node 2.2 (shot2)
4. Finally, deselect Node 2.2.1.1 (shot3)

 **Expected behavior**
Checkboxes for Node 2.2 and 2.2.1 have not been cleared (as per shot3). They should have.

**Version**
- ids-enterprise: [v4.38]

**Screenshots**

 
TreeMultiSelectIssueShot1
TreeMultiSelectIssueShot2
TreeMultiSelectIssueShot3

**Platform**
 - Chrome

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes issues related to the App Menu Trigger button on Module Tabs, as well as filtering issues in the App Menu itself:

- Adds a setting to the Tabs component to allow Module Tabs instances with an App Menu trigger enabled to optionally hide the text present inside the trigger button. (#4590)
- Fixes a regression in the App Menu filtering logic that was causing accordion items that matched the filter to incorrectly be visually hidden. (#4592)
- Changed the App Menu filter logic to hide all items when filtering on a term that matches no items.  Previously, if attempting to filter on a term that matched no items, all items would be displayed. (#4592)

**Related github/jira issue (required)**:
Fixes #4590
Fixes #4592
Related to #4052

**Steps necessary to review your pull request (required)**:
Pull this branch, build, run the demoapp, then:

_Test Module Tabs App Menu Trigger:_
- Open http://localhost:4000/components/tabs-module/example-app-menu-button-audible.html?layout=nofrills
- Observe that the app menu trigger button has no text visible.
- Open a screen reading tool such as Apple Voiceover and navigate to the App Menu trigger.  It should read the word "Menu" in some way, which is still present in the DOM for accessibility purposes.

_Test App Menu Filtering:_
- Open http://localhost:4000/components/applicationmenu/example-filterable?theme=uplift&variant=light
- In the app menu searchfield, type "#3".  After filtering completes, the results should include: "Role #1 Task #3", "Role #2 Task #3", and "Role #3".
- Clear the searchfield and type "zzzzz".  After filtering completes, no items should be present in the filter results.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

@whernebrink @Milan1983

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@wherenebrink Just letting you know, after working through this issue a bit we determined that we needed to keep some text present within the App Menu trigger button in order to keep this button accessibility-friendly -- having a button with no text inside isn't friendly to screen reading tech.  Instead, we provided an additional setting you can apply to the module tabs:  `appMenuTriggerTextAudible: true;` which will cause the text to be visually hidden, but still present in the DOM.  Please check this against your environment and let us know if it works for you.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Filtering fix looks great. The only small issue is a slight misalignment of the icon in uplift mode http://localhost:4000/components/tabs-module/example-app-menu-button-audible.html?theme=uplift&variant=light&colors=0066D4&layout=nofrills

Screen Shot 2020-12-23 at 10 12 52 AM

Also should we make it just a little bit bigger (10/15 pixel on each side?)

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Comment by whernebrink** [comment]
> appMenuTriggerTextAudible

Hey @EdwardCoyle, will this be available in ids-enterprise-ng typings? Currently it's not. Also, I think if you want to provide an options to soho-tabs now (using ng 11 with all strict modes), you have to provide all options (since typing SohoTabsOptions has no optionals). Should I create a ticket for this in ids-enterprise-ng?

**Comment by tmcconechy** [comment]
I can add the missing types for 4.36 for `appMenuTriggerTextAudible` and any others i find. I usually do this for releases but forgot this time

Im not sure what you mean about options to soho-tabs tho. It should have options

**Comment by tmcconechy** [comment]
Added the missing types i found from 4.35 and 4.36 https://github.com/infor-design/enterprise-ng/pulls
Regarding tabs, i did see some others missing. I know assume thats what you mean. So i went ahead and added those as well

**Comment by whernebrink** [comment]
@tmcconechy Great thanks!

In regards to:
> Im not sure what you mean about options to soho-tabs tho. It should have options

What I meant was, if you want to provide options to soho-tabs, you need to provide all of them, or else Angular Ivy/TypeScript will be sad (I have strict mode for both turned on).

Let's say I just want to set the following options: 
```typescript
options = {
    addTabButton: true
  };
```
Markup:
```html
<div soho-tabs
     class="is-personalizable"
     [moduleTabs]="true"
     [tabsOptions]="options">
```

I get the following complaint: (error from our application - don't get confused with it saying libs etc)
Screenshot 2021-01-12 at 22 25 05

Which I assume has to do with that none of the tab options are optional e.g. 
```typescript 
addTabButton: boolean;  
// instead of 
addTabButton?: boolean;
```
Screenshot 2021-01-12 at 22 19 09

When I add the type `SohoTabsOptions` to my options you will see it in this way:
Screenshot 2021-01-12 at 22 25 49

**Comment by tmcconechy** [comment]
@whernebrink yes you have a point i think all tab options are optional so i have made them such https://github.com/infor-design/enterprise-ng/pull/968/commits/64b70bccdced35fa4da6e80949869290cc3767f9

**Pull request merged**
