### PR TITLE
5552 - Fix on Row Status not showing on Tree Grid

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes a bug where row status is not properly rendered on Tree List.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5552

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-tree-rowstatus.html
- Expand the Tree Grid
- Click `Add Row Status`
- Click `Add Status`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
Adding works fine but am getting an error when removing it.

Check the console tab
tree-err

**Comment by tjamesallen15** [comment]
> Adding works fine but am getting an error when removing it.
> 
> Check the console tab tree-err

My bad on this one. As I didn't encounter it on my first try. I pushed an updated fix to handle this one.

**Review by tmcconechy — COMMENTED** [review]
Looks great @tjamesallen15 but i was just a little bit confused on the example. Why do i have to press the button initially?

**Comment by ericangeles** [comment]
I see alert, info, and in-progress status are not removing. Is that intentional?

**Comment by tjamesallen15** [comment]
> I see alert, info, and in-progress status are not removing. Is that intentional?

Will check on this one!

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
