### PR TITLE
8582 - Fixed bug on popupmenu showing behind app menu on mobile

### LINKED ISSUE #8582: Application Menu: Mobile - Popup menu is behind the application menu - BETA 4.94
**Describe the bug**
In mobile version, a pop up menu appears behind the application menu

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html
2. Open the application menu
3. Click the **Add Item** button
4. The pop up menu is behind the application menu

**Expected behavior**
Pop up menu is in front of the application menu

**Version**

- ids-enterprise: beta 4.94

**Screenshots**
image

Animation

**Platform**
 - Device: Android 13 Galaxy S23
 - Browser Name: Chrome
 - Browser Version: 120.0.6099.144

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Z-index for app menu on mobile is 7001, so updated z-index for popupmenu

**Related github/jira issue (required)**:

Closes #8582 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- In mobile, go to: http://localhost:4000/components/applicationmenu/example-menubutton.html
- Click on Add Item
- Popup should be in front

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected. However, the button looks off when in hover state. Refer to this issue: https://github.com/infor-design/enterprise/issues/8723

image


https://github.com/infor-design/enterprise/assets/102151352/b40f1d10-b04e-4fdb-bd0a-2c79bed35139

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
However, in classic the button is off
image

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:

image

image
image

**Comment by n-ace-ancog** [comment]
@jbrcna I think the issue is still related to #8707. @ericangeles not sure if we need to it on this PR or create a new issue regarding the hover button at classic.

**Review by jbrcna — APPROVED** [review]
okay thanks for clarifying. approving now

**Comment by ericangeles** [comment]
Probably related to that, @n-ace-ancog.

**Review by tmcconechy — APPROVED** [review]
Yes the hover state is fixed on that other PR

**Pull request merged**
