### PR TITLE
5804 - Charts enhancement puppeteer script

### LINKED ISSUE #5804: Charts: Create a Puppeteer Script for disable selections
Describe the Issue
Create a unit testing for Charts' disable selections.

See attached BDD for more information.
[story_github2736.docx](https://github.com/infor-design/enterprise/files/7441999/story_github2736.docx)

Related github issue
#2736

### PR DESCRIPTION
**Pull request by jbrcna**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Charts puppeteer test for  #5804 
image

**Related github/jira issue (required)**:
Closes #5804 
Related Issue #2736 

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer
4. It should pass.

image

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by jbrcna** [comment]
Hello, @ericangeles . Thank you for clarifying. I created another PR for this. Again, I apologize; I simply thought it would be a good idea to include all other example pages because their scripts are nearly identical. the script is generic/reusable, and I can apply it to different components. I just need to make a few changes and add a few things.

this PR only has disable selection state tests. thanks :slightly_smiling_face:

**Review by ericangeles — CHANGES_REQUESTED** [review]
Am still seeing unrelated codes to the disabled selection. Please remove those. As I told you nth time that the conversion will be done by the devs so we will establish the patterns/code approach for the unit testing.

Please stick to the plan. Thanks.

**Comment by jbrcna** [comment]
Hi @ericangeles  can you clarify what are the things that shouldn't be included? if it makes sense to talk further or have a quick call please let me know

**Comment by jbrcna** [comment]
> Am still seeing unrelated codes to the disabled selection. Please remove those. As I told you nth time that the conversion will be done by the devs so we will establish the patterns/code approach for the unit testing.
> 
> Please stick to the plan. Thanks.

Hi @ericangeles , could you please elaborate on the items that should not be included? the bdd has the ff. 
image
It lacks the tooltips and pointer. I noticed a test for tooltips and pointers in column-grouped.puppeteer-spec.js, so I added it to my scripts tests.
I just added the tests for ID's cause I noticed there are automation ids present.

if it makes sense to talk further or have a quick call please let me know.

**Comment by EdwardCoyle** [comment]
@jbrcna before you update, please `git pull` this branch.  We merged #5891 to fix a problem with some unexpectedly failing tests.

**Comment by jbrcna** [comment]
thank you, @EdwardCoyle

**Review by ericangeles — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
