### PR TITLE
6979 - Tabs Header White Background Default

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will change the default background for tabs header in default and alternate.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6979

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-header/example-index.html

Please refer to the requirements on:
- https://github.com/infor-design/enterprise/issues/6979
- https://www.figma.com/file/0VaVCeINhJjxvISUQrHq2D/Tabs?node-id=1737%3A1897&t=9W7Orfuqyo1RlArt-0

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
If any E2E fails because of the adjustment will fix along the way once reviewed.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This isnt quite right yet @tjamesallen15 

1. it looks like you just copied over the http://localhost:4000/components/tabs-header/example-alternate.html example to the main and switched them around. alternate should not be effected
2. instead implement the new designs and states https://www.figma.com/file/0VaVCeINhJjxvISUQrHq2D/Tabs?node-id=1504%3A725&t=DX2f4VPERUDc8AN6-1 on the example-index.html but you need to do it only for default when the color changes they should be as before
3. side issue iss the blue effect on the tab scrolling is too much blue and the color switching doesnt work

But the main thing is this isnt the alternate tabs its changing the whole design of the normal header tabs but only for default color/theme

**Comment by ericangeles** [comment]
Am seeing a border on selected item. As per the design, it should not have border when selected.

Screen Shot 2022-12-14 at 3 36 18 PM

Also, there's a blue-ish shadow on a smaller viewport. Perhaps, use a slate 10?

Screen Shot 2022-12-14 at 3 36 27 PM

**Comment by tmcconechy** [comment]
It still looks like the http://localhost:4000/components/tabs-header/example-alternate.html example. This isnt quite right. If needed might try to start over but these are the tests Im doing:

- change the default look ofhttps://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html  to the new look not taking the alternate example and reusing it on main but add a switcher.
- missing focus states when i tab into the tabs
- alternate example should be uneffected on https://main-enterprise.demo.design.infor.com/components/tabs-header/example-alternate.html 
- changing to dark mode should look like before
- changing to contrast mode should look like before
- changing any color other than default should look like before

Doesn't seem like any of that above is working at the moment.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
New Set of issues..

1) Can you remove the text "Header Tabs Test: Spillover Example" just call it "Header Tabs"
2) This example could have 3-4 tabs instead but the overflow should still work. Maybe a second example?
3) on http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=light the fade effect should fade to white not grey.... also the button is not the right size on the right?

Screen Shot 2022-12-15 at 10 48 26 AM
4) dark mode isnt correct http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=dark (should be as before)
5) http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=contrast
6) The focus state is not working on http://localhost:4000/components/tabs-header/example-index.html when tabbing (should be on the tabs as per the design and the overflow button)
7) http://localhost:4000/components/tabs-header/example-alternate.html?theme=new&mode=contrast -> contrast mode should be the same background color as the body...(was wrong before though)
8) i noticed the focus state does work on http://localhost:4000/components/tabs-header/example-alternate.html?theme=new&mode=contrast&colors=003876 but we should make it round and visible like the new design and make it work the same on http://localhost:4000/components/tabs-header/example-index

Getting there 👍🏻  Thanks for the hard work!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good only two "questions"

- Of these 3 failing tests.. https://github.com/infor-design/enterprise/actions/runs/3716132295/jobs/6328678091#step:8:2706 
- 1 and 2 i thiink should be checked. 3 can be skipped as the page looks ok

- if i tab into the tab list the selected item doesnt seem to have a focus state...
- the overflow doesnt seem focusable (minor but it at one point did)

**Comment by deep7102** [comment]
Looks nice, just saw few thing as:

- see two different overflow styles as with and without the pipe separator
http://localhost:4000/components/tabs-header/example-alternate.html -vs- http://localhost:4000/components/tabs-header/example-index.html
image
image

- hover state on dark mode does not looks right
http://localhost:4000/components/tabs-header/example-index.html?theme=new&mode=dark&colors=0066D4
image

**Comment by deep7102** [comment]
> @deep7102 I don't see any problem with the hover state in dark mode new. The dark mode should not be affected with these new design color states.

Thanks @ericangeles

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
Seems good for now 👍🏻

**Pull request merged**
