### PR TITLE
5121 - Fix on splitter button's position

### LINKED ISSUE #5121: Splitter Component: Collapse button not working properly
**Describe the bug**
Splitter collapse button is not working properly and looks off in Test page
**To Reproduce**

1. Go to Test page https://main-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html
or 
https://main-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html
2. Splitter collapse button is not working properly and looks off in 
3. Please see screen shot attached. 

**Expected behavior**
Splitter collapse button should be working properly 

**Version**

- ids-enterprise: [e.g. v4.5.1 ]

**Screenshots**
 
Splitter2
Spitter1

**Platform**
 - All Browsers

**Additional context**
None

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Removed CSS code that made the position of the button go beyond the splitter's boundaries
- Adjusted position of button.

**Related github/jira issue (required)**:

Closes #5121 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: 
    - http://localhost:4000/components/splitter/test-collapse-button-right.html
    - http://localhost:4000/components/splitter/test-collapse-button.html
 - Click on splitter button

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
This is minor but when you click the button so that it goes to the far left its a few pixels off there..

Screen Shot 2021-06-11 at 10 08 45 AM

**Comment by yohannahbautista** [comment]
> This is minor but when you click the button so that it goes to the far left its a few pixels off there..
> 
> Screen Shot 2021-06-11 at 10 08 45 AM

Hello, I adjusted the position, is it alright now?

**Comment by tmcconechy** [comment]
@yohannahbautista 
Looks like it could be pushed over a bit more to the right. It should be centered in the "bar"

**Comment by yohannahbautista** [comment]
> @yohannahbautista
> Looks like it could be pushed over a bit more to the right. It should be centered in the "bar"

image
Is this alright?

**Review by tmcconechy — APPROVED** [review]
Looks good to me 👍🏻

**Review by ericangeles — CHANGES_REQUESTED** [review]
Looks good on `New` version but not totally align on `Classic`.

splitter

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
