### PR TITLE
8232 - Add External settings and hide show sections to module nav

### LINKED ISSUE #8232: Module Nav: Add settings for external users
We need to add a couple setting to the module nav for external user Landmark cases

1. A setting to disable and hide the module switcher, for scenarios that do not have any modules to switch among
2. A setting to relocate the user profile information in the top part of the nav to the bottom of the nav (see design reference below)

Design reference is here: https://www.figma.com/file/kibzUkQhlNArg0P4PvvpME/Module-Nav%3A-Standalone?type=design&node-id=0-1&mode=design&t=47WmlX6ZqvPenn3v-0 

Let me know if there are any other questions!

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds two new features to module nav. One is a guest section at the bottom, and the second is the ability to hide and show the search and switcher section. Additionally fixed a couple bugs.

- the utils.mergesettings worked odd and didnt properly merger. made a new function in utils
- fixed the dark mode header border it was too light
- fixed a bug in menu button that clicking when open did not toggle the menu button

**Design Review Questions**

See: https://8232-external-settings-enterprise.demo.design.infor.com/components/module-nav/example-hide-show-sections.html?colors=fff

- is guest section optionally clickable
- i made guest section a bit more compact

@krishollenbeck -> can you see if this looks good or needs anything from your end (I will add types to the wrapper when reviewed)
@talkaboutdesign -> please have a look
@EdwardCoyle -> notice change to updated a different merge function, i think this is why we have wierd workaround and settings needed in NG wrapper (just a note) but do review please

**Related github/jira issue (required)**:
Fixes #8232 

**Steps necessary to review your pull request (required)**:
- http://localhost:4000/components/module-nav/example-hide-show-sections.html?colors=fff
- click the buttons on the side when expanded and collapsed to hide/show each section
- try RTL
- try themes (in dark mode notice the bottom border)
- go to http://localhost:4000/components/popupmenu/example-menubutton.html and click to open then click again and it should now show

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by krishollenbeck** [comment]
@tmcconechy The Webapp switcher also doubled as a way to display the WebApp Title.
image

Where will the title go now? With the switcher gone?

**Comment by krishollenbeck** [comment]
@tmcconechy If we keep the switcher visible can we have readonly display?

**Review by EdwardCoyle — DISMISSED** [review]
Looks good, no issues with the deep copy

**Comment by talkaboutdesign** [comment]
The demo looked good to me.

**Comment by talkaboutdesign** [comment]
Unrelated to this new feature, I notice that text is ever so slightly pushed down in comparison to the rest of the items in the UI. Is it possibly to align middle?
CleanShot 2023-12-13 at 14 47 50@2x

**Comment by tmcconechy** [comment]
@talkaboutdesign added a small adjustment. Moving this to QA

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Close button and ellipses are overlapped.

image

Icon and text should be aligned correctly within the dropdown.

image

I noticed that the close button position is a bit higher within the searchbar.

image

image

Expand-all icon is moving upon clicking.

https://github.com/infor-design/enterprise/assets/102151352/706b83de-1818-405e-83d4-f8ca991b120b

Focus state is not centered.
image

**Comment by tmcconechy** [comment]
@glenlieorillo what browser is that

**Review by glenlieorillo — APPROVED** [review]
The bugs have been fixed. Thanks, @tmcconechy!

image

image


https://github.com/infor-design/enterprise/assets/102151352/908ec6c7-592f-47ab-8468-3e2389e531a3

image

image

**Review by jbrcna — APPROVED** [review]
Approving
Close button and ellipses are overlapped
image

Icon and text should be aligned correctly within the dropdown.
image

close button position is a bit higher within the searchbar.
image

Expand-all icon is moving upon clicking.
Focus state is not centered.
image

**Comment by jbrcna** [comment]
in RTL,  the period is positioned in the first letter (beginning of sentence) . is this expected? 
image

**Pull request merged**
