### PR TITLE
8846 - Tabs Vertical Tooltip

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add settings `moduleTabsTooltips` available for tabs vertical to for showing tooltips.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8846

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs-vertical/example-index.html
- Hover the first tab, tooltip should be shown

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
@tjamesallen15 looks good. just one lint error to fix? Note im fixing some other test issues will merge soon

**Comment by tjamesallen15** [comment]
> @tjamesallen15 looks good. just one lint error to fix? Note im fixing some other test issues will merge soon

Yep will do shortly

**Review by tmcconechy — DISMISSED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi James, this is already working as expected in New Version but not in Classic. 

Notice that the first tab doesn't have ellipsis but has tooltip in Classic. 
Test Data: [screen-capture (2).webm](https://github.com/infor-design/enterprise/assets/45757016/ffbed757-b7f5-4d5e-b98d-88adaeb27c92)

Thanks, 
Janah

**Review by jbrcna — DISMISSED** [review]
image
image

**Review by glenlieorillo — DISMISSED** [review]
image

image

**RTL**

image


image

**Comment by tmcconechy** [comment]
@tjamesallen15 seems @janahintal has a point on classic mode

**Comment by tjamesallen15** [comment]
> @tjamesallen15 seems @janahintal has a point on classic mode

I didn't notice it. Will check it. Thanks @tmcconechy

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
image

image

**Review by jbrcna — APPROVED** [review]
image
image

**Pull request merged**
