### PR TITLE
5141 - Fix anchor link on firing the change event in editor

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the anchor link in editor to fire once there's any changes that the link did.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5141

**Steps necessary to review your pull request (required)**:
- Go to http://localhost:4000/components/editor/example-with-events.html
- Select some text
- Click the anchor link buton in toolbar section
- A modal pops up, just click `insert`
- Notice below, the `Change Event Detected` should be color red
- Use also the hotkey for triggering the anchor link
- Select some text again
- Then hit `cmd+h` for the hotkey
- A modal pops up, just click `insert`
- Output should be the same

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@ericangeles something isnt 100% here. Try this example

http://localhost:4000/components/editor/example-dirty-tracking.html
- select text
- use the link modal and link some text
- in this case the dirty indicator is not shown on that change

So while the change event works the dirty functionality isnt yet

**Comment by deep7102** [comment]
I see same as @tmcconechy comment above. Also see change event fire soon the anchor model popup opens. It should only trigger if anything change.

**Comment by tmcconechy** [comment]
@ericangeles FYI i fixed a test that will likely fail for you on the other open PR

**Comment by tmcconechy** [comment]
This is working now but something was introduced in these two editor tests https://github.com/infor-design/enterprise/pull/5148/checks?check_run_id=2468052118#step:11:3926

The searchfield test is the one i fixed in the other PR

**Review by EdwardCoyle — APPROVED** [review]
This looks good to me now 👍

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
