### PR TITLE
7822 - Added listcontextmenu event

### LINKED ISSUE #7822: ModuleNav: Need to expose context menu event
**Describe the bug**
LM needs to be able to right click the dropdown menu. Then open a URL on a new link.

**To Reproduce**
1. Go to  https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
2. Click on module switcher drop down
3. right click a menu item and open in new window

**Expected behavior**
- could have either a (contextmenu) on the module nav switcher
- or a onContextMenu call back
- in the test page the URL gets inserted so it can be followed but it should only stay for right click not normal click

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a `listcontextmenu` event which is used to add data for right click, open in a new window functionality for Landmark.
ALSO IMPORTANT: Fixed a black colored button on the header in alabaster mode.

**Related github/jira issue (required)**:
Fixes #7822

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/dropdown/example-contextmenu-event.html
- open the dropdown and right click any item
- then select open in new tab. 
- check the URL it has the text of the item you clicked
- try the same thing on the module switcher on http://localhost:4000/components/module-nav/example-index.html?colors=fff (for example right click on Landing Page Designer)
- also on  http://localhost:4000/components/module-nav/example-index.html?colors=fff hover the buttons on the header and they should look as before

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @krishollenbeck @EdwardCoyle

**Review by glenlieorillo — DISMISSED** [review]
http://localhost:4000/components/dropdown/example-contextmenu-event.html

https://github.com/infor-design/enterprise/assets/102151352/84ccba01-97c6-4e57-9d66-029ef59b2e8e

 http://localhost:4000/components/module-nav/example-index.html?colors=fff 



https://github.com/infor-design/enterprise/assets/102151352/1f3ce7c5-25c6-406e-b265-d71ec704a553



image

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving
image

image

image

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
image
image

**Pull request merged**
