### PR TITLE
4950 - Fix datepicker buttonset visibility on small screens

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes the datepicker apply and cancel buttons where unable to see/reach on a small screens such as small phones (iPhones mainly) and when resizing the browser to a smaller height.

Added a vertical scrollable when viewing it and adjust some elements of datepicker to accommodate more to the smaller screens. It also supports both portrait and landscape orientation view of the small screen phones.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4950

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datepicker/example-timeformat.html
- Open the dev tools and toggle device toolbar
- Select iPhone 5/SE `(Since 320px is the minimum width that we support)`
- Test first on portrait orientation: Open the datepicker per input field
- Datepicker should fit to the screen
- Then test in landscape: Open the datepicker per input field
- Datepicker should be vertically scrollable and able to see the buttonset
- In browser, resize the height to at least `500px`
- Then open the datepicker per input field to test
- It should be vertically scrollable and able to see the buttonset

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — CHANGES_REQUESTED** [review]
The scrolling in general works pretty well, but on the last step you mentioned I'm seeing this in Mac OSX Chrome:

Screen Shot 2021-03-17 at 10 01 44 AM

**Comment by ericangeles** [comment]
> The scrolling in general works pretty well, but on the last step you mentioned I'm seeing this in Mac OSX Chrome:
> 
> Screen Shot 2021-03-17 at 10 01 44 AM

@EdwardCoyle its because I only support up to 500px max height. Let me add more px to accommodate this. Thanks!

**Comment by tmcconechy** [comment]
Also @ericangeles i see that the text is cut off... with the .... can we fix this as well? Myabe move the text over a bit if we have to. I saw this before on some smaller devices but didnt get a chance to look at it
Screen Shot 2021-03-18 at 10 25 11 AM

**Comment by tmcconechy** [comment]
You fixed all this right @ericangeles ? Im not seeing my issue anymore and it looks pretty good to me except for one thing:

Screen Shot 2021-03-22 at 9 54 45 AM

See how the container isnt extending to the edges anymore?

**Comment by ericangeles** [comment]
@tmcconechy yes I made some fixes in text being cut off. I didn't catch what your saying. So you want the popover datepicker to be adjusted at the edge of the screen?

**Comment by tmcconechy** [comment]
Yes i havnt seen it look like this before? Maybe someone used margin instead of padding? in the non mobile view it looks ok.

**Comment by ericangeles** [comment]
@tmcconechy, this is the look from the latest version. It looks not proportion to me. Should we still make the datepicker popover adjusted to the edge of the screen? I also noticed that the `monthview-container` and the `monthview-popup` don't have the same width, and it looks odd.

datepicker

**Comment by tmcconechy** [comment]
Yes, i think we should probably try as it looks quite weird.

1. It should be centered in the frame
2. Should not be a gap where the lines around the buttons touch the edge

**Comment by tmcconechy** [comment]
@ericangeles im not seeing any change? But i do see the problem. Its this rule here highlighted  in the screen shot. I dont think this rule is correct...
Screen Shot 2021-03-24 at 9 38 54 AM

**Comment by ericangeles** [comment]
So the goal would be to look like this?

mb

**Comment by tmcconechy** [comment]
I think that it should look "roughly" like this:

Screen Shot 2021-03-25 at 8 56 19 AM

- for smaller devices to make it easier can reduce the space between the edges and side of the device
- should be centered
- "lines" should extend to the bottom and edges

**Review by tmcconechy — APPROVED** [review]
Looks good now 👍🏻

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
