### PR TITLE
2289 - Uplift charts text size Adjustments [v4.19.x]

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes an issue with the Uplift Charts text size too big.

**Related github/jira issue (required)**:
#2289

**Steps necessary to review your pull request (required)**:
- Pull this branch and run the demoapp
- Navigate to http://localhost:4000/components/bar/example-index.html?theme=uplift
- See the text size not too big (should not cutoff)

### CODE REVIEW

**Comment by deep7102** [comment]
Hi @nickwynja 
http://localhost:4000/components/bar/example-index.html?theme=uplift
It works fine on this example, but not all over like below examples breaking with those `xs` size fonts.

http://localhost:4000/components/bar/test-alignment.html?theme=uplift
http://localhost:4000/components/bar/example-long-text.html?theme=uplift

**Comment by nickwynja** [comment]
If I do

```css
.chart-container {
  text {
    font-size: $theme-size-font-xs;
    font-family: $theme-font-family-base;
  }
}
```
then I get this:

image

image

image

**Comment by deep7102** [comment]
Yes! @nickwynja I did not tried with font-family, but it look great. Let me test all other places if all looks fine going to push soon -thanks

**Comment by deep7102** [comment]
Hi @tmcconechy updated now
- Text selection color
- Legend text size

**Pull request merged**
