### PR TITLE
 640 - Dynamic validation messages do not update the displayed value

### PR DESCRIPTION
**Pull request by marknolaninfor**
Test
http://localhost:4000/components/validation/test-dynamic-message.html
Change the dropdown to any value other than Hawaii and focus out of the control to trigger the validation.
The validation then contains the dynamic message including the current value.

### CODE REVIEW

**Comment by LarryAmisola** [comment]
Cannot pull this PR. It seems like you edit and pushed your master to our Master.

**Comment by clepore** [comment]
Also please follow the pull request template that is auto-populated when you create a pull request:
```
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
<!--
Example: When "Adding a function to do X",
explain why it is necessary to have a way to do X.
-->

**Related github/jira issue (required)**:
<!--
Provide a link to the related issue(s) to this Pull Request;
auto-closing github issues if necessary (example: "Closes #100")
-->

**Steps necessary to review your pull request (required)**:
<!--
Include:
- commands you ran and their output
- screenshots / videos
- test scenarios
-->

<!-- After submitting your PR, please check back to make sure tests pass on Travis. -->
```

**Comment by clepore** [comment]
@LarryAmisola since it came from an external collaborator (aka they are requesting their forked branch merge with our master branch) you will need to [checkout the pull request locally](https://help.github.com/articles/checking-out-pull-requests-locally/) to test.

**Comment by tmcconechy** [comment]
I'll redo this PR on a branch so i can fix the tests.

**Pull request closed without merging**
