### PR TITLE
4998  - Add updates for node 14

### LINKED ISSUE #4998: General: Update to Node 14
**Describe the bug**
Node 14 is working. So making so adjustments to update dev dependencies. This issue is for tracking these changes.

**Version**
- ids-enterprise: [e.g. v4.39]

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR sets the node version to 14.16.0 and adds a few updates to dependencies being used.
Most notably changed from node-sass to dart-sass (package is called just "sass").

The failing check needs to be changed after this is merged - so ignore the 12x build check failure

**Related github/jira issue (required)**:
Closes #4998

**Steps necessary to review your pull request (required)**:
```
rm -rf node_modules (or delete it)
nvm install 14.16.0
nvm  use
npm i
run npm cache clean
rm -rf node_modules  (for some reason had to do it twice)
npm i
```

Then test commands like:
- npm run e2e:ci:debug
- npm run functional:ci
- npm run build
- npm run start

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by rob2d** [comment]
@tmcconechy getting a bunch of "cannot find module" errors suddenly after removing `node_modules` and installing new deps on this branch. Will try to clear `node_modules` and run again.

**Comment by tmcconechy** [comment]
yes, I found i had to one time (i think) delete node_modules and npm i a second time. Not sure why or if i did it in the wrong order...

**Comment by tmcconechy** [comment]
FYI regarding the checks. I need to merge this then change the checks in the branches. So ignore the node 12 check failing. I can only do it once i get this in

**Comment by rob2d** [comment]
@tmcconechy got it going. Things working properly between build/dev.

One thing, and may be superficial/subjective, is it might be easier to read webpack configs when they're more sequential; in this case I don't know if it's too hacky for this teams' taste but can also do something like:

```
module.exports = {
  entry: { ...someOptions },
  plugins: [
    PluginA,
    PluginB,
    ...(isProduction? [] : [CopyWebpackPlugin({ 
      opts 
    }])
  ]
}
```

**Review by rob2d — APPROVED** [review]
put a comment on that but it's just a thought vs any issues

**Comment by tmcconechy** [comment]
Ok i feel like i tried that before and failed... With it. Maybe leave it for now as we are a bit behind on things

**Comment by rob2d** [comment]
things seem to be working but am just waiting on E2E tests locally on this one.

**Comment by rob2d** [comment]
@tmcconechy sorry had two windows open and had this issue confused with the enterprise-wc. 

(Definitely need to do a better job to organize my workflow here).

**Comment by rob2d** [comment]
@tmcconechy e2e tests were taking quite a while to run locally so hadn't completed yet as I figured functional tests can go by quicker (though this also took a while).

Since you might be a lot more familiar with the quirks, should I re-run these locally if they are passing on CI?

```
SUMMARY:
√ 1069 tests completed
× 4 tests failed

FAILED TESTS:
  Area Chart API
    × Should show on page
      Chrome Headless 89.0.4389.90 (Windows 10)
    Error: Expected 'Comp AComp BComp C' to equal 'Component AComponent BComponent C'.
        at <Jasmine>
        at UserContext.eval (webpack:///./test/components/area/area-api.func-spec.js?:115:98)
```

**Comment by tmcconechy** [comment]
Yeah sometimes a couple randomly fail - usually take a quick look and rerun. If it fails consistently definitely we fix.
I actually have not see that one cause an issue.

**Review by rob2d — APPROVED** [review]

**Pull request merged**
