### PR TITLE
6725 - Change inline width only if column width is specified

### LINKED ISSUE #6725: DataGrid: In modal gets inline style which is not desired
**Describe the bug**
You can reproduce this issue by checking out `14.1.x` build and run it.

Then go M > Modal Dialog 

Click on Dialog with Data Grid 

image

image

Now if you check out `14.0.x` build and start it

image

image

You can already notice a visible difference. The modal in 14.0.x is wider, and does not have added inline width style.

**To Reproduce**

The repository used is `enterprise-ng` to reproduce.

**Expected behavior**
The inline width style is not desired.

**Version**
- ids-enterprise-ng: 14.2.1

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Column width will only change if it's specified in column settings.

**Related github/jira issue (required)**:

Closes #6725 

**Steps necessary to review your pull request (required)**:

- Pull this branch and build
- Use this IDS version to build in IDS NG
- Build and run IDS NG
- Go to: http://localhost:4200/ids-enterprise-ng-demo/modal-dialog
- Click on "Dialog with DataGrid"
- Datagrid should be in default width and have no inline width style on the table element

Using the same IDS build, test the issue mentioned here: https://github.com/infor-design/enterprise-ng/pull/1361

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@claudenbach can you test this fix out agains https://github.com/infor-design/enterprise-ng/issues/1358 i wonder if its the same fix?

**Comment by claudenbach** [comment]
Let me do some testing to confirm.

**Review by tmcconechy — COMMENTED** [review]
Not sure if this is ok or not but i can see a difference on:

http://localhost:4000/components/datagrid/test-modal-datagrid-tooltips.html
vs
https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html

and
https://main-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid-tabbing.html
vs
http://localhost:4000/components/datagrid/example-modal-datagrid-tabbing.html

Might be ok, but i'm still confused about the impacts of this issue

**Comment by claudenbach** [comment]
Yes, this fix does resolve the issue identified with https://github.com/infor-design/enterprise-ng/issues/1358.

**Comment by tmcconechy** [comment]
ok good 👍🏻 @claudenbach and i found my question was because my page was not "tall" enough causing scrolling, so ok for me here then

**Comment by tmcconechy** [comment]
@guoliang can you test your use case with this fix? @yohannahbautista can we add some test?

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
