### PR TITLE
5336 - Fix on nan value in sliders

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the NaN value showing on tooltip in sliders.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5336

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/slider/example-range.html
- Play around the slider

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — DISMISSED** [review]
Nice fix! 🍌

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I think im still seeing the issue if i

- click on the slider example text
- hit tab onto the slide and it shows NaN immediately

**Comment by deep7102** [comment]
Saw same as @tmcconechy 

image

**Comment by tjamesallen15** [comment]
New fix is up! Waiting for you guys to review it! Thanks.

**Review by tmcconechy — APPROVED** [review]
Looks 👍🏻  now. Thanks @tjamesallen15

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
