### PR TITLE
7383 - Popupmenu button isn't visible 

### LINKED ISSUE #7383: Popupmenu/CAP: Popupmenu button isn't visible when the menu is open and is in a CAP header in classic theme dark mode
**Describe the bug**
**In classic theme dark mode** - when there's a popupmenu in a contextual action panel header, the popupmenu button has the same color as the header when the menu is open, resulting in it not being visible.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/test-complex-toolbar.html?colors=50535A&theme=classic&mode=dark
2. Click on "Contextual Action Panel" to open the CAP
3. Click on "..." to open the popupmenu
4. Notice that the color of the popupmenu button is changed and no longer visible

**Expected behavior**
The button should be a different color.

**Version**
- ids-enterprise: 4.80.1

**Platform**
 - Infor Application/Team Name: Homepages

**Additional context**
In New theme, the button color is set to `#606066` and looks like this:
image

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added additional selector so that buttonset width isn't changed

**Related github/jira issue (required)**:

Closes #7383 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/contextualactionpanel/test-complex-toolbar.html
- Click on Contextual Action Panel
- More menu should be on toolbar

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — COMMENTED** [review]
Popup menu button is already fixed. However, the search box border looks off.

http://localhost:4000/components/contextualactionpanel/test-complex-toolbar.html?theme=new&mode=dark&colors=default
image

**Comment by janahintal** [comment]
HI @yohannahbautista, still failing in responsive view. 
image

**Comment by ericangeles** [comment]
@yohannahbautista can you check these comments?

**Review by glenlieorillo — APPROVED** [review]
QA Approved.

Tested in: http://localhost:4000/components/contextualactionpanel/test-complex-toolbar.html

image


https://user-images.githubusercontent.com/102151352/234464827-5c3ce818-6653-499c-9e05-30ac9291ac8a.mov

**Review by ericangeles — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]

**Pull request merged**
