### PR TITLE
8065 - Make slate color darker

### LINKED ISSUE #8065: Colors: Change slate 01 to a more "visible" color
**Describe the bug**
On some screens / monitors and based on user feedback the slate 01 color is too light. Design made it darker.

**To Reproduce**

1. Go to http://localhost:4300/
2. Check http://localhost:4000/components/module-nav/example-index.html
3. Check http://localhost:4000/components/datagrid/example-index.html
4. Check http://localhost:4000/components/cards/example-index.html?theme=new&mode=contrast&colors=default
5. Smoke test http://localhost:4000 and http://localhost:4000/components for issues

**List Of Areas with  (possibly) Slate 01**

- http://localhost:4000/components/applicationmenu/test-six-levels.html -> h1-h5 content
- http://localhost:4000/components/masthead/example-index.html -> masthead title text
- http://localhost:4000/components/datagrid/example-index.html -> header color
- http://localhost:4000/components/popupmenu/example-index.html?theme=new&mode=dark&colors=default -> menu items
- http://localhost:4000/components/module-nav/example-index.html?colors=fff -> module nav bg color
- http://localhost:4000/components/tabs-vertical/example-index.html -> background color (looks good)
- http://localhost:4000/components/header/example-breadcrumbs.html -> header breadcrumb color
- http://localhost:4000/?theme=new&mode=contrast&colors=default -> lots in contrast mode
- http://localhost:4000/?theme=new&mode=dark&colors=default -> lots in dark mode

**Expected behavior**
Darker slate

**Additional context**
https://jira.infor.com/browse/IDS-1721

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

For initial testing. I will make this change to the ids-identity repo for the real fix.

**Related github/jira issue (required)**:
Fixes #8065 

**Steps necessary to review your pull request (required)**:
**List Of Areas with  (possibly) Slate 01**
Check things look ok in all themes (easies on kitchen sink http://localhost:4000/). Some call outs:

- http://localhost:4000/components/colors/example-index.html slate 01 should be #f5f5f5
- http://localhost:4000/components/applicationmenu/test-six-levels.html -> h1-h5 content
- http://localhost:4000/components/masthead/example-index.html -> masthead title text
- http://localhost:4000/components/datagrid/example-index.html -> header color
- http://localhost:4000/components/popupmenu/example-index.html?theme=new&mode=dark&colors=default -> menu items
- http://localhost:4000/components/module-nav/example-index.html?colors=fff -> module nav bg color
- http://localhost:4000/components/tabs-vertical/example-index.html -> background color (looks good)
- http://localhost:4000/components/header/example-breadcrumbs.html -> header breadcrumb color
- http://localhost:4000/?theme=new&mode=contrast&colors=default -> lots in contrast mode
- http://localhost:4000/?theme=new&mode=dark&colors=default -> lots in dark mode

** Design QA Links**
- https://8065-slate-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html -> h1-h5 content
- https://8065-slate-enterprise.demo.design.infor.com/components/masthead/example-index.html -> masthead title text
- https://8065-slate-enterprise.demo.design.infor.com/components/datagrid/example-index.html -> header color
- https://8065-slate-enterprise.demo.design.infor.com/components/popupmenu/example-index.html?theme=new&mode=dark&colors=default -> menu items
- https://8065-slate-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff -> module nav bg color
- https://8065-slate-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html -> background color (looks good)
- https://8065-slate-enterprise.demo.design.infor.com/components/header/example-breadcrumbs.html -> header breadcrumb color
- https://8065-slate-enterprise.demo.design.infor.com/?theme=new&mode=contrast&colors=default -> lots in contrast mode
- https://8065-slate-enterprise.demo.design.infor.com/?theme=new&mode=dark&colors=default -> lots in dark mode

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@talkaboutdesign - the URLS arent working can you review local. Need to sync with Artem but not sure if he's available

**Comment by talkaboutdesign** [comment]
> @talkaboutdesign - the URLS arent working can you review local. Need to sync with Artem but not sure if he's available

got it. Will run locally for now. But will be a challenge for testing on my windows machine.

**Comment by tmcconechy** [comment]
@talkaboutdesign note that the URLS work now. For testing

**Comment by ericangeles** [comment]
Things that I've noticed, @tmcconechy 

https://8065-slate-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?colors=ffffff&theme=new&mode=dark

The background color of the body and the accordion page are the same in dark mode, making it appear extended. (More on design feedback)
Screenshot 2023-10-16 at 7 40 37 PM

---

https://8065-slate-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=new&mode=dark&colors=ffffff#excluded-vendors

Here's another request for design feedback. When viewing on mobile (in the alabaster color and dark mode combination), please take a look at the gradients. They don't seem correct. Can they be improved?

Screenshot 2023-10-16 at 7 40 45 PM

**Comment by tmcconechy** [comment]
@ericangeles i fixed the tab fade. The other issue i think it looks OK. Not sure what else to do. But lets see when @talkaboutdesign reviews

**Comment by talkaboutdesign** [comment]
Good to go. @hey-yall lets make a design ticket for current sprint to update Slate01 color in Figma to the adjusted value at #f5f5f5.

**Review by ericangeles — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@ericangeles FYI im going to make the change in the ids-repo and adjust the PR

**Comment by ericangeles** [comment]
Sure thing, @tmcconechy

**Comment by tmcconechy** [comment]
cc @infor-design/qa

**Comment by jbrcna** [comment]
please see my findings below

`http://localhost:4000/components/colors/example-index.html slate 01 should be #f5f5f5`
in https://8065-slate-enterprise.demo.design.infor.com/components/colors/example-index.html
image
in local
image


https://8065-slate-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?theme=classic&mode=light&colors=default
in classic the active state focus highlight is not full/ cut off
image

https://8065-slate-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=classic&mode=dark&colors=default - in datagrid dark mode when you click order date column multiple times, the column next to it changes its color

https://github.com/infor-design/enterprise/assets/56722184/681c2efe-47e3-4cbb-9f91-7e30b5c8d3d5

https://8065-slate-enterprise.demo.design.infor.com/?theme=new&mode=contrast&colors=default - should be #f5f5f5
image

**Comment by ericangeles** [comment]
@tmcconechy, is this accidentally closed?

**Comment by tmcconechy** [comment]
I think it was closed because it was merged. Some of the points that @jbrcna made should be resolved (because i didnt properly change the color for testing).

Anything else can make a new issue.

**Comment by ericangeles** [comment]
Oh okay, I thought it was a PR.

**Comment by tmcconechy** [comment]
BTW I noticed the demo apps might not have the new package so thanks for bring it up. I did actually miss the comments from @jbrcna i thought it was approved https://github.com/infor-design/enterprise/commit/5c2680ebaf1c51069a2d9e35ebc70cae49577806

But that should resolve issues where the demos show the old color. Anything else lets make a new issue and i';ll recheck. Give it 20-30 minutes to update main. https://main-enterprise.demo.design.infor.com/components/colors/example-index.html

**Comment by jbrcna** [comment]
slate 01 is now correct #f5f5f5
image

but in https://main-enterprise.demo.design.infor.com/?theme=new&mode=contrast&colors=default
or
https://8065-slate-enterprise.demo.design.infor.com/?theme=new&mode=contrast&colors=default
image

**Comment by jbrcna** [comment]
created new issue for active state/focus highlight issue
https://github.com/infor-design/enterprise/issues/8109

**Comment by hey-yall** [comment]
Reminder that for changes like this, we also need to tap a designer to update the Figma files. Discrepancies between the doc site and the Figma library are causing team issues. Going forward, please tag me so I can make a ticket for updating Figma. Thanks!

**Comment by tmcconechy** [comment]
@hey-yall ok i just assumed they did but when they put it in a seperate file i guess it gets lost. Who should we ping @talkaboutdesign ?

**Comment by hey-yall** [comment]
> @hey-yall michal already made those changes we had a ticket for it.

Still shows as FAFAFA in the 4.8 library file which a partner linked as a source of confusion. I made a ticket for next sprint to correct (https://jira.infor.com/browse/IDS-1810) to align info across systems of record.

**Pull request closed without merging**
