### PR TITLE
Chore - Add new translations

### LINKED ISSUE #8489: FileUploadAdvanced component Spanish language issue
**Describe the bug**
We are using IDS 4.91.0. 
We are using fileupload advanced component to upload files using browse and drag drop files option. We are unable to view select files to browse in Spanish language.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=es
2. There is no "upload files" link like the other languages.

**Expected behavior**
The "upload files" link should exist like the other languages.

**Version**

- ids-enterprise: [v4.91.0]

**Screenshots**
image

**Additional context**
It is similar to #6226 .
Only need to update from `<span class=»hyperlink»>` to `<span class="hyperlink">` in es-ES.js.

It's a regression issue caused by this commit https://github.com/infor-design/enterprise/commit/bd42e45477f6163435bd32b6aed39958a2a4784a# on 22 Nov 2023.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds new translation dump, fixes an issue 

**Related github/jira issue (required)**:
Fixes #8489 

**Steps necessary to review your pull request (required)**:
- tests pass
- go to http://localhost:4000/components/fileupload-advanced/example-index.html?locale=es 
- page should have a link in it now

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image
image

Note: there is a `"` and the end of the link

**Review by janahintal — DISMISSED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/cedc30f2-5639-4c63-993f-23a236b47b03

**Comment by tmcconechy** [comment]
@jbrcna note i fixed the extra `"` - good catch

**Comment by jbrcna** [comment]
thanks for fixing it @tmcconechy . 
image

**Pull request merged**
