### PR TITLE
5792 - Fix on searchfield value being cleared when it collapses then expands

### LINKED ISSUE #5792: ToolbarFlex: Search value removed after going into responsive view
**Describe the bug**
ToolbarFlex: Search value removed after going into responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html
2. Add a text in the first search field 
3. Minimize the view port
4. Open the Search field

**Expected behavior**
Text should still remain

**Version**
ids-4.57-dev

**Screenshots**
N/a

**Platform**
Windows 10 Chrome 

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Searchfield value is cleared when it expands. 

Added a fix where the value is saved in settings when the searchfield is not focused, if the searchfield is expanded and a value exists in settings, assign the value to the input.

**Related github/jira issue (required)**:

Closes #5792 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/toolbar-flex/example-index.html
- Add a text in the first searchfield
- Click outside searchfield
- Minimize screen (switch to mobile or minimize it enough that searchfield collapses)
- Click searchfield to expand it

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@yohannahbautista can you move this to 4.58 log?

**Comment by ericangeles** [comment]
@tmcconechy is it still okay to add possible PRs for this week to 4.57?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
The only problem i see is that when you follow the steps the X goes away? (no x when its in expanded mode)

**Comment by yohannahbautista** [comment]
Based on this: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield 
It looks like it doesn't really have an x in expanded mode unless it's collapsible. I'll look into it and try to add it.

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
Yes this looks good now. I think if it was in one size it shouldnt disappear in the other right?
So great fix 👍🏻

**Pull request merged**
