### PR TITLE
8082 - Fix disabled radio button dot.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted styling of checked disabled radio button to center the selected indicator/dot.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/8082

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/radios/example-index
- Open the browser dev tools.
- Locate the "Option four" element in the HTML tree.
- Add `checked="true"` to the input element.
- Selected indicator/dot should be centered within the radio button.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
Nice fix! 🍌

**Review by max-hizon — DISMISSED** [review]
Works on Windows Edge
image

Windows Firefox
image

Windows Chrome
image

**Comment by yohannahbautista** [comment]
Hello, would it be better for future testing to include a radio button that has this scenario? You can put it in a separate group

**Review by janahintal — APPROVED** [review]
Working as expected in https://8082-disabled-radio-dot-enterprise.demo.design.infor.com/components/radios/example-index?theme=classic&mode=light&colors=default

image

**Review by jbrcna — DISMISSED** [review]
nice work!
image

**Review by tmcconechy — DISMISSED** [review]

**Comment by tjamesallen15** [comment]
Can you pull and merge the main branch here to fix the file conflict @RJ-Csc?

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
