### PR TITLE
7406 - Button Adjust personalized colors

### LINKED ISSUE #7406: Button: colors issue
**Describe the bug**
when using dark mode buttons are off in all colors but default
when using light | high contrast buttons are off in all colors but default & alabaster

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. Switch to dark mode
4. Observe button colors 
5. hover over the buttons
6. Notice that buttons are off in all colors but default
7. Switch to Light | High contrast mode
8. Observe button colors 
9. Notice that buttons are off in all colors but default & alabaster

**Expected behavior**

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
image

**Platform**
All
**Additional context**
related to https://github.com/infor-design/enterprise/issues/7215

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adjusts buttons personalized colors after recent change where some of the variables in the colors object were removed, focuses on the dark mode

**Related github/jira issue (required)**:
Closes #7406

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/button/example-index.html
- switch to dark mode and some color
- check buttons bg, text, border, hover colors
- test light/contrast as well

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — DISMISSED** [review]

**Comment by ericangeles** [comment]
@andriivarhanov can we avoid using !important? Let's give CSS specificity a try instead.

**Comment by andriivarhanov** [comment]
- updated disabled buttons color
- removed `!important` where I could

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@CindyMercadoReyes can you help out with QA?

**Review by jbrcna — COMMENTED** [review]
This is still in progress on my end. summary of test findings [wip]
http://localhost:4000/components/button/example-index.html these 2 buttons (primary-action-three, primary-alerttwo) remains grey bg color no matter what color you switch
 


http://localhost:4000/components/button/example-index.html?colors=8D0B0E&theme=classic&mode=light -  in Classic theme (Light | High Contrast) they are always azure
 


http://localhost:4000/components/button/example-index.html?colors=8D0B0E&theme=classic&mode=dark -   in Classic Dark they change colors

 


http://localhost:4000/components/button/example-index.html?colors=ffffff&theme=new&mode=dark – the bg color of these 2 buttons (tertiary-filter-two) were removed.

 


http://localhost:4000/components/button/example-index.html?colors=ffffff&theme=classic&mode=dark – In Classic tertiary-filter-four button also has bg color removed.
 


http://localhost:4000/components/button/example-index.html?theme=classic&mode=contrast&colors=default – with Classic High Contrast, icon looks similar when hovered compare to Light | Dark theme it darkens/sharpens
 


http://localhost:4000/components/button/example-index.html?theme=new&mode=light&colors=ffffff – no hover state with New theme Light mode Alabaster color.

**Comment by jbrcna** [comment]
[http://localhost:4000/components/button/example-index.html](http://localhost:4000/components/button/example-index.html?colors=8D0B0E&theme=classic&mode=light) – Classic theme, tertiary button not readable in all colors but default and alabaster
Light | High Contrast
image


[http://localhost:4000/components/button/example-index.html](http://localhost:4000/components/button/example-index.html?theme=new&mode=light&colors=941e1e) – New theme,  hover the 3 buttons. see error 
Light | High Contrast
image



[http://localhost:4000/components/button/example-index.html](http://localhost:4000/components/button/example-index.html?colors=BB5500&theme=classic&mode=light) – sometimes I get different shades with same color 
image

**Review by tmcconechy — DISMISSED** [review]
Just merged main to check the jobs even tho this is WIP. Just FYI

**Comment by jbrcna** [comment]
> Just merged main to check the jobs even tho this is WIP. Just FYI

thanks for clarifying @tmcconechy . I've been trying to figure out what exactly I did to see that issue. now it was clear to me.

**Comment by jbrcna** [comment]
there's an issue on more actions button with alabaster. but I believe it was fixed on 7390 - 
image

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
