### PR TITLE
Chore: Add listview classes and docs

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Due to some questions, i put togther some docs for the list view classes.

CC @deep7102 for ongoing work on new component

**Related github/jira issue (required)**:
NA

**Steps necessary to review your pull request (required)**:
- review inline
- note that one link wont work until actually deployed

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles is this one you are fixing already https://github.com/infor-design/enterprise/runs/6370718849?check_suite_focus=true#step:11:77 ? Or shall i look at it and update?

**Comment by ericangeles** [comment]
> @ericangeles is this one you are fixing already https://github.com/infor-design/enterprise/runs/6370718849?check_suite_focus=true#step:11:77 ? Or shall i look at it and update?

It's different, @tmcconechy. You can update that one.

**Comment by ericangeles** [comment]
@tmcconechy I also encountered the failing test. I'll fix it on my PR.

**Comment by tmcconechy** [comment]
@ericangeles just pushed it... sorry was waiting for it to run

**Comment by tmcconechy** [comment]
@ericangeles for some reason it didnt work? Can you try?

**Comment by ericangeles** [comment]
@tmcconechy yeah, I kept getting the same error. Trying another way on my PR.

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
