### PR TITLE
3119 - Fix RTL Tooltip/Popover placement

### LINKED ISSUE #3119: RTL: Tooltips and popovers sometimes open far from source
**Describe the bug**
Sometimes tooltips and popovers are shown very far from the source when in RTL. Often this is about tooltips above the source. We have this issue in a couple of placed in Homepages in both tooltips and popovers.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tooltip/example-tooltips-on-elements.html?locale=ar-SA
2. Hover on Email adress field
3. Actual result: Toolip is displayed far from the field

**Expected behavior**
The Tooltip should be shown just above the field (as in LTR)

**Version**

- ids-enterprise: v 4.22.1

**Screenshots**
image

popover in Homepages:
image

other popover in Homepages:
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
It might also be good to know that our popover issues are all in modal/contextual action panels. But We've seen tooltips being misplaced in other places too (but not as far as in these popovers)

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes an issue with positioning of tooltip/popover components when a RTL Locale causes all elements to flip horizontally.  Previously, these components would incorrectly be shrunk horizontally and enlarged vertically due to a text-wrapping issue only present on RTL, which was causing the placement algorithm to incorrectly set the tooltip/popovers higher in their containers. This has been fixed.

Additionally, this PR has a few minor visual improvements surrounding text/button/header spacing on Popovers.

**Related github/jira issue (required)**:
Closes #3119 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, then run the app.
- Open http://localhost:4000/components/tooltip/example-tooltips-on-elements.html?locale=ar-EG
- Hover each of the input fields and ensure the placement of the tooltip is correct.
- Open http://localhost:4000/components/popover/example-alternate-positions.html?locale=ar-EG
- Click each of the buttons and make sure the header text, close icon, "Apply" button, and modal buttons are all properly aligned.
- Open http://localhost:4000/components/datagrid/test-modal-datagrid-single-column
- Click the "Add Context" button.  Ensure the modal buttonset is properly aligned.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Looks good. Just wondering one thing on http://localhost:4000/components/tooltip/example-tooltips-on-elements.html?locale=ar-EG . Should the "states" dropdown have a tooltip?

**Comment by EdwardCoyle** [comment]
I see what @deep7102 mentioned, I'll double check that before we merge this

**Comment by EdwardCoyle** [comment]
@deep7102 @tmcconechy Fixed the problem, take another look!

**Comment by ericangeles** [comment]
Looks great! I just notice a minor issue.

- It shows a horizontal scrollbar in http://localhost:4000/components/tooltip/example-tooltips-on-elements.html?locale=ar-EG. When hovering each input fields, it disappears. And when you hover off, it shows it again.

**Comment by ericangeles** [comment]
I see it on safari, chrome and firefox. See below the browser image, it does have horizontal scrollbar.

chrome
firefox
safari

**Comment by EdwardCoyle** [comment]
@ericangeles working on a fix for that

**Comment by EdwardCoyle** [comment]
@ericangeles take another look and let me know if you're still seeing this

**Comment by ericangeles** [comment]
🍌

**Pull request merged**
