### PR TITLE
5292 - Donut: Update legends to have a setting

### LINKED ISSUE #5292: Charts: Update legends to have a setting
**Is your feature request related to a problem or use case? Please describe.**
Implement a change to the charts so that the design will show a popup for legends when it doesnt fit. See https://jira.infor.com/browse/UXD-2682

**Describe the solution you'd like**
- Implement this design
- Decide if it goes in the old and current code

**Describe alternatives you've considered**
Maybe we do this just in the new charts.

**Additional context**
See design https://jira.infor.com/browse/UXD-2682
Relates closely to https://github.com/infor-design/enterprise/issues/5275

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Included a list menu in legends when an item exceeds the maximum width. Based on the design here: [https://jira.infor.com/browse/UXD-2682](https://jira.infor.com/browse/UXD-2682)
- List of items will be in a one line instead of columns if one item exceeds the chart's maximum width. List button will appear if not all the items can fit and will show the rest of the items in the popup menu

**Related github/jira issue (required)**:

Closes #5292 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/donut/example-legend-bottom-popup.html
- Click on the list button and select an item

**Included in this Pull Request**:
- [ ] A note to the change log.
- [ ] A new sample page in the directory.
- [ ] An e2e test for the feature.

### CODE REVIEW

**Comment by ericangeles** [comment]
Looks great! 🍌 Just move the log to 4.54.0, and suggest adding e2e for visual. Overall, great job!

**Comment by ericangeles** [comment]
I also noticed some minor UI issues once I changed the placement setting to right. 

donut

**Comment by tmcconechy** [comment]
@yohannahbautista if your fixing some minor UI issues then i would check the pie center label is centered..

Screen Shot 2021-07-06 at 9 11 26 AM

Also try selecting the center label text and notice the selection color is not visible (text can be white within the blue)

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — DISMISSED** [review]
Looking good, nice work 👍

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles any further things you want to test or is this good?

**Review by deep7102 — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
All good! Great work, @yohannahbautista! 🍌

**Pull request merged**
