### PR TITLE
5290 - Fix Searchfield Icon is not properly aligned in Firefox

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the searchfield icon that is not properly aligned in firefox view.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5290

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbar-flex/example-searchfield-collapsible.html
- Click on the searchfield button

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — COMMENTED** [review]
Looks good!Just noticed an issue on close button when searching. Might need to fix it as well.

- Go to the sample page and open in Firefox
- Search on toolbar searchfield
- Notice the close icon is not properly align

err

**Comment by tmcconechy** [comment]
Other than  @ericangeles 's comment this looks good to me

**Review by EdwardCoyle — APPROVED** [review]
👍 LGTM

**Review by tmcconechy — APPROVED** [review]
Me too

**Pull request merged**
