### PR TITLE
2552/2811 - Fix footer and tooltip with application menu

### LINKED ISSUE #2552: Application menu: toolbar buttonset in footer area overlaps menu content
**Describe the bug**
IE 11 issue only - When the application menu content height is such that it shows a scrollbar, the application menu toolbar area appears in the middle of the application menu content until users clicks elsewhere.

**To Reproduce**
See screenshot: (a role switcher demo will be added to ep-ng project to duplicate this issue).

**Expected behavior**
Application menu toolbar should not overlaps content area.

**Version**

- ids-enterprise: v4.19.0

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11
 - Browser Version: 11.885.17134.0

### LINKED ISSUE #2811: Application: Menu tooltip shows white text on white background on default theme color.
**Describe the bug**
Application menu tooltip shows white text on white background with on default theme color.

**To Reproduce**
1. Go to http://4210-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html
2. Toggle the role switcher on the right top corner of application menu.
3. Hover over the title with "..." 
4. Also seeing on https://4200-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html that the ... is not there.
4. See tooltip box in white background and white text - unreadable

**Expected behavior**
Tooltip on default color should show a different background color than white so text is readable.

**Version**

- ids-enterprise: v4.19.0-dev.20190424

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Fixed footer toolbar buttons, when the application menu content height is such that it shows a scrollbar. The footer toolbar area was overlapping to menu content until users clicks elsewhere.
- Fixed tooltip was showing white text on white background which makes text to be unreadable

**Related github/jira issue (required)**:
Closes #2552
Closes #2811

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app

Issue #2552
- Use windows10 and ie11
- Navigate to http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html
- Expand all if need `Employee`, `Manager` and `Recruiter` so it shows a scrollbar
- Toggle top button titled `Some extra long title or may be too long`
- After toggle top button
- See the footer toolbar buttons, should be all the way down in menu

Issue #2811
- Use windows10 and Chrome
- Navigate to http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html
- Toggle top button titled `Some extra long title or may be too long`
- Hover over the title with cut of text
- See the tooltip text should be readable (white background and black text)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
I think I prefer the first but it should be consistent throughout so I defer to making it consistent.

**Comment by deep7102** [comment]
To fix for chrome to show the `ellipsis` need to add `width` property which is causing the content text to have till end only, so the tooltip making adjustments for the placement position. In this case is center of the text.
https://github.com/infor-design/enterprise/blob/a3b4caeb25ec6376cb8009c84f4861d8b621cd41/src/components/accordion/_accordion.scss#L530

**Comment by davidcarlsonberg** [comment]
I am unable to see the footer buttons on Win10 IE11.
footer-buttons

**Comment by tmcconechy** [comment]
@davidcarlsonberg I think this is ok, when the overlay is open its the only possible action (its like a popup)
@deep7102 Ok lets go with the position change then

**Pull request merged**
