### PR TITLE
8076 - Searchfield Collapsible

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix animation of collapsible searchfield.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8076

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/header/example-index.html?colors=ffffff
- Open the searchfield component, it should animate from right to left
- Go to http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
- Open the searchfield component, it should animate from right to left

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Animation looks fantastic now. But i see one issue on 

http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html when you expand and collapse the search the grid/page jumps up and down a bit. Can you check that?

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Bug has been fixed. However, the hover state size expands when you type a word in the searchfield.

Steps to reproduce:
1. Hover over then click the searchfield icon
2. Type any word
3. Click on the page
4. Hover over again the searchfield icon

http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html

image

https://github.com/infor-design/enterprise/assets/102151352/7d496deb-a4e2-4d11-a2a9-734f08f49116

Query: There is no color background upon hovering over the searchfield icon. Is this the correct behavior for this example @tmcconechy? Thanks!

http://localhost:4000/components/header/example-index.html


https://github.com/infor-design/enterprise/assets/102151352/e958bbce-a99e-48cc-aa1d-7dbe16e14f5e

**Review by jbrcna — APPROVED** [review]
Large GIF (468x224)
Large GIF (482x224)

**Comment by tmcconechy** [comment]
@glenlieorillo yes for now no background color on search

**Review by glenlieorillo — DISMISSED** [review]
https://github.com/infor-design/enterprise/assets/102151352/8072be45-5715-4a8a-9d25-5cc85b9e430b

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
