### PR TITLE
4347 - Fix export to csv logic for utf16 with datagrid

### LINKED ISSUE #4347: Datagrid: Export to CSV with special characters (é, à, ü, ...)
Export to CSV with special characters (é, à, ü, û, ...) does not generate them correctly.

datagrid

Excel_file

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed the logic for utf-16 encode special characters (é, à, ü, û, ...) export to csv was not generated them correctly with Datagrid.

**Related github/jira issue (required)**:
Closes #4347

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4000/components/datagrid/example-export-from-button.html
- Click on toolbar button `Export To Csv`
- It should download file `muExport.csv`
- Open this download file with `MS Excel`
- See in column `Extra`, all the special characters should be generated correctly
- If you open with any other utf-8 friendly editor like `atom`, `visual studio` or `sublime`
- It should show tab as separate columns

**Additional context**:
Implemented as tab `\t` to separate columns in order to display properly on excel, This can be turn on/off by passing 3rd argument as object with below settings/options.

```
// grid.exportToCsv();
{
  flexChar: boolean (default true), //if false `char` will not be auto change to `\t` tab
  flexUtf8: boolean (default true), //if false `utf-8` will not be auto change to `utf-16le`
  char: string (default ','), //custom separator char
  firstLine: boolean (default true) // if false will not added to first line `sep=<separator.char>`
}
```

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @afarn and @sanx72 if you can test this 👍

**Review by tmcconechy — COMMENTED** [review]
Should we make a not eof this in the change log as now its tab seperated vs comma seperated? Wonder if comma should still be the default?

Why is there spaces in the words in the file? Is this because its UTF 16 ?

**Comment by afarn** [comment]
This issue is now resolved. Thank you.

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
I fixed one image on my PR in the list above - i think it was a chrome 86 thing

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
