### PR TITLE
3963 - Add ability to pass date/time formats with no literals to Mask

### LINKED ISSUE #3963: Date Format with no separator not supported in masking
**Describe the bug**
I want to use format yyyyMMdd in input-masking but I can not write anything in the textbox with this format.

**To Reproduce**
1. Have a textbox
2. Add a mask such as yyyyMMdd
3. Try to write anything in the textbox

**Expected behavior**
The input should follow the mask

**Version**
4.27.4

**Platform**
 - Infor App Builder

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adjusts the detection of date/time format characters in the built-in Date masking function to allow it to process date/time strings that don't contain separators or other special characters.  

**Related github/jira issue (required)**:
Closes #3963

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the demoapp
- Open http://localhost:4000/components/mask/test-dates-no-separators.html
- Fill out the fields according to their placeholders and make sure non-allowed input is thrown out.  All fields are also validated by the Datepicker, so invalid dates should be correctly flagged as an error field.

These three test cases are also covered by new Mask functional tests.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

----
@kels0

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@tmcconechy I definitely see the second problem there, but I didn't see validation failing on the first one.

**Comment by tmcconechy** [comment]
Yeah.. Not seeing it just now but i think it might have been giving an error try this:

- in the third picker -> select a value in the picker
- type a value -> then select a value in the picker 

In both situations:
```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.parseDate (locale.js:1198)
    at DatePicker.setValueFromField (datepicker.js:1591)
    at DatePicker.openCalendar (datepicker.js:616)
```

**Comment by tmcconechy** [comment]
FYI found the regex could use a bit more:  E, z and M should be 1-4 

```
match(/(d{1,2}|M{1,4}|y{1,4}|H{1,2}|h{1,2}|m{1,2}|s{1,2}|a{1}|z{1, 4}|E{1, 4})/g)
```

**Comment by tmcconechy** [comment]
@EdwardCoyle i merged the somewhat related fixes in locale back to master now that you were waiting for

**Comment by EdwardCoyle** [comment]
@tmcconechy I got rid of the date/time cases for now, since the original ask was date only.

**Comment by tmcconechy** [comment]
@EdwardCoyle something fishy maybe with this PR.Has a large number of changes and commits. Some look duplicate (read already merged) but something strange happened on the last push. Maye just a rebase and or sync with master?

But everything else is working ok.

**Comment by EdwardCoyle** [comment]
@tmcconechy I'm closing this one in favor of #4164.  I have no idea what happened and I can't get the history cleaned up here, so I did a clean cut of `master` against that new PR and cherry-picked commits in order.

**Pull request closed without merging**
