### PR TITLE
2212 - Uplift datagrid fixes [v4.19.x]

### LINKED ISSUE #2212: Datagrid: Theme Uplift header alignment issues
**Describe the bug**
There are still many alignment issues involving the datagrid header and its short/med/tall w/ filter row combinations.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html?theme=uplift
2. Click on the `...` menu
3. Change the combinations of row height and toggle filter row

**Expected behavior**
Everything should be aligned.

**Version**
- ids-enterprise: 4.19.0-dev+ (uplift theme)

**Screenshots**
- Too many to list

**Platform**
 - all

**Additional context**
related to #2072 and PR https://github.com/infor-design/enterprise/pull/2202

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Cleans up some styles and adds some fixes so datagrid looks nicer in uplift. Also fixed "heavy" looking text in the headers in Firefox

**Related github/jira issue (required)**:
Fixes #2212 

**Steps necessary to review your pull request (required)**:

Fixed issues on the following pages:
http://localhost:4000/components/datagrid/example-beforeselect-veto.html
http://localhost:4000/components/datagrid/example-beforeselect-veto.html?theme=uplift
http://localhost:4000/components/datagrid/example-filter.html
http://localhost:4000/components/datagrid/example-filter.html?theme=uplift
http://localhost:4000/components/datagrid/test-alerts.html
http://localhost:4000/components/datagrid/test-alerts.html?theme=uplift
http://localhost:4000/components/datagrid/example-tooltips.html
http://localhost:4000/components/datagrid/example-tooltips.html?theme=uplift
http://localhost:4000/components/datagrid/example-drilldown.html
http://localhost:4000/components/datagrid/example-drilldown.html?theme=uplift

Things should look better in terms of:
- icons
- alignment issues in filter
- cell text alignment
- should look ok on all three row sizes

Also fixed
http://localhost:4000/components/datagrid/example-tooltips.html?theme=uplift
http://localhost:4000/components/datagrid/example-tooltips.html
- the text was not the same padding on both top and bottom

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
http://localhost:4000/components/datagrid/example-beforeselect-veto.html
- Ctrl + Click works
http://localhost:4000/components/datagrid/example-beforeselect-veto.html?theme=uplift
- Ctrl + Click only works to deselect, does not work to select

http://localhost:4000/components/datagrid/test-alerts.html?theme=uplift
- Tag cell content seems one pixel lower than Badge cell content
tag-badge

**Comment by tmcconechy** [comment]
@davidcarlsonberg 
1. the way http://localhost:4000/components/datagrid/example-beforeselect-veto.html works you need to hold ctrl (which is command key down on mac) in order to select or deselect. (its a feature to veto beforeselect done for m3 since they do this different there). SO try with command on mac?
2. I'll wait for Eds pr as i have a feeling i willl need to adjust this twice.

**Comment by deep7102** [comment]
Icons not align in column `Status` (Phone view)
http://localhost:4000/components/datagrid/example-filter.html?theme=uplift

Icons not align in column `Alert|Alert w Text|Alert Choose Header` (Phone view)
http://localhost:4000/components/datagrid/test-alerts.html
http://localhost:4000/components/datagrid/test-alerts.html?theme=uplift

Tooltip content looks bit low
http://localhost:4000/components/datagrid/example-tooltips.html?theme=uplift

**Comment by tmcconechy** [comment]
@davidcarlsonberg @deep7102 i think i have fixed your comments now https://github.com/infor-design/enterprise/pull/2275

**Pull request merged**
