### PR TITLE
5459 - Add Info Status to Message Example

### LINKED ISSUE #5459: Message: Add informational status
**Is your feature request related to a problem or use case? Please describe.**
Message component currently has only 3 statuses available: error, alert, success.

**Describe the solution you'd like**
We would like to be able to set an informational status. It would have a blue 'info' icon like on the screenshot.
image

**Describe alternatives you've considered**
Temporary we do not include any status for those messages, but we would like to

**Additional context**
Used in angular app
Infor application: WFM

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Add an alert status to a Message example on example-index.html

**Related github/jira issue (required)**:
Fixes #5459 

**Steps necessary to review your pull request (required)**:
- Pull branch, run app, visit http://localhost:4000/components/message/example-index.html, ensure alert status shows up on "Confirmation Example"

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@davidcarlsonberg this doesnt seem quite right reviewing the issue again https://github.com/infor-design/enterprise/issues/5459 they want the info status icon added (i believe alert was already there so confused about that). But would expect an Informational Example button.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Two small things

1) the icon should be azure adding icon-info should do it

```
<svg class="icon icon-info" focusable="false" aria-hidden="true" role="presentation"><use href="#icon-info"></use></svg>
```

2) does the is-info class do anything really?
3) in the example i would leave the "confirmation example" as it was add add a new button above it call "Info Example".

**Comment by davidcarlsonberg** [comment]
> Two small things
> 
> 1. the icon should be azure adding icon-info should do it
> 
> ```
> <svg class="icon icon-info" focusable="false" aria-hidden="true" role="presentation"><use href="#icon-info"></use></svg>
> ```
> 
> 1. does the is-info class do anything really?
> 2. in the example i would leave the "confirmation example" as it was add add a new button above it call "Info Example".

I wasn't going to add a new button as wouldn't that force up to update the visual regression test?

**Comment by tmcconechy** [comment]
i think in this case it makes sense. As you cant easily find the info icon on the page. You have to guess and try the confirmation one and that one doesnt usually need an icon. So yeah maybe you will have to update the image but i think it makes sense.

**Comment by davidcarlsonberg** [comment]
> i think in this case it makes sense. As you cant easily find the info icon on the page. You have to guess and try the confirmation one and that one doesnt usually need an icon. So yeah maybe you will have to update the image but i think it makes sense.

Cool, sounds good. How do I update a visual regression image? 😄

**Comment by tmcconechy** [comment]
oh sorry i thought you knew about it - the docs are here https://github.com/infor-design/enterprise/blob/main/docs/TESTING.md#working-with-visual-regression-tests we have heard they are pretty good so try and work through that section?

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
