### PR TITLE
4996 - Change font size of heading, subheading, and micro in listview 

### PR DESCRIPTION
**Pull request by iamjamesreyracho**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug on Listview heading, subheading, and micro.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/4996

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go http://localhost:4000/components/listview/example-index.html?theme=new&mode=light&colors=0066D4
- Check the listview: heading, subheading, and micro heading

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
There is a build issue here and I don't know how to fix it.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@iamjamesreyracho @tjamesallen15 - i fixed the build error we were missing a bracket. But requesting changes so i can clarify the design specs for the sizes. I looked on https://jira.infor.com/browse/IDS-100 and they mentioned they were reviewing which i missed.

Meanwhile...
At any rate the sizes dont match the design there exactly. Also did you check if there was an existing rule you could change instead of adding new riules?

So lets see if they come back

**Comment by tjamesallen15** [comment]
> @iamjamesreyracho @tjamesallen15 - i fixed the build error we were missing a bracket. But requesting changes so i can clarify the design specs for the sizes. I looked on https://jira.infor.com/browse/IDS-100 and they mentioned they were reviewing which i missed.
> 
> Meanwhile... At any rate the sizes dont match the design there exactly. Also did you check if there was an existing rule you could change instead of adding new riules?
> 
> So lets see if they come back

Yes. I cross check the .scss files and it uses the classic rules, that's why we added new theme rules in the -new.scss file. Upon checking the Jira Ticket it seems that the design is this?

 suggest:

16px *semibold optional* (Slate 10) - heading 

16px (Slate 10) - subheading 

14px (Slate 7) - subtext

or do we wait for them to finalize the ticket?

**Comment by tmcconechy** [comment]
Yeah lets see what they say otherwise will have to change the font to allow for semi bold. So lets wait for more updates a bit more.. If we dont get any soon can go for it as is for now

**Comment by tmcconechy** [comment]
@iamjamesreyracho OK go with

```
16px *semibold optional* (Slate 10) - heading - font-weight 600
16px (Slate 10) - subheading 
14px (Slate 7) - subtext
```

Thanks!

**Comment by tjamesallen15** [comment]
@iamjamesreyracho i can help you with this one if you need.

**Review by tmcconechy — APPROVED** [review]
Looks good to me 👍🏻

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
