### PR TITLE
1459 - Pager: display a condensed page size selector in List/Detail patterns

### LINKED ISSUE #1459: Pager: Need to have page size chooser available at narrower widths
**Is your feature request related to a problem? Please describe.**
Need to be able to have standalone pager.js display the page size chooser in narrow widths

**Describe the solution you'd like**
Remove 'Records Per Page' test at narrow widths and just display the dropdown. 

**Describe alternatives you've considered**
Some sort of smaller text that is still meaningful.

**Additional context**
50295215-31692000-043d-11e9-8754-e0fd1de2797c

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds a "condensed" view of the Pager component's page size selector button, when using a pager inside of List/Detail patterns.  This allows it to fit correctly alongside of the pager button row in a small space.

screen shot 2019-02-27 at 9 24 37 am
screen shot 2019-02-27 at 9 24 45 am

To facilitate this design, some additional changes to the way settings are passed around between the Listview and the Pager components were made.  There's now a `pagerSettings` object on the Listview settings that will be passed into the Pager during initialization, rather than having specific, cherry-picked settings at the Listview level.

**Related github/jira issue (required)**:
Closes #1459

**Steps necessary to review your pull request (required)**:
Pull this branch and run the demoapp:
- Open http://localhost:4000/patterns/list-detail-paging-pagesize-selector.html and test to ensure the page size selector is working correctly.
- Open http://localhost:4000/patterns/list-detail-paging.html and observe that there should only be two pager buttons in the "list" side, with the "next" button pushed to the right edge, and the "previous" button pushed to the right.
- Open http://localhost:4000/components/pager/example-standalone and double check that it isn't showing the condensed page size selector button
- Open http://localhost:4000/components/listview/example-paging.html (and other standard Listview paging examples) to ensure they have not changed.
- Open http://localhost:4000/components/datagrid/example-paging (and other standard Datagrid paging examples) to ensure they have not changed

### CODE REVIEW

**Comment by pwpatton** [comment]
@EdwardCoyle would this work for stand alone pager as well?

**Comment by kayiuho** [comment]
This is good from the design side.

**Comment by EdwardCoyle** [comment]
@pwpatton the way it's currently setup, the sizing change happens automatically when contained by a List/Detail pattern.  No, it's not necessarily configurable to turn on in any scenario.

**Comment by EdwardCoyle** [comment]
Noting that per a conversation with @pwpatton, we decided to add a setting that can turn on the small page size selector.  I added it to the Standalone Pager example, along with a functional test for the setting.

**Comment by janahintal** [comment]
Pager Doesn't show in iOS Devices. Will move this ticket to Failed for now. Thank you. 

Steps to Replicate:
1. Using iOS Device, Open 'https://4170-beta0-enterprise.demo.design.infor.com/patterns/list-detail-paging-pagesize-selector.html'
2. Notice that the Page doesn't show the Pager at the bottom. 

Tested using: Iphone XS - Safari


Screen Shot 2019-03-21 at 4 02 49 PM

**Pull request merged**
