### PR TITLE
7506 - stats component

### LINKED ISSUE #7596: Widget: Actions button not shown when hovering widget
**Describe the bug**
Regression between 4.83.0 and 4.84.0. The widget actions button should be shown when hovering the widget, it's not on 4.84.0

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.84.0/demo/components/cards/example-workspace-widgets?theme=uplift&variant=light
2. Hover anywhere on "Bordered" widget

**Expected behavior**
The widget actions button (top right) should show up, but it's not. If hovering where the button is, it will show up after a slight delay.

See below for working
https://design.infor.com/code/ids-enterprise/4.83.0/demo/components/cards/example-workspace-widgets?theme=uplift&variant=light

**Version**
- ids-enterprise: v4.84.0

hover

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add a new component called stats.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7506
Closes #7596 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/stats/example-index.html

Figma Reference: https://www.figma.com/file/vFSHOqtgm9ypxOtOTHoBjF/List-View-Cards?type=design&node-id=0-1&t=Op6UQdJJNZyGldN1-0

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — DISMISSED** [review]
QA Approved.


https://github.com/infor-design/enterprise/assets/102151352/b75ad6bd-9b23-4d0c-aafe-d48438ce0916

**Review by jbrcna — DISMISSED** [review]

**Review by janahintal — DISMISSED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 i worked with @talkaboutdesign to clarify some things and made some fixes.. Hope you don't mind it seemed easier.

- we only need the borderless card with them on
- need it to work like borderless card
- needed an actionable click state
- i added some variables and dark mode and made contrast look decent
- fixed RTL

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 there are two comments i didn't get to you could maybe look at.

1. In the actionable examples only one should be selected at a time. you can update the logic in the example page script. I think ultimately that should be a jquery Util tho. i don't think this needs to be a full component but we might have to move this logic someplace.
2. Can you try to see if you can make the hover state and selection state animated a bit so its smoother? I tried and it looked weird
3. We might need to figure out the subtitle card size (nothing to do I will figure out if its correct via teams comment)

**Comment by tjamesallen15** [comment]
> @tjamesallen15 i worked with @talkaboutdesign to clarify some things and made some fixes.. Hope you don't mind it seemed easier.
> 
> * we only need the borderless card with them on
> * need it to work like borderless card
> * needed an actionable click state
> * i added some variables and dark mode and made contrast look decent
> * fixed RTL

I was about to do this comment and notice that some of it was changed already. Thanks @tmcconechy. I was just following the figma. No worries.

**Comment by tjamesallen15** [comment]
> @tjamesallen15 there are two comments i didn't get to you could maybe look at.
> 
> 1. In the actionable examples only one should be selected at a time. you can update the logic in the example page script.
> 2. Can you try to see if you can make the hover state and selection state animated a bit so its smoother? I tried and it looked weird
> 3. We might need to figure out the subtitle card size (nothing to do I will figure out if its correct via teams comment)

- Done on #1
- On #2 I tried my best on making the transition moother, can you check? it seems smooth to me now.
- While waiting for the design review, i made the subtitle 10px to make it seem more like a subtitle. otherwise i can change it if we want it.

**Review by tmcconechy — APPROVED** [review]
Made some fixes from design review that were tough to explain. Looks good now. ready for QA

**Review by ericangeles — DISMISSED** [review]

**Review by glenlieorillo — DISMISSED** [review]
QA Approved.

image

**Review by jbrcna — COMMENTED** [review]
https://7506-stats-component-enterprise.demo.design.infor.com/components/stats/example-index.html?theme=classic&mode=contrast&colors=default
in classic mode cards are not aligned.

image

**Comment by EdwardCoyle** [comment]
Per addressing @jbrcna's comment, I tested this and everything else looks good now

**Comment by tmcconechy** [comment]
thanks. i fixed the classic issue @jbrcna @EdwardCoyle

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Comment by talkaboutdesign** [comment]
I know that based on how IDS is setup classic mode is there by default. But just so you are aware. Design team does not consider classic as something we support anymore. Our POV is classic mode is deprecated, bug fixes only, anything new we create is just for the "New" version as we call it. This means we will not be spending any of our time on QA or making design adjustments for classic. Especially for new components. 

CleanShot 2023-06-14 at 07 15 19@2x

**Comment by tmcconechy** [comment]
I understand @talkaboutdesign ~ we unfortunately still have to keep it for now. So we just make it "passable" but doesnt really require feedback. But the new enterprise web components version no longer includes it. Thats where we cut it off and out.

**Pull request merged**
