### PR TITLE
8020 - Datagrid Dirty Tracker

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix an issue where dirty tracker will appear even no change was made from the cell.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8020

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Click on cell with data under Order Date column
- Click on page

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Bug still exists on the first column (blank cell). Dirty tracker appears even there is no changes have been made.


https://github.com/infor-design/enterprise/assets/102151352/3555bcdd-d3f4-481c-b4cc-0c41aeddbd15

image

image

**Review by jbrcna — COMMENTED** [review]
dirty tracker appears when validation is triggered. only the first row/cell is affected.
image

**Review by glenlieorillo — COMMENTED** [review]
Issue has been fixed. I just noticed that when I change the value of the other column cell, the dirty tracker will appear and when reverted to its original value, the dirty tracker will be removed. But when I enter/change the date in the `Order Date` column and delete/revert the value, the dirty tracker stays in the cell. Kindly confirm @tmcconechy if this is the expected behavior. Thank you!


https://github.com/infor-design/enterprise/assets/102151352/28287b04-ce39-482a-8fdf-1695c7d652b4

**Review by jbrcna — CHANGES_REQUESTED** [review]
dirty tracker is still displayed even after reverting to its original value
image

**Pull request merged**
