### PR TITLE
8618 - Autocomplete Keydown

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix autocomplete losing focus on keydown.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8618

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/autocomplete/example-index.html
- In the input field, type "ne" and wait for the results to appear.
- Hit the down arrow to nav down the list
- The focus should still be on the input box

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Losing focus on keydown still occurs.

**Steps to reproduce**
1. Type `ne`
2. Select the first result via `arrow down`
3. The selected result is highlighted and the cursor still exists
4. Add `w`, should now be `new`
5. Press `arrow down`
6. Input loses focus

https://github.com/infor-design/enterprise/assets/156752175/3545f31c-68cc-4b6b-9fd4-35e002bf8061

**Review by jbrcna — APPROVED** [review]
image

**Comment by jbrcna** [comment]
However, when you repeat the steps again ( steps 3 to 5 ) the input field loses focus
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Same observation on my end.

https://github.com/infor-design/enterprise/assets/102151352/fba4735c-745b-4d40-b093-8b1abe6d7f52

**Review by n-ace-ancog — DISMISSED** [review]
Very nice!

https://github.com/infor-design/enterprise/assets/156752175/ba9ea6c2-8a0c-4166-9db7-9c06d5a6f720

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/478a0810-5041-4a69-b0cb-58b206468dea

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
