### PR TITLE
1620 - Fix popup selection bug 

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes a regression in popupmenu where some items that should be checked are not checked.
This was caused be https://github.com/infor-design/enterprise/pull/8124
@tjamesallen15 can you test this PR since i see you added those lines?

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-ng/issues/1620

**Steps necessary to review your pull request (required)**:
- get the latest  https://github.com/infor-design/enterprise-ng as an example was added
- `npm run build` then copy to  https://github.com/infor-design/enterprise-ng and run 
- run http://localhost:4200/ids-enterprise-ng-demo/popupmenu
- open the "Menu For Loop" example and try and toggle between the selected items
- reopen and it should show the right one as selected
- on this repo run this branch
- test http://localhost:4000/components/donut/example-legend-bottom-popup.html -> when you select the menu items it should toggle the selected item in the chart
- check the "selection/selected" examples on http://localhost:4000/components/popupmenu

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — APPROVED** [review]
image

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
unable to unselect items in https://1620-popup-bug-enterprise.demo.design.infor.com/components/popupmenu/example-selectable-multiple.html
&
https://1620-popup-bug-enterprise.demo.design.infor.com/components/popupmenu/example-selectable-multiple-with-headers.html
Large GIF (866x556)

**Comment by tjamesallen15** [comment]
@tmcconechy  aside from what @jbrcna found, its good to me.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Focus state looks off
- Upon clicking the selected item, it goes back to the default item `Response Late (62%)`

**Steps to reproduce:**
1. Click the bullet steps icon
2. Select an item `Past Expiry (8%)`
3. Click the displayed selected item `Past Expiry (8%)`
4. Notice the behavior

https://1620-popup-bug-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html


image

https://github.com/infor-design/enterprise/assets/102151352/273e7048-e57a-46d1-aa81-a58a467b1a3b

**Review by janahintal — CHANGES_REQUESTED** [review]
Also failing on my end on both Classic and New version https://1620-popup-bug-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html?theme=classic&mode=light&colors=default 
image

After selecting on the legend list and selecting on the pie chart, the legend didn't changed.

**Comment by tmcconechy** [comment]
@janahintal @jbrcna @glenlieorillo 
I fixed what i could. But for the one issue it was too complicated so i made a new issue for later https://github.com/infor-design/enterprise/issues/8443 as that issue already existed.

Will have to merge this to get the critical part, so any other minor issues just make a new issue, please

**Comment by jbrcna** [comment]
> @janahintal @jbrcna @glenlieorillo I fixed what i could. But for the one issue it was too complicated so i made a new issue for later #8443 as that issue already existed.
> 
> Will have to merge this to get the critical part, so any other minor issues just make a new issue, please

alright @tmcconechy . thanks!

**Pull request merged**
