### PR TITLE
7546 - Fix UI of listview with filters

### LINKED ISSUE #7546: Listview: filters misaligned
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html
2. See error

**Expected behavior**
the filters should be properly aligned

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
image

**Platform**
All

**Additional context**

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the UI of listview with filters.

**Related github/jira issue (required)**:

Closes #7546 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/example-filters.html
- Filter buttons should be inline with the search field
- Buttons shouldn't have background colors and borders
- Listview should have border radius bottom of 8px (left and right)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
The only question that comes to mind is the hover state on the X.

Screenshot 2023-06-20 at 1 39 52 PM

I think it should look like https://main.wc.design.infor.com/ids-search-field/example.html

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Border looks off in Classic Version.
image

Kebab Menu is invisible in Classic Version.
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
Classic theme
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Also failing on classic mode on my end. 
image

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — DISMISSED** [review]

**Review by yohannahbautista — DISMISSED** [review]

**Pull request merged**
