### PR TITLE
5021/5056 - Fix multiselect dropdown list position on mobile

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the position of dropdown list (multiselect) on mobile. I also added some minor adjustment on dismissible icon that I noticed.

Added to this PR to fix the dropdown list flows up or detached to the input field if the browser is smaller.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5021
Closes https://github.com/infor-design/enterprise/issues/5056

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

Test #1 
- Go to http://localhost:4000/components/multiselect/example-compact.html
- Open it via browserstack on mobile or the built-in device in chrome toolbar
- Click to open `Mutliselect (with tags)`
- Select multiple items
- The position of dropdown list should be stay in its place and able to select multiple items
- Check the position of the close icon
- Should be align to the text
- Test this also in classic

Test #2 
- Go to http://localhost:4000/components/dropdown/test-sizes.html
- Make the browser smaller, make the height `700px` to have scrollbar
- Open the last dropdown below
- Make a search, type `45`
- The list should not be detached or flow up

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Please disregard some commits in the logs, kinda messed up. :) I was on this branch when fixing the toast https://github.com/infor-design/enterprise/issues/5015 issue, which I have PRed already (https://github.com/infor-design/enterprise/pull/5081).

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks good for the fix but i'm seeing two things. But i can't tell if they regressed. 

Both issues seen on http://localhost:4000/components/multiselect/example-compact.html in desktop or mobile mode

1.The multiselect with tags has an un-needed scrolllbar
Screen Shot 2021-04-14 at 10 01 14 AM

2. Also when you clear the items out the icon looks far away from the left (not sure if this is fixable easily if not can defer).

Screen Shot 2021-04-14 at 10 01 53 AM


Asking @EdwardCoyle if we remembers this being this way or not?

**Comment by EdwardCoyle** [comment]
Probably should test against #5056

**Comment by tmcconechy** [comment]
We should see if this resolves https://github.com/infor-design/enterprise/issues/5056 as well.

**Comment by EdwardCoyle** [comment]
@tmcconechy Seems like the scrollbar issue was present from before: https://master-enterprise.demo.design.infor.com/components/multiselect/example-compact.html

However, this was all working as of 4.37.0: https://4370-enterprise.demo.design.infor.com/components/multiselect/example-compact.html?theme=uplift&variant=light&colors=0066D4

**Comment by tmcconechy** [comment]
ok do you want to fix these here @ericangeles or a new issue?

**Comment by ericangeles** [comment]
> ok do you want to fix these here @ericangeles or a new issue?

Yep, will do the fix here.

**Comment by ericangeles** [comment]
@tmcconechy @EdwardCoyle adding #5056 fix to this PR.

**Review by tmcconechy — COMMENTED** [review]
Looks really good but just one thing related i see. 

http://localhost:4000/components/multiselect/example-compact.html
- open the first tag example and select 5 or more items
- re-open and the list is a bit off

Screen Shot 2021-04-16 at 8 56 35 AM

**Comment by ericangeles** [comment]
I couldn't replicate that one @tmcconechy. Am getting this,

ss

**Comment by tmcconechy** [comment]
Im seeing it on Chrome/Mac - Desktop at around this size browser:

Screen Shot 2021-04-16 at 9 33 27 AM

Does that help?

**Comment by ericangeles** [comment]
Yeah, I am seeing it now but when the compact mode is not activated. Let me check it.

**Comment by tmcconechy** [comment]
Hmm im still seeing it?
Screen Shot 2021-04-16 at 11 16 54 AM

**Review by tmcconechy — APPROVED** [review]
Looks good now 👍🏻  Thanks!

**Review by EdwardCoyle — APPROVED** [review]
👍  LGTM

**Pull request merged**
