### PR TITLE
1906 - Add a fixes so that beforeSelect can be vetoed

### LINKED ISSUE #1906: Datagrid: Add events to allow multiselect only when modifier key is pressed
**Is your feature request related to a problem? Please describe.**
In M3, we need to be able to do a multiple select, but only when the user is pressing the Ctrl/Command (mac) key at the same time. This is a behavior that thousands of M3 users are accustomed to. The M3 H5 client is currently being rewritten using ids-enterprise-ng components and this feature enhancement for the datagrid is very much needed. 

**Describe the solution you'd like**
Option 1:
The optimal solution would be to have a property e.g. modifierKey (available for `multiple` selection datagrids) which would take a supported (by you guys) value e.g. ctrl or alt. Lets say the value ctrl is given, the datagrid control would check If ctrlKey or metaKey (mac) is available on the triggered event and its current value. If the value of the mappings for the modifyer key is true, then go ahead and add the row to the list of selected rows, otherwise unselect all rows and add only the current row to the list of selected rows. If this modifyerKey property is not present on the datagrid options object, continue with default behavior (as today). 

Option 2:
A different solution could perhaps be to add `beforeRowActivated` (or similar event before a row is actually activated or selected) for `multiple` selection datagrids too (currently only available for mixed selection datagrids?). You would have to pass the original event (not only the `row` and `item` which is the case for the `mixed` selection datagrids today), so that the developers can check if `event.ctrlKey` or `event.metaKey` exists and if anyone is true. 

**Describe alternatives you've considered**
An alternative solution I've tried is to create an angular directive to be added to the same div as the `soho-datagrid` one which has a HostListener for click event. I can then inject the datagrid in the directive and unselect all rows if the modifyer key of my choice is not true. This works to some extent, but not when the rows are selected using keys (tabbing and selecting with enter for example). Also some events are not triggerd by users, so it is not a good solution for that reason too.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a beforeSelect callback to datagrid so that you can veto row selection. The requirements listed needed to also know if CTRL or shift is pressed, so re-added the keyboard module to start up #643 , this had the functionality needed to see the pressed keys anytime. To let the events run through had to fix up the contextmenu function. Bonus: can now right click datagrid as long as no context menu functionality is attached for inspection.

**Related github/jira issue (required)**:
Fixes #1906 

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/datagrid/example-beforeselect-veto.html
- Selecting rows is not possible.
- But if you hold down CTRL key or Command (on Mac) and click a row it will select.
- This mimics M3 functionality in a non invasive way

http://localhost:4000/utils/example-keyboard.html
- hold a key of any kind and it will show

- Everything is nicely covered by the new tests
- Retest Datagrid Context Menu
http://localhost:4000/components/datagrid/test-tree-contextmenu.html
http://localhost:4000/components/datagrid/test-contextmenu.html
http://localhost:4000/components/datagrid/test-contextmenu-dynamic.html
http://localhost:4000/components/datagrid/test-contextmenu-in-events.html (new test)

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Also noting that this PR probably also covers most -- if not all of -- #643

**Comment by tmcconechy** [comment]
Right except for the breaking consistency changes.

**Comment by tmcconechy** [comment]
Good can make banana bread 😛

**Comment by hernebrink** [comment]
@tmcconechy Do i need to create a ticket for enterprise-ng project in order to get this available for the angular component?

**Comment by tmcconechy** [comment]
I usually track that on tickets like this https://github.com/infor-design/enterprise-ng/issues/472
I went ahead and added this so it was for sure in https://github.com/infor-design/enterprise-ng/pull/491

**Pull request merged**
