### PR TITLE
6721 - icons puppeteer new icons test

### PR DESCRIPTION
**Pull request by glenlieorillo**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds puppeteer snapshots for icons component.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6721

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Run in terminal `npm run e2e:puppeteer`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@glenlieorillo were you able to generate the image snapshots in the ubuntu environment?

**Comment by tjamesallen15** [comment]
I can help you setup docker environment on monday @glenlieorillo

**Comment by glenlieorillo** [comment]
> @glenlieorillo were you able to generate the image snapshots in the ubuntu environment?

Not yet, @ericangeles. Will do it on Monday with @tjamesallen15. 😊

**Comment by ericangeles** [comment]
Looks good now!

**Comment by ericangeles** [comment]
Looks good now!

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
