### PR TITLE
7677 - Fixes on issues in popover when opening and closing

### LINKED ISSUE #7677: Popover: Event handlers of other components are removed when reopening the popover
**Describe the bug**
When using different IDS components inside popover contents, they are working fine the first time, but after closing and reopening the popover they are not working properly.
The issue is with probably with seting content using innerHtml which is known for removing event handlers.

**To Reproduce**

Textarea;
1. Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Click on 'Popover 1'
3. Write something in text area and see that counter is working fine.
4. Close and reopen 'Popover 1'
5. There are now two counters, one working fine and another frozen.

Expandable data grid:
1. Click on 'Popover 2'
2. Expand datagrid row - should work fine
3. Close and reopen 'Popover 2'
4. Try to expand datagrid row - it will not work anymore

**Expected behavior**
Other components should work just fine when used inside popover.

**Version**

- ids-enterprise: 4.84

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Infor WFM

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fix on textarea creating a duplicate counter when reopening popover.

Fix in datagrid is more of another implementation on a datagrid in popover:
Based on how textarea behaved when popover opens and closes, it reinitializes again. With datagrid it doesn't seem to reinitialize at all (and so doesn't have any events attached). Used popover events for hidden and before show to have datagrid be reinitialized.

**Related github/jira issue (required)**:

Closes #7677 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/popover/test-nested
- Click buttons to check popover
- Close and open again

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still failing on my end.

Issue on 'Characters left' counter:

1. Click 'Popover (Text Area)' button
2. Key in any text on the text area
3. Notice the 'Characters left' counter
4. Click close button
5. Click 'Popover (Text Area)' button
6. Key in again any text
7. See error


https://github.com/infor-design/enterprise/assets/102151352/61f61c4f-3a7e-4117-b3a1-d41cf4d14086

**Observation:**
I noticed that there was an asterisk '*' (required field indicator) after 'Page Title', I believe there should be validation error notification. Kindly correct me if I am mistaken @tmcconechy Thanks!

image


-----

Issue 2 Popover (Datagrid): Approved


https://github.com/infor-design/enterprise/assets/102151352/b013c843-cd96-4bae-9057-0b9b57802108

**Comment by ericangeles** [comment]
I also noticed what @glenlieorillo pointed out. Another issue, although unrelated to the main problem, can be fixed immediately: the tooltip-title section with the close button is not aligned.

**Comment by tmcconechy** [comment]
@yohannahbautista you can probably remove the required `*` if the validation isnt hooked up its just something for QA to flag. Since its not part of the issue lets just remove from the example

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/4c42eb36-386f-4c1c-ab56-c7adc9d0f5a1

**Comment by glenlieorillo** [comment]
> @glenlieorillo look ok now?

Yes, @tmcconechy. Thanks, @yohannahbautista

**Comment by tmcconechy** [comment]
@yohannahbautista does this fix https://github.com/infor-design/enterprise/issues/7679 ?

**Pull request merged**
