### PR TITLE
7915 - card is selected trigger tabs

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix issues when using both card and tabs component.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7915

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/cards/test-tabs-card.html
- Click the `Attachments`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
This is now working as expected. However, I noticed that the border below tabs is missing in Dark-Classic.

image

image


https://github.com/infor-design/enterprise/assets/102151352/2cdecfc7-cf57-4989-9dc2-6a12df1dcf55

**Comment by tmcconechy** [comment]
@glenlieorillo can you make a new issue for that? i will check for a fix but is out of scope for this fix to me.

**Comment by tmcconechy** [comment]
@tjamesallen15 @glenlieorillo i fixed the color issue here https://github.com/infor-design/enterprise/pull/7994

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/6fa2adec-1ffd-4e22-8a2a-3e9cbe0d73c7

**Review by jbrcna — COMMENTED** [review]
Approved.
Large GIF (1178x504)

**Pull request merged**
