### PR TITLE
6929 - datagrid undefined headicon

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix header icon tooltip showing when undefined.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6929

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-empty-header-icon.html
- Header Icon tooltip should not be shown

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by s-werking** [comment]
Hi @tjamesallen15, I was hoping that we could have a header icon shown without setting a headerIconTooltip option, but the header icon is not shown in the sample. Could this be possible?

**Comment by s-werking** [comment]
> @tjamesallen15 i think reading the issue its a bit confusing but you want to only show the icon in the header and no tooltip? Is that right @s-werking ?

Correct

**Review by tmcconechy — CHANGES_REQUESTED** [review]
See inline comment and suggestion. Think the example needs a tweak

**Comment by EdwardCoyle** [comment]
@tjamesallen15 I think there may be something else triggering a tooltip somewhere:
- Goto http://localhost:4000/components/datagrid/example-header-icon-with-tooltip.html
- Hover just the empty space inside the "Product Name" cell.  See screenshot 1
- Then hover the icon inside that same cell.  See screenshot 2

| Screen Shot 2023-03-23 at 11 28 32 AM | Screen Shot 2023-03-23 at 11 28 22 AM |

This is maybe related to Tim's comment about the settings, maybe a conflict?

**Comment by tmcconechy** [comment]
yeah thats right @EdwardCoyle i think the `headerTooltip` in the example can go. For purposes of fully testing the use case.

**Comment by tjamesallen15** [comment]
Thanks for both of you guys @tmcconechy  @EdwardCoyle

**Review by tmcconechy — APPROVED** [review]
Added a new example with no tooltip as requested. So we have two examples. Looks good now! Thanks!

**Pull request merged**
