### PR TITLE
4989 - Header: larger search x alignment issue

### LINKED ISSUE #4989: Header: larger search x icon alignment issue
**Describe the bug**
The x icon of Searchfield was misaligned 

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html
2. Enter text in searchfield
3. See error
4. X icon is not properly aligned

**Expected behavior**
should be properly aligned

**Version**

- ids-enterprise: v4.39.0-dev

**Screenshots**
image

**Platform**
All

**Additional context**

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Should solve most (if not all) of the styling issues with the search fields and toolbar search fields that contain clear buttons.

**Related github/jira issue (required)**:
Closes #4989 

**Steps necessary to review your pull request (required)**:
- Build the demo application and look over components in the places listed below. 
- Type in some content and see an "X" to clear content. 

Previously the "X" would be down into the search field on certain scenarios; this should no longer happen. 

As mentioned in the issue, the components in these sections should be checked locally.
[http://localhost:4000/components/searchfield](http://localhost:4000/components/searchfield)
[http://localhost:4000/components/toolbarsearchfield](http://localhost:4000/components/toolbarsearchfield)
[http://localhost:4000/components/header](http://localhost:4000/components/header)
[http://localhost:4000/components/tabs-module](http://localhost:4000/components/tabs-module)

For reference/sanity check if the PR is merged:
[https://master-enterprise.demo.design.infor.com/components/searchfield](https://master-enterprise.demo.design.infor.com/components/searchfield)
[https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield](https://master-enterprise.demo.design.infor.com/toolbarsearchfield)
[https://master-enterprise.demo.design.infor.com/components/header](https://master-enterprise.demo.design.infor.com/components/header)
[https://master-enterprise.demo.design.infor.com/components/tabs-module](https://master-enterprise.demo.design.infor.com/components/tabs-module)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@rob2d did not verify this for a fact but this test is failing https://github.com/infor-design/enterprise/pull/4991/checks?check_run_id=2194012748#step:10:3243

This may mean either:
- http://localhost:4000/components/applicationmenu/example-filterable.html broke (the filter box has an x as well)
- or this needs updating git

Steps are here https://github.com/infor-design/enterprise/blob/master/docs/TESTING.md#working-with-visual-regression-tests its probably easier to do that part when you have the mac setup though. So maybe i can update it quick for you?

**Comment by rob2d** [comment]
@tmcconechy thanks for the references. There were actually a few things I hadn't caught with that test case initially since I wasn't aware the menu was functional in this demo which Ed pointed out -- so re-visited that and noticed I wasn't respecting a rule which cleared display. I think the only thing left is the button being slightly off centered.

For the test configs, I can also look into that if there's nothing else. It would definitely probably help to just run locally. But also have a main PC with WSL2 config'd already (particularly good for Docker + Windows), as well as the Macbook, so it may be a little redundant to do this 3x but I don't mind if nothing else.

**Comment by tmcconechy** [comment]
OK i'll just update that quick for you and you can get into the visual regression tested after you get the mac operational

**Comment by tmcconechy** [comment]
FYI i tried the test on the VM - so its its probably it will pass now as i didnt see it fail there. So lets see

**Comment by rob2d** [comment]
(🤞🤞)

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I did the PR review however and found an issue...

1. go to http://localhost:4000/components/header/example-buttons-larger-search.html
1. type something
1. hit the x with the mouse -> it is now not closing (but it did before despite the alignment issue https://master-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html)
1. also type something
1. hit tab -> similar to an issue @danielortiz1982 fixed elsewhere the x is not visible within in the focus state and the focus state as appearing "oval" here.. compare with tabbing on http://localhost:4000/components/searchfield/example-index.html

Otherwise looks like a good fix

**Comment by rob2d** [comment]
@tmcconechy thanks for looking over that again -- looking into it, was held up on the other branches a bit.

**Comment by rob2d** [comment]
should have gotten it now
4989_example-buttons-larger-search

**Review by EdwardCoyle — COMMENTED** [review]
This looks pretty good to me.  The only thing I wasn't sure about:  do we want to address the focus state on this PR @tmcconechy?  It's working well on the in-page searchfields, but I saw the oval-shaped focus state is still present on App Menu searchfields:  http://localhost:4000/components/applicationmenu/example-filterable.html

Screen Shot 2021-03-26 at 9 51 08 AM

**Comment by tmcconechy** [comment]
I think we should if we can - i didnt verify if it was caused by the fix?

**Comment by EdwardCoyle** [comment]
I didn't see it on master: https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html

**Comment by tmcconechy** [comment]
OK then should fix it ... its also pretty noticeable and the tabbing to the X is a new feature

**Comment by rob2d** [comment]
Will try to check into this one today

**Comment by rob2d** [comment]
@EdwardCoyle thanks for pointing this out -- ran this locally but could not reproduce -- double checked that I was on the right branch. Would you mind letting me know your browser/OS?

What I see is below:
image

**Comment by rob2d** [comment]
had to reflow and attempted to add fixes. Failed on CI but hadn't gotten this locally. Hopefully this was just a fluke.

image

**Comment by tmcconechy** [comment]
I've seen that datagrid test fail on occasion couldnt figure out whats wrong with it, if it keeps failing maybe we'll just drop it as i think it has other tests. For now restarted the tests

**Review by tmcconechy — APPROVED** [review]
LGTM now

**Comment by tmcconechy** [comment]
OK go for it - all for making changes to make the tests stable. However, i would cap the time we spend on this so we can move to more important things. Main goal would be fixing the one flaky test not changing many others. 

Also we had typically just put the selectors as strings in the test. But i can see the point of extracting that...

**Comment by rob2d** [comment]
Cool thanks @tmcconechy ! 

Just a note on this branch I added the `TESTING.md` changes we mentioned in the chat yesterday. Added a TOC just because I found myself sort of going back and forth and seems just with the visual regression baseline stuff an area people may want to quickly skim around vs read from start => end. But we can take those out if consistency or maintainability is an issue as well.

Was having some small issues, but will time-box trying to get the data grid row tests updated early this afternoon since they still intermittently fail. If not fruitful immediately, can stash and at least it would be useful to pick up how some things work for being able to maintain this repo going forward.

**Comment by rob2d** [comment]
also updated `browserslist`: we were still supporting IE11 which did not allow `Promise.all` -- this is useful in cutting test time down but also for some nuanced issues with async/tests occasionally not working.

**Comment by rob2d** [comment]
After updating row delete test code, those are running through fine. 

PR now stumbling on other tests at the moment. These seem a bit vague/unrelated but may also involve the same async sort of logic so can update that if re-run doesn't complete. Hoping to move to other issues for the afternoon and may revisit though.

```
  Datagrid Tree
    ✖ Should be able to track dirty cells with treeGrid
      Chrome Headless 89.0.4389.90 (Linux x86_64)
    Uncaught TypeError: col.editor is not a constructor thrown

    ✖ Should be able to track dirty cells with treeGrid 
      Chrome Headless 89.0.4389.90 (Linux x86_64)
    Uncaught TypeError: col.editor is not a constructor thrown

    ✖ Should be able to track dirty cells with sort column and treeGrid
      Chrome Headless 89.0.4389.90 (Linux x86_64)
    Uncaught TypeError: col.editor is not a constructor thrown

    ✖ Should be able to track dirty cells with sort column and treeGrid 
      Chrome Headless 89.0.4389.90 (Linux x86_64)
    Uncaught TypeError: col.editor is not a constructor thrown
```

**Comment by rob2d** [comment]
refactored the new failing tests above into more sequential async and increased timeouts from 1ms to 400ms (not a holistic fix), just to see if this was the issue. Seems may be logical? But very interesting as there aren't logical changes there at all.

**Comment by rob2d** [comment]
So the issue with the datagrid regression was because the browserslist changes were revealing some issues in the rollup compatibility with that, and since that may be a complex build issue reverted those. But for the current failing test:

Yesterday evening I narrowed the colorpicker-in-editfield test issue down to `updateColorMenu.js` -- where it is deleting the color picker. Fixed by checking for the color picker and re-using that instance vs deleting it. 

But also scanned through all the CSS changes (they seem only related to toolbar-wrapper/appmenu or search bar and very specific to the icon.close instances) and there was nothing in the rules that should have affected either the colorpicker button  

Found there were more e2e tests failing after this but there's something in how the components work that I am not understanding or able to see that doesn't seem obvious; e.g. how a seemingly unrelated CSS change specifically on the close button positions would break other things that aren't in the same element hierarchy functionally. The colorpicker, for example, is sitting on a popover wrapper away from everything else, and nothing in the toolbar the button is in isn't affected by the changes.

(@tmcconechy)

**Comment by tmcconechy** [comment]
Yeah this got out of hand. But i fixed the colorpicker issue i mentioned. Its unrelated to anything you did and this issue.

**Comment by rob2d** [comment]
@tmcconechy Thanks Tim and sorry about the run around on this PR. I am going to try to gradually cherry pick and test locally on another branch now that I know how to do that from start this time.

**Pull request closed without merging**
