### PR TITLE
5400 - Lookup, timepicker and datepicker trigger buttons not tabbable if element is not tabbable

### LINKED ISSUE #5400: Modal: No focused element in modal if first field is disabled and has a trigger button
**Describe the bug**
There is no focused element in the modal if first field is disabled and has a button like lookup, timepicker and datepicker.
I think we also need to set the tabindex of trigger button to -1, current value is 0 even if the input is disabled.

    var focusableElemSelector = ['button:not([disabled]):not([tabindex="-1"])', ...

**To Reproduce**
https://stackblitz.com/edit/ids-enterprise-pbmw8c?file=index.html

Pre-req: First field in the modal should be disabled and has a button like lookup, timepicker and datepicker
1. Open up the modal

**Expected behavior**
First editable field (name) should be focused.

**Actual Behavior**
First editable field  (name)  is not focused.

**Version**
- ids-enterprise: v4.52.1

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 91.0.4472.124

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fix there is no focused element in the modal if first field is disabled lookup, timepicker or datepicker
by making trigger button not tabbable 

**Related github/jira issue (required)**:
Closes #5400

**Steps necessary to review your pull request (required)**:
- pull the branch & build
- http://localhost:4000/components/modal/test-focusable-elements.html
- open up the modal
- see first editable field is focused

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
This is very minor but some of the labels dont look disabled. (Compare the disabled Datepicker to Timepicker). If you just add `field is-disabled` i think that will do it.

Just noticed because they dont look "as" disabled without it.

**Comment by andriivarhanov** [comment]
> This is very minor but some of the labels dont look disabled. (Compare the disabled Datepicker to Timepicker). If you just add `field is-disabled` i think that will do it.
> 
> Just noticed because they dont look "as" disabled without it.

@tmcconechy 
Fixed for timepicker and lookup. Works for select and textarea. Doesn't work for regular input, should I fix it for regular input as well?

**Comment by tmcconechy** [comment]
@andriivarhanov it seems to work on input if you use this example http://localhost:4000/components/input/example-index.html 

Or if you just mean should you add it on the input as well on that example. Then yes i would say that would be good.

**Comment by andriivarhanov** [comment]
@tmcconechy I meant if we should consider adding `is-disabled` class to the `field` by js for regular input. The class being added on initialization in select, textarea, timepicker, datepicker and lookup components if element has disabled attribute.

**Comment by tmcconechy** [comment]
@andriivarhanov ok if thats the case that would be a good addition.

**Comment by andriivarhanov** [comment]
@tmcconechy I've added check for disabled inputs to form component https://github.com/infor-design/enterprise/pull/5431/commits/0595d467e27e15af3657116dbc768de7e6c2eb49

**Review by tmcconechy — APPROVED** [review]
Looks good. Nice job @andriivarhanov 👍🏻

**Review by EdwardCoyle — APPROVED** [review]
Looks great, @andriivarhanov.  Thanks for the contribution!

**Review by ericangeles — APPROVED** [review]
Nice work, @andriivarhanov ! 🍌

**Pull request merged**
