### PR TITLE
7762/7760 -Add fixes for editor and color picker

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed broken functionality in color picker and editor. @ericangeles @tjamesallen15 

Caused By:
https://github.com/infor-design/enterprise/pull/7735/files#diff-b06106137d1a69bd28f432d8c8b19dddc9714fea7df3462dbf570c09983197c0R1059

I reverted that change as its going to impact a lot of people. Maybe you can test that the issue went away as i was unable to get that stackblitz to work. Also we dont want it to close on the submenu click anyways.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/7762
Fixes https://github.com/infor-design/enterprise/issues/7760

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/editor/example-index.html
- make sure you can pick a heading in the heading picker
- go to http://localhost:4000/components/colorpicker/example-index.html
- make sure you can pick a color in the picker

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
I see. Yeah, that makes sense.

**Review by janahintal — CHANGES_REQUESTED** [review]
Unable to change font height after changing text color.
https://app.screencast.com/rfLmbA4HkpK6U

**Comment by tmcconechy** [comment]
@janahintal it appears this did not work for some time so is unrelated https://4840-beta0-enterprise.demo.design.infor.com/components/editor/example-index.html

We will have to fix that one later do to priorities so can you make a new issue for that?

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
Please retest it @infor-design/qa

**Review by janahintal — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving this on both http://localhost:4000/components/editor/example-index.html & http://localhost:4000/components/colorpicker/example-index.html and just created new issue for the unrelated issue I found during testing. Thanks! :)

**Pull request merged**
