### PR TITLE
7507 - New classes and example page for listview card

### LINKED ISSUE #7507: ListCards: New Set of classes (components)
**Describe the bug**
Add additional list view card examples https://www.figma.com/file/vFSHOqtgm9ypxOtOTHoBjF/List-View-Cards?type=design&node-id=175-10662&t=oZtZIfwqEQTRcsFz-0(on top left side)

Should be a new page with the variants in this design in a list.

**Other Similar Existing Variants:**

https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-variations-hitboxes.html
https://main-enterprise.demo.design.infor.com/components/hierarchy/example-stacked.html
https://main.wc.design.infor.com/ids-swipe-action/example.html

(leave them for now)

**Additional context**
cc @jmacaluso711

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

On http://localhost:4000/components/listview/example-card
- The listview on the left is a listview of cards. Added card-list class for styles on a listview of card components. 
- The one on the right is the usual listview with custom html, based on this example: http://localhost:4000/components/listview/test-custom.html

**Related github/jira issue (required)**:

Closes #7507 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/listview/example-card

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Hi @yohannahbautista looking pretty good. I worked with design and got some feedback as follows:

1) some buttons are square (filter and ...) just use the same btn-icon and btn-tertiary buttons and styles as the button page (reuse that component)
2) the list on the right side doesn't really need a vertical scroll bar
3) For placement in the page use a home page like this example https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html
Then show the two left and right sides as widget contents. Inside it (borderless homepage widget at 1x1 and at 2x1). Thats the proper placement.
3. Design noticed this (try safari) (in mac turn scroll bars off)
Screenshot 2023-06-09 at 10 00 03 AM
4. For the filter button maybe use another icon so that in classic it doesnt disappear (QA) will notice https://7507-card-listview-enterprise.demo.design.infor.com/components/listview/example-card?theme=classic&mode=light&colors=ffffff
5. The red late label looks a little tight with the text - can you recheck figma
6. The cards can be optionally selected. This means they get the same hover state and click to select functionality as the ones on https://github.com/infor-design/enterprise/pull/7584 (we maybe want to put this functionality in a util and reuse it). 

cc @ericangeles

**Comment by tmcconechy** [comment]
FYI ~ in https://github.com/infor-design/enterprise/pull/7584 i made a jquery function to select a group of elements you can try to reuse here.

**Comment by tmcconechy** [comment]
Looking good. A few additional comments.

1. did you manage to reuse https://github.com/infor-design/enterprise/blob/main/src/utils/selectable.jquery.js
2. Instead of an auto-height widget we should put it in a border-less widget that is 1x2 (2 height) and then should be scrollable inside the widget. May not need that auto height addition
3. I think the ... button should have the same hover state as other buttons. Only the widget header has the minimal hover state
Screenshot 2023-06-21 at 9 22 06 AM
4. In dark mode the selection state should be azure 06 (change/add a sass variable) and also the border bleeds a bit
Screenshot 2023-06-21 at 9 24 03 AM
5. in dark / classic mode they have a double background and the button color is too dark
Screenshot 2023-06-21 at 9 24 30 AM

**Comment by tmcconechy** [comment]
@yohannahbautista opening this up for review from design. But i see two things

1. A lot of space at the bottom when you screel down. Also the cards dont seem to line up same size at the bottom . Should be more like https://main-enterprise.demo.design.infor.com/components/homepage/example-scenario-b.html but without the borders ect.
2. I think the hover state and selection state is incorrect should be like https://main-enterprise.demo.design.infor.com/components/stats/example-index.html with the borders the same and the hover state is on the border. And when you click it to select "shifts" a little bit. Actions works the right way for border, hover and selection states so maybe can reuse the same css code

**Comment by tmcconechy** [comment]
@yohannahbautista looks good

1. the card borders dont look quite right they should look like http://localhost:4000/components/cards/example-workspace-widgets.html (just the box shadow). Maybe have to do `$(elem).card()` like that example 
2. when i hover the card it has a weird animation. also should maybe use a pointer cursor.

Still waiting for some feedback from @talkaboutdesign

**Comment by tmcconechy** [comment]
@yohannahbautista here is the design feedback from https://www.figma.com/file/3nceANMnllWQviKSfqqkeM/ListView_Example_Card?type=whiteboard&node-id=0%3A1&t=PdvD191SWdtiAWvW-1

**Comment by talkaboutdesign** [comment]
@yohannahbautista @tmcconechy 

Selected state does not match KPIs the border is smaller. 
There is inconsistency in spacing. 

CleanShot 2023-06-27 at 10 11 33@2x

Should be 16px always. 


Overflow menu missing text? 

CleanShot 2023-06-27 at 10 13 26@2x

CleanShot 2023-06-27 at 10 13 33@2x

**Comment by talkaboutdesign** [comment]
Looks like if you remove the extra div, and change the button to just btn-icon it fixes it. 

CleanShot 2023-06-27 at 16 20 59@2x

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista everything looks good to me. Do you want to have one quick look @talkaboutdesign 

- The only issue i see is that if you go in dark mode the icon doesnt look really good. My suggestion would be to remove the amber border and amber background color when in dark mode theme only.

Thanks @yohannahbautista ! Nice work

**Comment by talkaboutdesign** [comment]
I see see the issues I pointed out above. Just did local run. Let's keep dark mode similar to KPI. https://7507-card-listview-enterprise.demo.design.infor.com/components/stats/example-index.html?theme=new&mode=dark&colors=default

**Comment by talkaboutdesign** [comment]
@tmcconechy @yohannahbautista Whats left is selected state should match Stats KPIs (currently it does not). 
And in Dark mode we should keep icon only just like Stats KPIs. 

Please double check if hover, selected matches this. Should be 1 to 1. 
https://7507-card-listview-enterprise.demo.design.infor.com/components/stats/example-index.html

**Review by tmcconechy — APPROVED** [review]
Fixed those last 2 items @talkaboutdesign

**Comment by ericangeles** [comment]
Great job! Additionally, we should include documentation for the listview-card feature, @yohannahbautista.

**Review by jbrcna — APPROVED** [review]

**Review by janahintal — DISMISSED** [review]

**Comment by tmcconechy** [comment]
lets merge when docs are added. everything is approved other than that

**Review by ericangeles — APPROVED** [review]

**Comment by yohannahbautista** [comment]
> Hi Team, just noticed that some icons are not visible in classic for all modes. image

@tmcconechy  @ericangeles  Hello, I'm following what's in the figma and there are a lot of icons not available in Classic, should I change or let it be?

**Comment by tmcconechy** [comment]
I think we will just leave this be since we need a beta. But normally in those situations what i would do is change the icon out with one in both themes so QA doesn't flag it.

**Comment by talkaboutdesign** [comment]
> I think we will just leave this be since we need a beta. But normally in those situations what i would do is change the icon out with one in both themes so QA doesn't flag it.

Agree with Tim. But technically speaking this component is "not supported" in classic. From design POV.

**Comment by tmcconechy** [comment]
Merging as is for now

**Pull request merged**
