### PR TITLE
4598 column line charts combined

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Whats the status on this one @ericangeles ? Thanks!

**Comment by ericangeles** [comment]
@tmcconechy had a problem with converting the x-axis to generate its position. You can take a look. Although the line component is there now.

**Comment by tmcconechy** [comment]
Any ideas @deep7102 ?

**Comment by deep7102** [comment]
Thanks! @ericangeles you was on the right track just bit off, but it fixed now should be line chart working fine, adjusted the dataset in example page, added new example to display hidden line dots and added below task list what had in mind to cover in this ticket still left few checks please take look and try to complete or if some other idea/approach you have can apply as you want.

 - [x] Add line chart (might need separate scale)
 - [x] Add dots to line (optional setting as line chart)
 - [x] Add animation
 - [x] Adjust for RTL
 - [ ] Adjust tooltip (should adjust line data in same column chart tooltip)
 - [ ] Add legend (should looks like a line as it shown in ticket [4598](https://github.com/infor-design/enterprise/issues/4598) screen shout)
 - [ ] Add automation-id's for line and dots (if need)

**Comment by deep7102** [comment]
> Also why does the line start a bit after the first bar? Is it independent data?

@tmcconechy it start from center in group, because all the data points are in center of each group
so if group have more bars it will be always stay in center align

**Comment by tmcconechy** [comment]
closing for now but can reraise when done on https://github.com/infor-design/enterprise/issues/4598

**Pull request closed without merging**
