### PR TITLE
NG1435 - Timepicker Validation

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix validation on timepicker not working properly after calling updated.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1435

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/timepicker/example-validation.html
- Find the `Uses Required Validation only on blur` Timepicker
- Try focusing on the input and go blur. `Required` message should pop below.
- Find the `Uses Required Validation with Time Validation` Component
- Try strictly putting `2` inside the input. `Required` message should pop below.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
This PR needs this PR to be merged first -> https://github.com/infor-design/enterprise/pull/7451

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@CindyMercadoReyes ready for QA

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
Ready to test @infor-design/qa

**Review by jbrcna — CHANGES_REQUESTED** [review]
no message is displayed in` Uses Required Validation with Time Validation `
image

**Review by glenlieorillo — COMMENTED** [review]
**Test result:**

http://localhost:4000/components/timepicker/example-validation.html
image

**Comment by ericangeles** [comment]
@jbrcna it looks like it's working? Can you retest it again?

**Comment by ericangeles** [comment]
> **Test result:**
> 
> http://localhost:4000/components/timepicker/example-validation.html image

@jbrcna Could you provide more information about your testing procedure and the criteria used to determine whether this is a pass or fail?

FYI for the @infor-design/qa

**Comment by janahintal** [comment]
Hi Team, still failing on my end. 
1. When I try to focus, click then go blur, the validation doesn't show unless I tab. 
2. When I try putting 2 inside the input. Required message don't show up. 

image

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
