### PR TITLE
7379 - card design enhancements

### LINKED ISSUE #7379: Widget/Card: Design Changes
**Is your feature request related to a problem or use case? Please describe.**
A list of changes to be incorporated by OS fully outlined on https://jira.infor.com/browse/IDS-1004

**1. Anatomy**

- [ ] Border Radius change from 3px to 8x
- [ ] Change the header height from 50 px (34px + 8px top/bottom margins) to 48px

https://jira.infor.com/browse/IDS-1005

**2. Settings**

- [ ] Border on and off
- [ ] Shadow on and off setting/class
- [ ] Header on and off setting/class
- [ ] Add padding 16px on card insides
- [ ] Padding on and off setting/class
- [ ] Add docs to readme

https://jira.infor.com/browse/IDS-1006

### LINKED ISSUE #7445: Homepage/Widgets: Change the sizes/gutter and banner sizes
**Is your feature request related to a problem or use case? Please describe.**
Change the gutter, banner and home page widget sizes. The changes would be in homepage.js and homepage.scss

**Describe the solution you'd like**
Test all example scenarios https://main-enterprise.demo.design.infor.com/components/homepage and see that it all works out.

**Additional context**
https://jira.infor.com/browse/IDS-989

### LINKED ISSUE #7510: Icons: Monthly drop
**Describe the bug**
Monthly icon drop
```
Asset updates:

Icons inconsistency fixed:
confirm-filled
success
success-alert
save
save-new
save-close
star-outlined
star-filled
star-half
stop-button
face-happy
face-sad
pause-button
coleman
copy

New system icons added:

vertical-ellipsis (in classic and new)
change-department
shifting
shift-origin
shift-destination
swap-list-left
swap-list-right 
single-line-drag
```

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds feature enhancements to the card/widget component and adjusts sizes, gutters, and banners on the homepage.

For the specs, see the ticket issues

**Related github/jira issue (required)**:

Closes #7379
Closes #7445 
Closes #7510

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Homepage sizes, gutters, and banner sizes #7445. See [Figma](https://www.figma.com/file/DxLvQRUlFFEf5cTuEICEEM/Widget-Enhancements-(documentation)?node-id=218-7540&t=00TpJYD8B7lSj2wg-0)
- Go to http://localhost:4000/components/homepage/example-hero-widget.html or http://localhost:4000/components/homepage/example-workspace.html?colors=ffffff
- Also test original old style cards http://localhost:4000/components/cards/example-index.html
- Widget gutter should have a `16px` gap
- Widget height should be `368px`
- Vertical gutter should be  `16px`
- Gutter between banner/hero and other widgets should be `32px`
- Banner/Hero max-height should be `384px`
- Banner/Hero vertical padding should have `8px`

2.) Widget Anatomy #7379
- Go to http://localhost:4000/components/cards/example-workspace-widgets.html
- Inspect the cards
- New widget/card should have `8px` border radius
- Header height should `48px`
- Box shadow of the widget/card should be `box-shadow: 0 2px 4px 1px rgba(0, 0, 0, 0.05)` See figma file for more in-depth details

3.) Borderless Widget
- Go to http://localhost:4000/components/cards/example-workspace-widgets.html
- `Borderless with Action` - If custom-icons are present, custom-actions and btn-actions will be shown.(Standard behavior)
- `Borderless` - the btn-actions will only be shown when hovering over the card/widget

4) Other
- see the subtitle example http://localhost:4000/components/cards/example-workspace-widgets.html

5.) Header with badge
- Go to http://localhost:4000/components/cards/example-workspace-widgets.html
- It should show a badge in the header in one widget

6.) Widget with back button
- Go to http://localhost:4000/components/cards/example-workspace-widgets.html
- Click the button in the back button example `Click to open detail view`
- It should show the detail view
- The header section will show the back button and detail custom buttons
- Click the back button
- It should go back to the previous view

7.) Search Style
- go to http://localhost:4000/components/cards/example-search.html
- also on http://localhost:4000/components/cards/example-workspace-widgets.html
- see new style
- check modes/colors
- scroll the list (the one list is intentionally empty)

8.) New Example
- http://localhost:4000/components/homepage/example-workspace.html
- ignore colors but they somewhat work
- ignore mobile

8.) New Example with all card features
- http://localhost:4000/components/cards/example-workspace-widgets.html
- ignore colors but they somewhat work
- ignore mobile

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
FYI, I'll update the PR description once the example pages are okay.

**Review by tmcconechy — COMMENTED** [review]
1. http://localhost:4000/components/cards/example-bordered.html -> should the action button get the hover state? it does here http://localhost:4000/components/cards/example-new-widget-anatomy.html
2. http://localhost:4000/components/cards/example-borderless.html if you hover the first widget the actions button seems on the wrong side?
3. http://localhost:4000/components/cards/example-expandable-cards.html -> has an extra ... menu that is overlapping the text. Remove it?
4. http://localhost:4000/components/cards/example-four-by-four.html -> should we make all the ... buttons the new way?
5. http://localhost:4000/components/cards/example-variations-hitboxes.html -> has the drag icon now? seems incorrect

**Comment by tmcconechy** [comment]
@ericangeles i reviewed with Maks (couldnt find his github id to ping) and he suggested it basically the idea is

- in borderless widget it can have just an actions button. If it does it is invlisible until hovered
- it can also have a second text / icon button if that button is (more than just the actions button. then in that case both buttons are visible. It seems like a wierd case but thats what they wanted. Can maybe do it with a "show-buttons" class they have to manually apply or try and apply it of more than just the actions button

**Comment by ericangeles** [comment]
@tmcconechy, I suggest that we consider updating the Figma file for this project. I've been relying on it to keep track of changes, but it may be beneficial to ensure it's up to date.

**Comment by EdwardCoyle** [comment]
@ericangeles everything looks really good here!  I think the only remaining issue is the more actions "..." buttons seem to be missing the hover state BG color, as seen on http://localhost:4000/components/cards/example-borderless.html:

Screen Shot 2023-05-08 at 9 09 21 AM

**Comment by tmcconechy** [comment]
@ericangeles i fixed the hover color up

**Comment by danielortiz1982** [comment]
GM @EdwardCoyle and @deep7102 
When you start this morning can you please provide support on this PR. We kind of need it merged today. Thanks!

**Review by EdwardCoyle — APPROVED** [review]

**Comment by EdwardCoyle** [comment]
Great work @ericangeles, this looks awesome

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
1. Homepage sizes, gutters, and banner sizes [#7445](https://github.com/infor-design/enterprise/issues/7445). **PASSED**
http://localhost:4000/components/homepage/example-hero-widget.html
Widget gutter should have a 16px gap – Passed
Widget height should be 368px – Passed
Vertical gutter should be 16px – Passed
Gutter between banner/hero and other widgets should be 32px – Passed
Banner/Hero max-height should be 384px – Passed
Banner/Hero vertical padding should have 8px – Passed

image

image
     
image

2. Widget Anatomy #7379 – **FAILED**
New widget/card should have 8px border radius – Passed
Header height should 48px – Passed
Box shadow of the widget/card should be box-shadow: 0 2px 4px 1px rgba(0, 0, 0, 0.05) - Failed

image

image

_this should be **rgba (0, 0, 0, 0.05)** instead of **rgba (0, 0, 0, 0.15)**_
image

3. Borderless Widget - **PASSED**

Go to http://localhost:4000/components/cards/example-borderless.html
Borderless Card/Widget with Custom Action - If custom-icons are present, custom-actions and btn-actions will be shown.(Standard behavior) - Passed
Borderless Card/Widget with only Button Action - the btn-actions will only be shown when hovering over the card/widget - Passed

image

image

4. Other - **FAILED**
see the subtitle example http://localhost:4000/components/cards/example-with-subtitle.html

Ellipses - not visible in New Version
Header, subheader, calendar icon and ellipses are not properly aligned in Classic Version

https://github.com/infor-design/enterprise/assets/102151352/098a276e-efe6-4cd6-aa72-eb42ec2bfd32



5. Header with badge - **FAILED**

Go to http://localhost:4000/components/cards/example-with-badge-in-header.html
It should show a badge in the header - failing in Classic Version, badge is too much close to the header


https://github.com/infor-design/enterprise/assets/102151352/80f4b4d1-1b8d-418d-9d69-cbb9609ea895

image

6. Widget with back button - **FAILED**

Go to http://localhost:4000/components/cards/example-with-back-button
Click the button Click to open widget detail view
It should show the detail view
The header section will show the back button and detail custom buttons
Click the back button
It should go back to the previous view

Ellipses - not visible in New Version
Header, subheader, calendar icon and ellipses are not properly aligned in Classic Version

https://github.com/infor-design/enterprise/assets/102151352/e8d389d0-59b1-47f1-95e6-a28df7a7ba14

7. Search Style - **FAILED**

go to http://localhost:4000/components/cards/example-search.html
see new style
check modes/colors
scroll the list (the one list is intentionally empty)

Ellipses - not visible in New Version
Scroll list border looks off


https://github.com/infor-design/enterprise/assets/102151352/c60280ae-d872-4628-bb3a-3a66167db2cc

8.) New Example - **FAILED**

http://localhost:4000/components/homepage/example-workspace.html
ignore colors but they somewhat work
ignore mobile

Ellipses - not visible in New Version
Visible line in Classic Version (see test evidence)
Icons are missing in Classic Version (see test evidence)
Header and subheader are not properly aligned in Classic Version


image

https://github.com/infor-design/enterprise/assets/102151352/1ea03261-7bf1-41a3-a592-16c783adffca

**Comment by tmcconechy** [comment]
Addition feedback https://www.figma.com/file/PwVwlrnn6iAEoQkkmY2zux/New-Widgets---UI-Implementation-QA?type=design&node-id=0-1&t=eyslvSWJU191F40q-0 from design side

**Comment by janahintal** [comment]
1. Homepage sizes - Passed

2. Widget Anatomy https://github.com/infor-design/enterprise/issues/7379 – **FAILED**
New widget/card should have 8px border radius – Failed
image
Header height should 48px – Failed
image
Box shadow of the widget/card should be box-shadow: 0 2px 4px 1px rgba(0, 0, 0, 0.05) - Failed
image

3. Borderless Widget - Passed
Borderless Card/Widget with Custom Action - If custom-icons are present, custom-actions and btn-actions will be shown.(Standard behavior)
Borderless Card/Widget with only Button Action - the btn-actions will only be shown when hovering over the card/widget

.4 Other - Passed

5. Header with badge - Passed
It should show a badge in the header
image

6. Widget with back button - **FAILED** Text and Buttons are overlapping and is looking off in http://localhost:4000/components/cards/example-with-back-button
image

Click the button Click to open widget detail view - Failed button not working
It should show the detail view - Failed
The header section will show the back button and detail custom buttons Failed
Click the back button - Failed
It should go back to the previous view - Failed


7.  Search Style - **FAILED** cards with search looks different on Windows 
image

go to http://localhost:4000/components/cards/example-search.html
see new style
check modes/colors
scroll the list (the one list is intentionally empty)

8. New Example - **FAILED**
New
image
image

Classic: https://www.screencast.com/t/V7QZgWX41z 
Looks off in Classic especially on Dark and High contrast
image

**Review by deep7102 — DISMISSED** [review]
Looking good now!

**Review by deep7102 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@jbrcna - i fixed all your issues but if only localhost you may need to run `npm i` to get the missing icons
@janahintal - I couldnt see any of your issues anymore some of it looks fixed or your out of sync
@talkaboutdesign - i fixed whats in figma

NOTE: All steps are updated as all the new stuff is on https://7379-card-design-enhancements-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html

So maybe just take a quick recheck on that page as this is rather urgent

**Review by EdwardCoyle — DISMISSED** [review]

**Review by EdwardCoyle — APPROVED** [review]
I think all previous points have been addressed, thanks @tmcconechy @ericangeles

**Review by jbrcna — DISMISSED** [review]
approving.... just noting some observations/clarifications

http://localhost:4000/components/cards/example-workspace-widgets.html
Tab to the button -> shows the button.
-	there’s a bit of a delay when showing the button



http://localhost:4000/components/homepage/example-workspace.html?theme=new&mode=dark&colors=default
-	more actions button looks off
image


https://7379-card-design-enhancements-enterprise.demo.design.infor.com/components/homepage/example-workspace.html?colors=9279a6&theme=classic&mode=light
-	icons are missing in classic
-	if you change colors, labels are missing as well
image



http://localhost:4000/components/cards/example-workspace-widgets.html?theme=classic&mode=light&colors=default
-	in classic version, they all have border?

image


http://localhost:4000/components/cards/example-workspace-widgets.html - shouldn’t it be closed when going to detail view?
steps
1. click more actions
2. go to detailed view
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
This also should be borderless in Classic Version.

http://localhost:4000/components/cards/example-workspace-widgets.html?
image

**Comment by tmcconechy** [comment]
actually @glenlieorillo we didnt want to change classic for this. it has to keep the original look

**Comment by janahintal** [comment]
Approving with Observations.

Findings: **Windows Edge Browser** 

1. http://localhost:4000/components/cards/example-workspace-widgets.html?theme=classic&mode=light&colors=default - Borderless has borders on Classic Mode
image


2. Buttons and Icons are missing in Classic view: https://7379-card-design-enhancements-enterprise.demo.design.infor.com/components/homepage/example-workspace.html?colors=ffffff&theme=classic&mode=light
image

**Pull request merged**
