### PR TITLE
7321 - Tabs Module Activate previous tab when active is removed from overflow menu

### LINKED ISSUE #7321: Tabs Module: Closing an active tab in the overflow menu results in a blank screen
**Describe the bug**
If a user closes a dismissible module tab (that is currently active) from the overflow menu, it results in a blank screen because the previous tab is not being automatically activated. It is only a problem with module tabs (standard tabs is working properly).

1. Go to the Module Tabs index example: https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index.html
2. Click on the 'Create New Tab button' many times until you have about 3 tabs in the overflow menu (showing '3 More')
3. Click the overflow menu and choose the last tab in the menu so it becomes active
4. Click the overflow menu again and click the X icon on the last tab so that it closes
5. Notice that you see a blank screen because the previous tab did not automatically activate.

**Expected behavior**
The previous tab should automatically activate, just like it does when closing a non-overflowed tab, and just like it does for non-module tabs.

**Version**
- ids-enterprise: v4.80.1

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: CSD edge apps
 - Device: Windows Dell laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 110.0.5481.180 (Official Build) (64-bit)

**Additional context**
This is an important bug for us because we rely on the previous tab being activated in order to handle Angular route navigation and component cleanup properly.

Thank you!

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR changes how selected tab is determined when removing a tab to help activate previous one 

**Related github/jira issue (required)**:
Closes #7321

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/tabs-module/example-index.html
- click on the 'Create New Tab button' many times until you have about 3 tabs in the overflow menu (showing '3 More')
- click the overflow menu and choose the last tab in the menu so it becomes active
- click the overflow menu again and click the X icon on the last tab so that it closes
- see the previous tab is selected when removing an active one

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — DISMISSED** [review]
Looks good 🍌

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@CindyMercadoReyes @jbrcna @janahintal @glenlieorillo - ready for QA

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Working as expected. However, tabs are unreadable in Alabaster (New/Classic-Light/High Contrast) see test evidences below:


https://user-images.githubusercontent.com/102151352/235638510-80448003-b876-49c6-b4e4-47661aa7a1a3.mov


https://user-images.githubusercontent.com/102151352/235638647-99470df0-1ac9-4c64-811e-04c04fcd56ea.mov

**Review by jbrcna — CHANGES_REQUESTED** [review]
working as expected.
image

however, tabs were not readable in alabaster Light | High Contrast
image

**Comment by ericangeles** [comment]
Please re-test @infor-design/qa

**Comment by janahintal** [comment]
The behavior is different from the ff: 
When selecting a tab from dropdown, then deleting it right after, the page gets blank. However, when selecting from the visible tabs then deleting it, the active tab becomes the previous tab. 
image

**Comment by tmcconechy** [comment]
@janahintal i think @ericangeles fixed this? can you test again? Or lets make a new issue for the rest

**Review by EdwardCoyle — APPROVED** [review]
Agree Alabaster changes aren't within scope of this.  There are still some issues with the state but lets move to another issue

**Comment by jbrcna** [comment]
alabaster issue is now fixed. 
image

**Review by glenlieorillo — APPROVED** [review]
Re-tested and approved.

http://localhost:4000/components/tabs-module/example-index.html?theme=new&mode=light&colors=ffffff

https://user-images.githubusercontent.com/102151352/235838663-c6e7f257-4ee5-48d6-9aae-17ec32246a38.mov

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
