### PR TITLE
555 - Permanently enable the Field Options button's visibility on touch-based devices

### LINKED ISSUE #555: Enable permanently-displayed field options button in touch environments
**Is your feature request related to a problem? Please describe.**
The user experience surrounding the field options button on input fields doesn't currently work all that well (as of `v4.9.0`) in iOS environments, and doesn't work at all in Android environments.

To test, open http://master-enterprise.demo.design.infor.com/components/field-options/example-index.html in a mobile browser.

_In iOS Safari:_
- Field Options are not accessible unless the field is previously focused, and the button doesn't always stay in-tact when navigating away from the input field.

_In Android Chrome:_
- Field options are completely inaccessible on dropdown/multiselect components
- On most input fields, field options are visible once the input becomes focused, but immediately disappear and close their menus when the button is tapped.
- On checks/radios, interestingly enough everything works fine.

**Describe the solution you'd like**
- Field Options attached to other components should always be visible on the page and ready for interactions when a touch environment is detected (the Environment core component has a check for this as of `v4.10.x` that can be used)

**Additional context**
For an example of why we might want this, see the discussion about touch-enabled context menus on input fields in #245

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Previously, mobile devices had difficulty using Field Options buttons due to their dependency on hover and focus events.  This PR sets up a touch-device mode, which permanently displays the field options button in environments where a touch screen is present.

**Related github/jira issue (required)**:
Closes #555

**Steps necessary to review your pull request (required)**:
Pull this branch and run the demoapp, then:

_In a desktop browser:_
- open http://localhost:4000/components/field-options/example-index
- hover each field and ensure that the field options button for each is displayed
- focus each field and ensure that the field options button for each is displayed

_In a mobile browser:_
- open http://localhost:4000/components/field-options/example-index
- ensure that the field options button is permanently displayed next to each field, and can be accessed with a tap.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@davidcarlsonberg, just pushed... changed `mouseenter` and `mouseleave` to `mouseover` and `mouseout` to fix those issues with Timepicker, Fileupload, Lookup, and close buttons.  These events bubble, so it helped clean up the lifecycle a bit while giving us the ability to delegate.

I think the fact that field options doesn't display when hovering a disabled item is by design (the logic being: no extra commands should be available if a component's primary action is disabled).  I added some specific logic for this into the `.field`'s event handler for dealing with visibility changes.

**Comment by EdwardCoyle** [comment]
Noting for visibility that fixing #245 depends on this being merged

**Comment by tmcconechy** [comment]
screen shot 2018-08-08 at 8 46 14 am

**Comment by EdwardCoyle** [comment]
@tmcconechy the intention is that it's always visible on touch screen devices.  I'm not sure that it's going to translate perfectly in the Chrome dev tools.

**Comment by EdwardCoyle** [comment]
Yeah, we don't really have any other precedent for disabling hover state-related visuals on elements that don't have focus, although I could see the argument for it.  Let's leave it for now

**Pull request merged**
