### PR TITLE
5319: Move Track Dirty Examples to Individual Components

### LINKED ISSUE #5319: TrackDirty: Move examples to the individual components
**Is your feature request related to a problem or use case? Please describe.**

Design suggested we should not show trackdirty as if it was a component. 

**Describe the solution you'd like**
- on https://main-enterprise.demo.design.infor.com/components/list you dont see trackdirty
- Each example on https://main-enterprise.demo.design.infor.com/components/trackdirty/example-index.html goes into its reprpective component as example-track-dirty

**Describe alternatives you've considered**
NA

**Additional context**
https://jira.infor.com/browse/UXD-2549

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request remove the Track Dirty component from the main components list and adds each example to the individual component pages.

**Related github/jira issue (required)**:

UXD-2549
Closes #5319 

**Steps necessary to review your pull request (required)**:

- Pull branch `5319-trackdirty-move-examples-to-individual-components`
- Run app, `npm run start`
- Navigate to http://localhost:4000/components/list and notice that Track Dirty no longer appears in that list.
- Navigate to the following pages and notice that an `example-track-dirty.html` page exists under each component:
  - http://localhost:4000/components/checkboxes/list
  - http://localhost:4000/components/colorpicker/list
  - http://localhost:4000/components/dropdown/list
  - http://localhost:4000/components/input/list
  - http://localhost:4000/components/multiselect/list
  - http://localhost:4000/components/radios/list
  - http://localhost:4000/components/spinbox/list
  - http://localhost:4000/components/textarea/list

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
Is it recommended to remove the test on `/trackdirty/example-index.html` now that the folder is gone or is there a more desirable way to remove the trackdirty folder from `/components/list`?

**Comment by tmcconechy** [comment]
@davidcarlsonberg I think for this case the best thing would be to remove the trackdirty folder from the app folder and that should do it? So by the end all examples are elsewhere on the component now

**Review by tmcconechy — COMMENTED** [review]
This looks 👍🏻  just need to update the test https://github.com/infor-design/enterprise/pull/5417/files#file-test-components-trackdirty-trackdirty-api-func-spec-js-L4

**Comment by vivz753** [comment]
What exactly is dirty tracking?

**Comment by tmcconechy** [comment]
@vivz753 on the examples its a marker where if you edit the field it shows a mark that the field has been modified (dirty)

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
