### PR TITLE
7390 - Searchfield fix collapsible icon color and behavior 

### LINKED ISSUE #7390: SearchField: Collapsible Example Issues / Icon is not collapsed
**Describe the bug**
A few weird bugs with collapsible search fields.

**To Reproduce**

**Issue 1**
1. Go to http://localhost:4000/components/header/example-breadcrumbs.html?theme=new&mode=contrast&colors=0066D4
2. Click on search to expand
3. Type a few words
4. Click out
5. See that the x is visible (and dark)

**Issue 2**
1. Go to http://localhost:4000/components/header/example-flex-toolbar.html?theme=new&mode=contrast&colors=0066D4
2. type text in searchfield
3. click outside the field
4. see issue.
5. hover the field.
6. see issue

**Issue 3**
1. Go to http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=new&mode=contrast&colors=0066D4
2. type text in searchfield
3. click outside
4. see issue (test is cleared)

**Issue 4***
1. go to http://localhost:4000/components/header/example-flex-toolbar.html
2. notice the search con is missing

**Screenshots**
https://user-images.githubusercontent.com/56722184/228843781-d061c31d-5081-450f-9c01-7bb4b265c49c.png

https://user-images.githubusercontent.com/814283/228943172-123db67b-31f7-4b11-bfbb-5417ab059805.png

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds adjustments to searchfield's loop icon and text in collapsible or not collapsible state, in toolbar flex, in header, personalizable 

**Related github/jira issue (required)**:
Closes #7390

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/header/example-breadcrumbs.html?theme=new&mode=contrast&colors=0066D4
  - click on search to expand -> type a few words -> click out
  - see that the x is not visible
  - check colors and modes (alabaster + light, alabaster + dark)
  - check mobile view
- go to http://localhost:4000/components/header/example-flex-toolbar.html
  - see the search icon is not missing
  - type text in searchfield and click outside the field
  - see the text is visible
  - check colors and modes (alabaster + light, alabaster + dark)
  - check mobile view
- go to http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=new&mode=contrast&colors=0066D4
  - type text in searchfield
  - click outside, click on search
  - see the text is visible
  - check colors and modes (alabaster + light, alabaster + dark)
  - check mobile view
- go to http://localhost:4000/components/header/example-non-collapsible-searchfield.html?theme=new&mode=dark&colors=ffffff
  - type text in searchfield
  - see the text is visible
  - check colors and modes (alabaster + light, alabaster + dark)
  - check mobile view

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
I do see a problem with the breadcrumb color http://localhost:4000/components/header/example-breadcrumbs.html?colors=ffffff&theme=classic&mode=contrast

Maybe see if that can be fixed (it should be the subheader color). Because QA will notice that one. But we can also make a new issue if its too much?

**Comment by andriivarhanov** [comment]
@tmcconechy let's include breadcrumb color fix in this PR, will do

**Comment by andriivarhanov** [comment]
added adjustments for subheader breadcrumbs colors:
- regular http://localhost:4000/components/header/example-breadcrumbs.html
- personalized http://localhost:4000/components/breadcrumb/example-navigation-breadcrumbs.html
- alternate http://localhost:4000/components/header/example-breadcrumbs-alternate.html

**Comment by tmcconechy** [comment]
@andriivarhanov see a couple things

1. the breadcrumb fix http://localhost:4000/components/header/example-breadcrumbs.html?colors=db7726&theme=new&mode=contrast is not taking the color on the subheader
2. when you load http://localhost:4000/components/header/example-non-collapsible-searchfield.html?theme=new&mode=dark&colors=ffffff it has a wierd animation on the search icon
3. on http://localhost:4000/components/header/example-flex-toolbar.html i dont see the X (steps mention being able to see it so maybe needs step correction or its a bug)

**Comment by andriivarhanov** [comment]
@tmcconechy 

> the breadcrumb fix is not taking the color on the subheader

subheader should have `personalize-subheader` class to get the color, I've updated the example
http://localhost:4000/components/header/example-breadcrumbs.html?colors=1F9254


> when you load it has a wierd animation on the search icon

fixed http://localhost:4000/components/header/example-non-collapsible-searchfield.html?theme=new&mode=dark&colors=ffffff

> on http://localhost:4000/components/header/example-flex-toolbar.html i dont see the X (steps mention being able to see it so maybe needs step correction or its a bug)

searchfield in toolbar flex doesn't have clearable X button by default, I've updated the example

**Review by EdwardCoyle — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — COMMENTED** [review]
please see my findings below.

**Summary:**

- x icon  no hover state 
- the searchfield has outline (black | white)
- misaligned x icon 
- x icon disappears when hovered in all colors but alabaster & default 
- x icon turns blue with alabaster 
- Classic theme, only the default color has no hover state 
- Dark mode, only alabaster color has no hover state.
- Dark mode, x icon turns white when hovered in all colors but default

**Comment by jbrcna** [comment]
**1st item**
[header/example-breadcrumbs.html?theme=new&mode=contrast&colors=0066D4](http://localhost:4000/components/header/example-breadcrumbs.html?theme=new&mode=contrast&colors=0066D4)
x icon no hover state 
image

[header/example-breadcrumbs.html?colors=ffffff&theme=new&mode=light](http://localhost:4000/components/header/example-breadcrumbs.html?colors=ffffff&theme=new&mode=light) – the searchfield has outline with alabaster color only, with all other colors it has no outline. However, when using dark mode, the searchfield has white outline with all colors.
Light | High Contrast
image


----------------------------------
**2nd item** 
[header/example-flex-toolbar.html?theme=new&mode=light&colors=ffffff ](http://localhost:4000/components/header/example-flex-toolbar.html?theme=new&mode=light&colors=ffffff )– misaligned x icon 
image

x icon no hover state
image


[header/example-flex-toolbar.html?colors=7928E1 ](http://localhost:4000/components/header/example-flex-toolbar.html?colors=7928E1 )– x icon disappears when hovered in all colors but alabaster & default. with default color the x icon stays the same. with alabaster the x icon turns blue

Light | High Contrast
image

[header/example-flex-toolbar.html?theme=classic&mode=light&colors=default](http://localhost:4000/components/header/example-flex-toolbar.html?theme=classic&mode=light&colors=default) – in Classic theme only the default color has no hover state. Dark mode has hover state in all themes and colors but alabaster.

Light | High Contrast
image


[header/example-flex-toolbar.html?colors=ffffff&theme=classic&mode=dark ](http://localhost:4000/components/header/example-flex-toolbar.html?colors=ffffff&theme=classic&mode=dark )– in Classic theme, Dark mode has hover state in all themes and colors but alabaster.

Dark mode
image


[header/example-flex-toolbar.html?colors=default&theme=classic&mode=dark](http://localhost:4000/components/header/example-flex-toolbar.html?colors=default&theme=classic&mode=dark) – when using dark mode. x icon turns white when hovered in all colors but default
image


------------------------------------

**3rd item**
[header/example-header-with-multiple-buttons-and-searchfield.html?colors=default&theme=classic&mode=contrast](http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?colors=default&theme=classic&mode=contrast) – When using Classic theme, only default color has no hover state.
Ligh | High Contrast
image


[header/example-header-with-multiple-buttons-and-searchfield.html?colors=ffffff&theme=classic&mode=dark ](http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?colors=ffffff&theme=classic&mode=dark )- When using Classic theme dark mode, only alabaster color has no hover state.

Dark mode
image


**4th item**
[header/example-non-collapsible-searchfield.html?theme=new&mode=dark&colors=ffffff](http://localhost:4000/components/header/example-non-collapsible-searchfield.html?theme=new&mode=dark&colors=ffffff)
no hover state for x icon
image


[header/example-non-collapsible-searchfield.html?colors=default&theme=classic&mode=light]( http://localhost:4000/components/header/example-non-collapsible-searchfield.html?colors=default&theme=classic&mode=light) -When using Classic theme, only default color has no hover state.
Ligh | High Contrast
image

[header/example-non-collapsible-searchfield.html?colors=ffffff&theme=classic&mode=dark](http://localhost:4000/components/header/example-non-collapsible-searchfield.html?colors=ffffff&theme=classic&mode=dark )– When using Classic theme dark mode, only alabaster color has no hover state.

image

**Review by glenlieorillo — COMMENTED** [review]
**Additional Findings:**

1. Not visible in Alabaster:

http://localhost:4000/components/header/example-non-collapsible-searchfield.html?colors=ffffff&theme=classic&mode=contrast


https://user-images.githubusercontent.com/102151352/233356239-dcadfc86-f64d-4b76-bec1-eb9b268f04d5.mov


2. Search box and other menus are centered:

http://localhost:4000/components/header/example-flex-toolbar.html?theme=new&mode=dark&colors=ffffff
image

http://localhost:4000/components/header/example-flex-toolbar.html?theme=classic&mode=light&colors=default
image

http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=classic&mode=dark&colors=ffffff
image

**Comment by andriivarhanov** [comment]
added fixes according to the recent findings:
- x icon alignment and color  fixes
- added hover bg to x icon in the header
- added personalized outline to the searchfield
- classic theme removed buttons hover bg
- classic theme buttons visibility in alabaster color

**Comment by jbrcna** [comment]
all items mentioned [here](https://github.com/infor-design/enterprise/pull/7429#issuecomment-1515918733) are now fixed. However, I just notice one thing in dark mode default colors. the searchfield has white outline only in default color (classic | new). wasn't sure if this is an issue
image

Also,
http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?colors=default&theme=classic&mode=dark - with dark mode (classic | new), the icons look disabled. with all other colors it looks like it has a white color, thus not looking disabled. see slate color
_sorry I missed this on my previous testing_
image


**New found issue:**
http://localhost:4000/components/header/example-flex-toolbar.html - x icon not centered.
image

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]
Awesome! thank you for fixing all items. Approving...
 $\textcolor{green}{\textsf{added outline to searchfield for all colors in dark mode}}$
image

 $\textcolor{green}{\textsf{changed buttons color for default color in dark mode}}$
image

 $\textcolor{green}{\textsf{ x icon is now centered.}}$
image

**Comment by andriivarhanov** [comment]
please don't merge it yet, I'm checking and fixing issues after merge conflict with #7406 in personalized styles

**Comment by andriivarhanov** [comment]
this PR is ready to be merged now

**Pull request merged**
