### PR TITLE
2925 - Update Uplift app menu designs to latest design guidelines

### LINKED ISSUE #2925: Application Menu: Uplift Menu | Design QA
**Is your feature request related to a problem? Please describe.**
Yes, related to issue https://github.com/infor-design/enterprise/pull/2861 needs continued design QA

**Describe the solution you'd like**
Basically @EdwardCoyle & I had a back and forth seen here:
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538058493
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538061769
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538112804

This is an addition upon that here are the design revisions:

- [ ] The menu is looking at things from a background perspective that is light to dark (bg is light, a hover state is darker) this should be flipped. It should start dark to light because the other headers and page elements will be lighter.

- [x] Menu background — background: #252429;

- [x] Hover Menu Item — background #323036;
border-radius: 6px; 
TYPE
font-family: SourceSansPro-Regular;
font-size: 16px;
color: #FFFFFF;
>>> 2ND LVL & BEYOND <<<
font-family: SourceSansPro-Regular;
font-size: 14px;
color: #FFFFFF;

- [x] Selected Menu Item — background: #5C5861;
TYPE
font-family: SourceSansPro-SemiBold;
font-size: 16px;
color: #FFFFFF;
>>> 2ND LVL & BEYOND <<<
font-family: SourceSansPro-Regular;
font-size: 14px;
color: #FFFFFF;

- [x] Expanded Menu Item (first level only) — background: #000000;
TYPE
font-family: SourceSansPro-SemiBold;
font-size: 16px;
color: #FFFFFF;

- [ ] On the option with the 'expanded menu item level w/ background', lets make the shape edge to edge (and remove the rounded corners) https://www.dropbox.com/s/mqzwcthvnhlzikp/Screenshot%202019-10-08%2016.32.47.png?dl=0 

- [ ] The option 'expanded menu item level WITHOUT background should be developed: https://www.dropbox.com/s/v1wi6df2gvq2w10/Screenshot%202019-10-08%2016.35.31.png?dl=0

- [ ]Focus state hiding should be double checked

- [ ] I will need to provide the color states for other themes as well. So that the menu can be accessible across.

**Describe alternatives you've considered**
Opacity. I see it's value in that you can set it and forget it. In this case, we're working on a component that can be themed and opacity would work well across. Concerns around accessibility, but as long as we test against that it could still work. This could be promising.

**Additional context**
Updated designs:
IDS_ApplicationMenu_superExpandedNavItems_alt
IDS_ApplicationMenu_superExpandedNavItems
IDS_ApplicationMenu_expandedNavItems
IDS_ApplicationMenu_WithoutIcons
IDS_ApplicationMenu_WithIcons
original

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR implements a handful of guidelines from the design team on the Vibrant/Uplift application menu style:
- Got rid of gutters for second-level accordion headers/panes.
- Changed the ordering of the colors in each main theme to be "darkest first":  backgrounds are darker than hover/focus states (this used to be opposite).
- Animation to help prevent visual jank.

Initially putting this PR into draft status.  Before merging we should:
- [ ] open a demo server against this branch for testing (http://2925-appmenu-uplift-qa-enterprise.demo.design.infor.com)
- [ ] get sign off from @infor-design/design and implement any revisions they want to see.

**Related github/jira issue (required)**:
Closes #2925 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, run the demoapp
- Open a browser (test many!) and navigate to:
   - http://localhost:4000/components/applicationmenu/test-hcm.html?theme=uplift
   - http://localhost:4000/components/applicationmenu/test-hcm-icons.html?theme=uplift
- If the viewport is too small, open the application menu by using the hamburger button on the top left of the page header.
- Test navigation with clicks and keys on the application menu.
- Open all levels on both examples and ensure alignment is correct, and design guidelines are properly implemented. 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@infor-design/design can review the work here by checking out:
- https://2925-appmenu-uplift-qa-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light
- https://2925-appmenu-uplift-qa-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm-icons.html?theme=uplift&variant=light

**Comment by kevinwhitedesign** [comment]
Screenshot 2019-12-02 10 16 29
looks like some color states don't map to the different color themes

**Comment by EdwardCoyle** [comment]
@kevinwhitedesign I'll double check the personalization colors.  Other than that, would you say that the overall design of the secondary/expandable menus on the app menu is correct on this demo, per the design guidance?  Just trying to make sure we get that right before we merge this one.

**Comment by kevinwhitedesign** [comment]
@kentonquatman @elizabethhartley & I have discussed this ticket - there are some issues with: "Changed the ordering of the colors in each main theme to be "darkest first": backgrounds are darker than hover/focus states (this used to be opposite)." that we see, looks like if the color is changed it does not follow this concept. It's in our backlog to look further into this one

**Comment by EdwardCoyle** [comment]
I purposefully didn't add a visual regression test because I expect it to change again when the colors/font sizes/icons/etc are all finalized.  Doesn't seem like it's "solidified" enough yet for that.

I can go back and add a changelog note though.

**Comment by kentonquatman** [comment]
Reviewing each variant, I've noticed a few issues that we might want to look at.

**1. Subtle high-contrast:** Using the same menu as default (lower contrast)
Screen Shot 2019-12-10 at 10 41 30 AM

**2. Subtle + color:** Missing some styling treatments (darker background behind open menu and lines between menu items)
Screen Shot 2019-12-10 at 10 46 34 AM
Screen Shot 2019-12-10 at 10 47 55 AM

**3. Vibrant default:** Sub-menu items look too dark
Screen Shot 2019-12-10 at 10 51 42 AM

**4. Vibrant high-contrast:** Sub-menu items have low contrast
Screen Shot 2019-12-10 at 10 53 50 AM

**5. Vibrant + color:** contrast might be too low with dark text and dark backgrounds
Screen Shot 2019-12-10 at 10 56 22 AM

**6. Vibrant + color:** Icon colors aren't changing on hover states
Screen Shot 2019-12-10 at 10 57 59 AM

That's all I have for now. Let me know if you need design assistance with any of this.

**Comment by EdwardCoyle** [comment]
@kentonquatman Some of these color combinations don't look quite right to me... for example, the last two screenshots above are demonstrating "Soho" color palette options against the Vibrant theme.  Are you able to reproduce how you got these colors with specific steps?  I'm wondering if the page was loaded with the `?colors` query param set to a bad value when you snapped them?

**Pull request merged**
