### PR TITLE
3479 - Add ellipsis in modal title

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This solution fixes the modal title to a two line with ellipsis when it's too long (not a fullsize modal). The fullsize modal will still get the ellipsis but has only a one line. _(Still for discussion if it's gonna be the behavior)_

Created a new mixin for line clamp that can reuse.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/3479

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app.
- Navigate to http://localhost:4000/components/modal/test-long-title-large-content.html
- Click `Show Modal` button
- Notice that the modal title converted into a two line and has ellipsis.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Looks good! Seems some tests are failing tho.
Can we try and update the example to show using a tooltip when its cut off?

**Comment by deep7102** [comment]
See title in two lines and has ellipsis, but did not see the tooltip.

**Comment by ericangeles** [comment]
> See title in two lines and has ellipsis, but did not see the tooltip.

Just added now @deep7102

**Comment by deep7102** [comment]
Looks good 🍌

**Pull request merged**
