### PR TITLE
6289 - Datagrid: Datepicker icon visibility on toggle with source setting

### PR DESCRIPTION
**Pull request by sesbrenosienna**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a bug where the datepicker icon is not visible when the datagrid starts as non editable and toggled to editable and is visible when the datagrid starts as editable and toggled to non editable with a source setting.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6289

**Steps necessary to review your pull request (required)**:
Scenario 1

- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-toggle-editable.html
- Hover over the date cells
- Click the edit button
- Hover over the date cells

Scenario 2

- Pull this branch, build, and run the app
- Set editable: true on initialization in test-toggle-editable.html
- Go to http://localhost:4000/components/datagrid/test-toggle-editable.html
- Hover over the date cells
- Click the edit button
- Hover over the date cells

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by s-werking** [comment]
Hi @sesbrenosienna,

Is there a way that we could accomplish the calendar icon visibility toggling while still preserving the selected rows? In my application of this, I toggle editability after a certain number of rows are selected but if I 'rerender' then all of the selected row information is wiped out. Thanks!

**Comment by sesbrenosienna** [comment]
Hello @s-werking! 😄 

I will check this out. Thanks!

**Comment by s-werking** [comment]
Hi @sesbrenosienna,
This method to rerender the grid with the "allowSelectAcrossPages: true" setting worked great, thank you!

**Comment by tjamesallen15** [comment]
Looks good. Just need to add an entry in the changelog.

**Review by tjamesallen15 — APPROVED** [review]

**Comment by tjamesallen15** [comment]
Approving. The changelog was in the first PR and this was a follow up pr.

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
