### PR TITLE
8164 - Pie with Bordered Class

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix rendering issues when having bordered class in the widget.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8164

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/donut/test-bordered.html
- See the donut chart looking fine

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Unable to see other legends on responsive view
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
RTL
image

**Review by jbrcna — APPROVED** [review]
thanks!
image

**Review by yohannahbautista — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
image

**Pull request merged**
