### PR TITLE
4020 - Fix Dropdown backspace special character bug

### LINKED ISSUE #4020: Datagrid: Backspace issue with Dropdown lists on Grids
See a "口" display in the cell when pressing the "Backspace" key having selected an entry form a dropdown list on a grid

1. Open Example grid https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html
2. Press S key twice, then press Enter key, to select the Shipped option.
3. Press Backspace key twice
Result: "口" (square character) displayed in the cell

**Expected behavior**
No "口" (square character) displayed in the cell

**Version**
latest (4.28.2) *Screenshots**
image

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Chrome
 - 81.0.4044.138 (64 bit)

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes an issue where pressing `backspace` in Windows 10 and `fn + delete` in Mac OS was inserting a special character in the input field. Using `String.fromCodePoint` to check for the special char in windows. Also checking for IE11 as this is not supported, but the bug was actually not occurring in IE11 so I think it's safe.

**Related github/jira issue (required)**:
closes #4020 

**Steps necessary to review your pull request (required)**:
- pull and run branch
- Go to http://localhost:4000/components/datagrid/example-editable.html click in an editable cell in the Action column.
- Select a new value, "Shipped" for example.
- In Windows press `backspace`  / In Mac OS press `fn + delete`
- The cell should now clear and not display a special character.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Maybe getting my guys confused but:

- if running on a browser stack (windows running on a mac) and i do fn + delete ? Is that the same as back space key on a windows device?
- if so should it do the same thing as delete key?

ie:
- type s in the dropdown to open
- hit backspace (fn + delete ?) (nothing happens)

**Comment by jmacaluso711** [comment]
Yeah that's what I assumed was the correct behavior. If you're on Mac and you hit delete nothing happens so fn+delete in windows should be the same.

**Comment by tmcconechy** [comment]
Well on mac now delete (moves back in the list). So you have to type to filter then you can backspace what you typed.
fn+delete on mac i think isnt important there.

But what happens on PC (not able to test it on browser stack that accurately). Does backspace work or delete? Sounds from the issue they expect backspace to remove a character (not add the wierd char).

**Comment by jmacaluso711** [comment]
Here's what I'm seeing when I test:

Mac OS: Press `delete`, nothing happens (this was the previous behavior)
Mac OS: Press `fn + delete`, the selection is deleted and no special char is inserted
Windows (browserstack): Press `backspace`, the selection is deleted and no special char is inserted
Windows (browserstack): `fn + delete`, nothing happens.

**Comment by deep7102** [comment]
I tested with VM on my machine win10 and use onscreen keyboard (virtual keyboard comes with windows)

**Pull request merged**
