### PR TITLE
5663 - Added option to format numbers and dates on export

### LINKED ISSUE #5663: Datagrid: Add option to excel export to use the current locale
**Is your feature request related to a problem or use case? Please describe.**
Hi IDS-Team,

While i'm working with the AppBuilder and the AppHub, i mentioned that the app doesn't take the locale from my browser (as every other application from the CloudSuite does). This is a bigger problem for the export function (to excel). Some formattings are not available (e.g. the Decimal separator (,) and 1000 separator (.) As usual in Germany) and have to be done after the excel export. When i set up different apps, i don't want the user to format the data after export.

Therefore i request you to improve your export functionality to take locale into consideration, so that after that the AppBuilder Team can implement a way for users to change the locale in app builder. 
Right now the export function just takes the data from the grid with no formatting.

The best way would be that the application takes the locale from the browser or i can set it in the app configurations.
I explained the problem in ticket 15714463 on the Infor Concierge Portal.

Please work on this issue because it will increases the attractiveness of the app. Otherwise it becomes unusable in many cases.

Thanks

**Describe the solution you'd like**
Add an option so that the export to excel uses the current locale when exporting dates/numbers.

**Describe alternatives you've considered**
End user has to do it everytime which is a pain.

**Additional context**
AppBuilder and the AppHub

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added format option in excel parameters on exportToExcel and exportToCsv. The default is false. If set to true, numbers and dates will be formatted according to current locale for export.

**Related github/jira issue (required)**:

Closes #5663 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-export-format.html
- Select a locale in the Locale dropdown
- Export the datagrid
- Excel/CSV should follow the specified locale format in numbers and dates

**Included in this Pull Request**:
- [ ] A new example page.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Hi @yohannahbautista I see a couple issues here.

1. Try exporting a csv as en-US and de-DE and compare
1. The price is 500 (no decimal) in one and 500,00 in the other 
1. The date is not changing format.. Should also format dates
1. Also looks like the tests may need updates

Thanks 👍🏻

**Comment by ericangeles** [comment]
Great work, @yohannahbautista! 🍌 We just need to fix the build and I believe this is another chrome version driver issue. It is persistent in other PRs as well. I will take a look.

**Comment by ericangeles** [comment]
@yohannahbautista this is the fix for the failing tests https://github.com/infor-design/enterprise/pull/5891. Once all passed, we can merge it to the main and update this branch.

**Comment by EdwardCoyle** [comment]
@yohannahbautista #5891 is merged, we'll watch this branch for passing tests

**Review by ericangeles — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
