### PR TITLE
NG1675 - BarStacked/ColumnStacked Many Records

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix an error encountered when having many records inside the graph.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1675
Related #8367 

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/bar-stacked/test-many-records.html
- Open `Developer Console`
- See no errors
- Go to http://localhost:4000/components/column-stacked/test-many-records.html
- Open `Developer Console`
- See no errors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@tjamesallen15 maybe the tooltip needs reformatting in this case (two columns?) so maybe something where it goes two column if more then a certain no of records

Hover the bar

Screenshot 2024-05-09 at 10 28 46 AM

**Review by glenlieorillo — COMMENTED** [review]
Showing no errors in the console. However, I agree with @tmcconechy. The tooltip is not displaying correctly. I will create a new issue for this bug.

https://github.com/infor-design/enterprise/assets/102151352/bb5a1e5b-f177-44d3-85c9-d07b3c419603

image


https://github.com/infor-design/enterprise/assets/102151352/d45578d9-db3b-4eeb-8d0a-73fcf4e171a5

**Comment by n-ace-ancog** [comment]
Aside from the tooltip, the vertical scroll bar seems it overshot a little.

image

**Review by janahintal — APPROVED** [review]
No errors on my end. 
image
image

**Review by tmcconechy — APPROVED** [review]
Looks good to me. I wouldnt mind fixing the tooltip issue if possible too but if we need to wait thats fine.

Also funny, i saw the scrollbar issue now i dont see it? Did you fix? I saw a fix for it yesterday but got side tracked, now i dont see it?

**Review by janahintal — COMMENTED** [review]
Tooltip still looks cut off in Mobile / Responsive view
image

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 are we fixing the tooltip to two column? Or doing that later?

**Comment by tmcconechy** [comment]
@ericangeles sure, i think maybe just change it to stack in two columns if say more than 10 bar items

**Comment by ericangeles** [comment]
@tmcconechy, agree with that design.

**Review by glenlieorillo — APPROVED** [review]
Showing no errors in the console log. Tooltip issue: https://github.com/infor-design/enterprise/issues/8708

https://github.com/infor-design/enterprise/assets/102151352/e0039f23-27d3-4e02-a39a-90ba1dd10b35


https://github.com/infor-design/enterprise/assets/102151352/99243bf6-927a-4a20-9f70-b8b2f52b6186

**Review by jbrcna — APPROVED** [review]
image
image

**Comment by tmcconechy** [comment]
@ericangeles should we maybe disable the tooltip? Or put in an issue to fix it later?

**Comment by ericangeles** [comment]
Lets fix it later, Tim. I believe QA created the issue on tooltip.

**Pull request merged**
