### PR TITLE
2211 - Fix Uplift Icon/Text Alignment [v4.19.x]

### LINKED ISSUE #2211: Icons: Theme Uplift icon alignment is off
**Describe the bug**
General icon alignment inside of buttons for Uplift theme is off.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/?theme=uplift
2. Review all items with icons
    - [x] buttons
    - [x] spinbox
    - [x] process indicator
    - [x] badges
    - [x] timeline
    - [x] dropdown
    - [x] checkboxes
    - [x] icons on Targeted Achievement chart (#2220)

**Expected behavior**
The alignment should look pretty.

**Version**
- ids-enterprise: 4.19.0-dev+ (uplift theme)

**Screenshots**
Screen Shot 2019-05-21 at 6 01 32 PM

**Platform**
- all

**Additional context**
Related to #2072

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes many text-to-icon alignment problems, padding, and margin changes associated with the Uplift theme addition.  See the list below for the components changed. 

**Related github/jira issue (required)**:
Closes #2211 

**Steps necessary to review your pull request (required)**:
Compare "Soho" and "Uplift" differences in alignment, padding, spacing, etc of Icons and Text in the provided list of components.  If there are any differences at all, they should be minimal.  Review the following list of pages in IE, Edge, Firefox, Chrome, Safari, etc.  Also check on mobile devices.

_Badges:_
- http://localhost:4000/components/badges/example-index
- http://localhost:4000/components/badges/example-index?locale=ar-EG
- http://localhost:4000/components/badges/example-index?theme=uplift
- http://localhost:4000/components/badges/example-index?theme=uplift&locale=ar-EG

_Button:_
- http://localhost:4000/components/button/example-index
- http://localhost:4000/components/button/example-index?locale=ar-EG
- http://localhost:4000/components/button/example-index?theme=uplift
- http://localhost:4000/components/button/example-index?theme=uplift&locale=ar-EG

_Checkboxes:_
- http://localhost:4000/components/checkboxes/example-index.html
- http://localhost:4000/components/checkboxes/example-index.html?locale=ar-EG
- http://localhost:4000/components/checkboxes/example-index.html?theme=uplift
- http://localhost:4000/components/checkboxes/example-index.html?theme=uplift&locale=ar-EG

_Colorpicker:_
- http://localhost:4000/components/colorpicker/example-index.html
- http://localhost:4000/components/colorpicker/example-index.html&locale=ar-EG
- http://localhost:4000/components/colorpicker/example-index.html&theme=uplift
- http://localhost:4000/components/colorpicker/example-index.html&theme=uplift&locale=ar-EG

_Dropdown:_
- http://localhost:4000/components/dropdown/example-index.html
- http://localhost:4000/components/dropdown/example-index.html?locale=ar-EG
- http://localhost:4000/components/dropdown/example-index.html?theme=uplift
- http://localhost:4000/components/dropdown/example-index.html?theme=uplift&locale=ar-EG
- http://localhost:4000/components/dropdown/example-icons.html
- http://localhost:4000/components/dropdown/example-icons.html?locale=ar-EG
- http://localhost:4000/components/dropdown/example-icons.html?theme=uplift
- http://localhost:4000/components/dropdown/example-icons.html?theme=uplift&locale=ar-EG
- http://localhost:4000/components/dropdown/test-icon-short-fields.html
- http://localhost:4000/components/dropdown/test-icon-short-fields.html?locale=ar-EG
- http://localhost:4000/components/dropdown/test-icon-short-fields.html?theme=uplift
- http://localhost:4000/components/dropdown/test-icon-short-fields.html?theme=uplift&locale=ar-EG

_Editor (buttons should all be present and not spilled over):_ 
- http://localhost:4000/components/editor/example-index?theme=uplift
- http://localhost:4000/components/editor/example-index?theme=uplift&locale=ar-EG

_Input (Short Fields):_
- http://localhost:4000/components/input/test-short-fields.html
- http://localhost:4000/components/input/test-short-fields.html?locale=ar-EG
- http://localhost:4000/components/input/test-short-fields.html?theme=uplift
- http://localhost:4000/components/input/test-short-fields.html?theme=uplift&locale=ar-EG

_Multiselect:_
- http://localhost:4000/components/multiselect/example-index.html
- http://localhost:4000/components/multiselect/example-index.html?locale=ar-EG
- http://localhost:4000/components/multiselect/example-index.html?theme=uplift
- http://localhost:4000/components/multiselect/example-index.html?theme=uplift&locale=ar-EG

_Process Indicator:_
- http://localhost:4000/components/processindicator/example-index
- http://localhost:4000/components/processindicator/example-index?locale=ar-EG
- http://localhost:4000/components/processindicator/example-index?theme=uplift
- http://localhost:4000/components/processindicator/example-index?theme=uplift&locale=ar-EG

_Responsive Forms:_
- http://localhost:4000/components/form/example-inputs.html
- http://localhost:4000/components/form/example-inputs.html?theme=uplift
- http://localhost:4000/components/form/example-inputs.html?locale=ar-EG
- http://localhost:4000/components/form/example-inputs.html?theme=uplift&locale=ar-EG

_Spinbox:_
- http://localhost:4000/components/spinbox/example-index
- http://localhost:4000/components/spinbox/example-index?locale=ar-EG
- http://localhost:4000/components/spinbox/example-index?theme=uplift
- http://localhost:4000/components/spinbox/example-index?theme=uplift&locale=ar-EG

_Timeline:_
- http://localhost:4000/components/timeline/example-index
- http://localhost:4000/components/timeline/example-index?locale=ar-EG
- http://localhost:4000/components/timeline/example-index?theme=uplift
- http://localhost:4000/components/timeline/example-index?theme=uplift&locale=ar-EG

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
Latest Chrome on Mac for all of these comments:

http://localhost:4000/components/button/example-index?locale=ar-EG
http://localhost:4000/components/button/example-index?theme=uplift&locale=ar-EG
- "..." menu button in RTL Uplift could be lowered by like one or two pixels

http://localhost:4000/components/checkboxes/example-index.html?locale=ar-EG
http://localhost:4000/components/checkboxes/example-index.html?theme=uplift&locale=ar-EG
- labels could be lowered by like one or two pixels

http://localhost:4000/components/dropdown/example-icons.html?theme=uplift
- Icons seem just a pixel or two too low

http://localhost:4000/components/dropdown/example-icons.html?theme=uplift&locale=ar-EG
- Icons seem just a pixel or two too high

http://localhost:4000/components/dropdown/test-icon-short-fields.html?theme=uplift&locale=ar-EG
- "W" seems too high and the ellipsis collides with the dropdown arrow icon

http://localhost:4000/components/input/test-short-fields.html
- Compound Fields are not aligned to each other

http://localhost:4000/components/input/test-short-fields.html?locale=ar-EG
- spinbox borders are off
- Compound Fields are not aligned to each other

http://localhost:4000/components/input/test-short-fields.html?theme=uplift&locale=ar-EG
- a lot of icons are off: search, cal, timepicker, spinbox
- also spinbox borders are off

http://localhost:4000/components/processindicator/example-index?theme=uplift
http://localhost:4000/components/processindicator/example-index?theme=uplift&locale=ar-EG
- empty circles are _really_ hard to see

http://localhost:4000/components/spinbox/example-index?locale=ar-EG
- some weirdness going on with the parentheses in the text in RTL

http://localhost:4000/components/timeline/example-index?theme=uplift
- "PO Accepted" seems like one pixel too high
- there is a dotted line visible just above the topmost blue circle

http://localhost:4000/components/timeline/example-index?theme=uplift&locale=ar-EG
- circles are too far left by like one or two pixels

**Comment by tmcconechy** [comment]
http://localhost:4000/components/badges/example-index?theme=uplift&locale=ar-EG

- suggest we make the badges bigger for uplift since the font is bigger it looks cut off this looks good to me..(uplift style)
```
.tag.round, .badge.round {
  width: 30px;
}
```

http://localhost:4000/components/dropdown/example-icons.html
- something here is caused the colors example to no longer work see http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html

http://localhost:4000/components/input/test-short-fields.html?theme=uplift&locale=ar-EG
- icons and bottom components like spinbox out of alignment

http://localhost:4000/components/multiselect/example-index.html?theme=uplift&locale=ar-EG
- checkboxes are missing? when you select items

http://localhost:4000/components/processindicator/example-index?theme=uplift&locale=ar-EG
- "Long, Drawn-out, Incomplete Process" icon is a little off in all examples

**Comment by EdwardCoyle** [comment]
Something with the button size changes has affected the Editor's Toolbar on Uplift:  http://localhost:4000/components/editor/example-index?theme=uplift

**Comment by deep7102** [comment]
Might be duplicate find as above by @tmcconechy or @davidcarlsonberg 

Fonts looks too big (All browser)
http://localhost:4000/components/button/example-index?theme=uplift&locale=ar-EG

Partial `::after` should be 1px down (Chrome|Safari)
http://localhost:4000/components/checkboxes/example-index.html?theme=uplift
http://localhost:4000/components/checkboxes/example-index.html?theme=uplift&locale=ar-EG

Color swatches not show while open
https://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
http://localhost:4000/components/dropdown/example-icons.html?theme=uplift

Close `X` button is too much lmargin-right (Phone View)
http://localhost:4000/components/dropdown/example-icons.html?locale=ar-EG
http://localhost:4000/components/dropdown/example-icons.html?theme=uplift&locale=ar-EG

Icons too low (Phone View)
http://localhost:4000/components/dropdown/test-icon-short-fields.html
http://localhost:4000/components/dropdown/test-icon-short-fields.html?locale=ar-EG


Fonts looks too big
http://localhost:4000/components/dropdown/test-icon-short-fields.html?theme=uplift
http://localhost:4000/components/dropdown/test-icon-short-fields.html?theme=uplift&locale=ar-EG

Multiselect checkboxes not align while open
http://localhost:4000/components/input/test-short-fields.html

Button icon and text too low
Multiselectable Menu Button checkboxes not aligned while opened
Multiselect checkboxes not align while open
Spinbox border not align
Radio Buttons not align
Checkboxes `Option 3` track dirty icon off few pixels
Compound Fields not align
Dropdown and Multiselect trigger icon very low (Phone view)
Lookup trigger icon very up (Phone view)
Spinbox `md|lg` wrap to another line (Phone view)
Compound Fields not showing all the fields (Phone view)
http://localhost:4000/components/input/test-short-fields.html?locale=ar-EG


Multiselectable Menu Button checkboxes not aligned while opened
Multiselect checkboxes not align while open
Datepicker && Timepicker icon too low
Spinbox border not align
Radio Buttons not align
Checkboxes `Option 3` track dirty icon off few pixels
http://localhost:4000/components/input/test-short-fields.html?theme=uplift&locale=ar-EG

Multiselect checkboxes not align while open (Chrome|Safari)
http://localhost:4000/components/multiselect/example-index.html?locale=ar-EG
http://localhost:4000/components/multiselect/example-index.html?theme=uplift&locale=ar-EG

Process Indicator(Small Size) too much right side padding or margin
http://localhost:4000/components/processindicator/example-index?theme=uplift&locale=ar-EG

**Comment by EdwardCoyle** [comment]
Any new reviewers probably also want to check:

_Colorpicker:_
- http://localhost:4000/components/colorpicker/example-index.html
- http://localhost:4000/components/colorpicker/example-index.html&locale=ar-EG
- http://localhost:4000/components/colorpicker/example-index.html&theme=uplift
- http://localhost:4000/components/colorpicker/example-index.html&theme=uplift&locale=ar-EG

_Responsive Forms:_
- http://localhost:4000/components/form/example-inputs.html
- http://localhost:4000/components/form/example-inputs.html?theme=uplift
- http://localhost:4000/components/form/example-inputs.html?locale=ar-EG
- http://localhost:4000/components/form/example-inputs.html?theme=uplift&locale=ar-EG

**Comment by clepore** [comment]
Approved by group consensus.

**Pull request merged**
