### PR TITLE
3476 - Update EmptyMessage text

### LINKED ISSUE #3476: EmptyMessage: Text needs to be more subtle
**Is your feature request related to a problem? Please describe.**
In general, the empty state messaging beneath the icons is too heavy, being displayed in 2.2rem source sans semibold. What we're seeing is that empty states often call too much attention to themselves and pull the eye away from more meaningful or priority information

**Describe the solution you'd like**
Consider either lightening the text color, maybe .7 opacity and/or make the font weight regular with similar lightening or decrease in opacity

image

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Making the empty message text more subtle. Using `$font-color-muted`. Also updated empty icon size to 80x80 based on @kevinwhitedesign recommendations.

**Related github/jira issue (required)**:
closes #3476 

**Steps necessary to review your pull request (required)**:
* Pull Branch
* Go to http://localhost:4000/components/emptymessage/example-index.html?theme=uplift&variant=light
* See updated color and size adjustments. 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Should the title size go down too? @kevinwhitedesign ? Doesnt seem to be a match comparing the design with this branch:

Screen Shot 2020-04-08 at 12 52 37 PM

**Comment by jmacaluso711** [comment]
@tmcconechy Yes, missed the font size change in the title. Fixed now.

**Comment by tmcconechy** [comment]
@EdwardCoyle do you mean the widget card title? If so i think we should reduce that too. If so i agreed :) Just trying to clarify what you mean?

**Comment by EdwardCoyle** [comment]
@tmcconechy I mean the text that reads "Add a New Project". It doesn't appear to be using the same muted color that the standalone message uses.

**Comment by tmcconechy** [comment]
Right i see, its sublte maybea bit darker. Ok, i would say lets drop the title on the card too in size. And then check the centering of it. Then also what you mentioned on checking the widget example.

**Comment by jmacaluso711** [comment]
Hi @EdwardCoyle @tmcconechy -- just to confirm I'm using the muted the color for "Add a new Project" and also reducing the size of the widget card title. Here's my local. Looking at @kevinwhitedesign's figma file and he does have a smaller size for the widget card title (2rem vs 2.2rem)

Screen Shot 2020-04-09 at 12 41 28 PM

**Comment by tmcconechy** [comment]
That looks good to me.

**Comment by jamie-norman** [comment]
Hey guys, I think that's looking at lot better. I still wonder if the main text could be muted even more (without contrast issues). But this is moving in the right direction.

**Pull request merged**
