### PR TITLE
NG1614 - Tooltip Special Characters

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix wrong cell focus on blur in tree grid.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1614

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tooltip/test-tooltip-number-sign.html
- Hover to the button
- Tooltip should be shown `#10 - 24# WHITE`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
🍌

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
🍌
image

image

image

**Review by glenlieorillo — APPROVED** [review]
Mac Chrome
image

Mac Firefox
image

**Review by janahintal — APPROVED** [review]
image
image
image


image
image

**Pull request merged**
