### PR TITLE
6893 - Updated dirty cell check in datagrid

### LINKED ISSUE #6893: Datagrid: Changing a colorpicker from none to a color does not make the cell dirty
**Describe the bug**
On an editable datagrid that has dirty indicators, when changing a colorpicker with no color specified to a different color there is no dirty indicator added to the cell.

**To Reproduce**
1. Add datagrid setting showDirty: true and change the color of a colorpicker to an empty string on http://localhost:4000/components/datagrid/test-editable-colorpicker.html
2. Go to http://localhost:4000/components/datagrid/test-editable-colorpicker.html
3. Change the colorpicker from none to a color
4. See that there is no dirty indicator on the cell

**Expected behavior**
It is expected that when changing a colorpicker's color, the dirty indicator is added to the cell.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
none to color colorpicker no dirty indicator

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 106.0.5249.119 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated dirty cell check to include checking if value and original value are the same length (to catch empty value case).

**Related github/jira issue (required)**:

Closes #6893 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-editable-colorpicker.html
- Update second row colorpicker with any color
- Dirty cell indicator should appear

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Feel free to skip or update those tests...

**Review by deep7102 — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Can you check this PR - seems like maybe some tab changes got in it by mistake? You can also see all the snaps are failing. Not sure that this was intended?

But the fix looks perfect

**Review by EdwardCoyle — COMMENTED** [review]
@yohannahbautista Dirty indication on the cell looks good.  After the test situation is resolve I'm ready to approve

**Comment by ericangeles** [comment]
These failing visual tests are fixed in the disabled color PR @tmcconechy @EdwardCoyle. It will fix these issues once that merged.

**Comment by ericangeles** [comment]
@yohannahbautista can you update the remaining snapshot? All good to me!

**Comment by tmcconechy** [comment]
Same here .. except the test 👍🏻

**Review by deep7102 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@yohannahbautista are all these fixes in the PR related to https://github.com/infor-design/enterprise/issues/6893 ? Looking at the fixes there are changes to tabs so not sure if its as intended. Maybe need to merge with main?

**Comment by yohannahbautista** [comment]
> @yohannahbautista are all these fixes in the PR related to #6893 ? Looking at the fixes there are changes to tabs so not sure if its as intended. Maybe need to merge with main?

@tmcconechy @ericangeles 
Hello, several tab visual regression tests fail if I don't add the changes, when I check the tab pages it's because the font is white against the white background.

**Comment by tmcconechy** [comment]
Ok, Maybe we need to merge https://github.com/infor-design/enterprise/pull/7050 as well.. @yohannahbautista

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
