### PR TITLE
8516 - Removed escaping HTML for cell nodes

### LINKED ISSUE #8516: Datagrid: escapes special chars in the cellchange event
**Describe the bug**
In prior [issue](https://github.com/infor-design/enterprise/issues/8285) it was fixed so that when entering special chars into editable fields wasn't escaped, however, the event object for `cellchange` event still have it

**To Reproduce**

1. Go to [example-editable](https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light)
2. Open console
3. Enter `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]` into  e.g. an activity column
4. See logged event object which has an additional `\` for the `value` prop, `rowData.activity` prop, as well as oldValue prop still escapes special chars `related[BALMAS1(&quot;TX60:&bsol;{IndexList_Items.TX60}&quot;)]`

**Expected behavior**
All mentioned props should be exactly the same as the inputted string, `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]`.

**Version**
- ids-enterprise: 4.90.1 (here the values are still being escaped on the event object), but also latest.
- ids-enterprise-ng: 17.1.3 (we're currently on this one and need a patch with only the change from this version)

**Platform**
 - Infor Application/Team Name: M3

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed escaping HTML for cell nodes. Any special character and tag will be accepted as is.

**Related github/jira issue (required)**:

Closes #8516 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-editable.html
- Update a cell with `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]`
- Should accept it as is
- Check console logs
- Object printed should have the same values

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by jbrcna** [comment]
image

**Comment by tmcconechy** [comment]
@yohannahbautista i am seeing duplicate `//` in the data

Screenshot 2024-03-08 at 11 49 39 AM

Also change the value again and test the `oldValue` is correct:
Screenshot 2024-03-08 at 11 50 43 AM

Note: We also need to test these cases https://github.com/infor-design/enterprise/pull/8447#issue-2136777688 (I did and they are ok for me)

**Comment by yohannahbautista** [comment]
@ericangeles @tmcconechy 
Hello, I don't know why but when cellchange prints the args object, the string changes. But if you get that variable specifically, it's the correct value (getting args.value instead of args as a whole). I added changes in the console.log to show it: https://github.com/infor-design/enterprise/pull/8520/files#diff-768c7771f225e5bb07c7f8be99b7ff0a6c5c02bbe5e4dba7c0c202bf079a932aR179
image

I also checked by printing the value around here: https://github.com/infor-design/enterprise/blob/23860fbea3168ff417d23b960a466a289b108958/src/components/datagrid/datagrid.js#L11623
Printing coercedVal, args.value, and args for comparison. coercedVal and args.value are the same but seeing value when you print the whole args object changes it

**Review by glenlieorillo — COMMENTED** [review]
image

**Review by n-ace-ancog — APPROVED** [review]
Old value is now correct.

**Current Branch**
image

**Main**
image

**Review by tmcconechy — APPROVED** [review]
Approving on my side. I did see a test failed but looked unrelated

**Review by glenlieorillo — APPROVED** [review]
image

**Pull request merged**
