### PR TITLE
8677 - Fix datagrid pager and data in `updateDataset` and `loadData`

### LINKED ISSUE #8677: Datagrid: Loading data with the loadData/updateDataset API does not honor the passed in activePage number and does not render the right rows
**Describe the bug**
I found some problems with the DataGrid's loadData/updateDataset API involving paging, and I have a coding solution to fix them. That API call accepts a pagerInfo param with an "activePage" value. If no activePage is passed in, then page 1 is assumed (which is good). However, after going to page 2, then calling the loadData API, the pager will show the requested page number properly, but the grid will render the wrong page of rows.

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/test-large-dataset-performance.html
2. Click on Load Data to get data in the grid
3. Click Next Page to get to page 2
4. Notice the grid renders the page 2 rows properly
5. Now click on Load Data again
6. Notice the pager shows "Page 1" (which is good), but the rendered rows are from page 2
(A similar problem happens when passing in an "activePage" value)

**Expected behavior**
When using the loadData/updateDataset API, the grid should render the correct page of rows. If no activePage is passed in, then the grid should render page 1's rows. If an activePage is passed in, then the grid should render that page's rows.

**Version**
- ids-enterprise: v4.94.2

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: CSD
 - Device: Dell laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 124.0.6367.119 (Official Build) (64-bit)

**Coding Solution**
In datagrid.js find the loadData function and change **line 1169** to be this (it fixes both issues):

if (this.pagerAPI) {
  this.pagerAPI.activePage = pagerInfo.activePage || 1;

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the pager and data in the `loadData` and `updateDataset` APIs to render the proper dataset.

**Related github/jira issue (required)**:

Closes #8677

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-large-dataset-performance.html
- Click the load data button
- Go to page 2
- Click the load data again
- It should render the correct data (from page 1) and not the page 2 data

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@aaronpikkarainen this look correct to you? Can see it on https://8677-datagrid-update-dataset-api-enterprise.demo.design.infor.com/components/datagrid/test-large-dataset-performance.html if needed

**Review by tmcconechy — APPROVED** [review]

**Comment by aaronpikkarainen** [comment]
@tmcconechy Yes, the code is correct, and the test case is working. Thank you!

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.

https://github.com/infor-design/enterprise/assets/156752175/d2d829dc-2a15-4752-8fbe-4c0301762556

**Review by janahintal — DISMISSED** [review]
Working as expected in https://8677-datagrid-update-dataset-api-enterprise.demo.design.infor.com/components/datagrid/test-large-dataset-performance.html
image

**Comment by tmcconechy** [comment]
@ericangeles maybe check the test that failed? I will be adding playwright really soon so if its not breaking something feel free to skip.

**Review by n-ace-ancog — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
