### PR TITLE
7153 7211 7212 7217 7218 7219 - Tabs/Header personalized colors

### LINKED ISSUE #7153: Personalization: When using .is-personalizable class on a form links are styled in white causing them to appear not to display when the color is set to white
**Describe the bug**
when using .is-personalizable class on a form links are styled in white causing them to appear not to display when the color is set to white

**To Reproduce**
Notice on the form here that the hyperlink test is white. This works fine for colors other than white
image

Notice on the white color the hyperlink seems to disappear, it's there but it's foreground color is still white making it seem like it's disappeared.
image

1. Got to a composisteForm and make the context form (summary) have the is-personalizable 
2. add a link to the composite form "summary"
3. Notice in white color the hyper link is white

**Expected behavior**
The hyperlink should return to the standard blue hyper link color in the white color.

**Version**
- ids-enterprise: 4.71.0-beta.2

### LINKED ISSUE #7211: is-personalizable contrast and dark mode - fade out color is wrong and the disabled tabs colors aren't very good
**Describe the bug**
is-personalizable contrast and dark mode - fade out color is wrong and the disabled tabs colors aren't correct

1. Put attached example into place
2. Click on open example and see tab issue

**Expected behavior**
colors for disabled tabs and tab overflow fadeout colors should have correct styling

**Version**
- ids-enterprise: 4.80.2

**Example**

**Screenshots**
image

### LINKED ISSUE #7212: Hyperlink: Color on personalize-actionable is incorrect for white color in new-contrast theme and new-light theme
**Describe the bug**
Hyperlinks seems fine for all colors except white when in new theme/contrast mode and light mode

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=contrast
3. notice hyperlinkg color is too dark

**Expected behavior**
Hyperlinks color should use contrast-mode hyper link color
Notice it's using some dark color in a rule from personalize.scss

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10726335/example-form-landmark2.html.txt)

**Screenshots**
new-contrast
image

new-light
image

### LINKED ISSUE #7217: Tabs: Color changes allowing screen to be displayed behind sticky tabs
**Describe the bug**
personlized tabset in new-dark theme default color - background color is transparent allowing screen to be displayed behind sticky tabs.

This happens only when the tabset has .is-personalizable.header-tabs classes set.

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. scroll the browser so that the tab content scrolls under the sticky tabs
4. notice tab content is displaying behind the sticky tabs

**Expected behavior**
Tab content should not display behind sticky tabs.

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10734308/example-form-landmark2.html.txt)

**Screenshots**
image

### LINKED ISSUE #7218: Personlized: Form in new-dark theme default color - foreground color is too dark
**Describe the bug**
personlized form in new-dark theme default color - foreground color is too dark

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. Notice the dark foreground color

**Expected behavior**
foreground color when personalized should look like the form when it's not personlized.

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10734597/example-form-landmark2.html.txt)

**Screenshots**
From example
image

### LINKED ISSUE #7219: is-personalize disabled tabs do not look disabled in dark mode default color
**Describe the bug**
personalized form in new-dark theme default color - disabled tabs do not look disabled 

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. Notice 2nd and 4th tabs should be disabled 

**Expected behavior**
disabled tabs should look disabled

**Version**
- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10735153/example-form-landmark2.html.txt)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes colors for a variation of header/tabs where header tabs are not in the header element and `tabs-container` has `is-personalized` . Changed header tabs disabled color to darker color.

**Related github/jira issue (required)**:
Closes #7219
Closes #7218
Closes #7217
Closes #7212
Closes #7211
Closes #7153

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/personalize/example-form-landmark2.html

#7153
- check summary `Purchase Order Date` item's link, see the link has default blue color
- change the color (not default), see the link is personalized, change the color to default -> change theme to contrast, see the link has default blue color

#7211
- change the color (not default)
- see the tabs fade out right/left gradient is correct
- see the disabled items are a bit faded

#7212
- change the color to default
- check summary `Delivery Order` item's link, see the link has default blue color
- change the color (not default), see the link is personalized, change the color to default -> change theme to contrast, see the link has default blue color

#7217
- change the color to default, change the theme to dark, shrink the browser so the vertical scroll appears
- scroll the page and see the tabs container is not transparent

#7218
- change the color to default and the theme to dark
- check the summary's text, see the text is not dark

#7219
- change the color to default and the theme to dark
- see the tabs disabled items are faded and visible (Options and User Fields items)

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks REALLY good. The only issue i see is in light contrast mode...

http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=light&colors=2578a9
or
http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=light

So need a correction there. To Be clear the easiest test set is:

- classic/new
- dark/light/contrast
- a color or default

**Comment by andriivarhanov** [comment]
added adjustments for classic version themes

**Review by deep7102 — DISMISSED** [review]
LGTM 🍌

**Comment by andriivarhanov** [comment]
@ericangeles @tmcconechy this one https://github.com/infor-design/enterprise/issues/7171 can be related to the changes in the PR

**Comment by ericangeles** [comment]
> @ericangeles @tmcconechy this one #7171 can be related to the changes in the PR

@andriivarhanov okay. I'll assign that ticket to you. Thanks for the heads up! :)

**Comment by pwpatton** [comment]
#7218 this is working for new theme but not for classic light and contrast, but seems to work for classic dark

http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=light&color=default
http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=contrast&color=default

image

image

But seems to be fine in classic/dark/default...
http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=dark&color=default

**Comment by pwpatton** [comment]
#7153, #7217, and #7212 seem good!

**Comment by tmcconechy** [comment]
@pwpatton just FYI color=default doesn't do anything its the same is leaving it off but i see all the issues you mentioned as well. Thanks!

**Comment by andriivarhanov** [comment]
@tmcconechy do you see the issue with personalized text color https://github.com/infor-design/enterprise/pull/7223#issuecomment-1433396120  as well?

**Comment by tmcconechy** [comment]
no @andriivarhanov i only saw that the disabled color was not that dark and the disabled buttons are pushed down. I didnt see the dark text color in that comment. Try updating the branch maybe @pwpatton  (`git pull`)

**Comment by andriivarhanov** [comment]
@pwpatton thanks for the feedback, I've addressed the disabled tab alignment issue and color, please pull the recent commits and build the app

**Comment by andriivarhanov** [comment]
Also added disabled tabs to these examples
http://localhost:4000/components/tabs-header/example-index.html
http://localhost:4000/components/tabs/example-desktop-breakpoint.html

**Comment by tmcconechy** [comment]
- Only a minor suggestions now but i think http://localhost:4000/components/tabs/example-desktop-breakpoint.html?theme=classic&mode=light&colors=2578a9 the disabled items should be a color lighter (same in dark classic/ contrast classic)
- Also in light mode http://localhost:4000/components/tabs/example-desktop-breakpoint.html?theme=new&mode=contrast&colors=2578a9 they dont appear very disabled. Would also drop a color (same for light dark and contrast)
- same here http://localhost:4000/components/personalize/example-form-landmark2.html?theme=classic&mode=dark the disabled items dont seem very disabled
- same here http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&colors=0066D4

I think this is all one issue. Just need to look more disabled.

**Comment by pwpatton** [comment]
I'd say all the disabled tabs color not looking "disabled enough" is a issue for classes and light for each example in @tmcconechy  comment above

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
