### PR TITLE
6707 - Searchfield enhancements

### LINKED ISSUE #6707: SearchField: Sync New Designs with the code
**Describe the bug**
See designs https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/IDS-Search?node-id=10%3A449
Make sure our examples represent this in the various areas.

**Additional context**

- [ ] Do this in both code bases
- [ ] Leave the app menu changes out of Enterprise

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Searchfield enhancements to sync with new designs

Note: Will update baseline images once the changes are okay

**Related github/jira issue (required)**:

Closes #6707 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to the following pages:

Card/Listview
http://localhost:4000/components/listview/example-search.html

Toolbar
http://localhost:4000/components/toolbar-flex/example-index.html

Input Searchfield
http://localhost:4000/components/input/example-index.html
http://localhost:4000/components/lookup/example-index.html

Toolbar Searchfield:
http://localhost:4000/components/contextualactionpanel/test-searchfield.html
http://localhost:4000/components/toolbarsearchfield/example-inside-contextual-panel.html

Header search field:
http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html

http://localhost:4000/components/header/example-searchfield-full.html

http://localhost:4000/components/header/example-searchfield-large

http://localhost:4000/components/header/example-toolbar-flex-with-categories.html

Application menu search field
http://localhost:4000/components/applicationmenu/example-filterable.html

Pages should follow the specifications in Figma: https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/IDS-Search?node-id=10%3A449

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Was thinking to wait the major changes in the icon design here https://github.com/infor-design/enterprise/pull/6882

**Comment by tmcconechy** [comment]
Yeah the icon "size" change may effect this a bit

**Review by ericangeles — CHANGES_REQUESTED** [review]
Here are the issues that I've found when testing it,

Go to 
- http://localhost:4000/components/listview/example-search.html
- Type anything in the searchfield
- It should not have blue shadow. Check the figma file. I think the border should be slate.
blue-shadow

Go to 
- http://localhost:4000/components/toolbar-flex/example-index.html?theme=new&mode=dark&colors=0066D4
- Type anything in the searchfield
- Hover on it
- Icons are not visible
icons-not-visible


Go to
- http://localhost:4000/components/toolbar-flex/example-index.html
- Type long text
- Close icon is overlapping

text-overlap

Go to
- http://localhost:4000/components/input/example-index.html
- Go to `Email Address - Checker` and put correct email address
- Success icon is kinda small. Adjust the height to `18px`

Go to
- http://localhost:4000/components/contextualactionpanel/test-searchfield.html
- Open the CAP
- Type anything in the searchfield
- It's missing a right border
Screen Shot 2022-11-28 at 6 56 56 PM

Go to
- http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html
- Type long text in searchfield
- Close icon is overlapping

Go to
- http://localhost:4000/components/header/example-searchfield-full.html?theme=new&mode=dark&colors=0066D4
- Type in searchfield
- Text is not visible
text-is-not-visible

Go to
- http://localhost:4000/components/applicationmenu/example-filterable.html
- Skip this part and revert it back
- It's not yet finalize
- Also, I noticed the gap between the search icon and the text
revert

**Review by tmcconechy — CHANGES_REQUESTED** [review]
A couple things i saw (all tested in firefox)

- on http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html if i open the search and then type and then click out. It does not slide back. Also the icons seem different sizes between the X and search
- on http://localhost:4000/components/applicationmenu/example-filterable.html the color is changed should be dark mode like https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html still

Minor:
- on http://localhost:4000/components/listview/example-search.html when you focus the field there is a small box shadow under that could be removed
- on http://localhost:4000/components/contextualactionpanel/test-searchfield.html the first time you open it slides shut wonder if this can be changed but not too important

**Comment by tmcconechy** [comment]
This all set to review (comments fixed?) @yohannahbautista ?

**Comment by yohannahbautista** [comment]
> This all set to review (comments fixed?) @yohannahbautista ?

@tmcconechy Hi, it should be okay now.

**Comment by ericangeles** [comment]
Looks good to me now! The only issue I noticed is the color of the text on searchfield. Make it more visible for all modes.

- Go to http://localhost:4000/components/applicationmenu/example-filterable.html
- Type something in the search field
- Text isn't visible enough (test in all modes)

**Comment by ericangeles** [comment]
Also, add log for 4.71 (including this ticket)

**Comment by tmcconechy** [comment]
Everything looks good to me here except for maybe one test needs updating. I reran it to check

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
