### PR TITLE
8610 - New Button Styles / Fix to personalize colors on subheader

### LINKED ISSUE #8557: UiChanges: Sync minor changes after the tokens are mapped
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### LINKED ISSUE #8610: Personalize: Header toolbar button text color is wrong on hover
**Describe the bug**
When using a Personalize Color (like Azure, not default/alabaster), the button text color is wrong on **hover** for buttons that are in header toolbars (the classic toolbar, not the flex toolbar).

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/header/example-subheader.html?colors=0066D4
2. Ensure the selected Color is Azure
3. Hover the "Filter" or "Filter 2" button
4. Notice that the icon color stays a nice white, but the text color becomes very dark and hard to see

**Expected behavior**
The text color should stay white (matching the icon color, and matching other examples of buttons in headers)

**Version**
- ids-enterprise: v4.93.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: CSD (Distribution)
 - Device: any (dell laptop)
 - OS Version: Windows 11 enterprise
 - Browser Name: Chrome
 - Browser Version: 123.0.6312.106 (Official Build) (64-bit)

**Solution**
The problem is in the below CSS rule in the file: **src/components/personalize/personalize.styles.js** around line **508**. This rule seems to override and clash with other rules that already handle hover color. It should either be removed or corrected. Thank you!

`
html[class*="theme-new-"] .header.is-personalizable button:not(:disabled):hover .app-header.icon > span,
html[class*="theme-new-"] .header.is-personalizable .toolbar [class^='btn']:hover:not(.go-button):not(.close):not(.searchfield-category-button):not([disabled]),
html[class*="theme-new-"] .subheader.is-personalizable button:not(.go-button):not(.close):not(.searchfield-category-button):not(:disabled):hover,
html[class*="theme-new-"] .subheader.is-personalizable button:not(:disabled):hover .app-header.icon > span,
html[class*="theme-new-"] .subheader.is-personalizable .toolbar [class^='btn']:hover:not(.go-button):not(.close):not(.searchfield-category-button):not([disabled]),
html[class*="theme-new-"] .personalize-subheader button:not(.go-button):not(.close):not(.searchfield-category-button):not(:disabled):hover,
html[class*="theme-new-"] .personalize-subheader button:not(:disabled):hover .app-header.icon > span,
html[class*="theme-new-"] .personalize-subheader .toolbar [class^='btn']:hover:not(.go-button):not(.close):not(.searchfield-category-button):not([disabled]) {
  color: ${colors.btnTertiaryHoverColor} !important;
  background-color: ${colors.btnTertiaryBgHoverColor} !important;
  opacity: 1;
}
`

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

1. Added new button styles. This includes less padding, different colors and states and no ripple state
1. Fixed the hover color and border on the subheader example.

**Related github/jira issue (required)**:
Fixes #8610 
Fixes #8557  

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/header/example-subheader.html?colors=0066D4
- hover the buttons and make sure both the text and icon are white
- test http://localhost:4000/components/header/example-subheader.html and a few other colors
- http://localhost:4000/components/images/example-avatar -> changed status color
- http://localhost:4000/components/button/example-index.html -> changed padding, disabled colors and focus state, removed ripple. This should match https://main.wc.design.infor.com/ids-button/example.html
- http://localhost:4000/components/header/example-subheader.html -> test themes and colors
- http://localhost:4000/components/homepage/example-hero-widget.html?colors=7928E1 -> check button hover states and state when menu is open (view last 6 months)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Found some issues testing other colors:
1. The hover state of the default option differs from the other colors.  Text and icon turns blue.
Animation
2. The horizontal dividers between sub header vanishes when switching to Alabaster (may not be related to the initial issue and is a baseline bug)
Animation
3. In Dark Mode, when default is selected the 2nd sub header doesn't have any focus color or is not being triggered
Animation

**Comment by tmcconechy** [comment]
Decided we need to add the button changes in order to do this right so expanding the PR to a second issue im working on today.

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

alabaster classic, the sub header doesn't have highlight effect
image

classic default. text is off
image

**Comment by tmcconechy** [comment]
@jbrcna @ericangeles @n-ace-ancog 

Please test again. I figured it was a good idea to add all the button changes. See notes for testing. Anything we find i will address as there is a lot of combinations. I think I got all of what i could find so far

**Review by ericangeles — DISMISSED** [review]

**Comment by ericangeles** [comment]
@jbrcna @n-ace-ancog, if you find any issues, feel free to create a ticket as we're almost at the end of the sprint.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Inconsistent color of icon and text in Classic - Default.

image


https://github.com/infor-design/enterprise/assets/102151352/4fef531c-4710-4101-b669-245c77308ed7


- Hover color is off when changing the color.

https://github.com/infor-design/enterprise/assets/102151352/0ee57f5e-52ea-40c8-aa9b-b13f4c17fa87

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
**Re testing of previous issues found:** https://github.com/infor-design/enterprise/pull/8652#pullrequestreview-2023905179

1. Hover in default - **OK**
Animation

2. Alabaster behavior - **OK**
Animation

3. Dark mode - **OK**
Animation

**Classic mode issues found**
1. The settings icon is highlighting when hovered
Animation
2. Hover color is too bright (not sure if this is personal opinion)
image
image
3. Dark mode default color and alabaster have different behaviors:
    - When clicking the button in default text changes color
    - Line separator vanishes when changing to alabaster
 
Animation

**Comment by tmcconechy** [comment]
@ericangeles i'll take a quick pass at some of these PR comments. Since of the holidays i think we can do the beta tomorrow or monday.

**Comment by ericangeles** [comment]
@tmcconechy, agree. For @infor-design/qa, please log new issues as I've mentioned. Let's do the beta release on Monday.

**Comment by tmcconechy** [comment]
@ericangeles give me a chance to do one look through then we can raise new issues. Will do so this morning. Just to make sure any changes didnt break anything.

**Comment by tmcconechy** [comment]
ok added a few more fixes. Calling this good for now. And keeping in mind classic isnt very important

**Pull request merged**
