### PR TITLE
2433 - Add Fullsize view support for Modals and Contextual Action Panels

### LINKED ISSUE #2433: Contextual Action Panel and Modal: Take up full width+height on mobile breakpoint
**Is your feature request related to a problem? Please describe.**
On mobile breakpoints, the contextual action panel has a constrained size, which cramps the content and introduces issues with zoom and scroll.

**Describe the solution you'd like**
- [x] At a mobile breakpoint, the contextual action panel should take the full height and width of the viewport so it behaves like a "sheet".
- [x] Overall, modals should contain less padding around the edges.
- [x] Contextual Action Panels should be setup to allow horizontal scrolling, if applicable. 

This also requires converting some components to using the contextual action panel instead of the simple modal. (See #2432)

**Describe alternatives you've considered**

**Additional context**

image

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds a feature to the Modal and Contextual Action Panel components, allowing those components to take up the full size available on a screen with their contents.  The feature is "opt-in" and puts this functionality behind a setting called `fullsize`, which can either be false (default), "always", or "responsive" to only become full screen below the "phone-to-tablet" breakpoint.

Some additional work in this PR made the following changes:
- The `setTimeout()` code that wrapped some animation-related functions, and some event triggers, has been replaced with callbacks registered to the RenderLoop.
- Some settings in the Contextual Action Panel that were previously top-level settings have been deprecated in favor of a new `modalSettings` object, which contains all those same settings.  The Contexual Action Panel has been modified to pass that object directly as the underlying Modal's settings.  Deprecation warnings and backwards compatibility for the old settings have been added at the Contextual Action Panel level, and documentation has been updated accordingly.

**Related github/jira issue (required)**:
Closes #2433 

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the app.

_To test the Modal portion of these changes:_
- Open http://localhost:4000/components/modal/example-fullsize-always.html
- Click the button to open the modal.  The modal should open and take up the full screen width and height.  The buttons at the bottom should be completely present and not be cut off.
- Open http://localhost:4000/components/modal/example-fullsize-responsive.html.  Make sure the screen size is above the "phone to tablet" breakpoint (larger than 767px wide)
- Click the button to open the modal.  The modal should appear normally (not full size)
- Resize the viewport to be less than 767px wide.  The modal should shift and take up the full screen width and height.

_To test the CAP:_
- Open http://localhost:4000/components/contextualactionpanel/test-fullsize-always.html
- Click the button to open the CAP.  The CAP should open and take up the full screen width and height.
- Open http://localhost:4000/components/contextualactionpanel/test-fullsize-responsive.html.  Make sure the screen size is above the "phone to tablet" breakpoint (larger than 767px wide)
- Click the button to open the CAP.  The CAP should appear normally (not full size)
- Resize the viewport to be less than 767px wide.  The CAP should shift and take up the full screen width and height.

_To test horizontal scrolling inside of a modal pane:_
- Open http://localhost:4000/components/contextualactionpanel/test-horizontal-scrolling.html
- Click the button to open the CAP.
- Try to scroll the area inside the CAP horizontally.  It should work with no issues.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
I think the e2e tests are going to continue failing here until we get the changes to `.travis.yml` from `v4.21.x` that were [pushed here](https://github.com/infor-design/enterprise/pull/2774/files#diff-354f30a63fb0907d4ad57269548329e3).

**Comment by EdwardCoyle** [comment]
> But do we have a way to do "mobile size" only i.e. not tablet for full page modals/CAPS?

Not sure I understand?  I thought the use case being requested was just to make the boundaries of the CAP/Modal fit the screen once you get below a certain threshold?

**Comment by tmcconechy** [comment]
I just mean the threshold is phone not table. So maybe a setting that goes full screen if phone + phablet and normal size of content anything bigger? It seemed like the example was doing it at tablet level. Was wondering if we should have a setting for that?

**Comment by EdwardCoyle** [comment]
I guess we could allow the breakpoint threshold to change (just plug into the existing breakpoints system for the setting)

**Comment by tmcconechy** [comment]
Ok, up to you if that's easy enough or that's for later. 

Was thinking like a http://localhost:4000/components/contextualactionpanel/test-mobilesize-responsive.html

If that's easy it might be worth it to just do it from the get go. My thinking was (and its maybe just the content) that the modal/cap is overly big for a tablet and doesnt need to fill the page.

**Pull request merged**
