### PR TITLE
7001 - Fix field filter alignment issues

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug in field filter where the design is not properly aligned.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7001

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-index.html
- Check the alignment of the input boxes.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
It looks like this change made some effect here: (use firefox)
http://localhost:4000/components/field-filter/example-short.html
-vs-
https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html

image

**Review by ericangeles — CHANGES_REQUESTED** [review]
I also noticed in http://localhost:4000/components/field-filter/example-index.html?theme=new&mode=light&colors=0066D4, when you click the dropdown field-filter, the caret icon moves.

It's very noticeable especially in Safari.

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — DISMISSED** [review]

**Comment by tjamesallen15** [comment]
> @tjamesallen15 see comment by @ericangeles -> i think that is all that remains

I do check it but can't be replicated on my end. I will talk to him tomorrow on office regarding this one

**Comment by tmcconechy** [comment]
yeah the only thing i see is this it looks a bit darker border. But im sure @ericangeles can explain.

image

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
This is very minor but i see a double border on focus of the arrow button:

Screenshot 2023-02-24 at 10 07 49 AM

**Review by tmcconechy — DISMISSED** [review]

**Review by deep7102 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles are all your issues resolved here?

**Comment by ericangeles** [comment]
The Caret icon doesn't seem to move now, but when hovering over the drop-down input field, the right border gets removed.  (All browsers)

Screen Shot 2023-03-01 at 11 02 36 PM

And when you select any in the input field, when opening the dropdown, it moves. (Safari and Firefox)

**Review by tmcconechy — APPROVED** [review]
Looks good enough for me. This component is minimally used

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
