### PR TITLE
4265 - Add support to select all on active page only for client side with datagrid

### LINKED ISSUE #4265: Datagrid: Client Side Paging doesn't have an option to configure select all (all pages vs the current page)
**Is your feature request related to a problem or use case? Please describe.**
We want the user to only select the page where they are at when clicking on Select All. This is a client side grid.

**Describe the solution you'd like**
We would like to see in the grid options an attribute that we can indicate if the select all should select all rows or just the page.

**Describe alternatives you've considered**
We don't have an alternative at the moment other than disable the select all feature

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added support to select all rows on active page only for client side paging with Datagrid.

**Related github/jira issue (required)**:
Closes #4265

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4000/components/datagrid/test-paging-select-clientside-multiple-current-page.html
- Click on top `Select All` checkbox (first cell in header first column), to select/unselect all
- Go to any other page, see the selection should not effect to any other page

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@AnaLauraMartinez Can you test this branch out? One main question i have is if it should "reset" the selections when you change page. So far its not doing that. I think it probably should?

Also @deep7102 i think the name is a bit awkward 'selectAllOnlyActivePage` what about `selectAllCurrentPage` not sure but open to other suggestions @EdwardCoyle is good at that?

**Comment by AnaLauraMartinez** [comment]
> @AnaLauraMartinez Can you test this branch out? One main question I have is if it should "reset" the selections when you change page. So far its not doing that. I think it probably should?

Could we please have a way to tell the widget that we want to keep the selected rows and add to them the selected in the next page?

**Comment by tmcconechy** [comment]
Do you mean?

1. Select all on page one
2. Go to page 2
2. Select all on page two

Now all are selected on noth page one and two?

**Comment by AnaLauraMartinez** [comment]
> Do you mean?
> 
> 1. Select all on page one
> 2. Go to page 2
> 3. Select all on page two
> 
> Now all are selected on the page one and two?

yes, that will work.

**Comment by tmcconechy** [comment]
Ok then this is doing the right thing. Just need to decide on setting name @EdwardCoyle ? what you think?

**Comment by EdwardCoyle** [comment]
`selectAllCurrentPage` seems to make more sense to me

**Comment by deep7102** [comment]
Hi @tmcconechy @EdwardCoyle updated now to use `selectAllCurrentPage`

**Review by EdwardCoyle — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
🍌

**Pull request merged**
