### PR TITLE
8022 -  Fix datagrid's error and trigger icons in RTL mode

### LINKED ISSUE #8022: Datagrid: Error Icon is disappearing/not present in the cell in RTL
**Describe the bug**
Error Icon is disappearing/not present in the cell in RTL.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
2. Click More button
3. Select 'Extra Small/Small/Medium' from the dropdown
5. Click on cell with blank data under Order Date column, leave the cell blank
6. Click the page
7. Notice the Error Icon

    **Extra Small and Small** - _upon hovering the cell, the Error Icon disappears moving to the right_
    **Medium** - _No Error Icon shown when you leave the cell blank_

**Expected behavior**
Error Icon should stay as is beside the calendar icon upon hovering.

**Version**

- ids-enterprise: 4.88.0-beta.0

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/0521c282-4453-43c9-8ba3-cf3a074a0628

**Platform**
 - All major browsers

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the error icon and trigger icon alignment in the datagrid across various row heights in RTL mode.

**Related github/jira issue (required)**:

Closes #8022 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Click on cell with blank data under Order Date column, leave the cell blank
- Click outside of the datagrid to show the error icon
- Test this to all row heights
- Error icon should positioned correctly

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — DISMISSED** [review]
image
image
image
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Dropdown icon is not properly placed.

Steps to reproduce:
1. Change the row height to extra small
2. Hover the first cell/cell with dropdown
3. Notice the dropdown icon

image

**Comment by ericangeles** [comment]
@glenlieorillo, could you please create a separate ticket for this? I noticed a couple of dropdown alignment issues, including in editing mode. Fixing this may be tedious as we are in the last week of the sprint.

**Comment by glenlieorillo** [comment]
> @glenlieorillo, could you please create a separate ticket for this? I noticed a couple of dropdown alignment issues, including in editing mode. Fixing this may be tedious as we are in the last week of the sprint.

I will create another ticket for this issue. Thanks, @ericangeles!

**Review by glenlieorillo — APPROVED** [review]

**Pull request merged**
