### PR TITLE
5303 styling issue with tab overflow mobile

### PR DESCRIPTION
**Pull request by Jah25**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

added style to the personalizer that sets the tab-container background image to none when the tab container is horizontal and has overflow tabs

**Related github/jira issue (required)**:

Closes ([#5303](https://github.com/infor-design/enterprise/issues/5303))

**Steps necessary to review your pull request (required)**:

-Build and run the application.
- navigate to this example: https://main-enterprise.demo.design.infor.com/components/personalize/example-form3-short.html
- Open devtools in chrome and display in responsive mode, choose a tablet or smaller screen size
- there should be no gradient on the overflow tab see image comparison below

Screen Shot 2021-07-22 at 10 12 51 AM

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@Jah25 rather than remove the effect i think we want to change color of the radial gradient as you can see it is working on the left side

Screen Shot 2021-07-21 at 10 04 59 AM

```
.tab-container.header-tabs::before {
  background-image: linear-gradient(to right, #0072ed, rgba(0, 114, 237, 0));
  left: 20px;
}
```

So maybe we can dynamically update that rule for the other side based on the current color.

**Comment by Jah25** [comment]
@tmcconechy sure I can make that change.

**Comment by tmcconechy** [comment]
See comment again added some more context for that was looking for the hextToRgba... But that might work what i just added / should be close

**Comment by Jah25** [comment]
@tmcconechy So the rgba($body-color-primary-background) looks like it works when it's in the personalize component, as opposed to in the tabs-horizontal, I'm not exactly sure where it's inheriting the different body color value so I wanted to run it by you.

**Review by tmcconechy — APPROVED** [review]
Looks good to me now. Go ahead and update the images

**Review by deep7102 — APPROVED** [review]
🍌

**Pull request merged**
