### PR TITLE
7926 - Adjusted positioning of text inside Weekview footer cell.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Centered the positioning of text inside the Week view footer-cell.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7926

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to: http://localhost:4000/components/week-view/example-stacked.html?theme=classic&mode=dark&colors=default
- Make sure classic theme is selected.
- Text within footer cell should be centered.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Nice fix 👍🏻

**Review by clayinfor — DISMISSED** [review]

**Review by glenlieorillo — DISMISSED** [review]
image

image

image

**Review by jbrcna — DISMISSED** [review]
great work. approving. thanks
image
image

**Comment by jbrcna** [comment]
in firefox, the calendar icon was misaligned. However, when you click today button the calendar icon automatically aligned itself
image

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving
image
image

**Pull request merged**
