### PR TITLE
7624 - Add new color palette (and tweaks)

### LINKED ISSUE #7624: Color: Updates to the Color Palette
**Describe the bug**
Adjust down the color pallet down. New designs.

**Additional context**
https://www.figma.com/file/Ff40dFpHSipTN0fxeySKjW/New-Slate-palette---handoff-file?type=design&node-id=0-1&t=MH4teboMUOJo04IX-11

https://jira.infor.com/browse/IDS-1315

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Adds adjusted down color pallette
- Based on test output fixed resulting contrast issues
- updated all down stream deps

After tests runs and developer quick tests will design QA

**Related github/jira issue (required)**:
Fixes #7624 

**Steps necessary to review your pull request (required)**:
- pull branch
- do `npm i` (IMPORTANT)
- test http://localhost:4000/ in all 6 theme/modes (but only new theme is important so will only fix major issues in classic)
- should have minor changes but should pass an accessibility scan in light and contrast mode
- try http://localhost:4000/components/module-nav/example-index.html?theme=new&mode=dark for anything very odd (will do future tweaks) http://localhost:4000/components/module-nav/example-index.html?theme=new&mode=contrast (should look ok temporarily)
- http://localhost:4000/components/colors/example-index.html should have an updated slate column values (compared to https://main-enterprise.demo.design.infor.com/components/colors/example-index.html)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@talkaboutdesign ~ do you guys want to review on this one?

**Comment by talkaboutdesign** [comment]
@tmcconechy how do we verify the hex values?

**Comment by talkaboutdesign** [comment]
Checked to make sure colors match what was defined in Figma. I imagine over time we might run into some bugs here and there because of this. But they would be pretty minor and cosmetic in nature.

**Comment by tmcconechy** [comment]
Holding for a bit due to possible tweaks https://jira.infor.com/browse/IDS-1377
Will need to reverse [on](https://github.com/infor-design/enterprise-wc/pull/1347/commits/ebfb9c76554d5f694aa11f9a997e4965a9df6776) once settled.

**Pull request closed without merging**
