### PR TITLE
2722 - Add Fontpicker Component to Editor

### LINKED ISSUE #2722: Editor: Configuring  heading buttons is not working
**Describe the bug**
Rich Text Editor seems to ignore editor buttons settings, or the feature is not documented. Editor always shows H3 and H4 while H1 and H2 are missing. Editor also seems ti ignore any settings other that _header1_ and _header2_ which are then displayed as 'H3' and H4'

**To Reproduce**
1. Run ids-enteprise-ng project and use this code
```
    // Customize the buttons on init
    this.editor.buttons = {
      editor: [
        'header1', 'header2', 'header3', 'header4', 'header5', 'header6',
        'separator', 'bold', 'underline', 'strikethrough',
        'separator', 'foreColor',
        'separator', 'justifyLeft', 'justifyCenter', 'justifyRight',
        'separator', 'quote', 'orderedlist', 'unorderedlist',
        'separator', 'anchor',
        'separator', 'clearFormatting',
        'separator', 'source'
      ],
      source: [
        'visual'
      ]
    };
```
2. Click on Rich Text Editor
3. See buttons H3 and H4 showing

**Expected behavior**
Editor should respect settings and create heading buttons accordingly, as per attached code H1, H2, H3, H4, H5, H6

**Version**
- ids-enterprise-ng: 5.5.2

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds a new Fontpicker component to IDS.  The Fontpicker has been integrated into the Editor component, and takes the place of the `h3` and `h4` buttons that previously existed.

**Related github/jira issue (required)**:
Closes #2722 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, run the app
- Navigate to http://localhost:4000/components/editor/example-index?theme=uplift
- inspect the fontpicker and ensure it works correctly when placing a standard caret in different editor blocks.  Also check that it works with text selected (note that this only does top-level block formatting, similar to the buttons' functionality).
- Navigate http://localhost:4000/components/editor/example-complex-fontpicker?theme=uplift
- double check that all header types and blockquotes work correctly.
- Do a general smoke test of all Editor configurations:  http://localhost:4000/components/editor/list
- Check the standalone Fontpicker example at http://localhost:4000/components/fontpicker/example-index.html, and make sure a toast appears when a new Font Style is chosen.

There are also a handful of new functional tests for this component that should all pass.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@Fruko if you're able, would you mind testing this in your environment to see if it meets your requirements?

**Comment by Fruko** [comment]
@EdwardCoyle  sure, the branch or after it's merged to master?

**Comment by tmcconechy** [comment]
@Fruko Either way. But if you do try the branch and find some suggestions we can get them in sooner before merged. But either will help.

**Comment by tmcconechy** [comment]
Screen Shot 2019-12-11 at 12 01 37 PM

- should we move the arrow closer? or is that the design?

Screen Shot 2019-12-11 at 12 02 41 PM
- should this one have an arrow?

**Comment by EdwardCoyle** [comment]
The design put some extra space between the text and the arrow.

I'm not sure why the in-page one doesn't have the arrow... I can look into it

**Comment by Fruko** [comment]
Sorry for the delay, the changes are good for our use case. Thanks!

**Pull request merged**
