### PR TITLE
8085 - Adjusted height so that focus is fully seen

### LINKED ISSUE #8085: Toolbar Searchfield: Unable to expand a collapsible searchfield using the search button
**Describe the bug**
It's a bit difficult to expand (open) a collapsible toolbar searchfield which isn't empty.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
2. Hover the search button on top example (notice it seems wide)
3. Click the search button to open the searchfield 
4. Type something
5. Click outside to collapse the searchfield
6. Try to open the searchfield again by clicking the search button
**Result**: It cannot be opened using the button. Instead, you need to click to the left of the button (in that "extra" space?)

**Version**
- ids-enterprise: v4.88.0

**Screenshots**
toolbarsearchfield

**Platform**
 - Infor Application/Team Name: OS Portal

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted height so that focus is fully seen

**Related github/jira issue (required)**:

Closes #8085 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
- Click on collapsible searchfield
- Focus border should be fully seen
- Type on searchfield
- Unfocus so it collapses
- Click on search icon
- Should expand

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
@tmcconechy, quick question: I remember that if the search field is collapsible and it has text, the text should also visible right? I am comparing it to 4.86,

https://4860-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=new&mode=light&colors=default

**Comment by tmcconechy** [comment]
@ericangeles yes it "was" like that but I dont think it has to be unless anyone complains about it? We could check with @talkaboutdesign

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
This is now working as expected. However, I noticed the hover state under `Non-Collapsible Searchfield Toolbar Flex - With Go Button` looks off.

image

**Comment by janahintal** [comment]
Got the same issue as with the button looking off for long text and in hover and focus state. Kindly see video below 
https://www.loom.com/share/103082f8df67494bb7d10d3f59ddf0ae?sid=dd03b739-94ed-4e32-a4da-0f9865f858f5

**Comment by tmcconechy** [comment]
@janahintal the hover state color is a seperate issue https://github.com/infor-design/enterprise/issues/8191 will be fixed on that one

**Comment by tmcconechy** [comment]
@janahintal how does this look for you now?

**Review by glenlieorillo — APPROVED** [review]
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
