### PR TITLE
5256 - Implement Action Sheet Component

### LINKED ISSUE #5256: Popupmenu: Add an option to show mobile menus
**Is your feature request related to a problem or use case? Please describe.**
Add a setting to popupmenu 

**Describe the solution you'd like**

- [x] Add the setting
- [x] Test it works on android and iphone (r-2)
- [ ] Add some code to the Web Component (later is fine)

**Designs**
(Not really a design use the OS menu)

Screen Shot 2021-06-01 at 1 36 31 PM

**Additional context**
See section "bottom action sheet"
https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR implements a new Action Sheet component that displays a mobile-friendly "drawer" of contextual actions that can be triggered for different purposes.  At large breakpoints, this component is represented by a simple, one-level-deep Popupmenu.  At smaller breakpoints, the mobile-friendly view is displayed and rolled out from the bottom of the page.

There are still some usability/etc features we could add to call this "complete" but PRing in the interests of getting design feedback.

**Related github/jira issue (required)**:
Closes #5256

**Steps necessary to review your pull request (required)**:
- Pull/Build/Run!
- Open http://localhost:4000/components/actionsheet/example-index
- Maximize your browser and click the "..." button.  The button should open a Popupmenu with four actions.
- Select an action.  A toast will appear containing the action's name.
- Open the Popup again and click outside.  A "cancel" toast is fired.
- Shrink the browser width to be less than 767px (`phone-to-tablet` breakpoint).
- Click the "..." button.  An Action Sheet should roll out from the bottom of the screen and an overlay covers the rest of the page content.
- Click any of the actions.  A toast will appear containing the action's name (fires the same event)
- Click the "..." button again.  Click the button inside the action sheet that reads "cancel".  A "cancel" toast will appear.

Some items left to do on this component can be seen on the [TODO.md file](https://github.com/infor-design/enterprise/blob/5256-action-sheet/src/components/actionsheet/todo.md)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
This is an excellent PR. Looks great. The only comment i have is..

a) should  the focus state be shown here? as you can't really use the keyboard. maybe it should be visually disabled
Screen Shot 2021-06-14 at 9 38 40 AM
b) we should also PR a web component version eventually in the new code set

I deployed a branch for design QA. Will post that up when its done so we can add it to the ticket.

**Comment by EdwardCoyle** [comment]
I wasn't sure about keyboard support for this yet -- I might be inclined to leave it as-is because if we accept the design, this component will probably need better keyboard support (technically you could have an action sheet show up on a "desktop" mode per its configuration).  If it does show up on desktop, it's possible to navigate with Tab/Shift+Tab (although it still needs the focus containment, etc)

**Comment by tmcconechy** [comment]
@kevinwhitedesign and @katieinfor 
Can design review the live link on https://5256-action-sheet-enterprise.demo.design.infor.com/components/actionsheet/example-index

Should open that on a mobile device..(s) and you can see the sheet

**Comment by tmcconechy** [comment]
@katieinfor - how long do you estimate it will take for design to review this issue? Trying to decide if we should merge and get feedback later or wait with it at this stage.

**Comment by tmcconechy** [comment]
@EdwardCoyle i say we remove the focus styles for now? And then merge this. From the call yesterday we determined that we wouldnt get feedback that fast so need to circle back on the design QA later when they can get to it

**Review by deep7102 — COMMENTED** [review]
Yes, same as @tmcconechy just the focus state on mobile view might not need, rest all looks relay  great 🍌

**Comment by EdwardCoyle** [comment]
@tmcconechy @deep7102 removed the focus states, should be good to go

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
🍌

**Review by tmcconechy — APPROVED** [review]

**Comment by katieinfor** [comment]
Hey @tmcconechy , Design QA approved this! 
Jira ticket: https://jira.infor.com/browse/UXD-2714?filter=100906 
thanks so much!

**Comment by katieinfor** [comment]
Hey @tmcconechy @deep7102 @kevinwhitedesign 
Here are the notes from the Design QA.
Feedback for Dev: 

- These are all the modifications that need to be made to align with the figma file. 
- Get rid of Toast when canceling out of action sheet 
- Make the left-aligned text and icons, centered. 
- Remove selection border for mobile when opening the action sheet. 
- Add pressed (pulse animation) state that was in designs 

 
Screen Shot 2021-06-24 at 11 45 22 AM

- Add the circle animation upon tapping on the ellipsis.  (shown above)

**Comment by tmcconechy** [comment]
cc @EdwardCoyle Do you want a new issue for that or is that small enough you can just do a additional PR?

**Pull request merged**
