### PR TITLE
4058/ 4050: Fixes to datagrid editor editor and missing editor tooltips

### LINKED ISSUE #4050: Editor: Missing tooltips
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:4000/components/editor/example-index.html
2. Hover on 'B'
3. See issue, there is no tooltip 

**Version**
- ids-enterprise: [v4.19 to now]

**Platform**
 - Mac/Chrome

**Additional context**
See also https://github.com/infor-design/enterprise/issues/4049

### LINKED ISSUE #4058: Datagrid: the fieldValue method is not always performing xssUtils.escapeHTML()
Describe the bug
The logic of fieldValue() does not handle the case when the field argument has a value of 'fields.comments.value'.  The method returns when the field contains '.' before  performing xssUtils.escapeHTML(value).

To Reproduce
1. Using the attached test-editable-editor-singleline-rowheight.html
2. Render the datagrid
3. Notice that the Singleline cell is not showing the rich text value
4. Setting breakpoint in fieldValue() of datagrid.js, see that it doesn't handle a field whose value consists of something like 'fields.comments.value'.

Expected behavior
Rich text cell value is displayed.

Version
4.30.0-dev

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Tried to fix the issue #4058 and it opened up a can of worms as the datagrid "editor" editor was broken. Fixed the following issues:

- datagrid "editor" editor will now load encoded data correctly
- datagrid "editor" editor will now now save
- datagrid "editor" editor will now not show misplaced tooltips when it opens
- Fixed missing tooltips on editor
- Fixed tooltip behavior in general so it will now hide when you click it and the delay is now working correctly

**Related github/jira issue (required)**:
Fixes #4058 
Fixes #4050 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-editable-editor-singleline-rowheight
- the second editor column should load the html data now (says "Bold & Italics"
- go to http://localhost:4000/components/datagrid/test-editable-editor-singleline
- you should now be able edit with the inline editor and save by clicking out
- go to http://localhost:4000/components/editor/example-index.html 
- hover the buttons and you should again get a tooltip
- go to http://localhost:4000/components/tooltip/example-index.html
- drag the mouse slowly down over the button and through the bottom -> tooltip should not show
- drag the mouse over the button and stop -> tooltip should show after 400 (ish ms)
- while the tooltip is open click the button -> tooltip should hide

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@deep7102 yeah i noticed that a couple times too. did you see a way to reproduce?

**Comment by deep7102** [comment]
yeah, I see with mac chrome
- click at the end of text
- click blow the row (on outside table) to go out edit mode
- click again at the end of text
- now again click blow the row (on outside table)
- see looks stuck there it looks do commit if you click to any other cell in that table

**Comment by EdwardCoyle** [comment]
All the tooltip work looks great!  The Editor Editor seems like it's working pretty well, but I found a weird usability thing:

- Open http://localhost:4000/components/datagrid/test-editable-editor-singleline
- Begin Editing the cell with the colorful text.  
- When edit mode is active, try drag-selecting a part of the cell's text.

It generally works fine, but occassionally as soon as you release the mouse button, the editable mode disengages, and a seemingly "emtpy" cell is left in its place.  When this happens, you can't see the contents of the cell anymore until you select another cell, but the value is still in place.  If you edited the text before you tried making the selection, those edits still take.

IDS-Enterprise-_6_

**Comment by tmcconechy** [comment]
I think thats the same issue as deepaks issue. It just wont repopen. I have yet to understand why the hide event wont fire.
I think if we fix that the whole thing will be good again

**Comment by deep7102** [comment]
yes, that is the same issue

**Comment by tmcconechy** [comment]
Ok @EdwardCoyle and @deep7102 think i worked out all the issues. I fixed a leaking popupmenu and made the opening and closing of the editor work a lot better

**Comment by deep7102** [comment]
Looks good now, it commit nicely.
One thing see it looks it been before, the editor got two color picker buttons in it.

**Comment by tmcconechy** [comment]
Hmm yeah taking i look i thought one was fore and one was back color.

**Comment by tmcconechy** [comment]
Fixed this but the visual images could fail. Thats a good catch deepak http://localhost:4000/components/editor/example-customize-buttons.html wasnt working

**Pull request merged**
