### PR TITLE
7162 - Update badges/alerts orange and yellow colors and its naming

### LINKED ISSUE #7162: Badges/Alerts: Update the orange/yellow colors
**Describe the bug**
On https://main-enterprise.demo.design.infor.com/components/alerts/example-index.html and https://main-enterprise.demo.design.infor.com/components/badges/example-index.html

We should have both an orange and yellow alert

**Additional context**
Colors was added to design system https://github.com/infor-design/enterprise/issues/6922

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates the yellow (caution) and orange (alert & warning) colors in badge and alert components.

**Related github/jira issue (required)**:

Closes #7162 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Alert
- Go to http://localhost:4000/components/alerts/example-index.html
- Check the `icon-warning` via inspecting the element
- `Warning` should be color yellow
- Check the `icon-alert`
-  `Alert` should be orange

2.) Badge/Tag
- Go to http://localhost:4000/components/badges/example-index.html
- I updated the test page and you should be able to see different types (default/neutral, good, warning, alert, info, warning)
- It should have warning (yellow) and alert (orange) examples
- Test in different versions and modes
- Go to http://localhost:4000/components/tag/example-index.html
- It should have warning (yellow) and alert (orange) examples
- Test in different versions and modes

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Some minor things. I do think the yellow is looking disabled but not sure we can solve that.  Thats the color. So just wanted to say it

1. The one icon does not look aligned..

Screenshot 2023-02-28 at 9 56 03 AM

2. For that yellow one can you change it from a clock to the same alert icon as the orange one. I think this will look better and match the case

3. For http://localhost:4000/components/badges/example-index.html i love what you did with the page. But can you make the section labels smaller same size as http://localhost:4000/components/alerts/example-index.html `<h2>Outlined Icons</h2>`

**Comment by ericangeles** [comment]
@tmcconechy, looks like the number 1 is not related to this PR? :)

**Comment by tmcconechy** [comment]
@ericangeles updated - my bad. See the yellow one is higher

**Comment by tmcconechy** [comment]
Also sorry for the slight change but i was using...

```
 --ids-color-error - red
 --ids-color-warning - orange
 --ids-color-caution - yellow
 --ids-color-success  - green
 --ids-color-info  - blue
 ```
 
 Going forward. So lets make `alert` orange and then add the new ones if not there..

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
