### PR TITLE
2270 - Datagrid text width improvements

### LINKED ISSUE #2270: Datagrid: Improve calculateTextWidth for various editor types
**Describe the bug**
calculateTextWidth can under estimate the required width for the following editors
* Lookup
* Date
* Time
* Dropdown
* Spinbox 
* Colorpicker

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-calculateTextWidth.html'
* Check the trigger icons for the Lookup, Date, Time
* The Dropdown does not display the the full label for the field
* The spinbox and color picker are not sized correctly

**Expected behavior**
The function is improved to allow for these editors to automatically calculate the minimum width required to display.

**Version**
4.20

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**
The formatters could actually skip the dataset and calculate the actual max width
* Date (Pass a date to the Formatter double digit days and month, eg last day of this year)
* Time (Pass a date to the Formatter, eg last second of today)
* Dropdown (Find the longest option label and pass that value)
* Spinbox (Find the largest and smallest for negatives and pass that to the formatter)
* Colorpicker 

This should then calculate faster, at least for larger datasets.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Update the calculateTextWidth, so that it better handles the formatters and editors.

**Related github/jira issue (required)**:
Closes #2270 

**Steps necessary to review your pull request (required)**:
- Go to http://localhost:4000/components/datagrid/test-calculate-text-width.html
- Check the column widths 
- Change the grid settings and click on update settings
- Check the column widths 
- Spot test other datagrid pages

**Additional Context**:
This was https://github.com/infor-design/enterprise/pull/2285 but i updated the baselines

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@tmcconechy all the other current Datagrid PR's are merged, should be safe to update baselines now.

**Comment by marknolaninfor** [comment]
@tmcconechy 

With the changes to no show the icon if there is an editor defined, but the grid is not editable then the following lines need to be reviewed. From 3987 on add **this.settings.editable &&**
```
    if (this.settings.editable && (columnDef.formatter === Formatters.Dropdown ||
      columnDef.formatter === Formatters.Lookup ||
      (columnDef.editor === Editors.Time))) {
      padding += 10;
    }

    if (this.settings.editable && columnDef.editor === Editors.Date) {
      padding += 5;
    }
```

It does not need to pad if there is no editor icon to display 
image

**Comment by tmcconechy** [comment]
I made a fix as per @marknolaninfor notes. Can i get two approvers? Thanks!

**Comment by davidcarlsonberg** [comment]
Capacity is incorrectly sorting (e.g., putting 10 and 100 just before 1,000):
capacity-sort

**Comment by tmcconechy** [comment]
Ok i was looking at that quick. Seems like the compressors.js is doing something wrong with filtering and sorting but it has been doing that as far back as i can tell. I'll fix it on another pr...

**Pull request merged**
