### PR TITLE
6007 - searchfield filter sort feature

### LINKED ISSUE #6007: SearchField: Request for enhanced Widget Search component with "Filter" and "Sort' control
One of the important elements of a widget is the _**effective placement of components to maximize the limited amount of space**_. But some current widget components are not effectively utilizing the limited space by displaying separately when they can be combined.

Currently the **"Search"** and the **"Filter/Sort"** components are displayed in separate panels even if both can be considered as _"Navigation Controls"_ that can be combined not only for aesthetic reasons but also to maximize the limited space of the widget. 

image

image

As the requirement to place more information in the widget level arise the need to maximize the available space in the 1x1 widget size becomes relevant. the **product developers thus resorted to "custom styling"** to achieve the combination of the Search and Filter/Sort components which is placed below the widget header.

image

This is effective as of the moment as application developers on different products can do custom styles but since the Search and Filter/Sort components are "common" and not a _"unique"_ component thus we must standardize them in the IDS to minimize custom styling across all products that will use the Homepage Widgets. This will shorten turnover time and we can also restrict custom styling efforts on components that is **_"unique"_ only to a particular product.**

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add a setting for filter and sort in listview.

**Related github/jira issue (required)**:
Closes #6007

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/example-filters.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Comments and suggestion are greatly appreciated as I am unsure if I got it correctly.

**Review by tmcconechy — COMMENTED** [review]
This looks pretty good @tjamesallen15 but a couple of things

a) can we do it without adding to the search field component instead we could just add a section to the listview toolbar where you can put a search and any one or two buttons (could be some other cases of buttons). So more of a container.

c) the style should be all grey - the button section is white now with an extra border around

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Putting request changes on until we see it done in a more flexible way where any button can be put into the template

**Comment by ericangeles** [comment]
Also, @tjamesallen15 maybe when we commit changes, perhaps make it a bit descriptive about the fix?

**Comment by tmcconechy** [comment]
@tjamesallen15 one way to think about the commit message we talked about before is to think of it like completing this sentence:

If merged this pr will: "....."

**Review by tmcconechy — COMMENTED** [review]
Looks great now! The only minor thing is the small gap between the sections.

Screen Shot 2022-03-18 at 9 29 48 AM

**Review by ericangeles — CHANGES_REQUESTED** [review]
I see multiple color and alignment issues in dark and high contrast modes and in classic version. See the screenshots

Classic Light Theme (close icon alignment and filter button colors)
Screen Shot 2022-03-21 at 8 43 53 PM

Classic Dark Theme (alignment close icon and filter btns colors)
Screen Shot 2022-03-21 at 8 43 35 PM

Classic High Contrast Theme
Screen Shot 2022-03-21 at 8 43 26 PM

New Hight Contrast Theme (also notice the border bottom edge of the container looks missing)
Screen Shot 2022-03-21 at 8 43 11 PM

New Dark Theme
Screen Shot 2022-03-21 at 8 43 00 PM

**Review by tmcconechy — COMMENTED** [review]
The only small thing i still see is the X is misaligned in any of the three classic modes.
Screen Shot 2022-03-22 at 9 17 37 AM

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
