### PR TITLE
7899 - Adjusted radio button dot centering

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted the sizing and positioning of radio button dot to be more consistently centered.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7899

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to: http://localhost:4000/components/radios/example-index.html
- Selected radio button dot should be centered.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@RJ-Csc can you see if you can improve this with browser zoom? I tried to zoom both in and out in the browser and when you do its not 100% centered.

**Review by yohannahbautista — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
Nice fix! 🍌

**Comment by tmcconechy** [comment]
@RJ-Csc @ericangeles is it just me or does it look like the sides are cut off? I.E. its slightly smaller and looks not completely round?

Screenshot 2023-09-18 at 12 04 40 PM

**Comment by ericangeles** [comment]
@tmcconechy, looks okay on my end.

**Review by tmcconechy — APPROVED** [review]
Ok it looks better now. Could be me

**Comment by ericangeles** [comment]
FYI @infor-design/qa

**Review by janahintal — APPROVED** [review]
Approving. 
image

**Pull request merged**
