### PR TITLE
7037 - Tabs Module Go Button

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in go button where it was affected by the latest changes for button.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7037

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- Hover the `Go` button
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=BB5500
- Hover the `Go` button. It should be the same as in the first link.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
not sure is this example only otherwise it looks weird see the screen shot as:

http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
image

http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=BB5500
image

**Comment by tmcconechy** [comment]
See the same as deepak..  I think:

- for http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html -> the search field border should be visible
- for colored http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=BB5500 the button shape of the category button isnt visible
- see comments https://github.com/infor-design/enterprise/issues/7037#issuecomment-1364127501 can we make it a bit less long?

**Comment by tmcconechy** [comment]
1. can we make the search field shorter as per https://github.com/infor-design/enterprise/issues/7037#issuecomment-1364127501 (maybe 20 px or so.. approx)
2. on a colorized version http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=BB5500 the hover state looks off

Screenshot 2023-01-04 at 10 39 50 AM

3. can we add a color / theme switcher on ://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html on the toolbar to test?
4. Tests

Lets wrap this up... 👍🏻

**Comment by deep7102** [comment]
Thanks! @tjamesallen15 
🍌 Looks nice, waiting for tests

**Review by tmcconechy — DISMISSED** [review]
Looks good now - one test seems unrelated i reran it if it still fails we can skip

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
Actually seems like one test https://github.com/infor-design/enterprise/actions/runs/3856281643/jobs/6572305552#step:10:1298 may have uncovered a bug / error where we can add a guard

**Review by tmcconechy — APPROVED** [review]

**Comment by s-werking** [comment]
Hi @tjamesallen15,

The tabs module header looks great in the new theme, but I'm still seeing some issue with the categories button in the classic theme:
image

**Comment by tmcconechy** [comment]
@s-werking try and test again after all the open PRs are merged. I think that this was fixed deep in one PR...

**Pull request merged**
