### PR TITLE
7722 - fix legend and labels position in column stacked

### LINKED ISSUE #7722: Column Stacked: labels not centered/aligned in legend
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/column-stacked/example-selected.html
2.  See error
3. Notice that the labels were not horizontally aligned with legend

**Expected behavior**
image

**Version**

- ids-enterprise: v4.85.0-dev

**Screenshots**
image

**Platform**
All

**Additional context**
see and check other EPs of Column stacked

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the alignment position of legends and labels.

**Related github/jira issue (required)**:

Closes #7722 
Closes 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/column-stacked/example-selected.html
- Check legends and labels position
- It should be aligned together
- alos test http://localhost:4000/components/column-stacked/components/bubble/example-index.html

**Included in this Pull Request**:
~~- [] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Maybe its another issue but the labels are not centered under the bar? Can you check that as well?

Screenshot 2023-08-17 at 10 25 42 AM

**Comment by ericangeles** [comment]
It looks fine on my end, @tmcconechy. Is this the same test page?

**Comment by ericangeles** [comment]
Removing the margin-bottom from the legend item shouldn't impact anything in the chart's labels.

**Comment by tmcconechy** [comment]
Hmm yeah im running your branch and going here:

Screenshot 2023-08-17 at 11 02 22 AM

Same issue on https://main-enterprise.demo.design.infor.com/components/column-stacked/example-selected.html

So this has another issue in the sprint already. Can either fix it on this one or a second PR... https://github.com/infor-design/enterprise/issues/7722

**Review by tmcconechy — APPROVED** [review]
Approved assuming the other part will be fixed on the other ticket

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/7e16ddd6-8c53-4db5-8346-6fd219dbdfe4

**Pull request merged**
