### PR TITLE
1546 - shared popupmenu placement

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix placement of shared popupmenu.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1546

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/popupmenu/test-context-menu-shared.html
- Open `Developer Console`

Procedure 1:
- Click `Destroy Input Popup` then click `Destroy Textarea Popup`
- See in the console where is the popupmenu placement of `action-popupmenu-2`

Procedure 2
- Refresh the Browser
- Try to do the other way, click `Destroy Textarea Popup` then click `Destroy Input Popup`
- See in the console where is the popupmenu placement of `action-popupmenu-2`
- The location should be the same as the previous step

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
What's the expectation here, @tjamesallen15? I'm kinda lost on the steps.

**Comment by tjamesallen15** [comment]
> What's the expectation here, @tjamesallen15? I'm kinda lost on the steps.

I updated the steps

**Review by tmcconechy — COMMENTED** [review]
Might be something wrong with the example but..

a) you cant right click the inputs it doesnt work
b) when you left click it opens on the bottom and the text is wierd size

Screenshot 2023-09-27 at 12 14 09 PM

We may want to clean this up better for QA

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
Approved.
image

image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/e3e7f618-b0d1-4e37-b400-19f037bfc806

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
