### PR TITLE
Fix incorrect updates in commitCellEditUtil 

### LINKED ISSUE #8850: Datagrid: Incorrect updates in commitCellEditUtil
**Describe the bug**
When using setActiveCell and click to refocus from one editable cell to another. A unique bug occurs where the value of the initially entered/clicked value is placed in the next focused value. This is only achieved with a specific scenario of code

Things to note: 
datagrid.settings.source always has a value with an placeholder function much like this
() => {
/* placeholder empty */
};.
when enter is done, a different focus is simulated and setActiveCell or element.click is used by the application to focus on the editable cell

**To Reproduce**
1. Use attached html file and replace the existing test-editable-inline-editor.html (https://github.com/user-attachments/files/15966129/test-editable-inline-editor.zip)
2. Press enter on 3 editable field or as show on gif below
SimulatedEnterKeyIssue

**Expected behavior**
Value of the 3rd editable row does not duplicate in the first editable row

**Version**
v4.97.0

**Platform**
 - Infor M3 H5A Application
 - Browser Name: Chrome/Edge
 - Browser Version: Version 126.0.6478.115 (Official Build) (64-bit) / Version 126.0.2592.68 (Official build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by crisjoshua-inf**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

On commitCellEditUtil function:
Added handling when cellNode and this.activeCell mismatches rowIndex and dataRowIndex to avoid incorrect updates to editable cells. Added Difference check for cellNode and active cell index

**Related github/jira issue (required)**:
https://inforwiki.atlassian.net/browse/MUA-14253

Fixes #8850

**Steps necessary to review your pull request (required)**:

test scenarios:
In M3 Angular application:

1. Open MMS300 Application -> Go to Data with valid editable cell. 
2. Edit First Editable cell on first row then edit second row as well on same column.
3. On Second Row, Editable cell, press enter twice very fast.

Actual: Value in second row is being placed in first row editable cell.
DoubleEnterKeyIssue

Things to note in M3 Angular Application:
1. this.settings.source always has a value with an placeholder function much like this 
() => {
          /* placeholder empty */
};.
2. when enter is done, a different focus is received from BE and setActiveCell or element.click is used by the application to focus on the editable cell
3. Will attempt to provide a stackblitz or an example in enterprise demo code in the future for better referrence. Thanks!

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@crisjoshua-inf can you fix the lint issues and add a change log entry?

Is there any way for us to test this in our examples?

**Comment by crisjoshua-inf** [comment]
Hi, attached a simulated example in enterprise demo code.
SimulatedEnterKeyIssue
[test-editable-inline-editor.zip](https://github.com/user-attachments/files/15966129/test-editable-inline-editor.zip)

**Comment by crisjoshua-inf** [comment]
Hi Tim, for the changelog, Should I use the PR URL and PR number for the reference?

**Comment by n-ace-ancog** [comment]
I am still able to replicate the issue in http://localhost:4000/components/datagrid/test-editable-inline-editor.html in this fork. The cursor / focus keeps going on the 1st editable component in the same column after pressing enter.

https://github.com/infor-design/enterprise/assets/156752175/21b3a629-821b-49d0-8645-73e19cd4d9f1

**Comment by tmcconechy** [comment]
@crisjoshua-inf use the issue number (github issue). So please make a quick issue too?

**Comment by crisjoshua-inf** [comment]
@n-ace-ancog doesn't look like the same issue. Did you copy the exact file in the repo? The change in focus is intended but the issue is when the value of the 3rd row editable cell is seen to replace the 1st row editable cell value in the gif. 

@tmcconechy I've created the issue and updated the changelog.

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@crisjoshua-inf which file did you add to test? Can you add the file to the pull request so we can test it?

**Comment by crisjoshua-inf** [comment]
Hi @tmcconechy, i've added the simulation code in this fork.
But it's important to note that in this fork, the fix is already in place for this issue. 
In order to replicate the issue, you'll have to remove the changes in datagrid.js and try to steps in http://localhost:4000/components/datagrid/test-editable-inline-editor.html. Thanks!

**Comment by n-ace-ancog** [comment]
> @n-ace-ancog doesn't look like the same issue. Did you copy the exact file in the repo? The change in focus is intended but the issue is when the value of the 3rd row editable cell is seen to replace the 1st row editable cell value in the gif.
> 
> @tmcconechy I've created the issue and updated the changelog.

@crisjoshua-inf yes I did. Replaced the file in the repo with the file in .zip you attached here. Also pulled the latest updates from this fork and tried it again. The 2nd row value is not being copied in the 1st row as well in my side.

https://github.com/infor-design/enterprise/assets/156752175/42c6c4ab-3677-407c-8a48-81f4ebb39068

I think a separate use case example page would be good here instead of updating the /test-editable-inline-editor.html due to the added behavior of change focus after pressing enter. Your thoughts @tmcconechy?

**Review by jbrcna — CHANGES_REQUESTED** [review]
Large GIF (1004x484)

**Comment by crisjoshua-inf** [comment]
After clarifying with @n-ace-ancog. I've created a new html test file named test-editable-inline-editor-quick-focus-change.html and reverted changes to test-editable-inline-editor.html. Please proceed with your testing. Thank you!

**Review by n-ace-ancog — APPROVED** [review]
Working on my end via http://localhost:4000/components/datagrid/test-editable-inline-editor-quick-focus-change.html.

**Before fix** - removed code changes in src/components/datagrid/datagrid.js

https://github.com/infor-design/enterprise/assets/156752175/20a11109-639f-4362-a129-a9856cac11c7

**After fix**

https://github.com/infor-design/enterprise/assets/156752175/91159f69-92ae-4c3d-9fd7-3bbe3a526e39

**Review by jbrcna — APPROVED** [review]
Large GIF (1004x484)

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/52d18214-e013-4e45-ad94-707244fae2ea

**Pull request merged**
