### PR TITLE
8399 - Fixed alignment issues in clear button

### LINKED ISSUE #8399: Searchfield: x icon focus is not centered
**Describe the bug**

**To Reproduce**

1. Go to https://4921-beta0-enterprise.demo.design.infor.com/components/searchfield/example-index
2. Type a text
3. Press tab to focus in x icon

**Expected behavior**
focus should be properly aligned

**Version**

- ids-enterprise: beta

**Screenshots**
image

**Platform**
all major browser

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted clear icon

**Related github/jira issue (required)**:

Closes #8399

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/searchfield/example-index
- Type a text
- Press tab to focus in x icon

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — COMMENTED** [review]
In **RTL**, the highlight circle is closer to the bottom:

image

image

**Default:**
image

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — DISMISSED** [review]
Mac Chrome - RTL
image

Mac Firefox - RTL
image

Safari - RTL
image

Mac Edge - RTL
image

**Comment by jbrcna** [comment]
issue still exists LTR 
safari
image
firefox
image

RTL is now fixed
image

**Review by janahintal — CHANGES_REQUESTED** [review]
**Windows** 
Chrome 
image

**FF latest - _button alignment looks a bit off / not centered_**
image

Edge latest
image



**Mac Sonoma** 
**Safari latest 17.3 - _button alignment looks a bit off / not centered_**
image

FF latest 
image

Chrome latest 
image

**Comment by tmcconechy** [comment]
Screenshot 2024-03-07 at 12 30 21 PM
Screenshot 2024-03-07 at 12 30 53 PM

Its a tiny bit off in both LTR and RTL but this would be acceptable for now for me.

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@infor-design/qa can you retest

**Review by glenlieorillo — APPROVED** [review]
**LTR**
- Mac Chrome
image

- Mac Firefox
image

- Mac Edge
image

- Safari (_Observation: slightly cut-off_)
image

**RTL**
- Mac Chrome
image

- Mac Firefox
image

- Mac Edge
image

- Safari (_Observation: slightly cut-off_)
image

**Review by n-ace-ancog — APPROVED** [review]
Now working as expected.

**Normal**
image

**RTL**
image

**Review by janahintal — APPROVED** [review]
image

**Review by jbrcna — APPROVED** [review]
image
image

**Pull request merged**
