### PR TITLE
NG1646 - fix tooltip not showing after selecting item in lookup

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

When you set up a tooltip in a lookup, it does not show after selecting an item or after closing the lookup modal. There is a method for setting up a tooltip that is only intended for multiple selections in a lookup. This also affects the `beforeShow` setting, causing it to be called when hovering over the input field. This PR fixes those issues.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1646

**Steps necessary to review your pull request (required)**:
1. Pull this branch, build, and run the app.
2. Go to [http://localhost:4000/components/lookup/test-beforeshow.html](http://localhost:4000/components/lookup/test-beforeshow.html).
3. Hover over the lookup input field.
   - It should show the tooltip: `testing tooltip`.
4. Inspect and check the console.
   - There should be no message output about `beforeShow` (API and response).
5. Open the lookup and select any item.
   - After closing the lookup modal, it should still show the tooltip: `testing tooltip`.
   - The console message should only appear after the lookup modal is closed.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by n-ace-ancog** [comment]
Not sure if this is an issue. Is this expected @ericangeles?
1. Select an item in the modal
2. The tooltip automatically shows up

https://github.com/infor-design/enterprise/assets/156752175/11e95fdd-05f4-40a6-9a04-b26406a1fdce

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/da81faf4-1183-44cd-b241-674faf3aebc6

**Comment by ericangeles** [comment]
@n-ace-ancog, yes, I believe so. Basically, it focuses on the input field while the content of the tooltip is already there.

**Comment by whernebrink** [comment]
@ericangeles does this fix mean that you can't use the tooltip's `beforeShow` on lookups?

**Pull request merged**
