### PR TITLE
5609 - Add mobile enhancements and style changes

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds mobile enhancements and style changes to the cards component.
- Card should have `16px` padding on both sides (basic card and card variations)
- swipe action right button should have `5px` border-radius (top right, bottom right) see the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- swipe action left button should have `5px` border-radius (top left, bottom left) see the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- Swipe action (left and right) should be wider than before. See the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- Swipe action icon should be `16px x 16px`
- The contents of it should always be centered
- The second line should be truncated

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5609

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Test the basic card
- Go to http://localhost:4000/components/cards/example-index
- Check the `.card-header`
- It should have `16px` spaces on both sides

2.) Test the card variations
- Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
- Card variations should have `16px` space on both sides

3.) Test the swipe action
- Go to http://localhost:4000/components/swipe-action/example-index.html
- Toggle the device toolbar in the chrome dev tool
- swipe action right button should have `5px` border-radius (top right, bottom right) see the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- swipe action left button should have `5px` border-radius (top left, bottom left) see the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- Swipe action (left and right) should be wider than before. See the [Figma](https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=272%3A11075) design
- Swipe action icon should be `16px x 16px`
- The contents of it should always be centered
- The second line should be truncated

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Expecting the build to fail. @tmcconechy, can you review it first before I update the test images?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Ok thanks @ericangeles 

1. The text in the card is too far down. If i look at the design they are measuring from the top of the card to the top of teh big C in Card. So that is now 27px. I think we need to eyeball this one and not explicitely set it to 18px... `8px 2px 8px 16px` looks good...

2. For the swip list..
a) the icon example doesnt appear centered vertically

Screen Shot 2021-12-14 at 10 14 09 AM

b) and i see small border bleed...
Screen Shot 2021-12-14 at 10 14 17 AM

c) I know its the design but the button feels a little wide? Can we down it just a small bit and override the design specs? It might be another one where the design specs dont 100% match reality in the code

**Comment by ericangeles** [comment]
@tmcconechy can you take a look again?

**Review by tmcconechy — APPROVED** [review]
Looks good to me now @ericangeles - just the tests or anyone else has anything on review..
Thanks...

**Review by tmcconechy — APPROVED** [review]

**Comment by deep7102** [comment]
Looks all good!
Not sure it might be just the example issue, but soon you click on  last card `Swipe Action (Continuous)` it has error.

image

**Comment by ericangeles** [comment]
@deep7102 yep, been seeing this since the component was implemented. Thoughts of this @tmcconechy @EdwardCoyle ?

**Review by EdwardCoyle — APPROVED** [review]
Not sure what the source of that event problem is... I tried tracking it down and it seems to be triggered by a Touchstart event, but it's not the one setup in the Swipe Action:

Screen Shot 2021-12-20 at 11 21 23 AM

The only one I can see is attached to `document` (see the "Event Listeners" tab on the Elements panel in dev tools), but if I remove that one it's still firing.

I'm approving this PR since it covers the design changes but we should come back to this one soon

**Comment by tmcconechy** [comment]
I cant seem to track it down either but it looks like maybe a handler was deleted or something https://stackoverflow.com/questions/32231036/uncaught-typeerror-x-event-speciali-origtype-intermediate-value-handl

Like the event handler function is gone...

**Comment by tmcconechy** [comment]
Made an issue https://github.com/infor-design/enterprise/issues/5965

**Pull request merged**
