### PR TITLE
Misc - Datagrid Column Size Fixes and Features

### LINKED ISSUE #4016: Datagrid: Default column width renders too wide
**Describe the bug**
One pushback we are getting in landmark for 4.x is that there is too much horizontal scrolling for datagrids compared to the 3.5. 

**To Reproduce**
- See me for how URL/login and credentials.

**Expected behavior**
Want to columns to be greedy about reclaiming white space.

**Version**
7.1.1 of ng/ 2.28 of ep
**Screenshots**
In this case many columns seem to take more space than is needed. Some have their filter fields taking up more width than their cell.
image
In 3.5 this was much less of an issue because in landmark we set the size to fit on the columns and had a much smaller font.
image
A more aggressive reclaim of white space could be of at least marginal improvement. 
image

**Platform**

 - PC
 - Window10
 - Latest Chrome

**Additional context**

### LINKED ISSUE #4017: Datagrid: Add favor data setting over the column header in a datagrid when sizing column
One pushback we are getting in landmark for 4.x is that there is too much horizontal scrolling for datagrids compared to the 3.5.

**Describe the solution you'd like**
A new setting to allow for cell data to be favored over the column headers when computing width.

**Describe alternatives you've considered**
A full auto fit all column where datagrid would never horizontally scroll; like in 3.5.

**Additional context**
With a few changes this could reclaim a lot of space and keep us from horizontally scrolling as much as we have to now. 
- change filter icon to be something much narrower perhaps just a down arrow
- have a minimum size for filter fields to they at least fit in the column header: sizes would be different based on the component. 
- Keep data always in view but allow the header text to have an ellipsis.

Notice in the before and after of the datagrid it's much small and it still shows all data. This is ofcource a stress test and when the browser is this wide it wouldn't need to have all the columns so narrow but I wanted to illustrate the difference that could be made up by doing the things listed above. 

image

### LINKED ISSUE #4032: Datagrid: Make the select column consistent size
**Is your feature request related to a problem or use case? Please describe.**
When datagrid allows select/multi-select, the column size seems to be trying to factor into the column sizing. However, this column doesn't need to change widths as it will always contain the same size content. It can be very inconsistent when in a multi-list situation. 

**Describe the solution you'd like**
Create a standard, fixed column size for the select column

**Describe alternatives you've considered**
-
**Additional context**
image

### LINKED ISSUE #4154: Datagrid: Spacing Inconsistencies
**Describe the bug**
I was looking at this https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=light&colors=0066D4

Discovered that cell padding was 21px on large size. We should move this onto the 8pt grid and use 24px for this padding.
Screenshot 2020-07-15 12 07 40

I also found that medium was using 16px cell padding, and in places where text was right aligned - 21px padding.
Screenshot 2020-07-15 12 07 49

The small datagrid was using 11px, should we switch to 16px to be on the 8pt grid? (I guess 8px padding is another option here)
Screenshot 2020-07-15 15 15 28

The extra small datagrid was using 10px cell padding, but probably could be using 8px for the same reasons.
Screenshot 2020-07-15 16 32 24

My designs on the left:
https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?node-id=29%3A2

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pr fixes 4 bugs and features all related to column sizing.
- Added a spaceColumn setting (no stretching)
- Added a columnSizing setting (data over header)
- Fixed bugs in the auto column width (mainly it wasn't taking the left and right padding into account)
- Fixed QA bug so that the left and right padding of cells and headers is in multiples of 4 (this will be the norm going foward). Large/Medium: 16 Small/Extra Small: 8

Impact: When reviewing try and smoke test a few example datagrid examples on http://localhost:4000/components/ particular with columns/column sizes, RTL themes and row height.

Note: Caused EVERY baseline to need an update 😢 

**Related github/jira issue (required)**:
Fixes #4032 
Fixes #4154 
Fixes #4016 
Fixes #4017 

**Steps necessary to review your pull request (required)**:
**Issue 4032**
- go to http://localhost:4000/components/datagrid/example-spacer-column.html
- notice the spacer column filling the right end
- hide/show columns in the .. menu
- the columns (particularly the selection column) will stay the same size
- try various column related tests

**Issue 4154**
- go to http://localhost:4000/components/datagrid/example-filter.html
- test themes and rowheights
- left and right padding has changed and is now Large/Medium: 16 Small/Extra Small: 8

**Issue 4016**
- go to http://localhost:4000/components/datagrid/example-books.html
- compare each to https://master-enterprise.demo.design.infor.com/components/datagrid/example-books.html
- notice some size reduction....
- try a few themes / row heights

**Issue 4016**
- go to http://localhost:4000/components/datagrid/example-columnsizing
- notice some size reduction and that the headers are cut off, its sizing to data alone
- go to http://localhost:4000/components/datagrid/example-books.html (this is the same but without that feature)
- try a few themes / row heights

**bonus fix**
- go to http://localhost:4000/components/datagrid/test-fixed-header-nested-grids.html
- expand the grid to reveal the nested grid
- scroll up and the headers should go under the other headers now

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@EdwardCoyle which example is that video. That sounds like a separate issue which @jmacaluso711 and I?  fixed here: https://github.com/infor-design/enterprise/issues/1924

But wondering if i broke something as it Looks Good Here:
https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?theme=uplift&variant=light&locale=he-IL

So would like to compare

**Comment by EdwardCoyle** [comment]
I was able to make this occur on http://localhost:4000/components/datagrid/example-spacer-column.html?locale=ar-EG -- possibly due to the spacer column?

I tried on http://localhost:4000/components/datagrid/example-fixed-header.html?theme=uplift&variant=light&locale=he-IL and it doesn't seem to occur unless you:
- make sure the grid is scrolled all the way to the left
- grab the second or third to last column resize handles and slowly drag to the right

Seems like it's ok for a short distance and it accelerates once it passes a certain point, making it feel like you're dragging the wrong way?  Not sure.

IDS-Enterprise-_9_

**Comment by jmacaluso711** [comment]
@EdwardCoyle @tmcconechy I'm seeing this behavior here as well: https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?theme=uplift&variant=light&locale=he-IL

If you keep dragging past the point where the columns on the right are at their min-width it continues to resize the column on the left. If you go really slowly you can see it, but if you continue dragging at the same pace it accelerates like in @EdwardCoyle's video.

**Comment by tmcconechy** [comment]
OK i played around with this bit but it seems like a separate issue. Hey @deep7102 do you have any thoughts?

**Comment by deep7102** [comment]
Yeah this looks funky, if you try to drag while holding shift key that's loos fine which isotherm option i see. I think this broken case while we dragging the column we are not adjusting whole table width which causing all the columns shifting. so might be if try to adjust table width accordingly as column wider/shorter might fix. not sure just thought might need to play around.

**Comment by tmcconechy** [comment]
ok lets push that to later then - it wasnt really 100% related to this fix as evident it was there in 4.26 as well

**Comment by deep7102** [comment]
Let's fix in separate issue.

**Comment by tmcconechy** [comment]
@EdwardCoyle @jmacaluso711 skipping this for now made a new issue https://github.com/infor-design/enterprise/issues/4193

**Pull request merged**
