### PR TITLE
8446 - Tooltip Tabs Header

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix tooltip not showing properly when there is an ellipsis in tabs.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8446

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs-header/test-max-width.html
- Hover on Tabs

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Not all tabs with ellipses (...) have a tooltip.

Steps to reproduce:
1. Hover over tabs (start with `Long Header Tabs 9` up to the last tab)
2. Wait for the tooltip


https://github.com/infor-design/enterprise/assets/102151352/18795961-1ca1-469e-abf8-445160afadf2

**Review by janahintal — CHANGES_REQUESTED** [review]
Issue still exists in https://8446-tooltip-tabs-header-enterprise.demo.design.infor.com/components/tabs-header/test-max-width.html
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
issue still exists
image

**Review by n-ace-ancog — COMMENTED** [review]
Seems all have tool tip now
**Mac Safari**
image

**Mac Chrome**
image

**Windows Chrome**
image

Maybe a question @tjamesallen15  @tmcconechy, do we expect tooltip on the tabs in the dropdown with text cut off (...) ?

**Comment by tmcconechy** [comment]
@tjamesallen15 @n-ace-ancog 

I would expect the tooltip only if

a) a tooltip is added in the code
b) or if its cut off to the ellipsis....

**Review by janahintal — CHANGES_REQUESTED** [review]
Disabled tab has tooltip. 

https://github.com/infor-design/enterprise/assets/45757016/9764ee57-29c3-4fe3-a2da-3534a78e712d

**Review by glenlieorillo — APPROVED** [review]
Bugs have been fixed. Thanks, @tjamesallen15!

https://github.com/infor-design/enterprise/assets/102151352/80033d88-08d6-4a1b-aa9b-34cc9582eafb

**Review by jbrcna — APPROVED** [review]
image
image

**Review by n-ace-ancog — APPROVED** [review]
Cut off text in the dropdown is now fully displaying.

**Windows Chrome**
image

**Mac Safari**
image

**Review by janahintal — APPROVED** [review]
Approving. Now working on my end. 
image

image

**Pull request merged**
