### PR TITLE
5887 - Added Comma translate option for locale for generating lists

### LINKED ISSUE #5887: MultiSelect: Use of localized commas is required in comma delimited lists
Use of localized commas is required in comma delimited lists e.g.

image

Example:
Japanese linguist: "Displayed options are divided by English comma, not a localized one (、)"
Arabic linguist: ".... you will the Arabic separated with English Comma, Arabic Comma should be used!"
Etc.

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added Comma option in translate.

Note: Not sure what to put in the other locales, only added for JP since it was mentioned in the ticket

**Related github/jira issue (required)**:

Closes #5887 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to:
   - http://localhost:4000/components/multiselect/example-index.html
   - http://localhost:4000/components/multiselect/example-index.html?locale=ja-JP
   - http://localhost:4000/components/multiselect/example-index.html?locale=ar-SA
   - http://localhost:4000/components/multiselect/example-index.html?locale=da-DK (check for locales that don't have special commas)
- Select several states in Multiselect (Standard)
- Commas should be correct for locale

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista the idea is that the commas can be different in some locales 

Japanese: https://en.wikipedia.org/wiki/Japanese_punctuation#Comma
Arabic: https://www.compart.com/en/unicode/U+060C

So maybe we add a section to each locale file for each file https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/ar-EG.js#L49 perhaps

```
punctuation: {
  comma: '،'
 }
```

Then read that for the locale. Would add this to all locales but everyone but the arabic and japanese one would just be `,`

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I think we should do it as part of a setting in each locale as explained above. And do it for arabic and japanese. The rest in english unless explained

**Review by EdwardCoyle — DISMISSED** [review]

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Review by tmcconechy — APPROVED** [review]
One correction / addition

**Review by glenlieorillo — APPROVED** [review]
QA Approved. 

http://localhost:4000/components/multiselect/example-index.html

https://github.com/infor-design/enterprise/assets/102151352/bce3ff96-1f50-422d-bfea-7eebf096f688

http://localhost:4000/components/multiselect/example-index.html?locale=ja-JP

https://github.com/infor-design/enterprise/assets/102151352/0f7fe55b-fd4d-4a78-bc68-6ee1e2ee5312

http://localhost:4000/components/multiselect/example-index.html?locale=ar-SA


https://github.com/infor-design/enterprise/assets/102151352/e16b23fe-73b4-48df-a75a-7f97fdd8a96d

Border looks off, will create a new ticket.
image


http://localhost:4000/components/multiselect/example-index.html?locale=da-DK


https://github.com/infor-design/enterprise/assets/102151352/1cd88cea-fc93-4538-a27d-b9b96ef0e0a8

**Review by jbrcna — COMMENTED** [review]
in Firefox the text is not centered. 
image

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
