### PR TITLE
2193 - Add Checkbox and Radio field types to the Compact Form

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR: 
- brings the style for the Compact Form into alignment with recent design iterations, as outlined in infor-design/design-system#370.  The styles shrink the input field fonts, change the header style, and add a gutter between nested grids (see [V5 Notes](https://paper.dropbox.com/doc/Compact-Form--AgGu0QJk83oONJo1DNMYEB_FAg-R8idPCwaQcbGBbIZVX3Md#:h2=V5:) in Dropbox Paper)
- Allows for the use of checkboxes/radios in the compact form with proper alignment/font sizes.

**Related github/jira issue (required)**:
#2193

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, run app.
- Navigate to http://localhost:4000/components/form-compact/example-index.html and http://localhost:4000/components/form-compact/example-index.html?locale=ar-EG (Uplift also works, but isn't 100% tested until we get the fonts in)
- Inspect the checkbox and radio button groups fields to ensure they line up properly with other fields.  - When selecting/highlighting any radio or checkbox, their field containers should change to the blue background color and remain that way until the focus moves away from that group.
- Ensure that on the desktop breakpoint, there is a gutter in-between Section One and Section Two, and that Section Three underneath lines up vertically with Section One.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@nickwynja that is actually standard browser behavior. Radios you can arrow checkboxes you tab, so we would have to fight with that...

**Comment by EdwardCoyle** [comment]
@nickwynja it's true that they're different in the sense that a group of radios represents multiple choices for the same "option" (fx: "x" could be 1, 2, or 3), where as a set of checkboxes could each toggle individual options (fx: "x" = true, "y" = false, "z" = false).

There's an argument to be made that we could support a group of related checkboxes that act in a similar manner to the radios, but at that point you could also argue that the right UI choice should be radios.

**Comment by EdwardCoyle** [comment]
@tmcconechy, question for you?

1. Not sure I understand this one.  There should be about an 8px border between any label/input text and the field boundaries.  Is there one/multiple specifically you're seeing without padding?
2. @nickwynja, Kayiu and I tried to figure this out, but it's trickier than just moving the markup around.  Section Two has to logically come before section three in terms of tab order.  The way the markup sits now, even though there's a large gap underneath section one, causes the fields to flow in the correct order, and sit correctly in the responsive view.  We settled on keeping it as-is.  See the screenshot below:
Screen Shot 2019-07-09 at 11 47 32 AM
3. Good catch, there should be borders on these groups!

**Comment by tmcconechy** [comment]
@EdwardCoyle 
1.  i mean the bottom padding on the whole thing is less than the top, left and right (at larger desktop where its 20px). Maybe a non issue because it might continue down.
2. Ok, yeah i figured or would be more like homepages with the absolute positioned containers. (Could be one option)
3. ok cool

**Comment by EdwardCoyle** [comment]
Not much I can do about that one, other than change the text content.  RTL with English copy seems to have that effect with punctuation.

**Comment by EdwardCoyle** [comment]
@tmcconechy I re-balanced the fields in this example a bit to lessen the space.  I had originally laid the fields out according to design document for this pattern, but I think your right that we should just show better layouts.  I also fixed the icon alignment.

@davidcarlsonberg I changed the copy on those inputs to have no punctuation so we don't see any RTL weirdness.

**Pull request merged**
