### PR TITLE
7991 - Fix Checkbox and Tab Darkmode colors

### LINKED ISSUE #7991: Checkbox: Style issue when checked, in modal in dark mode
**Describe the bug**
The background of a selected checkbox is the same as the modal background color in dark mode.

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-checkbox.html?theme=new&mode=dark&colors=default
2. Open modal
3. Check one of the checkboxes

**Screenshots**
image

**Version**
- ids-enterprise: v4.87.0

**Platform**
 - Infor Application/Team Name: OS Portal 
 
**Additional context**
Looks OK on 4.86.0

### LINKED ISSUE #7999: Cards: Border below the tabs is missing in Classic-Dark Version
**Describe the bug**
Border below the tabs is missing in Classic-Dark Version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/cards/test-tabs-card.html?theme=classic&mode=dark&colors=default
2. Notice the border below tabs is missing

**Expected behavior**
There should be a border below the tabs

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

image

image

_Reference:_
image

**Platform**
 - All major browsers

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changed the checkbox color in dark mode and also added a small fix to tab border in classic mode.

**Design Questions:**
- disabled checkbox colors
- focus state (tab into checkbox its very very subtle but is correct as its mostly a white ring

**Design QA Links:**
https://darkmode-colors-enterprise.demo.design.infor.com/components/checkboxes/example-index.html
https://darkmode-colors-enterprise.demo.design.infor.com/components/modal/test-checkbox.html?theme=new&mode=dark&colors=default

**Related github/jira issue (required)**:
Fixes #7991
Fixes #7999

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/checkboxes/example-index.html?theme=new&mode=dark&colors=default
- see new colors
- also check http://localhost:4000/components/modal/test-checkbox.html?theme=new&mode=dark&colors=default

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
update: made changes based on design feedback

**Review by tjamesallen15 — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
Looks good! Just need to resolve the conflict on the test page. 🍌

**Review by janahintal — APPROVED** [review]
Approving, colors looks good on dark mode. On both https://darkmode-colors-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=new&mode=dark&colors=ffffff & https://darkmode-colors-enterprise.demo.design.infor.com/components/modal/test-checkbox.html?theme=new&mode=dark&colors=default

Seeing console error after I refresh the page.
Video:
https://www.loom.com/share/f5557ec8f6f746aaaac177dfea962976?sid=9818017e-8ac2-4c00-9d98-7148826cb5d0

image

**Comment by max-hizon** [comment]
Is it okay for the colors of the checkboxes of New and Classic to be different? It might be better to have the same color scheme for both versions.

New (changed checked boxes to white)
image

Classic (still uses gray checked boxes but visible)
image

**Review by jbrcna — APPROVED** [review]
great work. approving

**Comment by tmcconechy** [comment]
@max-hizon yes its ok. Classic mode is essentially "deprecated" and we are not updating the look there so will remain as is in mostly all cases unless a critical bug.

**Pull request merged**
