### PR TITLE
7467 - Fixes in disabled datagrid filters

### LINKED ISSUE #7467: Datagrid: Disabling a dropdown column filter adds grey box around dropdown arrow
**Describe the bug**
When a dropdown column filter gets disabled, the dropdown arrow on the column filter has a grey box around it. I also noticed that the timepicker column filter is still clickable when it is disabled.

**To Reproduce**
1. Add `filterDisabled: true` as a column setting for the activity column in http://localhost:4000/components/datagrid/example-filter.html
2. Go to http://localhost:4000/components/datagrid/example-filter.html
3. See that there is a grey box around the dropdown arrow in the column filter

4. Add `filterDisabled: true` as a column setting for the time column in http://localhost:4000/components/datagrid/example-filter.html
5. Go to http://localhost:4000/components/datagrid/example-filter.html
6. Click on the timepicker button in the Time column filter
7. See that it is still clickable even though it is disabled

**Expected behavior**
The dropdown column filter should look the same as other column filters when they are disabled. The timepicker button should not be clickable when the column filter is disabled.

**Version**
- ids-enterprise: v4.82.0-dev

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 112.0.5615.138 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes on disabled filters in datagrid

**Related github/jira issue (required)**:

Closes #7467 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-filter-disabled.html
- Check all the disabled filter columns. Click and hover on buttons
- Should look disabled

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — CHANGES_REQUESTED** [review]
the timepicker button is now unclickable. however the calendar icon is misaligned and activity column looks off in High Contrast
`safari browser`
image

`high  Contrast`
image

**Comment by ericangeles** [comment]
@yohannahbautista can you take a quick look? Thanks!

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@jbrcna does this look good now to you?

**Comment by jbrcna** [comment]
yes @tmcconechy . it was now fixed. approving
image

**Review by jbrcna — APPROVED** [review]

**Review by janahintal — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]

**Pull request merged**
