### PR TITLE
3870 - Added tree in calendar events

### LINKED ISSUE #3870: Calendar: Request for a Tree List Type Legend Display
**Is your feature request related to a problem or use case? Please describe.**
The Legend display list is only at one level. However, in the use case of Pathway, the items in the Legend have sub-items that form levels like in Tree lists (as seen below).

**Describe the solution you'd like**
The Legend display would be suitable for Pathway if there is a way to make lists support Tree Lists.

**Describe alternatives you've considered**
n/a

**Additional context**
-	Infor Pathway uses the Calendar in booking Facilities. Hence, the Facilities are listed as the Legend’s items. These facilities have sub-facilities as well as seen below.
o	Additionally, if a higher level item in the Facilities is checked all of its sub-facilities will get checked as well.

Sample:
image

IDS Calendar Legend:
https://master-enterprise.demo.design.infor.com/components/calendar/example-only-calendar-legend.html

image

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added tree in calendar events

**Related github/jira issue (required)**:

Closes #3870 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/calendar/test-calendar-event-tree.html
- Check event tree on the left

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista not sure if this is done from what i suggested before. But checking again...

1. Maybe this can just go to ellipsis instead ...
2. Can we show some sick time items so we can see that that works to hide/show them?

Screenshot 2024-02-05 at 10 48 53 AM

**Comment by jbrcna** [comment]
Failing in RTL
**Safari**
no check box
image

**Chrome , Firefox**
checkbox is displayed.  however, there's no check icon 
misaligned texts.
focus highlight is cut off
image

other events is not displayed. when` discretionary time off is checked,` notice that the event that is displayed is only "birthday off". `Autumn Foliage `Trip & `Mexico Trip` were not displayed
image




wasn't sure if this is a bug but noting for reference. 
focus highlight is cut off with long text
image

**Review by tmcconechy — COMMENTED** [review]
Looks good but two things.

1. Can we remove the extra space between these items:
Screenshot 2024-02-08 at 9 52 59 AM
2. Do we have a way to set the tree to expanded or collapsed when you open the page?
3. Des this need Angular types?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Just those last two things please if you can @yohannahbautista ?

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- I just noticed that the color of ellipses in a disabled category `Company Hol...` is different.

image

image

image

- `Cancel` and `Apply` buttons are not rendered properly in RTL.

Steps to reproduce:
1. Go to https://3870-event-tree-enterprise.demo.design.infor.com/components/calendar/test-calendar-event-tree.html?theme=new&mode=light&locale=ar-SA (RTL)
2. Click the calendar icon
3. Notice the buttons below (Cancel and Apply buttons)
image

**Review by jbrcna — APPROVED** [review]
image
image

**Comment by jbrcna** [comment]
perhaps not related but noting for reference
**RTL**
dropdown is cut off in responsive view
image

**Comment by tmcconechy** [comment]
@yohannahbautista when your back and working on this. Note that new design assets. Looks like they wanted the checkbox children uncolorized https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11564&mode=design&t=VyfuxiBj2RUbs2sK-0

**Comment by ericangeles** [comment]
Please review it again, @infor-design/qa

**Comment by jbrcna** [comment]
dropdown is still cut off in RTL. also notice that the icon and legend text have no space 
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Also failing in Mobile on my end with Legend alignment.
image

Add Event API & Modal checkbox looks cut off 
image


Getting 'Undefined NaN' after clicking Today in Weekview on https://3870-event-tree-enterprise.demo.design.infor.com/components/calendar/test-calendar-event-tree.html?theme=new&mode=light&locale=ar-SA#
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Failing in mobile view (RTL).

**BrowserStack** (iPhone 15 Pro Max)

image

Also, getting 'undefined NaN' after clicking `Today` button in Week view.
image

image

**Comment by tmcconechy** [comment]
@yohannahbautista if anything is unreleated/existing issue feel free to make/or ask QA to make new issues. 👍🏻

**Comment by yohannahbautista** [comment]
@glenlieorillo @jbrcna @janahintal Are these issues because of my PR or do they already exist in main? If any of the bugs are because of my changes, I'll include it here, but if not then it might be better to report it as a separate bug

**Comment by jbrcna** [comment]
> @glenlieorillo @jbrcna @janahintal Are these issues because of my PR or do they already exist in main? If any of the bugs are because of my changes, I'll include it here, but if not then it might be better to report it as a separate bug

Hi @yohannahbautista , thanks for clarifying. the RTL issue also exists in main
image

**Comment by yohannahbautista** [comment]
Hello, there's text overflow already in my local, and I've updated the checkbox colors for the child nodes
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/996e0d77-2698-4524-9e6d-23eb3d174762

**Review by janahintal — APPROVED** [review]
Looks good, approving! Thanks.
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
