### PR TITLE
6546 - lookup dblclick

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add `dblClickApply` setting in lookup for selection of item.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6546

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/lookup/example-dblclick.html
- Open `Lookup` for `Product`
- Double Click an item to select.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 it doesnt seem to be putting the values in the field.

http://localhost:4000/components/lookup/example-dblclick.html
- click one and hit apply -> value is not put in the field
- and open it again and double click an item -> value is not put in the field

**Comment by tmcconechy** [comment]
@tjamesallen15 now it seems to insert the item on click and not double click in the example http://localhost:4000/components/lookup/example-dblclick.html

**Comment by tmcconechy** [comment]
sorry @tjamesallen15 still dont think this is quite right. I think it should work two ways on this new example

a) you double click to insert
b) you click and it selects it -> then you can hit apply to insert

Also make sure http://localhost:4000/components/lookup/example-multiselect.html and http://localhost:4000/components/lookup/example-index.html are unaffected (doesn't seem to be but just for your testing)

**Comment by tjamesallen15** [comment]
Ready for review.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
