### PR TITLE
9004 - Selected tab in overflow menu change

### LINKED ISSUE #9004: Tabs: Header tabs in overflow get inserted into tab order, instead of scrolling the tab container
**Describe the bug**
A header tab in the overflow menu is inserted into the tab order, instead of scrolling. This is causing indexing issues when used in landmark UI, but it also easily seen in the controls.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
2. Click on the tab overflow dropdown, and select Header Tabs 18
3. See error. Header tab 18 gets inserted earlier in the tab order.
HeaderTabsIssue

**Expected behavior**
The tab contained should "scroll" over to the correct tab position. This was the behavior in version 4.95.5
HeaderTabsIssuePrevious

**Version**

- ids-enterprise: 4.99.0

**Platform**
 - Infor Application/Team Name: Landmark Web UI
 - All

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Removed previous behavior where selected tab in the overflow menu will be moved to the next visible space
- Added additional check on the isTabOverflowed method as the check didn't include overflow tabs on the left (which should update the overflow menu to include left overflow tabs now)

**Related github/jira issue (required)**:

Closes #9004 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/tabs-header/example-index.html
- Select a tab in the overflow menu
- Should scroll to that tab

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — DISMISSED** [review]
Looks good.

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected on my end. Tested in LTR and RTL.

https://github.com/user-attachments/assets/e33e9fe6-db90-4e91-bbf8-041e7da16ba2

**Review by tmcconechy — DISMISSED** [review]

**Comment by ericangeles** [comment]
I believe there will be some changes here, @tmcconechy @yohannahbautista. The same behavior in the WC that was discussed during the sprint planning.

**Review by tmcconechy — APPROVED** [review]

**Comment by yohannahbautista** [comment]
> I believe there will be some changes here, @tmcconechy @yohannahbautista. The same behavior in the WC that was discussed during the sprint planning.

@ericangeles It's already there, I think (the updating of overflow menu?)

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
image

**Pull request merged**
