### PR TITLE
6834 - datagrid filter row incorrect (2)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where dropdown filter does not render correctly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6834

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-multiple-grids-in-tab.html
- Click on `Top Bottom` tab
- From the bottom grid, click on Filter icon from the toolbar
- Click the dropdown for the Multiple Selection column

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Am still seeing the issue in Firefox @tjamesallen15

**Review by tmcconechy — DISMISSED** [review]

**Comment by tjamesallen15** [comment]
> Am still seeing the issue in Firefox @tjamesallen15

can't see it on my end, tried on mac and windows.

**Comment by tmcconechy** [comment]
I'm not seeing the issue on FF but when you select it does move as the grid adjusts. So thats not really an issue to me. But we could maybe fix it a bit by making the column a fixed size.

Also after i select the alignment is a little off in FF (but i would recheck chrome and FF for this)

Screen Shot 2022-09-28 at 12 39 34 PM

**Comment by ericangeles** [comment]
@tmcconechy yeah that's the thing that I am seeing. I believe that's the issue that was raised by the QA.

**Comment by tmcconechy** [comment]
Ok, So we are on the same page then...

a) try to set a column width and see if that fixes it moving when you select avalue
b) should also fix that alignment issue in the screen shot

**Review by tmcconechy — DISMISSED** [review]
Looks Good now!

**Comment by EdwardCoyle** [comment]
I noticed on the test page, after switching to the "top bottom" tab, when you click the top datagrid's filter button, no state changes happen on the top grid... is that expected on this sample?  http://localhost:4000/components/datagrid/test-multiple-grids-in-tab.html

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
