### PR TITLE
8611 - Add fix for error with no widgets

### LINKED ISSUE #8611: Homepage: Crashes after 4.94 update
**Describe the bug**
After updating to 4.94, the Homepage (Angular `soho-homepage`) crashes with an error:

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Fs.resize (global:scripts.js:216:1158595)
    at HTMLBodyElement.<anonymous> (global:scripts.js:216:1159609)
    at HTMLBodyElement.dispatch (global:scripts.js:2:40035)
    at v2.handle (global:scripts.js:2:38006)
    at Object.trigger (global:scripts.js:2:70124)
    at ce.fn.init.triggerHandler (global:scripts.js:2:70811)
    at global:scripts.js:216:16756
    at global:scripts.js:216:10715
    at timer (zone.js:2402:41)
    at _ZoneDelegate.invokeTask (zone.js:403:31)

After this, the Homepage no longer re-calculates the position/size of widgets when resized.

**To Reproduce**

Cannot reproduce exact issue in samples. Could be that the Homepage is initially empty? I.e no widgets.

A similar issue can be reproduced by:

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/homepage/test-add-remove-widget.html
2. Click "Remove Widget" until the last one is removed
3. See error in console

The difference might be that in our app, the Homepage is _initially_ empty, which causes more issues.

**Version**

- ids-enterprise: 4.94.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Additional context**
This line crashes (possibly because there are no Widgets when the Homepage is created?):
https://github.com/infor-design/enterprise/blob/4edb56906c0a88a62455212096b0de9636c02afd/src/components/homepage/homepage.js#L744

Possibly caused by this commit: https://github.com/infor-design/enterprise/commit/8dfa48a5e974bd257666922024b3491eee886c73

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

When home page has no widgets and you resize an error occured. This is a fix for this.

cc @anhallbe (does this need a patch on 4.94?)

**Related github/jira issue (required)**:
Fixes #8611 

**Steps necessary to review your pull request (required)**:
- retest https://github.com/infor-design/enterprise/pull/8544
- go to http://localhost:4000/components/homepage/test-add-remove-widget.html
- remove all widgets with the remove button
- check the console
- resize the page
- should be no errors with or without widgets

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by janahintal — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/ea710d2e-9910-4373-8d82-c2d59a1b90e0

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
image

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@tmcconechy this is a patch right?

**Comment by tmcconechy** [comment]
Yes But i patched it already @ericangeles

**Pull request merged**
