### PR TITLE
7801 - Updated hover color for breadcrumb in header

### LINKED ISSUE #7801: Header: breadcrumbs hover color is off
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-breadcrumbs.html#
2. Hover over the items
3. See error on last item` Level Two Detail View`

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
All major browsers
**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added additional selector for breadcrumb in header.

**Related github/jira issue (required)**:

Closes #7801 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/header/example-breadcrumbs.html
- Hover over breadcrumb items
- Hover color should not be dark

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good @yohannahbautista but can you fix a quick thing i see?

http://localhost:4000/components/header/example-breadcrumbs.html?theme=new&mode=dark&colors=default

- doesnt look too good. can you make the second header to be slate 07

Screenshot 2023-09-07 at 11 42 47 AM

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi team, noticed that the third breadcrumb link disappears when hovered in Alabaster
Video: https://app.screencast.com/vjgI1elbSNmId

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The bug still exists in Alabaster.


https://github.com/infor-design/enterprise/assets/102151352/c6c8fa2b-001a-4af4-aec1-6567f9fd63dd

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in alabaster. 
image
Note: Light/High contrast only. Dark mode is working fine

**Review by tjamesallen15 — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
