### PR TITLE
5438 - Fix on overlap in today text and calendar view changer

### LINKED ISSUE #5438: Calendar: Month” dropdown is overlapping with “Today” on mobile
**Describe the bug**
Month” dropdown is overlapping with “Today” on mobile 

**To Reproduce**

1. Go to 'url: https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Noticed that “Month” dropdown is overlapping with “Today” on mobile & responsive view below 385x780
4. Please see screen shots attached. 
5. Please reference ticket: https://github.com/infor-design/enterprise/issues/5245

**Expected behavior**
The Month” dropdown  should not be overlapping with “Today” on mobile & responsive view below 385x780

**Version**

- ids-enterprise: [v4.54]

**Screenshots**
Iphone Image 2
Iphone Image 1

**Platform**
 - Device: (if applicable) [e.g. iPhone 12 and all older versions]

**Additional context**
None

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Width of view changer and position of today text will update based on screen size.

**Related github/jira issue (required)**:

Closes #5438 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/calendar/example-index.html
- Switch to mobile

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I think on some smaller phones this doesnt look quite right. See Iphone X

Screen Shot 2021-08-17 at 10 19 32 AM

For a different fix maybe we can make the today link hide on smallest breakpoints with a media query. This should be acceptable

**Comment by yohannahbautista** [comment]
> I think on some smaller phones this doesnt look quite right. See Iphone X
> 
> Screen Shot 2021-08-17 at 10 19 32 AM
> 
> For a different fix maybe we can make the today link hide on smallest breakpoints with a media query. This should be acceptable

Hello, I tried aligning it a bit better, tell me if it looks okay, if not I'll hide the today link instead

**Comment by tmcconechy** [comment]
Screen Shot 2021-08-18 at 9 18 51 AM

Still not loving how its alligned. I think i can see two options

1) Change the month to abbreviatd when its this size https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/en-US.js#L40 
2) Hide the today (easier) as they can still access today in the calendar

**Review by tmcconechy — APPROVED** [review]
Ok nice i think that looks great 👍🏻

**Review by ericangeles — APPROVED** [review]
🍌

**Pull request merged**
