### PR TITLE
3666 - Update the design of  widget counts in uplift

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Implementing the new design for widget count in uplift. I've also tweaked some positions in non uplift.

This is not limiting to the four colors that was in the design, we can use all the color palettes that we have, even adding other colors in the future. 

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/3666

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Navigate to http://localhost:4000/components/counts/example-widget-count.html?theme=uplift&variant=light&colors=0066D4
- Compare it to the old design in uplift https://master-enterprise.demo.design.infor.com/components/counts/example-widget-count.html?colors=0066D4
- Should show the new design for uplift
- Also check the non uplift, made some adjustments
- Test this to all variants

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Calling this WIP as it needs a few more things.

**Comment by ericangeles** [comment]
@tmcconechy you can take a look now. The CI will probably failed because of baseline image. But will fix it after.

**Comment by tmcconechy** [comment]
Looking great. Maybe just two things now

1) On the 4th example: User example let's change the alert to another icon (like success)
2) On the 3rd example: Can we show icons on all 4 (error, orange alert, yellow alert , info?)
3) Can we add two more with six , two, three ect and see if they work ok?

**Comment by tmcconechy** [comment]
Looks like you got it all covered now 😄  Maybe just fix the test and we call it done.
If you want to perhaps some of these can go on seperate test pages. And fix the test that way. Up to you either way.

**Comment by ericangeles** [comment]
@tmcconechy this should be good to go now. ☕

**Pull request merged**
