### PR TITLE
2318 - Improve Uplift theme

### LINKED ISSUE #2318: Uplift: Fallout from last minute design changes
**Describe the bug**
Testing each component A-Z and reporting some issues. Listed in short form. We will divide these up.

**To Reproduce**
Continued list from https://github.com/infor-design/enterprise/issues/2318:

- [x] [Cards Example](http://localhost:4000/components/cards/example-group-action.html?theme=uplift) - the secondary toolbar needs work
- [x] [Colorpicker Example](http://localhost:4000/components/colorpicker/example-index.html?theme=uplift) - arrow is missing the border 
- [x] [Contextmenu Example](http://localhost:4000/components/contextmenu/example-index.html?theme=uplift) - icons not centered in the menu
- [x] [Header Example](http://localhost:4000/components/header/test-header-gauntlet.html?theme=uplift) -Misalignment on text and checkbox, text is a bit too low.
- [x] [Editor Example](http://localhost:4000/components/components/editor/example-index.html?theme=uplift&variant=dark) - In Edge the H3 and H4 icons are cut off
- [x] [Favorite Example](http://localhost:4000/components/favorites/example-index.html?theme=uplift) - Focus state is out of alignment
- [x] [Fileupload Example](http://localhost:4000/components/fileupload-advanced/example-index.html?theme=uplift) - Upload a file and look at the X icon , its misaligned
- [x] [Masthead](http://localhost:4000/components/masthead/example-index.html?theme=uplift) - Title text is a little close
- [x] [Message](http://localhost:4000/components/message/example-index.html
) - Click success button on IE edge and a tiny scroll bar is visible
- [x] [Multiselect](http://localhost:4000/components/multiselect/example-placeholder.html?theme=uplift) - The placeholder is the same color
- [x] [Paging Example](http://localhost:4000/components/blockgrid/example-paging.html?theme=uplift)- pager buttons not aligned in chrome and a little low
- [x] [Popdown](http://localhost:4000/components/popdown/example-index.html?theme=uplift) - the icon is not aligned with the text. Also when opening the top of the popdown shows an extra bordered edge on the top.
- [x] [Popover](http://localhost:4000/components/popover/example-alternate-positions.html?theme=uplift) - button appears outside the popup
- [x] [Radar](http://localhost:4000/components/radar/example-index.html?theme=uplift) - Text is smaller and very hard to read
- [x] [Searchfield](http://localhost:4000/components/searchfield/example-no-all-results-link.html?theme=uplift) - Is the x big?
- [x] [Slider](http://localhost:4000/components/slider/example-index.html?theme=uplift) - The bar is a little too dark
- [x] [Swaplist](http://localhost:4000/components/swaplist/example-index.html?theme=uplift) - Drag handle is very large
- [x] [Masthead](http://localhost:4000/components/masthead/example-index.html?theme=uplift) - make uplift masthead 313236 for back color (slate 08) and make the title 1.4rem (14px)
- [ ] [Tree](http://localhost:4000/components/tree/example-index.html?theme=uplift) - the icons for just a generic node i dont think are right liike like radios

**Version**

- ids-enterprise: v4.19.0

**Screenshots**
n/a

**Platform**
- all

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR makes many minor changes to icon/text alignments, padding, margins, font-size, and other small details to refine the aesthetic of the Uplift theme.  The full list of items addressed are in the checkbox list on #2318 

**Related github/jira issue (required)**:
Closes #2318 

**Steps necessary to review your pull request (required)**:
See the checklist on #2318 to review each item for accuracy.  Additionally, all visual regression tests should pass.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Need to update several baseline images on the CI:
- [ ] [Circle Pager](http://localhost:4000/components/circlepager/example-index)
- [ ] [Counts](http://localhost:4000/components/counts/example-index)
- [ ] [Datagrid on Modals](http://localhost:4000/components/datagrid/test-modal-datagrid-single-column)
- [ ] [Datagrid (standard)](http://localhost:4000/components/datagrid/test-paging-select-indeterminate-multiple)
- [ ] [Datagrid (Targeted Achievement](http://localhost:4000/components/datagrid/test-targeted-achievement)
- [ ] [Listview Single Select](http://localhost:4000/components/listview/example-singleselect)
- [ ] [Listview Multi Select](http://localhost:4000/components/listview/example-multiselect)
- [ ] [Pager (List Detail, No Page Size Selector)](http://localhost:4000/patterns/list-detail-paging)
- [ ] [Pager (List Detail, With Page Size Selector)](http://localhost:4000/patterns/list-detail-paging-pagesize-selector)
- [ ] [Searchfield](http://localhost:4000/components/searchfield/example-index)
- [ ] [Flex Toolbar (AJAX)](http://localhost:4000/components/toolbar-flex/example-more-actions-ajax)

Most of the differences are in the Pager layout... some are button icons being slightly off

**Comment by EdwardCoyle** [comment]
@tmcconechy about your comments here:

> http://localhost:4000/components/cards/example-group-action.html?theme=uplift i think maybe we need a top border (tried a background but it didnt look good).

I didn't see the original card designs so I'm not sure what to do here... @nickwynja any opinions?

> http://localhost:4000/components/fileupload-advanced/example-index.html?theme=uplift
> uplift a smaller file and wait until it completes -> the completed icon is also misaligned

Just fixed that one in the last push

> http://localhost:4000/components/blockgrid/example-paging.html?theme=uplift
> It was like this but how come the first and last pager icons are disabled? 

We can open a separate issue for that... I was wondering about that too but it's out of scope for fixing Uplift styles.

**Comment by tmcconechy** [comment]
1) its like this http://localhost:4000/components/cards/example-group-action.html so the group action has a color seperation. So was thinking either a color (which looked bad) or a border
2) Cool
3) Ok sounds good..

**Comment by nickwynja** [comment]
> > http://localhost:4000/components/cards/example-group-action.html?theme=uplift i think maybe we need a top border (tried a background but it didnt look good).
> 
> I didn't see the original card designs so I'm not sure what to do here... @nickwynja any opinions?

This update was done adhoc without a design. The design intent was to remove unnecessary bounding boxes but I do agree that it's helpful in this case. I think a `border-top` should go on `.card-group-action` rather than  reintroduce a border to the card header.

**Comment by EdwardCoyle** [comment]
Just pushed the changes for the top border.  I've also raised #2522 for the pager button issue.

**Pull request merged**
