### PR TITLE
1910 - Datepicker RTL next and prev buttons

### LINKED ISSUE #1910: RTL: Datepicker wrong direction of Next/Prev buttons
**Describe the bug**
When using Datepicker in RTL, the Next/Prev buttons that change the months are directing to the wrong month when clicked. 
The layout on the screen is OK, but when a user wants to go to the next month, he clicks on the **left** button, and for the previous month he clicks on the **right** button. But he gets the exact opposite response. 

**To Reproduce**
1. Go to [Hebrew datepicker](https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?locale=he-IL)
2. Click on 'Calendar Icon'
3. The month now is April (אפריל)
3. Click on the Left button 
4. It goes to March (מרץ ) instead of May (מאי)

(I don't know if there is an English RTL locale for easier testing)

**Expected behavior**
In RTL - Left arrow =Next and Right arrow=Prev
In LTR - Left arrow =Prev and Right arrow=Next

**Version**

- ids-enterprise: ALL

**Screenshots**

**Platform**
 - OS Version: Windows 7
 - Browser Name Chrome
 - Browser Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
Thanks!

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Next and prev buttons in RTL remained in place instead of switching locations

**Related github/jira issue (required)**:
Closes #1910.

**Steps necessary to review your pull request (required)**:
- Pull branch, run app
- Visit http://localhost:4000/components/datepicker/example-index
  - Open Elements pane of Dev Tools
    - add `dir="rtl"` to `<html>` tag
    - ensure next and prev buttons operate as you would expect for `right-to-left` (prev on right, next on left)
- Visit http://localhost:4000/components/monthview/example-index
  - Ensure this view also performs as expected following the instructions for the above datagrid URL

**Included in this PR:**
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Everything looks great on the Monthview.  The `example-index` Datagrid sample doesn't have datepickers, but I found this one (http://localhost:4000/components/datagrid/test-editable-datetime.html) and it seems the buttons and the header aren't exactly in line when you make the switch to RTL:

Screen Shot 2019-05-06 at 5 02 17 PM

**Comment by davidcarlsonberg** [comment]
@EdwardCoyle I've updated the URLs in the description to accurately reflect what I was referring to. Thanks for pointing that out.

**Comment by tmcconechy** [comment]
Seems like the fix is right but i would note to go back to https://github.com/infor-design/enterprise/issues/1910 and test those steps as it explains the hebrew text. (and works!)

**Comment by davidcarlsonberg** [comment]
Confirmed it works on reproduction of the steps in the original issue.

**Comment by deep7102** [comment]
Hi @davidcarlsonberg I saw too, as @EdwardCoyle point out the cell content moves to right soon calendar popup open.
http://localhost:4000/components/datagrid/test-editable-datetime.html?locale=he-IL

**Comment by davidcarlsonberg** [comment]
@deep7102 I'm not sure what you mean?

**Comment by deep7102** [comment]
@davidcarlsonberg 
http://localhost:4000/components/datagrid/test-editable-datetime.html?locale=he-IL
- Open above link
- In 1st-row 3rd-column
- Keep watching the content alignment
- Hover and click on calendar icon in this cell to open calendar popup
- See the content alignment shifted towards to right
- Close the popup
- See the content alignment shifted towards to left again

**Comment by davidcarlsonberg** [comment]
> @davidcarlsonberg
> http://localhost:4000/components/datagrid/test-editable-datetime.html?locale=he-IL
> 
> * Open above link
> * In 1st-row 3rd-column
> * Keep watching the content alignment
> * Hover and click on calendar icon in this cell to open calendar popup
> * See the content alignment shifted towards to right (all the text inside this cell)
> * Close the popup
> * See the content alignment shifted towards to left again (all the text inside this cell)

I see it, finally. This is an unrelated issue. I'll make a ticket for it.

**Pull request merged**
