### PR TITLE
7302 - Colors should remain the same when changing theme colors

### LINKED ISSUE #7302: Application Menu: is-personalizable class turns app menu the current theme color
**Describe the bug**
I wanted to check if this is a bug or if this is working as designed.

When the app menu has the "is-personalizable" class and the page is loaded without any customizations to the theme, the menu is the standard color. Then when a theme is applied the app menu becomes the selected theme color.

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/test-six-levels.html
2. Note that the app menu is the standard menu color
3. Select a color from the theme menu
4. See that the app menu has changed to the selected color
5. Change to the classic theme
6. Note that the app menu is back to the standard color even with a color applied to the theme.

**Expected behavior**
If this is not working as designed, it is expected that the app menu stays the standard menu color when different colors are selected for the theme.

**Version**
- ids-enterprise: v4.81.0-dev

**Screenshots**
New theme:
image

Classic theme:
image

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version:  110.0.5481.178 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed personalize styles for appmenu

**Related github/jira issue (required)**:

Closes #7302 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: 
   - http://localhost:4000/components/applicationmenu/test-six-levels.html
   - http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html
   - http://localhost:4000/components/applicationmenu/example-personalized-roles.html
   - http://localhost:4000/components/applicationmenu/example-personalized.html
   - http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html
- Check all modes/versions/color:
   - Open appmenu and levels
   - Colors should remain the same

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista its also doing it on http://localhost:4000/components/applicationmenu/example-personalized-roles.html?colors=7928E1 and possibly other examples. Can you check all the app menu examples.

Also can you update the docs and remove app menu from mentions here https://github.com/infor-design/enterprise/blob/main/src/components/personalize/readme.md#supported-personalization-components

We probably want to make sure `is-personalizable` from `application-menu` classes for the examples. But we also want to make sure it has no effect first (so maybe leave it in one example for testing).

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
Think this is ready for qa @CindyMercadoReyes @jbrcna @janahintal

**Comment by tmcconechy** [comment]
cc @s-werking for review

**Comment by s-werking** [comment]
When changing colors in a classic theme, are we expecting the selected app menu item to be a grey color regardless of the color choice (like the new theme) or would the selected item's color change based on the theme color? Right now the selected item remains the azure color when the theme color changes.

**Comment by tmcconechy** [comment]
@s-werking we dont have a design for that and we didnt touch classic. I can check but i think this ok.
@hey-yall - think we can get some quick feedback

Screenshot 2023-04-13 at 12 04 24 PM

**Comment by tmcconechy** [comment]
@yohannahbautista lets make the selection color either slate-70 for now in classic instead of azure. 
We made a design issue https://jira.infor.com/browse/IDS-1040 and will adjust if they come back with a better suggestion

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista when i look it looks a little light in classic light mode. i.e. seems to be 414247 not 56565B (slate 70)

Also can you fix classic - contrast mode as its showing the color. (dark contrast looks ok)

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista i see one issue 

- in classic mode / light http://localhost:4000/components/applicationmenu/example-index.html?theme=classic&mode=light&colors=default i cant see the selected state
Screenshot 2023-04-17 at 10 43 36 AM
- in dark and contrast mode (contrast is a little better) the focus state could be improved. I would make it the lightest slate color for a border

Screenshot 2023-04-17 at 10 43 28 AM

**Review by jbrcna — COMMENTED** [review]
Please see my findings below:


---------------------------------------------
http://localhost:4000/components/applicationmenu/test-six-levels.html?theme=classic&mode=light&colors=ffffff – the dash changes color with alabaster in Classic Theme
`Ligh | High Contrast using Alabaster `
image



http://localhost:4000/components/applicationmenu/test-six-levels.html - Outline changes color when you switch colors.
image

http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=new&mode=contrast&colors=ffffff – Box has no outline (white) with **alabaster** when clicked. However, when using **Classic Theme**, Box has no outline (white) with **alabaster** & **default** color.
`Light | High Contrast
`
image


http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=new&mode=light&colors=default – When using Light – New Theme with Default color. the outline turns azure when item is clicked. (With other colors but alabaster the outline is white)
image

**Review by glenlieorillo — COMMENTED** [review]
http://localhost:4000/components/applicationmenu/test-six-levels.html
**Bullet point is not visible in Alabaster**


https://user-images.githubusercontent.com/102151352/232765956-e81658ef-9c13-4ba6-8c6d-55dfa3eecdd3.mov

http://localhost:4000/components/applicationmenu/example-personalized.html
**The shape of the highlight in Light Mode is differ from Dark and High Contrast Mode**

_Light_
image

_Dark_
image

_High Contrast_
image

http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html
**The shape of the highlight in Light Mode is differ from Dark and High Contrast Mode**

_Light_
image

_Dark_
image

_High Contrast_
image

**Review by tmcconechy — APPROVED** [review]
This looks good to me. @glenlieorillo i see your screen shots but that shouldnt be possible because the colors do not change now. Maybe you are looking at the wrong branch?

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@glenlieorillo i didnt see your issue. But if you still see it on main please make a seperate issue for it.

**Pull request merged**
