### PR TITLE
7824- Weekview add event modal

### LINKED ISSUE #7824: WeekView: Add ability to add events with modal
**Describe the bug**
The modal dialog only displays in the Month view

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/calendar/example-index?theme=uplift&variant=light'
2. Double Click on a day within the calendar when in month view
3. Close the dialog
4. Change the view to week
5. Double click on a time within any day
6. Nothing happens

**Expected behavior**
The same dialog will open allowing the user to add an event.

**Version**
- ids-enterprise: v4.85.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: Pathway
 - OS Version: Windows 10
 - Browser Name: [e.g. chrome, safari, stock browser]

**Additional context**
The calendar can contain multiple events during the day and the week/day view would be used to schedule events based on available time within that day. Easier to look at another view to see what times are available and then add a new event via the dialog.

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added event modal for weekview

**Related github/jira issue (required)**:

Closes #7824 
Event modal for weekview

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/calendar/example-index
- Change the view to week
- Double click on a time within any day

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — DISMISSED** [review]

**Review by jbrcna — DISMISSED** [review]
image
image

**Review by glenlieorillo — DISMISSED** [review]
https://github.com/infor-design/enterprise/assets/102151352/f5b9ca0a-4e4d-45d3-b796-7b5a092232dc

**Review by janahintal — APPROVED** [review]
Approving verified working as expected in [7824-weekview-add-event](https://7824-weekview-add-event-enterprise.demo.design.infor.com/components/calendar/example-index)](https://7824-weekview-add-event-enterprise.demo.design.infor.com/components/calendar/example-index)

**Review by tmcconechy — COMMENTED** [review]
The only thing i would suggest is when you click on a time it should show that time in the popup and unclear "All Day". If you click in the "All Day" section it can check the all day event.

(More time based so that would work better for week view). But otherwise this looks nice :)

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/9e32b2bc-f968-4903-adbb-5e3db658735f

**Review by janahintal — APPROVED** [review]
Approving 
https://www.loom.com/share/36b8b8d1db284ca2acc0209a933a6455?sid=61da7bf3-2f5b-4bf6-90e7-05bafa7d1978

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
