### PR TITLE
8166 - ActionPanel: fixed layout for CAP close button in RTL

### PR DESCRIPTION
**Pull request by max-hizon**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This pull request will fix the alignment issue of the close button of the contextual action panel in RTL

**Related github/jira issue (required)**:
Closes: https://github.com/infor-design/enterprise/issues/8166

**Steps necessary to review your pull request (required)**:
1. Go to http://localhost:4000/components/contextualactionpanel/example-index.html?locale=ar-EG
2. Open the contextual action panel button
3. See that the close button is now aligned

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Looks good but make sure to learn about https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start

You could use margin-inline-start and margin-inline-end and it works without a special RTL rule 👍🏻

**Review by yohannahbautista — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Fix has been already applied but this looks off to me.

image

image

**Comment by tmcconechy** [comment]
Ok can you have a look @max-hizon i marked as failed/wip. Looks like something we could fix. When you do maybe try my suggestion of if needed https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start

Thank You!

**Comment by max-hizon** [comment]
@tmcconechy made the fix using your suggestion. It should be much better now. Thanks!

**Review by ericangeles — APPROVED** [review]
Looks good! 🍌

**Review by glenlieorillo — APPROVED** [review]
image

**Review by jbrcna — APPROVED** [review]
image

**Pull request merged**
