### PR TITLE
7955 - Tabs Radios Overflow

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the focus state of radio button not fully shown in tabs.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7955

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs/example-enable-disable-individual-tabs.html
- Click one radio button
- Press arrow down or up (depending on what you radio button clicked)
- See the focus

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/6d6fb967-8025-407c-8fdd-a083b3f556af

Safari
image

Firefox
image

Edge
image

iOS
image

Android
image

**Review by max-hizon — CHANGES_REQUESTED** [review]
Button is still cropped on focus state (less cropped than before)
Before
image

After
image

To reproduce:
1. Click 'Primary Button'
2. Tab out of the window
3. Tab back into window
4. See error

*Note: not sure if this is within scope of the PR but is part of issue #7955

**Comment by ericangeles** [comment]
Good catch, @max-hizon. Can you verify it @tjamesallen15 ?

**Review by jbrcna — APPROVED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 can you fix the button too its noted on https://jira.infor.com/browse/IDS-1698 as well. Thanks!

**Review by janahintal — APPROVED** [review]
Working as expected in https://7955-tabs-radio-overflow-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs.html

**Comment by tjamesallen15** [comment]
Will do @ericangeles @tmcconechy

**Review by yohannahbautista — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
All issues resolved

**Pull request merged**
