### PR TITLE
2825 - Use position sticky for datagrid

### LINKED ISSUE #605: Datagrid - fit last column during resize
**Is your feature request related to a problem? Please describe.**

Discussed with landmark and on chat several times. 
**Describe the solution you'd like**

Teams would like an option similar to "fit" on this example:

https://www.jqueryscript.net/demo/jQuery-Plugin-For-Draggable-Resizable-Table-Columns-colResizable/
See also 
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnResizing/jQuery/Light/

Keep the existing method (similar to flex in the example)
**Additional context**

- landmark
- teams (marek and victor)

### LINKED ISSUE #1671: Datagrid: Blank area on the right side of the grid appears after resizing a column
**Describe the bug**
A blank area appears on the right side of the grid after resizing a column to smaller size.

**To Reproduce**
1. Go to http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Drag the right border of Order Date column to left to resize to smaller size
3. See issue: A blank area appears next to the Phone column

**Expected behavior**
There should be no blank area in the datagrid when you resize a column

**Version**
- ids-enterprise: v4.6.0 - v4.16.0-beta0

**Screenshots**
datagrid_blankarea

**Platform**
 - All Devices, OS and Browsers

**Additional context**
No additional context.

### LINKED ISSUE #1818: Datagrid: Column size issues
Describe the bug
A datagrid is sizing the last column to wide.  Getting lots of push back in Landmark that the columns are not sized correctly.  The last column (typically contains the least significant information) is sized much larger than the preceding columns. 

To Reproduce
1. Using the attached example-column-sizing.html
2. Notice the size of the last column that contains a drop-down select

Expected behavior
Improve the layout of the column sizes

Is related to:
https://github.com/infor-design/enterprise/issues/1168

### LINKED ISSUE #2224: Datagrid: Group header appears too large in iOS devices
**Describe the bug**
Datagrid: Group header appears too large in iOS devices

**To Reproduce**

1. Using iOS device, Open browser Safari or Google
2. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html

**Expected behavior**
Header

**Version**
v4.14.0 or v4.19.0

**Screenshots**
Group header text should not appear too large in Devices

**Platform**
iOS 12
iPhone X Max

**Additional context**
No any other Additional context about the problem here.

### LINKED ISSUE #2363: Datagrid: Cannot scroll horizontally when no data is shown
**Describe the bug**

**To Reproduce**
1. Go to http://4190-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Resize the page to smaller size
3. Type "testfilter" in the Product Name filter field
4. No Data Available message will be shown
5. Try to scroll horizontally, see issue: datagrid will not scroll

**Expected behavior**
Datagrid should be scrolled horizontally when No Data 

**Version**
- ids-enterprise: v4.17.0 to v4.19.0-rc0

**Screenshots**
No applicable screenshot.

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

### LINKED ISSUE #2825: Datagrid: Use position sticky for frozen header
**Is your feature request related to a problem? Please describe.**

Working on weekview `position: sticky` worked out well. See if i can use this on datagrid as well. This will help with accessibility and prevent mismatched columns.

**Describe the solution you'd like**

- [x] Remove the use of two tables for sticky header
- [x] Make sure we dont need to break table layouts
- [x] Test all column width settings

**Describe alternatives you've considered**
Keep current solution

**Additional context**
https://codepen.io/chriscoyier/pen/PrJdxb
http://localhost:4000/components/week-view/example-index.html (currently on a branch)

### LINKED ISSUE #2835: Datagrid: misalligned headers and rows
**Describe the bug**
The vertical lines dividing columns are misalligned in header row and result rows when vertical scroll appears

**To Reproduce**
1. I've reproduced in ng demo app
2. Go to Datagrid - Fixed header
3. Select 10 or 5 records per page
4. Be sure that all rows are visible so there is no vertical scrollbar in grid
5. Now change the window size, so the vertical scrollbar appears.
6. Observe, that you can go a bit further to the right now (width of scrollbar)

**Expected behavior**
All lines should be aligned correctly

**Version**

- ids-enterprise: 4.22.0
- ids-enterprise-ng: 6.1.0
- windows only?

**Screenshots**
image

### LINKED ISSUE #2864: DataGrid: Missing horizontal scrollbar when filter is applied
**Describe the bug**
When the datagrid is wider and horizontal scrollbar is present and you apply the filter, the scrollbar disappears. Issue when you filtered out columns hidden right

**To Reproduce**
1. update fixed header demo page, so the filtering is enabled (delete `disableClientFilter: true`)
2. Open app, make window smaller so the horizontal scrollbar appears
3. scroll to the right and filter out something so `No Data Available` appears
4. See that the scrollbar is lost and you are moved to left, so you cant easily navigate to clear/modify the filter field

**Expected behavior**
Scrollbar should stay there so the user is able to navigate there via mouse.
Or keep the header on the same place so the used filter field is on the screen.

**Version**
- ids-enterprise-ng: 6.0.0

**Screenshots**
image

**Additional context**
Still possible to reach the field by tab key, but when you delete the filter the grid is not alligned (unless you do some horizotnal scrolling)
image

### LINKED ISSUE #3175: Datagrid: Personalized column modal window was not centered on IE11
**Describe the bug**
modal window of 'Personalize Column' was not centered

**To Reproduce**
1. Open IE 11 and Navigate to http://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Click on toolbar button `....`
3. Click on `Personalize Columns`

**Expected behavior**
modal window should be centered

**Version**
master-enterprise

**Screenshots**
image

**Platform**
IE11

**Additional context**
On first load not all toolbar options were shown (maybe this is just a timing issue)
image

### LINKED ISSUE #3193: Datagrid: Focus is cut off after resizing the window from responsive view to full view
**Describe the bug**
Datagrid: Focus is cut off after resizing the window from responsive view to full view

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-single-column.html?theme=uplift&variant=dark
2.  Minimize the screen to responsive view
3.  Click and focus on "Some Compressor" product name 
 - Notice that the focus is full an not cut off
4. Maximize the window to full view (While the focus on responsive view is still active)

**Expected behavior**
Focus should be responsive 

**Version**
Beta 4.24 

**Screenshots**
1. Responsive view 
image

2. Full view after maximizing the window
image

**Platform**
All Browser & OS

**Additional context**
NA

### LINKED ISSUE #3207: Hyperlinks in DataGrid still causes redirection, even when href is '#'
**Describe the bug**
Redirects in grids still occur when clicking a hyperlink in a grid cell, even though they should be prevented if the href is '#'.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dynamic-links.html
2. Click on a hyperlink within the Grid
3. URL in address bar changes to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dynamic-links.html#

**Expected behavior**
The URL in address bar should not change

**Version**
Found in v4.19.4. and also observed in 4.23.0

**Screenshots**
N/A

**Platform**
 - Device: Desktop PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:  78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Attempting to use this in a dialog to navigate a folder structure. Because it redirects, clicking on any link causes the dialog to be dismissed and go to the redirected URL.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changed the way tables are rendered to avoid gaps at the end of the grid and fix the sizes so they work in resize. This is done by using css position: sticky for headers. It has a few consequences. The spaceColumn option which was never completed was removed. The stretchColumn option is still working but is less important now and defaults to no stretch. IE 11 will now no longer support sticky headers because it does not support css position sticky, so it will degrade in functionality. This improves all issues with columns getting out of alignment.

Test as many datagrid examples as you can handle.

**Related github/jira issue (required)**:
Fixes #2825
Fixes #3175
Fixes #2835
Fixes #2363
Fixes #2864
Fixes #2224
Fixes #3193
Fixes #1818
Fixes #3207
Fixes #605
Fixes #1671 

**Steps necessary to review your pull request (required)**:
**2825**
* http://localhost:4000/components/datagrid/example-fixed-header.html - will still scroll - test this on all browsers we support
* http://localhost:4000/components/datagrid/test-horizontal-scroll.html is a good test page for all scenarios (chrome desktop is fine)
* http://localhost:4000/components/datagrid/list - test all examples with Test Column -  (chrome desktop is fine)

**3175**
* open http://localhost:4000/components/datagrid/example-export-from-button.html in IE 11
* from the .. menu on the right above the grid, select personalise columns
* this should be centered
* also now loading the items quicker on beforeLoad so there is no FOUC

**2835**
* test this on windows or with visible scroll bars
* go to http://localhost:4000/components/datagrid/test-fixed-header-filter.html
* select 5 records
* resize the page so that a vertical scroll appears
* in all cases lines should align (they may size adjust a bit on resize) 

**2363**
* go to http://localhost:4000/components/datagrid/example-filter.html
* filter on something that doesn’t exist so that the empty message is shown
* should be able to scrolll still horizontally (this example has a frozen column

**2864**
* go to  http://localhost:4000/components/datagrid/test-fixed-header-filter.html
* filter on any condition that doesn’t exist so that the empty message is shown
* should be able to scrolll still horizontally (this example has a frozen column

**2224**
* go to http://localhost:4000/components/datagrid/example-grouping.html in IOS
* group text should be a normal (not huge) size

**3193**
* go to http://localhost:4000/components/datagrid/test-editable-single-column.html
* click in any row to edit
* resize the page either smaller or bigger (the editor should be same size as the cell during that resize

**1818**
* go to http://localhost:4000/components/datagrid/test-column-sizing.html
* the last column should no longer stretch
* resizing the page should still fill

**3207**
* go to http://localhost:4000/components/datagrid/test-dynamic-links.html
* click any link in the first column
* URL should NOT change to a # at the end

**605**
* go to http://localhost:4000/components/datagrid/example-index
* resize any column
* note that the adjacent column is also moved
* last and first column cannot be resizes

**1671**
* go to http://localhost:4000/components/datagrid/example-index
* Drag the right border of Order Date column to left to resize to smaller size
* A blank area no longer appears
* Try sorting after resize

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Saw this while testing #3175 (http://localhost:4000/components/datagrid/example-export-from-button.html) on IE11/Browserstack:

Screen Shot 2019-12-10 at 12 03 57 PM

**Comment by EdwardCoyle** [comment]
Testing #2363 (http://localhost:4000/components/datagrid/example-filter.html) - Something strange going on with the column sizing when changing the filter term:

Untitled_-Dec-10-2019-12_06-PM

**Comment by EdwardCoyle** [comment]
While testing #1818 (http://localhost:4000/components/datagrid/test-column-sizing.html), I saw this, but I'm not sure if it's a "deal breaker"... more like a minor interaction bug.  The column edges don't really stay aligned with the mouse cursor while dragging, and tend to jump way ahead/behind it:

Untitled_-Dec-10-2019-12_14-PM

**Comment by deep7102** [comment]
I just found only here as:
http://localhost:4000/components/datagrid/example-export-from-button.html
ie11 - personalize window see two scroll bars

image

**Comment by deep7102** [comment]
This one did not following the steps are those, those selected rows re looks single select only
```

    load this branch on an NG branch off master
    go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader
    select 5 records
    resize the page so that a vertical scroll appears
    in all cases lines should align (they may size adjust a bit on resize)
```

**Comment by tmcconechy** [comment]
@deep7102 i clarified those steps

**Comment by tmcconechy** [comment]
All comments are now fixed but https://github.com/infor-design/enterprise/pull/3224#issuecomment-564134049 could not find a fix for that so punting

**Pull request merged**
