### PR TITLE
8274 - Fixed size in close button of tab list

### LINKED ISSUE #8274: Tabs: 'x' button size appears to be too small
**Describe the bug**
Tabs: 'x' button size appears to be too small 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-dismissible-tabs.html?theme=new&mode=contrast&colors=default 
2. Minimize to responsive view 
3. Open the dropdown

**Expected behavior**
'x' button size should look normal

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed size in close button of tab list

**Related github/jira issue (required)**:

Closes #8274 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/tabs/example-dismissible-tabs.html
- Minimize until more menu button appears
- Open menu
- Hover over an item
- X should not be tiny

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista super duper minor but it could be more centered vertically
Screenshot 2024-01-04 at 9 42 46 AM

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
This is now working as expected. However, I also noticed the alignment issue that @tmcconechy mentioned above.

image

https://github.com/infor-design/enterprise/assets/102151352/93ed8b93-caf6-489c-b4e2-330505ae7b56

**Review by jbrcna — DISMISSED** [review]
image

image

**Comment by tjamesallen15** [comment]
@yohannahbautista could you create a 4.92 changelog section and add this one. Thanks.

**Comment by ericangeles** [comment]
Everything looks good to me, @yohannahbautista, except for the changelog that James mentioned.

**Review by tjamesallen15 — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
