### PR TITLE
8913 - Fix switch layout issue in Datagrid Personalization

### LINKED ISSUE #8913: Datagrid: Switch in personalization dialog is misaligned
**Describe the bug**
A change made misaligned the switch

**To Reproduce**

1. Go to  https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html
3. See error

**Expected behavior**
Switch as in the switch component

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Recent fixes broke the layout of the switch in the personalization dialog.

**Related github/jira issue (required)**:
Fixes #8913 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/example-index.html
- click ...
- open personalization and review the switch styles 

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — APPROVED** [review]
image

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

http://localhost:4000/components/datagrid/example-index.html
image

http://localhost:4000/components/datagrid/example-reorder.html
image

**Review by glenlieorillo — COMMENTED** [review]
Switch is now working as expected. However, it seems that the `drag icon` is not working.

https://github.com/user-attachments/assets/36e71f4f-2a9a-4bf0-a7a0-54b30cab07df

image

**Comment by glenlieorillo** [comment]
> @glenlieorillo can you make a new issue for that problem? I only fixed css here so wasnt this fix. And im not following the steps exactly.

Alright, @tmcconechy. I created an issue for this bug, please see for reference: https://github.com/infor-design/enterprise/issues/8920

**Pull request merged**
