### PR TITLE
5258 - Update the tab counts design for translation requirements

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates the design of tab counts to comply with the translation requirements.

The position of the counts will depend on the current locale. Also, the counts in spillover will be removed.

Top position counts will only work on
- English locales `en-US`
- Chinese Simplified `zh-CN`, `zh-Hans`
- Chinese Traditional `zh-tw`, `zh-Hant`
- German `de-DE`
- Japanese `ja-JP`

The rest will work on the bottom position.

It also has the ability to set it via the settings `countsPosition` (top & bottom only).

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5258

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Top Counts Position
- Go to http://localhost:4000/components/tabs/example-counts.html for English
- http://localhost:4000/components/tabs/example-counts.html?locale=de-DE for German
- http://localhost:4000/components/tabs/example-counts.html?locale=zh-CN for Chinese simplified
- http://localhost:4000/components/tabs/example-counts.html?locale=zh-Hans for Chinese simplified
- http://localhost:4000/components/tabs/example-counts.html?locale=zh-TW for Chinese traditional
- http://localhost:4000/components/tabs/example-counts.html?locale=zh-Hant for Chinese traditional
- Counts should be positioned at the top
- Resize the page to show the spillover popupmenu
- Counts should not be visible in spillover

2.) Bottom Counts Position
- Go to http://localhost:4000/components/tabs/example-counts.html?locale=pt-PT
- http://localhost:4000/components/tabs/example-counts.html?locale=ar-EG
- http://localhost:4000/components/tabs/example-counts.html?locale=no-NO
- Counts should be positioned at the bottom

3.) Changing the position via `countsPosition` setting
- Add `countsPosition`: `bottom` or `top` in the test page
- It should override the default position of the counts

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Looks great. Maybe i would suggest a test that tests one of each direction...

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
Looks good - something funny on the tests so reruning.

**Review by deep7102 — DISMISSED** [review]
Looks good 🍌

**Comment by ericangeles** [comment]
The test is acting weird. I tried to run the test suite via VM and on my local and it passed.

**Comment by tmcconechy** [comment]
@ericangeles I dont know. Same here. But i have seen it fail on ci a few times. So i skipped it for now.
When we rewritet he time picker tests for puppetteer we can make an equivalent test there.

**Review by tmcconechy — APPROVED** [review]

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
