### PR TITLE
7768 - Fix validation error icon position in RTL

### LINKED ISSUE #7768: Datagrid: Validation error icon position is not correct in RTL
**Describe the bug**
Soho-datagrid has date column and lookup columns which has validations and for lookup we have custom validations.]
If the field validation got triggered then the icon alignment got disturbed in RTL case.

**To Reproduce**

1. Add a Soho-datagrid with datepicker and lookup
2. Add default validation for date and custom validatuon for lookup
3. Go to RTL case and give any invalid date and invalid data for lookup(Which should trigger custom validation)
4. After grid showing validation error for the cell hover on it and observe the position of error icon.

**Expected behavior**
Error icon should be in same position in RTL case like LTR

**Version**

- ids-enterprise: v15.2.1 (Onwards)

**Screenshots**

MicrosoftTeams-image (6)

MicrosoftTeams-image (7)

**Observation screenshorts in soho-datagrid example**

**RTL**:
MicrosoftTeams-image (8)

**LTR**:
MicrosoftTeams-image (9)

You can observe the issue in below link as well:

https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?locale=ar-SA

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes a bug where the validation icon position was not correct in RTL (Right-to-Left) mode.

**Related github/jira issue (required)**:

Closes #7768 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Clear any value in a cell in `Order Date` column to trigger the validation
- Icon should be in the left section of the cell
- Hover on it
- It should be positioned correctly with the datepicker icon
- Remove the date value in cell
- It should not return any NaN value

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles i think it was this https://github.com/infor-design/enterprise/issues/7849

**Comment by ericangeles** [comment]
Oh, I thought it had been fixed. I'll fix the issue raised above.

**Comment by ericangeles** [comment]
@glenlieorillo, can you retest the NaN issue? I've pushed a fix for that and adjusted the icon a bit when active.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Hello @ericangeles, NaN value issue is already fixed. However, I still found some issues on my end.

**Issue 1: Calendar Icon position in other Row Height**

Steps to reproduce:

1. Click More button
2. Select 'Extra Small/Small/Medium' from the dropdown
3. Click the Calendar Icon
4. Notice the Calendar Icon -- it also keeps on moving when you click the Calendar Icon 

image

**Issue 2: Error Icon Position**

Steps to reproduce:

1. Click More button
2. Select 'Extra Small/Small/Medium' from the dropdown
3. Click the blank cell
4. Click the page
5. Notice the Error Icon
- Extra Small and Small - _upon hovering the cell, the Error Icon disappears moving to the right_
- Medium - _No Error Icon shown when you leave the cell blank_


https://github.com/infor-design/enterprise/assets/102151352/8651d8d0-bb5e-4fcf-9111-4dfe073d6109

**Query:** Is it necessary to have dirty tracker on the cell even if you just click the cell?
cc: @tmcconechy


https://github.com/infor-design/enterprise/assets/102151352/b57dfa3b-cfe6-470e-a086-f829192cdb02

**Comment by tmcconechy** [comment]
@glenlieorillo No, the dirty indicator should only come if you change the cell contents.

**Comment by glenlieorillo** [comment]
> @glenlieorillo No, the dirty indicator should only come if you change the cell contents.

Thanks, @tmcconechy! I just noticed that when I click the cell with data and no edit is made, a dirty indicator will appear on the cell.

**Comment by tmcconechy** [comment]
ok @glenlieorillo that seems like a bug. I will let @ericangeles decide if he wants to fix or make a new issue

**Comment by ericangeles** [comment]
Let’s create separate issues for those things as we need to release beta today.

**Comment by tmcconechy** [comment]
ok @ericangeles do you think this improved anything as it is? i.e. ok to merge in your opinion?

**Comment by ericangeles** [comment]
Yes, the noticeable issue is the NaN value, although the main issue was the icon error position in RTL. We can patch other issues if you want.

**Comment by glenlieorillo** [comment]
> @glenlieorillo can you make issues for the remaining points like the dirty indicator showing up. ect...

Hello @tmcconechy, I have created 3 issues for the remaining points: [8020](https://github.com/infor-design/enterprise/issues/8020) [8021](https://github.com/infor-design/enterprise/issues/8021) [8022](https://github.com/infor-design/enterprise/issues/8022)

**Pull request merged**
