### PR TITLE
7413 -  Fix background color and hover bg color of column grouped headers in light header

### LINKED ISSUE #7413: Datagrid: Render issue group header background color
**Describe the bug**
The background color for the group header is incorrect when the grid option of isList is set to true.  

**To Reproduce**

1. Using the attached example 'test-with-tab-headers-horizontal.html'
2. Setting the gridOptions of 'isList:true'
3. Notice that background color for the group header is different than the background-color of column header

**Expected behavior**
Background color of the group header should be the same as the background color of the column header.

**Version**

- ids-enterprise: v4.80.6

**Screenshots**
image

**Additional context**
Several Landmark customers are affected.

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the background color and hover background color of column grouped headers in light header. (New Theme only)

**Related github/jira issue (required)**:

Closes #7413

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-grouped-headers-is-list
-  Datagrid header groups should have a white background color
- When hovering over headers with filters, the hover background color should be `#ecf2f8`

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — COMMENTED** [review]
when using classic theme,
the group header is different than the background-color of column header.
no hover state in product name column
image

**Comment by ericangeles** [comment]
@jbrcna, AFAIR, the light feature in the datagrid is only available in the new theme. Please refer to this previous ticket: https://github.com/infor-design/enterprise/issues/7008. I might have to revert the changes that will only work in the new theme.

**Comment by tmcconechy** [comment]
@ericangeles we will have to come up with something so that it works in the other themes

**Comment by ericangeles** [comment]
Perhaps, we can create a new ticket for that one?

**Comment by tmcconechy** [comment]
Sure. Please do.

**Comment by janahintal** [comment]
Approved for new theme. Thanks!

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
