### PR TITLE
7571 - Added swatch bar on colorpicker button

### LINKED ISSUE #7571: Sink Page: editor text color button is off in shades of green
**Describe the bug**

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com/
2. Find the editor component
3. click text color button and select emerald (choose the 2nd emerald)
5. play around with other color to see difference
6. try also the hover state of button

**Expected behavior**

**Version**

- ids-enterprise:v4.84.0-beta0

**Screenshots**
image

**Platform**
All

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added swatch bar over colorpicker icon. Swatch color will update instead of the entire button on color selected

**Related github/jira issue (required)**:

Close #7571 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/editor/example-index.html
- Select a color in text color picker
- Bar should be the one that changes color only

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
image

image

**Review by jbrcna — APPROVED** [review]
approving. the bar icon changes color accordingly as well.
 great work
image

**Review by janahintal — DISMISSED** [review]
Approving. Verified working in  http://localhost:4000/components/editor/example-index.html
Thanks!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Works great. To make it perfect could you adjust the icon position a bit. It sits a little low in comparison to other icons and is right on the bottom of the button on hover/focus.

Screenshot 2023-08-14 at 12 42 26 PM

Just push the A up a bit and make sure there is equal(ish) space on the top/bottom right/left

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
