### PR TITLE
2912 - Dropdown: Fix misaligned icons in IE11 (Uplift theme)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes the misaligned dropdown icons in IE11, specific in the Uplift theme. Removed unnecessary css property that cause the misalignment.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/2912

**Steps necessary to review your pull request (required)**:
- Pull this branch, run the app
- Navigate to http://localhost:4000/components/dropdown/example-icons?theme=uplift
- Click the dropdown menu to open
- Icons should now align properly

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
One thing I'm seeing with this icon that's not unique to IE11 is that the iconography on the "in-page" pseudo element isn't properly aligned with the one that shows up once the menu is opened.  See what happens in the gif below between when the menu is opened/closed:

Oct-9-2019-10_28-AM

Ideally the icon (and the text, for that matter) really shouldn't move at all between the menu's open/closed states.  It creates a bit of visual "jank".  I'd say we should probably get that resolved too.

Additional notes about that:  There are some Uplift-specific rules that affect this, within those rules are some specific placements for Firefox/IE, and for right-to-left scenarios.  Make sure to test all of those when modifying these, it's a bit of a pain.

**Comment by tmcconechy** [comment]
@ericangeles you should be able to fix @EdwardCoyle comment i think a seperate rule is in there to align it in the field that may need adjusting

**Comment by tmcconechy** [comment]
@ericangeles still seeing the icon on "Dropdown with Icons" shift a bit when opening.

**Comment by ericangeles** [comment]
> @ericangeles still seeing the icon on "Dropdown with Icons" shift a bit when opening.

Hi @tmcconechy , could you screenshot it? Or a screencast will do. Thanks.

**Comment by tmcconechy** [comment]
Ok sorry its not IE just chrome / mac
[IDS Enterprise.webm.zip](https://github.com/infor-design/enterprise/files/3713026/IDS.Enterprise.webm.zip)

**Comment by ericangeles** [comment]
> Ok sorry its not IE just chrome / mac
> [IDS Enterprise.webm.zip](https://github.com/infor-design/enterprise/files/3713026/IDS.Enterprise.webm.zip)

Will do the fix now. Thanks.

**Comment by EdwardCoyle** [comment]
Merged this after fixing the changelog conflict, since @deep7102 and @tmcconechy were good with it.

**Pull request merged**
