### PR TITLE
8467 - Fix selected row color in dark theme

### LINKED ISSUE #8467: IdsDatagrid: Selected lines not intuitive when using dark mode
**Describe the bug**
It is hard to understand which line is selected in the new dark mode. Which line is highlighted/selected? By experience you learn, but (for some users) it is counter-intuitive. The black lines are the ones being selected. Some users would have it the other way around.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?theme=new&mode=dark&colors=default
2. Click on any line
3. Selected line is same as the background which can be confusing to other users

**Expected behavior**
Selected lines should not have the same color as the background or at least have a more distinguishable identifier.

**Version**

- ids-enterprise: v4.92.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Infor M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
In the samples, there is a checkbox to indicate which lines are selected. This is not the case in our application as we do not display the checkbox as seen in the attached screenshot.

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes selected row color in dark theme.

**Related github/jira issue (required)**:

Closes #8467

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-multiselect.html?theme=new&mode=dark&colors=default
- Select any row in the grid
- Selected row should be on Slate color

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles not sure about this color. Will review with design https://8467-datagrid-selected-color-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?theme=new&mode=dark&colors=default

**Comment by tmcconechy** [comment]
on thought is to use the same selected state as here https://8467-datagrid-selected-color-enterprise.demo.design.infor.com/components/dropdown/example-index.html?theme=new&mode=dark&colors=default on dropdown.

I thought this was speced out by design on the issue but not seeing it again.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?node-id=2882-48798&mode=dev

@ericangeles lets try these colors for selection state

Screenshot 2024-05-02 at 12 00 00 PM

**Comment by ericangeles** [comment]
@tmcconechy, I didn't see any specifications in the ticket issue or Jira ticket, which is why I ended up using Azure.

**Review by glenlieorillo — APPROVED** [review]
**_Before fix:_**
image

**_After fix:_**
image

**Review by janahintal — APPROVED** [review]
image
image

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:
image

**Review by jbrcna — APPROVED** [review]
image

**Pull request merged**
