### PR TITLE
4714 - Fix a layout issue in RTL

### LINKED ISSUE #4714: RTL:Wizard tick circle offset
**Describe the bug**
Hi, in Wizard component in RTL mode, the tick circle is off by a few pixels

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/wizard/example-index.html?locale=he-IL#](https://design.infor.com/code/ids-enterprise/latest/demo/components/wizard/example-index.html?locale=he-IL#)
2. See the circle

**Expected behavior**
As LTR.
When I change `html[dir='rtl'] .wizard-header .tick::before` value of `right: 7px;` to -3px it looks ok.

**Version**

- ids-enterprise:v4.35

**Screenshots**
image

After changing CSS property:
image
it looks OK:
image

**Platform**
 - OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version:  87.0.4280.88 (Official Build) (64-bit)]

**Additional context**
Thanks!

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a fix as noted on #4714 to fix a layout issue in RTL

**Related github/jira issue (required)**:
Fixes #4714

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/wizard/example-index.html?locale=he-IL
- active step's double border should be aligned

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
Looks good, just a minor issue.

The solid circle is not perfectly centered with border circle around, and the bar overlapping on it.

Screen Shot 2020-12-28 at 3 25 07 PM

**Comment by tmcconechy** [comment]
@ericangeles i couldnt get it perfect but i think this is better (try it on all the dots by clicking each one and each one shifts a little bit)

**Comment by ericangeles** [comment]
Is it okay to push some fix? I might find a better css fix for this @tmcconechy

**Review by ericangeles — APPROVED** [review]
Re-reviewed 🍌

**Comment by tmcconechy** [comment]
Feel free if you have a better idea...

**Comment by ericangeles** [comment]
@tmcconechy your last commit doesn't reflect at first when am checking it. All good to me now.

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
