### PR TITLE
1132 NG - Rows are selected if there are initial values in input

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

When there are initial values in the input field, the grid should select the correct rows.

**Related github/jira issue (required)**:

Addresses this issue: https://github.com/infor-design/enterprise-ng/issues/1132

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/lookup/example-multiselect-paging-serverside.html
- Open "Products (with initial values)" lookup
- The correct items must be selected

**Included in this Pull Request**:
- [ ] A change in one of the example pages.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I see one sort of unrelated issue. Is the toolbar has too much space between the blue toolbar and grid?

Screen Shot 2021-11-09 at 10 06 46 AM

It should be right on top of the datagrid....
Screen Shot 2021-11-09 at 10 07 41 AM

But we can make a new issue for this if not an easy fix?

Also maybe @anhallbe wants to test this?

**Comment by tmcconechy** [comment]
Still seeing it look like this, where there is a gap on the top and now a gap on the bottom.

Screen Shot 2021-11-10 at 10 49 20 AM

**Comment by ericangeles** [comment]
@tmcconechy looks like the build has a problem with the chrome version again? We encountered this in new PRs.

**Comment by tmcconechy** [comment]
@ericangeles this should work i hope https://github.com/infor-design/enterprise/pull/5858

**Comment by tmcconechy** [comment]
Hopefully fixed the tests. The only thing i see is the toolbar is a little off left and right sides:

Screen Shot 2021-11-11 at 11 40 48 AM

**Review by tmcconechy — APPROVED** [review]

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
