### PR TITLE
8151 - Added personalization color changes

### LINKED ISSUE #8151: Preview - Accent colors - Default shows azure in color selector, and should alabaster be kept as an option?
**Describe the bug**
This is related to the preview/dev build, using alabaster as default. These are the colors returned from `Soho.theme.personalizationColors()` in Light mode, which we use to build the color selector (dropdown is-swatch)

```
{
    "default": {
        "id": "default",
        "name": "Default",
        "backgroundColorClass": "primary-bg-color", <--- This seems to have wrong value
        "value": "#0066D4" <--- Should this be white?
    },
    "alabaster": {
        "id": "alabaster",
        "name": "Alabaster",
        "backgroundColorClass": "alabaster",
        "value": "#ffffff"
    },
  // ... rest of accent colors
}
```

image

`primary-bg-color` in effect on the option
image

**To Reproduce**
I couldn't find the dev build deployed, but should be reproducible in an example that uses the swatch dropdown.

**Expected behavior**
`primary-bg-color` should be white. And will alabaster still be kept as a personalization color? We could filter it out if we want to avoid duplicates (Default & Alabaster), with a fallback to default if alabaster has previously been selected, so more of a question.

**Additional context**
The default value itself works fine, i.e. headers/subheaders/tabs get alabaster. It's just the representation of it in the swatch.

**Version**
- ids-enterprise: v4.89.0-dev.0
 
**Platform**
 - Infor Application/Team Name: OS Portal

### LINKED ISSUE #8152: Preview - Header - Border looks incorrect in Dark mode
**Describe the bug**
The bottom border of the header has the same color as it has when using Light mode. Seems to stand out too much in Dark mode?

image

Compared to latest:
https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-index?theme=new&mode=dark&colors=default

**Version**
- ids-enterprise: v4.89.0-dev.0

**Platform**
 - Infor Application/Team Name: OS Portal

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes some wrong colors in personalization.

**Related github/jira issue (required)**:
Fixes #8151
Fixes #8152

**Steps necessary to review your pull request (required)**:
- http://localhost:4000/components/personalize/example-index.html
- type the following in the console

```js
Soho.theme.personalizationColors().default
```

- default is white
- copy the class primary-bg color and put it on the header -> header should stay white
- change to dark node http://localhost:4000/components/personalize/example-index.html?colors=default&theme=new&mode=dark -> notice that the border is fixed 

Screenshot 2023-11-07 at 11 59 57 AM

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The fix has already been applied. However, the 'More' menu is not visible.


https://github.com/infor-design/enterprise/assets/102151352/e244f7e2-ea3b-402d-b637-e013c6034d29

image

**Review by jbrcna — APPROVED** [review]

**Comment by tmcconechy** [comment]
@glenlieorillo try running `npm i` because there is new icon packages and maybe you switched between a branch with old and new ones on localhost.

**Comment by jbrcna** [comment]
image

**Review by janahintal — APPROVED** [review]
Working as expected in https://8151-personalization-colors-enterprise.demo.design.infor.com/components/personalize/example-index.html?theme=new&mode=light&colors=default 

image
image

**Pull request merged**
