### PR TITLE
7896 - Fix widget sizes

### LINKED ISSUE #7896: Card/Widget: Height greater than header + content heights combined
**Describe the bug**
The height of a widget is greater than its header and content elements combined. This doesn't seem right, as it leads to a noticeable gap with full content.  

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-workspace-widgets?theme=uplift&variant=light
2. Inspect the widget element, and its header and content elements
3. Widget height is 373px. Header is 48px, content 318px (366px combined). Means there is 7px of dead space, see screenshot below. 
4. For a double height widget, it's the other way around, header + content heights exceed widget height

**Expected behavior**
Height of a widget should be header + content.

**Version**
- ids-enterprise: latest (4.86.0)

**Screenshots**
`.widget-content` colored red
image

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
We're currently using v4.85.0, where same issue can be seen (but widget is 368px tall, so only 2px dead space). I think the new widget height is supposed to be 368px, so content should be 320px?

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed as noted that the widget height is a bit inconsistent. Sizes should be

- Widget Total 368
- Header 48
- Body 320 

cc @talkaboutdesign

**Related github/jira issue (required)**:
Fixes #7896

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/cards/example-workspace-widgets.html and confirm
- test all widget and card examples http://localhost:4000/components/cards http://localhost:4000/components/widgets and http://localhost:4000/components/homepage
- looking for unneeded scrollbars or similar issue
- also check the double height widget on http://localhost:4000/components/homepage/example-scenario-h.html (widget 752, header 48, content 704)

**Included in this Pull Request**:
- [x] A note to the change log.

**Screen Shots**

Screenshot 2023-09-06 at 1 14 12 PM
Screenshot 2023-09-06 at 1 14 02 PM
Screenshot 2023-09-06 at 1 13 55 PM

### CODE REVIEW

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
http://localhost:4000/components/cards/example-workspace-widgets.html - PASS
image


image

http://localhost:4000/components/homepage/example-scenario-h.html - PASS
image

------

------

**Cards**

http://localhost:4000/components/cards/example-group-action.html

- Bottom border looks off

image

------

http://localhost:4000/components/cards/example-expandable.html

- The first item is selectable while the others are not

https://github.com/infor-design/enterprise/assets/102151352/4bd854b2-074e-4469-a3b2-693abed3ef9b

-----
-----
**Homepage**


http://localhost:4000/components/homepage/example-add-widget.html

- Unnecessary scroll bar
- Bottom border looks off

https://github.com/infor-design/enterprise/assets/102151352/318a3432-7bb4-407a-ac4e-75ff27f5c4d5

image

------

http://localhost:4000/components/homepage/example-calendars.html?theme=new&mode=dark&colors=default

- Bottom border looks off
image

-----

http://localhost:4000/components/homepage/example-filled.html

- Unnecessary scroll bar
- Bottom border looks off


https://github.com/infor-design/enterprise/assets/102151352/5e5ee63f-cbc4-444e-aa96-f965d29301c4

------

http://localhost:4000/components/homepage/example-monthviews.html?theme=new&mode=dark&colors=default

@tmcconechy, kindly verify if this is the expected design for these calendars. Thanks!

image

-------

**Review by clayinfor — APPROVED** [review]

**Comment by tmcconechy** [comment]
@glenlieorillo good observations. I have cleaned up all of them. Thanks!

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Hello @tmcconechy, I encountered additional issues. See details below. Thank you so much!

**Issue 1:** http://localhost:4000/components/homepage/example-add-widget.html

Upon clicking the 'Remove/Append Business Insight' button, I noticed that the pie chart appears/overlaps the bar chart. See screenshot below:

image


https://github.com/infor-design/enterprise/assets/102151352/939154a6-aa5f-4930-b8fd-3e06f29c5c8e

**Issue 2:** http://localhost:4000/components/homepage/example-monthviews.html

Calendar icon, dropdown menu, 'Today' button and arrows disappear when going to the next month using arrow keys.

_Steps to reproduce:_

1. Click any date
2. Press down arrow key until you reach the next/other month
3. Press up arrow key, go back to the previous month
4. Notice that the Calendar Menus above the calendar is missing

image

https://github.com/infor-design/enterprise/assets/102151352/2031798d-f8f2-4f75-89b4-46849155a18b

http://localhost:4000/components/cards/example-group-action.html - **PASS**

image

http://localhost:4000/components/cards/example-expandable.html - **PASS**


https://github.com/infor-design/enterprise/assets/102151352/82c743f0-b3d8-40ad-b63e-541aa68d5703



http://localhost:4000/components/homepage/example-calendars.html?theme=new&mode=dark&colors=default - **PASS**

image

http://localhost:4000/components/homepage/example-filled.html - **PASS**


https://github.com/infor-design/enterprise/assets/102151352/88011034-7856-4fb0-a989-4e240281a237

**Comment by tmcconechy** [comment]
@glenlieorillo lets make new issues for those as they are really unrelated. Can you check if they exist on https://main-enterprise.demo.design.infor.com/components and if they do make an issue based on that?

Neither seems easier or super important right now.

**Review by ericangeles — APPROVED** [review]
Looks good! 🍌

**Pull request merged**
