### PR TITLE
7204 - Personalization Header buttons color

### LINKED ISSUE #7204: Personalize: Secondary button in header is different from all others
**Describe the bug**
When a `.btn-secondary` or `soho-button="secondary"` button is inside a header (toolbar), it looks different from all other button types. Especially so in Light / HighContrast theme.

**To Reproduce**

1. Go to https://anhallbe.github.io/ids-repro/header-buttons
2. Notice the buttons in the header
3. Change the color theme to anything but "Default"
4. *See how the "Secondary Button" text is almost invisible.*
5. Hover the buttons
6.* See how "Secondary Button" behaves differently from the others* (not necessarily incorrect, but it appears like a bug.

**Expected behavior**
I guess it's fine that "secondary" buttons look different from the others. But the text should always be visible.

**Version**

- ids-enterprise: 4.80.2

**Screenshots**
image

**Additional context**
https://jira.infor.com/browse/SCRMPORTALV2-5678

Repro code: https://github.com/anhallbe/ids-repro/blob/master/src/app/header-buttons/header-buttons.component.html

```html
<soho-header>
  <soho-toolbar-flex>
    <soho-toolbar-flex-section [isButtonSet]="true">
      <button soho-button="primary">Primary Button</button>
      <button soho-button="secondary">Secondary Button</button>
      <button soho-button="tertiary">Tertiary Button</button>
      <button soho-button="icon" icon="component" title="Icon Button"></button>
      <button soho-menu-button>Menu Button</button>
      <ul soho-popupmenu>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 1</a>
        </li>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 2</a>
        </li>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 3</a>
        </li>
      </ul>
    </soho-toolbar-flex-section>
  </soho-toolbar-flex>
</soho-header>
```

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes secondary button color/hover color when it's in the header by excluding `.header` in personalization styles and fixes primary/tertiary button's color for dark theme not default color.

Also fixes an issue with a padding in the popup menu when when toolbar overflowed hidden items has icons

**Related github/jira issue (required)**:
Closes #7204 

**Steps necessary to review your pull request (required)**:
- pull and build

Header buttons:
- go to http://localhost:4000/components/personalize/example-header-buttons.html
- change color/mode, check button's color/icon color/hover/focus
- all buttons should be the same style
- go to http://localhost:4000/components/button/example-index.html
- buttons/states should not change so the changes applied to header buttons only

Popup menu:
- go to http://localhost:4000/components/personalize/example-header-buttons.html
- resize the browser's window to a size where no buttons are overflowed to the menu
- open the menu and see no padding added
image
- resize the browser's window to a size where some buttons overflowed to the menu
- open the menu and see overflowed buttons with icons, open some secondary menu and see there is no extra padding

---
**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — DISMISSED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@andriivarhanov while the problem is fixed i see a couple wierd things on the example. 1. Maybe we can put these in a toolbar so they flow correctly in the header?

2. Also for some reason in the example the ... menu is extra wide (maybe a markdown issue).

image

**Comment by andriivarhanov** [comment]
@tmcconechy 
1. done
2. it looks like some issue with popup menu, can also be seen here https://main-enterprise.demo.design.infor.com/components/header/example-flex-toolbar.html, when the toolbar's buttons have icons menu got `has-icons` class and the padding, should I work on it in this PR?

**Comment by tmcconechy** [comment]
Yeah lets take a quick look @andriivarhanov but if it turns into  something major we can reconsider

**Comment by andriivarhanov** [comment]
Fixed the popup menu issue, updated the issue's description with the steps to review

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
