### PR TITLE
8962 - Add new translations and verify the changes.

### LINKED ISSUE #8786: Locale: Incorrect "Available" translations in Italian and Thai
Locale: Incorrect "Available" translations in Italian and Thai

**Italian**
image

**Thai**
image

en-messages.json
 "Available": { "id": "Available", "value": "Available", "comment": "Button tooltip used in a list of movable items" },
 "Selected": { "id": "Selected", "value": "Selected", "comment": "Text describing a selected object" },

"Available" and "Selected" are unclear strings. Result = Mistranslations. For example, in French, there are 4 translations for "Selected". The provided comments are not consistent.

"Available" and "Selected" = Poor strings
"Available Items" and "Selected Items" = Clear strings + add comments indicating string context/usage including the fact that Item is NOT a product/an article. Item = Part of a list, collection, or set

### LINKED ISSUE #8962: Locale: Incorrect "Small" and "Extra Small" translations in Spanish
Locale: Incorrect "Small" and "Extra Small" translations in Spanish

image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds new translations from the translation team which fixes two issues

**Related github/jira issue (required)**:
Fixes #8962
Fixes #8786

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/swaplist/example-index.html?locale=it-IT
- verify text is Disponibili
- go to http://localhost:4000/components/swaplist/example-index.html?locale=th-TH
- verify text is พร้อมใช้งาน
- go to http://localhost:4000/components/datagrid/example-index.html?locale=es-ES
- open the ... menu and verify the items say Pequena (not pequeno)

**Included in this Pull Request**:
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — CHANGES_REQUESTED** [review]
spanish is working as expected
image

However, the other translations is not taking effect
image
image

**Comment by tmcconechy** [comment]
@jbrcna should be fixed (was a timing issue on slower networks)

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://new-translations-enterprise.demo.design.infor.com/components/swaplist/example-index.html?locale=it-IT
image

https://new-translations-enterprise.demo.design.infor.com/components/swaplist/example-index.html?locale=th-TH
image

https://new-translations-enterprise.demo.design.infor.com/components/datagrid/example-index.html?locale=es-ES
image

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
nice work!
image
image

**Pull request merged**
