### PR TITLE
2178 - Add support for ids-breadcrumb

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added a fix to support using new ids-breadcrumb inside of legacy header. Also found that if you take is-personalization class off 

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-wc/issues/2178

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/header/test-no-personalize.html -> should be alabaster
- go to http://localhost:4000/components/header/example-wc-breadcrumb.html
- a) dropdown should open when resized and show overflowed items
- b) should be centered in the header
- c) go to http://localhost:4000/components/header/example-wc-breadcrumb.html?colors=1C86EF and try states and personalization should work
- regression test http://localhost:4000/components/header with https://main-enterprise.demo.design.infor.com/components

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
Looks good! 🍌

**Review by n-ace-ancog — COMMENTED** [review]
Working as expected for most, but encountered a style issue in the dark mode.
http://localhost:4000/components/header/test-no-personalize.html
image

http://localhost:4000/components/header/example-wc-breadcrumb.html
Animation

http://localhost:4000/components/header/example-wc-breadcrumb.html?colors=1C86EF
image

http://localhost:4000/components/header/example-wc-breadcrumb.html?theme=classic&mode=light&colors=default
image

http://localhost:4000/components/header/example-wc-breadcrumb.html?theme=new&mode=dark&colors=default
The text are almost unreadable in Dark mode and there is a white gradient element when browser is resized.
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
image
Failing in dark
image

text looks disabled
image

**Comment by tmcconechy** [comment]
@ericangeles asking design to review. One note: If approved this should go on all row-reorder examples not just the group one i.e. https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html

**Comment by ericangeles** [comment]
@tmcconechy, sure thing.

**Comment by tmcconechy** [comment]
@ericangeles woops wrong issue

**Comment by tmcconechy** [comment]
@jbrcna fixed dark mode

NOTE: Because of the way this works:

a) it may be a delay changing theme on this example
b) ultimately later this example should go in the other repo

So for those reasons not that worried about it but wanted to test this out here

**Review by janahintal — CHANGES_REQUESTED** [review]
https://breadcrumb-in-header-enterprise.demo.design.infor.com/components/header/test-no-personalize.html
image


Tabs selected from overflow does not look selected in responsive view https://breadcrumb-in-header-enterprise.demo.design.infor.com/components/header/example-wc-breadcrumb.html#
image

image

**Review by jbrcna — APPROVED** [review]
https://breadcrumb-in-header-enterprise.demo.design.infor.com/components/header/test-no-personalize.html
image
image

https://breadcrumb-in-header-enterprise.demo.design.infor.com/components/header/example-wc-breadcrumb.html#
image

image
image
image
image

**Review by glenlieorillo — APPROVED** [review]
image

image

image

image

**Pull request merged**
