### PR TITLE
6634 - Update all dependencies and use node 18

### LINKED ISSUE #6634: Node 16: Update all Dependencies and Use Node LTS
**Describe the bug**

- [x] check ncu ~ check each dependency
- [x] use the LTS node in .nvmrc
- [x] update d3?
- [x] update jquery 

Note: https://github.com/infor-design/enterprise/issues/6912

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates node to use LTS (18.13.0 as of writing). This includes:

- updating node .nvmrc
- all dependencies that can be updated
- remove some things as noted on https://github.com/infor-design/enterprise/issues/6749
- update d3 to fix issues with security

NOTE: May not want to merge this until 4.71.x is released.
NOTE2:  Build check 14 will be replaced with check 18 once merged

**Related github/jira issue (required)**:
Fixes #6634 

**Steps necessary to review your pull request (required)**:
- `rm -rf node_modules`
- `nvm use`
- `npm i`
- test every command in package.json
- test all chart functionality and general demo app

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
I tried all the different builds, tests, etc... Everything looks good.  Really nice work @ericangeles @tmcconechy

**Review by EdwardCoyle — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
Looks good 🍌 
Thanks! @tmcconechy @ericangeles

**Comment by tmcconechy** [comment]
Will hold on this until 4.7.1 then merge. Thanks All

**Comment by tmcconechy** [comment]
Will merge this if all tests pass again after merging conflicts....

**Pull request merged**
