### PR TITLE
7982 - Fix process indicator icon sizing to remove gaps.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Resized icons to remove gaps between line separators.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7982

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/processindicator/example-index.html
- Check example process indicator icons.
- There should be no gaps between the icons and separator lines.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I see a couple things.

1. It looks a little bigger now (seeing 15px vs 22px). Lets use 22px for the small one
Screenshot 2023-10-09 at 10 41 37 AM


2. some are streteched out or not circlular anymore and some of non centered icons

Screenshot 2023-10-09 at 10 42 09 AM

**Comment by tmcconechy** [comment]
@RJ-Csc looks like now its lost the colors on the icons as it was before

Screenshot 2023-10-11 at 10 25 50 AM

vs

Screenshot 2023-10-11 at 10 25 46 AM

**Comment by RJ-Csc** [comment]
Hello @tmcconechy. Looks good on my end. 
image

**Review by tmcconechy — APPROVED** [review]
Thanks @RJ-Csc i think its because i was on an old branch without some icon updates.

**Comment by tmcconechy** [comment]
@infor-design/qa cc

**Comment by max-hizon** [comment]
Works on all modes

Light
image

Dark
image

High Contrast
image

Note: Classic version had this already implemented and issue was only on New version

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**
image

**Mac Edge**
image

**Mac Firefox**
image

**Safari**
image

**Review by janahintal — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Comment by jbrcna** [comment]
image

**Comment by jbrcna** [comment]
nevermind. it's working in main. thanks
image

**Pull request merged**
