### PR TITLE
5827 - Follow up fix in icon position and rlm issues on firefox and safari (RTL)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR addresses icons' position on firefox and incorrect display of parenthesis on safari (RTL).

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5827

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Open the test page http://localhost:4000/components/listview/example-status.html?locale=he-IL in Safari and Firefox
- Test first in Firefox
- Icon should be visibly aligned with the text
- Test in Safari
- Fieldset title should be `Status Indicator (Alert)` and not `(Status Indicator (Alert`
- Alert text should be `ESCALATED (2X)` and not `(ESCALATED (2X`
- Alert icon should be visibly aligned with the text 

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
~~- [ ] A note to the change log.~~

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Pretty minor but in FF its pushed up a little bit...
Screen Shot 2021-12-13 at 9 46 55 AM

**Comment by ericangeles** [comment]
@tmcconechy what version of firefox are you on? This is what am getting

Screen Shot 2021-12-15 at 12 03 18 AM

**Comment by tmcconechy** [comment]
Hmm yes i still see it..

Screen Shot 2021-12-14 at 11 28 36 AM

This is the browser im using (mac)
Screen Shot 2021-12-14 at 11 27 35 AM
.

**Comment by ericangeles** [comment]
@tmcconechy I am still don't see the issue on my end even updating my firefox to 95. I pushed a better fix to center the icon automatically.

**Review by yohannahbautista — APPROVED** [review]

**Comment by tjamesallen15** [comment]
Looks good on my screen. Tested both in Mac and Windows Firefox.
image

**Review by tjamesallen15 — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
