### PR TITLE
8138 - Changed personalize columns design

### LINKED ISSUE #8138: Datagrid: Add ability to personalize column groups
**Describe the bug**
Personalization for column groups in datagrid is not present. Need the personalization for the column groups.

**To Reproduce**
Applied this columnGroups for SohoDataGridOptions.

```
 columnGroups: [{ colspan: 1, id: '', name: ''},{ colspan: 1, id: '', name: 'Claim (Line) Number'},
        {colspan: 1, id: '', name: 'Cost Type'},{colspan: 2, id: '', name: 'Costs'},
        {colspan: 2, id: '', name: 'Item'}, { colspan: 1, id: '', name: 'Serial Number'},
        {colspan: 1, id: '', name: 'Status'}, { colspan: 1, id: '', name: 'Creation Date'},
        {colspan: 2, id: '', name: 'Breakdown Date'}],
      toolbar: {title: '', actions: true, results: true, personalize: true },
      saveUserSettings: {
       columns: true,
       rowHeight: true,
       sortOrder: true,
       filter: true
     },
```

**Steps to reproduce the behavior**
Personalization is not present for column groups in toolbar.

**Expected behavior**
Personalization should present for column groups in toolbar.

**Version**

- ids-enterprise: v4.87.0

**Screenshots**
image
image

**Platform**
 - Infor Application/Team Name: Infor LN 
 - Device: PC
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome, Edge
 - Browser Version: Version 118.0.5993.118 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changed personalize columns design

**Related github/jira issue (required)**:

Closes #8138 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-grouped-headers.html
- Personalize button (gear icon) should be there
- Open to see menu
- Groups should show
- try here as well http://localhost:4000/components/datagrid/example-books.html or on any datagrid page with the personalize option

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista I didn't take a very deep look at this but one flag for now. I dont think we want to add this button to every data grid.

a) Keep it as is in the ... menu when you click the personalize columns https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html then show the popup / modal from there
b) Can also add one example with a custom toolbar with the a button like that. Then provide a method (if not already one) to show the personalization dialog.

But be default we dont want the button added automatically to everyones grid toolbars by default. 👍🏻

**Comment by yohannahbautista** [comment]
> @yohannahbautista I didn't take a very deep look at this but one flag for now. I dont think we want to add this button to every data grid.
> 
> a) Keep it as is in the ... menu when you click the personalize columns https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html then show the popup / modal from there b) Can also add one example with a custom toolbar with the a button like that. Then provide a method (if not already one) to show the personalization dialog.
> 
> But be default we dont want the button added automatically to everyones grid toolbars by default. 👍🏻

@tmcconechy @ericangeles 
Should I use something like this for the list? https://main-enterprise.demo.design.infor.com/components/arrange/example-index.html

**Comment by tmcconechy** [comment]
@yohannahbautista yes for me thats what i would use so they can sort the items. SO if that works you can use it on the new popup.

Basically the old popup should be changed to this new design.

**Comment by ericangeles** [comment]
@yohannahbautista, I've merged the main to fix the build issue. Please update your branch. Thanks!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista looks pretty good but a few things

1. unneeded scrollbar
2. Cant seem to drag the items (important)
3. Cant seem to toggle the items (important)
4. Seem  not centered in the focus state
5. The keyboard could also work (arrow up and down and enter/space to toggle)

**Comment by n-ace-ancog** [comment]
Is it expected that the column group are not draggable (the "grab indicator" indicates its draggable) and only its members are allowed to be draggable?

https://github.com/infor-design/enterprise/assets/156752175/e8fe3097-45da-4362-bdad-2dacc6eb835e

image

**Comment by tmcconechy** [comment]
@yohannahbautista this is looking pretty good but i see a few things

1) Might be better if you click the switch it toggles, it is toggling when you click the item
2) We might want this new indicator when dragging https://github.com/infor-design/enterprise/pull/8621
3) When i click a child to toggle it it hides the part (click status and see it hides the part)
4) Switch isn't centered
5) What if there is a lot more columns? Does the dialog scroll?
6) I noticed we are loosing search functionality which might be an issue. Maybe we need to keep the search bar on top

**Comment by tmcconechy** [comment]
@ericangeles sounds good to me, then maybe just need to clean up the drag image. It has a white space on the bottom (a mix of highlighted and white). Thats all

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles @n-ace-ancog 
> Is it expected that the column group are not draggable (the "grab indicator" indicates its draggable) and only its members are allowed to be draggable?

There's no details on how it should behave so I based it on the actual datagrid. You can't drag column groups on the datagrid itself, just the columns.

> Might be better if you click the switch it toggles, it is toggling when you click the item

I'm using the selected event so it selects the list item itself. I'm not really sure if I can have a listener for the switch specifically since switch itself clicks with label and the button: https://main-enterprise.demo.design.infor.com/components/switch/example-index.html

> I noticed we are loosing search functionality which might be an issue. Maybe we need to keep the search bar on top

It wasn't in the figma so I didn't add it
https://www.figma.com/design/JZdeun4ht1IsqZpV9xAW8Y/Colors?node-id=1382-13660&t=Xoq3RWJlhlkbVg40-0

**Comment by tmcconechy** [comment]
@yohannahbautista one comment from design "could add a bit of space between labels and switchbuttons (toggles) "

Screenshot 2024-05-15 at 9 19 17 AM

We can come back with the search designs later.

**Comment by tmcconechy** [comment]
@yohannahbautista i crossed out fixed items in my list

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Some issues found regarding the behavior of the personalized columns in http://localhost:4000/components/datagrid/example-grouped-headers.html:
1. When a hidden column is dragged to other group, the following column is transferred instead

image
  - Activity column here is not visible and was dragged from **Column Group Two**
  - At the background, Quantity column is now at the **Column Group One**
  - In the Modal, Quantity column is undraggable and is at **Column Group Three**

image
  - Once Activity column is show, it is now at **Column Group Four**

https://github.com/infor-design/enterprise/assets/156752175/4b980aea-469f-4841-a063-9f2fd47b6770


2. The parent group toggle also changes when only 1 column was changed - the rest are still in "on" state

https://github.com/infor-design/enterprise/assets/156752175/44c064f7-1430-4a98-a178-e93f43db7132

3. When searching, group are still displayed even if no columns matches under it
image

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles @n-ace-ancog 
> The parent group toggle also changes when only 1 column was changed - the rest are still in "on" state

There's no details on actual behavior on the new design of personalize columns in the figma, just how it looks. 

There's a discussion thread about it: https://jira.infor.com/browse/IDS-1616 so I based it off that. It acts as a "Toggle all in group" switch. If one column is disabled, the group toggles to off setting. If all the columns are enable, the group is toggled on. If you want to toggle on/off on all the columns in group, you can choose the group switch.

**Comment by tmcconechy** [comment]
@yohannahbautista even tho its not well defined in figma the pattern has been working for a while. At the simplest level its really just. Can i configure the columns in the grid with the dialog. A lot of this stuff is impossible to put in figma.

With that functionality i think it should work like this:

- if you click the parent it closes all the items in the group, if you click the parent again it shows them
- BUT if you click a child it should only toggle that child. Without this there is no way to turn the children off

Also issues remaining:

1) When you drag i'd like to get rid of the extra white space under it
2) Clicking the item still feels wierd. If you click the text it toggles BUT if you click the empty space between the text and switch it does not. I really think it should work only if you click the switch and it should have a bit of a bigger hit point around it. For example clicking the bar on the switch its hit or miss.

**Comment by ericangeles** [comment]
@tmcconechy, should the group header have an icon handle even if it's not draggable?

**Comment by ericangeles** [comment]
Honestly, I'm confused by the Figma file containing this feature, or am I just looking at the wrong link?
https://www.figma.com/design/JZdeun4ht1IsqZpV9xAW8Y/Colors?node-id=1382-13660&t=1QipAVdn265PTnMN-0

**Review by jbrcna — APPROVED** [review]
image
image
image
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Some re-test issues found:
1. When moving a column coming from a non-consecutive group to other group, the column on the consecutive group has additional columns

   **Steps to replicate**
    1. Open the modal
    2. Drag price from **Column Group Three** to **Column Group One**
    3. At the background, the **Quantity** column is now at **Column Group Two** - **_ISSUE_**
image
    4. Close the modal
    5. Open the modal again
    6. The entire **Column Group One** is at "off" state - **_ISSUE_**
image

2. **Column Group** toggle doesn't update when all of the columns under it are either off or on
image
- I think for this one, if all of the column has the same state, the group toggle will be updated as well

3. Columns can be dragged outside of a group
image

4. The **Column Group** has a drag icon indicating that its draggable, but they can't be dragged around
image

**Review by tmcconechy — APPROVED** [review]
Thanks @yohannahbautista Im going to call this one good for now. We can fix anything else later that comes up.

Thanks for your hardwork 💪🏻

**Review by janahintal — CHANGES_REQUESTED** [review]
Modal is not centered in Responsive / Mobile view
https://8138-datagrid-personalize-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
image

**Review by ericangeles — APPROVED** [review]
Great work, @yohannahbautista 🍌 

Could you also add the settings and event in NG wrapper?

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
