### PR TITLE
Misc - Added an alternative fix for XSS vulnerability

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a new fix by reverting some previous changes and using innerText instead of html()

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8444
Closes https://github.com/infor-design/enterprise/issues/8285

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/example-editable.html
- in both the hyperlink and text cell enter special chars like `&<>`
- hit enter to commit
- go back and forth a page
- try to paste `<script>alert("Hello World!")</script>` in a cell and it should not alert
- try to paste `related:[BALMAS1("TX60:\{IndexList_Items.TX60}")]` in a cell and it should stay in tact
- paste `c:\windows\temp` in a cell and it should work
- type in the price column to see that works
- http://localhost:4000/components/datagrid/example-editable-with-row-status.html (For editable with row status)
- Type in a special character (for example, '<', '>', '&') in first cell under Activity column
- After cell out, it should not change into encode value
- http://localhost:4000/components/datagrid/test-editable-lookup-mask.html
- Open the lookup modal
- Select the cell that has script tag
- It should not run the script

Relates to https://github.com/infor-design/enterprise/pull/8180

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@n-ace-ancog can you test this one as well. We are trying to decide between the two fixes

**Comment by tmcconechy** [comment]
Problems on this one

1. http://localhost:4000/components/datagrid/test-editable-lookup-mask.html executes the script
2. typing c:\windows\test in the hyperlink adds an extra \

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
[http://localhost:4000/components/datagrid/example-editable.html](http://localhost:4000/components/datagrid/example-editable.html) 

The values `<>&` are sanitized properly, but found others that are behaving weirdly.

**First case** - entering `<svg/>` then tabbing out fills up the entire cell with space. Then focusing back shows encoded values in the hyperlink column

Animation

**Second case** - after entering `related:[BALMAS1("TX60:\{IndexList_Items.TX60}")]` an symbol is being added every time the hyperlink cell is being focused. 

Animation

@tmcconechy - here are the initial findings.

**Comment by n-ace-ancog** [comment]
[http://localhost:4000/components/datagrid/example-editable-with-row-status.html](http://localhost:4000/components/datagrid/example-editable-with-row-status.html ) - is not a valid link

[http://localhost:4000/components/datagrid/test-editable-lookup-mask.html](http://localhost:4000/components/datagrid/test-editable-lookup-mask.html) - alert is being displayed.
Animation

**Comment by tmcconechy** [comment]
@n-ace-ancog i fixed those issues thanks!

**Comment by n-ace-ancog** [comment]
[http://localhost:4000/components/datagrid/example-editable.html](http://localhost:4000/components/datagrid/example-editable.html)

**First case** - now working properly. 
Animation

**Second case** - now working properly.
Animation

The following are also working as expected:
- `<>&` characters are not being encoded
- `<script>` not being triggered
- price column is editable
Animation

**Comment by n-ace-ancog** [comment]
[http://localhost:4000/components/datagrid/example-editable-with-row-status.html](http://localhost:4000/components/datagrid/example-editable-with-row-status.html) 

Working as expected.
Animation

[http://localhost:4000/components/datagrid/test-editable-lookup-mask.html](http://localhost:4000/components/datagrid/test-editable-lookup-mask.html)

**First case** - script is **not** being triggered anymore, but after tabbing out of the cell - it shows an empty cell. Re-focusing on the cell shows the text without the `<script>` tag. Is this expected @tmcconechy?

Animation

**Second case** - `<svg/>` tag now just showing as text

**Review by jdilag90 — APPROVED** [review]
lgtm

**Comment by tmcconechy** [comment]
@n-ace-ancog yes, i made it strip the tag out. The important thing is it doesnt run the script. This could be improved but its a wierd edge case and i dont want to break anything else.

Since this passed the teams tests maybe we can consider that as expected. Since its not super well defined.

**Review by n-ace-ancog — APPROVED** [review]

**Pull request merged**
