### PR TITLE
3389 - Fix iOS scrolling bug related to Modals

### LINKED ISSUE #3389: Modal: Cannot scroll after closing modal on an iOS device
**Describe the bug**
Modal is not working after closing a different modal in iOS device

**To Reproduce**
1. Open iOS mobile and Go to http://4250-rc1-enterprise.demo.design.infor.com/
2. Click Show Modal button
3. Close the Modal 
4. Click any button to open the Message component and then and close the message 
5. Notice that you will not be able to scroll the page nor click another button again. 

**Expected behavior**
Be able to open another modal without issue after opening a modal

**Version**
IDS RC1 4.250

**Screenshots**
N/a

**Platform**
iOS Mobile Devices

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes an iOS bug where it would sometimes not be possible to scroll inside a scrollable page area after opening/closing multiple Modals, Messages, etc.

**Related github/jira issue (required)**:
Closes #3389

**Steps necessary to review your pull request (required)**:
Pull this branch, build, run the app.  Then try the following:

_To test the scrolling bugfix:_
- in Mobile Safari on an iOS device/simulator, open the Kitchen Sink page at http://localhost:4000
- Scroll down to the Modal examples and click "Show Modal".  The modal should appear.
- Close the modal, and scroll down to the Message samples beneath it.  Click any of the Message buttons.  The Message should appear.
- Close the message and attempt to scroll the Kitchen Sink page.  The page should scroll properly.
- Open Safari dev tools and inspect your device/simulator page. Ensure there is no `modal-engaged` CSS class on the `body` tag.

_Smoke test nested modals to make sure the overlay/container are still working properly when closing multiple items:_
- In any browser, open http://localhost:4000/components/modal/test-nested.html
- Open all three nested modals and close them.  Ensure the overlay only disappears after the highest-level modal is closed.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
I am still able to reproduce the issue:

- I open it via browserstack (iPhone 11 Pro, Safari)
- Went to http://localhost:4000
- Open "Show Modal"
- Then close it
- Open the Error Example Button
- Then close it
- Open the next Button `Alert Example`
- Close it
- Then I wasn't able to scroll the page
- I check the body tag, and the `modal-engaged` class is there

**Comment by EdwardCoyle** [comment]
@ericangeles I'm wondering if your browserstack instance had something cached?  I checked this on Browserstack with the same specs, and was seeing it work as expected:

Untitled_-Mar-10-2020-9_49-AM

**Comment by tmcconechy** [comment]
@EdwardCoyle I am still seeing the scroll issue if i..
- scroll down
- click modal
- proceed to click and close error example, then alert example then success example (seems like it works the first 2 times on message but not 3 times)

**Comment by EdwardCoyle** [comment]
@ericangeles @tmcconechy, I was able to track down the issue.  Good find!

**Comment by tmcconechy** [comment]
Just one minor QA thing is the button is cut off on the example. 

Screen Shot 2020-03-11 at 9 20 57 AM

**Comment by EdwardCoyle** [comment]
@tmcconechy I fixed that padding issue but I'm expecting a bunch of Modal baselines to fail due to the change... will fix if it happens.

**Pull request merged**
