### PR TITLE
Refactor personalize styles, update personalized app menu

### PR DESCRIPTION
**Pull request by nickwynja**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Makes default application menu and personalized menu more consistent
- Improves overall design of personalized app menu
- Consolidates personalize colors for more readable/designer-friendly `personalize.styles.js`

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/design-system/issues/358

**Steps necessary to review your pull request (required)**:

**`example-personalized.html`**:
* [soho-theme default](http://localhost:4000/components/applicationmenu/example-personalized.html)
* [soho-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized.html?theme=soho&colors=7025B6)
* [uplift-theme default](http://localhost:4000/components/applicationmenu/example-personalized.html?theme=uplift)
* [uplift-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized.html?theme=uplift&colors=7025B6)

**`example-personalized-roles.html`**:
* [soho-theme default](http://localhost:4000/components/applicationmenu/example-personalized-roles.html)
* [soho-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=soho&colors=7025B6)
* [uplift-theme default](http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=uplift)
* [uplift-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=uplift&colors=7025B6)

**`example-personalized-roles.html`**:
* [soho-theme default](http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html)
* [soho-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=soho&colors=7025B6)
* [uplift-theme default](http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=uplift)
* [uplift-theme personalized](http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?theme=uplift&colors=7025B6)

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Note to other reviewers that we should also double check the standard Accordion component, which is used for the "menu" part of the Application Menu:

- http://localhost:4000/components/accordion/example-index.html?theme=uplift
- http://localhost:4000/components/accordion/example-accordion-panels.html?theme=uplift&colors=800000

... are just a few examples

**Comment by nickwynja** [comment]
@EdwardCoyle  Thanks for pointing out `example-accordion-panels.html`. I had to push a fix based on that.

**Comment by tmcconechy** [comment]
Did you mean for it to just be all one color now. I think it needed the color separation for the internal accordion (subheader color) but thats maybe debatable?

Screen Shot 2019-05-21 at 10 22 36 AM

Compare:
http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html
vs
http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?colors=80000

Also the focus color and the selected item color is not pronounced when colored at all which may be an issue. (class is-selected)

**Comment by tmcconechy** [comment]
Also on http://localhost:4000/components/accordion/example-index.html?theme=uplift the icon isnt centered in the header in uplift
 
Screen Shot 2019-05-21 at 10 29 13 AM

**Comment by nickwynja** [comment]
> - [x] "fix" the selection state (it could be the same as the hover state)
> - [x] Consider a better focus state on the app menu
> - [x] Bump the icon to the middle on accordion


image
image

**Comment by nickwynja** [comment]
@tmcconechy Yes, we need to revisit states overall with the design team. That'll be for a future fix. I'd appreciate if you could update the baselines for me. Thanks!

**Comment by EdwardCoyle** [comment]
@nickwynja:
- seems like the new [visual regression test for the App Menu](https://travis-ci.com/infor-design/enterprise/jobs/201900469#L654) is failing.  We will probably have to update the baseline image for it.
- Not sure what the deal is [with this one](https://travis-ci.com/infor-design/enterprise/jobs/201900469#L881), I tested locally and it seems fine.  May have been a timing fluke.

The [linter failure](https://travis-ci.com/infor-design/enterprise/jobs/201900471#L546) is fairly straightforward.

**Pull request merged**
