### PR TITLE
8344/8411 - Fix Subcomponents not closing when hitting the escape key

### LINKED ISSUE #8344: Modal: Closing a timepicker in a modal with "esc" causes a crash
**Describe the bug**
When a timepicker that's inside a modal is closed using `esc`, a console error is encountered and the entire page becomes uninteractable.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/modal/test-modal-field-filter.html
2. Click "Show Modal"
3. Open the timepicker
4. Close the timepicker with `esc`
5. Notice how the modal is closed and the timepicker is still open, and the page becomes uninteractable. Open the devtools and notice the console error.

**Expected behavior**
The timepicker should close with no errors.

**Version**

- ids-enterprise: `4.91.0-dev.0`

**Screenshots**
modal_timepicker

**Platform**
 - Infor Application/Team Name: OS Portal / Homepages

### LINKED ISSUE #8411: Datagrid: Escape key closes modal and opens colorpicker after the modal is closed
**Describe the bug**
When a colorpicker cell is focused on a table within a modal and the user presses the Escape key, the modal is closed and the colorpicker is opened after.

**To Reproduce**

1. Please use this zipped html file: [test-editable-colorpicker-on-modal.zip](https://github.com/infor-design/enterprise/files/14127309/test-editable-colorpicker-on-modal.zip)
2. Click on Show Modal button
3. Click on a colorpicker cell
4. Select a color
5. Press the Escape key

**Expected behavior**
After comparing this to other datagrid cells, it is expected that the modal is closed and the colorpicker does not open.

**Version**
- ids-enterprise: 4.88.0-beta.0

**Screenshots**
editable colorpicker escape key on modal

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 121.0.6167.87 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the issue where the subcomponents modal does not close when hitting the escape key.

**Related github/jira issue (required)**:

Closes #8344
Closes #8411

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/modal/test-modal-field-filter.html (Timepicker)
- Open the modal
- Click the Timepicker trigger to open the timepicker popover
- Hit escape key, timepicker popover should close
- Hit escape key again, modal should close
- Go to http://localhost:4000/components/modal/test-editable-colorpicker-on-modal.html (Colorpicker)
- Open the modal
- Click the colorpicker to show the list
- Hit escape key, popupmenu colorpicker should close
- Hit escape key again, modal should close

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Screenshot 2024-02-19 at 10 32 39 AM

Might be out of scope but the icon sits a little low and it shifts when you click in the field

**Review by jbrcna — DISMISSED** [review]
Large GIF (1114x544)
Large GIF (1512x724)

**Review by jbrcna — APPROVED** [review]
reapproving

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/f8ef3397-0392-459c-aac8-82fb04193291


https://github.com/infor-design/enterprise/assets/102151352/4cbb2bc2-3d60-4983-aecd-dfd36b119844

**Pull request merged**
