### PR TITLE
4832 - Datagrid: Accents Not Matched for Alert Ranges

### LINKED ISSUE #4832: Datagrid - French accents are not matching when using alert ranges
**Describe the bug**
Datagrid - Status column showing blank in French language.

**To Reproduce**
Please replace bellow attached file in the enterprise-ng project and go to link http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic
you will see the value "En file d\'attente" is not getting display in datagrid view with icon.
[datagrid-demo.service.ts.zip](https://github.com/infor-design/enterprise-ng/files/5958542/datagrid-demo.service.ts.zip)

**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Encoded values do not match inside the Formatter.Alert function.

**Related github/jira issue (required)**:
Closes #4832 

**Steps necessary to review your pull request (required)**:

- Pull branch, run app
- Visit new test page: http://localhost:4000/components/datagrid/test-alerts-escaped-html.html
- Notice data is present in Alert w Text field because the range value is now HTML-escaped. Before only the data value was escaped and this resolved as a mismatch.
- go to http://localhost:4000/components/datagrid/example-filter.html
- test the status column is rendered with french text and that the filter works here

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
I'm thinking that they might want us to do this from inside the Alert Formatter code https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.formatters.js#L577

But lets see if it flies i made a comment here:
https://github.com/infor-design/enterprise/issues/4832#issuecomment-901139308

Did you try the NG part of it and see?

**Comment by davidcarlsonberg** [comment]
> I'm thinking that they might want us to do this from inside the Alert Formatter code https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.formatters.js#L577
> 
> But lets see if it flies i made a comment here:
> [#4832 (comment)](https://github.com/infor-design/enterprise/issues/4832#issuecomment-901139308)
> 
> Did you try the NG part of it and see?

Nope, how would I go about that?

**Comment by tmcconechy** [comment]
i mean on the issue https://github.com/infor-design/enterprise/issues/4832#issue-805571855 can download his zip 

Do you have https://github.com/infor-design/enterprise-ng setup? If not clone it local and then

- copy his file in and replace the one there and then run

```
npm i
npm run build
npm run start
```

Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic 

it looks like hes doing it this way `{ value: "En file d\'attente", label: "En file d\'attente" }`

**Review by tmcconechy — COMMENTED** [review]
Looks good! But we need to update a couple images because the data changed:
https://github.com/infor-design/enterprise/pull/5529/checks?check_run_id=3377378344

👍🏻

**Review by ericangeles — APPROVED** [review]
Looks good! 🍌

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
