### PR TITLE
7606 - Add new editor designs

### LINKED ISSUE #7606: Editor: Design Cleanup for Alabaster
**Describe the bug**
Need to finish up alabaster theme fixes for the Editor component

- Editor -> https://main-enterprise.demo.design.infor.com/components/editor/example-index.html

**Expected behavior**

Editor: https://www.figma.com/file/8ekRxSWEbFxDzmvzraB1LH/Rich-Text-Editor?type=design&node-id=518-314&mode=design&t=aaj0rcFpsCQHH7lJ-0

See: https://jira.infor.com/browse/IDS-1335

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added new styles for the editor component. Mainly around buttons and toolbar. (note Datagrid split in a second issue)
But also changes some link styles and popup menu in dark mode

**Related github/jira issue (required)**:
Fixes #7606 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/editor/example-index.html
- try all modes light, dark, contrast (contrast theme not important at all but should not break)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — APPROVED** [review]

**Comment by tmcconechy** [comment]
@talkaboutdesign do you and Lauren want to review (dont know her github ID) see https://7606-editor-datagrid-designs-enterprise.demo.design.infor.com/components/editor/example-index.html

Made some comments as we discussed a few changes i left out that did'nt quite work in the figma

**Comment by ericangeles** [comment]
@laurensteiger

**Comment by laurensteiger** [comment]
Qa can be seen [here.](https://www.figma.com/file/8ekRxSWEbFxDzmvzraB1LH/Rich-Text-Editor?type=design&node-id=619-4486&mode=design) @tmcconechy

**Review by clayinfor — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@laurensteiger fixed all the points except

1. could not figure out a way to not overline the line but it is smoothed out with slightly closer colors
2. because the outside border is the same as input fields the bottom border is slightly lighter (light mode outside is slate 04 but the border bottom is slate03). This is to match input fields as discussed on teams

**Comment by laurensteiger** [comment]
Looks good to me!

**Comment by talkaboutdesign** [comment]
@laurensteiger make sure your file reflects the final state of this. We need this to be updated in Figma Library as well. Can you make a jira issue and assign Michael to it.

**Comment by tmcconechy** [comment]
Merging as approved previously

**Comment by laurensteiger** [comment]
> @laurensteiger make sure your file reflects the final state of this. We need this to be updated in Figma Library as well. Can you make a jira issue and assign Michael to it.

ok will work on it now

**Comment by laurensteiger** [comment]
@tmcconechy update just realizing now that upon hover the azure selected state is not AA or AAA accessible. Can we change the selected azure state to azure8?
Screenshot 2023-08-23 at 3 25 18 PM

**Comment by laurensteiger** [comment]
same for dark mode. needs to be azure 02 to pass AA on hover

**Comment by talkaboutdesign** [comment]
@laurensteiger @tmcconechy before making this change what are accessibility guidelines on hover states? 

**For example here:** https://accessibleweb.com/question-answer/what-are-the-contrast-requirements-for-an-elements-focus-mouseover-select-states/

Let's pause on this. Because this affects all components with azure color and slate as hover.

**Comment by tmcconechy** [comment]
@talkaboutdesign @laurensteiger we could make it all azure 02 for any colors in dark mode. If we really need that mode to pass accessibility. The requirement is just that the text / on background passes. No matter what the state. For hover it can be more subtle and not even change color as long is it doesnt get invisible contrast wise or go below the ratio

@jbrcna I'll look at the firefox issue later. But the links i had discussed not changing with @laurensteiger so that part in the design doc can be ignore

**Comment by laurensteiger** [comment]
@tmcconechy ok so if it only has to be accessible on bg, i think we should be good to go with the editor. Just want to double check so tagging @talkaboutdesign

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy

**Comment by laurensteiger** [comment]
@tmcconechy talked to @talkaboutdesign on this, I am currently working on hover work so the hover work will help determine this eventually.

**Pull request merged**
