### PR TITLE
7164 - Collapse button adjustments in mobile

### LINKED ISSUE #7164: Toolbar-flex: searchfield collapse button issue in mobile
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-centered-content.html?theme=new&mode=dark&colors=0066D4
2. Click on '.searchfield'
4. See error, Notice the missing border
5.  Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-centered-content.html?theme=new&mode=contrast&colors=003876
6. Click on '.searchfield'
7. See error, Notice the missing border
8. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-centered-content.html?theme=classic&mode=dark&colors=2578a9
9. Click on '.searchfield'
10. See error. Notice the collapse button is not visible

**Expected behavior**

**Version**

image

**Screenshots**
`New theme dark mode`
image

`New theme high contrast mode`
image

`Classic theme dark mode`
image

**Platform**
mobile

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Color and alignment adjustments for collapse button in mobile

**Related github/jira issue (required)**:

Closes #7164 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Switch to mobile
- Go to: http://localhost:4000/components/toolbar-flex/example-centered-content.html
- Click on searchfield, collapse button should be seen, button borders should be visible
- Check all versions and modes

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
The only issue i see is the collapse button has a wierd color.

Screenshot 2023-02-17 at 9 46 34 AM

I think just make it match the border color of the rest of the field?

**Review by andriivarhanov — COMMENTED** [review]
I'm not quite sure, but maybe we make icon color same color as the border, like a secondary button
image

**Comment by tmcconechy** [comment]
Yeah i think we can make this like any button (same style and states as the icon button on https://main-enterprise.demo.design.infor.com/components/button/example-index.html )

**Review by andriivarhanov — APPROVED** [review]
looks good to me

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
