### PR TITLE
6014 - Clear icon adjustments in searchfield

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjustments in searchfield for go and category button in flex toolbar

**Related github/jira issue (required)**:

Addresses https://github.com/infor-design/enterprise/issues/6014#issuecomment-1446731618

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
- Check that searchfield icons are aligned
- Check in versions and modes

### CODE REVIEW

**Review by tjamesallen15 — DISMISSED** [review]

**Comment by ericangeles** [comment]
Looks like a pixel gap?

Screen Shot 2023-03-02 at 8 53 30 PM

**Comment by ericangeles** [comment]
Another thing in classic http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=classic&mode=light&colors=default. When you hover on `Non-Collapsible Searchfield Toolbar Flex - With Go Button`, the border disappears.

**Comment by ericangeles** [comment]
@yohannahbautista am still seeing the border disappears when hovering in classic.

Screen Shot 2023-03-03 at 3 09 23 PM

**Comment by tmcconechy** [comment]
Screenshot 2023-03-03 at 9 54 52 AM

In classic mode if i focus it i see one side change color... Looks a little wierd but not a huge deal

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — COMMENTED** [review]
In classic mode. I still see the buttons in two different colors

http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=classic&mode=light&colors=default

Screenshot 2023-03-06 at 9 31 26 AM

I think make them both the same color as the go button, and align the X in the center with the text.

**Comment by tmcconechy** [comment]
@yohannahbautista The x is aligned now. But some minor tweaks might be good.

1. In classic mode if i focus the input the right side is a different color
2. In classic mode the search icon feels very  large (compared to the one above)
3. In new mode also if i focus the input the right side is a different color

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
