### PR TITLE
8421 - Fix tags close button alignment

### LINKED ISSUE #8421: Multiselect: x icon is not aligned
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/multiselect/example-compact.html
2. Click on Multiselect (with Tags)
3. See error

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

classic theme
image

**Platform**
all

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes tags close button alignment

**Related github/jira issue (required)**:
Fixes #8421 

**Steps necessary to review your pull request (required)**:
- review the x on http://localhost:4000/components/multiselect/example-compact.html it should be aligned in classic and new theme
- review the x on http://localhost:4000/components/tag/example-index.html it should be aligned in classic and new theme

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Tag/s alignment is a bit off in RTL
- Border in the disabled tag is broken

image


https://github.com/infor-design/enterprise/assets/102151352/45e3ba6e-855b-4116-947a-08c32d58d298

**Comment by tmcconechy** [comment]
@glenlieorillo should be fixed now, please recheck. 👍🏻

**Review by jbrcna — APPROVED** [review]
image
image
image
image

**Comment by jbrcna** [comment]
the issue is now fixed. However, the arrow in disabled dropdown overlaps in firefox browser
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Mac Chrome - Classic (same issues in Edge and Safari)**
- x button is cut off
image

**Mac Firefox - Classic**
- Misalignment of label and x button
image

**Comment by tmcconechy** [comment]
ok @jbrcna @glenlieorillo please try again, fixed the firefox and improved classic a little

**Comment by jbrcna** [comment]
image

image

image

image


**RTL**
this is now fixed https://github.com/infor-design/enterprise/pull/8424#issuecomment-1933398628
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
when not in compact mode the ellipsis is not shown
image
misaligned x icon 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://8421-multiselect-x-enterprise.demo.design.infor.com/components/multiselect/example-compact.html

https://8421-multiselect-x-enterprise.demo.design.infor.com/components/tag/example-index.html - APPROVED

**Mac Firefox**
- ellipses and dropdown icon overlapped.
image

- Still failing (https://8421-multiselect-x-enterprise.demo.design.infor.com/components/multiselect/example-compact.html?theme=classic&mode=light&colors=default&locale=ar-SA)

image

**Mac Chrome**
image

- RTL Classic - x icon is cut-off
image

**Comment by tmcconechy** [comment]
@jbrcna can we just make a new issue for the ellipsis text im not even really seeing it but also it is out of scope.
Since we have other priorities lets raise any additional issue seperate. Im actually not seeing anything wrong on my end.

**Pull request merged**
