### PR TITLE
8762 - Cell Value Hyperlink Click

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix cell value from argument passed on hyperlink click.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8762

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-cell-click-args.html
- Open `Developer Console`
- Click hyperlink, check the cell value from object in the console (should be 2)
- Click approval button, check the cell from the object in console (should be 12)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — APPROVED** [review]
image

**Comment by n-ace-ancog** [comment]
@tjamesallen15 

When clicking on the hyperlink it says the cell is 2, but when its the approved button its 12. Is there a hidden column in between or my numbering is wrong?

**Clicking the hyperlink** - results in 2 if the starting index is 0
image

**Clicking the approved button** - results in 12 if the starting index is 1, but should be 11 if starting index is 0
image

**Comment by tjamesallen15** [comment]
> @tjamesallen15
> 
> When clicking on the hyperlink it says the cell is 2, but when its the approved button its 12. Is there a hidden column in between or my numbering is wrong?
> 
> **Clicking the hyperlink** - results in 2 if the starting index is 0 image
> 
> **Clicking the approved button** - results in 12 if the starting index is 1, but should be 11 if starting index is 0 image

Its correct. I just tried checking the changelogs and see 13 columns. See below
image

**Review by n-ace-ancog — DISMISSED** [review]
Thanks for clearing it up @tjamesallen15! Working as expected on my end.

**Review by jbrcna — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Pull request merged**
