### PR TITLE
8036 - Adjusted dismissible icon for multiselect dropdown tags.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Color for the dismissible or "X" icon in the tags of the disabled multiselect dropdown component did not match the text color. Adjusted styling to match the color as well as some adjustments to the positioning of the button.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/8036

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/multiselect/example-index.html?theme=new&mode=contrast&colors=default
- Dismissible or "X" icon color should match the text color for the disabled multiselect.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
image

**Review by janahintal — DISMISSED** [review]
Approving 
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
the icon color is now fixed. however, the x icon is not properly aligned when using firefox browser with classic theme
image

**Comment by RJ-Csc** [comment]
Hello @jbrcna. Looks good on my end.
image

**Review by jbrcna — APPROVED** [review]
approving. thanks @RJ-Csc . awesome!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
hey @RJ-Csc can you duplicate the styles on http://localhost:4300/ids-multiselect/example.html

Screenshot 2023-11-10 at 9 59 29 AM
Screenshot 2023-11-10 at 9 59 42 AM

For disabled as they look better IMHO. You will need to run https://github.com/infor-design/enterprise-wc to see it tho. The example site has an issue https://main.wc.design.infor.com/ids-multiselect/example.html

Also i noticed when you select a tag in the non-disabled one the size of the field shuffles a but.

cc @ericangeles in case he needs to explain further

**Review by max-hizon — COMMENTED** [review]
Works as expected

image

**Review by jbrcna — APPROVED** [review]

**Comment by ericangeles** [comment]
@infor-design/qa, please review it again once @RJ-Csc addresses @tmcconechy's request for a change. Let me know if you have any questions here, @RJ-Csc.

**Review by tmcconechy — APPROVED** [review]
Very nice

**Pull request merged**
