### PR TITLE
Update respective test dependencies versions

### PR DESCRIPTION
**Pull request by d-g-h**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updates dependencies, and squashes deprecation notice generated by Webpack. Fix utilizes beta software, underlying source fix seems OK, simply upgrades Webpack

**Steps necessary to review your pull request (required)**:
`rm -rf node_modules`
`npm install`
`npm run test`, locally.

### CODE REVIEW

**Comment by d-g-h** [comment]
> info using node@v8.11.3

@davidcarlsonberg Where is that log from? Local, I guess, as the CI is on 10, can you try `nvm use 10`?

**Comment by davidcarlsonberg** [comment]
re: https://github.com/infor-design/enterprise/pull/634#issuecomment-414712891
@d-g-h That's my local log outputted by the test. Followed your instructions and here is the newest:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dberg2/.nvm/versions/node/v10.9.0/bin/node',
1 verbose cli   '/Users/dberg2/.nvm/versions/node/v10.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'e2e:ci' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'pree2e:ci', 'e2e:ci', 'poste2e:ci' ]
5 info lifecycle ids-enterprise@4.10.0-dev~pree2e:ci: ids-enterprise@4.10.0-dev
6 info lifecycle ids-enterprise@4.10.0-dev~e2e:ci: ids-enterprise@4.10.0-dev
7 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: unsafe-perm in lifecycle true
8 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: PATH: /Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dberg2/Projects/enterprise/node_modules/.bin:/Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dberg2/Projects/enterprise/node_modules/.bin:/Users/dberg2/.nvm/versions/node/v10.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: CWD: /Users/dberg2/Projects/enterprise
10 silly lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Args: [ '-c',
10 silly lifecycle   'npm run webdriver:update && npx protractor test/protractor.ci.conf.js' ]
11 silly lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Returned: code: 1  signal: null
12 info lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Failed to exec e2e:ci script
13 verbose stack Error: ids-enterprise@4.10.0-dev e2e:ci: `npm run webdriver:update && npx protractor test/protractor.ci.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid ids-enterprise@4.10.0-dev
15 verbose cwd /Users/dberg2/Projects/enterprise
16 verbose Darwin 17.7.0
17 verbose argv "/Users/dberg2/.nvm/versions/node/v10.9.0/bin/node" "/Users/dberg2/.nvm/versions/node/v10.9.0/bin/npm" "run" "e2e:ci"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error ids-enterprise@4.10.0-dev e2e:ci: `npm run webdriver:update && npx protractor test/protractor.ci.conf.js`
22 error Exit status 1
23 error Failed at the ids-enterprise@4.10.0-dev e2e:ci script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tmcconechy** [comment]
Seems like you should use node 9 or node 10...Thats what i tested on previously (not node 8)

**Comment by tmcconechy** [comment]
Actually im getting...

```
[11:45:08] E/configParser - Error: The module '/Users/tmcconechy/Dev/enterprise/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

On node 9

**Comment by d-g-h** [comment]
I believe we need to node 10 now. Especially, if you installed node-sass with node 10, if you installed node-sass with node 9, you can use that. Can't go back and forth without a complete reinstall though... as it overwrites the node-sass bindings

**Comment by tmcconechy** [comment]
OK, Cool. Yeah, it seems to work ok for me on 10.8.0. I wonder if you need to do...

```
npm prune && npm install
```

After changing node or blow away the node_modules and do npm install?

**Comment by d-g-h** [comment]
@davidcarlsonberg Is the demo server running aka `npm start`? If so, in a separate window/terminal, run `npm run e2e:ci`. That needs to be running for the e2e tests.

I get the same message if it's not running...

```sh
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise@4.10.0-dev e2e:ci: `npm run webdriver:update && npx protractor test/protractor.ci.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise@4.10.0-dev e2e:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dhall1/.npm/_logs/2018-08-21T15_51_58_722Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise@4.10.0-dev test: `npm run mdlint && npm run eslint && npm run functional:ci && npm run e2e:ci`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise@4.10.0-dev test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dhall1/.npm/_logs/2018-08-21T15_51_58_772Z-debug.log
```

Yeah, sorry, locally, we just didn't want to prestart the local server for you, as it hard to stop... it if it's a sorta like a runaway process. 

The CI/Travis does this, FYI...

https://github.com/infor-design/enterprise/blob/master/.travis.yml#L24

`  - if [ $TEST_SUITE = e2e ]; then (npm run quickstart &) && sleep 5; fi` ... etc

**Comment by d-g-h** [comment]
@tmcconechy I `rm -rf node_modules`

**Comment by davidcarlsonberg** [comment]
@d-g-h Demo server was running, yes. `npm run e2e:ci` log below:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dberg2/.nvm/versions/node/v10.9.0/bin/node',
1 verbose cli   '/Users/dberg2/.nvm/versions/node/v10.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'e2e:ci' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'pree2e:ci', 'e2e:ci', 'poste2e:ci' ]
5 info lifecycle ids-enterprise@4.10.0-dev~pree2e:ci: ids-enterprise@4.10.0-dev
6 info lifecycle ids-enterprise@4.10.0-dev~e2e:ci: ids-enterprise@4.10.0-dev
7 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: unsafe-perm in lifecycle true
8 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: PATH: /Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dberg2/Projects/enterprise/node_modules/.bin:/Users/dberg2/.nvm/versions/node/v10.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle ids-enterprise@4.10.0-dev~e2e:ci: CWD: /Users/dberg2/Projects/enterprise
10 silly lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Args: [ '-c',
10 silly lifecycle   'npm run webdriver:update && npx protractor test/protractor.ci.conf.js' ]
11 silly lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Returned: code: 1  signal: null
12 info lifecycle ids-enterprise@4.10.0-dev~e2e:ci: Failed to exec e2e:ci script
13 verbose stack Error: ids-enterprise@4.10.0-dev e2e:ci: `npm run webdriver:update && npx protractor test/protractor.ci.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dberg2/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid ids-enterprise@4.10.0-dev
15 verbose cwd /Users/dberg2/Projects/enterprise
16 verbose Darwin 17.7.0
17 verbose argv "/Users/dberg2/.nvm/versions/node/v10.9.0/bin/node" "/Users/dberg2/.nvm/versions/node/v10.9.0/bin/npm" "run" "e2e:ci"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error ids-enterprise@4.10.0-dev e2e:ci: `npm run webdriver:update && npx protractor test/protractor.ci.conf.js`
22 error Exit status 1
23 error Failed at the ids-enterprise@4.10.0-dev e2e:ci script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Pull request merged**
