### PR TITLE
5791 - Fix the height of collapse button in non-collapsible searchfield

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the height of the collapse button in the non-collapsible toolbar searchfield on a smaller viewport.

I noticed that this kind of issue is always going back so I created a visual test for it. The issue is either the height of it or the position of the close button.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5791

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield
- Resize the browser to `766px` or below
- Click the `icon search` of Collapsible Searchfield Toolbar Flex
- The searchfield and the collapse button should have the same height
- Click the `icon search` of Non-Collapsible Searchfield Toolbar Flex
- The searchfield and the collapse button should have the same height
- Test in Classic
- Test in different browsers

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by yohannahbautista** [comment]
Looks good! Though I have a question: Is the x button supposed to be that near the edge in the new version? It looks odd when comparing it to the classic one
Screen Shot 2021-11-03 at 5 45 56 PM
Screen Shot 2021-11-03 at 5 46 31 PM

**Comment by ericangeles** [comment]
I am not 100% about that but we can ask @tmcconechy. Is it by design?

**Comment by tmcconechy** [comment]
I think it should be further the right? So maybe need to fix that. Should be the same as the distance of any of the other lookups

**Review by yohannahbautista — APPROVED** [review]
Looks good!

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
