### PR TITLE
8963 - Fixed special characters being encoded in editor

### LINKED ISSUE #8963: Datagrid: Encoded special characters on inline editors
**Describe the bug**
When inputting special characters (& ' < >) in inline editors, the characters become encoded.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html
2. Type any special character on a field
3. Focus out of the field and focus in (click)
4. Notice encoded characters
5. Repeat step 3 many times
6. Notice added encoded characters

**Expected behavior**
Special characters are not encoded

**Version**

- soho-xi-version: v4.98.0

**Screenshots**

https://github.com/user-attachments/assets/7d9e0ad6-6bc6-49fd-807c-ccd71a452ba4

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed escape HTML so that special characters won't be encoded

**Related github/jira issue (required)**:

Closes #8963 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-editable-with-inline-editor.html
- Type special characters in Activity  (& ' < >) 
- Focus out
- Focus in
- Characters should stay the same

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — DISMISSED** [review]
Working on my end.

https://github.com/user-attachments/assets/d436a359-6e0f-487d-981c-a4fdcdb9de93

**Comment by ericangeles** [comment]
Could you add test here, @yohannahbautista ?

**Review by tmcconechy — DISMISSED** [review]
Looks good (agree with the tests idea)

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/33f841f9-fdb1-4f84-b770-523f9c493a44

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
