### PR TITLE
8275 - Tab Add Tab Button

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix tabs add tab button focus.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8275

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs/example-add-tab-button.html
- Click the `+` button
- Focus Border should look good

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 I see a couple style issues can you check with figma:

https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.8?type=design&node-id=35787-106917&mode=design&t=PcEjm1vR6tYjroyn-0


1) The icon looks like the wrong X? And/Or wrong size?

Screenshot 2024-01-08 at 10 41 08 AM

2) I also see when i hover the tabs the tab shape looks wrong (too much space on top)
Screenshot 2024-01-08 at 10 40 51 AM

**Comment by tmcconechy** [comment]
Looking better. But i think the + looks like it floats a bit much more in space
Screenshot 2024-01-11 at 1 31 12 PM

Can we do it more like above (in figma), also still looks like the wrong icon? 

Also the X looks like to could be moved more to the right and centered vertically

Screenshot 2024-01-11 at 1 31 19 PM

**Comment by tjamesallen15** [comment]
> Looking better. But i think the + looks like it floats a bit much more in space Screenshot 2024-01-11 at 1 31 12 PM
> 
> Can we do it more like above (in figma), also still looks like the wrong icon?
> 
> Also the X looks like to could be moved more to the right and centered vertically
> 
> Screenshot 2024-01-11 at 1 31 19 PM

Will do @tmcconechy , I laugh about your comment in the add button in space. Good giggles. Hahaha.

**Comment by tjamesallen15** [comment]
@tmcconechy   , i'm done with the first one. However the second request you want, it seems like the same with the figma, Giving screenshots below.

Figma
image

Local
image

**Comment by tmcconechy** [comment]
ok @tjamesallen15 looks pretty good now. except only two things

1. the blue line should be connected to the bottom (its a pixel or two up)

Good:
Screenshot 2024-01-16 at 11 46 55 AM
Wrong:
Screenshot 2024-01-16 at 11 47 02 AM

2. Instead of using the + as a character should use the svg icon then it will look the same - i.e. its not using the icon

Screenshot 2024-01-16 at 11 48 26 AM

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
image

image

image

image

**Review by janahintal — APPROVED** [review]
image
image

**Pull request merged**
