### PR TITLE
7210 - Searchfield adjustments for collapse

### LINKED ISSUE #7210: Header: Expand / Minimize icon become invisible after tabbing from the search field
**Describe the bug**
Header: Expand icon become invisible after tabbing from the search field 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-flex-toolbar.html?theme=classic&mode=light&colors=2578a9
2. Minimize the screen 
3. Type in the search field 
4. Click Tab 

**Expected behavior**
Expand / Minimize button should be visible 

**Version**
ids-4.81-dev

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjustments in searchfield icons in header

**Related github/jira issue (required)**:

Closes #7210 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Minimize screen to be less than around 700px
- Go to: http://localhost:4000/components/header/example-flex-toolbar.html?theme=classic&mode=light&colors=2578a9
- Open searchfield
- Collapse should be there
- Type on searchfield
- Tab
- Collapse should be there

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Noticed two issues (only tried classic mode but do try both new and classic)

1. the collapse is cut off
Screenshot 2023-03-09 at 10 00 33 AM
2. if you focus the adjacent button it looks overlaping on the search and pushed over
Screenshot 2023-03-09 at 10 00 47 AM

**Comment by tjamesallen15** [comment]
Tried checking this too based on the Tim's comments

1. Collapse is clean in New Theme

2. Focus issue also displays on new theme

3. Other colors are clean and modes

**Comment by tmcconechy** [comment]
Looks good but i did see one more thing...

Screenshot 2023-03-10 at 2 12 10 PM

If you are on desktop size and put text in and exit the field. the text is hard to see. In this case it should stay with the white background.

Screenshot 2023-03-10 at 2 12 10 PM

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
LGTM 🍌

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
