### PR TITLE
2281 - Fix for Datagrid time filter [v4.19.x]

### LINKED ISSUE #2281: Datagrid: Time filter does not filter correctly client side.
**Describe the bug**

**To Reproduce**
1. Go to 'components/datagrid/test-filter-datetime-client-side.html'
2. Filter by the time field, eg greater than 1:00 AM, 1:00 PM

**Expected behavior**
The filtering is based on just the time 

**Version**
4.19.x

**Screenshots**
image
image

**Platform**
All devices and browsers

### PR DESCRIPTION
**Pull request by marknolaninfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Filter times on the client 

**Related github/jira issue (required)**:
Closes #2281 

**Steps necessary to review your pull request (required)**:
1. Go to 'http://localhost:4000/components/datagrid/test-filter-datetime-client-side.html'
2. Filter by the time field, eg greater than 1:00 AM, 1:00 PM

### CODE REVIEW

**Comment by tmcconechy** [comment]
4.19.x and Master are now in sync. I changed base on this to master and tested and it seems fine.
Thanks!

**Comment by tmcconechy** [comment]
Actually a CHANGELOG entry would be appreciated.

**Comment by marknolaninfor** [comment]
Can this also go into 4.19?

**Comment by tmcconechy** [comment]
@marknolaninfor Yes since its a small thing. The rest was too risk for cut off. I will reraise as we botched the re-base.

**Comment by tmcconechy** [comment]
Closing in favor of https://github.com/infor-design/enterprise/pull/2307

**Pull request closed without merging**
