### PR TITLE
8431 - Fix axis labels visibility

### LINKED ISSUE #8431: Bar: Axis label visibility
**Describe the bug**

There are some cases where the axis label is not visible because it uses the `em` unit. Given that `em` is dependent on the parent's font-size, it becomes essential to explicitly include the font-size property within the `axis-label` element. This ensures that the axis label does not rely on other parent elements for its font size, mitigating the possibility of encountering situations where the parent elements lack a specified font size.

**Expected behavior**
We need to explicitly add font-size in the `<g class="axis-labels">`

```csss
.axis-labels {
  font-size: 1.6rem; // based in the .row font-size but open for discussion
}
```

**Version**

- ids-enterprise: 4.88.0

**Additional context**
Reported here https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1706860686874?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1706860686874&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1706860686874

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes axis labels visibility by adding font-size in `axis-labels` container.

**Related github/jira issue (required)**:

Closes #8431

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/bar/example-axis-labels.html
- You should be able to see axis labels
- Inspect the element and find `axis-labels` element
- It should have `font-size` property with `1.5rem` value

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Saw an error on hierarchy in tests but if it comes back can skip as eventually will add playwright in here

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Comment by ericangeles** [comment]
@jbrcna its in the parent. `axis-labels`. Check it again.

**Review by jbrcna — DISMISSED** [review]
thanks @ericangeles . value is correct
image

**Review by glenlieorillo — APPROVED** [review]
image

image

**Review by janahintal — DISMISSED** [review]
image

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
Minor lint issue in the change log 👍🏻

**Review by janahintal — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
image

**Review by tmcconechy — DISMISSED** [review]

**Review by janahintal — DISMISSED** [review]
image

**Pull request merged**
