### PR TITLE
8715 - Add new dependencies and icons

### LINKED ISSUE #8715: Icons: Add new icons
**Describe the bug**
Run the new pipeline to add some new icons. The following icons are new https://www.figma.com/design/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?node-id=465-422&t=7aGVy1Rbif3ZGPxb-0

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Add some new dependencies to keep things updated. Most importantly the design repo to get a few new needed icons

**Related github/jira issue (required)**:
Fixes #8715

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/icons/example-index.html
- search in dev tools on the DOM to find.
- the following are new icons: `user-remove`, `trending-down`, `snooze` `trending-up` `trend-left` `trend-right`

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Comment by ericangeles** [comment]
@jbrcna, did you re-install the package?

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Unable to find the new icons with https://8715-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html or via localhost

image

image

image

image

image

image

**Comment by jbrcna** [comment]
> @jbrcna, did you re-install the package?

no. I used this link https://8715-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html

**Comment by tmcconechy** [comment]
@jbrcna good point i forgot to update the file for the demo app to show them. It will work now but may take 40 mins to deploy to https://8715-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html

**Review by jbrcna — APPROVED** [review]
thanks for your prompt fix @tmcconechy . 
this is now working as expected.
image

**Pull request merged**
