### PR TITLE
NG1567 - Remove disabled prop in trigger button on enable call

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Remove disabled prop in trigger button on enable call

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1567

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/timepicker/test-states.html
- Click Disable
- Timepicker should be disabled
- Click Enable
- Timepicker should be enabled

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
cc @infor-design/qa

**Review by jbrcna — APPROVED** [review]
approving. 
this is also working in main
Large GIF (422x266)

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/b521cc8a-6e32-4fb9-8c11-2f36fcadfecb

**Review by janahintal — APPROVED** [review]

**Pull request merged**
