### PR TITLE
8504 - Fixed searchfield icon alignment in filter

### LINKED ISSUE #8504: Datagrid: Searchlist icon is missing in Safari and misaligned in Firefox
**Describe the bug**
The searchlist icon under `Product Id` column is misaligned in Mac Firefox and it is missing in Safari.

**To Reproduce**

1. Go to https://8363-datagrid-datefilter-enterprise.demo.design.infor.com/components/datagrid/test-filter-date-hide-days.html
2. Hover over the searchfield under Product ID column (Safari)
3. Notice the searchlist icon under Product ID column (Mac Firefox)

**Expected behavior**
Searchlist Icon should be present in Safari and aligned properly in Mac Firefox.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Mac Firefox

image

Safari

image

**Platform**
 - Safari and Mac Firefox

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed searchfield icon alignment in filter

**Related github/jira issue (required)**:

Closes #8504 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-filter-date-hide-days.html
- Check filter search icon
- Check in other browsers

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Mac Firefox**

Issue still exists.

https://github.com/infor-design/enterprise/assets/102151352/e7b65d4e-9364-4ebb-92e8-765c400ee785

- RTL
Searchfield and dropdown should have space in between.
image

Focus state doesn't fit within the searchfield.

- Mac Chrome
image

image

- Safari
image

**Review by tmcconechy — COMMENTED** [review]
Minor: I think it sits a bit high in chrome:

Screenshot 2024-03-26 at 12 55 33 PM

**Review by jbrcna — COMMENTED** [review]
image
However, this is working in main
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Issue still exists in Mac Firefox.
- Another issue, the table cells are not aligned.

https://github.com/infor-design/enterprise/assets/102151352/41f1245f-a138-4a0d-a519-3b31b6612797

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
changing row height and clicking search icon causes an issue
image

**Comment by jbrcna** [comment]
issue still exist in small row height
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Issue still exists.

- Table cells are misaligned
- Icon in `small` row height is a bit higher

https://github.com/infor-design/enterprise/assets/102151352/66d8cee0-faa7-4e19-9d23-dc0ed0669575

image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The icon seems to be aligned now, but the columns are not aligned.
**Safari**
image

**Windows Chrome**
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Table cells are still misaligned in `Extra Small` and `Small` row height.

http://localhost:4000/components/datagrid/test-filter-date-hide-days.html

https://github.com/infor-design/enterprise/assets/102151352/8c08aca2-78b8-4b25-80c4-884a24b1e605

https://8504-datagrid-search-enterprise.demo.design.infor.com/components/datagrid/test-filter-date-hide-days.html

https://github.com/infor-design/enterprise/assets/102151352/89cf7048-d419-403a-a35a-eb7d08edd5b3

**Pull request merged**
