### PR TITLE
5239 - Fix the position of clear filter icon when changing the row height

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the position of clear filter icon when chaning the row height and also when doing filtering for both themes.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5239

**Steps necessary to review your pull request (required)**:
- Pull this branch, build and run the app
- Go to http://localhost:4000/components/datagrid/test-lookup-filter
- Then open the lookup on `Product Id`
- Select any Product to trigger the clear filter icon
- Then change the row height to `Extra Small`
- The icon should properly centered in lookup field
- Test this to different row heights
- Then try to filter/sort the `Product Id` column
- It should stay to its position
- Test on both themes then repeat the steps

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Seeing one wierd thing about this @ericangeles 
- when you change between the small/med/normal row heights
- the filter value is lost in the field and the x goes away

Is that a new issue?

**Comment by ericangeles** [comment]
Hmm, that's one of the fix in this issue. Could you tell me how you reproduce it, @tmcconechy?

**Comment by tmcconechy** [comment]
- go to http://localhost:4000/components/datagrid/test-lookup-filter
- notice it has an X and text in the lookup column
- in the ... menu pick extra small (or any other row)
- notice it has missing X and text now and the grid is also filtered

Seems like it did this before looking on a branch but maybe we can check why the value disappears as it is out sync

**Comment by ericangeles** [comment]
Will take a look at it.

**Comment by deep7102** [comment]
I see same as @tmcconechy all other looks fine!

**Comment by ericangeles** [comment]
I see the issue now, @tmcconechy. That is another issue, but we can try to fix that too.

**Comment by tmcconechy** [comment]
Maybe not important right now then if it was there

**Pull request merged**
