### PR TITLE
2739 - Improve Uplift Application Menu / Accordion Hierarchy

### LINKED ISSUE #2739: Application Menu: Improve hierarchy in uplift (New Design)
**Describe the bug**

We have had reports of the hierarchy in uplift mode of the app menu. in soho it works as each section has a background color change. But in uplift design wants to adjust the spacing instead of a background.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift&variant=light&colors=0563C2
2. Expand the second item to see more heir achy items
4. See attached examples:
https://www.dropbox.com/s/n416uamxdphx3av/Screenshot%202019-09-04%2015.29.29.png?dl=0
https://www.dropbox.com/s/xxodwkhhxir14cq/Screenshot%202019-09-04%2015.30.09.png?dl=0

**Expected behavior**
A clearer hierarchy so you dont get lost in the menu

**Design Comments**

After a brief look it seems that implementation may be a bit off on both sides of the spectrum here, and that this problem was starting to get solved in the design but not communicated well. I’ll try to resolve here.

It seems that largely: alignment, vertical & horizontal spacing may be off in both LMK & IDS examples. The biggest problem in that is the vertical spacing and the lack of alignment in LVL 1 menu items.

New Design: 
https://inforus.invisionapp.com/share/QZTSFWVAFS2

Approx. Adjustment Log: https://github.com/infor-design/design-system/issues/409#issuecomment-528457527

- [x] Even distribution of HCM nav icons at the top.
- [x] Search bar hint text should more clearly tell the user what they can do. If this was a full HCM search then the text ‘search’ would work. However, since it’s nav items and sub pages it doesn’t seem appropriate or helpful. Push it further: an additional idea here is to have the user click in and then immediately get suggestions on what to search for, or things they’ve searched for in the past. For the interim, “Look up menu items” feels very appropriate to me.
- [x] Comfy-er search bar in general. Is consistent with selection / hover states for menu items as well. (40px H, 288 W, 6px Radius)
- [x] Some additional space between header & menu items. Visual separation. (40px vert)
- [x] Clear difference in padding on the left for menus with icons and without.
- [ ] For this menu example, active menu items take on the selected UI theme (instead of the azure). This is basically for theme consistency so that if this was the slate theme or the azure theme, we’d be using values from those families.
- [ ] LVL1 Selected menu item is
Text: bold, #fff @ 100% opacity
Bg: #fff @ 15% opacity
- [ ] LVL1 Hover menu item is
Text: Reg, #fff @ 100%
Bg: #fff @ 5%
- [ ] Vertical spacing between selected & hover states is 4px
- [ ] LVL1 Selected expanded menu item
Text: Bold, #fff @ 100%
Bg: #000 @ 20% Opacity
Chevron: #fff @ 100%
- [ ] Use Uplift-style chevron icons
- [ ] Use Uplift-style add / minus icons
- [ ] Expanded LVL1 sections have additional vertical spacing at bottom (56px)
- [ ] LVL2-6 Normal state menu item
Text: Regular, 14px, #fff @ 50% opacity
Icon: #fff @ 50% opacity
- [ ] LVL2-6 Selected / Hover menu item
Text: Reg, 14px #fff @ 100%
Bg: #fff @ 15%
- [ ] Explore using the provided alternative background colors to help visuals, although text indentation, lvl 1 expansion and text styling should solve for this issue sufficiently.

**Effected Version**
- ids-enterprise: [e.g. v4.21.0]

**Dev To Do**
- [ ] Build a new example page like the design showing HCM menu with actual hierarchy
- [ ] Use inspect in https://inforus.invisionapp.com/d/main#/console/18409050/382534032/inspect  to see any css details for the new design
- [ ] Code the uplift theme so that the menu looks as the new designs now.
- [ ] See if anything needs to be updated with indent in soho theme (the background we will leave as is so more just minor padding issues and any size issues)

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR makes changes to the Uplift Application Menu that greatly improves the visual hierarchy of its nested accordion headers and content.

**Related github/jira issue (required)**:
- Closes #2739 
- Related to infor-design/design-system#409

**Steps necessary to review your pull request (required)**:
Pull this branch, run `npm prune && npm i && npm start` for a clean install with the latest design system assets, Then check the Application Menu and its internal accordion's visual hierarchy to ensure it makes sense on the following samples:

_New Samples:_
- http://localhost:4000/components/applicationmenu/test-hcm?theme=uplift
- http://localhost:4000/components/applicationmenu/test-hcm?theme=uplift&variant=dark
- http://localhost:4000/components/applicationmenu/test-hcm?theme=uplift&variant=contrast
- http://localhost:4000/components/applicationmenu/test-hcm?theme=uplift&colors=0563C2
- http://localhost:4000/components/applicationmenu/test-hcm-icons?theme=uplift
- http://localhost:4000/components/applicationmenu/test-hcm-icons?theme=uplift&variant=dark
- http://localhost:4000/components/applicationmenu/test-hcm-icons?theme=uplift&variant=contrast
- http://localhost:4000/components/applicationmenu/test-hcm-icons?theme=uplift&colors=0563C2

_Personalized Role Switcher:_
- http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html?theme=uplift
- http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html?theme=uplift&variant=dark
- http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html?theme=uplift&variant=contrast
- http://localhost:4000/components/applicationmenu/test-personalized-role-switcher-long-title.html?theme=uplift&variant=dark&colors=0563C2

_Six Level Hierarchy Test:_
- http://localhost:4000/components/applicationmenu/test-six-levels?theme=uplift
- http://localhost:4000/components/applicationmenu/test-six-levels?theme=uplift&variant=dark
- http://localhost:4000/components/applicationmenu/test-six-levels?theme=uplift&variant=contrast
- http://localhost:4000/components/applicationmenu/test-six-levels?theme=uplift&colors=0563C2
- http://localhost:4000/components/applicationmenu/test-six-levels-icons?theme=uplift
- http://localhost:4000/components/applicationmenu/test-six-levels-icons?theme=uplift&variant=dark
- http://localhost:4000/components/applicationmenu/test-six-levels-icons?theme=uplift&variant=contrast
- http://localhost:4000/components/applicationmenu/test-six-levels-icons?theme=uplift&colors=0563C2

Make sure that all theme variants, personalization, and right-to-left alignment of the Application Menu all work.  All secondary functionality, such as tooltips on truncated headers, button alignments, etc should look good and function properly.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
This looks good just pused one change as the icon in the header needed to be changed from solid to the new "linear" icon version here or its impossible to see

Screen Shot 2019-10-01 at 11 07 08 AM

**Comment by kevinwhitedesign** [comment]
Hey guys love the work here, a few improvements I had in mind / QA items:

does this have to be this way where the focus states stay on until you click away? can this not have the focus state lingering? here's the example https://www.dropbox.com/s/vrfbwyhh6aiwtc3/Screenshot%202019-10-03%2013.52.26.png?dl=0

also a video example https://www.dropbox.com/s/mi26lfdrj3ecjr4/state-issues.mov?dl=0
 
looks like the active state was different in the provided design here:
https://www.dropbox.com/s/pr3lbravf2rv8hf/Screenshot%202019-10-03%2013.53.45.png?dl=0

I think the active state is important to remain #fff @ 15% because if the menu is themed it will work better.

also my hover state was #fff @5% opacity

bg for the whole menu was #252429 

this deep nav dropdown area was #000 @20% opacity
https://www.dropbox.com/s/wvu4f15zb7sqx54/Screenshot%202019-10-03%2013.59.01.png?dl=0

looks like we're going to need a lot more space(56px) for between deep nav items & 1st level nav items:
https://www.dropbox.com/s/9hjxa9z8uk9ljjl/Screenshot%202019-10-03%2014.00.28.png?dl=0

lastly, there should be an option without a 'deep nav dropdown area' as seen in the design here:
https://www.dropbox.com/s/gyesqcmuv3pacat/Screenshot%202019-10-03%2014.02.35.png?dl=0

**Comment by kevinwhitedesign** [comment]
lets get rid of this background as well: https://www.dropbox.com/s/1mgettcbsalw8yy/Screenshot%202019-10-03%2014.11.13.png?dl=0

I thought it made sense if it was 'sticky' but it's not

**Comment by EdwardCoyle** [comment]
Hi @kevinwhitedesign.  I want to address a couple of these more generally.

As far as colors go, as a rule we're not working with opacity channels on any of these standard theme colors.  This is mainly for compliance with accessibility requirements, but also to make sure we're using colors that have previously been defined in the design tokens, [as seen on our color palette example page](https://master-enterprise.demo.design.infor.com/components/colors/example-index.html?theme=uplift).  As far as our defaults go, we're strictly using design token colors in our SASS code with very few exceptions (and those that exist most likely shouldn't).  That's mainly the reason for things like the black selected (active?) state instead of the very dark gray.  It's definitely something we could change, but we'd need to talk about building that into the standard color palette we ship.  To my knowledge, a lot of those colors were specifically picked because combinations of them would pass WCAG 2.0 AA tests, which a lot of our consuming teams require.  

In the case of personalization, that rule changes a bit because it's not really possible to stay within the color palette definitions if we want to support any branding/theming.  Those personalized colors are also programatic in Enterprise, where there's a base color that gets various shades of luminosity generated along with it.  It's understood by the consuming teams that enabling personalization puts them at risk of not necessarily being 100% WCAG 2.0 AA compliant.

I'm wondering if we can work towards defining these requirements a bit in the designs?

Just as a quick specific sample:
> I think the active state is important to remain #fff @ 15% because if the menu is themed it will work better.

In the default light color scheme for Uplift, that would end up being darker than Slate10 on the color palette page.  In the current set of colors, Slate10 is what is making up the background in the "nested" accordion panes, and that's as dark as the color palette goes unless we choose straight-up black.

> bg for the whole menu was #252429

That's our Slate10.  If we went with this for the whole background, it would have kept us from going any darker with the background in the nested areas.

As far as some of these other bullets:

> does this have to be this way where the focus states stay on until you click away? can this not have the focus state lingering?

I'm guessing you mean that once something that was focused becomes selected/active, the focus state should disappear?  If so, it doesn't necessarily have to stay that way.  I thought this was built into the "hiding focus" system we have but I'll double check it.

> I think the active state is important to remain #fff @ 15% because if the menu is themed it will work better.

The personalized colors are currently going darker for the active state.  I can try to go lighter instead, which should at least be close the #fff @ 15%.  It's tricky because I think the personalization system tends toward white for the text, so certain color combos may be pretty tough to read, which is why I tended to go darker.

> looks like we're going to need a lot more space(56px) for between deep nav items & 1st level nav items:
https://www.dropbox.com/s/9hjxa9z8uk9ljjl/Screenshot%202019-10-03%2014.00.28.png?dl=0

I can adjust this.  Is this just for the spacing between the bottom of an open nested area and a top level menu?  This isn't the spacing between top level items in general?

> lets get rid of this background as well: https://www.dropbox.com/s/1mgettcbsalw8yy/Screenshot%202019-10-03%2014.11.13.png?dl=0

Can do, no prob

> lastly, there should be an option without a 'deep nav dropdown area' as seen in the design here:
https://www.dropbox.com/s/gyesqcmuv3pacat/Screenshot%202019-10-03%2014.02.35.png?dl=0

We have a lot of app menu samples like this.  One of these is http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?theme=uplift.  If you want to see the full list of current samples, you can use the directory listing on http://master-enterprise.demo.design.infor.com/components/applicationmenu/list

I think we might try to open a new issue for the next release to address these.

**Comment by tmcconechy** [comment]
Sounds good once we sort out these details I do suggest we make a new issue as this one is done and merged now

**Comment by kevinwhitedesign** [comment]
I'll have to get back to this soon

**Comment by kevinwhitedesign** [comment]
looks like we're going to need a lot more space(56px) for between deep nav items & 1st level nav items:
https://www.dropbox.com/s/9hjxa9z8uk9ljjl/Screenshot%202019-10-03%2014.00.28.png?dl=0

I can adjust this. Is this just for the spacing between the bottom of an open nested area and a top level menu? This isn't the spacing between top level items in general?


(the answer to this one is yes @EdwardCoyle)  It didn't have to do with the top level items

**Comment by tmcconechy** [comment]
@kevinwhitedesign lets just list all changed you want in a list on https://github.com/infor-design/enterprise/issues/2920 will make this not get missed.

**Pull request merged**
