### PR TITLE
7340 - More Fixes For Alabaster (no css class)Add patches for alabaster

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The main idea behind this change is that the teams cant easily add a color class to the header for alabaster. So instead we removed all alabaster rules and made it work in the personalization API. Also did quite a bit of testing and fixed related changes due to that.

@andriivarhanov please restest latest tab work due to merges...

Needed:

- [ ] QA testing
- [x] Fix any failing tests
- [x] Fix http://localhost:4000/components/button/example-index.html?colors=ffffff

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/7340

**Steps necessary to review your pull request (required)**:
- pull and run
- test http://localhost:4000 (modes/colors/version -> buttons/hover states/disabled ect)
- test http://localhost:4000/components/personalize (modes/colors/version
- test http://localhost:4000/components/header (modes/colors/version)
- test  http://localhost:4000/components/button/example-index.html?colors=ffffff and change color
- look for anything that seems subjectively "majorly off"

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
seeing some issues happened after merge:

- http://localhost:4000/components/personalize/example-form2.html?theme=classic&mode=contrast&colors=default classic theme high contrast header bg color

image

- http://localhost:4000/components/personalize/example-form2.html?colors=ffffff&theme=new&mode=light alabaster header personalized text color 

- http://localhost:4000/components/personalize/test-form2-short.html?theme=classic&mode=contrast&colors=default tabs disabled items color

**Comment by andriivarhanov** [comment]
@tmcconechy added some fixes personalized header related:
- hyperlink color in default mode on the page http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=light&colors=default
- text/icons color alabaster http://localhost:4000/components/personalize/example-form2.html?colors=ffffff&theme=new&mode=light
- header tabs disabled items color (alternate, horizontal) all modes http://localhost:4000/components/personalize/example-form-landmark2.html?colors=ffffff&theme=classic&mode=light

**Comment by glenlieorillo** [comment]
### **Header (Light Mode)**


### **Breadcrumbs are hard to read**

- go to [header/example-breadcrumbs](https://main-enterprise.demo.design.infor.com/components/header/example-breadcrumbs.html)
- hover over breadcrumbs

image


https://user-images.githubusercontent.com/102151352/228521002-3d482a48-c8f8-4530-b352-d92765520bdb.mov


### **Icon Issue in Alabaster (_All related examples_)**

- go to [header/example-disabled-buttons](https://main-enterprise.demo.design.infor.com/components/header/example-disabled-buttons.html) 
- change color to Alabaster
- click hamburger icon
- click any on the list
- click on the white part of the page
- notice the highlighted icon

https://user-images.githubusercontent.com/102151352/228533676-a719c8a2-cca9-4f87-b771-0df0fc14868c.mov


- go to [header/example-drilldown](https://main-enterprise.demo.design.infor.com/components/header/example-drilldown.html)
- change color to Alabaster
- click hamburger icon
- click any on the list
- click on the white part of the page
- notice the highlighted icon


https://user-images.githubusercontent.com/102151352/228535284-d869cadd-2ed5-4f5d-9317-c055d87c6f5c.mov



### **Buttons are unreadable when hovered**

- go to [header/example-flex-toolbar](https://main-enterprise.demo.design.infor.com/components/header/example-flex-toolbar.html)
- hover over buttons, ellipses

image


- go to [header/example-header-with-multiple-buttons-and-searchfield](https://main-enterprise.demo.design.infor.com/components/header/example-header-with-multiple-buttons-and-searchfield.html)
- hover over buttons, ellipses

image

### **'View Profile' button is unreadable in Alabaster**

- go to [header/example-record-id](https://main-enterprise.demo.design.infor.com/components/header/example-record-id.html)
- change color to Alabaster
- hover over the 'View Profile' button

image

### **'Advanced Search' link is unreadable**

- go to [header/example-searchfield-large](https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-large.html)
- Notice the 'Advanced Search' link

image

### **Wizard is unreadable**

- go to [header/example-wizard](https://main-enterprise.demo.design.infor.com/components/header/example-wizard.html)

https://user-images.githubusercontent.com/102151352/228552343-fd085add-fcfd-4bf6-aaa4-7c107dc2ec8a.mov

**Comment by tmcconechy** [comment]
@ericangeles would you be able to fix the comments on @glenlieorillo side - i think i fixed @andriivarhanov 's points.
Thanks in advance!

**Comment by ericangeles** [comment]
@glenlieorillo did you test it locally? Most of these issues are already resolved in this PR but I noticed a couple of issues that needs to be fixed. Please test it locally and not in the main.

**Comment by glenlieorillo** [comment]
> @glenlieorillo did you test it locally? Most of these issues are already resolved in this PR but I noticed a couple of issues that needs to be fixed. Please test it locally and not in the main.

@ericangeles I tested this on main-enterprise. Will retest today in localhost.

**Comment by glenlieorillo** [comment]
### **Header (Light Mode)**
tested in localhost
http://localhost:4000/components/header/list



**Breadcrumbs are hard to read**

- go to [header/example-breadcrumbs](http://localhost:4000/components/header/example-breadcrumbs.html)
- hover over breadcrumbs

image

**Icon Issue in Alabaster (_All related examples_)**

- go to [header/example-disabled-buttons](http://localhost:4000/components/header/example-disabled-buttons.html) 
- change color to Alabaster
- click hamburger icon
- click any on the list
- click on the white part of the page
- notice the highlighted icon


https://user-images.githubusercontent.com/102151352/228796279-7e90cd49-0526-48f9-90c8-0be3ff41840c.mov


### **Buttons are unreadable when hovered**

- go to [header/example-flex-toolbar](http://localhost:4000/components/header/example-flex-toolbar.html)
- hover over buttons, ellipses


https://user-images.githubusercontent.com/102151352/228796747-3d94c234-ed0f-478f-9885-0a0684c8a41f.mov


- go to [header/example-header-with-multiple-buttons-and-searchfield](http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html)
- hover over buttons, ellipses


https://user-images.githubusercontent.com/102151352/228797149-defa4c4a-f899-4c1a-b2b3-5d76d9f28d72.mov

**'View Profile' button is unreadable in Alabaster**

- go to [header/example-record-id](http://localhost:4000/components/header/example-record-id.html)
- change color to Alabaster
- hover over the 'View Profile' button

image


**'Advanced Search' link is unreadable**

- go to [header/example-searchfield-large](http://localhost:4000/components/header/example-searchfield-large.html)
- Notice the 'Advanced Search' link

image

**Wizard is unreadable**

- go to [header/example-wizard](http://localhost:4000/components/header/example-wizard.html)

image

**Comment by glenlieorillo** [comment]
**Personalize (Light Mode)**
tested in localhost

- go to [personalize/example-form2](http://localhost:4000/components/personalize/example-form2.html)
- change color to Alabaster
- notice the progress bar

image

**Comment by jbrcna** [comment]
**breadcrumb is missing.** 
[header/example-breadcrumbs-alternate.html](http://localhost:4000/components/header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default) - only default & alabaster color has the breadcrumb displayed.
image

[header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default](http://localhost:4000/components/header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default) - when using dark mode, breadcrumb is not displayed in all colors

**Comment by jbrcna** [comment]
Hello, below are my findings 


**breadcrumb is missing.** 
[header/example-breadcrumbs-alternate.html](http://localhost:4000/components/header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default) - only default & alabaster color has the breadcrumb displayed.
image

[header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default](http://localhost:4000/components/header/example-breadcrumbs-alternate.html?theme=new&mode=dark&colors=default) - when using dark mode, breadcrumb is not displayed in all colors

---
**searchfield "x" icon is color iss off**
[header/example-breadcrumbs.html?colors=0066D4&theme=new&mode=contrast](http://localhost:4000/components/header/example-breadcrumbs.html?colors=0066D4&theme=new&mode=contrast) - x icon is hard to read when hovered. using alabaster color is ok. see also x icon in other EPs.
image

---
**button text color is off when hovered**
[header/example-emphasize-id.html?colors=0066D4&theme=new&mode=contrast](http://localhost:4000/components/header/example-emphasize-id.html?colors=0066D4&theme=new&mode=contrast) - button color is off when hovered when using all colors but default & alabaster. see also buttons in other EPs.
image

---
**text not displayed when the field is not focused**
all colors but default & alabaster are affected
steps
1. go to [header/example-flex-toolbar.html?colors=0066D4&theme=new&mode=contrast](http://localhost:4000/components/header/example-flex-toolbar.html?colors=0066D4&theme=new&mode=contrast)
2. type text in searchfield
3. click outside the field
4. see issue.
5. hover the field.
6. see issue
Large GIF (920x480)

---
**text is cleared  when searchfielsd is not focused**
using high contrast text is not displayed when field is not focused
steps
1. Go to [header/example-header-with-multiple-buttons-and-searchfield.html?theme=new&mode=contrast&colors=0066D4](http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=new&mode=contrast&colors=0066D4)
2. type text in searchfield
3. click outside
4. see issue
Large GIF (906x480)

---
**x icon is off with alabaster**
steps
1. go to [header/example-non-collapsible-searchfield.html?colors=ffffff&theme=new&mode=light](http://localhost:4000/components/header/example-non-collapsible-searchfield.html?colors=ffffff&theme=new&mode=light)
2. type a text in field
3. see issue
image

---
**caret icon color is off when hovered**
using all colors but default & alabaster
steps
1. go to [header/example-popupmenu.html?colors=7928E1&theme=new&mode=contrast]
(http://localhost:4000/components/header/example-popupmenu.html?colors=7928E1&theme=new&mode=contrast)
2. Hover or clicked the button
3. See issue
image

**Comment by CindyMercadoReyes** [comment]
More issues found below: 
Header (Light Mode)
 
Breadcrumbs are hard to read
 
Steps to reproduce:
•	go to [header/example-breadcrumbs](http://localhost:4000/components/header/example-breadcrumbs.html)
•	hover over breadcrumbs
 
 
Icon Issue in Alabaster (All related examples)
 
Steps to reproduce:
•	go to [header/example-disabled-buttons](http://localhost:4000/components/header/example-disabled-buttons.html)
•	change color to Alabaster
•	click hamburger icon
•	click any on the list
•	click on the white part of the page
•	notice the highlighted icon
 
Steps to reproduce:
•	go to [header/example-drilldown](http://localhost:4000/components/header/example-drilldown.html)
•	change color to Alabaster
•	click hamburger icon
•	click any on the list
•	click on the white part of the page
•	notice the highlighted icon
 
Buttons are unreadable when hovered
 
Steps to reproduce:
•	go to [header/example-flex-toolbar](http://localhost:4000/components/header/example-flex-toolbar.html)
•	hover over buttons, ellipses
 
Steps to reproduce:
•	go to [header/example-header-with-multiple-buttons-and-searchfield](http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html)
•	hover over buttons, ellipses
 
'View Profile' button is unreadable in Alabaster
 
Steps to reproduce:
•	go to [header/example-record-id](http://localhost:4000/components/header/example-record-id.html)
•	change color to Alabaster
•	hover over the 'View Profile' button
 
'Advanced Search' link is unreadable
 
Steps to reproduce:
•	go to [header/example-searchfield-large](http://localhost:4000/components/header/example-searchfield-large.html)
•	Notice the 'Advanced Search' link
 
 
Wizard is unreadable
 
Steps to reproduce:
•	go to [header/example-wizard](http://localhost:4000/components/header/example-wizard.html)
 
 
Personalize (Light Mode)
 
Steps to reproduce:
•	go to [personalize/example-form2](http://localhost:4000/components/personalize/example-form2.html)
•	change color to Alabaster
•	notice the progress bar

**Comment by tmcconechy** [comment]
@CindyMercadoReyes @jbrcna @glenlieorillo 

I went through all the issues noted on this branch and either:

1. Could not reproduce
2. I fixed it
3. Or pushed them on to this issue https://github.com/infor-design/enterprise/issues/7390

Please have one more check. On this branch and let me know (probably going to make issues for the rest of the remaining bugs).

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy , Just adding this additional issue to the ticket. Please see below:



'x' button is not aligned properly in 
https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html?theme=new&mode=dark&colors=default 

https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-full.html?theme=new&mode=dark&colors=default

Hyperlinks are not visible in https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-large.html?theme=new&mode=dark&colors=default

X3
X2
X1

**Review by CindyMercadoReyes — DISMISSED** [review]
Approving this ticket. Kind regards, Cindy

**Pull request merged**
