### PR TITLE
6738 - Datagrid header icon with tooltip

### LINKED ISSUE #6738: Unit Testing: Create a Puppeteer Script for "Datagrid: Add ability to have an icon on the datagrid header with a tooltip".
Describe the Issue
Create a unit testing for "Datagrid: Add ability to have an icon on the datagrid header with a tooltip".

See attached BDD for more information.
[BDDStory_github6490.docx](https://github.com/infor-design/enterprise/files/9348373/BDDStory_github6490.docx)

Related github issue
#6490

### PR DESCRIPTION
**Pull request by jbrcna**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes #6738 
related to #6490 
**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer datagrid
4. It should pass.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by jbrcna** [comment]
Comments and suggestions are greatly appreciated as I am stumped on this one. I'm unable to verify the tooltip by hovering over the icon (svg).

**Comment by jbrcna** [comment]
Here are the things I’ve tried so far
- wait for element before trying to hover
- Click the element before hover
- Focus the element before hover
- Mix and match page.hover and element.hover
- Hover using coordinates of element
- Hover using coordinates of element with random math (adding/subtracting x and y coords)
- Setting the viewport to larger/smaller size
- Adding zoom before hover
- Adding waits (static and selector wait)

**Comment by tmcconechy** [comment]
@jbrcna this might not be too easy. In the code it looks like the event is on the `mousenter` of the th element so you would need to trigger on that. Give it a try. Might also need to set the event target which im not sure if can be done.

**Comment by jbrcna** [comment]
thank you for this insight @tmcconechy . I will try to do it tom. I'm thinking of using page.evaluate to trigger `mouseenter` or forcing the element state using/in console.

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Pull request merged**
