### PR TITLE
5119 - locale exclamation mark non english (locale)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the position of exclamation point of validation in non english localization.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5119

Set of Pages for Testing
Input Validation
- http://localhost:4000/components/validation/example-index.html?locale=en-US
- http://localhost:4000/components/validation/example-index.html?locale=ru-RU
- http://localhost:4000/components/validation/example-index.html?locale=ar-SA

Tab Vertical Validation
- http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=en-US
- http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ru-RU
- http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ar-SA

**Steps necessary to review your pull request (required)**:
General Rule
- For LTR the icon should be on the left
- For RTL the icon should be on the right

Step 1
- Pull this branch, build, and run the app
- Go to the input validation pages
- Clear one of the inputs
- See the error
- Do this with other validation pages

Step 2
- Go to tab vertical validation pages
- Clear the `Email Address` textbox
- See the error
- Do this with other validation pages

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@tjamesallen15 im not sure of the rules here so made a comment to the translator https://github.com/infor-design/enterprise/issues/5119#issuecomment-1739457942 for clarification on which go on which side.

Also see an issue in Arabic http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ar-SA the icon is very far away

**Comment by tmcconechy** [comment]
@tjamesallen15 so according to the translation team there was some confusion here. I agree with this comment https://github.com/infor-design/enterprise/issues/5119#issuecomment-1743114583

a) In all languages the error should be on the left (both input errors and tab errors). All error icons should be on the left. the input errors should always be on the left. Unless it is a Right To Left language (he-HI or ar-SA) then in both cases the error is on the right.
b) cant change the icon so just leave that

**Review by tmcconechy — CHANGES_REQUESTED** [review]
As above

**Review by tmcconechy — APPROVED** [review]
Looks great now but can we make the icons the same size? I dont see why they need to be different (but not your fault it was like that before)

Also for future reference instead of padding-left and padding-right use can use padding-inline-start and padding-inline-end and you dont need special rules for RTL if you do. (update if you want)

https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start

**Review by yohannahbautista — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
Looks good. I did see one issue QA might mention in that http://localhost:4000/components/validation/test-error-on-tab-vertical.html?theme=new&mode=light&colors=default&locale=en-US has two scrollbars.

But good for me

**Comment by tjamesallen15** [comment]
> Looks good. I did see one issue QA might mention in that http://localhost:4000/components/validation/test-error-on-tab-vertical.html?theme=new&mode=light&colors=default&locale=en-US has two scrollbars.
> 
> But good for me

Thanks with suggestion above about padding-inline, I learned new and might be able to use it in the future tickets!

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Comment by ericangeles** [comment]
FYI @infor-design/qa

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
http://localhost:4000/components/validation/example-index.html?locale=en-US -- **PASSED**


https://github.com/infor-design/enterprise/assets/102151352/cec8dcae-f843-4653-b296-c316ef0a27dd

http://localhost:4000/components/validation/example-index.html?locale=ru-RU -- **PASSED**

https://github.com/infor-design/enterprise/assets/102151352/78447c9c-f59c-4fe4-b027-5d80e81d55f1

http://localhost:4000/components/validation/example-index.html?locale=ar-SA -- **PASSED**

https://github.com/infor-design/enterprise/assets/102151352/9327d342-31ce-4fc7-9dcc-afaa34730639

http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=en-US -- **FAILED**

- Page content disappears upon changing color.

**Steps to reproduce:**

1. Click More button
2. Click Colors
3. Select any color other than Default

image

https://github.com/infor-design/enterprise/assets/102151352/bcbed9ef-e7e1-422f-a686-0cf8b424033c

http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ru-RU -- **FAILED**

- Page content disappears upon changing color.

**Steps to reproduce:**

1. Click More button
2. Click Colors
3. Select any color other than Default

image


https://github.com/infor-design/enterprise/assets/102151352/83a65776-0cfa-4554-b228-9924959aa5ae

http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ar-SA -- **FAILED**

- Page content disappears upon changing color.

**Steps to reproduce:**

1. Click More button
2. Click Colors
3. Select any color other than Default

image

- Text and Error Icon are overlapping.

**Steps to reproduce:**

1. Clear the Email Address text box
2. Notice the Text and Error Icon on the Nav Pane

image

https://github.com/infor-design/enterprise/assets/102151352/3dd8ee23-3249-4c49-ad53-8a42b73ee417

**Review by jbrcna — CHANGES_REQUESTED** [review]
http://localhost:4000/components/validation/test-error-on-tab-vertical.html?locale=ar-SA
overlapping icon
image

not related but notice that alabaster wasn't translated
http://localhost:4000/components/validation/example-index.html?colors=BB5500&theme=classic&mode=light&locale=ru-RU
image

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
Everything seems fixed. merging as this sat a long time

**Pull request merged**
