### PR TITLE
8457 - Datagrid Editable Left Right Keys

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will Fix unable to use the left/right arrow keys on the text in an editable cell.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8457

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Click one editable cell
- Try using left and right arrow keys, should traverse to the letters

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 i cant use arrow keys to navigate the cells anymore

1. go to http://localhost:4000/components/datagrid/example-editable.html
2. click row id cell
3. try to use any arrow key (should be able to move around the cells)

I think the fix would involve the edit mode code/handlers. Not switch the quickEdit/actionable mode

**Review by jbrcna — APPROVED** [review]
Large GIF (532x386)

**Review by janahintal — APPROVED** [review]
image

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 looks good on example.html but i think there is some problems on http://localhost:4000/components/datagrid/test-editable-actionable-mode.html

1. Problem one: it seems to be inserting a `.` when i didnt add one. I cant really reproduce it all the time its some combination of typing characters then arrow left and arrow right and space key. cc @n-ace-ancog 
2. This actionable mode is not working now. Go into activity key and type then hit tab and it goes to the pager not the next editable cell

**Comment by tmcconechy** [comment]
Now the arrow keys do not work in the cells

a) go to http://localhost:4000/components/datagrid/example-editable.html or http://localhost:4000/components/datagrid/test-editable-actionable-mode.html
b) click in a cell to edit
c) try to use arrow keys

Basically. requirements should be as follows:

1) keyboard behavior is not effected from navigating cells. This means arrow keys on http://localhost:4000/components/datagrid/example-editable.html  to move cells and both arrow keys and tabs to move to next editable cell on http://localhost:4000/components/datagrid/test-editable-actionable-mode.html
2) No matter the setting when you go in a cell. The arrow keys only navigate in the cell. Until you exist edit mode

**Comment by tmcconechy** [comment]
@tjamesallen15 @yohannahbautista 

I see a weird bug:

- try to focus the activity column
- then press (or any key) followed by space 3-4 times fast and it inserts a decimal
Screenshot 2024-04-15 at 10 31 06 AM

**Comment by yohannahbautista** [comment]
> @tjamesallen15 @yohannahbautista
> 
> Looking good, but I see a weird bug:
> 
> * try to focus the activity column
> * then press (or any key) followed by space 3-4 times fast and it inserts a decimal
> 
> Screenshot 2024-04-15 at 10 31 06 AM

@tmcconechy 

Hello, the "." may be a default in Keyboard settings. Unchecking the "Add period..." may work
image

**Comment by tmcconechy** [comment]
Nice @yohannahbautista i didnt know about that. Thought it was wierd. Approving.

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/62e8bc94-bb46-4e96-8f97-19866833e087


https://github.com/infor-design/enterprise/assets/102151352/db261628-b373-4a34-a739-d8799eb8eb53

**Review by jbrcna — APPROVED** [review]
reapproving
image

**Review by janahintal — APPROVED** [review]
image

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
@yohannahbautista thanks for covering up for James!

**Pull request merged**
