### PR TITLE
7019 - Modal Draggable

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add setting `draggable` to be able to drag modals.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7019

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/modal/test-draggable.html
- Try to drag the modal

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
- Mac Chrome

https://github.com/infor-design/enterprise/assets/102151352/419ecfe5-88a9-43ad-8bca-43d20cfdc1a5

- Mac Firefox

https://github.com/infor-design/enterprise/assets/102151352/472c81f0-a286-4366-8082-a34a0108eae8

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 when the modal is open you cant click into any of the fields and type
Otherwise looks good. We can also let it drag partly off the screen not all the way off though

**Comment by tjamesallen15** [comment]
I just changed the area of draggable in to header only now. Then allowed the modal to be drag outside of the document @tmcconechy

**Review by glenlieorillo — DISMISSED** [review]
Retested and approved.


https://github.com/infor-design/enterprise/assets/102151352/00b517b3-b690-423c-8c44-ef8fc2de6ae0

However, I just noticed the character count. `{0}` should not be included in the displayed text. Created a new issue for this bug: [8532](https://github.com/infor-design/enterprise/issues/8532)

image

**Comment by ericangeles** [comment]
@glenlieorillo, we have reported a ticket issue regarding the character count message in here https://github.com/infor-design/enterprise/issues/8449.

**Review by jbrcna — DISMISSED** [review]
Large GIF (696x704)

**Review by tmcconechy — COMMENTED** [review]
@tjamesallen15 looks good. Do you think you can make it so you cant drag it all the way off? Maybe lets say 20px margin?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 looks good. Do you think you can make it so you cant drag it all the way off? Maybe lets say 20px margin?

I don't get it how much 20px we need (20px offset or 20px of modal showing) but I made the modal example draggable outside of document about halfway through.

**Comment by tmcconechy** [comment]
@tjamesallen15 Now the drag is not as smooth. I think lets change it back to the way you had it as first where you can not drag the whole modal off the page? It worked better and was fine. I should have just left it like that...

**Comment by tjamesallen15** [comment]
> @tjamesallen15 Now the drag is not as smooth. I think lets change it back to the way you had it as first where you can not drag the whole modal off the page? It worked better and was fine. I should have just left it like that...

Good news. I fixed the rough drag, was error on my end in validation of the position! 😁

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
image
image

**Pull request merged**
