### PR TITLE
8530 - Calendar Day View Event Render

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix render of events on day view for non all-day events, also fixed modal button and input positions.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8530
Closes https://github.com/infor-design/enterprise/issues/8490
Closes https://github.com/infor-design/enterprise/issues/8657

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-start-end-hour.html
- Click on `April 23`
- Change to `Week View`
- Change to `Day View`

For #8490 
- Go to http://localhost:4000/components/calendar/test-start-end-hour.html or just refresh the page
- Click on `April 5`
- Change to `Day View`
- Check April 5 should have 11pm covered
- Check April 6 should have until 5am covered

For #8657 
- Open the Add Event (Modal) or just click an existing events to show modal
- Check if input positions are properly aligned
- Check if the button positions are properly aligned.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Issue found with the following:
1. Create a new 3 day event with time 8AM to 7 AM
2. Go to **day** view
3. Go the 2nd day, the entire day should be booked, but in this instance only half day

**Month view** - OK
image

**Week view** - OK
image

image

**Day view** - **NOT OK**
1st day
image

**2nd day was cut off**
image

3rd day is okay
image

This also exist on the existing event April 22 - 24 12 AM - 11:59 PM, the second day cuts before 12 AM maybe that's why its not noticeable

image

**Comment by n-ace-ancog** [comment]
Found a minor baseline issue regarding the dates overlapping with the calendar icon #8657. FYI for other reviewers.

**Review by jbrcna — CHANGES_REQUESTED** [review]
text and buttons are off
image

last day of the event time is not correct
image


should b e 5am
image
image

**Comment by tjamesallen15** [comment]
I also covered #8657. @n-ace-ancog 

For @n-ace-ancog comments, check the new event `Cancun on Three`. I premade the event you created for testing

For @glenlieorillo comments, it is covered until 5am.

cc @ericangeles @tmcconechy I fixed the regressed bugs for the calendar.

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
**Issues found**
1. For the regression bug, seems to be fixed on double digit day, but when combined with double digit month and day bug still appears.

image

2. When creating a new overlapping event, non-overlapping part is not aligned to the overlapping part. One navigated to another view, it fixes it.
image
image

3. Create a new event on May 14 - 8 AM to 10 PM and change to week and day view - the events are not side by side.

**Event created**
image

**Week view**
image

**Day view**
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Re-testing issues:
1. Regarding dates overlapping to calendar icon - **not ok**
image
2. Creating new event that overlaps other event - **seems ok now**
Animation
3. Creating a new event on May 14 - 15 8 AM to 10 PM and change to week and day view - **seems ok now**
image
**week view**
image

**day view**
image
image

4. Like issue 3, but the days are May 13 to 15 8 AM to 10 PM - **not ok**
**week view**
image
**day view - on the 1st overlapping day**
image

**Comment by tjamesallen15** [comment]
The overnight bug is now fixed. However, I can't seem to find the input box overlap. Screenshot below
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
**Preivous issues:** https://github.com/infor-design/enterprise/pull/8650#pullrequestreview-2031242189

1. **OK**
image

2.  **Still OK**
image

3. **Still OK**
image
image
image

4. **OK**
image
image
image

@tjamesallen15 - Adding more than 2 events produces the same issue

**New Issues**
1. The purple event spans from 6 AM to 10 PM, but looks liked its stacked - happens when there's more than 2 events 
image

2. The very bottom of the events are not aligned - all events span the next day
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Same result on my end, the bottom of the `All day` events are not aligned.
image

image

Just a comment for @n-ace-ancog issue, the event doesn't stack. The first created event will display on top of the other created event. For me, this is not an issue.

image

**Comment by jbrcna** [comment]
buttons and icons were now fixed
image

However, the event is until 12:00pm but it continued over 12:00pm. Did I understand it correct?
image

**Comment by n-ace-ancog** [comment]
With regards to the new issues found another separate Github issues will be created:
1. Stacking of calendar events for 3 or more instances (will be created if an enhancement request is needed or created by users)
2. Misalignment of end of day elements with a day having multiple events

@tjamesallen15  @ericangeles - let me know if I missed anything

**Review by n-ace-ancog — DISMISSED** [review]
Approving in reference to the following review/comment:
- https://github.com/infor-design/enterprise/pull/8650#pullrequestreview-2035093135
- https://github.com/infor-design/enterprise/pull/8650#issuecomment-2090513392

**Comment by tmcconechy** [comment]
@n-ace-ancog the only other issue i would add is if you go to mobile or tablet view and open the popup it doesnt look quite right

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
