### PR TITLE
3594 - Fix Editor Issues

### LINKED ISSUE #2256: Editor: H3 and H4 overwrites other styling in Edge but not in Chrome
**Describe the bug**
Minor, but currently the Editor works a little differently in Edge (+ IE11) compared to Chrome. In Edge when you have styled some text and then choose to style it with H3 or H4 all other styling are lost, but in Chrome when you have styled some text and then choose H3 or H4 the other styles are still applied.

**To Reproduce**
In Edge and Chrome:
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Add A new line and and some test text
3. Select the text
4. Make it Bold, Italic, Underlines, Strike through and color it
5. Click H3 (or H4)
6. See the result

**Expected behavior**
I'm not fully sure what is the expected behaviour (If edge or Chrome does it right). In word it seems all "before styling" is lost when applying a Heading style so perhaps that is the expected behavior? But Edge (and IE11) and chrome should handle it equally.

**Version**
- ids-enterprise: v 4.18.1

**Screenshots**
-

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome & Edge
 - Browser Version: Version 74.0.3729.157 (Official Build) (64-bit) &
Microsoft Edge 44.17763.1.0, Microsoft EdgeHTML 18.17763

**Additional context**
-

### LINKED ISSUE #2679: Editor: Bullet / numbered list item can't be turned into H3/H4
**Describe the bug**
This is a minor issue. A bullet / numbered list item can't be turned into H3/H4. The style does look like it gets applied, since the buttons get active, but it remains a list item. Only seems to be an issue in Chrome & Safari.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Type something
3. Turn text into bullet / number list
4. Turn into H3/H4
**Result**: Not turned into H3/H4

**Expected behavior**
Turned into H3/H4

**Version**
- ids-enterprise: 4.20.0

**Platform**
 - Browser: Chrome / Safari

### LINKED ISSUE #3288: Editor: Increase paragraph top padding and adjust header styles
## Describe the bug
Paragraph spacing seems to disappear when multiple styles are introduced
1. Go to http://localhost:4000/components/editor/example-index.html
2. Add a couple headings on the page
3. Add a paragraph below the heading
4. The paragraph spacing seems to disappear

## Expected behavior
All text should have some spacing between block level elements.

## Screenshots

Only using paragraph styles
Screen Shot 2019-12-23 at 11 22 34 AM

Adding heading styles
Screen Shot 2019-12-23 at 11 23 06 AM

Paragraph spacing disappears below heading
Screen Shot 2019-12-23 at 11 25 01 AM

## Platform
 - Macbook Pro
 - macOS 10.14.6 (Mojave)
 - Chrome v79.0.3945.88

## Additional context
I also think that "Heading 1" and "Heading 2" are too close in size. We should either make Heading 1 larger or Heading 2 smaller.

### LINKED ISSUE #3577: Editor: Rich text editor UI updates
The rich text editor (RTE) field should be revised as part of the UI uplift initiative.
The update should address the following issues:

- Improved transitions between HTML and WYSIWYG (visual) editors. The current transition has been disorienting for some users. (https://github.com/infor-design/design-system/issues/440)
- Simplified UI. The current version has outlines around everything and boxes inside boxes.
- Clean up toolbar icons. Some icons have been scaled or squeezed.
- Make separations more distinct in the toolbar.

### LINKED ISSUE #3594: Editor: Toggling source view on a modal gives wrong width.
**Describe the bug**

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/test-modal.html
2. Click on the button
3. In the .. of the editor select source view
4. See error (width changes)

**Expected behavior**
Width stays the same as before

**Version**
- ids-enterprise: [v4.26]

**Platform**
 - Chrome

### LINKED ISSUE #3598: Editor: Toggling source view to HTML and making edits does not display dirty indicator
**Describe the bug**
Toggling the rich text editor to HTML mode and making changes does not display the dirty indicator. Works correctly when in Visual mode.

**To Reproduce**
Steps to reproduce the behavior to test HTML mode:
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html'
2. Click on 'HTML'
3. Make changes
4. Dirty indicator does not display

Steps to reproduce the behavior to test Visual mode:
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html'
2. Make changes
3. Dirty indicator displays correctly

**Expected behavior**
If the component is defined with validation, then both modes should display the dirty indicator.

**Version**

- ids-enterprise: v4.26

**Screenshots**

**Platform**
 - All

**Additional context**

### LINKED ISSUE #3638: TextArea: Text not visible in safari
**Describe the bug**

**To Reproduce**
1. Use Safari Mac (latest)
1. Go to https://master-enterprise.demo.design.infor.com/components/textarea/example-index.html
1. See that the text is invisible in the disabled input

**Expected behavior**
Text should be visible

**Version**
- ids-enterprise: [e.g. v4.26.1]

**Platform**
  - OS Version: [iOS or mac]
 - Browser Name [safari]

**Additional context**
Ms Teams

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a number of related editor issues, to enhance behavior and looks in uplift.

**Related github/jira issue (required)**:
Fixes #3577 
Fixes #3594 
Fixes #2679 
Fixes #2256
Fixes #3598 
Fixes #3288 
Fixes #3638
 
**Steps necessary to review your pull request (required)**:
**Issue 3577**
- go to http://localhost:4000/components/editor/example-index.html
- test it in all 2 themes and 3 variants 
- in particular notice the toolbar look is adjusted in Uplift

**Issue 3594**
- go to http://localhost:4000/components/editor/example-index.html
- click to toggle between the source and visual view
- notice that the buttons are now disabled not removed
- go to http://localhost:4000/components/editor/test-modal.html
- open the modal 
- click to toggle between the source and visual view
- notice that the dialog width now does not change

**Issue 2679**
- go to http://localhost:4000/components/editor/example-index.html
- create bullet list with two items (or a number list)
- select all of the bullet list
- make it a heading one -> should be a heading one and no longer a list

**Issue 2256**
- go to http://localhost:4000/components/editor/example-index.html
- type a new row with text "Test Text"
- select that text
- click bold, itallic, underline, strikethrough
- make it a heading one -> should be a heading one and no longer a list
- this is the same behavior as IE 11 and Edge now

**Issue 3598**
- go to http://localhost:4000/components/editor/example-dirty-tracking.html
- change text in the preview view -> should show a dirty indicator
- reload
- change to source view
- change text in the preview view -> should now show a dirty indicator

**Issue 3288**
- go to http://localhost:4000/components/editor/example-dirty-tracking.html
- clear all text
- make a Heading one with text
- hit enter at the end of the line
- type some text
- hit enter again
- the header to next text should be the same margin as between the two paragraphs 

**Regression**
- test all of http://localhost:4000/components/editor/
- try several browsers

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Issue 3577 (not sure about this might right, but check anyway)
http://localhost:4000/components/editor/example-index.html?theme=uplift&variant=dark
- for uplift dark theme
- open header picker dropdown
- see the selected color, looks less readable -is this right text color?

Issue 3594
http://localhost:4000/components/editor/test-modal.html
- resize browser window to mobile size
- open modal and editor looks not responsive

**Comment by ericangeles** [comment]
The only issue that I see is the editor inside of modal. 

Go to
- http://localhost:4000/components/editor/test-modal.html
- Resize the browser to a smaller view.
- Editor is cut off. Should be responsive.

The rest looks good to me.

**Comment by tmcconechy** [comment]
Needs https://github.com/infor-design/enterprise/pull/3632 to fix the tests but this is ready to test.

**Comment by deep7102** [comment]
Responsive issue fixed, but saw one thing
http://localhost:4000/components/editor/test-modal.html
- resize browser window to mobile size
- open modal and click on `...` action button in editor toolbar
- choose `View Source` to switch html mode
- click back to `...` action button
- see all the buttons are disabled, there is no way to switch back to preview mode

**Comment by tmcconechy** [comment]
@deep7102 pushed an update for that

**Comment by fitzorama** [comment]
@tmcconechy Am seeing this issue, can duplicate with the example-dirty-tracking.html sample
- Click HTML to switch the mode
- Click Visual to switch the mode
- Enter a value (non-space)
- Dirty indicator does not display

**Comment by fitzorama** [comment]
Another, can also duplicate with the example-dirty-tracking.html sample
- In Visual mode, after the last line hit Enter to create new line
- Enter a couple of characters
- Dirty indicator should appear
- Click HTML to change mode
- Click Visual to change mode
- Dirty indicator still displays
- Set cursor to end of new characters and delete them  (backspace) including the new line
- Should be pristine at this point, but dirty indicator still displays
- Click back to HTML mode to verify pristine state

**Comment by tmcconechy** [comment]
@deep7102 @fitzorama - i fixed your noted issues. Ready to test again.

**Comment by fitzorama** [comment]
@tmcconechy First issue is resolved; second issue is not, dirty indicator not going away

**Comment by tmcconechy** [comment]
OK, lets try again

**Comment by fitzorama** [comment]
@tmcconechy Looks good, both issues resolved, including the spaces issue we chatted about off-line.

**Comment by tmcconechy** [comment]
Ok, thanks merging so this can get in the nightly!

**Pull request merged**
