### PR TITLE
8016 - Reorder tags

### LINKED ISSUE #8016: Tabs: Reorder/Drag tabs coming from More button
**Is your feature request related to a problem? Please describe.**
In line with this ticket https://github.com/infor-design/enterprise/pull/7728

Possibility to be able to do the same reordering and dragging when tabs are coming from the more button:
image

**Additional context**
In addition need an event that fires when the sort changes and for each of the drag events

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Enhancement and bugfix in reordering tags

**Related github/jira issue (required)**:

Close #8016 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the branch
- Go to: http://localhost:4000/components/tabs-module/example-sortable.html
- Add tabs until overflow happens
- Select a tab from more menu
- Tab should appear in the next visible space

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista i think this looks good but..

a) can we fix the x position
Screenshot 2024-06-28 at 10 34 09 AM
b) when adding new tabs can we make it scroll over so the new tab is in view?

Screenshot 2024-06-28 at 10 35 02 AM

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/ce3cee0d-19d6-4910-b20a-77ea1590a16b


Menu icon is not visible in New - Light Mode. Created an issue for this bug: https://github.com/infor-design/enterprise/issues/8863

image

**Review by jbrcna — DISMISSED** [review]
image

**Comment by tmcconechy** [comment]
@yohannahbautista seems my points are not addressed https://github.com/infor-design/enterprise/pull/8856#pullrequestreview-2148207105

Also the hamburger icon color makes it invisible.

**Review by glenlieorillo — DISMISSED** [review]
image

**Review by jbrcna — DISMISSED** [review]
image

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
@yohannahbautista can you start a new 4.98.0 section in the change log

**Pull request merged**
