### PR TITLE
7797 - Fix bar charts label were not visible

### LINKED ISSUE #7797: Bar Chart x-axis is disappearing in IDS 4.85.0
**Describe the bug**
Bar chart x-axis values are disappearing after we enable the preview mode in Infor OS Portal.

**To Reproduce**

1. Add a widget with chart https://design.infor.com/code/ids-enterprise/latest/bar
2. Open the Infor OS portal in preview mode. adding **?ospClientPreview=true**to the url
3. You'll see the x-axis values of chart will disappear.

**Expected behavior**
x-axis values should not disappear.

**Version**

- IDS version changes from 4.80.2 to 4.85.0 when we enable preview mode. We have issue in IDS 4.85.0.
- On preview mode, Infor OS version is 2023.09.00 (PREVIEW, 20230727-131728, 3063, 8388)

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Infor OS Workspace, Infor AIS

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the issue where the x-axis labels on the bar chart were not visible.

It also fixes alignment issues on bar-stacked with legends.

**Related github/jira issue (required)**:

Closes #7797 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to
  - http://localhost:4000/components/bar/example-index
  - x-axis labels should be visible
  - Position of legend should be aligned as well
  - http://localhost:4000/components/bar-stacked/example-index
  - In bar-stacked, x-asis labels should be visible
  - legends position should be fine as well
  - http://localhost:4000/components/bar-stacked/example-stacked-100.html 
  - There should be no vertical scrollbar, and it should be aligned properly.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good but http://localhost:4000/components/bar-stacked/example-stacked-100.html
Has a lot of extra space between the bottom and legend. Perhaps can be rebalanced like the other.  http://localhost:4000/components/bar/example-index vs http://localhost:4000/components/bar-stacked/example-index

**Comment by ericangeles** [comment]
@tmcconechy, both http://localhost:4000/components/bar-stacked/example-stacked-100.html and http://localhost:4000/components/bar-stacked/example-index have the same height (when you look into the svg height). 

When dealing with only the bar chart at http://localhost:4000/components/bar/example-index, if we adjust it the same way as the bar-stacked chart, it will cut off the bottom labels.

Do you have any recommendations?

**Comment by tmcconechy** [comment]
@ericangeles your right, looking again they are the same size. Is it possible to make the upper chart part extend a little bit down so that its equal space on top and bottom of the legend..

Screenshot 2023-08-23 at 9 29 04 AM

Just seems to be a lot of wasted space. Ideally 16px on top and bottom of the legend?

**Comment by ericangeles** [comment]
@tmcconechy I also considering the axis labels if we adjusted it?

**Comment by tmcconechy** [comment]
@ericangeles it might make more sense to make chart use more space so it can show more. But i guess whatever makes it look more balanced. It isnt bad as is but i think that can be improved for spacing

**Review by clayinfor — APPROVED** [review]

**Review by tjamesallen15 — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
**BAR**

http://localhost:4000/components/bar/example-index

image

https://7797-bar-x-axis-label-enterprise.demo.design.infor.com/components/bar/example-index

image


**BAR-STACKED**

http://localhost:4000/components/bar-stacked/example-index

image

https://7797-bar-x-axis-label-enterprise.demo.design.infor.com/components/bar-stacked/example-index

image

http://localhost:4000/components/bar-stacked/example-stacked-100.html

image

https://7797-bar-x-axis-label-enterprise.demo.design.infor.com/components/bar-stacked/example-stacked-100.html

image

**Pull request merged**
