### PR TITLE
7947 - Adjusted icon colors in classic

### LINKED ISSUE #7947: Header: Icons are not in the proper place
**Describe the bug**
Icons are not in the proper place.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html
2. Notice the magnifying and down arrow icon above 'Product:1' 

**Expected behavior**
Icons should be placed properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - All major browsers

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted icon colors in classic. Moved style from header-new to header so that color will apply to both new and classic.

**Related github/jira issue (required)**:

Closes #7947 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/header/example-toolbar-flex-with-categories.html
- In both new and classic, check that icons in searchfield are aligned and the colors are correct

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This is a bit minor but you can see the shape of the search input is a pixel smaller between focus and non focus mode. So the box doesnt line up on the top and bottom

Screenshot 2023-10-10 at 10 44 45 AM
Screenshot 2023-10-10 at 10 44 40 AM

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
cc @infor-design/qa

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/e4ea6cb7-59bd-45d9-a32d-3cd45f04ce9b

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Expand icon next to 'x' button is not visible on both classic and new version for responsive view. 
https://7947-header-icons-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html 
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
new
image

classic
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Bug still exists in Classic-Alabaster.

Screenshot 2023-10-16 at 4 33 59 PM

image

image

**Review by glenlieorillo — DISMISSED** [review]
image

image

image

**Review by janahintal — CHANGES_REQUESTED** [review]
Hello Team, 

Issue/s: 
Search field looks off in responsive view for alabaster https://7947-header-icons-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html?colors=ffffff&theme=classic&mode=contrast 
Mode: All 
Version: New & Classic 
Color: Alabaster

Video: https://www.loom.com/share/6414edb33fcd46b28e534ea45fc9656f?sid=77008049-5cb3-4432-9ffc-4fd8642022ad
image
image
image

Thanks!

**Comment by jbrcna** [comment]
mobile view - https://7947-header-icons-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=contrast&colors=ffffff
image
**Dark**
image
**Light**
image

Steps
1. open in mobile view
2. input a text in searchfield
3. tab to focus on collapse button
4. see issue
5. hover on buttons
6. click anywhere on the page
7. hover on buttons
8. see issue

https://github.com/infor-design/enterprise/assets/56722184/b0d938a5-d5a7-4810-893f-0eb87983c6f8

**Comment by tmcconechy** [comment]
@yohannahbautista i see a double border here now:

Screenshot 2023-10-19 at 11 20 44 AM

It looks ok tho, but i think it had a single one before

**Review by tmcconechy — APPROVED** [review]
Looks good now for me 👍🏻  Can you retest @infor-design/qa ?

**Comment by ericangeles** [comment]
Please re-test @infor-design/qa

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://7947-header-icons-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=contrast&colors=ffffff

Searchfield dropdown menu is cut-off in mobile. (BrowserStack)

**iOS**
image

**Android**
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
still Failing in mobile view
image

**Comment by ericangeles** [comment]
Can you guys test it again? @infor-design/qa

**Comment by jbrcna** [comment]
alabaster is now fixed
light
image

dark
image

high contrast
image

**Comment by jbrcna** [comment]
double border retest
image

**Comment by jbrcna** [comment]
mobile vet retest
image

**Review by max-hizon — COMMENTED** [review]
Fixed double borders
image

Header icons no longer crops at 400
image

Below 400 it would still crop. Design choice needed on either hiding the button icon or shortening the dropdown box length when width dimension is smaller than 400

image

**Review by max-hizon — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
