### PR TITLE
5608 - Badges - Mobile Enhancements and style changes

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Mobile enhancements and style changes.

**Related github/jira issue (required)**:
 #5608 

**Steps necessary to review your pull request (required)**:

View http://localhost:4000/components/badges/example-index.html
Make sure changes look good on mobile and adhere to guidelines in original issue: 
  - https://jira.infor.com/browse/IDS-188
  - https://github.com/infor-design/enterprise/issues/5608

**Included in this Pull Request**:
- [ ] ~An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good. Only thing i see is that the blue badge with 15 in it needs maybe one more pixel width on the right as its rather close. Can we add margin or something to achieve

**Comment by davidcarlsonberg** [comment]
Failed tests seem to have nothing to do with the PR? I've run them three times over and get the same result.

**Review by tmcconechy — DISMISSED** [review]
Looks good - but reruning the tests to see whats happening...

**Review by tmcconechy — DISMISSED** [review]
The chrome driver error is fixed on another PR will have to merge it on when thats merged so this is good to me

**Review by ericangeles — APPROVED** [review]

**Review by tjamesallen15 — APPROVED** [review]

**Pull request merged**
