### PR TITLE
7827 - Added overflow in modal body for horizontal scroll

### LINKED ISSUE #7827: Modal: No horizontal scrollbar
**Describe the bug**
Due to [this rule](https://github.com/infor-design/enterprise/blob/a1d586753e6ed1cff5ead98bdb67a387f87d2cf1/src/components/modal/_modal.scss#L759-L763C4), long horizontal content in modals is cut and no scrollbar appears.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1651-3pjhpt
2. Click on "Open Modal"
3. Notice the overflowing content and no scrollbar

**Expected behavior**
A scrollbar should appear

**Version**

- ids-enterprise: `4.85.0`

**Platform**
 - Infor Application/Team Name: Homepages / OS Portal

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added overflow in modal body for horizontal scroll

**Related github/jira issue (required)**:

Closes #7827 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/modal/test-overflow-horizontal.html
- Click on button and open modal
- Horizontal scroll should appear

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
This fix will break the solution in this PR: https://github.com/infor-design/enterprise/pull/7533

- Go to http://localhost:4000/components/modal/test-modal-datagrid-title-overlap.html
- Open the modal
- There should be no horizontal scrollbar

**Review by tmcconechy — DISMISSED** [review]

**Review by tjamesallen15 — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@janahintal i think it seems ok? What specifically is worng in dark mode?

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/d3996449-4fa9-4f83-bc73-c132999b5eae

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
this good @ericangeles @janahintal ?

**Comment by tmcconechy** [comment]
@janahintal thats just the custom style for all scrollbars. Its the same everywhere. Maybe make an issue if you think it should be changed and we can adjust it everywhere?

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Comment by tmcconechy** [comment]
@janahintal lets make a new issue for the scrollbar UI thing.

**Pull request merged**
