### PR TITLE
NG1641 - Field Filter Reset Field

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add Default Field Filter Reset example page.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1641

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-default-filter-type.html
- Change the filter type of `Filterable` to `>`
- Click the `Reset Default`
- It should go back to `=`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:
Animation

**Review by jbrcna — APPROVED** [review]
image

**Comment by jbrcna** [comment]
Large GIF (678x412)

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/074b0863-bb20-431a-87c4-44dcea15947b

However, the Filterable dropdown looks off in RTL. Refer to this issue: [8659](https://github.com/infor-design/enterprise/issues/8659)

image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
