### PR TITLE
Tabs White Theme Issues (2)

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will update example page, recalibrate positionining and fix theme discrepancies.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7085
Closes https://github.com/infor-design/enterprise/issues/7102
Closes https://github.com/infor-design/enterprise/issues/7103
Closes https://github.com/infor-design/enterprise/issues/7107
Closes https://github.com/infor-design/enterprise/issues/7105

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-header/example-index.html
- Go to http://localhost:4000/components/tabs/example-index.html

For #7085 
- Go to http://localhost:4000/components/compositeform/test-with-tab-headers-horizontal.html

For #7102
- Go to http://localhost:4000/components/header/example-tabs-alternate.html

For #7103
- Go to http://localhost:4000/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4

Steps to do:
- Select a tab see the focus, use arrow keys to transfer focus
- Check the focus and hover in the tabs
- Make a screen smaller and check the fade out aligned in the more button.
- Change colors and classic view and check again.

For #7107 
- Go to http://localhost:4000/components/header/example-disabled-buttons.html?colors=0066D4&theme=new&mode=light
- Check the disabled button color
- Change colors and classic view and check again.

For #7085 and #7105 
- Go to http://localhost:4000/components/page-patterns/test-landmark-requisitions-screen.html
- Check the alignment of the tabs, change colors and classic view, check again
- Vertical Tabs: Go to http://localhost:4000/components/compositeform/test-with-tab-headers-vertical.html
- Check the alignment of the tabs, change colors and classic view, check again
- Vertical Tabs: Go to http://localhost:4000/components/tabs-vertical/example-index.html
- Check the alignment of the tabs, change colors and classic view, check again

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — CHANGES_REQUESTED** [review]
All the color adjustments in this one look good -- I tested all the different themes/personalization options.

One thing I want to check:  Is it right that the selected tab is not "rounded" the way any other focused tabs are?  (This might be in the designs but I haven't seen it):

Screen Shot 2023-01-17 at 9 22 02 AM Screen Shot 2023-01-17 at 9 22 15 AM

I also wanted to point out that it looks like the composite form example is good, but I'm still seeing the "cut off" focus state problem on some tab examples.  Wondering if we need to address the "non-alternate" examples... If you smoke test the page patterns folder there are a handful of tabs examples where the cut off problem is still present:  http://localhost:4000/components/page-patterns

For example on http://localhost:4000/components/page-patterns/test-landmark-requisitions-screen.html:
Screen Shot 2023-01-17 at 9 32 18 AM

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Also seeing a few issues http://localhost:4000/components/tabs/example-index.html?theme=classic&mode=dark

Make sure to try any tab examples you test in both versions and all three modes and colors.

Also checked out https://github.com/infor-design/enterprise/issues/7102
- looks like on http://localhost:4000/components/header/example-tabs-alternate.html
- the focus state is misaligned 
- the hover state is mixing two colors -> can probably just make it the same as http://localhost:4000/components/tabs/example-index.html

checking https://github.com/infor-design/enterprise/issues/7103 the
- on http://localhost:4000/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4 the hover state does look strange

**Comment by tmcconechy** [comment]
Ok two things left... i can see

1. This page you cant see the tabs http://localhost:4000/components/tabs/example-index.html?theme=classic&mode=dark&colors=9279a6
2. Minor: On http://localhost:4000/components/header/example-tabs-alternate.html the states can be the same as  http://localhost:4000/components/tabs/example-index.html (we dont really need the alternate anymore as the default is the same, so to keep it simple can use the same)

**Comment by tmcconechy** [comment]
OK one last issue i see 👍🏻 

- now the new hover state is gone http://localhost:4000/components/tabs/example-index.html compare with https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html
- what i meant is the alternate one isnt needed anymore we can just use the "new" styles from the design for both example-index and tabs-header/example-alternate.html would be the same....

**Review by tmcconechy — DISMISSED** [review]
Looks good now 👍🏻 I think i fixed the test issues here https://github.com/infor-design/enterprise/pull/7122

**Review by ericangeles — APPROVED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
