### PR TITLE
8773 - Add fix to refresh tooltip

### LINKED ISSUE #8773: Datagrid: Tooltip for a column's displayed filter operator is incorrect
**Describe the bug**
The displayed tooltip for a column's filter operator is incorrect.  The tooltip is showing 'Contains', when it should be 'Starts With'.

**To Reproduce**

Have been unable to create a test example that demonstrates this issue.  But have provided ,gif file containing console logs as to what Landmark is experiencing.  Seems tied to a column having a defaultFilterOperator that is not the first filterConditions option.

Perhaps tied to the grid-tooltip div created for the data-automation-id.

Will include an updated test-filter-with-default-operator.html that I've been testing with, but can't seem to show the issue.

**Expected behavior**
Expect the displayed tooltip to match the column's filter operator being shown.

**Version**

- ids-enterprise: v4.95.2

**Additional context**
Let me know if you want me to demonstrate the issue Landmark is experiencing.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a fix to refresh possibly cached tooltip in prod mode. (Hard to test) @claudenbach can you test on your end.

**Related github/jira issue (required)**:
Fixes #8773 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-filter-with-default-operator.html
- hover each button the filter row and see that the tooltip matches
- select different items and make sure it changes for the tooltip
- try another language http://localhost:4000/components/datagrid/test-filter-with-default-operator.html?locale=de-DE

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Note: Approved by @claudenbach

**Review by ericangeles — APPROVED** [review]

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The tooltip are working, but it seems like filtering is not working anymore

image

image

image

**Latest**

https://github.com/infor-design/enterprise/assets/156752175/7e28ee60-5b9e-47d2-b2f1-0d1968cc00d6

**Current Branch**

https://github.com/infor-design/enterprise/assets/156752175/1b571d57-34da-46ec-9294-3573ed69f289

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in safari.
image

Also, the search filter seems to be not working. no error in console
image

**Comment by tmcconechy** [comment]
@jbrcna @n-ace-ancog 

Fixed the safari issue and update the example to show filtering (had a setting on to disable it as the tooltip was the original issue here)

**Review by n-ace-ancog — APPROVED** [review]
Now working on my end.

https://github.com/infor-design/enterprise/assets/156752175/7222d75c-b0db-47f5-a752-a3cbe6a17327

**Safari**
image

image

**Firefox**
image

image

**Comment by jbrcna** [comment]
> @jbrcna @n-ace-ancog
> 
> Fixed the safari issue and update the example to show filtering (had a setting on to disable it as the tooltip was the original issue here)

thanks @tmcconechy . approving
image
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
