### PR TITLE
8206 - Added css setting for lookup

### LINKED ISSUE #8206: Custom CSS-Class for Lookup-modals
**Is your feature request related to a problem or use case? Please describe.**
Cannot config custom CSS class for lookup-modal.

**Describe the solution you'd like**
cssClass property already exist in the lookup model setting. but it's didn't apply. 
Please see the example: 
https://stackblitz.com/edit/lookup-single-select-async-bug-7sclkl?file=src%2Fapp%2Fapp.component.css

**Additional context**
(https://stackblitz.com/edit/lookup-single-select-async-bug-7sclkl?file=src%2Fapp%2Fapp.component.css)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added css setting for lookup.

**Related github/jira issue (required)**:

Closes #8206 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/lookup/test-custom-css.html
- Open lookup
- Header should be red text

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]
Can we have this in NG, @yohannahbautista ?

**Review by tmcconechy — APPROVED** [review]

**Comment by ericangeles** [comment]
FYI @infor-design/qa

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/cf687451-ec3a-4f2f-a68e-34c21b99a73f

**Pull request merged**
