### PR TITLE
6746 - datagrid is editable render row

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix bug in datagrid where isEditable is not returning row correctly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6746

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-addrow-with-is-editable.html
- Open `Developer Console`
- Click `Add Row`
- See the `Console`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 this doesnt seem to be working everytime...Try this

- after pressing add row
- click on product name cell on row 2 (index 1) -> says row zero
- click on product name cell on row 8 (index 7) -> says row 6?
- click on product name cell on row 1 (index 0) -> says row 7

I guess when adding the row at the top we need to place it at the top in the array. Then maybe all this will work again?

**Review by tmcconechy — DISMISSED** [review]
Looks like its working well now. Thanks @tjamesallen15 
If you do update this could add a description to the method and it could be private maybe. But not a big deal

**Comment by tmcconechy** [comment]
can you test this one too @deep7102 ?

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
🍌 LGTM!

**Pull request merged**
