### PR TITLE
1580 - Contextual Toolbar hide after action performed

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the contextual toolbar not hiding after peforming button action.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1580

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-contextual-toolbar-hide.html
- Open `Developer Console`
- Click one checkbox to show the toolbar
- Click `Perform Action`
- Toolbar should hide
- Click one checkbox to show the toolbar
- Deselect the checkbox selected to hide the toolbar
- Click the select all to show the toolbar
- Deselect the select all to hide the toolbar
- Go to http://localhost:4000/components/datagrid/test-contextual-flex-toolbar-hide.html
- Click one checkbox to show the toolbar
- Click `Perform Action`
- Toolbar should hide
- Click one checkbox to show the toolbar
- Deselect the checkbox selected to hide the toolbar
- Click the select all to show the toolbar
- Deselect the select all to hide the toolbar

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 a couple of things here im seeing

a) Would use a flex-toolbar instead
b) Maybe the example should be named test-contextual-toolbar-hide.html or something similar around the problem
c) im not sure that we want to automatically assume they want to unselect all rows, as we dont know what the action would be.

Instead i would maybe just suggest adding a function to hide the contextual action toolbar (if not already one) and expose that in the API and docs and show it in the example. Unless im missing something rereading the issue @jaliya-roshen

**Comment by tjamesallen15** [comment]
> @tjamesallen15 a couple of things here im seeing
> 
> a) Would use a flex-toolbar instead b) Maybe the example should be named test-contextual-toolbar-hide.html or something similar around the problem c) im not sure that we want to automatically assume they want to unselect all rows, as we dont know what the action would be.
> 
> Instead i would maybe just suggest adding a function to hide the contextual action toolbar (if not already one) and expose that in the API and docs and show it in the example. Unless im missing something rereading the issue @jaliya-roshen

Hello, Tim! I thought the user has not done yet migrating from flex-toolbar so that's why he wants this fixed for contextual toolbar for now.

**Review by jbrcna — APPROVED** [review]
image

**Comment by tmcconechy** [comment]
ok thanks @tjamesallen15 maybe we can make an example with both toolbars. Also from a behavior standpoint what should happen is when all zero rows are selected the toolbar hides. If any are selected it shows. So maybe it would be tied to selection events (i didnt confirm this if it is already the case). Just a note

**Review by tmcconechy — APPROVED** [review]
👍🏻

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/15cd31b7-992b-46f4-8f84-cbc2beb9b7ba

**Review by janahintal — APPROVED** [review]
Working as expected in https://1580-datagrid-contextual-hide-enterprise.demo.design.infor.com/components/datagrid/test-contextual-flex-toolbar-hide.html & https://1580-datagrid-contextual-hide-enterprise.demo.design.infor.com/components/datagrid/test-contextual-toolbar-hide.html

**Review by jbrcna — APPROVED** [review]
approving. 
verified in https://1580-datagrid-contextual-hide-enterprise.demo.design.infor.com/components/datagrid/test-contextual-flex-toolbar-hide.html & https://1580-datagrid-contextual-hide-enterprise.demo.design.infor.com/components/datagrid/test-contextual-toolbar-hide.html

**Comment by anhallbe** [comment]
@tjamesallen15 this appears to close the toolbar when the button is a menu button:


Uploading Screen Recording 2024-01-19 at 08.42.41.mov…

**Pull request merged**
