### PR TITLE
1145 - Fixed extra text expand-collapse with tree datagrid

### LINKED ISSUE #1145: Extra text (Expand / Collapse) added with tree datagrid
**Describe the bug**
When using editable and treegrid option with datagrid, some extra text (Expand / Collapse) added to the target node soon try to edit parent node cell.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-tree-editable.html
2. Click on any parent node's cell text with (+/-) icon to get in edit mode.
3. Click anywhere else on the page or "Enter" key to get out from edit mode without make any changes.
4. See in that cell's content some extra text (Expand / Collapse) added.

**Expected behavior**
It should not add anything extra.

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Using editable and treegrid, extra text (Expand / Collapse) was adding to the target node after edit parent node cell.

**Related github/jira issue (required)**:
Closes #1145

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/datagrid/test-tree-editable.html
- Open above link
- Click on any parent node's cell text with (+/-) icon to get in edit mode
- Click anywhere else on the page or "Enter" key to get out from edit mode without make any changes
- See in that cell's content should not added any extra text (Expand / Collapse)

### CODE REVIEW

**Comment by tmcconechy** [comment]
Looks ok but maybe:
- update the column widths in the example so that they fill the container.
- ensure the first column has a bit wider width so it doesnt always scroll the text

**Comment by deep7102** [comment]
Updated now, example page to fill column widths

**Comment by deep7102** [comment]
Hi @davidcarlsonberg which browser you having the scrolling issue. I cannot reproduce it

**Comment by davidcarlsonberg** [comment]
On Chrome.

ezgif com-video-to-gif

**Pull request merged**
