### PR TITLE
NA - Fix calendar issues

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

When testing i noticed a problem on the calendar page fixing but please review @RJ-Csc @ericangeles @tjamesallen15
https://github.com/infor-design/enterprise/pull/8011/files caused an issue with the calendar/popup sizes.

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/pull/8011

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/calendar/example-index.html and calendar should not look like https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
- on the same page open the picker by clicking the calendar icon next to Oct should not look like https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html

**Example When Wrong**
Screenshot 2023-10-31 at 11 39 39 AM

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @infor-design/qa

**Review by max-hizon — APPROVED** [review]
Works as expected
image

image

**Review by yohannahbautista — DISMISSED** [review]

**Review by glenlieorillo — DISMISSED** [review]
https://github.com/infor-design/enterprise/assets/102151352/de799997-db59-43fa-87ce-ae5ef154da57

**Comment by jbrcna** [comment]
this is now fixed. however, in Safari, the month label is not visible. it only becomes visible when clicked
image

**Review by janahintal — APPROVED** [review]
Working as expected in https://calendar-issues-enterprise.demo.design.infor.com/components/calendar/example-index.html 

image

image

**Comment by tmcconechy** [comment]
thanks @jbrcna fixed the label in safari

**Review by jbrcna — APPROVED** [review]
nice! Approving
image

**Pull request merged**
