### PR TITLE
7113 - Adjustment in title width

### LINKED ISSUE #7113: Searchfield: input field overlap in mobile view
**Describe the bug**

**To Reproduce**

1. Go to https://4710-beta2-enterprise.demo.design.infor.com/components/header/example-long-title-no-button.html
2.  See error

**Expected behavior**
the long title should have an ellipsis.

**Version**

- ids-enterprise: v4.71.0-beta2

**Screenshots**
image

**Platform**
mobile 

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted title width calculations

**Related github/jira issue (required)**:

Closes #7113 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Change screen width to around 600px
- Go to: http://localhost:4000/components/header/example-long-title-no-button.html
- Title ellipses should appear and should not exceed screen

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I think we need to set the height again after collapsing the search try this

- screen around 620px wide
- go to http://localhost:4000/components/header/example-long-title-no-button.html
- focus the search
- un focus the search
- notice the text remains in the same place

**Comment by tmcconechy** [comment]
See sort of a weird situation...

- start out big so there is no ....
- focus the search
- now resize will the search until its mobile size

Screenshot 2023-01-25 at 1 41 02 PM

- also i think while expanding on mobile the size could be improved....
Screenshot 2023-01-25 at 1 42 53 PM

**Comment by tmcconechy** [comment]
Still seeing the issue on the last comment?

**Review by tmcconechy — APPROVED** [review]
I skipped a couple tests as we are getting rid of e2e tests anyways.

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
