### PR TITLE
8306 - RTL Color Picker

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix RTL alignment for color picker.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8306

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/colorpicker/example-index.html?locale=ar-SA
- Go to Color Picker section
- Click the Color Picker
- Select outside to close the color picker
- Should be the same alignment

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@tjamesallen15 the popup looks good now but on RTL the order of the field is wrong

Screenshot 2024-02-23 at 11 35 12 AM

- Should be swatch -> text -> icon not icon -> swatch -> text

See http://localhost:4000/components/colorpicker/example-index.html?locale=ar-SA

**Comment by tjamesallen15** [comment]
Like this one @tmcconechy ?

image

**Comment by tmcconechy** [comment]
@tjamesallen15 Yes you got it right now. The only minor things

1. In RTL mode can you move the arrow a little more over to the left?
2. There use to be an arrow on the popup 

Screenshot 2024-02-26 at 9 18 14 AM

**Comment by jbrcna** [comment]
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in classic
image

**Review by tmcconechy — APPROVED** [review]
Looks good now

**Comment by tjamesallen15** [comment]
FYI @infor-design/qa

**Review by janahintal — APPROVED** [review]
image
image

image
image

image
image

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
