### PR TITLE
403 - Improve Listview Accessibility

### LINKED ISSUE #403: Accessibility: Failed Listview Accessibility Tests
Original Issue: http://jira.infor.com/browse/SOHO-7938

----

Axe is reporting the following WCAG2AA errors as critical errors on a handful of Listview component test pages:

- http://localhost:4000/components/listview/example-index:

> _Description:_
> Ensures ARIA attributes are allowed for an element's role 
> 
> _Fix any of the following:_
> ARIA attribute is not allowed: aria-selected="true"...
>```
> <li class="selected" aria-selected="true" tabindex="0">
>  <a href="#" aria-disabled="true"><span class="audible">You are currently on page  </span>1</a>
> </li>
>```
> Breaks axe rule: `aria-allowed-attr`

- http://localhost:4000/components/listview/example-mixed-selection
- http://localhost:4000/components/listview/remove-clear

Screen Shot 2018-05-11 at 4 35 50 PM

> _Description:_
> Ensures every form element has a label
>
> _Help:_
> Form elements must have labels for about 12 nodes...
>
> _Fix any of the following:_
> - `aria-label` attribute does not exist or is empty
> - `aria-labelledby` attribute does not exist, references elements that do not exist or references elements that are empty or not visible
> - Form element does not have an implicit (wrapped) `<label>`
> - Form element does not have an explicit `<label>`
> - Element has no title attribute or the title attribute is empty
>```
> <input tabindex="-1" type="checkbox" class="checkbox hide-focus">
>```
> _Breaks axe rules:_
>   - `aria-label`
>   - `aria-labelledby`
>   - `implicit-label` 
>   - `explicit-label` 
>   - `non-empty-title`

- http://localhost:4000/components/listview/example-mixed-selection:

> _Description:_
> Ensures ARIA attributes are allowed for an element's role
>
> _Help:_
> Elements must only use allowed ARIA attributes
> 
> _Fix any of the following:_
>  - ARIA attribute is not allowed: `aria-selected="true"`
>```
> <li class="selected" aria-selected="true" tabindex="0">
>   <a href="#" aria-disabled="true"><span class="audible">You are currently on page  </span>1</a>
> </li>
>```
> _Breaks axe rules:_
>  - `aria-allowed-attr`

Follow debugging instructions on docs/TESTING.md to investigate the issue in the devTools console, and run test in high-contrast which has disables zero rules. These errors can also be double checked with Chrome Audit in devTools, or use the Chrome or Firefox extension, https://www.axe-core.org/

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR:
- Reenables failed Listview accessibility tests
- Makes changes to the markup rendered for the Listview's items and pager bar to improve screen reader interactions.
- Adds a utility for aXe e2e tests that provides some console output when those tests fail

**Related github/jira issue (required)**:
Closes #403

**Steps necessary to review your pull request (required)**:
Pull this branch and run the demoapp, then look at the following pages to ensure there are no visual problems:
- http://localhost:4000/components/listview/example-index
- http://localhost:4000/components/listview/example-mixed-selection
- http://localhost:4000/components/listview/remove-clear

Additionally, if you have the aXe extension for Chrome, run it against those pages to ensure there are no accessibility problems with the HTML markup.  This testing is duplicated by the newly re-enabled e2e tests included in this PR, which should all pass.

**Includes**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Looks good, saw one aXe scanned issue for more `...`  button in header for `Buttons must have discernible text` I think if we can modifies [this rule](https://github.com/infor-design/enterprise/blob/e4cafb2d8374ede4a9d32aa1ae343ea2c95029cc/src/components/toolbar/_toolbar.scss#L359) not to be hidden hopefully it can fix this case too.

**Comment by EdwardCoyle** [comment]
@deep7102 which example did you see this on?

**Comment by deep7102** [comment]
I saw on all three
- open any example with chrome and open aXe ext by dev tools
- make browser window small (ie. phone size)
- refresh the page
- run aXe "ANALYZE" and see there
http://localhost:4000/components/listview/example-index
http://localhost:4000/components/listview/example-mixed-selection
http://localhost:4000/components/listview/remove-clear

**Comment by tmcconechy** [comment]
I see that, it seems like it works if you move the audible span in front of the SVG. So that should be an easy error to get rid of if you want?

**Comment by EdwardCoyle** [comment]
Just raised #2088 for the header button changes

**Pull request merged**
