### PR TITLE
8484 - Add visual indicator for drag and drop on rows

### LINKED ISSUE #8484: IDSdatagrid: Add visual indicator for drag and drop on rows
In the datagrid, please add an indicator for drag & drop functionality in rows. Use the same indicator that we use for drag & drop for columns. 

Please see more info in this Jira ticket: https://jira.infor.com/browse/IDS-1302

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds visual indicator (border bottom color) for drag and drop on grouped rows in datagrid.

**Related github/jira issue (required)**:

Closes #8484

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Group row reorder
- Go to http://localhost:4000/components/datagrid/example-grouping-row-reorder.html
-  Drag any of the rows
- It should show visual indicator (border bottom color)

2.) Row reorder (Non Group)
- http://localhost:4000/components/datagrid/example-row-reorder.html
- Reorder any of the rows
- It should show visual indicator (border bottom color)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Indicator is not on the correct rows or not showing once page scroll is triggered. When scrolled at the very bottom of the page, indicator is not showing anymore.

Animation

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
**Some issues found**

1. An error occurs when dragging a row in the header row.
Animation

2. No visual indicator when selected **reset to default** option - is this also supported @ericangeles?
Animation

3. No indicator as well found in http://localhost:4000/components/datagrid/example-row-reorder.html - maybe same case as item 2
Animation

**Comment by ericangeles** [comment]
@n-ace-ancog, I am not getting any errors. This PR is only for the group row, so you cannot see the feature in that example.

**Comment by ericangeles** [comment]
I think if you hold too much in the row it shows the error?

**Comment by ericangeles** [comment]
This is for Grouped Row only feature @infor-design/qa.

**Review by n-ace-ancog — DISMISSED** [review]
Working as expected now.
Animation

**Baseline bug** 
- After swapping any two rows, dragging the row while not using the draggable indicator causes errors in the console. Replicated in main.
Animation

**Review by n-ace-ancog — APPROVED** [review]
All working as expected now.
Animation

**Review by janahintal — DISMISSED** [review]
Working as expected on my end in 
https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html

**Review by jbrcna — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles asking design to review. One note: If approved this should go on all row-reorder examples not just the group one i.e. https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html

**Comment by ericangeles** [comment]
@tmcconechy, sure thing. I was also looking into that, but the JIRA ticket does not provide detailed information, and the difficulty is only set at `2`.

**Comment by tmcconechy** [comment]
@ericangeles agreed maybe make it a 3? doesnt really matter thats what they communicated to me in a call.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Visual Indicator is not properly aligned in RTL.

image


https://github.com/infor-design/enterprise/assets/102151352/275c6a83-0fa1-4332-a570-d65557ddac86

**Review by jbrcna — CHANGES_REQUESTED** [review]
confirming on my end as well
visual indicator is not aligned on the left border. RTL
image

**Comment by ericangeles** [comment]
@infor-design/qa ready for testing in non group row reorder. I updated the steps to test it.

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in Safari
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Visual indicator is not present in Safari.

https://github.com/infor-design/enterprise/assets/102151352/65e0b743-5921-4b17-8131-23de1351b04e

Visual indicator is still misaligned in RTL.

https://github.com/infor-design/enterprise/assets/102151352/b8f5139f-3e20-41a0-96b2-f8985303274d

https://github.com/infor-design/enterprise/assets/102151352/1b0bcd9c-a3d6-4421-9fd6-9b18b45d2ee5

https://github.com/infor-design/enterprise/assets/102151352/b9ec3284-b5f8-4538-9d50-d4d649741e84

**Comment by ericangeles** [comment]
@glenlieorillo @jbrcna, I've pushed a fix for Safari not showing the visual indicator. However, you may notice some flakiness in the indicator. This is due to an existing issue in the 'arrange' component. Perhaps consider creating a separate issue for the flakiness, as it will require more debugging and fixing. You can check https://main-enterprise.demo.design.infor.com/components/arrange/example-index to see the console and observe the error, although I've already fixed it [here](https://github.com/infor-design/enterprise/pull/8621/files#diff-1876b41eec7910543cc452fce97f87b7c2cf4a6667adbd5fd87af13a0e208254R358).

**Comment by tmcconechy** [comment]
@ericangeles the feedback i got from the design is...

a) Can we make the column shorter (so it doesnt take up so much space) maybe about 16px padding on each side from the icon
b) Can the line go horizontal across the rows. Should be a black line with no arrows like this but black.

Screenshot 2024-04-23 at 10 35 37 AM

**Comment by ericangeles** [comment]
@tmcconechy can we have a figma design or even just the spec of the border? (thickness, color in dark mode etc.)

**Comment by tmcconechy** [comment]
Thats it in the screen shot... Amanda did it with just a screen shot tool like a one off. 

its: color-gray-70 and a 3 px height.

**Review by jbrcna — APPROVED** [review]
the visual indicator can now be seen in Safari browser.
image

**Review by janahintal — CHANGES_REQUESTED** [review]
No Visual Indicator in Windows Chrome browser: 

https://www.loom.com/share/c13ba466ec1f4c7a8ea066004309d256?sid=47c30bca-358e-42cc-879a-b718622d86d6

https://www.loom.com/share/6e7f735afbf948acad28de493e9dcebc?sid=e7ef280e-ae91-489c-b227-d5b4baa2e6e7

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Some observations:
1. The visual indicator works on very slow movement, but when dragging items faster - its unnoticeable. As per the `gif` below, the 1st part I am dragging the rows considerably slow to trigger the indicator compared to the 2nd part where I drag it to what I consider normal where the indicator rarely shows up
Animation
2. The visual indicator only shows up when meeting a specific condition. As I observe, it only shows when the floor of the moving row is close or overlaps on the floor of the row being replaced. This maybe related to item 1.
Animation

**Comment by jbrcna** [comment]
the vi only shows when it merges with the bottom border. may I clarify if is this by design?
image
image

**Comment by tmcconechy** [comment]
@ericangeles im not seeing the divider. But when i drag i see it move a few pixels (maybe it needs to be fixed position) but its also invisible

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Same observation. No visual indicator or divider upon dragging a row. 

https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html

https://github.com/infor-design/enterprise/assets/102151352/fefa403c-0c62-4cdc-ab5c-192255446522

**Comment by jbrcna** [comment]
same on my end as well.
image

**Review by janahintal — CHANGES_REQUESTED** [review]
No visual indication when dragging down 
https://www.loom.com/share/1318f1ac11e6453b82ee8957a5db8308?sid=5915c2f2-8bd5-4132-9b2d-ce746c99257c

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Very nice! 

**Found some issues**
1. It seems in the in the group reorder data grid, dragging the rows from bottom to the top doesn't trigger it always.

**Group re-order** - encountering issues
Animation

**Row reorder** - seems ok
Animation

2. The indicator is not that visible in dark mode - more if dragging it where there's a header row below

Animation

Animation

**Comment by ericangeles** [comment]
@n-ace-ancog, that's the default behavior in the grouping. We can discuss that with the design team, @tmcconechy. The way you drag it to swap it is to reposition the entire section of the row. Again, this one isn't specced out. Could you classify it as a bug? We can fix it if we have more time for the next sprint.

**Review by glenlieorillo — DISMISSED** [review]
This is now working as expected. However, the visual indicator is not visible in Dark Mode as mentioned by @n-ace-ancog.

https://github.com/infor-design/enterprise/assets/102151352/4ca5a40b-11b2-4894-bdaa-6f93dc83b7d9




https://github.com/infor-design/enterprise/assets/102151352/2e352a40-eeb7-443b-b9e1-49fb43cc6c8d



https://github.com/infor-design/enterprise/assets/102151352/26529b2c-7ea3-4ac3-9c9b-db4632e9ead8




https://github.com/infor-design/enterprise/assets/102151352/5307bb6e-49f0-4d83-8504-9ff5b63cb86c

**Comment by ericangeles** [comment]
@n-ace-ancog @glenlieorillo, I pushed a fix for dark theme.

**Review by jbrcna — CHANGES_REQUESTED** [review]
the visual indicator can now be seen and obvious. 
image
image

However, when you move an item and place it over the row you wanted it to be transferred, it goes over the top of the supposed row
see below.. I am placing it on 2nd row and it goes over the 1st row. Notice that the indicator is in the 2nd row
Large GIF (678x412)

Also in dark mode, v.i is not shown
image

**Comment by tmcconechy** [comment]
@ericangeles yeah this is an enhancement and im ok with leaving this out of this release. Its not well thought out.

On https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html it seems like:

a) any items a drag do not stay in that position (for example try to drag 6 to the top)
b) when the indicator appears it moves the rows up and down a couple pixels

**Review by n-ace-ancog — COMMENTED** [review]
Visual indicator are now more visible in dark mode.

Animation

@ericangeles - i just noticed that the cursor + the indicator are telling a different actions that can be done.

For example in the baseline, the cursor is telling me when the row is ready to be dropped
Animation

But in this branch, the cursor was in ready state with the indicator, but upon releasing it did not swap rows. I had to go further for the row swapping to happen, but then the **blocked** cursor appears
Animation

**Comment by ericangeles** [comment]
@tmcconechy, let's park this for now and present the intended design and behavior to the design team. It will be a waste of time if we don't have the correct guidelines for this feature.

**Review by janahintal — CHANGES_REQUESTED** [review]
The visual indicator in https://8484-datagrid-drag-icon-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html is incorrect when dragging from bottom to the first row & no visual indicator when dragging  second row to first row. 



https://www.loom.com/share/30f3b7c881de40c387ef53ed86486bff?sid=b2fbeec8-1008-4d57-8541-ea39ed397f85

**Comment by ericangeles** [comment]
Closing this PR as I will create a new fix for this feature.

**Pull request closed without merging**
