### PR TITLE
526 - Fix datagrid code-block editor focus

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed code-block editor focus was not working with Datagrid.

**Related github/jira issue (required)**:
Closes infor-design/enterprise-ng#526

**Steps necessary to review your pull request (required)**:
- Pull and build this branch
- Pull and build NG branch ([526-datagrid-code-block-focus](https://github.com/infor-design/enterprise-ng/tree/526-datagrid-code-block-focus))
- Copy and replace "dist" folder from `enterprise` to `⁨enterprise-ng⁩/node_modules⁩/ids-enterprise`
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/datagrid-code-block-editor
- Put focus in the Company cell of any row
- Press tab key to into Code Block cell
- Continue pressing tab key to tab across the input fields that make up the Code Block
- Attempt to tab into the Name cell
- Focus should be working fine

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @claudenbach is it possible to test this on your end?

**Comment by deep7102** [comment]
Hi @tmcconechy @EdwardCoyle updated now, `Shift + Tab` should work now.
- place cursor in company
- tab until to get to the name field
- shift tab should go back

**Comment by tmcconechy** [comment]
@deep7102 I do see the menu moved over a bit and i did update but im still seeing the issue. If i focus the name field and shift tab backwards it goes to the first field in the code block not the last.

**Comment by deep7102** [comment]
Hi @tmcconechy updated now, to fix the case shift tab backwards

**Comment by tmcconechy** [comment]
Im also seeing that if you open the ... menu at the end of the code block you get kicked out of edit mode.

**Comment by deep7102** [comment]
- Waiting to see if we need to remove the animation on borders
- For last ... menu if you see its still in edit mode just the border look, because focus on popup and whole cell is has border I think that is just the way it style

**Comment by tmcconechy** [comment]
Going to merge as i need this code for what im working on and its approved. @claudenbach can still test and give feedback on master when your ready.

**Pull request merged**
