### PR TITLE
6047 - Sync with the new design (Searchfield with headers/subheader)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR refines some of the colors (font color, background color, etc.) for all modes (Light, Dark, High Contrast).

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/6047

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

Go to (New Theme)
- http://localhost:4000/components/header/example-searchfield-full.html
- http://localhost:4000/components/header/example-searchfield-full.html?theme=new&mode=dark
- http://localhost:4000/components/header/example-searchfield-full.html?theme=new&mode=contrast
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=light
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=dark
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=contrast
- Compare it to the design https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/Search_Enhancements?node-id=209%3A2536

Test also in Classic Theme
- http://localhost:4000/components/header/example-searchfield-full.html
- http://localhost:4000/components/header/example-searchfield-full.html?theme=classic&mode=dark
- http://localhost:4000/components/header/example-searchfield-full.html?theme=classic&mode=contrast
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=classic&mode=light
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=classic&mode=dark
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=classic&mode=contrast

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Expecting some visual tests to be failed. Will fix it once identified.

**Comment by ericangeles** [comment]
Adding WIP as I need to still adjust the height of the search field, icon sizes, alignments, etc. Making it pixel perfect.

**Comment by ericangeles** [comment]
Open for review now. Once okay with the newly implemented design, I will fix the failing visual tests (expecting a LOT).

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks good except i noticed that the non expandable header icon is the wrong color here http://localhost:4000/components/header/example-index.html

Aside from that - this is all i found

**Review by tmcconechy — DISMISSED** [review]

**Review by tjamesallen15 — CHANGES_REQUESTED** [review]
image

I checked it using Mozilla Firefox and the Icon above is currently misaligned. This is also seen in the following links
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=light
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=dark
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=contrast
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=classic&mode=light
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=classic&mode=dark
http://localhost:4000/components/header/example-toolbar-flex-with-categories.html?theme=new&mode=contrast

**Comment by ericangeles** [comment]
@tjamesallen15 I think it has something to do with the fix that was also made in the lookup component. Good catch!

**Review by tjamesallen15 — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
