### PR TITLE
7909 - Add `truncated` setting with tootltip on validation messages

### LINKED ISSUE #7909: Validation: Add setting to not wrap the validation message
**Describe the bug**
The alert message shown for soho-lookup validation gets overlapped with other fields if the alert message has width greater than the input.

**To Reproduce**
1. Add a custom validation which has an alert message like "Value is not found in the list" for a lookup.
2. Click on the lookup and select a value.
3. Make changes to the value selected in the input such that the value does not exist in the list of values.
4. Then we trigger a custom validation message saying, "Value is not found in the list".

**Expected behavior**
The expected behavior would be if the alert message exceeds the length of the soho-lookup field it should a ellipsis to the end of the text and adjust the validation message in the given width and add a soho-tooltip, on which if we hover it should show the complete text.

**Version**

- ids-enterprise-15.2.8

**Screenshots**
Observed behavior:

92c03836-8cf0-4c72-8dbe-3e729721aef7

Expected:

6a8ebe59-73e8-411e-b4fb-819f8bf0d938

**Additional context**
Also, for accordion labels the soho-tooltip is being handled effectively we can see if the content exceeds the given width it automatically adjusts adds the ellipsis and tool-tip

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds a feature that allows you to truncate validation messages and display a tooltip. This is useful if you have a long validation message.

**Related github/jira issue (required)**:

Closes #7909

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/validation/test-truncated-with-tooltip
- Type `2`, then tab out to show the error message
- Message should be truncated
- Hover on it
- It should show tooltip and its message

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Maybe add to the docs?

**Review by n-ace-ancog — APPROVED** [review]
Working as expected on my end.

image

image

image

image

image

image

**Review by jbrcna — APPROVED** [review]
image
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Failing in Safari. Showing two tooltips upon hovering.

https://7909-validation-truncate-setting-enterprise.demo.design.infor.com/components/validation/test-truncated-with-tooltip

**LTR**
image

**RTL**
image

**Comment by ericangeles** [comment]
Looks like on Safari, when you use `white-space: nowrap` seems to trigger the automatic display of native tooltip.

The last commits should address this issue.

**Review by glenlieorillo — APPROVED** [review]
Working now as expected in Safari.

image

**Review by n-ace-ancog — APPROVED** [review]
Chrome:
image

Safari:
image

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
