### PR TITLE
8218 - Fixed disabled color for colorpicker

### LINKED ISSUE #8218: Datagrid: Colorpicker on a disabled row is not greyed out
**Describe the bug**
In a datagrid, when a row containing a color picker is disabled, the content of other cells are greyed out, but the colorpicker is not.

**To Reproduce**

1.  Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-colorpicker.html
2.  In the code, add the property 'isRowDisabled: true' to the first row

Result:
image

**Expected behavior**
Would expect the text for the colorpicker in the disabled row to be grey.

**Version**

- ids-enterprise: 4.82.1

**Screenshots**
image

**Platform**
- Infor Application/Team Name: Lawson
- OS Version: Windows 11
- Browser Name: Chrome
- Browser Version: 119.0.6045.106 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed disabled color for colorpicker

**Related github/jira issue (required)**:

Closes #8218 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-editable-colorpicker.html
- Last row should have colorpicker in disabled color

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
I found some bugs under `Colorpicker` column:

https://github.com/infor-design/enterprise/assets/102151352/79e1b29a-98ca-4207-ac76-e453074c3fcf

Dropdown icon is not properly aligned.
image

Dropdown icon is not rendered properly upon selecting/deselecting the cell.
image

`None` color is not rendered properly in `Extra small`, `Small`, `Medium` Row Height. 
image

Contents under `Colorpicker` column are cut-off in `Medium` Row Height.
image

Dropdown icon should be placed before the color code in RTL. 
image

**Review by jbrcna — DISMISSED** [review]
color picker is now greyed out
image

**Review by jbrcna — COMMENTED** [review]
maybe not related to fix in this PR but noting for reference. 

**Observations**
icon not centered
image

icon is cut off upon selecting in dropdown
image

red line overflows in smaller row heights
image

swatch icon is cut off
steps
1. click to open color picker
2. click outside
image

**Comment by tmcconechy** [comment]
@yohannahbautista feel free to fix what you can/want for now and put the rest in a future issue. For me i would say just the basic column should render like the icon / editor should function and look ok

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
image
image

Existing
image

image

**Review by glenlieorillo — APPROVED** [review]
Still seeing the same issue from the above comments. However, the fix related to this issue has already been applied. Approving for now.

image


https://github.com/infor-design/enterprise/assets/102151352/f377f667-331e-4c2b-9a4a-4ed592256d63

**Pull request merged**
