### PR TITLE
7974 - Fix disappearing popup borders.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted overflow of time parts and sizing of month view popup container to avoid disappearing borders.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7974
Closes https://github.com/infor-design/enterprise/issues/6865

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/datepicker/example-timeformat.html
- Switch to responsive mobile view.
- Open any date picker popup.
- Shorten width dimension to 322.
- Popup borders should not disappear.

For https://github.com/infor-design/enterprise/issues/6865:
- Open month picker of any date picker popup.
- Highlighting should be consistent.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@RJ-Csc i dont think this will work. Because it adds a box shadow thats unwanted to the monthview https://main-enterprise.demo.design.infor.com/components/monthview/example-index.html

But if you add the same fix to the monthview-popup class it qualify it, could be ok https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/_datepicker.scss#L105

Also the overflow: auto makes it show an unwanted scollbar.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — DISMISSED** [review]

**Comment by ericangeles** [comment]
@infor-design/qa fyi

**Comment by max-hizon** [comment]
Using width dimensions from 320 and 568 displaces the centered inner blue circle
image

**Comment by tmcconechy** [comment]
@RJ-Csc up to you if you can fix the comment from @max-hizon in addition or want a new issue?

**Comment by jbrcna** [comment]
image

**Comment by tmcconechy** [comment]
@RJ-Csc can you check into what @jbrcna pointed out. that should probably be fixed.

**Comment by ericangeles** [comment]
@infor-design/qa can you review this again?

**Comment by ericangeles** [comment]
@RJ-Csc, where are we on this?

**Comment by RJ-Csc** [comment]
Hello @ericangeles, will be pushing updates in a bit. Was messing around with the place component as it dealt with the sizing of the popover, but decided to go with a css fix instead.

**Comment by RJ-Csc** [comment]
This should also close https://github.com/infor-design/enterprise/issues/6865

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi Team, kindly see test result below. 

Date Time Picker in Locale (Time to Current) looks cut off and has scroll bars in mobile 

https://7974-datepicker-popup-missing-borders-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?theme=classic&mode=light&colors=default 

Version: Classic 
Mode: Light 
Color: All
Environment: Mobile iOS 15 iPhone 13 all browsers

image


Cheers!

**Comment by tmcconechy** [comment]
cc @RJ-Csc

**Comment by ericangeles** [comment]
Are you having difficulty with this, @RJ-Csc? Can you help him, @tjamesallen15? Thank you.

**Comment by ericangeles** [comment]
@RJ-Csc, I wouldn't recommend doing a force push; instead, make it a habit to pull any updates into your branch. This might cause problems in your PR and probably when merging it into the main branch.

**Comment by RJ-Csc** [comment]
@infor-design/qa

**Review by jbrcna — APPROVED** [review]
image

image

**Comment by jbrcna** [comment]
in mobile view dimension: 320 x 568
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Border still disappearing in mobile view.

BrowserStack (iPhone 13 v15)
https://7974-datepicker-popup-missing-borders-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html

image

**Review by ericangeles — APPROVED** [review]
It looks okay now on the iOS device, @glenlieorillo. I only see it when checking it from landscape and rotating it to portrait, but I don't think that this is a deal breaker. So it's good on my end.


Screenshot 2023-10-24 at 10 01 15 AM


@jbrcna, do you know of any smartphones that have a resolution of `320x568`? I don't think this size is common on modern smartphones; it seems more like a feature of low-end devices.

**Review by max-hizon — APPROVED** [review]
Works as expected

image


image


Border issue fixed but new issue on where the popup arrow points to. Will issue a new ticket for it
image

**Review by glenlieorillo — APPROVED** [review]

**Comment by RJ-Csc** [comment]
Hello @infor-design/qa. Please test for https://github.com/infor-design/enterprise/issues/6865 in this PR as well.

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
> It looks okay now on the iOS device, @glenlieorillo. I only see it when checking it from landscape and rotating it to portrait, but I don't think that this is a deal breaker. So it's good on my end.
> 
> Screenshot 2023-10-24 at 10 01 15 AM
> @jbrcna, do you know of any smartphones that have a resolution of `320x568`? I don't think this size is common on modern smartphones; it seems more like a feature of low-end devices.

I have approved this @ericangeles . the 320 x 568 testing is based on the steps in this PR. but the screenshots of [this](https://github.com/infor-design/enterprise/pull/8011#pullrequestreview-1692310328 ) is from BrowserStack (iPhone 13 v15). that is why I previously approved this pr and just put the screenshot for reference.

**Pull request merged**
