### PR TITLE
NG 1431 - Fixed bug in Safari where dynamically switching from RTL to LTR doesn't update all the alignments

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated dir to ltr instead of removing dir attribute when changing locales to make Safari update alignments.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1431

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Open Safari
- Go to: http://localhost:4000/components/datagrid/test-rtl-swap
- Click on Arabic button
- Check alignments. Click on editable fields and check alignments
- Click on English button
- Check alignments. Click on editable fields and check alignments

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista just wondering if there is any other solution (maybe with css) because the attribute really shouldnt need to be there if its LTR since a) there is no css against that and b) its the default?

I tried without it and the only issue i noticed with the datagrid column dividers? Is that the only issue?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Wondering if there is another fix other than adding the attribute when its not need. Since its its already the default it doesn't seem like it should be needed. Maybe a css solution or more component specific solution?

**Comment by ericangeles** [comment]
It looks like for some reason in Safari, when switching back to English, the datagrid doesn't go back to its LTR look. As a result, the `showLabel` column remains in the left section. That's why the current CSS rules does not work.

**Comment by ericangeles** [comment]
@tmcconechy checking the example page and the issue is reproducible there. I don't see any way to fix it via CSS only (as I've mentioned above the behavior of current issue) and am okay with the fix, not unless it's a breaking change.

Or we might want to just isolate the adding attr `ltr` in safari only.

e.g.,

```
else if (self.isSafari) {
  html.attr('dir', 'ltr');
}
```

Open for discussion.

**Comment by yohannahbautista** [comment]
Hello, it's not just datagrid that doesn't render properly, toolbar has an issue too. If I run the page without the change:
(added another toolbar to test other components)

Original page
image

After clicking Arabic, then English
image
The toolbars don't fully go back to its previous alignment.

**Comment by tmcconechy** [comment]
Ok Wierd. @ericangeles @yohannahbautista if thats the only way I guess its minor that it adds the attribute. Safari is wierd, i just felt like it shouldnt be needed since its the default but if thats the only way I'll approve

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
