### PR TITLE
6072: Puppeteer Script for Calendar event colors should accept color keywords

### PR DESCRIPTION
**Pull request by janahintal**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Calendar puppeteer test for #6072  

**Related github/jira issue (required)**:

#5743 

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer calendar`
4. It should pass.

Steps:
Scenario 1: Legend Colors
Given user is on https://main-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html
Then I should see the custom colors in events and legends
And the colors on the event types displayed in the calendar should also be reflected in the legend
When I Uncheck a legend
Then it should not display the event accordingly
When I check a legend
Then it should display the event accordingly

Scenario 2: Creating new event
Given user is on https://main-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html
Then I should see the custom colors in events and legends
And the colors on the event types displayed in the calendar should also be reflected in the legend
When I create an event via Add Even (Api) 
Then I should see a new random event
And the color should be similar to Team Event
When I create event via Add event (Modal)
Then I should see a new event
And the colors on the event types displayed in the calendar should also be reflected in the legend

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
The tests look good to me. But im seeing some other failure. Rerunning

**Comment by deep7102** [comment]
Looks all good, found one thing as `Scenario 2` the legend color is not same as event checkbox color.
http://localhost:4000/components/calendar/test-event-custom-colors.html
- Create event via Add event (Modal)
- See legend color

IDS-Enterprise-2022-02-02

**Comment by tmcconechy** [comment]
@deep7102 this is noted on failed QA issue for the task https://github.com/infor-design/enterprise/issues/5743 i think @tjamesallen15 will fix soon

**Review by deep7102 — DISMISSED** [review]

**Comment by ericangeles** [comment]
Looks good! @janahintal please add a changelog for this PR. Thanks!

**Comment by janahintal** [comment]
Hi, I will add the Add Event Api test once all the background colors are equal on event and calendar. 
image

image

**Review by tmcconechy — APPROVED** [review]
FYI chrome driver is fixed on https://github.com/infor-design/enterprise/pull/6094

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
