### PR TITLE
NG1651 - Fixed asterisk being cut off when textOverflow is set to ellipsis

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed asterisk being cut off when textOverflow is set to ellipsis

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1651

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to
  - http://localhost:4000/components/datagrid/example-editable.html
  - http://localhost:4000/components/datagrid/test-ellipsis.html
- Required columns should have asterisk (*) fully viewable
- Minimize columns
- Ellipsis should still appear

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Looks good. Just please check the lint error

**Review by jbrcna — APPROVED** [review]
image
image
image

**Comment by tmcconechy** [comment]
@yohannahbautista now starting 4.98.0 for the change log

**Review by jbrcna — APPROVED** [review]
image
image
image
image

**Review by glenlieorillo — APPROVED** [review]
image

image

**Pull request merged**
