### PR TITLE
1731 - Cards Selected and Deselected Event

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug selected and deselected event are not triggered on action.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1731

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/cards/example-multi-select.html
- Open `Developer Console`
- Try to select, unselect a card
- See the logs

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
@tjamesallen15 did you try to confirm this works in the NG project?

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/7cc0c5a4-8bbd-4b10-935a-2327eca14225

**Review by janahintal — APPROVED** [review]
image

**Pull request merged**
