### PR TITLE
7845 - Pie/Donut Legend Item Select

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the displayed legend when selecting a different one.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7845

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/donut/example-legend-bottom-popup.html
- Click on the dropdown then select "Open (26%)"
- Expect the text "Response Late (62%)" to change to "Open (26%)"

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — APPROVED** [review]
:heavy_check_mark:

image

**Review by ericangeles — APPROVED** [review]
Great work, @tjamesallen15 ! 🍌

**Review by max-hizon — APPROVED** [review]
Working on all other legends as well

image

image

image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

Mac Chrome
https://github.com/infor-design/enterprise/assets/102151352/0262c010-5588-40ab-b8e2-360923ea0284

Safari
https://github.com/infor-design/enterprise/assets/102151352/50c2574f-4780-445b-a581-fbc974b4ec54

Mac Firefox
https://github.com/infor-design/enterprise/assets/102151352/c242c8d4-1cf1-4fcf-9e47-bd247d2f1bb8

**Pull request merged**
