### PR TITLE
7116 - Timepicker fix field value when day period goes first in the time format

### LINKED ISSUE #7116: Timepicker with Korean locale gives an invalid value
**Describe the bug**
When using the timepicker component with a Korean locale (ko-KR), the value that the user selects is invalid.

**To Reproduce**
1. Open the URL: https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=ko-KR
2. Click the clock icon to open the value selector.
3. Select a time, any time, and press the 'Set Time' button.
4. Note the field validation immediately shows an error.

**Expected behavior**
The value entered using the selector should be a valid value.

**Version**
Ent: 4.70.0
NG: 14.7.0
**Screenshots**
image
Note in the screenshot above, the value returned from the selector puts the day period value (오전) after the time value (1:00).

If you manually enter the day period value BEFORE the time value, the value is valid. For example:
image

If you look at the IDS ko-KR locale file, you'll see that the timeFormat is 'a h:mm'.
 
**Platform**
 - Infor Application/Team Name: GLT
 - Device: 
 - OS Version: Win 11
 - Browser Name: Chrome
 - Browser Version: 109.0.5414.75 

**Additional context**

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes field value when day period goes first in the time format by using locale format date to set value on the field

**Related github/jira issue (required)**:
Closes #7116 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/timepicker/example-index.html?locale=ko-KR
- select a time and press the `Set Time` button
- see the day period goes first in the field and there are no validation errors
- go to http://localhost:4000/components/timepicker/example-index.html?locale=zh-CN
- select a time and press the `Set Time` button
- see the day period goes first in the field and there are no validation errors

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
But see a failing test `Timepicker Puppeteer Tests › Timepicker Chinese Localization Tests › should set the time and period without any error message` -> reran it to confirm but

I can also see it on

http://localhost:4000/components/timepicker/example-index.html?locale=zh-CN
compare to https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN

I guess we will need to use the AM/PM position somehow in the fix?

**Comment by tmcconechy** [comment]
@andriivarhanov can you see if https://github.com/infor-design/enterprise/issues is closely related

**Comment by andriivarhanov** [comment]
@tmcconechy I think these two are related https://github.com/infor-design/enterprise/issues/7188 and https://github.com/infor-design/enterprise/issues/7191 , the timepicker doesn't parse/format field value correctly in case of `a h:mm` `ah:mm` formats, apparently 24h format as well, trying to use `Locale` to parse/format the value

**Review by tmcconechy — APPROVED** [review]
Looks good. Thanks @andriivarhanov

**Review by ericangeles — APPROVED** [review]
Great work, @andriivarhanov! Thanks!

**Pull request merged**
