### PR TITLE
7408 - Adjusted alignment for popupmenu icon buttons

### LINKED ISSUE #7408: Buttons: Overlapping icons in menu buttons
**Describe the bug**
Buttons: Overlapping icons in menu buttons

**To Reproduce**

1. Go to http://localhost:4000/components/button/example-menubutton-submenu-icons.html
2. Open the menu button 
3. Also test in Classic version

**Expected behavior**
Icons should not overlap 

**Version**
IDS-4.82-DEV

**Screenshots**
image
**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted alignment for popupmenu icon buttons

**Related github/jira issue (required)**:

Closes #7408 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/button/example-menubutton-submenu-icons.html
- Open menu button
- Open Actions
- Icons should be aligned

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Looks good to me! Can you create a new changelog for `4.84` and put this fix log there? Thanks, @yohannahbautista 🍌

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
looks good. ready for QA

**Review by deep7102 — COMMENTED** [review]
Looks good 🍌 
@yohannahbautista are we going to up[date change log?

**Review by jbrcna — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — COMMENTED** [review]
Tested and passed.

Verified in: http://localhost:4000/components/button/example-menubutton-submenu-icons.html

image

**Comment by janahintal** [comment]
Failing in Mobile / Responsive view
image

**Comment by ericangeles** [comment]
@janahintal please create a ticket issue for that one.

**Pull request merged**
