### PR TITLE
7826 - Calendar Custom Colors

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix custom colors render of events.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7826

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-event-custom-colors.html
- See the custom event colors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Event title in the Right Side event summary is not visible in some modes

- https://7826-calendar-custom-colors-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html?theme=new&mode=light&colors=default
- https://7826-calendar-custom-colors-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html?theme=new&mode=contrast&colors=default

image
image

Different event color displayed in Classic 
e.g see Administrative Leave event color as the same as with Discretionary time off
https://www.loom.com/share/88671fa3af1243eca5431566a6c95169?sid=5fda1792-3d65-405f-96b3-e3579907023e

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The color doesn't change when changing the event type.

**Steps to reproduce:**
1. Create new event by double clicking the desired date
2. Select type (_eg. Discretionary Time Off_)
3. Click `Submit` button
4. Click the created event
5. Change the event type then click again the `Submit` button
6. Change again the event type to Discretionary Time Off
7. Notice the event color

https://github.com/infor-design/enterprise/assets/102151352/b1bd0e3b-164c-4151-b6f4-46975585a5b2

**Review by janahintal — CHANGES_REQUESTED** [review]
There is unnecessary object in the right side of the card when in responsive view. 
Pager is still not centered. 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Tab color for `Sick Time` is different.
image

When you change the view to Week/Day, the color is being change.

- Month View
image

- Week View

image

- Day View
image


https://github.com/infor-design/enterprise/assets/102151352/4cb899e4-07d1-4967-b4a3-d217532a2845

**Review by janahintal — CHANGES_REQUESTED** [review]
Sick Time still changes color after switching to Week View. Also notice that the alignment is off when the date is overlapping. 

image

**Comment by tjamesallen15** [comment]
> Sick Time still changes color after switching to Week View. Also notice that the alignment is off when the date is overlapping.
> 
> image

I can't replicate the Sick Time issue atm. Seems okay on my end
image

However the aligment bug is visible on my end. I will fix on that.

**Comment by ericangeles** [comment]
@infor-design/qa, please re-test.

**Review by n-ace-ancog — DISMISSED** [review]
Working as expected.

image

image

image

image

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Alignment of the created event still looks off.

image

Event colors are now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/b2363700-6b97-4a4f-8647-c14afeffe886

**Comment by tjamesallen15** [comment]
> Still failing on my end.
> 
> * Todays day with event looks off. The calendar date overlaps with the event.
> * Overlapping dates still looks off.
> * After adding a new event, it defaults to color blue instead of the color in the legend.
>   image

Can I get a video for this one?

**Comment by tjamesallen15** [comment]
@janahintal

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi @tjamesallen15 I can still replicate the issue
https://www.loom.com/share/d6c7e610651f4b85b0c2a54c853a3e8b?sid=9f83321d-b4f9-4a57-b9e7-2bd538f52759

**Comment by tjamesallen15** [comment]
Done. please check again ty.
image

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@tjamesallen15 can you use lighter colors in this example https://7826-calendar-custom-colors-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html
Its just that it shows a color contrast issue on the page we shouldnt encourage. 

Just change to colors in the first 3 rows https://main-enterprise.demo.design.infor.com/components/colors/example-index.html (10-30)

**Review by jbrcna — CHANGES_REQUESTED** [review]
opening an event and do nothing but submit changes the event color.
**before**
image

**after**
image

**Comment by tjamesallen15** [comment]
@tmcconechy @ericangeles see the qa findings above.

there are to types of json files here. one with custom-types, one with custom events.

calendar loads the with custom events (following its colors saved)
user click the custom event and press save
reverts back to the color saved from custom types not with the custom-events

my understanding is that it is a special events that's why it have a custom colors preloaded. should we save the colors of the custom colors?

**Comment by tmcconechy** [comment]
@tjamesallen15 I dont think that we should commit the custom colors and change the data. But if they override it on the API it should use the overrride (in all cases).

So might just be checking: if overridden use that ELSE use the data

**Comment by n-ace-ancog** [comment]
@tjamesallen15 @ericangeles @tmcconechy, the color persist after updating it without changing the event type. When changing the event type, the color still remains the same. Is this expected or the color should be tied on the event type?

https://github.com/infor-design/enterprise/assets/156752175/4466cde9-607c-4546-ab80-e1075aa2349d

**Review by jbrcna — CHANGES_REQUESTED** [review]
updating an event does not update its color. 
image
also, the color of the header and title could be improved.

**Comment by tjamesallen15** [comment]
> @tjamesallen15 @ericangeles @tmcconechy, the color persist after updating it without changing the event type. When changing the event type, the color still remains the same. Is this expected or the color should be tied on the event type?
> 
>  Screen.Recording.2024-05-24.at.3.22.27.PM.mov

yes. stated above by tim to always use the overridden.

**Comment by tjamesallen15** [comment]
> updating an event does not update its color. image also, the color of the header and title could be improved.

Hello, that is intended. thanks.

**Review by ericangeles — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Thanks for confirming @tjamesallen15. Working as expected from my side.

https://github.com/infor-design/enterprise/assets/156752175/9c3e82d9-e91f-4bd5-84f0-0086f92aa49c

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
> > updating an event does not update its color. image also, the color of the header and title could be improved.
> 
> Hello, that is intended. thanks.

thanks for clarifying @tjamesallen15

**Pull request merged**
