### PR TITLE
8147 - Datagrid Filter Range

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix rendering issues on filter range when selected by render default.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8147

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-custom-filter-conditions-and-defaults.html
- See that Date column's filter type is In Range
- Open the date picker
- Try selecting date range

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Hello Team, unable to filter a date in '=' filter. I'm trying to filter  = Todays date but it defaults to a range. 

https://www.loom.com/share/ee0d2be04c5943a986ba362e65bf40bb?sid=c5459ac8-297a-4244-8492-a905f05d178b

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/2c9fbbed-5c16-46e5-884c-3afc9b35e110

**Review by jbrcna — DISMISSED** [review]
image

**Comment by ericangeles** [comment]
@tjamesallen15, could you please check the date filter that @janahintal mentioned above?

**Comment by tjamesallen15** [comment]
> Hello Team, unable to filter a date in '=' filter. I'm trying to filter = Todays date but it defaults to a range.
> 
> https://www.loom.com/share/ee0d2be04c5943a986ba362e65bf40bb?sid=c5459ac8-297a-4244-8492-a905f05d178b

May I know what platform is this? I've been trying to reproduce it on my end but to no avail. I'm testing it on via local setup (localhost)

cc @ericangeles

**Comment by janahintal** [comment]
Hi @tjamesallen15, I can still reproduce the issue on my end. I'm using windows 10 Chrome Version 120.0.6099.130(Up to date).

**Comment by janahintal** [comment]
Hi @tjamesallen15, the function is working in local however the icons are misplaced. 
image

**Comment by tjamesallen15** [comment]
> Hi @tjamesallen15, the function is working in local however the icons are misplaced. image

Is this Safari? what browser is this? Thanks.

**Comment by tjamesallen15** [comment]
DDD23A47-4B70-4776-8305-903FFD0A7A10

Not reproducible on my end, tested on Safari, Chrome and Firefox (Mac)

**Comment by tjamesallen15** [comment]
Windows Chrome and Firefox
image

cc @ericangeles

**Comment by ericangeles** [comment]
@janahintal I tested it on windows 10 via browserstack and I don't see the icon alignment issue.

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Comment by janahintal** [comment]
@ericangeles I also tested in browser stack and I'm getting the same alignment issue. 
image

**Comment by ericangeles** [comment]
@janahintal can you create a separate ticket and we’ll take a look just to make sure.

**Comment by ericangeles** [comment]
Did you try to pull the latest updates from that branch?

**Pull request merged**
