### PR TITLE
8635 - Correct Demo App So Fonts Are Served

### LINKED ISSUE #8635: Fonts: Serve Google Fonts From Demo App
**Describe the bug**

Because of GDPR (google has minor tracking information in the font api). And because google URLS are blocked in some countries like China. https://www.cookieyes.com/documentation/google-fonts-and-gdpr/

We need to serve the Source Sans Font locally.

**Tasks**

- update https://github.com/infor-design/design-system/tree/main/font/theme-uplift to the latest font and update guidance on how to use it
- change https://github.com/infor-design/enterprise to use the font 
- update the information in design system and enterprise docs to mention the two ways of doing it and which is reccomended
- add the font also to ids-foundation and update ids-enterprise-wc as well (less critical)
- testing
- Add it in enterprise-ng repo / update NG docs/usage on it

**Expected behavior**

Examples and docs show using the source sans font in the demo app.

### LINKED ISSUE #8671: General: Fix language support in font-face.css and demo app
**Describe the bug**

Need to add all the custom language fonts to the demo app. 

**Tasks**

- [ ] See if approved with legal
- [ ] for each of the font urls open the link in the browser
- [ ] download each file
- [ ] add the file to the font-face.css like the existing ones based on whats in the file (you only need the ones for the language in question)
- [ ] test all locales

**Font urls**

https://fonts.googleapis.com/css?family=Mada:300,400,600&amp;display=swap&amp;subset=hebrew

https://fonts.googleapis.com/css?family=Assistant:300,400,600&amp;display=swap&amp;subset=hebrew

https://fonts.googleapis.com/css?family=Noto+Sans:300,400,700&amp;display=swap&amp;subset=devanagari
        
https://fonts.googleapis.com/css?family=Noto+Sans+JP:300,400,700&amp;display=swap&amp;subset=japanese
        
https://fonts.googleapis.com/css?family=Noto+Sans+KR:300,400,700&amp;display=swap&amp;subset=korean
        
https://fonts.googleapis.com/css?family=Sarabun:300,400,600&amp;display=swap&amp;subset=thai
        
https://fonts.googleapis.com/css?family=Noto+Sans+SC:300,400,700&amp;display=swap&amp;subset=chinese-simplified
       
**Font Matrix**
```
$cultures-font-family: (
  'ar-EG': ('Mada', 'Source Sans Pro', 'arial', sans-serif),
  'ar-SA': ('Mada', 'Source Sans Pro', 'arial', sans-serif),
  'he-IL': ('Assistant', 'Source Sans Pro', 'arial', sans-serif),
  'hi-IN': ('Noto Sans', 'Source Sans Pro', 'arial', sans-serif),
  'ja-JP': ('Noto Sans JP', 'Source Sans Pro', 'arial', sans-serif),
  'ko-KR': ('Noto Sans KR', 'Source Sans Pro', 'arial', sans-serif),
  'th-TH': ('Noto Sans Thai', 'Source Sans Pro', 'arial', sans-serif),
  'zh-CN': ('Noto Sans SC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-TW': ('Noto Sans TC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-Hans': ('Noto Sans SC', 'Source Sans Pro', 'arial', sans-serif),
  'zh-Hant': ('Noto Sans TC', 'Source Sans Pro', 'arial', sans-serif)
);
```

**To Test**

1. go to https://main-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=zh-TW changing the url as above in the matrix
2. inspect the text and look on the rendered fonts tab that the correct one loaded

Screenshot 2024-05-02 at 1 20 12 PM

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Because of GDPR and banned googleapis in china, we changed all the docs and sample app to use a self hosted font instead of the google api URL.

**Related github/jira issue (required)**:
Fixes #8635
Fixes #8671

NOTE: Do not merge until told as we are checking some things with compliance team

**Steps necessary to review your pull request (required)**:

- make sure to do `npm run start` again on this branch
- test kitchen sink page http://localhost:4000/ 
- compare to https://main-enterprise.demo.design.infor.com/
- should be no changes to font
- go to http://localhost:4000/components/locale/test-translations.html?locale=zh-Hant
- and change locale as per https://github.com/infor-design/enterprise/pull/8676/files#diff-7b212a43457da2316b470408aa34ec118787d2049001c33542bad92f4dfdad8eR11-R17 and in each case there should be no errors in the console and that font should display (you can inspect text to check)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — DISMISSED** [review]
This is now working as expected.

image

image


**_Before fix:_**
image

**_After fix:_**
image

**Review by janahintal — DISMISSED** [review]
https://www.loom.com/share/4dc4efcad2bf4493afcac421bce60ae8?sid=ac09ce23-7412-4ab5-97d6-e34c6e2ff63c

**Comment by n-ace-ancog** [comment]
Seems like the current branch has bigger fonts than with main. They are both in 100% zoom.

http://localhost:4000/components/locale/test-translations.html?locale=zh-Hant

https://github.com/infor-design/enterprise/assets/156752175/a5c2426f-33d1-47a7-98d0-699b526f2dc3

**Comment by tmcconechy** [comment]
@n-ace-ancog yes, there is a difference i should have mentioned with the language fonts. They were not working before so it was using a different font now.

**Review by ericangeles — DISMISSED** [review]

**Pull request merged**
