### PR TITLE
Chore: Try to fix builds build changing sass to node-sass

### LINKED ISSUE #8548: Chore: Change Node Sass to
**Describe the bug**

In order to get off node 18 to node 20 we need to move out the node-sass dependency and replace our sass usage to this package: https://github.com/infor-design/enterprise-wc/blob/main/package.json#L90

**To Reproduce**

1. Update `.nvmrc` to the latest LTS node package https://nodejs.org/en/download
2. `npm i`
3. See error

**Expected behavior**
Replace node-sass and any sub plugins with `sass` and fix any compilation issues.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

All builds are doing this: https://github.com/infor-design/enterprise/actions/runs/8803214086/job/24160775124?pr=8632#step:6:20
Trying to fix the build error by updating and releasing caches. By installing sass instead of node-sass.

**Things to Test**

1. Where i changes these `calcs` in here did it break anything?
2. Does removing node-once importer break anything (need to test custom builds i think worst case may have duplicate css in it which we can maybe just ignore for now)

**For QA**

- review the effected components in https://github.com/infor-design/enterprise/pull/8642/files and test those pages
- smoke test kitchen sink page

Fixes #8548

### CODE REVIEW

**Comment by ericangeles** [comment]
@tmcconechy, I've double-checked the CSS where we made changes and noticed some issues. I've pushed the correct ones now.

**Comment by ericangeles** [comment]
Tested the `calc` and it works.

**Comment by ericangeles** [comment]
I think we're good in here, Tim.

**Comment by tmcconechy** [comment]
Lets get QA to have a quick look too

**Review by ericangeles — APPROVED** [review]

**Comment by n-ace-ancog** [comment]
@tmcconechy  @ericangeles I'm encountering this error when starting the local server

image

**Comment by ericangeles** [comment]
Reinstall the package. Delete the node_modules folder and install it again. 

If you’re on mac run: rm -rf node_modules && npm i.  (Its just the same as deleting the node modules folder and installing the package.

**Review by n-ace-ancog — APPROVED** [review]
Tried deleting the node_modules folder and doing `npm install`, but encountered the same problem. What fixed it was to re-clone the repository locally.

Working as expected.

http://localhost:4000/components/completion-chart/example-index.html
image

http://localhost:4000/components/editor/example-index.html
image

http://localhost:4000/components/images/example-index.html
image

http://localhost:4000/components/monthview/example-index.html
image

http://localhost:4000/components/processindicator/example-index.html
image

http://localhost:4000/components/switch/example-index.html
image

http://localhost:4000/components/timepicker/example-index.html
image

http://localhost:4000/components/typography/example-index.html
image

http://localhost:4000/components/wizard/example-index.html
image

**Sink page**
image

image

image

**Review by jbrcna — APPROVED** [review]
aprub!

**Pull request merged**
