### PR TITLE
1609 - Fix popover and clean examples

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed a bug where some contents where no longer rendered in popover (regression).

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-ng/issues/1609

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/popover/example-extra-css-class.html and click the button, should again see contents
- same for http://localhost:4000/components/popover/test-content-string.html
- briefly smoke test http://localhost:4000/components/popover (dont need to dig deep)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — DISMISSED** [review]

**Comment by ericangeles** [comment]
@tmcconechy, we may wanna remove the test here since the example page that is related to the test is now removed. https://github.com/infor-design/enterprise/actions/runs/7587306522/job/20667349597?pr=8355#step:9:257

**Comment by ericangeles** [comment]
Or just update the url from `example-using-max-width-setting` to `test-using-max-width-setting`.

**Comment by tmcconechy** [comment]
@ericangeles all fixes

**Review by ericangeles — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Bug has been fixed. However, the text and close button overlap in Classic.

https://github.com/infor-design/enterprise/assets/102151352/8ce1ba59-f2f8-45e6-a021-bf5b18a9d3d3


https://github.com/infor-design/enterprise/assets/102151352/09d15a6d-8587-495a-8c8e-9dc137b49625

http://localhost:4000/components/popover/test-content-string.html

image

image

**Review by janahintal — CHANGES_REQUESTED** [review]
Failing on responsive view 
https://1609-popover-enterprise.demo.design.infor.com/components/popover/test-content-string.html?theme=new&mode=light&colors=default
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
this is working as expected.
image
image
image

However, the x icon was mislaligned in classic
image

**Comment by tmcconechy** [comment]
@janahintal @jbrcna @glenlieorillo 

1. Fixed the X issue (by shortening the text in the example as its not important)
2. For the mobile/responsive issue this already worked this way and this example is not that mobile friendly so not sure what we can do. I think we can leave this, definitely for now. If you think it should be addressed would be a bigger issue for popups on mobile devises so could make a new issue for later? But i think maybe we ignore it

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
image
image
image
image
image

image

**Review by jbrcna — APPROVED** [review]
image

image

**Pull request merged**
