### PR TITLE
3090 - Fix bug with addEvents [v4.23.x]

### LINKED ISSUE #3090: Calendar: Add Event API Errors
**Describe the bug**
Latest fixes broke addEvent in a couple of ways.

**To Reproduce**
1. Go to http://localhost:4000/components/calendar/example-index.html
2. in the console run
```
$('.calendar').data('calendar').addEvent({
      id: '6',
      subject: 'Discretionary Time Off',
      shortSubject: 'DTO',
      comments: 'Personal time',
      location: 'Canada Office',
      status: 'Approved',
      starts: '2018-08-24T10:00:00.999',
      ends: '2018-08-24T14:00:00.999',
      type: 'dto',
      isAllDay: false
    })
```
3. See error
4. now reload this page and run 
```
$('.calendar').data('calendar').addEvent({
      id: '1',
      subject: 'Test Event One',
      status: 'pending',
      starts: '2019-12-02T15:00:00.000',
      ends: '2019-12-02T16:00:00.000',
      type: 'dto',
      isAllDay: 'false'
    })
```
5. this works but adds the date on todays date instead

**Expected behavior**
No errors/problems

**Version**

- ids-enterprise: [e.g. v4.23.0-b]

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed a problem with the add API where it gave errors or added to the wrong date.

**Related github/jira issue (required)**:
Fixes #3090 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/calendar/example-index.html
- in the console type
```
$('.calendar').data('calendar').addEvent({
      subject: 'Test Event One',
      status: 'Pending',
      starts: '2019-12-02T15:00:00.000',
      ends: '2019-12-02T16:00:00.000',
      type: 'dto',
      isAllDay: 'false'
    })
```
- go to december and you should see this new date
- type
```
$('.calendar').data('calendar').addEvent({
      subject: 'Discretionary Time Off',
      shortSubject: 'DTO',
      comments: 'Personal time',
      location: 'Canada Office',
      status: 'Approved',
      starts: '2018-08-21T10:00:00.999',
      ends: '2018-08-21T14:00:00.999',
      type: 'dto',
      isAllDay: false
    })
```
- go to August 2018
- should say a DTO added on the 21st

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.

### CODE REVIEW

**Comment by deep7102** [comment]
Looks added event having wrong info
http://localhost:4000/components/calendar/example-index.html

```
$('.calendar').data('calendar').addEvent({
      id: '1',
      subject: 'Test Event One',
      status: 'pending',
      starts: '2019-12-02T15:00:00.000',
      ends: '2019-12-02T16:00:00.000',
      type: 'dto',
      isAllDay: 'false'
    });
```
- Go to December and you should see this new event `Test Event One` on 12/02/2019
- Click on that event 
- See wrong info in popup window and side bar event info window

**Comment by EdwardCoyle** [comment]
I'm seeing the same thing @deep7102 reported too, didn't see it before

**Comment by tmcconechy** [comment]
@EdwardCoyle @deep7102 My mistake. That command will only work when you have no data at all. There is already an event with ID: 1 so its merging data with that. Better to run with no id and it will make a unique one. 

```
$('.calendar').data('calendar').addEvent({
      subject: 'Test Event One',
      starts: '2019-12-02T15:00:00.000',
      ends: '2019-12-02T16:00:00.000',
      type: 'dto',
      isAllDay: 'false'
    });
```

or id: 'someunique'

**Comment by tmcconechy** [comment]
Updated the commands.

**Pull request merged**
