### PR TITLE
7530 - Datagrid Default Operator For Lookup

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug in datagrid where default operator for lookup is not rendered properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7530

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-filter-with-default-operator.html
- See the Default Operator for the `Product Id`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
@claudenbach how does this look for you?

**Comment by claudenbach** [comment]
Seems correct for a lookup is that is an alpha type, but what about a lookup that is a numeric type?  The operators are different for a numeric vs alpha field type.

**Comment by tmcconechy** [comment]
@claudenbach i dont think we have had this before tho. Its always treated as a string. Although we "could" check it..

**Comment by claudenbach** [comment]
We do have examples were the column with a lookup is a numeric.  In these cases, we would be using the numeric operators (or filter conditions). For example a column containing a manufacturer number, product number, or employee number.

**Comment by tmcconechy** [comment]
and that already works ? ok @tjamesallen15 do you know what to do to fix?

**Comment by claudenbach** [comment]
Yes, that currently works.

**Comment by claudenbach** [comment]
Here's an example...

Git-7530-Example

**Comment by tjamesallen15** [comment]
Try checking my latest push

**Comment by tmcconechy** [comment]
@claudenbach how does it looks now?

**Comment by claudenbach** [comment]
Looks good.  Thanks!

**Pull request merged**
