### PR TITLE
6253 - Follow up for Validation

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug where toolbar error message still appears after error is removed.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6253

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

Scenario 1:
- Go to http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html
- Click `Show Error` (Should show the message)
- Click `Hide Error` (Show hide the message)

Scenario 2:
- Go to http://localhost:4000/components/toolbar/test-error-on-toolbar-with-button.html
- Click `Show Error` (Should show the error/required on the field)
- Click `Hide Error` (Should show the error/required on the field)

Scenario 3:
- go to http://localhost:4000/components/datagrid/test-editable-paging-validation.html
- edit a cell and make it blank
- go to page 2 -> error should show on the toolbar

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@s-werking can you have a look?

**Comment by s-werking** [comment]
I think we may be getting farther away from the original issue. With the original html sample that I provided, the issue was that the error message on the toolbar would still be visible after selecting the "Hide Error" button. Now when I try to test on the original html file, the Special Actions button no longer receives any error message. Here's some steps I'm using to test if this better clarifies what solution I'm looking for:
1. Use this zipped html file:
[test-error-on-toolbar-with-addmessage.2.zip](https://github.com/infor-design/enterprise/files/8787896/test-error-on-toolbar-with-addmessage.2.zip)
2. Click on the "Show Error" button
Expected Result: The Special Actions button on the toolbar should have an error message and the text should turn red. The toolbar should not have an error icon (there was an error icon on the toolbar in the ticket's gif)

3. Click on the "Hide Error" button
Expected Result: The Special Actions button on the toolbar should not have an error message and should no longer have red text.

**Comment by tjamesallen15** [comment]
> I think we may be getting farther away from the original issue. With the original html sample that I provided, the issue was that the error message on the toolbar would still be visible after selecting the "Hide Error" button. Now when I try to test on the original html file, the Special Actions button no longer receives any error message. Here's some steps I'm using to test if this better clarifies what solution I'm looking for:
> 
> 1. Use this zipped html file:
>    [test-error-on-toolbar-with-addmessage.2.zip](https://github.com/infor-design/enterprise/files/8787896/test-error-on-toolbar-with-addmessage.2.zip)
> 2. Click on the "Show Error" button
>    Expected Result: The Special Actions button on the toolbar should have an error message and the text should turn red. The toolbar should not have an error icon (there was an error icon on the toolbar in the ticket's gif)
> 3. Click on the "Hide Error" button
>    Expected Result: The Special Actions button on the toolbar should not have an error message and should no longer have red text.

Can try this one again.

**Comment by yohannahbautista** [comment]
Hello, the error pops up when you do this:
http://localhost:4000/components/toolbar/test-error-on-toolbar-with-addmessage.html
1. Show Error
2. Hide Error
3. Select an option in Special Actions dropdown
Screen Shot 2022-05-30 at 3 06 48 PM

**Review by yohannahbautista — APPROVED** [review]

**Review by ericangeles — DISMISSED** [review]

**Comment by ericangeles** [comment]
Can you take a look again, @s-werking ?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Will hold this with request changes for now.

1. I agree with @s-werking -> do we need that new flag isValidatedError? If so maybe we can add it automatically somehow by checking either the target or that it was called with addMessage
2. Also did it show an error icon before? I.E. should the icon be visible at the end (could cause overflow issues tho)

**Comment by tmcconechy** [comment]
@tjamesallen15 would like to finalize this one for beta tomorrow. Can you take a look. If not we can patch it in later but this would be prefered.

Thanks!

**Comment by tjamesallen15** [comment]
> @tjamesallen15 would like to finalize this one for beta tomorrow. Can you take a look. If not we can patch it in later but this would be prefered.
> 
> Thanks!

will do!

**Review by ericangeles — APPROVED** [review]

**Comment by s-werking** [comment]
Looks good to me, thank you @tjamesallen15!

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
