### PR TITLE
6207 - Tabs Module: X Button Not Centered, Search Icon Filled In

### LINKED ISSUE #6207: Tabs Module: 'x' button is not centered in new version
**Describe the bug**
Tabs Module: 'x' button is not centered in new version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
2. Type in the search field 
3. Click Tab to focus in 'x' button

**Expected behavior**
Blue circle / focus should be centered

**Version**
4.62-ids-dev

**Screenshots**
image

**Platform**
Windows Chrome 10 & other major browsers & OS

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed extraneous declarations that prohibitted the close icon from aligned in a centered manner. Matched the height and width to that of the svg or any previous min-height declaration.

Search icon has a fill added by an injected `<style id="soho-personalization">` script. Added an extremely specific rule local to `enterprise` to override this injection.

**Related github/jira issue (required)**:

Resolves #6207 

**Steps necessary to review your pull request (required)**:

- Pull Build Run
- Visit http://localhost:4000/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
- Notice search icon is no longer filled in, notice close icon is aligned properly
- check other pages on http://localhost:4000/components/personalize and example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4 to  make sure nothing is broke

NOTE: I did notice the search icon is off in alignment outside of module tabs but I believe there is a ticket for this already?

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Looks good - cant find anything in http://localhost:4000/components/personalize
Also not sure about the alignment thing i didnt notice but if u want to fix that as well do feel free.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Sorry i checked some more. These pages look really bad:

http://localhost:4000/components/tabs-module/example-category-searchfield.html
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

Can you check if this fix caused it or not? Didnt have time. And if there is a related fix it would be nice to include it.

They are BTW supposed to be white there https://github.com/infor-design/enterprise/pull/6234 its just alignment stuff

**Comment by davidcarlsonberg** [comment]
This fix did not break those but I can add a fix for them in this PR.

**Comment by tmcconechy** [comment]
Yeah i think please take a look @davidcarlsonberg seems important

**Comment by tmcconechy** [comment]
@davidcarlsonberg not sure if this is done but i see some tests failing. So just remove the WIP when its ready. Thanks!

**Comment by davidcarlsonberg** [comment]
Yup, may need to update some images.

**Comment by tmcconechy** [comment]
Sorry these are a bit out of scope but seeing some issues on http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

- the left button, field and go button dont all line up
- hovering the category button makes it disappear

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
