### PR TITLE
Fix disabled color

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
The disabled color on buttons was changed to look more disabled. We missed this in the process. Also the button changes effected the datagrid filter row

**Related github/jira issue (required)**:
Fixes #7024 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/button/example-index.html
- look at the disabled buttons - style changed a bit
- go to http://localhost:4000/components/datagrid/example-filter
- click the filter buttons

### CODE REVIEW

**Comment by tmcconechy** [comment]
Can someone update snapshots for me if i dont get to it soon?

**Comment by tmcconechy** [comment]
can you try that again @ericangeles i can seem to get my vm to work

**Review by ericangeles — DISMISSED** [review]

**Review by deep7102 — CHANGES_REQUESTED** [review]
Looks good on light theme, but need to update on dark and contrast theme.
image
image

**Review by deep7102 — APPROVED** [review]
Thanks! looks good 🍌

**Review by EdwardCoyle — APPROVED** [review]
Looks good

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
