### PR TITLE
6876 - Revert OptionalDependencies and use a command

### LINKED ISSUE #6876: ids-enterprise declares a lot of dependencies since 4.67
**Describe the bug**
While scanning for vulnurable and non-compliant (license) packages, we found that `ids-enterprise` declares a lot of dependencies since version 4.67.

**To Reproduce**

Output from `npm info ids-enterprise@4.66`:
```
ids-enterprise@4.66.0 | Apache-2.0 | deps: 5 | versions: 865
Infor Design System (IDS) Enterprise Components for the web
https://github.com/infor-design/enterprise

[...]

dependencies:
d3: ^5.16.0              fsevents: *              ids-identity: 4.11.11    jquery: ^3.6.0           promise-polyfill: ^8.2.3 

[...]
```

Output from `npm info ids-enterprise@4.67`:
```
ids-enterprise@4.67.0 | Apache-2.0 | deps: 52 | versions: 865
Infor Design System (IDS) Enterprise Components for the web
https://github.com/infor-design/enterprise

[...]
dependencies:
@wordpress/jest-puppeteer-axe: ^3.1.0 check-node-version: ^4.2.1            eslint-plugin-jasmine-jquery: ^1.0.0  highlight.js: ^11.5.1                 
archiver: ^5.3.1                      d3: ^5.16.0                           eslint-plugin-jasmine: ^4.1.2         html-loader: ^1.1.0                   
axe-core: ^4.3.3                      eslint-config-airbnb-base: ^14.2.1    eslint: ^7.32.0                       ids-css: ^1.5.0                       
axe-webdriverjs: ^2.3.0               eslint-plugin-babel: ^5.3.1           front-matter: ^4.0.2                  ids-identity: 4.11.11                 
babel-eslint: ^10.1.0                 eslint-plugin-compat: 3.13.0          fsevents: *                           jquery: ^3.6.0                        
browserstack-local: ^1.5.1            eslint-plugin-import: ^2.24.2         handlebars: ^4.7.7                    promise-polyfill: ^8.2.3              
(...and 28 more.)

[...]

```

**Additional context**
https://jira.infor.com/browse/LIME-8572

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
The fix to use optional dependencies caused errors with security and extra dependencies to be installed when released as a lib.

To fix this, i reverted this change. Then i made a custom command `npm run install-demo`.

@corpulent willl need to review this and update the images? To use the new command, if not they will get larger again.
 
WIP but please review - dont want to merge until @corpulent has checked this out.

@ericangeles this will effect https://github.com/infor-design/enterprise/pull/6731 as you need to merge this and also make updates in both files...

**Related github/jira issue (required)**:
Fixes #6876

**Steps necessary to review your pull request (required)**:
- check size of node_modules
- `rm -rf node_modules`
- run `npm run install-demo` 
- check size of node_modules (will be smaller)
- `npm run build` still works `npm run start` still works.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by danielortiz1982 — DISMISSED** [review]

**Comment by ericangeles** [comment]
Quick question @tmcconechy, does the `npm run install-demo` will now be part of the setup?

**Comment by ericangeles** [comment]
`npm run build` and `npm start` is not working on my end after running `npm run install-demo`.

**Comment by tmcconechy** [comment]
thanks @ericangeles  i messed up this should now work
```
rm -rf node_modules
npm run demo-install
npm run build
npm run start
```

This command is only going to be used by @corpulent to set up the sites in the deploys like: https://main-enterprise.demo.design.infor.com and https://4680-beta0-enterprise.demo.design.infor.com/ ect. So not really part of what you would typically use. But if you had a case where you only need to build and start the site you could use it. But you wouldnt be able to run tests and lint and stuff. The main idea is to reduce the size of these images so they only have what they need to run the site.

**Review by danielortiz1982 — APPROVED** [review]
This looks good to me, however I will defer to @corpulent for the final approval.

**Review by corpulent — APPROVED** [review]
looks good

**Pull request merged**
