### PR TITLE
3531 - Rearrange resize widgets

### LINKED ISSUE #3531: Homepage: Allow widgets to be resized and rearranged.
**Is your feature request related to a problem? Please describe.**
Widgets don't have the ability to be resized or rearranged by the user.

**Describe the solution you'd like**
Widgets should be able to be resized and rearranged by the user.

**Describe alternatives you've considered**

**Additional context**

Ming.le Homepages which has this ability:
image

### PR DESCRIPTION
**Pull request by crlang44**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Homepage does not have the ability to let the user rearrange, resize, or delete widgets.

**Related github/jira issue (required)**:

Closes #3531

**Steps necessary to review your pull request (required)**:

Go to the following page:
http://localhost:4000/components/homepage/example-editable.html

Toggle the editing mode by clicking the button.
Resize a widget.
Drag a widget to reorder it.
Make sure the widget with no-remove class does not have a delete button in edit mode.
Delete a widget.
Check the console.log for the triggered events for each action.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
1. Can you update the PR description with test steps and more info. 
2. Also see some lint errors https://travis-ci.com/infor-design/enterprise/jobs/295182585#L422
3. I wasnt able to edit the http://localhost:4000/components/homepage/example-index.html like before? Do we need a http://localhost:4000/components/homepage/example-editable.html example added with it turned on so you can test this easily?

Wasnt able to test because of that yet

**Comment by crlang44** [comment]
Still adding delete functionality..

**Comment by ericangeles** [comment]
@crlang44 is this ready to review?

**Comment by tmcconechy** [comment]
I was told by @crlang44 on ms teams this is ready.

**Comment by crlang44** [comment]
It's ready for review

**Comment by tmcconechy** [comment]
I'd approve this to further advance to QA. There are some complications on different layouts i think (all different size widgets). So needs more testing. The only two initial comments i have (other than looks good).

- maybe we can put that toggle button to be a toggle in the toolbar more like http://localhost:4000/components/form/example-compact-mode.html
- it would be nice if when you move the widgets they move immediately and not move back and then again into position.

**Comment by crlang44** [comment]
> I'd approve this to further advance to QA. There are some complications on different layouts i think (all different size widgets). So needs more testing. The only two initial comments i have (other than looks good).
> 
> * maybe we can put that toggle button to be a toggle in the toolbar more like http://localhost:4000/components/form/example-compact-mode.html
> * it would be nice if when you move the widgets they move immediately and not move back and then again into position.

What page are you seeing this on? With animations turned off for the reorder it should just drop in place, but it sounds like what you're seeing is what happened when I still had it do animation.

**Comment by tmcconechy** [comment]
Just on http://localhost:4000/components/homepage/example-editable.html  just move the first widget over to the second and you can see it move back and then go there

Video:
https://drive.google.com/file/d/1XzNuzREVt5-LSlfNMhH5A513n5pXwlfj/view

**Comment by crlang44** [comment]
I'm not able to reproduce that issue in Chrome but I do see that I need to add touch support so maybe that is related.

**Comment by crlang44** [comment]
Ok, I'm not able to add mobile support at this time. We can continue with the code as it is here.

**Comment by crlang44** [comment]
This is what I see compared to Tim's recording above.
homepage-widget-drag

**Comment by crlang44** [comment]
homepage-widget-drag-2

**Comment by deep7102** [comment]
Yes! I see the same as @tmcconechy move the first widget over to the second and see it move back and then go there.
I think it happens because it fire the change to set new position after you drop the dragged widget and NOT while dragging.

**Comment by EdwardCoyle** [comment]
@crlang44 this is fantastic work!  Thanks so much for the contribution!

**Pull request merged**
