### PR TITLE
8101 8102 - Searchfield with categories/dropdown border and height in RTL

### LINKED ISSUE #8101: Searchfield: Border looks off in RTL
**Describe the bug**
Searchfield border looks off in RTL.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-short.html?locale=ar-SA
https://main-enterprise.demo.design.infor.com/components/searchfield/example-update.html?locale=ar-SA
2. Notice the searchfield
3. Also, the text is not properly aligned

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

image

**Platform**
 - All major browsers

**Additional context**

### LINKED ISSUE #8102: Searchfield: Dropdown border looks off in RTL
**Describe the bug**
Dropdown border looks off in RTL.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-full?locale=ar-SA
2. Notice the dropdown menu, it should be way around.

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - All major browsers

**Additional context**

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Made the adjustments to searchfield with categories and dropdown in RTL mode

**Related github/jira issue (required)**:
Closes #8101 
Closes #8102 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/searchfield/example-categories-short.html?locale=ar-SA
- see the input is the same height as the categories
- go to http://localhost:4000/components/searchfield/example-update.html?locale=ar-SA
- see the input is the same height as the categories and the placeholder is aligned
- go to http://localhost:4000/components/header/example-searchfield-full?locale=ar-SA
- see that the dropdown menu is correctly aligned

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by yohannahbautista — COMMENTED** [review]
Not sure if it should be in this ticket, but hover and focus border looks to only be on the horizontal lines

**Comment by ericangeles** [comment]
@yohannahbautista yeah, that's a bit off. Can you fix that as well, @andrivarhanov ?

**Review by yohannahbautista — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@andrivarhanov i see a small issue with the border color and radius

Screenshot 2023-12-04 at 12 28 31 PM

- when you click the button you see the border changes (should stay the same wether it is focused or not and match the rest of the field)
- the border radius on both sides is different (should be like the right side http://localhost:4000/components/input/example-index.html)

**Comment by jbrcna** [comment]
image
image
image
image
image

**Review by tmcconechy — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
