### PR TITLE
8946 - Fix uncaught error when destroying toolbar

### LINKED ISSUE #8946: Toolbar: Console error when clicking a button that destroys the toolbar
**Describe the bug**
We are seeing a console error often in CSD when a click action on a toolbar button results in the toolbar being destroyed. The use case is that a toolbar button performs navigation in the app which destroys the old screen/toolbar in order to render a new screen.

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/toolbar/test-destroy-and-remove.html
2. Click on any button in the toolbar
3. See error in the console

TypeError: Cannot read properties of undefined (reading '0')
    at Toolbar.setActiveButton (toolbar.js:1141:46)
    at Toolbar.handleClick (toolbar.js:821:10)
    at HTMLButtonElement.<anonymous> (toolbar.js:628:14)
    at HTMLButtonElement.dispatch (jquery-3.7.1.js:5145:27)
    at elemData.handle (jquery-3.7.1.js:4949:28)

**Expected behavior**
There should be no console error when destroying a toolbar via a button click.

In order to fix this, you could add logic in the "handleClick" function which checks if the toolbar has been destroyed, and if so then don't proceed with any of the handleClick logic.

**Code**
handleClick: function handleClick(e) {
  // Ignore the handleClick logic if the toolbar is already destroyed
  if (!this.items) {
    return false;
  }

**Version**

- ids-enterprise: v4.98.0

**Platform**
 - Infor Application/Team Name: CSD
 - Device: Dell laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 127.0.6533.89 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes uncaught error when destroying toolbar. Added a guard clause to prevent any uncaught error in `handleClick` event.

**Related github/jira issue (required)**:

Closes #8946

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbar/test-destroy-and-remove.html
- Click the `Close` button to destroy the toolbar
- Toolbar should be removed
- There should be no uncaught error in the console tab

**Included in this Pull Request**:
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles seems like some tests are failing i did fix some things recently so maybe try pulling main too if its not an actual error in the test?

**Comment by ericangeles** [comment]
My branch is outdated. That should do it! 💪🏼

**Review by jbrcna — DISMISSED** [review]
image

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/314b7d94-9a8f-41ec-bd58-7c47d32c1038

**Pull request merged**
