### PR TITLE
8305 - RTL Dropdown Select

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix misaligned dropdown trigger in RTL.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8305

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/multiselect/example-index.html?locale=ar-SA
- Scroll down to Multiselect
- Click the dropdown menu

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jbrcna** [comment]
image
image
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
x icon is cut off in classic
image

when using firefox x icon was misaligned in classic
image

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving. Thanks! 
image

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**Classic RTL**

- x is cut-off
- comma (,) is inverted

image

**Comment by tjamesallen15** [comment]
> **Classic RTL**
> 
> * x is cut-off
> * comma (,) is inverted
> 
> image

X cut off is now fixed, but not sure with the comma is intended, if it is bug, please file another one for it. thank you! :)

**Comment by glenlieorillo** [comment]
> > **Classic RTL**
> > 
> > * x is cut-off
> > * comma (,) is inverted
> > 
> > image
> 
> X cut off is now fixed, but not sure with the comma is intended, if it is bug, please file another one for it. thank you! :)

Thanks, @tjamesallen15! Will file another issue for the inverted comma.

**Comment by glenlieorillo** [comment]
@tjamesallen15, I already figured it out. I used Google to translate the English words into Arabic. As you can see in the screenshot below it is as expected.

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The bug has been fixed in Mac Chrome. However, a bug still exists in Mac Firefox. See screenshot below:

- Misaligned x button under `Multiselect (with Tags)`

**Mac Firefox**
image

**Mac Chrome**
image

image

**Comment by jbrcna** [comment]
misaligned x icon is now fixed. 
image

just slightly cut off
image

**Review by janahintal — DISMISSED** [review]
Looks okay on Chrome and on mobile view. Approving. Thanks!
image
image

**Review by glenlieorillo — COMMENTED** [review]
**Mac Firefox**
- x icon is slightly cut-off.

image

**Mac Chrome**
- Slightly cut-off and alignment is a bit off.

image

**Comment by kyfloresca** [comment]
hi, could you please check this scenario? happens both in RTL and LTR on zoom. thanks! 

https://github.com/infor-design/enterprise/assets/116287798/e8aad390-ed31-4237-ac6b-96b5902275b4

**Comment by tjamesallen15** [comment]
> hi, could you please check this scenario? happens both in RTL and LTR on zoom. thanks!
> 
>  ids-dropdown-rtl-issue.small.mp4

Try to check it later when this build is finished

**Review by janahintal — CHANGES_REQUESTED** [review]
Multiselect (with Tags) Scroll bar is a little cut off on a google chrome smaller screen. 
image
Same goes for the mobile view, Multiselect (with Tags) Scroll bar is a little off compared to Multiselect (Standard) 
image

**Comment by jbrcna** [comment]
working as expected.
image
image

However, the zoom issue still exists
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
x icon alignment is off in LTR.

Mac Chrome - New Version

image

**Review by janahintal — APPROVED** [review]
image
image
image
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
