### PR TITLE
5065 - New Calendar Designs For Selected, Current, Focus and Hover

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add new design for selected, hover, focused and current day in Calendar Monthview, Week View and Day View.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5065

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/example-index.html
- Notice that the current day will be enclosed by blue circle
- Try clicking one of the days to changed the selected day
- Use arrow keys to transfer focus from one day to another
- Do this also in week-view and day-view

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks good the only style issue is that the today date looks like it still has the blue state on it. I would think it should look like this.

Screenshot 2024-01-23 at 10 24 59 AM

Also the focus state doesnt seem to work. If i tab to the calendar i never get into the calendar. I see you added a lot of code for `focusDay` but i think it might be unneeded. All we maybe need to do is set tabindex="0" on one day that has the focus and then tabindex="-1" on the rest then adjust this each time we use the arrow keys to move around.

This already worked before on https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html but the focus state was not really shown. If you just style that and leave the focus code as before i think it should work.

**Review by tmcconechy — DISMISSED** [review]

**Comment by ericangeles** [comment]
FYI @infor-design/qa

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Blue circle looks off in Day View.

image


https://github.com/infor-design/enterprise/assets/102151352/685f1eda-ade2-417e-960b-1933cd1f645b

**Review by janahintal — CHANGES_REQUESTED** [review]
Current date looks off on the ff: 
https://5065-calendar-week-and-day-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=classic&mode=dark&colors=default
image

**Comment by tmcconechy** [comment]
@janahintal @jbrcna @tjamesallen15 @glenlieorillo 

I think i fixed all the issues. Please QA this as part of the beta and if any additional issues are found do raise a new issue.
Thanks!

**Comment by tmcconechy** [comment]
@jbrcna try https://4921-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html (or main)
I had named the branches wrong and this is definitely the latest, and it works there.

**Comment by jbrcna** [comment]
this is what I see on my end @tmcconechy . calendar icon position is not centered.
**firefox**
image

**Comment by tmcconechy** [comment]
@jbrcna it works better on my end https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=classic&mode=light&colors=default
Screenshot 2024-01-29 at 9 25 43 AM

**Comment by jbrcna** [comment]
works on my end as well. @tmcconechy . thanks!
image

**Pull request merged**
