### PR TITLE
5846/6044 - Fix on fileupload icon alignment

### LINKED ISSUE #6044: Datagrid: Icons are not aligned in file upload column
**Describe the bug**
Datagrid: Icons are not aligned in file upload column

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-fileupload.html
2. Upload a file

**Expected behavior**
Icons should be aligned

**Version**
4.60-ids-dev

**Screenshots**
image

**Platform**
All major browser, OS and devices. 

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Edited css to align file upload buttons in datagrid correctly

**Related github/jira issue (required)**:

Related to #5846 
Closes #6044 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-editable-fileupload.html
- Upload a file
- Icons should be aligned

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I tested this in all 4 row Heights and it seems off

- extra small - folder icon is off screen
- small - folder icon is almost off screen
- med - icons not centered folder icon a bit off and a bit close to the x
- large - the text and the icons are not centered in the cell

Screen Shot 2022-01-21 at 9 33 13 AM

**Comment by tmcconechy** [comment]
Im still seeing it not aligned in all 4 row heights and if you click the cell it shuffles around a lot

**Comment by yohannahbautista** [comment]
> Im still seeing it not aligned in all 4 row heights and if you click the cell it shuffles around a lot https://watch.screencastify.com/v/5cEGaB8cEcMC6WcJ2YCk
@tmcconechy What browser is this in? The icons are only slightly down when the filename is too long, but I haven't gotten the one in the video
Screen Shot 2022-01-31 at 8 49 15 AM

**Review by tmcconechy — DISMISSED** [review]
@yohannahbautista im just seeing them a bit down in Large row height now. So i think you must have fixed it. If you can adjust that a bit that would be great but this seems close enough to approve now.

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
