### PR TITLE
7464 - dropdown mouseenter and keydown selection issue

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug in dropdown where mouseenter and keydown triggers simulatenously.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7464

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/dropdown/example-index.html
- Click on the dropdown
- Move the mouse cursor over an option, e.g. `California`
- Use the up and down arrow keys.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
I still see some inconsistencies when trying to hover on other states. 

Try hovering on Oregon, then use up arrow. It expected to shift to Oklahoma but it jumps to Texas.

**Review by ericangeles — APPROVED** [review]
Nice fix! 🍌

**Review by EdwardCoyle — DISMISSED** [review]

**Comment by janahintal** [comment]
Approved. Working as expected https://app.screencast.com/VlksCkefqr5n5

**Review by janahintal — DISMISSED** [review]

**Comment by jbrcna** [comment]
issue still exist when using up arrow key. 
Steps
1. Click on the dropdown
2. Move the mouse cursor over an option, i.e., California
3. Ensure that the list item "California" is the last item on top
4. Use the up  arrow keys.
5. See error
6. it jumps two level (instead of Arkansas)
7. Note that when using down arrow key (Hawaii last item on bottom) it was working as expected.


Large GIF (638x438)

**Review by tmcconechy — DISMISSED** [review]

**Pull request merged**
