### PR TITLE
4352 - Fix range highlight with datepicker

### LINKED ISSUE #4352: Datepicker: date highlights issue in mobile view
**Describe the bug**
The selected date highlight is a bit off

**To Reproduce**
1. Go to https://4290-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Click on datepicker and select date range
in this case `Range - select forward ` (Sep 7 - Sep 11)
3. See error

**Expected behavior**
it should look something like this
image

**Version**
- ids-enterprise: [v4.32.0-beta0]

**Screenshots**
image

**Platform**
Major browsers (Safari, EDGE Chrome)

**Additional context**

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed range highlight was not aligning for Mac/Safari with Datepicker.

**Related github/jira issue (required)**:
Closes #4352

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Use Mac/Safari
- Navigate to: http://localhost:4000/components/datepicker/example-range.html
- Use safari device toolbar (iPhone 8 Plus)
- Open any range picker and check for highlight should not misalign

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by jmacaluso711 — CHANGES_REQUESTED** [review]
@deep7102 I'm seeing a minor mis-alignment issue still when I look in the xcode iphone 8 plus simulator. Looks like just the focus state on the date

Screen Shot 2020-09-28 at 4 15 36 PM

**Comment by deep7102** [comment]
Hi @jmacaluso711 updated now, to fix the case you found.

**Comment by tmcconechy** [comment]
Dumb question but im not seeing a safari - device toolbar? Where is that? I tried this in chrome device toolbar and i still see the issue:

Screen Shot 2020-09-29 at 9 58 51 AM

**Review by jmacaluso711 — DISMISSED** [review]
@tmcconechy If you go to Develop > Enter Responsive Design Mode, you can then choose a device to test on. @deep7102 Looks good to me now

**Review by tmcconechy — APPROVED** [review]
Thanks @jmacaluso711 thats a new one for me. Also i must not have the latest. I retried this branch and the fix is working in both safari and chrome dev tools for me now

**Review by jmacaluso711 — APPROVED** [review]

**Pull request merged**
