### PR TITLE
8889 - Fix error on datagrid eror expanding rows

### LINKED ISSUE #8889: Datagrid: Errors when expanding rows with frozenColumns
**Describe the bug**
Recent changes on #8832 caused an error when expanding rows with frozen cols

**To Reproduce**

1. Go to http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns.html
2. Click on and + to expand rows
3.  See error in console

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes a regression from https://github.com/infor-design/enterprise/issues/8832

**Related github/jira issue (required)**:
Fixes #8889 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-expandable-row-frozen-columns.html
- expand rows
- check the console, should be no errors. also the expandable row should resize

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi Tim, I'm still having errors and UI issues after expanding rows and changing row size. 

Test Data: [screen-capture.webm](https://github.com/infor-design/enterprise/assets/45757016/647b6158-cb55-43f3-9649-b44d5036ab0d)
image


Regards, 
Janah

**Review by jbrcna — APPROVED** [review]
image
image

**Review by glenlieorillo — DISMISSED** [review]
No errors on my end.

https://github.com/infor-design/enterprise/assets/102151352/1375edec-4167-483b-97f4-4846073c9431

**Comment by tmcconechy** [comment]
@janahintal i cant reproduce. Maybe you didnt have the right branch or something?

Can test it here as well https://8889-grid-error-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns.html

**Review by jbrcna — APPROVED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
image

**Review by janahintal — APPROVED** [review]
image

**Pull request merged**
