### PR TITLE
2446 - Add metadata param to the Homepage `resize` event with container height

### LINKED ISSUE #2446: Homepages: homepage.js isn't returning a correct height.
**Describe the bug**
The homepage component element doesn't have a height set on it. 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
2. In devtools highlight the `div.homepage` element.
3. make `overflow: auto` as an element style 
4. See incorrect height

**Expected behavior**
Want to see the height correctly set for the homepage element give it's home page tiles current layout.

**Version**
- ids-enterprise: v4.19

**Screenshots**
image

Notice when I set overflow to auto it shows the home page's true height.

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds an extra parameter to the Homepage component's `resize` event, containing metadata about the current state of the Homepage component.  One of the properties of this parameter is the calculated height of the Homepage container.

The `containerHeight` property is calculating the height of the Homepage container internally based on blocks, the number of available columns and rows, and the gutters.

**Related github/jira issue (required)**:
Closes #2446

**Steps necessary to review your pull request (required)**:
- Pull this branch and run the app
- Navigate to http://localhost:4000/components/homepage/test-hero-widget-calculate-height.html
- Resize the browser viewport once
- Look in a dev tools console.  See that the `console.log` is correctly reporting an object after the `metaData:` string that contains a `containerHeight` property.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

----
paging @pwpatton

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@pwpatton can you check this change against your implementation and see if the number we are passing through the resize event works for setting container height?

@tmcconechy on http://localhost:4000/components/homepage/test-hero-widget-calculate-height.html, in some cases, there seems to be an extra widget's worth of height added to the total.  I'm wondering if [my calculation](https://github.com/infor-design/enterprise/pull/2608/files#diff-22d84c71524b1b9addb8568d1f0d468eR64) is missing a check somewhere?

**Comment by EdwardCoyle** [comment]
@tmcconechy I pushed a change that accounts for a currently-empty row in the `rowsAndCols` matrix.  Added a test for it as well.

**Comment by tmcconechy** [comment]
Yes looks good now to me. I think just need to fix those tests and this seems good. Adding @pwpatton for testing

**Comment by pwpatton** [comment]
@tmcconechy Yes, this seems really good.

**Pull request merged**
