### PR TITLE
8015 - Fixed focus border style

### LINKED ISSUE #8015: Checkbox: Focus State Not Discernible
**Describe the bug**

The focus state on checkboxes needs improvement its not very discernible.

**To Reproduce**
1.  See https://main-enterprise.demo.design.infor.com/components/radios/example-index.html and focus
2. Tab in the page through the checkboxes

**Expected behavior**
Maybe something more like https://main-enterprise.demo.design.infor.com/components/radios/example-index.html

**Screenshots**

Not too bad here but could be better:
Screenshot 2023-10-02 at 1 28 32 PM

More so here:
Screenshot 2023-10-02 at 1 28 27 PM

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed focus border style

**Related github/jira issue (required)**:

Closes #8015 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/checkboxes/example-index.html
- Focus on checkboxes
- Should have similar style to: http://localhost:4000/components/radios/example-index.html

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@yohannahbautista looks good

- https://www.figma.com/file/Lu7tVeygUHVN04nHRgoxxM/checkbox%2Fradio-redesign?type=design&node-id=1-53&mode=design&t=uu01kR0i9eMVBaRZ-0
- the design looks a bit different but i like the way this looks a little tighter

Can we make these changes to the Radio too?

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
image
image
image
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
image

RTL Issues
- Misaligned dirty indicator

- warning indicator looks off

http://localhost:4000/components/checkboxes/example-index.html
image

image

image

**Review by janahintal — CHANGES_REQUESTED** [review]
Focus still not that visible and could be improved on the following:

https://8015-checkbox-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=new&mode=dark&colors=default
image


https://8015-checkbox-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=classic&mode=light&colors=default
image

**Review by janahintal — APPROVED** [review]
Approving 
image
image

**Pull request merged**
