### PR TITLE
7505 - Hero Widget Alabaster

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix Dropdown border not rendered properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7505

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/homepage/example-hero-widget.html
- Check the colors on personalization are not changed when changing color
- Confirm on all 6 themes (mode/version)
- For more steps for testing follow through the issue link

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by yohannahbautista** [comment]
Outline on the charts seem to change color
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Dropdown menu font/hover color issue:

Steps to reproduce:
1. Hover dropdown menu
2. Change color from 'Default' to 'Alabaster'
3. Hover again the dropdown menu and notice the font color
4. Change again the color from 'Alabaster' to any color (_Ruby_)
5. Hover again the dropdown menu 

image

image

image

**Review by glenlieorillo — APPROVED** [review]
image

image

image

**Review by janahintal — APPROVED** [review]
Approving. Verified working in http://localhost:4000/components/homepage/example-hero-widget.html thanks!

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 looks good for me. Good job finding all the rules. The only issue i see is the button should not have special style like this

Screenshot 2023-08-14 at 11 30 10 AM

It should just be a regular button as per Tertiary buttons on https://main-enterprise.demo.design.infor.com/components/button/example-index.html (see hover/disabled https://main-enterprise.demo.design.infor.cm/components/button/example-menubutton.html

Opening up for design QA assuming that will be fixed. CC @talkaboutdesign - see anything else?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 looks good for me. Good job finding all the rules. The only issue i see is the button should not have special style like this
> 
> Screenshot 2023-08-14 at 11 30 10 AM
> It should just be a regular button as per Tertiary buttons on https://main-enterprise.demo.design.infor.com/components/button/example-index.html (see hover/disabled https://main-enterprise.demo.design.infor.cm/components/button/example-menubutton.html
> 
> Opening up for design QA assuming that will be fixed. CC @talkaboutdesign - see anything else?

 I actually saw this, but didn't bother to change first because I'm not sure if it is correct or wrong. Thanks for this one, @tmcconechy. I'll change it.

**Comment by talkaboutdesign** [comment]
Will look into it in the am. Can you tell me everything that changed?

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — DISMISSED** [review]
Approving. just an observation, the caret color is off when hovered.
image

**Comment by tmcconechy** [comment]
Screenshot 2023-08-17 at 10 03 16 AM

@jbrcna i fixed that. Perhaps the live link was'nt updated as we were having problems with that recently but should be fixed. So will ignore that for now

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
1. Dropdown menu is unreadable in High Contrast Mode.
2. Labels are not aligned in legend, same issue with this ticket [7834](https://github.com/infor-design/enterprise/issues/7834)

https://github.com/infor-design/enterprise/assets/102151352/8a8d1f3e-33e8-4426-9af2-84b37af985d3



image

image


image

**Comment by tmcconechy** [comment]
@glenlieorillo good catch. it should not be azure in contrast mode. so i added a fix for the 1.
2. will be fixed later on that other issue

**Comment by talkaboutdesign** [comment]
@tmcconechy slate seems to present wrong text color in header. 
CleanShot 2023-08-18 at 17 00 53@2x

**Comment by tmcconechy** [comment]
@talkaboutdesign yes we were tracking that issue on this one https://github.com/infor-design/enterprise/pull/7825

should be fixed there soon

**Comment by tmcconechy** [comment]
@talkaboutdesign anything to add other than https://github.com/infor-design/enterprise/pull/7825 which is being fixed? Or else will merge

**Comment by talkaboutdesign** [comment]
I didn't notice anything else.

**Pull request merged**
