### PR TITLE
7320 - Change default color back to azure 

### LINKED ISSUE #7320: Personalization: Make Azure the Default
**Describe the bug**
Was decided we arent quite ready to make white/alabaster the default. So will need to make azure the default again and make alabaster a personalization option. This as of now needs to go in 4.80.x as a patch and be changed delaying the 4.81.x release. So this is high priority.

Sorry about this @ericangeles ! Maybe it can be PR'd to main, then copied back to 4.81.x and 4.80.x with one general fix and testing?

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html
2. Header should be azure
3. Open the .. menu and select colors -> should be an alabaster option
4. Open the .. menu and select default -> should go back to azure 
5. Open the .. menu and select azure -> should also go back to azure 

**Expected behavior**
 - test https://main-enterprise.demo.design.infor.com/components/personalize all should be azure by default
 - test https://main-enterprise.demo.design.infor.com/components/header all should be azure by default
 - in any page the colors should have a new alabaster option
 
**Version**
- ids-enterprise: [e.g. v4.80 / v4.81.0]

**Additional context**
Fix is probably changing all variables in https://github.com/infor-design/enterprise/blob/main/src/themes/theme-new-light.scss back to azure as a default
https://github.com/infor-design/enterprise/tree/main/src/components/personalize needs alabaster added to the list and code to make it happen.

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the default color back to azure and add alabaster in personalization colors.

The focus areas of these changes, for now, are the header, masthead, and personalize components. I anticipate that some components will be affected by this revert, but we can fix those next time.

For patch `[4.80.x, 4.81.x]`

**Related github/jira issue (required)**:

Closes #7320 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/header/example-index.html
- Default color should be azure
- Check the `Colors`
- Alabaster should be available
- Test all elements in different colors
- Test all example pages
  - http://localhost:4000/components/header
  - http://localhost:4000/components/masthead
  - http://localhost:4000/components/personalize

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by danielortiz1982** [comment]
@tmcconechy @deep7102 @EdwardCoyle 
Can you please provide support on this PR. It's urgent. Thank you.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks good to me.. The only issues i see are:

- in contrast mode the color should be darker azure see https://4601-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html?colors=0066D4 -> dont think it was correct before but should be 0066D4 as its higher contrast
- in classic contrast there is a problem with the button color http://localhost:4000/components/header/example-index.html?theme=classic&mode=contrast
- I think the focus state can be improved it looks like a double border

Screenshot 2023-03-16 at 9 56 21 AM
- see the old one https://4601-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html?colors=0066D4
Screenshot 2023-03-16 at 9 56 36 AM 
Im just talking about the box shadow not the shape of the button...

**Comment by deep7102** [comment]
Looks nice!
addition to Tim's found I see as:

- In contrast mode search text color, when search field have some text and collapsed state
- http://localhost:4000/components/header/example-index.html?theme=new&mode=contrast&colors=default
image

- Classic theme, in contrast mode icons color
- http://localhost:4000/components/header/example-index.html?theme=classic&mode=contrast&colors=default
image

**Review by EdwardCoyle — COMMENTED** [review]
I didn't see anything beyond what Tim and Deepak mentioned

**Review by tmcconechy — DISMISSED** [review]

**Review by deep7102 — DISMISSED** [review]
LGTM 🍌

**Pull request merged**
