### PR TITLE
7631 - Fix XSS when setting up tree node

### LINKED ISSUE #7631: Cross-Site Scripting (XSS) when setting up tree node
**Describe the bug**
When creating a tree you can use cross-site scripting to bypass any protection (escaping).

**To Reproduce**

Steps to reproduce the behaviour:
Create a tree using the SOHO controls. Within the text field add in your attack. EG:

```
 <ul role="tree" id="addnode-tree" aria-label="Asset Types" class="tree" data-init="false">
          <li>
              <a href="#" id="home">'\"><img src=x onerror=alert(1)>'</a>
          </li>
</ul>
```
Please see:

https://stackblitz.com/edit/ids-enterprise-4jn25k?file=index.html

Based off https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/test-add-node?theme=uplift&variant=light

**Expected behaviour**
The code should protect you against it. The reason why this is important is that we create trees based on user input (a workaround has been implemented).

**Version**
v4.50.2

**Screenshots**
image

**Platform**
 - Infor Application/Team Name:  SunSystems
 - Device: N/A
 - OS Version: N/A
 - Browser Name:  All
 - Browser Version: 114.0.5735.134 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes cross-site scripting when setting up tree node.

**Related github/jira issue (required)**:

Closes #7631 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tree/test-add-node.html
- The error message should not pop up before the page loads
- Note: If you see error in console regarding (404), that's fine

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Failing on my end. 
https://7631-tree-xss-enterprise.demo.design.infor.com/components/tree/test-add-node.html
image

**Comment by ericangeles** [comment]
@janahintal, try testing it locally. The branch environment isn't working very well today.

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

http://localhost:4000/components/tree/test-add-node.html


https://github.com/infor-design/enterprise/assets/102151352/7e4af947-a858-4e74-9f09-6bb2e27378f2

**Review by janahintal — APPROVED** [review]
Working now in http://localhost:4000/components/tree/test-add-node.html

**Pull request merged**
