### PR TITLE
8768 - Dropdown No Results

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix  no results text still displaying after removing filter text.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8768

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html
- Open dropdown action
- Type something to see the no results text
- Clear it all

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Comment by jbrcna** [comment]
this is working as expected. However, in firefox the dropdown list is cut off.
image
the capslock issue still exists as well
image

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

https://github.com/infor-design/enterprise/assets/156752175/e3b5f213-342a-4bda-b2f8-25dabdbe93c2

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
I replicated the issue found by @jbrcna in Mac Firefox:

- Firefox

_LTR_
image

_RTL_
image


However, It is now working as expected in other browsers.

- Mac Chrome
image

_RTL_
image

- Safari
image

- Mac Edge
image

**Comment by tmcconechy** [comment]
@tjamesallen15 also does this fix take into account: https://github.com/infor-design/enterprise/issues/8768#issuecomment-2145929009

**Review by glenlieorillo — APPROVED** [review]
Working now as expected in Mac Firefox. Thanks, @tjamesallen15!


https://github.com/infor-design/enterprise/assets/102151352/aef25b52-12af-4ce6-894d-7349c34ff7b5


https://github.com/infor-design/enterprise/assets/102151352/b06f638e-8c1b-4245-a0d1-31d51e776ea2

**Review by jbrcna — APPROVED** [review]
working on my end as well. thanks @tjamesallen15 
image

the capslock issue still exist.
image

**Pull request merged**
