### PR TITLE
7783 - button menu secondary combo

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix  stylings for button menu and secondary combo.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7783

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/button/example-menubutton.html
- See the button under `Button Menu + Secondary`
- Try it on other mode and colors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 looks good but the style needs improvements

Screenshot 2023-09-21 at 11 20 04 AM

1. the icon can be same color as the text (this might be just me because of the icon changes) if so ignore
2. the padding should be equal on each side same as https://main-enterprise.demo.design.infor.com/components/button/example-index.html (can really look like the action button with the icon but the icon on the other side)

**Comment by tjamesallen15** [comment]
> @tjamesallen15 looks good but the style needs improvements
> 
> Screenshot 2023-09-21 at 11 20 04 AM
> 1. the icon can be same color as the text (this might be just me because of the icon changes) if so ignore
> 2. the padding should be equal on each side same as https://main-enterprise.demo.design.infor.com/components/button/example-index.html (can really look like the action button with the icon but the icon on the other side)

The point 1, didn't appeared to me, both on Windows and Mac
The point 2, is taken for adjustment

Thanks!

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by yohannahbautista — DISMISSED** [review]

**Review by janahintal — CHANGES_REQUESTED** [review]
Button menu disappear after opening the menu using tab and keyboard click. 
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
Failing in alabaster
looks disabled in dark mode

image

high contrast 
when you hover out the button is not visible
image

**Comment by tjamesallen15** [comment]
Will do it tomorrow, I'm SL today.

**Comment by tjamesallen15** [comment]
Hello All,

All of the test are cannot be reproduce on my end. Please my screenshots.
image
image
image

Please give me a clear and concise step by step information.
Please also pull dependencies by doing npm i (remove first your node_modules folder) and doing an npm run-script build and npm rebuild node-sass for the svg icons to be fixed.

**Comment by jbrcna** [comment]
verified in https://7783-button-menu-secondary-combo-enterprise.demo.design.infor.com/components/button/example-menubutton.html?colors=ffffff

under `"Buttom Menu"`
hovered over the button, click, then remove the mouse. please refer to max observation [here](https://github.com/infor-design/enterprise/issues/7783#issuecomment-1732830240)

**using keyboard**
under `Button Menu + Secondary`
click "Add item" , press shift + tab, then press Enter

**Review by jbrcna — CHANGES_REQUESTED** [review]
verified in local
image
image

**Review by jbrcna — COMMENTED** [review]
the issues mentioned above were now fixed. however, the hover is off in classic theme, azure color
image

`Azure classic`
https://7783-button-menu-secondary-combo-enterprise.demo.design.infor.com/components/button/example-menubutton.html?colors=0066D4&theme=classic&mode=light
image

**Review by janahintal — APPROVED** [review]
Approving. 

Observation: There is no focus on Button Menu + Secondary button when on keyboard navigation. 
https://www.loom.com/share/f1365b82214646d3897b1da15cc01288?sid=42514d24-ff03-40f9-a076-4ef6319c48eb

**Review by jbrcna — APPROVED** [review]

**Comment by ericangeles** [comment]
> Approving.
> 
> Observation: There is no focus on Button Menu + Secondary button when on keyboard navigation. https://www.loom.com/share/f1365b82214646d3897b1da15cc01288?sid=42514d24-ff03-40f9-a076-4ef6319c48eb

@janahintal please create a new ticket and we'll take a look.

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
