### PR TITLE
4818 - Remove Tabs Animation

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the NaN value showing on tooltip in sliders.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/4818
Closes https://github.com/infor-design/enterprise/issues/5094
Closes https://github.com/infor-design/enterprise/issues/5164

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- http://localhost:4000/components/tabs/test-no-animation-tabs.html
- Delete the value of the textbox under Contracts Tab.
- Required icon will appear
- Input any value again in the textbox
- Observe the animated bar

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Hello @tmcconechy 

Note: There's a lot of commented out lines of code right now but I will remove it once this pull request was reviewed. I just didn't remove the codes first because it's all over the place and I might have trouble bringing back it just in case for revision.

I will also add the changelod together with updating the commented out codes.

Thanks!

**Comment by ericangeles** [comment]
@tjamesallen15 Tim and I had a conversation about the additional fix for this. Once the animating removes, just use the CSS approach to have a border bottom styling when selected. You probably need to tweak a bit the stylings on the tabs area.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks like its mostly working. 

1. Please remove commented commented code
1. http://localhost:4000/components//modal/test-tabs.html -> the bar is initially the wrong size when opening the modal

Screen Shot 2021-07-14 at 10 26 27 AM

1. could add a bit more space for the error icon (if easy not a big deal)

Screen Shot 2021-07-14 at 10 27 03 AM

**Review by EdwardCoyle — COMMENTED** [review]
This is looking good so far.  One additional thing I found:
- http://localhost:4000/components/tabs/example-index.html?theme=classic
- On Classic theme, the selected state is a bit taller.  It should be the same size as the hover state:

Screen Shot 2021-07-15 at 10 11 49 AM

**Comment by tmcconechy** [comment]
@tjamesallen15 Still see a couple small things but this is looking good

1. The seected "bar" is a little shorter than before compare https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html to http://localhost:4000/components/tabs/example-index.html
2. If you tab into the tab and then arrow left  you will see the focus box is pushed up 
Screen Shot 2021-07-16 at 9 45 30 AM

**Comment by tmcconechy** [comment]
@tjamesallen15 i still see Ed's one issue. Also some tests are failing https://github.com/infor-design/enterprise/pull/5424/checks?check_run_id=3103023364#step:11:3377

I would think the visual styles should be the same but if they are just a bit off we can update the images. But some of the other failures should be looked at, in some cases maybe these tests are not needed anymore and can be removed or refactored.

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

I'll update the images.

On Eds issue, can you pinpoint me what's the issue as it someone not clear to me. Here is the current screenshot on my latest commit.
Screen Shot 2021-07-21 at 2 45 20 PM

I will check the baseline images for now.

Thanks!

**Comment by tjamesallen15** [comment]
Hello Team,

I'm still not finish checking and working on fixing affected components.

**Comment by tmcconechy** [comment]
@tjamesallen15 it looks better now for eds issue (before the darak border on hover was thicker). it was just comparing https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=classic&mode=light with http://localhost:4000/components/tabs/example-index.html?theme=classic&mode=light

and http://localhost:4000/components/tabs/example-index.html with  https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html

The only thing i do see is that the size is a few pixels different. Its probably passable but would look more centered and possibly fix some visual regressions if we made them equal. See https://drive.google.com/file/d/1iO4omEP0Zr2yVae5Bm_ranBVaJnKPnc7/view

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

Please review my changes first after that, I'll update the baseline images! :) 

Tahnks!

**Comment by ericangeles** [comment]
Looks good now @tjamesallen15. One thing I noticed, when you scale down and triggers the tab-more button, it shows a scroll bar.

tab-scrollbar

**Comment by tmcconechy** [comment]
aside from @ericangeles  comment im ok to approve this once thats addressed

**Comment by tjamesallen15** [comment]
Done with scrollbar! :) @tmcconechy @ericangeles

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]
Approved but lets let @EdwardCoyle have a second look since this is pretty critical functionality

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
