### PR TITLE
8904 - FileuploadAdvanced beforefileupload

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add beforefileupload event in handleFileUpload method.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8904

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/fileupload-advanced/example-index.html
- Open `Developer Console`
- Put one item or drag an item in the fileupload
- See the event log below

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
image

**Review by ericangeles — COMMENTED** [review]
Looks good! Perhaps a test, @tjamesallen15?

**Review by jbrcna — DISMISSED** [review]
image

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
Please add this to NG as well, @tjamesallen15. Thanks! 🍌

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
