### PR TITLE
8600 - Added background settings for homepage and hero widget

### LINKED ISSUE #8600: HomePages: Add Background image functionality
**Describe the bug**

1. Add the ability to show a background image on home pages. This is optional via a setting.
1. Also when resizing to mobile the chart size (width) isnt correct...This might be a regression.

**Task**
Add this to both EP and WC.

**Screenshots**

Screenshot 2024-04-05 at 7 30 29 AM

**Additional context**
https://inforwiki.atlassian.net/browse/IDS-2068
https://inforwiki.atlassian.net/browse/IDS-2143

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added background settings for homepage and hero widget

**Related github/jira issue (required)**:

Closes #8600 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/homepage/example-background-image
- Hero and homepage should have image backgrounds

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by jbrcna — CHANGES_REQUESTED** [review]
nice background
image

just minor observation
no image in classic , firefox browser
image

button is not properly displayed, Safari browser
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
`Metals` not visible in the chart
image

Texts are hard to read in Dark Mode
image

Dropdown menu is cut off in Safari
image

Legend focus looks off
image

Pie chart is cut off in RTL
image

image

Image background is cut off in a small viewport
image

image

**Comment by talkaboutdesign** [comment]
A few other things to keep in mind. 

Image is behind all the widgets. It has a specific height. (defined in the design file). 

Banner widgets should look like regular widgets now. With solid background. Image should not be visible through them. See design file with examples and clear guidelines.

**Comment by tmcconechy** [comment]
cc i reviewed this with @talkaboutdesign he mentioned some items (im not seeing them in the design)

1. The logo is a separate item. There are two options. Background image, and logo should be a separate item you setup.
2. That part of page should scroll up with the rest of content. Right now its sticky.
3. Banner area should be shown, with pager widgets (can be empty)
4. Demo: https://www.figma.com/file/3NBGQJthD3eY6l9cjI9UQn/Workspace%3A-October-24-Release?type=design&node-id=22%3A7962&mode=design&t=2RxIQk5ZeJs9J5fb-1
5. Log should follow with the widget
Screenshot 2024-04-25 at 10 37 20 AM
7. Aligned here
Screenshot 2024-04-25 at 10 37 42 AM

Anything unclear let us know 👍🏻

**Comment by tmcconechy** [comment]
@yohannahbautista see https://github.com/infor-design/enterprise/issues/8600#issuecomment-2079438529 for feedback/ Thank You!

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
- Shadow effect of the next card/pager is visible.
image

- Bottom border is cut off.
image

- Arrow keys is not working on the third page.

_Steps to reproduce:_
1. Click on pager
2. Use right/left key to switch page
3. Try to use the tab key then enter - working

https://github.com/infor-design/enterprise/assets/102151352/74f4e037-dca7-4eb8-9b53-ca1bdb2ac1a8

**Comment by tmcconechy** [comment]
@yohannahbautista i think this looks good. 

The only additional issues i see:

a) is if you go to 2 or 3 widget width and reload the page. You see the page load a bit wierd. Where the image is shown and then the widgets fade in. Its pretty noticible. Maybe we can do something about that?
b) the issue of the width at the bottom of the page noted in the video is still there

**Review by ericangeles — APPROVED** [review]
This looks fantastic, @yohannahbautista! 🍌 

If I am going to cherry-pick, the only thing is that the border color(left and right) is not there when sliding the widget/card. But overall, this is great!

**Comment by ericangeles** [comment]
@yohannahbautista, please add a doc for this feature and create PR for NG as well. Thanks!

**Review by glenlieorillo — APPROVED** [review]
Nice, @yohannahbautista!⭐️

https://github.com/infor-design/enterprise/assets/102151352/42ac265d-c3e3-4060-862b-d0590c0ad5d3

**Review by n-ace-ancog — DISMISSED** [review]
Very nice!

image

image

image

image

**Review by janahintal — DISMISSED** [review]
https://www.loom.com/share/1ba89cab00db4c73a7dc6c4040760e0a?sid=348df254-6a19-4b14-9fd4-a64155269d92

**Review by jbrcna — DISMISSED** [review]
Brilliant! 
image

image

image

**Comment by tmcconechy** [comment]
@yohannahbautista @ericangeles 

1. I still dont really love how the top fades in... anything we can do?
2. Can we make even more space on the bottom? 20px padding like between widgets

**Comment by ericangeles** [comment]
@tmcconechy, maybe instead of fades in, perhaps a smooth transition?

**Comment by tmcconechy** [comment]
Sure: Lets see how that looks. Or maybe a faster fade in by maybe 50% faster? The other idea i had was fade in from bottom to top as it looks like it goes top to bottom, but not sure how easy that is?

**Review by tmcconechy — DISMISSED** [review]
Good from me. Im waiting on design reviews though.

**Comment by alixrosales** [comment]
https://www.figma.com/file/3NBGQJthD3eY6l9cjI9UQn/Workspace%3A-October-24-Release?type=design&node-id=22-22870&mode=design&t=rLBgwnQlmLE5Grgg-0

When a brand image is added, the widgets shift down a bit to give more space for it. There should be equal amount of space between logo and top of branded area, and widgets.

**Comment by alixrosales** [comment]
1. The pager (three dots) are not centered with the widgets. 
2. Spacing between banner widgets and pagination 8px. Space between masonary widgets section and pagination 16px.
3. When I scroll all the way down, there's no padding with the bottom of the page. 

Doesn't seem like I'm able to add images -- but trying here: 
CleanShot 2024-05-03 at 12 56 05@2x

**Comment by tmcconechy** [comment]
@yohannahbautista see above from @alixrosales please. Also for the padding maybe you need to pull main again for the fix[ ](https://github.com/infor-design/enterprise/pull/8670)

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Widgets are still misaligned.

image

Looks off in a smaller viewport.
image

**Review by n-ace-ancog — COMMENTED** [review]
Seems to be aligned now.
image

The only issue I see is there now space at the very bottom.
image

**Review by janahintal — CHANGES_REQUESTED** [review]
There is unnecessary object in the right side of the card when in responsive view. 
Pager is still not centered. 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
No bottom border.

image

**Comment by ericangeles** [comment]
@glenlieorillo for that, we have an open PR that fixes that https://github.com/infor-design/enterprise/pull/8680.

**Review by glenlieorillo — APPROVED** [review]
This is noted, @ericangeles. Approving this PR. 

https://github.com/infor-design/enterprise/assets/102151352/6c85a6ba-021b-4a21-b9d2-2702c3b80af3


https://github.com/infor-design/enterprise/assets/102151352/1f66c95a-cf64-43a7-bf7a-07f7a2549f6d

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.

image

image

image

image

**Review by ericangeles — APPROVED** [review]

**Comment by ericangeles** [comment]
Think we're good here, @tmcconechy. 

Thanks for the hard work, @yohannahbautista 🥂

**Pull request merged**
