### PR TITLE
3805  - Add fix for app menu button not firing due to bad extend logic

### LINKED ISSUE #3805: ApplicationMenu: Button not working in NG
**Describe the bug**
Due to changes on extend the app menu button is not working in NG. The problem is empty arrays are not getting extended properly in the settings.

**To Reproduce**
1. Go to the ng project on master
2. Click on the hamburger menu
3. See error (its not working)

**Expected behavior**
This works and extend works.

**Version**
- ids-enterprise: [e.g. v4.27]

**Platform**
 - Chrome

**Additional context**
Originated in Ms Teams

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Extend did not extend arrays the same way jquery does (position by position). This caused the way the app menu settings are passed in NG to not work in the sample app.

**Related github/jira issue (required)**:
Fixes #3805

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/applicationmenu/test-manual-init.html
- app hamburger should work
- all tests should pass

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.

### CODE REVIEW

**Comment by jmacaluso711** [comment]
Looks good. Noticed a separate minor issue. The hamburger icon looks like it got messed up at some point:

Screen Shot 2020-04-27 at 11 19 15 AM

Might be worth fixing in another issue?

**Comment by tmcconechy** [comment]
hmm i tried to fix that. so maybe i made it worse? is that on http://localhost:4000/components/applicationmenu/test-manual-init.html ? it wasnt centered before but this looks worse

**Comment by jmacaluso711** [comment]
Yeah I see it on http://localhost:4000/components/applicationmenu/test-manual-init.html -- Looks like the first bar's top position is off or something

**Comment by tmcconechy** [comment]
Mine looks better @jmacaluso711 is this chrome? Do you have zoom set?

Screen Shot 2020-04-27 at 12 56 18 PM

**Comment by jmacaluso711** [comment]
Ah.. yes I was slightly zoomed

**Pull request merged**
