### PR TITLE
7570 - Fileupload Icon Alignment

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the alignment of the close button and file icon button.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7570

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/fileupload/example-index.html
- Upload a file
- Hover `x` icon

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks pretty good but can you change the height of both the icon button(s) to match https://main.wc.design.infor.com/ids-upload/example.html

Screenshot 2023-07-12 at 10 33 18 AM
Screenshot 2023-07-12 at 10 33 02 AM

**Review by tmcconechy — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Hover color is off in Dark Mode.

image

**Review by jbrcna — DISMISSED** [review]

**Comment by tmcconechy** [comment]
cc @tjamesallen15 ⬆️

**Review by janahintal — CHANGES_REQUESTED** [review]
Hi Team, fix already applied New but icons still looks off in classic when hovered.
https://app.screencast.com/YYqsLjWUCVaeL

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
image

**Pull request merged**
