### PR TITLE
NG1740 - Fixes on select row in group

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated index used to get row data on select event. Updated dataset used when unselecting rows to sync correctly (dataset used to check if a row is selected or not was different with the dataset updated when deselecting rows, which is why row couldn't be selected a second time)

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1740

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-grouping-multiselect.html
- For row with Customer ID 7:
   - Select row. Should have correct row data in console
   - Deselect
   - Select again. Checkbox should be checked

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Review by n-ace-ancog — COMMENTED** [review]
Seems to be selectable again, but the select all option in column header is not updating on some rows. Is this a setting?

**To replicate**
1. Select 7 and unselect
2. See select all header not updated
3. Refresh the page
4. Select 5 and unselect
5. The select all header is updated

image

https://github.com/user-attachments/assets/101d859a-27a8-4073-98be-fbed2964c7a6

**Comment by yohannahbautista** [comment]
> @yohannahbautista another issue i saw
> 
> 1. Go to https://ng-1740-datagrid-select-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html
> 2. Hit sort on the customer ID column
> 3. select the one with 7 in it and deselect and check the console -> data seems incorrect

@tmcconechy 
Hello, the item data looks identical on my end. If you mean the different indexes, I think that's the usual values
image

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
Looks good.

**Review by n-ace-ancog — APPROVED** [review]
Now working on my end.

https://github.com/user-attachments/assets/9dcf3080-e049-4405-b4ad-4bfa1b31e24d

**Pull request merged**
