### PR TITLE
8434 - Header Tabs Max Width

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add setting `maxWidth` for header tabs for long titles.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8434

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs-header/test-max-width.html
- See the long titles on ellipsis

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@tjamesallen15 nice fix!

@infor-design/qa - i had to merge this one please just test it on main and if any issue raise a new issue or comment here. Thanks

**Comment by jbrcna** [comment]
this is working as expected. However, when you hover over the truncated title only the safari browser has tooltip
Safari
image


other browser

image

**Comment by tmcconechy** [comment]
@jbrcna thats a good point. I think we should add a tooltip later. Made an issue for next time: https://github.com/infor-design/enterprise/issues/8446

**Comment by glenlieorillo** [comment]
Same observation as @jbrcna. I also tested in mobile view (BrowserStack), and the tooltip doesn't work.

image

**Comment by tmcconechy** [comment]
@glenlieorillo I made an issue for the tooltip https://github.com/infor-design/enterprise/issues/8446

**Pull request merged**
