### PR TITLE
6750 - Use optional dependencies

### LINKED ISSUE #6750: Chore: Use optionalDependencies
**Describe the bug**

Will move all test and lint and dependencies not need for the build or server running to the optionalDependencies section.

This will allow the command `npm ci --no-optional` to be used that will reduce the size of the node_modules to be used with deploying the static sites like https://main-enterprise.demo.design.infor.com/components/

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Moves all dependencies not related to build or demo site to optional dependencies. This lets us run ` npm ci --no-optional` which will give a smaller (699.8 to 190MB approx) that can be used to ease space on the deployed containers.

Also removed moment.js as was small fix but its a big dependency.

Also in order to do this i brought back the package-lock.json.

**Related github/jira issue (required)**:
Fixes #6750 

**Steps necessary to review your pull request (required)**:

**Normal Situation**
- `rm -rf node_modules`
- `npm i` -> then check the size of the node modules
- make sure everything works still (the checks will also tell this as normal)

**For static site deploy situation**
- `rm -rf node_modules`
- `npm ci --no-optional` -> then check the size of the node modules it should be less note that there is one error that will be fixed later you can ignore
- `npm run build` -> should work
- `npm run quickstart` -> should start the same site

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
~- [ ] A note to the change log.~

### CODE REVIEW

**Review by danielortiz1982 — APPROVED** [review]
@tmcconechy Looks good to me, I'll defer to @corpulent for final approval. 🚀

**Review by danielortiz1982 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles waiting for @corpulent to try this FYI

**Comment by tmcconechy** [comment]
Put WIP in well @corpulent confirms..

**Comment by tmcconechy** [comment]
Did you test this @corpulent ? Did it help?

**Review by danielortiz1982 — APPROVED** [review]

**Review by corpulent — APPROVED** [review]
looks good

**Pull request merged**
