### PR TITLE
4152 - Fix inconsistencies readonly styling

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes the inconsistencies of readonly styling on all input-related components.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4152

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Navigate to http://localhost:4000/components/form/example-readonly-inputs.html
- All input components should be consistent
- Test this to all themes and variants

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
To me it seems the icon colors for the Readonly state on both Dark variants, and the Vibrant Contrast variant, blend in a bit too much:

**Dark Variants:**
Screen Shot 2020-07-30 at 1 10 27 PM
Screen Shot 2020-07-30 at 1 11 23 PM

**Contrast Variants:**
Screen Shot 2020-07-30 at 1 10 57 PM
Screen Shot 2020-07-30 at 1 11 09 PM

... however, I'm not sure if I should mark Changes Requested here because it matches everything else (I tested against the Datepicker and the icon colors are the same there).  I think as long as it's easily changed, we should be OK if they want to change icon colors for Readonly/Disabled states overall in the future.

**Comment by tmcconechy** [comment]
I suggest that we bump those up/down a notch while we are "in here". As they are rather faint to the point it looks like a mistake @EdwardCoyle

**Comment by ericangeles** [comment]
Does these will work for all the input components?

**Comment by tmcconechy** [comment]
@ericangeles yes for consistency all input components should be similar.

**Pull request merged**
