### PR TITLE
7607 - Fix button icon hover background color when rows are selected

### LINKED ISSUE #7607: List style datagrid shows messed up icon buttons on hover when rows are selected.
**Describe the bug**
In Announcements feature in Portal 2.0 there is an issue with our icon buttons inside a list style data grid. See attached gif for reference.

**Expected behavior**
Buttons should render without artifacts. 

**Version**
4.80.2

**Screenshots**
CleanShot 2023-06-15 at 12 38 54@2x

CleanShot 2023-06-15 at 12 38 29

CleanShot 2023-06-15 at 12 43 18@2x

**Platform**
 - Infor Application/Team Name: Infor OS 
 - Device: Laptop
 - OS Version: macOS
 - Browser Name: All browsers

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the button icon hover background color when rows are selected.

**Related github/jira issue (required)**:

Closes #7607 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-iconfile-buttons
- Paste this code in console to select a row (add `.is-selected` class)
```
$('#readonly-datagrid > div.datagrid-wrapper.center.scrollable-x.scrollable-y > table > tbody > tr:nth-child(1)').addClass('is-selected')
```
- Then hover on those button icons
- Background hover color should be `rgba(0, 0, 0, 0.1)`

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles go to what page? Its missing something in the steps

**Comment by ericangeles** [comment]
@tmcconechy, I updated the steps.

**Review by tmcconechy — APPROVED** [review]
Looks good for now. This is a wierd use case. If you do update this again maybe fix the width on the button or the border-radius to 4px because it has a wierd shape. But not really sure what to do with it so fine for now unless you decide to update it anyways

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Already fixed in Light Mode. However, the issue still appears in Dark and High Contrast Modes.

https://github.com/infor-design/enterprise/assets/102151352/2f3b42e9-b6d8-49cc-a23c-d2771c0deb76

**Comment by ericangeles** [comment]
@glenlieorillo you need to run the script that I mentioned in the steps.

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/1fea4de7-97bb-4584-8687-6944fa5ff089

**Pull request merged**
