### PR TITLE
8617 - Fix missing frozen columns

### LINKED ISSUE #8617: Datagrid: Visibility Issue with columns after update
**Describe the bug**
After updating to IDS version 4.94.2, we noticed an issue with the soho-datagrid component in conjunction with the soho-splitter. Specifically, only the first column of the soho-datagrid is visible, while the rest are hidden. This problem does not occur when using IDS version 4.93.1. Interestingly, if the soho-datagrid is not within a soho-splitter, it displays correctly.
Attached are screenshots showing the difference between the soho-datagrid with three columns (IDS 4.93.1) and the one with only one column (IDS 4.94.2).
We need urgent attention to resolve this issue.

**To Reproduce**

1. use splitter 
2. use soho data grid inside the soho splitter mention in step 1

**Expected behavior**
All the grid column should visible (as they are visible in version 4.93.0).

**Version**

- ids-enterprise:  v4.94.1

**Screenshots**

image

image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

In some cases like a splitter used with a datagrid, some columns become hidden. This was a regression from https://github.com/infor-design/enterprise/pull/8560

**Related github/jira issue (required)**:
Fixes #8617 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-frozen-only.html
- should not be a gap between the two columns and the last one (should be a filler column in the middle that looks empty)
- go to http://localhost:4000/components/datagrid/example-splitter.html
- two columns should show on the grid on the right side

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:

http://localhost:4000/components/datagrid/test-frozen-only.html
Branch vs main
image

image

http://localhost:4000/components/datagrid/example-splitter.html
image

image

**Review by janahintal — APPROVED** [review]
Working as expected 
image
image



Observation: 
Unable to scroll left and right in Mobile https://8617-frozen-col-issue-enterprise.demo.design.infor.com/components/datagrid/test-frozen-only.html 
image

**Review by glenlieorillo — DISMISSED** [review]
_**Before fix:**_

image

**_After fix:_**

https://github.com/infor-design/enterprise/assets/102151352/09bcb39f-c2b6-47df-8917-63899943dab8

image

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
this is working as expected
image
image

perhaps not related but noting for reference. when the viewport is smaller, the bottom border is missing
image

**Pull request merged**
