### PR TITLE
4598 - Ability to add line chart in column-grouped

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the ability to insert/add a line chart into column-grouped component.

The column-grouped with line chart would have,
- ability to hide the dot of the line chart
- the tooltip to work only with the dots
- a legend for the line chart
- not able to select/click the legend
- add attributes e.g. automation ids

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4598

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined
- It should show the line chart with dots
- It should have legend of the same color
- Legend of the line should not clickable (compare to the column legends)
- Hovering the dots will show a tooltip with data
- Inspect the line chart
- It should have ids and automation ids (line chart itself and the dots)
- Go to http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined-hide-dots
- It should show the line without dots
-  It should have legend of the same color
- Legend should not clickable
- Inspect the line chart and it should have id and automation ids
- No other functionality (like a tooltip) if the dots are hidden

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@tmcconechy do we need to add this also to 4.57 or it's fine in 4.58?

**Comment by tmcconechy** [comment]
nice work 👍🏻  look great.

1. is it possible to customize the color of the line by the API? (color data)
2. by default the dark mode color probably needs to be changed http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined?theme=new&mode=dark&colors=0066D4 (maybe it can just use the some color  / class as the bottom axis line)

**Review by deep7102 — APPROVED** [review]

**Comment by tmcconechy** [comment]
Maybe will wait on this then for 4.57 as i think we should fix the theme

**Comment by ericangeles** [comment]
@tmcconechy is this okay now? I just change the color of the line chart to slate04 when in dark mode.

**Review by tmcconechy — DISMISSED** [review]
Yes looks good now 👍🏻

**Review by tmcconechy — APPROVED** [review]
Adjusted to slate 30. Since deepak already approved im going to go ahead and merge.
Nice job on this one again @ericangeles . It was a tough one 👍🏻

**Pull request merged**
