### PR TITLE
5550 - Fix on datepicker header not showing

### LINKED ISSUE #5550: In Model popup date picker's year and month get hide
**Describe the bug**
In Model popup Date picker's header get hide. 

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/datepicker/test-modal.html'
2. Click on 'Date Control'
3. See date picker's header get hide.

**Expected behavior**
It should show date picker properly.

**Version**

- ids-enterprise: V4.51.1

**Screenshots**
MicrosoftTeams-image (8)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

If the datepicker top position reaches a certain point, it will switch to horizontal view and move lower.

**Related github/jira issue (required)**:

Closes #5550 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datepicker/test-modal.html
- Minimize browser to 660 or below in height or switch to mobile
- Click "Add Context"
- Open datepicker
- Header should be shown

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
I dont mind this solution. But wondering if its possible to get the arrow shown and have it point to the field. Maybe it can position on top or left of the field in this case? Using the position API.

**Comment by yohannahbautista** [comment]
> I dont mind this solution. But wondering if its possible to get the arrow shown and have it point to the field. Maybe it can position on top or left of the field in this case? Using the position API.

@tmcconechy Would this be okay?
Screen Shot 2021-09-20 at 12 08 02 PM

**Comment by ericangeles** [comment]
@tmcconechy it does make sense to put the datepicker on the right side instead of on top when on a certain height.

**Comment by tmcconechy** [comment]
@ericangeles @yohannahbautista - i do think this looks ok but it would be better on top or bottom. Thats usually what it did before. But this would be more than acceptable in my opinion

**Comment by ericangeles** [comment]
@tmcconechy yeah, I think if the screen size can still accommodate the height of the datepicker, we can still use the on-top position. And if the screen is wider or in landscape mode, we can use the right position.

**Comment by tmcconechy** [comment]
Sounds good: Default Bottom, Next Top, Then Left or RIght (depending on RTL direction)

**Comment by yohannahbautista** [comment]
Hi, here's how it looks so far (the placement depends on the datepicker's position)
Screen Shot 2021-09-21 at 11 00 55 AM
Screen Shot 2021-09-21 at 11 01 42 AM
Screen Shot 2021-09-21 at 11 02 08 AM

**Comment by ericangeles** [comment]
Looks good now! The only issue now is when you're on mobile, landscape mode. The datepicker header is still missing.

dp

Tested it on iPhone X Landscape mode.

**Comment by ericangeles** [comment]
Looks good! The only issue now is when you're on mobile, landscape mode. The datepicker header is still missing.

dp

Tested it on iPhone X Landscape mode.

**Comment by ericangeles** [comment]
@yohannahbautista I also noticed that when the datepicker pops up, the button `Add Context` moves.

**Comment by tmcconechy** [comment]
I think this looks right 👍🏻  so should be good once you iron out all the issues

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
I think this is working better now. Thanks @yohannahbautista 
One thing we might want to fix is if i click the calendar icon once it opens. If i click it a second time it should toggle closed but it just closes and opens. Its unrelated but could be a simple fix? If not we can make an issue for it

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
