### PR TITLE
5286 - Unable to reopen filter options after paging

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the reopening of filter options after doing pagination. In Popupmenu component, doesn't meet the condition for wrapping and unwrapping of the menu. (In `teardown()` method)

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5286

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Scenario 1
- Go to http://localhost:4000/components/datagrid/test-filter-paging-client-side.html and http://localhost:4000/components/datagrid/test-filter-paging-server-side.html
- Click on any filter options dropdown (keep it open)
- Click on "Next Page" or "Last Page" button
- Close the filter options dropdown
- Try to open it again
- It should open the filter options

2.) Scenario 2
- Click on any filter options dropdown (Open at least 3)
- Reopen the previous filter option
- It should open the filter options

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Sorry @ericangeles I think this should work another way. (which might make it simpler actually).

So when you click any of the ager buttons it should close then (and then reopen) as when you click out of the popup it should usually close.

**Comment by ericangeles** [comment]
@tmcconechy does this not behave as expected?

**Comment by ericangeles** [comment]
@tmcconechy, hmm weird coz it gets close when moving to the other page on my end.

**Comment by ericangeles** [comment]
The thing here is that the close method (from Popupmenu) doesn't really work and it doesn't meet the condition under `teardown()`. Can find here `if (!otherTriggers.length) {`.  For some reason, the id is just being replicated/moved when you click the other filter options.

**Comment by ericangeles** [comment]
filter-reopen

**Comment by tmcconechy** [comment]
This is what im seeing:
https://drive.google.com/file/d/1STVdW-S_Aq3qgI1lYA3uMvJlm2rbF0Zg/view

1. http://localhost:4000/components/datagrid/test-filter-paging-client-side.html
2. open filter dropdown
3. hit next page

**Comment by tmcconechy** [comment]
Maybe you can add this https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L1687 to the pager button click or page events

**Comment by ericangeles** [comment]
@tmcconechy it seems that the `this.currentHeader` is not the right target that's why the `close()` method doesn't work at all.

**Review by tmcconechy — APPROVED** [review]
Ok, not sure whats wrong before but i do see it working now. Maybe my branch was out of sync. Sorry 👍🏻

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
