### PR TITLE
5073 - Fix reopening of filter options after doing sorting on server-side paging

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

After the new implementation of shared popupmenu lifecycle, for some reason, the server-side paging in Datagrid does not work properly or it appears to affect the behavior of the Popupmenu instance.

This PR fixes reopening of filter options after doing sorting on server-side paging.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5073

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-filter-paging-server-side.html
- Click on any filter options dropdown (keep it open)
- Do a sort (on any of the columns)
- Close the filter options dropdown
- Reopen the filter options dropdown
- It should open the filter options dropdown

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
@ericangeles your fix wasn't quite working for me. So i changed it a a bit to close the menu when you sort. This seems to fix it.

**Comment by ericangeles** [comment]
@tmcconechy so the dropdown option will be close when doing sorting? So it will not remain open?

**Comment by tmcconechy** [comment]
Yeah when you click out it should close i think (even on sort). And i think thats the main issue.

**Comment by ericangeles** [comment]
I see. My initial fixed was it will stay open even after doing sorting, then when you close the filter option and tries to open it again, it should reopen.

**Comment by tmcconechy** [comment]
Yeah but if you click anywhere else on the header it closes. So i think if you sort it should close... Seems to work as i expect with this.

**Comment by ericangeles** [comment]
Got it then! :) Was under impression that it should behave as the same with the 4.38.1. 

https://4381-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html

**Comment by tmcconechy** [comment]
Yeah i think this seems better to me - more consistently closing when you click out

**Review by EdwardCoyle — APPROVED** [review]
Looks good guys

**Pull request merged**
