### PR TITLE
NG1124 - Missing About Events

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add event exposure in about component.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1124

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/about/example-index.html
- Open `Developer Console`
- Click the button to open the About Modal and close it.
- Notice the events are being triggered.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by deep7102 — CHANGES_REQUESTED** [review]
Hi see the events firing but in weird way
http://localhost:4000/components/about/example-index.html
image

**Comment by tmcconechy** [comment]
@tjamesallen15 yeah looks like they are in the wrong order https://github.com/infor-design/enterprise/issues/5743

should be: beforeclose then close then afterclose

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]
🍌 Looks good

**Review by tmcconechy — APPROVED** [review]
https://github.com/infor-design/enterprise/pull/6094 has the chrome driver problem fixed

**Pull request merged**
