### PR TITLE
5234 - Add example of vertical tabs inside of CAP

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR implements vertical tabs inside of contextual action panel.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5234

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/contextualactionpanel/example-cap-tabs-vertical.html
- Click `CAP - Tabs Vertical` button
- Vertical Tabs should looks fine inside of CAP
- Play around the CAP (Check links to make sure it's clickable)
- Test on mobile and tablet viewport
- It should be responsive
- When you hit the `767px` below, it should change to normal tabs

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Screen Shot 2021-06-24 at 9 19 29 AM

This looks pretty good. The only thing i see is a double scroll bar. Also nting we need an example of this in NG as well when this is done. Does that need a seperate issue?

**Comment by ericangeles** [comment]
@tmcconechy see that too. The modal wrapper has a dynamic max height. Ideally, to make the left tabs sticks is to have a fixed height. The height of the modal will really depend on how long the contents are. This kinda tricky on the responsive layout aspect. But yeah, will try to find a better way to fix the unnecessary scrollbar.

**Comment by ericangeles** [comment]
Also, I guess we need a ticket issue for NG example?

**Comment by tmcconechy** [comment]
Made one here @ericangeles https://github.com/infor-design/enterprise-ng

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
