### PR TITLE
8956 - Improve swaplist drop area

### LINKED ISSUE #8956: SwapList: Enlarge the drop target area when there is no existing item to begin with
**Is your feature request related to a problem or use case? Please describe.**
Intuitiveness. The drop area is too small and almost non-visible on initial drag-drop item on each box.

**Describe the solution you'd like**
Enlarge the initial drop target area so it's easier to drop the first item

**Describe alternatives you've considered**
Using the transfer arrow

**Additional context**
drop-area

**And what application do you work on?** 
Landmark Web UI

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR improves the size of the SwapList's drop area when there are no existing items and also fixes some UI inconsistencies.

Additional:
- Refactor some codes in Swaplist
- A command for visual testing in percy
- Documentation in testing

**Related github/jira issue (required)**:

Closes #8956

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/swaplist/test-additional-empty
- Drop and hold the item from an empty target area
- The drop area indicator should be more visible and have a larger drop area than before

**Included in this Pull Request**:
~~- [ ] A test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — COMMENTED** [review]
The drop area is now bigger.

https://github.com/user-attachments/assets/2e471db5-176d-4649-a9dd-8a3a23776792

But, there is this animation going back to its origin when trying to drop the item just below the drop area. _Look at the 0:05 at the video below_

https://github.com/user-attachments/assets/77102caf-1e2f-497d-9ddc-0330a0845073

Also, in RTL its working, but the rounded edge of the boxes are facing the wrong sides when flipped.

image

image

**Review by jbrcna — DISMISSED** [review]
image

**Comment by tmcconechy** [comment]
Good from me. Maybe look at @n-ace-ancog 's point? I didnt notice the animation in the video but we could fix the rounding ect

**Review by glenlieorillo — COMMENTED** [review]
I have the same observation with @n-ace-ancog regarding the animation.


https://github.com/user-attachments/assets/077ecc15-51dc-498f-a13f-5d64a26dbb48

image

**Comment by ericangeles** [comment]
@n-ace-ancog, the animation rollback occurs because the target area doesn’t fully cover the card content area. I’ve made an adjustment so that if you drag outside the area of the existing swap list item, the indicator will cover the entire card content area.

**Comment by tmcconechy** [comment]
I think we are good here then?

**Pull request merged**
