### PR TITLE
8541 - GenAiButton Start Stop

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add start and stop methods for generative timeout.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8541

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/button/test-generative-start-stop.html
- Click `Start`
- Click `Stop`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/69b8bc48-c044-48ef-a2ef-fb5d468a9829

**Review by jbrcna — DISMISSED** [review]
image

image

**Comment by jbrcna** [comment]
is this also available in classic @tjamesallen15 ?

**Review by janahintal — DISMISSED** [review]
image
image

**Review by glenlieorillo — DISMISSED** [review]
Retesting.

**BrowserStack**

- iPhone 15 ProMax

https://github.com/infor-design/enterprise/assets/102151352/fa31d4be-bf77-41ed-b737-17b688fba06a

- Galaxy Z Fold 5

https://github.com/infor-design/enterprise/assets/102151352/0bdd9dae-8076-4c29-8e8f-ee0657e86c56

**RTL**


https://github.com/infor-design/enterprise/assets/102151352/ed360581-9068-40e8-8c8e-a32e7185bc56

**Review by tmcconechy — CHANGES_REQUESTED** [review]
1. Can this part be removed https://github.com/infor-design/enterprise/pull/8568/files#diff-37a7886828368ca85e6042c9e13fea72ec09a5c749eb7cd7a288f1b6c49c1695R29 it seems like its still using it.
2. Can we make it called:

- startAnimation
- stopAnimation

If we have different animations later we can add a parameter to it later for different types.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
