### PR TITLE
329 - Disabled searchfield placeholders

### LINKED ISSUE #329: Searchfield: User can select "No Results" and "All Results" placeholders
**Describe the bug**
User can select "No Results" and "All Results" placeholders.

**To Reproduce**
1. Open Chrome/Safari on Galaxy S9 or iPhone X using browserstack
2. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/searchfield/example-clearable.html
3. Type "test" in the search field
4. Click "No Results", "No Results" will be selected and will be the value of the search field
5. Clear the value of the search field then type "al"
6. Click "All Results For "al", "All Results For "al" will be selected and will be the value of the search field

**Expected behavior**
"No Results" and "All Results" placeholders should not be selectable

**Screenshots**
No screenshot applicable

**Platform**
 - Samsung Galaxy S9+ and S8, iPhone X, iPhone 8
 - Browsers: Chrome, Safari, Firefox

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by tmcastro**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Disabled the "No Results" and "All Results" placeholders
- http://localhost:4000/components/searchfield/example-clearable.html

**Related github/jira issue (required)**:
Closes #329 

**Steps necessary to review your pull request (required)**:
- Type "test" in the search field
- Click "No Results", "No Results" should be disabled
- Clear the value of the search field then type "al"
- Click "All Results For "al", "All Results For "al" should be disabled

### CODE REVIEW

**Comment by tmcastro** [comment]
Will continue working on this on Nov Sprint

**Comment by tmcconechy** [comment]
ok make a note on this when its ready to review again.

**Comment by tmcconechy** [comment]
I would also remove the hover state and cursor for that item, as it makes it seem like you can click it

**Comment by deep7102** [comment]
👍 Agreed with Ed `if we should be disabling the "All Results" link though.`

**Comment by tmcconechy** [comment]
Thats true. I suppose we should change this so that all results can open a link.
Im not sure the API allows for that currently.

**Comment by tmcastro** [comment]
Hey guys, did I understand this right? You wanted me to revert the changes I did for more-results and keep the ones for no-results. Which means that if I click on "All results for 'keyword'", it will still be selected?

**Pull request merged**
