### PR TITLE
8129 - Add new icons

### LINKED ISSUE #8129: Icons: Add new Icons
**Describe the bug**
Add new icons as per:

https://www.figma.com/file/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?type=design&node-id=0%3A1&mode=design&t=6E3lyWA7MXFo9fND-1
https://www.figma.com/file/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?node-id=111%3A11855&mode=dev

**Task**

- Add to both EP and WC
- Should be a 3rd/2nd set of icons you can enable
- icons with _ should be shown for backwards compatibility
- test icon font

**Should Add only to Preview Release until April**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added a new ids-identity package with newly design Icons. This is intended to go in the `preview` version.

**Related github/jira issue (required)**:

Fixes #8129

**Steps necessary to review your pull request (required)**:
- test kitchen sink for new icons http://localhost:4000/ in both new and classic mode
- examine new icons on http://localhost:4000/components/icons/example-index.html in both new and classic mode

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
New Icons are missing in http://localhost:4000/.

image

https://github.com/infor-design/enterprise/assets/102151352/c98cea21-0018-4222-ad73-0fb186ce638b

image

**main-enterprise:**

image

image

https://8129-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html -- APPROVED


https://github.com/infor-design/enterprise/assets/102151352/fef0c7ef-9c18-47b5-8223-174e9ff21616

**Review by janahintal — APPROVED** [review]
Working on my end on both https://8129-new-icons-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default & https://8129-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=new&mode=light&colors=default
https://www.loom.com/share/49c815c695f742dba5c66f88f4bdeb74?sid=b984e098-cb42-4744-8107-ca445420139b

**Comment by ericangeles** [comment]
@glenlieorillo did you re-install the packages?

**Review by glenlieorillo — COMMENTED** [review]
Reinstalled the package. Thanks, @ericangeles!

Working now as expected. However, the modal icons are cut-off in Classic. Do I need to create a new issue instead? @tmcconechy @ericangeles 

image

https://github.com/infor-design/enterprise/assets/102151352/c7a56099-d905-49ba-9435-e77100eba842


https://github.com/infor-design/enterprise/assets/102151352/a3e13767-e8fb-4bbb-8ce1-02aaf6bc54f1

**Comment by ericangeles** [comment]
Thanks, @glenlieorillo ! No need. I believe we have PR fix for that.

**Review by glenlieorillo — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
working as expected.
verified in http://localhost:4000/components/icons/example-index.html & https://8129-new-icons-enterprise.demo.design.infor.com/components/icons/example-index.html

**Comment by jbrcna** [comment]
wait one sec. are these icons by design?. icons were not visible
image

**Comment by jbrcna** [comment]
®️ logo is missing 
`actual`
image

`expected`
image

**Comment by tmcconechy** [comment]
@ericangeles @jbrcna @glenlieorillo 

1. I fixed the icon-user-status-unknown icon
2. For the icon-user-avatar-dark it only shows in dark mode its only used here http://localhost:4000/components/applicationmenu/example-menubutton.html
3. fix the message dialog. It did need a pixel for the new icons to work
4. for the logos I think they are ok. some have the logo and some do not in some cases the logo is white so you cant see it on the background. Just going to let that one go.

**Review by jbrcna — APPROVED** [review]
thanks @tmcconechy

**Pull request merged**
