### PR TITLE
8132 - Added contentWidth column setting to set width in formatters

### LINKED ISSUE #8132: Allow buttons to span full width of column in datagrid
**Is your feature request related to a problem or use case? Please describe.**
Buttons appear clipped on initial load if the column width is lower than the width of the button. For example..
image

**Describe the solution you'd like**
An option to allow button to span full width of column. Like this..
full-width-button-example

**Additional context**
This is for LMCLIENT ticket reported by one of our App teams.

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added contentWidth column setting to set width in formatters. Currently only used in button formatter

**Related github/jira issue (required)**:

Closes #8132 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-contentwidth
- Adjust column width of button column
- Should stay in 100% and adjust accordingly

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
@yohannahbautista, there's a strange behavior when resizing the column. Can we also fix it, so we can ensure it's working perfectly?

**Comment by tmcconechy** [comment]
Also seeing the strange resize maybe can fix it by using fixed width columns in initially?

**Comment by tmcconechy** [comment]
@krishollenbeck will this be a problem? Or else we have to reduce the padding

Screenshot 2023-12-18 at 10 07 04 AM

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
One way to improve this example is by adding the `btn` class to the buttons using a callback function in the formatter.

But I am okay with this fix.

**Review by jbrcna — APPROVED** [review]
image

**Comment by krishollenbeck** [comment]
@tmcconechy Hello, I was on vacation for a couple weeks. Just saw your comment on the padding. I think maybe we can add a class or something in our formatter to override the padding if we need to.

**Pull request merged**
