### PR TITLE
1847 - Adds Appmenu Personalization

### LINKED ISSUE #1847: App Menu: Add personalization options to application menu
**Is your feature request related to a problem? Please describe.**
For deeper personalization of applications, we should add personalization APIs to the application menu.

**Describe the solution you'd like**
When a user sets a personalization color, the application menu inherits that personalized color as well.

**Describe alternatives you've considered**
n/a

**Additional context**
Screen Shot 2019-03-25 at 3 48 37 PM  Screen Shot 2019-03-25 at 3 50 57 PM
Screen Shot 2019-03-25 at 3 48 53 PM Screen Shot 2019-03-25 at 3 48 45 PM

### LINKED ISSUE #1935: Application menu: support full-width role switcher
**Is your feature request related to a problem? Please describe.**
To support complex menus in products like HCM, we need to introduce a more robust role switcher in the application menu.

**Describe the solution you'd like**
Support an menu which areas over the application menu which can be populated by a dynamic and nested list.

**Describe alternatives you've considered**
We could support the more standard popover that exists in examples now but the experience isn't fine tuned and causes some discomfort on a phone layout.

**Additional context**
Picture1

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adds some new features to personalization and app menu.

Appmenu
- Adds a header and footer 
- Adds some content elements/toolbars
- Added support for personalization API
- Add an role switcher

Counts
- Cleanup docs and examples
- Added a non actionable example
- Added counts on top or bottom

Personalization
- Exposed some classes you can use to personalize sections

**Related github/jira issue (required)**:
Closes #1847 
Closes #1935

**Steps necessary to review your pull request (required)**:
App Menu:
http://localhost:4000/components/applicationmenu/example-personalized.html?colors=0563C2
- Type a color  at the end of the url you like
- Try to pick a color from the ... menu 
- Look at the overall example - this one has a flat menu

http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?colors=7025B6
- Type a color  at the end of the url you like
- Try to pick a color from the picker
- Try to pick a color from the ... menu 
- Try the search
- Look at the overall example - this shows the "role switcher"
- Press the menu button on the header to see the role switcher

http://localhost:4000/components/applicationmenu/example-personalized-roles.html?colors=0563C2
- Type a color  at the end of the url you like
- Try to pick a color from the picker
- Try to pick a color from the ... menu 
- Look at the overall example - this one has a multi level menu
- see also in uplift http://localhost:4000/components/applicationmenu/example-personalized.html?colors=7025B6&theme=uplift

Counts:
http://localhost:4000/components/counts/example-not-actionable.html
- Visual only Counts

Personalization Api Classes:
http://localhost:4000/components/personalize/example-classes.html?color=0563C2
http://localhost:4000/components/personalize/example-classes.html
- shows counts as personalized

### CODE REVIEW

**Comment by tmcconechy** [comment]
For the first part the design was different for the two elements, so i copied the design. They shrunk the text down a level (actually there is two classes that can be interchanged. Maybe i can make them start at the same height tho.

The second thing is a quick fix.

**Comment by tmcconechy** [comment]
@jmacaluso711 Pushed a fix for those two things.

**Comment by janahintal** [comment]
Hi @tmcconechy, noticed that when in responsive view, the scroll is overlapping the label. Please see image below. 

Screen Shot 2019-04-23 at 12 21 41 PM


Tested in: 
http://localhost:4000/components/applicationmenu/example-personalized.html?colors=0563C2
http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?colors=7025B6
http://localhost:4000/components/applicationmenu/example-personalized-roles.html?colors=0563C2
http://localhost:4000/components/applicationmenu/example-personalized.html?colors=7025B6&theme=uplift
http://localhost:4000/components/counts/example-not-actionable.html
http://localhost:4000/components/personalize/example-classes.html?color=0563C2
http://localhost:4000/components/personalize/example-classes.html

**Comment by tmcconechy** [comment]
@janahintal I think we should raise a new issue for this and not fail this one. As the issue is with the module tabs

http://localhost:4000/components/tabs-header/example-index.html

But i cannot reproduce it, when you raise a new issue can you add the browsers and the scroll bar mac setting your using? (I tried chrome mac with all settings and could not see the issue).

**Pull request merged**
