### PR TITLE
8584 - Fix avatar shape on hierarchy

### LINKED ISSUE #8584: Sinkpage: Hierarchy - Avatar issue - BETA 4.94
**Describe the bug**
There is an error in shape for Avatar, and the color doesn't correspond with the status/position.

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/
2. Scroll down to `Hierarchy` component
3. See error

**Expected behavior**
Avatar should be round and should match the color for each status/position.

**Version**

- ids-enterprise: Beta 4.94

**Screenshots**
image

**Platform**
 - Tested in Mac Chrome, Safari and Mac Edge.

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes the broken avatar shape introduced to the hierarchy component.

**Related github/jira issue (required)**:
Fixes #8584

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/hierarchy/example-stacked.html
- note that the avatars (green ones) are round again and centered

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — APPROVED** [review]
**Safari**
image

**Mac Firefox**
image

**Mac Chrome**
image

**Observation** @tmcconechy, seems the legend position is not consistent across browsers.
**Chrome/Edge**
image

**Safari/Firefox**
image

**Review by glenlieorillo — COMMENTED** [review]
The shape is now correct. However, the avatar doesn't follow the color based on the legend.

image

**Review by jbrcna — COMMENTED** [review]
the avatar is now correct. but the color is all green?
image
image

**Comment by tmcconechy** [comment]
good catch @jbrcna @glenlieorillo i fixed the issue with the color not changing

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]
great work!
image

firefox
image

edge
image

**Review by n-ace-ancog — APPROVED** [review]
Colors are now as expected.

image

**Review by janahintal — APPROVED** [review]
image

**Pull request merged**
