### PR TITLE
6686 - Searchfield visual bugfix

### LINKED ISSUE #6686: Tabs Module: Searchfield visual issues
**Describe the bug**
1. When the searchfield isn't focused, the height of the searchfield is smaller than the categories and go buttons.
2. When the window is resized smaller and then expanded, the Go button is cut off

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
3. Click on the searchfield to focus it
4. Click anywhere else on the page
5. Notice that the searchfield height is now smaller than the categories and go buttons
6. Resize the window small enough where the searchfield collapses
7. Expand the window with the maximize button
8. Notice that the Go button is cut off

**Expected behavior**
It is expected that the searchfield height remains the same height regardless of its focus, and the Go button should be fully visible when resizing the window.

**Version**
- ids-enterprise: v4.66.0-dev

**Screenshots**
searchfield visual issues

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 103.0.5060.134 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Adjusted border in searchfield so that height is even
- Added check for searchfield go button on changing buttonset width

**Related github/jira issue (required)**:

Closes #6686 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

On uneven searchfield height:
- Click on the searchfield to focus it
- Click anywhere else on the page

On cut off go button:
- Resize the window small enough where the searchfield collapses
- Expand the window with the maximize button

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Fix for build issue https://github.com/infor-design/enterprise/pull/6724 FYI

**Comment by tmcconechy** [comment]
Not sure if this is ready to review but seeing a few odd things.

1. on reduced width the buttons flow funny and the text is cut off (i think the example should use toolbar-flex to fix some of this)
Screen Shot 2022-08-10 at 10 17 01 AM
2. The focus state on the category button and go button isnt visible or shows a slight border change only
3. keep reloading the page and you see the search field move around (might also be fixed by changing to toolbar-flex in the example)

**Comment by s-werking** [comment]
Hi @tmcconechy,

Is it possible that this gets fixed without changing the sample to use toolbar-flex? This could be a possibility in the future, but right now it would be too close to our code cutoff to switch to a different component.

**Comment by tmcconechy** [comment]
I dont think so, maybe the shape of the search field might be ok without it but I doubt we can fix:

- the text getting cut off on the toolbar title
- the loading behavior
- and some width/resizing behavior (possible)

I would suggest we make the example look right with the new toolbar code and include the example with the old toolbar code (so include both) and get it mostly right but still may be toolbar issues with using the old toolbar

**Comment by s-werking** [comment]
Sounds good, thank you!

**Comment by tmcconechy** [comment]
@yohannahbautista UPDATE: I fixed this issue here on the PR, you may need to adjust some visual tests?
I also put the fix on 4.64 and 4.65 as this was time sensitive to finish today due DTO...

Thanks!

**Comment by yohannahbautista** [comment]
New PR here: https://github.com/infor-design/enterprise/pull/6824

**Pull request closed without merging**
