### PR TITLE
5611 - Accordion Mobile Enhancements

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will adjust spacing and hitboxes in accordion for mobile enhancements.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5611

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/accordion/example-accordion-panels.html
- Open `Developer Console`
- Inspect the `Spacing`
- Inspect  the `Hitboxes`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
Will fix the visual regression issues once this PR is approve.

**Review by ericangeles — CHANGES_REQUESTED** [review]
I would rather extend the `hitbox` setting in the button component so it has the option to use it or not. You can check this example page 

http://localhost:4000/components/button/example-button-with-hitbox.html

And make adjustments in the accordion component styling if it's needed. :) Let me know if you need help.

**Review by tmcconechy — COMMENTED** [review]
I think this would be ok. As long as it doesnt change the height from the old version https://main-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html we could keep the hitboxes in the component.

It makes for less settings. The only question i have is that the spacing on the left to the icon vs the spacing to the button doesnt look equal anymore (left and right side). I didnt check but does the design take this into account?

**Comment by tjamesallen15** [comment]
> I think this would be ok. As long as it doesnt change the height from the old version https://main-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html we could keep the hitboxes in the component.
> 
> It makes for less settings. The only question i have is that the spacing on the left to the icon vs the spacing to the button doesnt look equal anymore (left and right side). I didnt check but does the design take this into account?

The height is still okay and wasnt change. I did adjust the the buttons for spacing.

**Review by tmcconechy — APPROVED** [review]
Personally i think this looks good. For this case i dont think we need a specific setting as it can fit and that way less options to worry about 👍🏻 

If @ericangeles agrees we can just need the tests fixes

**Review by ericangeles — DISMISSED** [review]
Approving! Thanks, @tjamesallen15 !

**Comment by tjamesallen15** [comment]
Will do the visual regression in a while.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
