### PR TITLE
7962 - Fix "delete all" in firefox.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Implemented a workaround to allow for "Ctrl + A delete" or "Delete all" in Firefox.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7962

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/searchfield/example-buttons.html
- Type in the search field.
- Select all by pressing ctrl + A.
- Hit Backspace or Delete.
- Full text should be deleted.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tjamesallen15 — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]
Approving. great work!
Large GIF (960x480)

**Review by glenlieorillo — COMMENTED** [review]
The bug is already fixed. However, the heart button is changing position.

Steps to reproduce:

1. Type in any text in search field
2. Select by pressing cmd/ctrl + A
3. Hit Delete or Backspace
4. Click the page
5. Click the search field
6. Notice the heart button


https://github.com/infor-design/enterprise/assets/102151352/07039764-6af3-4572-ad41-3804f941ae15

**Review by ericangeles — CHANGES_REQUESTED** [review]
Functionality works well! 🍌 Great job @RJ-Csc. 

I'm seeing the same issue that @glenlieorillo mentioned. Could you also adjust the custom icon slightly to center it vertically?

**Review by janahintal — DISMISSED** [review]
Approving. 
https://www.loom.com/share/a6fd8dfa07e84db6a8b14a6448019d33

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I do see an issue if you type: 'test test test' and then select the middle test and backspace the cursor moves.

I think we want to figure out a fix where we dont actually do the backspace at let the browser do it? For example if key is 8 or 46 is it calling preventDefault()?

**Comment by max-hizon** [comment]
Not sure if this is within the scope but it doesn't work if you select all without using "Ctrl + A" if the text is not in the autocomplete selection


https://github.com/infor-design/enterprise/assets/79514236/0cc780ee-4cc8-4689-812d-29a7ce41833a

**Comment by jbrcna** [comment]
> Not sure if this is within the scope but it doesn't work if you select all without using "Ctrl + A" if the text is not in the autocomplete selection
> 
>  2023-09-28.14-10-15.mov

@max-hizon  try to update your local branch. to do that  check out this branch if you already have one then do " git pull" .

**Comment by max-hizon** [comment]
> > Not sure if this is within the scope but it doesn't work if you select all without using "Ctrl + A" if the text is not in the autocomplete selection
> > 2023-09-28.14-10-15.mov
> 
> @max-hizon try to update your local branch. to do that check out this branch if you already have one then do " git pull" .

It works now on my end. Thanks!

**Comment by tmcconechy** [comment]
I see a wierd thing. If you type `aaa<space><space><space>` -> it inserts `aaa.` 
I think handling the selection manually like this can be buggy. Did you see if there is a reason why it doesnt work. In the code without adding special handling for you @RJ-Csc ?

**Comment by RJ-Csc** [comment]
Hello @tmcconechy! The reason I decided to implement special handling for text selection and deletion in **Firefox** was due to how it seemed buggy in its current state going by: https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html, specifically with the caret jumping to the end when you press the the _shift_ or _backspace_ keys. How do you think I should proceed with this issue?

**Comment by tjamesallen15** [comment]
> Hello @tmcconechy! The reason I decided to implement special handling for text selection and deletion in **Firefox** was due to how it seemed buggy in its current state going by: https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html, specifically with the caret jumping to the end when you press the the _shift_ or _backspace_ keys. How do you think I should proceed with this issue?

Hello. I have a fix suggestion if you want. I can share how I approach it if things gets harder on your end.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Tim's issue still exists.

https://github.com/infor-design/enterprise/assets/102151352/ce8a4121-123d-45d3-b313-959f485cd56a

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The issue has been fixed. However, when the 'No results' text is clicked it became the searched text in the search field. (All major browsers)


https://github.com/infor-design/enterprise/assets/102151352/2f9b88c9-71aa-44b4-8054-179212dffa68

**Comment by tjamesallen15** [comment]
> The issue has been fixed. However, when the 'No results' text is clicked it became the searched text in the search field. (All major browsers)
> 
>  Screen.Recording.2023-10-02.at.9.16.03.PM.mov

Hello @glenlieorillo, you can approve this. The issue you mentioned above was fixed here.
https://github.com/infor-design/enterprise/pull/8007

**Review by tjamesallen15 — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/a2d16a77-3956-4788-ae31-f53a34aeeb90

**Review by janahintal — APPROVED** [review]
https://www.loom.com/share/5d4c69eda56344be8629bc6da2f1bd3b?sid=05ca5a53-b2cc-4a38-a504-2c30fa1a517b

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
Much better fix 👍🏻 Thanks!!!

**Pull request merged**
