### PR TITLE
6069 - Dropdown: Typing Capital Letters in an Open NoSearch Dropdown …

### LINKED ISSUE #6069: Dropdown: Typing capital letters in an open noSearch dropdown does not focus a value
**Describe the bug**
Typing a capital letter to select a value works when the dropdown is closed, but not when the dropdown is open. This happens on dropdowns with the noSearch option set to true.

**To Reproduce**
1. Go to http://localhost:4000/components/dropdown/example-no-search-lsf.html
2. Click on the top dropdown to open it
3. Type "T"
Expected Result: "T - Thor"  should be focused
Actual Result: The blank option is focused

**Expected behavior**
When a capital letter is typed in an open dropdown with noSearch turned on, the corresponding option should receive focus just as it would when the lowercase letter is typed.

**Version**
- ids-enterprise: v.4.60.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit)
Related Lawson JIRA Ticket: [LSF-50656](https://jira.lawson.com/browse/LSF-50656)

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

In Windows10, using Chrome, some users are reporting that upon initial open of the dropdown and then immediately pressing 'Shift + T', the T input is not focused/selected.

**Related github/jira issue (required)**:
Fixes #6069 

**Steps necessary to review your pull request (required)**:
Visit on Windows10 and Chrome http://localhost:4000/components/dropdown/example-no-search-lsf.html
Click the noSearch dropdown to open (the first/top one)
Press Shift + T
The T entry should be focused.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@s-werking look like its working to you?

**Review by tmcconechy — DISMISSED** [review]

**Comment by s-werking** [comment]
The only issue I see with this solution now is that the backspace and delete keys no longer focus the blank option when the dropdown is open.

**Comment by tmcconechy** [comment]
Backspace appears to work for me (but im mac). Also looking again at the fix seems like it would basically just prevent Ctrl key from doing anything? So not sure i even understand the fix.

Any other ideas for a fix?

**Comment by s-werking** [comment]
I checked on our product for the hotkeys that use the different control keys on open dropdowns and they still seems to work alright, this is more to prevent the control keys from showing up in the autocomplete search as a character.

The backspace and delete buttons are included in the list of control keys so that is why those don't function properly. The fix for the backspace/delete key on noSearch was put in handlePseudoElemKeydown() which is not hit in this scenario because the input is readonly (https://github.com/infor-design/enterprise/issues/5113).

 Having the backspace/delete key fix above additionally put into a place like handleKeyDown() where an open noSearch dropdown would hit and keeping the original fix that @davidcarlsonberg put in would hopefully fix the issue. We can have a call about this if it still doesn't make much sense, thanks!

**Comment by s-werking** [comment]
I added a section of code for when backspace or delete is pressed and the noSearch dropdown is open. Here's the patch for it:
[Add_backspace_delete_key_handler_for_noSearch_dropdowns_when_open.zip](https://github.com/infor-design/enterprise/files/8164699/Add_backspace_delete_key_handler_for_noSearch_dropdowns_when_open.zip)

I checked that this would not change the behavior for dropdowns that are not noSearch.

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
