### PR TITLE
7499 - Added z-index for empty filter wrapper

### LINKED ISSUE #7499: Datagrid: Not all of the Select All checkbox is clickable when filtering is enabled
**Describe the bug**
If the Select All checkbox is displayed and filtering is enabled you may not be able to click on all of the checkbox.

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/datagrid/test-change-show-select-all-checkbox.html'
2. Click on 'Toggle Select All'
3. Open the browser console and enter '$('#datagrid').data('datagrid').updated({ filterable: true })' to enable the filtering.
4. Personalize Columns the columns via the More button on the grid and display just the Product Id and Checked columns.

**Expected behavior**
All of the Select All checkbox should be clickable and hidden by the 'datagrid-filter-wrapper'.

**Version**
4.82.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Pathway
 - OS Version: Windows 11
 - Browser Name: chrome

**Additional context**

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added z-index for empty filter wrapper so that it won't overlap with checkbox.

**Related github/jira issue (required)**:

Closes #7499 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-change-show-select-all-checkbox.html
- Click on Toggle Filter
- Click on Toggle Select All
- In Personalize Columns, uncheck everything except Product ID and Checked
- Hover on lower half of Select All checkbox, should be able to click

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — DISMISSED** [review]

**Comment by marknolaninfor** [comment]
> Hi Team, the toggle is already working as expected in http://localhost:4000/components/datagrid/test-change-show-select-all-checkbox.html?theme=classic&mode=light&colors=ffffff however, there's some minor issue in classic mode for the search field as the icon is misaligned. image

The issue ticket has different steps, as it turns on the filters on the columns. This step is required as it alters the header and this is the issue that needs to be corrected.

Open the browser console and enter '$('#datagrid').data('datagrid').updated({ filterable: true })' to enable the filtering.

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Search icon alignment is already fixed. However, the close button becomes misaligned.

image

**Comment by yohannahbautista** [comment]
> Search icon alignment is already fixed. However, the close button becomes misaligned.
> 
> image

Hello, it looks to be fixed now
Screenshot 2023-06-29 at 2 13 54 PM

**Comment by ericangeles** [comment]
Please review it again @glenlieorillo @janahintal

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — APPROVED** [review]

**Pull request merged**
