### PR TITLE
1969 - Fixes a bug when using the datagrid filter row toggle function

### LINKED ISSUE #1969: Datagrid - toggle filter row breaks the UI
**Describe the bug**
When we use the datagrid toggle filter row feature, it breaks the UI - column titles are not visible

**To Reproduce**
1. run demo app
2. open DataGrid - Toolbar and Breadcrumb page
3. hit Toggle Filter Row button twice

**Expected behavior**
Column names should be visible

**Version**
- ids-enterprise-ng: 5.2.1

**Screenshots**
image

**Platform**
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

When switching the filter row on and off and then on again the text is misaligned. This addresses that. Also fixed a problem I spotted on the sort indicator on columns with no filtering.

**Related github/jira issue (required)**:
Fixes #1969 

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/datagrid/test-fixed-header-filter.html
- in the .. menu turn the filter row off
- in the .. menu turn the filter row on again
- everything should be aligned
- hover the columns to see the sort indicators are aligned
- test this on all 3 row heights in the ... menu

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
There's a bit of misalignment going on with the sort indicators when you compare left and right aligned column header text.  It's present on all sizes, but it's especially noticeable on the "Medium" row height setting:

Apr-18-2019-12_18-PM

**Comment by EdwardCoyle** [comment]
Tracked the misalignment down to [this](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/_datagrid.scss#L231)...

If you test the sort indicators in Firefox, the alignment is a lot better.  This seems to be an issue mostly in Chrome

**Comment by clepore** [comment]
I tried to fix up some of the header element containment issues and oddities, but it goes much deeper than I imagined. I went ahead and approved as is.

**Comment by janahintal** [comment]
Hi @clepore, I have tried testing http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html in different browsers and OS. Seems fine but when I test it in Windows10 IE11 and Edge, the header label is aligned Center and when hovered, it will switch position to top left which is different to other browser. 

May I know if this is expected in Windows Edge and IE11 browsers?
Please see image below.  

Edge: 
Screen Shot 2019-04-22 at 3 23 07 PM

IE11:
Screen Shot 2019-04-22 at 3 18 12 PM

**Pull request merged**
