### PR TITLE
7800 - Fix legend colors for selected days of week

### LINKED ISSUE #7800: Calendar: Day legend shading applied in Month view but not Week/Day views
When Calendar has a Day Legend it is applying background shading to "Weekend" days in Month view but not in Week view or Day view.  Note that background shading is being applied correctly to other types of days ("Public Holiday" days and "Other" days) in all views correctly.

1. Open a calendar that has a Day legend.
2. In "Month" view, observe that "Weekend" days are shaded correctly.
3. Switch to "Week" or "Day" view.
4. Observe that the "Weekend" days are not shaded.

**Expected behavior**
The "Weekend" days should also be shaded when in "Week" and "Day" views, just like they are in "Month" view.

**Version**
v4.80.0

**Screenshots**
Refer to attached file.
[Calendar day background.docx](https://github.com/infor-design/enterprise/files/12331626/Calendar.day.background.docx)

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - Device: Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome

 - Browser Version: 115.0.5790.171 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added week of days when setting legend colors in weekview

**Related github/jira issue (required)**:

Closes #7800 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/calendar/test-weekends-disable.html
- Weekendsshould be disabled
- Go to: http://localhost:4000/components/calendar/test-weekends-color.html
- Weekends should be ruby
- Check Week and Day view as well

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista this is good but i think two primary things are needed

1. Lets make it the same color as https://main-enterprise.demo.design.infor.com/components/monthview/test-disable-weekends.html its good you can change the color this way
2. But also the API on https://main-enterprise.demo.design.infor.com/components/monthview/test-disable-weekends.html is different so i think that should also be supported in calendar

```
disable: {
  dayOfWeek: [0, 6]
}
```

**Review by jbrcna — APPROVED** [review]
image
image
image

**Review by ericangeles — APPROVED** [review]

**Comment by tmcconechy** [comment]
@yohannahbautista see https://github.com/infor-design/enterprise/pull/7980#pullrequestreview-1642392775 again. I think i would expect

a) http://localhost:4000/components/calendar/test-event-custom-colors.html example but both weekends should be the same color
b) a second calendar example like https://main-enterprise.demo.design.infor.com/components/monthview/test-disable-weekends.html using the same API as that example

**Review by jbrcna — APPROVED** [review]
image
image

**Review by ericangeles — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
