### PR TITLE
1614 - Add disable row option to datagrid

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adding a feature that will disable row/s in Datagrid.

Fixed some possible bugs/issues:
- It shouldn't be checked/selected when toggle the Select All checkbox.
- It shouldn't count the disabled row/s when toggle the Select All checkbox.
- Disabled hover state.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/1614

**Steps necessary to review your pull request (required)**:

- Pull this branch
- Run http://localhost:4000/components/datagrid/example-disabled-rows.html

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles When do you plan on finishing this up? We freeze EOD friday. Thanks!

**Comment by ericangeles** [comment]
@tmcconechy @deep7102 , disable row function is now working. Will just fix some of the issues that @deep7102 mentioned.

**Comment by tmcconechy** [comment]
@deep7102 try another test i think i fixed all those

**Comment by EdwardCoyle** [comment]
Just one thing I saw - the description on this PR says that the hover state shouldn't be displayed on disabled rows, but I'm seeing it anyway:

Apr-30-2019-9_18-AM

Also, should it be possible to focus on cells that are inside disabled rows?  My hunch is that it shouldn't, but I'm not sure what the rules for accessibility on a datagrid would be here.

**Comment by tmcconechy** [comment]
I guess disabled is disabled so no hover or ability to click the row to focus. Not sure if we want to get into changing the keyboard to jump it though, seems like a lot of work.

**Comment by tmcconechy** [comment]
@EdwardCoyle i fixed the hover state but elected to allow the rows to be focused for the time being for keyboard

**Pull request merged**
