### PR TITLE
7293- Add alabaster design for tabs module

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the Alabaster design for the tabs module. Additionally, I have fixed some test pages in the datagrid and composite form.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7293

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to 
  - http://localhost:4000/components/tabs-module/example-index.html?colors=ffffff
  - http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=ffffff
  - http://localhost:4000/components/tabs-module/example-category-searchfield.html?colors=ffffff
  - http://localhost:4000/components/tabs-module/example-hidden-module-tabs.html?colors=ffffff
- Test every element states, color combination, etc.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks Good. I did wonder about some of the fixes in the files changed. Some seem irelevant? Is it all legit?

Also i see a double border on focus? Is that the design?
Screenshot 2023-05-23 at 10 11 19 AM

**Comment by ericangeles** [comment]
Yes, Tim, I just noticed that those example pages have errors when I stumbled upon them. So I fixed it.

**Comment by ericangeles** [comment]
The border focus has been there all along. Do you think we should revisit it with the design team?

**Comment by EdwardCoyle** [comment]
@ericangeles regarding the double border: It's always been present, but the issue is the padding between the Module Tab border and the focus state is bigger in some places... looks like even more padding on the sides of the first and last one.

Compare the size/padding with https://4700-enterprise.demo.design.infor.com/components/tabs-module/example-index.html#module-tabs-controls to it.  I think it might just need some extra padding removed, but not sure... IIRC the focus state box is drawn by JS here so hopefully nothing there to tweak.

**Comment by tmcconechy** [comment]
Did this even have a design @hey-yall ? @talkaboutdesign.
Not seeing it here https://jira.infor.com/browse/IDS-1054 https://jira.infor.com/browse/IDS-1010

**Comment by hey-yall** [comment]
> Did this even have a design @hey-yall ? @talkaboutdesign. Not seeing it here https://jira.infor.com/browse/IDS-1054 https://jira.infor.com/browse/IDS-1010

Hey Tim, these tasks are currently in progress with Lauren Steigerwald and requires a design work session to align strategy and design. Lauren, Alix, and I met this morning about it and are prioritizing Alabaster focus with Nunz very soon.

**Comment by tmcconechy** [comment]
ok @hey-yall can we make this a light grey? ask them if you dont mind or i can be looped in

**Comment by tmcconechy** [comment]
ok @ericangeles maybe we should not have started yet lets see if they can turn around a better design for it soon

**Comment by ericangeles** [comment]
Okay. Lets wait for the design. Parking this one.

**Comment by tmcconechy** [comment]
will close. this for now until thats done. i made a quick fix so its passable for now on another PR related

**Pull request closed without merging**
