### PR TITLE
5193 - Add ability to resize the app menu

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the ability to resize the application menu. You can activate it via settings, `resizable: true`.

With this implementation, the app menu will,
- always opened
- it has a minimum width of `300px` and cannot be resized below `300px`
- it should save the last position of app menu after reloading (via `this.settings.savePosition`)
- the behavior on smaller viewport should still be the same
- show ellipsis if texts were too long / also on a deep level menu
- tooltip should also work

Not sure about the style of the resizer. (Open for suggestions and changes)
Might add puppeteer test (once the https://github.com/infor-design/enterprise/pull/5501 merge)

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5193

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/applicationmenu/example-resizable-menu
- Drag the edge of the app menu
- Play it around by resizing (scale up, scale down)
- Combine with opening and closing the menu then do resize
- On smaller view when scaling down, the app menu should behave the same way (which will disappear on a certain viewport)
- Open all the level menu to show how it will look
- Ellipsis should work when the text is too long, and tooltip should display

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks really good so far.

1) can you add some longer menu items and deeper sections to the example so we can test how that works?
2) can you push the scrollbar over a few pixels so the black section isnt visible on the right of it?

Screen Shot 2021-08-10 at 9 55 33 AM

3) Can it be saved in local storage so when you reload it stays in the same position?

**Comment by deep7102** [comment]
@ericangeles this looks good,
only thing add api setting to toggle on/off the localstorage save

**Comment by tmcconechy** [comment]
Yeah agreed we should add the save or not as a setting

**Review by tmcconechy — DISMISSED** [review]
Looks great 👍🏻 
I guess that the scrollbar cant be all the way over covering the black or we run into the issue of it being hard to grab?

**Comment by ericangeles** [comment]
Yes, we can maybe add a bit of px to be able to grab it easily?

**Comment by tmcconechy** [comment]
Yeah or if the scrollbar can be up next with no dark on the rightside, maybe we can add some "invisible" part that lets you grab and drag. But the behavior is looking nicer to me now so willing to except the dark bit if its not fixable

**Comment by tmcconechy** [comment]
ok good for now - lets see what other reviewers think

**Review by deep7102 — DISMISSED** [review]

**Pull request merged**
