### PR TITLE
Misc - Merge preview release with new icons and alabaster default

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adding in the new icons and the change to make alabaster the default color on header controls. This can now be added and tested this month for roll out in Feb 4.82 release

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/8152
Fixes https://github.com/infor-design/enterprise/issues/8151
Fixes https://github.com/infor-design/enterprise/issues/8129
Fixes https://github.com/infor-design/enterprise/issues/7861

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/icons and test the new icons (done before but retest)
- Check that alabaster is default on header -> http://localhost:4000/components/header/example-index.html
- Check that alabaster is default on header Tabs -> http://localhost:4000/components/tabs-header/example-index.html
- Test colors on http://localhost:4000/components/personalize

All these were tested but should be tested once more for final inclusion, see history on the issues for more details

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
Are we merging now the alabaster default to main, @tmcconechy ?

**Comment by tmcconechy** [comment]
Yes we want new icons and alabaster as default now. For the 4.92 -> start of Feb. So ready to finally go in @ericangeles

**Review by janahintal — CHANGES_REQUESTED** [review]
Logos not visible in Classic
https://merge-preview-enterprise.demo.design.infor.com/components/icons/example-logos.html?theme=classic&mode=contrast&colors=default
https://merge-preview-enterprise.demo.design.infor.com/components/icons/example-logos.html?theme=classic&mode=dark&colors=default
https://merge-preview-enterprise.demo.design.infor.com/components/icons/example-logos.html?theme=classic&mode=light&colors=default 
image

Some text and icons are not visible in https://merge-preview-enterprise.demo.design.infor.com/components/personalize/example-form2.html?theme=new&mode=dark&colors=default
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Some text and icons are not visible.
image

More button is not visible in Alabaster.
image

image

All icons are unavailable.
image

No logos are displayed.
image

**Comment by tmcconechy** [comment]
@janahintal 

1. Not all icons are available in classic like the logos (this cant be fixed)
2. Fixed


@glenlieorillo 

Make sure to run `npm prune && npm i` on the localhost when testing or icons may be missing

1. Fixed
2. Could not reproduce try again (on localhost?)
3. Could not reproduce try again (on localhost?)
4. Could not reproduce on http://localhost:4000/components/icons/example-status-colors.html
5. http://localhost:4000/components/icons/example-logos.html

@ericangeles sure just need to get this approved/tested then its done. Not delaying anymore than that. hopefully this should be it

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected. Thanks, @tmcconechy!

image

image

image

image


https://github.com/infor-design/enterprise/assets/102151352/8cb6e08b-2c78-40a3-9ff4-99495e7a06ca


https://github.com/infor-design/enterprise/assets/102151352/8f68ad52-8bcb-4625-bd8f-75da44bc5a41


https://github.com/infor-design/enterprise/assets/102151352/2931336c-2ea2-47e3-aa86-b92fadd26764

image


https://github.com/infor-design/enterprise/assets/102151352/1b4bf5f6-587c-4d1b-aaaa-bfc9bb5d7226

image

image

image

image

image

image

image

image

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
