### PR TITLE
8141 - Datagrid Actional Mode Navigation

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix tab key navigation when using actionable mode when having editor and formatter.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8141
Closes https://github.com/infor-design/enterprise/issues/8245

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-datagrid-tab-navigation.html
- Click `Add Row`
- Click on the cell under column `Source Value`
- Press `1` and then press `Tab`
- it should go to the next column.
- Press `2` and then press `Tab`
- It should go to the next column.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Thanks looks like a good fix 👍🏻 One small addition i see the focus state is a little cut off on the bottom can we adjust it?

Screenshot 2023-12-14 at 10 32 36 AM

**Review by ericangeles — APPROVED** [review]
Looks good to me too! Also, please check the focus state alignment in classic mode as well. 👍🏼

**Review by jbrcna — APPROVED** [review]
image

**Review by janahintal — APPROVED** [review]
Now working as expected in New and Classic
https://8141-datagrid-actionalmode-nav-enterprise.demo.design.infor.com/components/datagrid/test-datagrid-tab-navigation.html 
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/ca0fb988-9367-4949-b4ab-4c14c56f0eb1

**Pull request merged**
