### PR TITLE
8870 - Datagrid Inline Editor SelectOnEdit

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix selecting issue on inline editor by adding `selectOnEdit` setting.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8870

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-editable-with-inline-editor.html
- Click the value inside the inline editor
- It should not be select on click

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Review by n-ace-ancog — DISMISSED** [review]
Working on my end.

https://github.com/user-attachments/assets/4fbb0f25-a444-4fa4-a689-d8f3cf2b4d3f

**Comment by tmcconechy** [comment]
@rcoseng can you test this?

I was thinking that selectOnEdit would focus all the text when you click in. Was this the idea? I think the behavior is correct now but maybe we need this to be the default a selectOnEdit selects all the text.

**Review by ericangeles — APPROVED** [review]
Looks good. I think this is a good way to provide options.

Can you add this to NG as well, @tjamesallen15 ?

**Review by jbrcna — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by rcoseng** [comment]
> @rcoseng can you test this?
> 
> I was thinking that selectOnEdit would focus all the text when you click in. Was this the idea? I think the behavior is correct now but maybe we need this to be the default a selectOnEdit selects all the text.

@tmcconechy Hi, yes that is the idea. selectOnEdit = true would focus all the text. I have also tested it and it looks good. Thanks!

**Pull request merged**
