### PR TITLE
NG1736 - Fixed alignment bug in chart on RTL

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated RTL style to fix chart being cut off

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1736

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/donut/example-legend.html?locale=ar-SA
- Chart should not be cut off

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — COMMENTED** [review]
The donut now fully visible, but noticed that the legend has little space compared to LTR version which makes the text wrapped

**RTL**
image

**LTR**
image

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**
image

**Safari**
image

**Mac Firefox**
image

**Mac Edge**
image

**BrowserStack: iPhone 15 Promax - Chrome**
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Legend is being cut off in RTL responsive view. 

**LTR**
image

**RTL**
image

**Review by tmcconechy — COMMENTED** [review]
@yohannahbautista Can we move it a little more to the right so that there is more space for labels? Approx.

Screenshot 2024-07-22 at 9 09 20 AM

**Review by jbrcna — DISMISSED** [review]
image

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista please see my comment about slightly adjusting it so that more text is visible

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
