### PR TITLE
8293 - RTL Datagrid Small Row Height

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix RTL alignment for color picker.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8293

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
- Change the row height to Extra Small
- Check alignments of the required icons on the activity column
- For extra steps visit the ticket issue

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by janahintal — CHANGES_REQUESTED** [review]
Filter and Sort icon is overlapping after playing around and resizing the columns. 
image

**Review by jbrcna — CHANGES_REQUESTED** [review]
focus state issue still exists
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Drag Icon and text are still overlapped in Mac Firefox.

https://8293-datagrid-srowheight-rtl-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light&colors=default

https://github.com/infor-design/enterprise/assets/102151352/52baa910-bf14-4b92-b46a-fd44c04b3641

image

**Review by tmcconechy — APPROVED** [review]
@tjamesallen15 
Approving for the required icon (original problem). If you want to fix up some of things QA finds that would be great. But we can timebox this and make new issues if its too much

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome** - Pass



https://github.com/infor-design/enterprise/assets/102151352/b8627100-a910-48b6-be0c-f830ac893ff1



image

**Mac Firefox**

- Approving for now.

_Note_: The bug still exists, drag icon and text are overlapped. Will create another issue for this bug.

https://github.com/infor-design/enterprise/assets/102151352/d8cde224-4e58-49a4-8609-d77f2500e09d

**Pull request merged**
