### PR TITLE
6918 - datagrid add row frozen column

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add an another test page in datagrid add row.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6918

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-addrow-with-frozen-columns
- Click on `Add Row`
- Enter a value for Product Name on the added row
- Click on the lookup icon for Product Id on the added row
- Choose a Product and Click Apply

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tjamesallen15** [comment]
@claudenbach @tmcconechy @ericangeles

**Review by tmcconechy — COMMENTED** [review]
@tjamesallen15 i dont see a fix - just a new example?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 i dont see a fix - just a new example?

I tagged you in my comment in the ticket. I can't reproduce this issue also that's why I just made the test page for it.

**Comment by tmcconechy** [comment]
Ok sorry missed that. Ok lets merge this then so @claudenbach can see. I cant reproduce any issue either in this example.

**Pull request merged**
