### PR TITLE
NG1594 - CAP/Modal Propagate and Compact

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add new settings `propagateStyle` and `compactPanel`.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1594

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/contextualactionpanel/test-propagate-compact.html
- Open `Developer Console`
- Check if modal body has classes `propagate-style` and `compact`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 I noticed that on:

http://localhost:4000/components/contextualactionpanel/test-propagate-compact.html

The padding is missing on top? Refer to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html

**Comment by tjamesallen15** [comment]
@tmcconechy under the request it says here, when using class `compactPanel`, it will add `compact` class that would have `padding: 0`
image

**Comment by tmcconechy** [comment]
@tjamesallen15 you think it would work if we just made the CAP blank so it doesnt seem misformatted? I think it would still serve the same purpose

**Review by janahintal — APPROVED** [review]
image

**Pull request merged**
