### PR TITLE
2335 - Fix that makes the theme switcher to reflect whats sent in the url params

### LINKED ISSUE #2335: Demo App: Add Uplift to the demo app theme switcher
**Is your feature request related to a problem? Please describe.**
Demo App: Add Uplift to the demo app theme switcher

**Describe the solution you'd like**
A menu with the colors, variant and theme

**Describe alternatives you've considered**
Not having it...

**Additional context**
Working on it exposed a couple minor bugs to fix as well added on the PR

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

#2335 was failed because when the url params are used the checkbox in the theme switcher were incorrect. This fixed that.

**Related github/jira issue (required)**:
Fixes #2335 
**Steps necessary to review your pull request (required)**:
- pull this and build normally
- go to a url with the parms such as http://localhost:4000/components/personalize/example-form.html?theme=soho&variant=contrast
- open the theme switcher in the top right and make sure the checkboxes are correct
- try different theme/variant combos

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
Is this meant to also integrate with colors? E.g., http://localhost:4000/components/personalize/example-form.html?theme=soho&variant=light&colors=#db7726 ?

**Comment by tmcconechy** [comment]
@davidcarlsonberg I thought it probably should so i made that work too. The only issue is if you change color and then theme it cant figure out to change the color to the other theme color since they are different so the check in that case wont show.

http://localhost:4000/components/personalize/example-form.html?theme=soho&variant=light&colors=56932e -> color should show in the menu

**Comment by tmcconechy** [comment]
Yeha maybe a hex is out of sync in the menu vs the code colors. Will check. Didnt spot that as its subtle

**Comment by tmcconechy** [comment]
That issue is now fixed @EdwardCoyle note that if you do change the url it may have the color from the other theme so you may need to reset the url in testing

**Pull request merged**
