### PR TITLE
Chore: Fix app menu buttons

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

I found the hover state on app menu buttons looked bad.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/8707

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/applicationmenu/example-filterable.html
- open app menu
- hover all buttons in it
- type in search and hover the x
- on http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html hover the buttons

### CODE REVIEW

**Review by n-ace-ancog — APPROVED** [review]
Just to confirm @tmcconechy no hover state for buttons in the app menu?

**Main**

https://github.com/infor-design/enterprise/assets/156752175/7e6e92c3-3649-4d19-a87f-53690826dbd9

**Current Branch**

https://github.com/infor-design/enterprise/assets/156752175/66162548-71c8-4fa6-b430-68799ee673ff

**Review by ericangeles — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://github.com/infor-design/enterprise/assets/102151352/d76e9f11-4de1-4779-982f-216ad08944d9

Failing in Classic Version.

image

https://github.com/infor-design/enterprise/assets/102151352/8051e76a-b372-4003-ae5a-bc8222fd9036

**Review by janahintal — CHANGES_REQUESTED** [review]
Hover state for 'x' button looks off in classic
image
image

There is no hover state for 'x' in the ff:

- https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html?theme=new&mode=dark&colors=default
- https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html?theme=new&mode=contrast&colors=default
-

**Comment by tmcconechy** [comment]
@n-ace-ancog no hover for X and caret icon based on old version

https://4880-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html

But there is one on https://4880-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html

Updated the steps to reflect the other example.

**Comment by tmcconechy** [comment]
@janahintal thanks! I fixed for classic mode. Woops forgot about it

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The clear button hover state in classic mode still looks off.

image

image

**Comment by tmcconechy** [comment]
@n-ace-ancog ok fixed that issue

**Review by n-ace-ancog — APPROVED** [review]
Working as expected:
**New**

https://github.com/infor-design/enterprise/assets/156752175/42454895-0f6b-40c4-9d82-a053925d5070

**Classic**

https://github.com/infor-design/enterprise/assets/156752175/3f23b1d6-5d77-411a-adb7-e89d34c100c3

**Review by ericangeles — APPROVED** [review]

**Review by janahintal — DISMISSED** [review]
Now working as expected
https://www.loom.com/share/f8f2e85d83f94faa8f2c25297be0a42b?sid=212ba6b3-21c8-48eb-bf3d-03d468377ba6

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html - PASSED


https://github.com/infor-design/enterprise/assets/102151352/8553bea5-53b6-469c-9d83-9749f029f2bc


https://github.com/infor-design/enterprise/assets/102151352/990ec3bc-4f9d-4ab1-bb97-e8ee04f985e9

https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html?theme=classic&mode=light&colors=default - Still failing on my end (Classic - Light and High Contrast Mode.)

image

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html - PASSED


https://github.com/infor-design/enterprise/assets/102151352/8553bea5-53b6-469c-9d83-9749f029f2bc


https://github.com/infor-design/enterprise/assets/102151352/990ec3bc-4f9d-4ab1-bb97-e8ee04f985e9

https://fix-app-menu-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html?theme=classic&mode=light&colors=default - Still failing on my end (Classic - Light and High Contrast Mode.)

image

image

**Comment by tmcconechy** [comment]
@jbrcna @glenlieorillo fixed that hover issue in classic. Try one last time (hopefully)

**Review by glenlieorillo — APPROVED** [review]
Working now as expected in Classic. Thanksss, @tmcconechy!

https://github.com/infor-design/enterprise/assets/102151352/c5f08f43-21ba-4422-8568-3f1851dece8b

**Review by jbrcna — APPROVED** [review]
the issue in classic is now fixed. 
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
