### PR TITLE
4086 - Fix datagrid multiselect checkboxes alignment in modal

### LINKED ISSUE #4086: Datagrid: Multiselect checkbox are misaligned in modal with 2 column grid
**Describe the bug**
Datagrid: Multiselect checkbox are misaligned in modal with 2 column grid

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-two-columns.html 
2. Open the Modal

**Expected behavior**
Multi select checkboxes should be aligned

**Version**
4.30.0

**Screenshots**
image

**Platform**
All Browser & OS

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed a bug where multiselect checkboxes were misaligned in a modal.

**Related github/jira issue (required)**:
closes #4086 

**Steps necessary to review your pull request (required)**:
- Pull and run branch
- go to http://localhost:4000/components/datagrid/test-modal-datagrid-two-columns.html
- Open modal and make sure the checkboxes are aligned

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@jmacaluso711 there is one similarish issue https://github.com/infor-design/enterprise/issues/4032 but i think it might be more complicated does this by any chance aslo fix that? Have a look if you can maybe?

**Comment by jmacaluso711** [comment]
@tmcconechy I think the baseline image needs to be updated for the visual regression test..
datagrid-modal-size-two-chrome-1200x800-dpr-1

**Comment by tmcconechy** [comment]
Looks good. Yeah i can tell its not from the two baselines being different. The problem is it stretches out to fill. Having seen a way to make it not stretch one column to fit. I might introduce a space column idea on another issue so you can skip #4032 if you dont find anything its not in the sprint for that reason. I just never tried setting the css like that so kind of hoped it would work :)

**Comment by jmacaluso711** [comment]
@tmcconechy yeah I think #4032 will take a bit more work. Grabbed it for next sprint

**Pull request merged**
