### PR TITLE
2686 - Fix memory leak with tabs

### LINKED ISSUE #2686: Tabs: Closing a tab causes a memory leak
**Describe the bug**
The tabs control has memory leaks when a tab is removed by clicking its X button. Details are below. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Open the Memory tab in Chrome Developer Tools
3. Click the 'Collect garbage' button to remove any clutter
4. Click the 'Take snapshot' button to get a comparison point of the memory heap
5. Click the '+' button to add a new tab
6. Click the 'X' button for that tab to close it
7. Click the 'Collect garbage' button again
8. Click the 'Take snapshot' button to get another memory heap.
9. While looking at "Snapshot 2" change the dropdown which says "All objects" to "Objects allocated between Snapshot 1 and Snapshot 2" (this will help you see what is hanging around in memory due to the new tab being added and removed)
10. Look at the results in the list to see what the tab left hanging around in memory. For example there is a Detached HTMLDivElement and HTMLAnchorElement (see items in screenshot below)

**Expected behavior**
The closed tab should not leave its DOM elements in memory. The below line of code in tabs.js is the culprit.

`
if (hasTargetPanel) {
  this.panels = this.panels.not(targetPanel);
}
this.anchors = this.anchors.not(targetAnchor);
`

This article describes how using variables and jQuery filters can cause big memory leaks due to the "prevObject" reference in jQuery objects - https://blog.yonatan.dev/jquery-prevobject-memory-leak/ - They recommend creating new references using the $() wrapper like this...

`
if (hasTargetPanel) {
  this.panels = $(this.panels.not(targetPanel));
}
this.anchors = $(this.anchors.not(targetAnchor));
`

**Version**
- ids-enterprise: v4.20.0

**Screenshots**
image

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 76.0.3809.100 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed memory leak issues with Tabs control after a tab removed.

**Related github/jira issue (required)**:
Closes #2686

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to http://localhost:4000/components/tabs/example-add-tab-button.html
- Open developer tools
- Click the `Memory` tab in developer tools
- Click the button `Collect garbage` (garbage bin icon) to remove any clutter
- Click the button `Take snapshot` to get a comparison point of the memory heap
- Click the button `+` on browser to add a new tab
- Click the button `x` on this new added tab to close it
- In developer tools, click the button `Collect garbage` (garbage bin icon) again
- Click the button `Take snapshot` to get another memory heap
- While selected `Snapshot 2` change the dropdown which says `All objects`
- From `All objects` to `Objects allocated between Snapshot 1 and Snapshot 2`
- Type `detached` in to textbox to filter the result
- It should not find any

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@tmcconechy I retested your steps against the latest cut of this branch and I'm no longer seeing the memory leak... although I'm not sure what changed?

Screen Shot 2019-08-29 at 4 29 17 PM

I'll approve this, but I'll leave it open for you to check over again.

**Comment by davidcarlsonberg** [comment]
For what it’s worth, I also was not able to reproduce the Tabs memory leak.

**Comment by deep7102** [comment]
@tmcconechy @EdwardCoyle @davidcarlsonberg 
Pushed some extra checks

**Comment by tmcconechy** [comment]
I cant reproduce it now either so either @deep7102 fixed or i made an error testing. Looks good

**Pull request merged**
