### PR TITLE
2023 - Colorpicker text cut off

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed an issue where the colorpicker text is cut off in extra small input field.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/2023

**Steps necessary to review your pull request (required)**:
- Pull this branch
- Run http://localhost:4000/components/colorpicker/example-sizes.html
- The text in `Extra Small` input field should be in ellipsis.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
The visual regression test for Colorpicker [doesn't seem to like the change](https://travis-ci.com/infor-design/enterprise/jobs/197944798#L975).  Might just be a matter of updating the baseline image for the test.

**Comment by EdwardCoyle** [comment]
@tmcconechy beat me to it :)

**Comment by tmcconechy** [comment]
@ericangeles mady you can fix this by selecting the text on focus (if its a readonly field). https://stackoverflow.com/questions/6847875/auto-highlight-an-input-field-on-focus

**Comment by tmcconechy** [comment]
@davidcarlsonberg is it just me or is your problem gone now? It seems to select all the text on focus suddenly?

**Comment by EdwardCoyle** [comment]
Definitely is still present in the current branch:

Screen Shot 2019-05-09 at 9 44 30 AM

I saw it in desktop Chrome.  To reproduce:
- Open the short colorpicker
- Choose a color whose name will bleed over (any of the Turquoise will do)
- After the color is selected, the text is cut off on the left side.

@davidcarlsonberg I'm not totally sure how we can fix this... any ideas?  Maybe programmatically set the text cursor to the beginning of the field?

**Comment by davidcarlsonberg** [comment]
I actually may have a fix in #1995. So maybe this is good to go and I address in that one. 
@tmcconechy @EdwardCoyle

**Comment by tmcconechy** [comment]
Approve again? i had to sort out the change log

**Pull request merged**
