### PR TITLE
841 - calendar features and related issues

### LINKED ISSUE #841: Remaining Calendar Features (Part Three)
**Remaining Current Design (Future Sprint)**
- [ ] adding events - on add button
- [ ] adding events - on double click
- [ ] editing events - on selecting
- [ ] showing more than one event in a day in the details
- [ ] mobile / responsive design
- [ ] drag times to extend / reduce them across days, Drag events to other days
- [ ] week view
- [ ] more docs and tests
- [ ] code sniffer scan
- [ ] in ar-SA locale the events are not showing, should map todays date when passed in the events.
- [ ] confirm keyboard on ar-SA - including the secondary picker.

**Added Nov/Oct Sprint**
- [x] upcoming events view
- [x] when no icon, the event should be left aligned
- [x] when selecting a day from the month switcher datepicker it doesn't go to that direct day..
- [x]  Right to left cleanup/retest
- [x] refactor showTodaysMonth to selectDay
- [x] comment back in the xit tests
- [x] keyboarding around on the calendar days
- [x] veracode scan

**Added Sept Sprint**
- [x] Ajax load events for a month
- [x] events for changing months
- [x] tooltip on ellipsis of event name
- [x] status (fx.. pending) on the event
- [x] notification banner
- [x] allow calendar items to span multiple dates
- [x] selecting events (with an event when selecting a day)
- [x] show readonly events details - when days are clicked

**Landmark Requirements:**
- [ ]   Keyboard navigation
- [ ]   notify by an event for show, add, update, delete 
- [x]  Allow display of calendar items to span dates and times.
- [x]  Allow a legend with a checkbox control to display/hide matching items
- [ ]   Allow click events on open areas and on calendar items: double click, right click (to open and show right click menu)
- [x]  Date navigator to go to the next/prev week, month, day.
- [ ]  Drag times to extend / reduce them, Drag events to other days
- [ ]   Need a way to tell calendar whether item is draggable or not.
- [ ]  Need an event on drop with "done" and "cancel" responses.
need to be able to cancel the drop from completing after drop event.
- [x]  Need an onSelection event
- [x]  Right to left compliant
- [x]  Other calendar support: Hijri, other?

**Optiva Requirements**
- [x]   Shared calendars
- [x]  Support for adding site level holidays
- [x]   UTC support
- [x]   We need support for importing and exporting calendar event data using a standard format (Wont do - should be implemented server side)
- [x]   The standard iCalendar (.ICS) format is supported by Outlook and Google Calendar for import from outlook. (Wont do - should be implemented server side)
- [ ]   Support for defining working days and working hours for groups of employees
    i.e. Monday through Friday. 7AM to 3PM

**ePathway Requirements**

- [ ]  View which days of the month are fully booked (i.e. all available times booked)
- [ ]  View which times in a day are booked
- [ ]  Ability to configure blocks/intervals of time (e.g. 15 minute blocks, 2 hour blocks etc.)
- [x]  Ability to configure starting (availability) date and final (availability) date. For example, a facility is available from the 1st of next month up until the end of the calendar year.
- [ ] Nice to have: If booking a facility (e.g. tennis courts), Google Maps integration to display/view the facility and other nearby facilities

**Other info**
This used to be SOHO-2182
Sprint Two Work was done on ticket https://github.com/infor-design/enterprise/issues/675

**Design**
[SoHo Calendar-UI-v1_050418_JN.pdf](https://github.com/infor-design/enterprise/files/2176670/SoHo.Calendar-UI-v1_050418_JN.pdf)

### LINKED ISSUE #1189: Datepicker - Bug in setToday on islamic calendar
**Describe the bug**

As found on the failing build https://travis-ci.com/infor-design/enterprise/jobs/157254117#L2399 there is a bug in the setToday function of the calendar. It stems from https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L1536 basically its not current to use a Date() type here and assume it will convert. We need to use arrays for islamic date because this is converting it back to Gregorian

**To Reproduce**
1. Has to be on a month with different number of days than the arabic calendar.
2. Call `$('#date-field-normal').data('datepicker').setToday()`
3. Notice the set date in the picker is wrong compared to https://www.staff.science.uu.nl/~gent0113/islam/ummalqura.htm

### LINKED ISSUE #1197: Datepicker - Issues with range picker, resetting the old values.
**Describe the bug**
There are some issues with date picker when using range picker.

**To Reproduce**
Bug One
1. Go to http://localhost:4000/components/datepicker/example-range.html
2. Click on the picker and select a range
3. Go back in the field
4. Clear the values
5. Open again 
6. Error: The picker should not be showing the old value

Bug Two
1. Go to http://localhost:4000/components/datepicker/example-range.html
2. Click on the picker and select a range
3. Go back in the field
4. Type a value in the field
5. Should not have to hit space in between in the mask
5. Open again 
6. Error: The picker should not be showing the old value

**Expected behavior**
Should reflect the value in the field. 

CC Lothar Blum

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Working on features to add to the calendar #841.
During the process moved keyboard code and verified it for related failing tests and umalqura calendar.
Did some cleanup work while testing the components effected (4 components on #1136)
Fixed the handling of Arabic to be more accurate and not fail on months with different numbers of days.
Moved keyboard logic

**Related github/jira issue (required)**:
Closes #841 
Closes #1189 
Closes #1197 

**Steps necessary to review your pull request (required)**:

841 -Calendar Features 
http://localhost:4000/components/calendar/example-index.html

- peep the events view on the right, clicking the events will select them in the page, it shows 14 days in advance (configurable)
- all text in the events are now left aligned
- selecting a day from the month switcher datepicker now goes to that direct day.
- RTL has been cleaned up http://localhost:4000/components/calendar/example-index.html?locale=ar-SA
- can now tab into the calendar and use arrow keys to keyboard around on the calendar days

1189 - Tests
These failing tests are now back in (were xitted) , they should pass

1197 - Range Bug
- Go to http://localhost:4000/components/datepicker/example-range.html
- Click on the picker and select a range
- Go back in the field
- Clear the values
- Open again

(note this was fixed because the keyboard stuff meant refactoring so had to verify this functionality)
(note 2 only 1 part is fixed the other part is a duplicate)

Impact
Do some testing on datepicker. Particularly Arabic and keyboard
Added many new tests.

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
I'm getting an error when running `npm run start` on your branch. Happens right after server starts running.
```
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1334:14)
    at listenInCluster (net.js:1382:12)
    at Server.listen (net.js:1469:7)
    at Function.listen (/Users/dberg2/Projects/enterprise/node_modules/express/lib/application.js:618:24)
```

**Comment by tmcconechy** [comment]
That probably just means you have the server running already on another terminal window?

**Comment by davidcarlsonberg** [comment]
Yup! Just saw that and was going top remove comment.

**Comment by tmcconechy** [comment]
Pushed fixes for
- clicking calendar on RTL
- non working date picker on calendar
- errors clicking cal on RTL
- funky RTL skip link

**Comment by tmcconechy** [comment]
Yes the arrow keys move the other way. Lets defer the keyboard on the secondary picker for later.

**Pull request merged**
