### PR TITLE
8404 - Tabs Module Spillover Alabaster

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix alabaster in tabs module.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8404
Closes https://github.com/infor-design/enterprise/issues/8298

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs-module/example-toolbar-with-spillover
- Check the UI

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jbrcna** [comment]
the issue still exists when you switch to alabaster

image

dark mode is ok.
image

**Review by tmcconechy — DISMISSED** [review]
Looks good to me

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
**RTL Issues**
https://8404-tabs-module-alabaster-default-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?locale=ar-SA

- The close button and label are overlapped.

image

- x button is not visible.

https://github.com/infor-design/enterprise/assets/102151352/79961694-8ed9-421c-a6cc-a2d6fe259c16

**Comment by jbrcna** [comment]
i don't see the x button overlapping in RTL. However, the x icon is on the right side in firefox
image

**Review by janahintal — CHANGES_REQUESTED** [review]
(+) sign button still invisible on light mode alabaster
image
Odd white box on tabs bar and no x icon on tabs in mobile version 
image

**Comment by tjamesallen15** [comment]
> **RTL Issues** https://8404-tabs-module-alabaster-default-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?locale=ar-SA
> 
> * The close button and label are overlapped.
> 
> image
> * x button is not visible.
> 
>  Screen.Recording.2024-02-21.at.11.09.21.AM.mov

The `New Tab Builder` tab is not a dismissible tab therefore it doesn't have a close button.

For the the overlap button and title, what suggestion to fixed this one? @tmcconechy @ericangeles

**Comment by glenlieorillo** [comment]
> https://8404-tabs-module-alabaster-default-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?locale=ar-SA

Hello @tjamesallen15,

I'm referring to the x button in the search bar.

**Steps to reproduce:**
1. Go to https://8404-tabs-module-alabaster-default-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?locale=ar-SA
2. Type any in search bar
3. Hover over on the left side of the search bar (_until the cursor will change to hand cursor_)


https://github.com/infor-design/enterprise/assets/102151352/cd239269-d964-4bde-80f5-43287f2af432

**Review by glenlieorillo — COMMENTED** [review]
- Missing tab border

https://8404-tabs-module-alabaster-default-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?locale=ar-SA#order-123456

image

_in LTR_:
image

**Review by janahintal — CHANGES_REQUESTED** [review]
No focus button on windows chrome dark mode when you hover on more actions beside the search bar.
image
Odd white box on tabs bar is still there and no x icon on tabs in mobile version
image
(+) sign is now more visible on light mode alabaster
image

**Review by janahintal — DISMISSED** [review]
Odd white box on tabs bar on mobile version has been fixed
image
Looks good on chrome. Approving. Thanks!
image

**Review by ericangeles — APPROVED** [review]

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
