### PR TITLE
229 - Added fix for dropdown control freezes upon selection in NG

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

The dropdown control freezes if the new form includes another dropdown in angular. 

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/229

**Steps necessary to review your pull request (required)**:

- Checkout this branch
- Download the attached zip file
[enterprise-ng-quickstart-master.-v2.zip](https://github.com/infor-design/enterprise/files/2732317/enterprise-ng-quickstart-master.-v2.zip)
- Run `npm install` then `npm serve`

To test if the fix in dropdown.js is working,

- Go to the NG project and open the file `sohoxi.js` in `node_modules/ids-enterprise/dist/js`
- Find the `closeList` function, then just add the fix in `dropdown.js`
- Or just change it in the Enterprise project and let it build
- Then copy the new file from dist in the Enterprise project to the `node_modules/ids-enterprise/dist/js` in the NG project.
- Then go to localhost:4200
- Select the 1st dropdown option "Alaska". This opens a sub-screen with a dropdown in it.
- Select the 2nd dropdown option "New York".
- Try the dropdown again, it should not freeze.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles This change seems to have broke some functionality on the colorpicker (as seen in the tests). Since it uses a dropdown there.

**Comment by ericangeles** [comment]
My commit in e2e test works on my local upon running the e2e:ci, then when i pushed it, it failed here in travis. 🤔

**Comment by ericangeles** [comment]
@tmcconechy we can probably close this one and I will create a new PR for this issue. It's a mess already.

**Comment by tmcconechy** [comment]
Sounds good - yeah lets start again

**Comment by ericangeles** [comment]
Yes. I will create a new branch too.

**Comment by resatz** [comment]
hi, im using ids-enterprise-ng 4.10.x.
facing same dropdrown frozen issue when i selected one option.
can anyone help me to solve this?
dropdown_issue

**Comment by tmcconechy** [comment]
@resatz you can see more infor on the corresponding issue https://github.com/infor-design/enterprise-ng/issues/229

I can see this was fixed in 4.15 / ng 5.1.0 or newer, so if you upgrade your version (suggest latest ) you will have this fixed

**Pull request closed without merging**
