### PR TITLE
8724 - Fix alert icon position in RTL

### LINKED ISSUE #8724: Listview: RTL alert icon overlapping text
**Describe the bug**
In Listview in RTL mode alert icon is overlapping text.
It was OK in v4.59.0
Issue [#5827](https://github.com/infor-design/enterprise/issues/5827) had similar issue.

**To Reproduce**

1. Go to [https://latest-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL](https://latest-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL)
2. See the red alert icon

**Expected behavior**
Alert icon should be aligned to the right in RTL

**Version**

- ids-enterprise v.4.95.0

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 124

**Additional context**
Thanks

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes overlap on the icon and text in RTL mode

**Related github/jira issue (required)**:
Fixes #8724 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/listview/example-status.html and notice the red text and icon is aligned ok
- try it on RTL http://localhost:4000/components/listview/example-status.html?locale=he-IL and should also be aligned now but flipped

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by n-ace-ancog** [comment]
For http://localhost:4000/components/listview/example-status.html?locale=he-IL, its now working properly.

image

Upon checking other example, I found this @tmcconechy in http://localhost:4000/components/listview/example-paging-clientside.html?locale=he-IL

image

**Review by glenlieorillo — COMMENTED** [review]
Working now as expected.

https://8724-fix-rtl-enterprise.demo.design.infor.com/components/listview/example-status.html

https://github.com/infor-design/enterprise/assets/102151352/a43b0677-8de6-4f2a-8401-81402806c771

https://8724-fix-rtl-enterprise.demo.design.infor.com/components/listview/example-status.html?locale=he-IL

https://github.com/infor-design/enterprise/assets/102151352/ac97ab87-8237-4751-a791-c65323c07ed4


https://github.com/infor-design/enterprise/assets/102151352/9f56dd9e-ada9-4a5c-89be-3dbbcd2ba94c

However, I also tested the other examples under `List View` and found the following bugs:

- Icons are overlapping
- Hover overflows outside the searchfield

https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html?locale=ar-SA

image


https://github.com/infor-design/enterprise/assets/102151352/0dfaebd6-f718-4847-bd0f-4d55669b6e47

- button/text looks off

https://main-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html?locale=ar-SA


https://github.com/infor-design/enterprise/assets/102151352/3d75e4c8-52b3-4012-a71e-f7935b25aecc

cc @tmcconechy

**Review by jbrcna — CHANGES_REQUESTED** [review]
this is now working in chrome but failed in firefox
image

**Comment by tmcconechy** [comment]
@n-ace-ancog @jbrcna @glenlieorillo 

thank you! I fixed the issues you found.

**Comment by jbrcna** [comment]
thanks @tmcconechy 
the red dot is still misaligned in firefox. 
image

**Comment by n-ace-ancog** [comment]
Now looks good on http://localhost:4000/components/listview/example-paging-clientside.html?locale=he-IL

image

Regarding the issue raised by @glenlieorillo on https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html?locale=ar-SA seems like its still happening. Type a text on the text box and the clear button will be displayed outside the text box
image

Also, when hovering the the + button it overlaps on the cards border.
image

**Comment by tmcconechy** [comment]
@n-ace-ancog fixed the X i missed that. Thanks!

**Review by n-ace-ancog — APPROVED** [review]
Now looks good on my side!

image

image

image

**Firefox**
image

image

**Comment by jbrcna** [comment]
the firefox issue still exists on my end. 
image
image

**Review by ericangeles — APPROVED** [review]
Looks good on all major browsers. Thanks, @tmcconechy!

**Pull request merged**
