### PR TITLE
8362 - Adjust top and bottom padding on home pages

### LINKED ISSUE #8362: Homepage: No bottom margin in layout?
This is more of a question if this is by design or not. It's been like this for a long time, but I'm pretty sure there was a margin at some time (a long time back)?

**Describe the Issue**
The homepage does not have any bottom margin, causing widgets to look a bit cut. Their bottom border/box shadow isn't shown. Might look better with some kind of margin/gap between last row of widgets and the end of the page?

**To Reproduce**
1. https://main-enterprise.demo.design.infor.com/components/homepage/example-four-column.html
2. Scroll to bottom

- ids-enterprise: 4.91.0-dev.0

**Screenshots**
image

**Platform**
 - Team: OS Portal

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed the top and bottom padding of the homepage component so there is a 16px gap on top and bottom. Had to use JS to do this. If someone has a better idea do let me know (was tricky due to position absolute elements).

**Related github/jira issue (required)**:
Fixes #8362 

**Steps necessary to review your pull request (required)**:
- check pages in http://localhost:4000/components/homepage
- like for example http://localhost:4000/components/homepage/example-four-column.html
- there should be a 16px gutter on top and bottom of the widgets in the home page
- smoke test http://localhost:4000/components/tabs-vertical/example-index.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — COMMENTED** [review]
image

image

**Review by janahintal — CHANGES_REQUESTED** [review]
image
image


**Observation:** 
There is a white padding at the bottom of the page. 
Environment: Win10 Chrome

https://widget-gutters-enterprise.demo.design.infor.com/components/homepage/example-index.html
https://widget-gutters-enterprise.demo.design.infor.com/components/homepage/example-filled.html
https://widget-gutters-enterprise.demo.design.infor.com/components/homepage/example-monthviews.html


image

**Comment by tmcconechy** [comment]
@janahintal had to change this. Now i made it so the gap is fixed but i cannot guarantee the bottom padding depending on page size. So ignore that point. But for now padding is 16px on top but the bottom can vary depending on widgets in use and screen size.

Can possibly circle back on this.

**Review by tjamesallen15 — APPROVED** [review]

**Review by janahintal — APPROVED** [review]
Approving. Thanks!
image
image
image

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/c4b02f4a-f965-4986-b307-02f1528ad982

image


image

**Pull request merged**
