### PR TITLE
8105 - Dropdown Empty Icon

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug where list is broken when empty icon is in the first option.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8105

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/dropdown/test-icons-color.html
- Open the dropdown, see no errors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/e99e96ae-4897-4e4d-9848-89013befdd21

**Comment by anhallbe** [comment]
@tjamesallen15 this causes a crash and the dropdown control to stop working in some scenarios:

image

This line crashes:

image

**Comment by ericangeles** [comment]
Can you check, @tjamesallen15 ?

**Comment by tmcconechy** [comment]
@tjamesallen15 was raised as a new issue https://github.com/infor-design/enterprise/issues/8353 thanks !

**Pull request merged**
