### PR TITLE
281 - Add new empty message design in modal

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Provided a new design for error empty message inside of modal. This design will probably use for error pages like HTTP 500 or HTTP 400.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/design-system/issues/281

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Navigate to http://localhost:4000/components/emptymessage/example-modal-empty-message.html
- Click `Modal Empty State Message` button
- You'll see an error empty message design

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@ericangeles this is looking pretty good but a couple suggestions.

- i was thinking this would be a new component in components folder called "error-page" but it doesnt seem to be logically a emptymessage 
- in an example there (example-index) just show the page with the error on it we dont need to animate in a modal the page should be static
- so presumably this can be all css component
- i don't think we should add a new primary button style (different colors and radius 8px) - so just use the normal primary button and not introduce any new styles
- im also getting a scroll bar on the dialog 
- icons seem a bit large we reduced this on another ticket... may want to tweak that a bit.

**Comment by ericangeles** [comment]
> @ericangeles this is looking pretty good but a couple suggestions.
> 
> * i was thinking this would be a new component in components folder called "error-page" but it doesnt seem to be logically a emptymessage
> * in an example there (example-index) just show the page with the error on it we dont need to animate in a modal the page should be static
> * so presumably this can be all css component
> * i don't think we should add a new primary button style (different colors and radius 8px) - so just use the normal primary button and not introduce any new styles
> * im also getting a scroll bar on the dialog
> * icons seem a bit large we reduced this on another ticket... may want to tweak that a bit.

This is all noted, @tmcconechy ! Thank you.

I was following the design that was provided, but yeah, will work this tomorrow. This is a big help! :) I wasn't 100% sure at first where to put this design so I come up putting in the empty message. I'll overhaul the whole design and code.

**Comment by ericangeles** [comment]
@tmcconechy maybe a new PR will do?

**Comment by tmcconechy** [comment]
Yeah i think the main thing we cant change the consistency of the buttons so we fit that into our system was probably a mistake in the design

**Comment by ericangeles** [comment]
Gotcha. Will close this now.

**Comment by tmcconechy** [comment]
ok look forward to the next one.

**Pull request closed without merging**
