### PR TITLE
2907 - Alignment checkbox and uplift fixes [v.4.22.x]

### LINKED ISSUE #2907: Checkbox: New global uplift rule causes alignment issues
**Describe the bug**

A recent change https://github.com/infor-design/enterprise/pull/2872/files#diff-4e8ca57486af317304770962b8ed1fc9R68 introduced an issue on our checkboxes.

**To Reproduce**
1. Go to http://localhost:4000/components/form/test-compound-checkboxes-alignment.html and see alignment issues
1. Go to http://localhost:4000/components/calendar/example-index.html?theme=uplift&variant=light&colors=0563C2
2. In the + menu select add event (modal)
3. Remove the rule https://github.com/infor-design/enterprise/pull/2872/files#diff-4e8ca57486af317304770962b8ed1fc9R68 since its not adquetly scoped.
4. Rest test this form and find a new alignment fix - does seem ok.

**Expected behavior**

**Version**
- ids-enterprise: [v4.22.0 beta]

**Platform**
 - Any (Chrome)

**Additional context**
The bigger problem for Landmark is we use a form layout on our checkboxes and this rule was scoped to all checkboxes. Will provide a form test example to follow. While Tim reworks the fix.

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

A recent PR added un-needed global checkbox top margins. Removed this and added a different fix. Also fixed a few other layout issues in the calendar and adjusted the font size down.

**Related github/jira issue (required)**:
Fixes #2907 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/form/test-compound-checkboxes-alignment.html
- checkbox should be inline with the input
- test the same page in uplift http://localhost:4000/components/form/test-compound-checkboxes-alignment.html?theme=uplift
- go to http://localhost:4000/components/form/example-inputs and the checkbox in the second compound field should be aligned
- should also do this in uplift http://localhost:4000/components/form/example-inputs.html?theme=uplift
- go to http://localhost:4000/components/calendar/example-index.html and in the + menu select Add Event (modal) and the dialog should look nice.
- should also look good in uplift 
http://localhost:4000/components/calendar/example-index.html?theme=uplift
- go to http://localhost:4000/components/form/test-checkbox-in-columns and the checkbox in the second compound field should be aligned
- should also look good in uplift 
http://localhost:4000/components/form/test-checkbox-in-columns?theme=uplift
- check spacing under http://localhost:4000/components/checkboxes/example-index.html between checkboxes

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Looks good!
just see on mobile view, top spacing need to be adjusted
http://localhost:4000/components/form/test-compound-checkboxes-alignment.html
http://localhost:4000/components/form/test-checkbox-in-columns

**Comment by tmcconechy** [comment]
@deep7102 and @EdwardCoyle please have another test now. fixed the responsive issues

**Comment by EdwardCoyle** [comment]
Definitely seems like the responsive problems are fixed, but the visual regression tests that are now failing are legit:

Compare 
- http://master-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?layout=nofrills
- http://localhost:4000/components/checkboxes/example-index.html?layout=nofrills

...and
- http://master-enterprise.demo.design.infor.com/components/checkboxes/example-checkbox-groups?layout=nofrills
- http://localhost:4000/components/checkboxes/example-checkbox-groups?layout=nofrills

These others are just in need of a baseline update once the two above are resolved:
- http://localhost:4000/components/form/test-compound-checkboxes-alignment?layout=nofrills
- http://localhost:4000/components/form/test-checkbox-in-columns?layout=nofrills

**Comment by tmcconechy** [comment]
Ok @EdwardCoyle @deep7102 - third try 👍

**Pull request merged**
