### PR TITLE
8430 - Toolbar Flex More Button

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix more button throwing error when click two times.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8430
Closes https://github.com/infor-design/enterprise/issues/8564

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-flex-toolbar.html
- Open `Developer Console`
- Click the more button, then click the more button again.
- Should see no errors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@tjamesallen15 something really badly wrong with the datagrid last column and toolbar. It may not be on this PR tho.

Compare:
http://localhost:4000/components/datagrid/example-editable.html
to:
https://4880-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

I see it on http://localhost:4000/components/datagrid/test-flex-toolbar.html with the toolbar.

any suggestions cc @ericangeles

**Comment by tjamesallen15** [comment]
I switched on to the main branch and the bug persist there, @tmcconechy

**Comment by tjamesallen15** [comment]
I saw the bug, its not related with this toolbar flex. It came from here.
image

It came from this PR.
https://github.com/infor-design/enterprise/pull/8126

I'll just handle it in this PR to fix it.
@tmcconechy  @ericangeles

**Comment by tmcconechy** [comment]
Thanks @tjamesallen15 yeah seems like an important regression we should fix ASAP

**Comment by tjamesallen15** [comment]
I handled it already in my latest push. @tmcconechy

**Comment by ericangeles** [comment]
One thing I've noticed about the toolbar flex in the datagrid is that it's too close to the datagrid.

Compare:

https://8430-toolbar-flex-more-button-bug-enterprise.demo.design.infor.com/components/datagrid/test-flex-toolbar.html

 to 

https://8430-toolbar-flex-more-button-bug-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — DISMISSED** [review]
Same fix that's on my mind. @tmcconechy

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.
Animation

**Review by tmcconechy — DISMISSED** [review]

**Pull request merged**
