### PR TITLE
7373 - Weekview agenda variant

### LINKED ISSUE #7373: IDSWeekview: Agenda variant
**Is your feature request related to a problem or use case? Please describe.**
This is a request for a variant of the IDS Weekview, which we will call the "Agenda View". It's a request from the WFM team for use in their homepage widget. 

**Describe the solution you'd like**
Scoped out here: https://inforonline.sharepoint.com/:w:/s/InforDesign/EdzNr6a9ZwdBtdAOPxeQcOAB6-xIpCzZHdWOd4PjulUvbg 
"A week-long calendar view that shows events for each day"
Design and more here: https://www.figma.com/file/0S0CmLnhegSnAOBulgvSD3/Nurse-Homepage-Designs?node-id=3977%3A112302&t=3iHxvWEXjG7oP7r1-0 

**Additional context**
Reach out to Andy for any additional information or context!

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added stacked view layout for weekview agenda variant.
Added settings for `stacked` and `showFooter`.
Added breakpoint listener to switch stacked view to one day view in phone-to-tablet widths.

**Related github/jira issue (required)**:
Closes #7373 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm install`, `npm run start`
2. Go to [stacked example](http://localhost:4000/components/week-view/example-stacked.html)
3. Check that design matches [figma](https://www.figma.com/file/BVwSQAZwE8m1swXPNw93kh/Calendar-Enhancement?type=design&node-id=0-1&t=N8POS7ZictwKHLOr-0)
4. Check that vertical scrolling works and that header/footer remain sticky
5. Check that weekview switches to one day view for mobile widths
6. Check that footer is toggleable by setting `showFooter` settings to true/false
7. Check different themes
8. Check different languages
9. Check that calendar component is unaffected by changes and still works as expected
10. Check http://localhost:4000/components/week-view/example-card.html -> for in a card

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — APPROVED** [review]
@jdilag90 this looks fantastic, well done

**Review by tmcconechy — DISMISSED** [review]
Looks Good. Thanks @jdilag I cant find any issues or anything missed.

@CindyMercadoReyes Ready for QA

**Comment by tmcconechy** [comment]
@talkaboutdesign @inforandy @hey-yall - do you guys want to review this one from a design side.

The page can be viewed here: https://7373-weekview-agenda-enterprise.demo.design.infor.com/components/week-view/example-stacked.html

Just add any comments here on this PR

**Comment by jbrcna** [comment]
when you use arrow keys for the first time in `week-view-datepicker-trigger`hte hightlight jumps to incorrect date.
steps.
1. go to http://localhost:4000/components/week-view/example-stacked.html
2. click calendar icon press arrow keys (i.e., right arrow key)
3. notice that the highlight jumps to the incorrect date instead of subsequent/succeeding date.
4. try also other arrow keys.

**clear button not working**
steps
1. go to http://localhost:4000/components/week-view/example-stacked.html
2. click calendar icon
3. click right arrow button to go to next month
4. click clear button
5. see issue

**today button is a bit closer to the calendar icon in safari browser**
image


monthyear-pane  is a bit off in dark mode
image

**Comment by tmcconechy** [comment]
cc @jdilag ☝🏻

**Comment by talkaboutdesign** [comment]
Yes, I need to review. Don't push until I approve.  P.S. I need to see this inside a widget card thats a 2x1 size. Since that is going to be a primary place this is going to live inside of.

**Comment by jdilag90** [comment]
@talkaboutdesign @tmcconechy added an example page for stacked weekview in a card. Below is a preview. 
Not sure when the public pr link will be available, but here's the local one (http://localhost:4000/components/week-view/example-card.html)

weekview-card

**Comment by talkaboutdesign** [comment]
The responsive mobile view seems to still have all the lines. and time indicators. Also not seeing cards when resizing down. 

CleanShot 2023-05-11 at 08 17 42@2x

**Comment by tmcconechy** [comment]
yeah your right @jdilag90 I see the design is like that. But i guess i could expect the mobile view to be stacked with no times like the main view. @talkaboutdesign ?

**Comment by jbrcna** [comment]
the issues mention [here](https://github.com/infor-design/enterprise/pull/7488#issuecomment-1540420606) were now fixed.
Also, the lines and time indicators in responsive mobile view is now removed. Cards are also displayed.
image

I wasn't sure if this is a bug but just noting for reference. 
> **today button is a bit closer to the calendar icon in safari browser** 
- In firefox calendar icon is a bit more on top.
image

- today is cut off in 320 width
image

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
