### PR TITLE
8367 - Graph Many Records

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix an error encountered when having many records inside the graph.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8367

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/pie/test-many-records.html
- Open `Developer Console`
- See no errors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — COMMENTED** [review]
this is working as expected. However, when I try to select each pie item an error occurred.
image
image

**Comment by tjamesallen15** [comment]
This is still WIP (Work In Progress) @jbrcna

**Review by tmcconechy — DISMISSED** [review]
Looks very good 👍🏻

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Issue still exists after selecting on Pie Chart. 


On first load:
image


After selecting on Pie Chart: 
image

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**


https://github.com/infor-design/enterprise/assets/102151352/4db0f13d-489e-4480-b344-ece49eed6a33

**Mac Firefox**


https://github.com/infor-design/enterprise/assets/102151352/935e36fa-6449-49bd-97e5-eeb16724e40f

**Comment by ericangeles** [comment]
@tjamesallen15, I am seeing the error as well. Click a slice, then click it again to deselect, you will see the error.

**Review by ericangeles — APPROVED** [review]
Looks good now!

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
just noting an intermittent issue. happens when you click (2 times) each slice. 
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/593a45d8-71c5-43c5-9549-e9a16649db9d

**Comment by ericangeles** [comment]
@jbrcna, I don't see it. Could you please provide a concrete steps to reproduce it?

**Comment by tmcconechy** [comment]
This seemed done.

**Comment by jbrcna** [comment]
> @jbrcna, I don't see it. Could you please provide a concrete steps to reproduce it?

I just click each slice twice. more like toggling it.

**Pull request merged**
