### PR TITLE
3482 - Fix dropdown position when the field is required inside of modal

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes dropdown list position when opening and if the field is required inside of modal. It also includes the datepicker issue when the list will be on top.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/3482

**Steps necessary to review your pull request (required)**:
- Pull this branch, run, and build the app
- Navigate to http://localhost:4000/components/modal/example-validation.html
- Tab all fields
- Open the dropdown field
- It should not overlap the `Type` label
- Also test the http://localhost:4000/components/datepicker/example-timeformat.html
- Resize the browser to 1408x870
- Open the second field datepicker
- Click the hours dropdown
- Dropdown list should stay on it's position

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Still seeing the issue but i think the fix area is on the right track.

**Comment by ericangeles** [comment]
@tmcconechy, I suspected that the modal causes the misalignment. I tried typing in the dropdown and it goes back to it's position. Same goes when deleting the text after searching. I pushed some changes but still it has a bug. Still figuring out some solution.

**Comment by tmcconechy** [comment]
Ok, let me know if your stuck and i can have a look too @ericangeles

**Comment by tmcconechy** [comment]
Need help with this @ericangeles or figured it out?

**Comment by ericangeles** [comment]
> Need help with this @ericangeles or figured it out?

For sure, @tmcconechy. I've pushed some changes. You can check it out.

**Comment by tmcconechy** [comment]
@ericangeles was testing this out and i found the issue. the validation is hiding the message and it makes the form move. I'm going to make a new PR with part of yours and a fix as i saw. Coming shortly....

**Comment by ericangeles** [comment]
@tmcconechy got it! My first fix before was to retain the validation text so that the modal doesn't shrink. That causes the dropdown to misaligned.

**Pull request closed without merging**
