### PR TITLE
6978 - Header Default White

### LINKED ISSUE #6978: Header: Add White Background (Default)
**Is your feature request related to a problem or use case? Please describe.**
Add the ability to add a white header and make it the default. 

**Describe the solution you'd like**
- Make white the default on https://main-enterprise.demo.design.infor.com/components/header/example-index.html
- All colors still possible in the .. menu

**Additional context**
Will need to go in WC as well.

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Changes in header colors to make the white background as default

Note: 
 - Will update baseline images in tests once changes are okay
 - No changes in tab, will wait for another PR to merge to avoid conflict

**Related github/jira issue (required)**:

Closes #6978 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to the following pages listed below, should follow the figma: https://www.figma.com/file/OPdYJhMBg9HFxGD6K9ZLZo/Header?node-id=1476%3A14373&t=2t2iyQL5uJ30w2qo-0

Header:
http://localhost:4000/components/header/example-index.html

Breadcrumbs
http://localhost:4000/components/header/example-breadcrumbs.html

Tabs (No changes in tab, will wait for another PR to merge to avoid conflict)
http://localhost:4000/components/header/example-tabs.html

With search field and icons:
http://localhost:4000/components/header/example-flex-toolbar.html

Searchfield full:
http://localhost:4000/components/header/example-searchfield-full.html

Wizard
http://localhost:4000/components/header/example-wizard.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Good Start just noticed the following

- try changing color in the color menu on http://localhost:4000/components/header/example-index.html?colors=1F9254
- notice the buttons and hover them and click on the search 
- in color mode it should still work similar to before. I think its ok if the button shapes stay the same though. Just need to fix the colors so its closer to how it works before

http://localhost:4000/components/header/example-breadcrumbs.html
- just has an extra | in it that looks like a  mistake

http://localhost:4000/components/header/example-tabs.html
- tab changes is covered on a separate issue but @tjamesallen15 should probably not this test page - looks good for the header alone

http://localhost:4000/components/header/example-flex-toolbar.html 
- try making a disabled button in the toolbar and notice it is invisible (i set one on this page to disabled)

- in general i think the menu needs to pop down a bit more with the new size of buttons

Screen Shot 2022-12-09 at 2 23 54 PM

**Comment by ericangeles** [comment]
@yohannahbautista looks like you also changed the tabs. Can you leave it as it was? It might conflict with @tjamesallen15 PR on tabs.

Also, it looks like the two borders overlap each other in the search field when focused.

Screen Shot 2022-12-14 at 5 15 37 PM

As per the design, it should look like this

Screen Shot 2022-12-14 at 5 18 47 PM

Other than that looks good!

**Comment by tmcconechy** [comment]
I tested again and these are my comments

1) the focus state on the search. Not sure if it works i will check with desgn but its cut off on top. Also try it in some of the colors. Looks good but the border is cut off on top
2) the animation ripple effect -> need to check on this with design but it doesnt look right especially in color mode

But try dark mode -> this should look as before colors seem incorrect
For high contrast mode -> this should look as light mode but with the darker color

Tests should be
- dark mode / contrast mode / classic mode -> colors should be as before shapes can change
- color modes -> should be same as before except the default is now "white" i.e. again colors same but the shapes can change

**Review by tmcconechy — COMMENTED** [review]
Nice work 👍🏻  The only remaining things i see are:

1) try to focus the button on the header in a colored mode like amber and see it is the wrong color. I think it should be white or opacity of white in that mode. its showing azure in it (only for colored headers)

Screen Shot 2022-12-16 at 12 55 36 PM


2) For the animation on the button try only animating background-color and color. I think the border or box-shadow part is making it look wierd on hover. Try hovering the .. button to see:

Screen Shot 2022-12-15 at 10 36 34 AM

~3) the search field focus state is reverted but its now missing the box shadow it had before https://main-enterprise.demo.design.infor.com/components/searchfield/example-index.html~

4) i noticed the arrow keys are not working so cannot use the keyboard on the header (might have broken before). Not able to tab to the hamburger menu and than use arrow left up to get across the header

**Comment by tmcconechy** [comment]
Checking again 3/4 fixed - noticed the keyboard doesnt work too

**Comment by yohannahbautista** [comment]
> i noticed the arrow keys are not working so cannot use the keyboard on the header (might have broken before). Not able to tab to the hamburger menu and than use arrow left up to get across the header

> Checking again 3/4 fixed - noticed the keyboard doesnt work too

@tmcconechy @ericangeles 
Hello, what should arrow keys do in header? I'm not sure what other key events should exist besides the focus tab and enter

**Comment by ericangeles** [comment]
@yohannahbautista arrows should be able to use when moving to other components with combination of tabbing.

**Comment by tmcconechy** [comment]
1. Still seeing wierd focus states on http://localhost:4000/components/header/example-index.html?colors=BB5500
2. Still seeing a wierd animation on hover -> i think it should just fade in the color (but minor)
3. And the keyboard. For that you should test as follow:

- tab into the header
- next tab goes out of the header
- once in focus on a button in the header left and right arrows should move between the header buttons
- but if you move into a search field because you can use arrows in the field up and down arrow should move next/previous. up/down arrow can also be used as left/right on buttons

**Review by deep7102 — COMMENTED** [review]
All other looks good, just saw same as https://github.com/infor-design/enterprise/pull/7022#issuecomment-1357797669

**Comment by ericangeles** [comment]
@tmcconechy, when I am testing the keyboard thing under the header and comparing it to the older version, it's all the same. Perhaps we can look at this one after we push the beta for the landmark team?

**Comment by tmcconechy** [comment]
Made issue https://github.com/infor-design/enterprise/issues/7041 will continue to review

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
