### PR TITLE
6891 - Fix Tree Map label styling in RTL.

### PR DESCRIPTION
**Pull request by RJ-Csc**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted label styling to not get cut off in RTL.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/6891

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to http://localhost:4000/components/treemap/example-index.html?locale=ar-sA
- Tree map labels should be properly visible in RTL.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by ericangeles — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by yohannahbautista — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/b94b6fe6-902c-4411-9250-12f0b889c5dc



image

**Comment by ericangeles** [comment]
@RJ-Csc, could you please fix the conflicts in the changelog, and then we'll be good to go here. Thanks!

**Review by janahintal — DISMISSED** [review]
Observation: % looks off in New theme

**Review by jbrcna — APPROVED** [review]
Approving
image

**Pull request merged**
