### PR TITLE
8443 - Fixes on chart legends

### LINKED ISSUE #8443: Donut: Issues with selection on legend popup
**Describe the bug**
Seeing a few issues on selection on the popup example

**To Reproduce**
1. Go to http://localhost:4000/components/donut/example-legend-bottom-popup.html
2. Click on legend menu and select the first item
3. Click on the legend item and see it incorrectly selects and changes
4. Also Click on a pie slice -> see it does not select the text in the legend

**Expected behavior**
Both above scenarios should work

**Additional context**
https://github.com/infor-design/enterprise/pull/8440

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

- Fix on legend colors updating correctly on select

**Related github/jira issue (required)**:

Closes #8443 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/donut/example-legend-bottom-popup.html
- Check legends on selecting

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Upon clicking the slice, the legend does not change to its corresponding label.

https://github.com/infor-design/enterprise/assets/102151352/0f7e3df9-6ead-45ba-b39d-6480e91e033a

**Review by janahintal — CHANGES_REQUESTED** [review]
Selected and legend changes after switching versions
https://github.com/infor-design/enterprise/assets/45757016/4ae4795d-0694-44cd-9a04-a2e65a5f1728

**Review by jbrcna — CHANGES_REQUESTED** [review]
legend does not reflect Selected item 
image

**Comment by tjamesallen15** [comment]
Can you guys try it on local testing? It seems the changes of @yohannahbautista is working when using local build

@infor-design/qa

**Comment by jbrcna** [comment]
> Can you guys try it on local testing? It seems the changes of @yohannahbautista is working when using local build
> 
> @infor-design/qa

issue still exists
image

**Review by janahintal — CHANGES_REQUESTED** [review]
Issue still exists in https://8443-chart-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html?theme=classic&mode=light&colors=default

I have selected `Response Late` legend yet all the other legend is till enabled or looks selected 
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The bug still exists in localhost.


https://github.com/infor-design/enterprise/assets/102151352/97feed1a-e733-4eb3-a09c-3e0f6ed293fe

**Review by jbrcna — CHANGES_REQUESTED** [review]
issue still exists in "Response late" category
image
image
also, there is an error in line 134
image

**Comment by tmcconechy** [comment]
@yohannahbautista

Summary:

1. the issue was when you click the legend text for the one visible legend. And that still happens.
2. lso seems like the text size and layout of the legend item changed. I would make it centered and same size as http://localhost:4000/components/donut/example-index.html
Screenshot 2024-03-26 at 12 46 07 PM
3. I noticed on http://localhost:4000/components/donut/example-index.html if you click the "Component A" slice it doesnt select.

**Review by tmcconechy — DISMISSED** [review]
Looks good. The focus state could be a bit more centered with the text to the swatch. But will let that go.

Screenshot 2024-03-28 at 10 54 40 AM
Screenshot 2024-03-28 at 10 54 28 AM

**Review by jbrcna — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
