### PR TITLE
4640 - Fix border behavior when hovering the card in editable mode

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes the behavior of border when hovering the card/widget in editable mode.

Noticed that the color of draggable/resizable were not using our color palette. Made some adjustments on scss file for us to easily adjust the color/s on different themes and variants (If we think we need to change it).

Expectation in this fix,

- Basically, the border color of widget/card (in editable) when hovered, will be blue (by default) on all themes and variants. Maybe we can discuss the color of it (I see white looks good on dark mode).
- When hovering out, it should retain the default border color of the widget/card. There should be no white border color.

Open for discussions.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4640

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/homepage/example-editable.html
- Hover the widget. (It should have blue border color)
- Hover out. It should go back to its original border color. No white border color will see.
- Test this to different combinations of themes and variants

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
- on subtle - dark mode - suggest we keep the borders as before 
- on subtle - high contrast mode- the bottom one has an extra border around
- on uplift - high contrast mode- the bottom one has an extra border around
- on uplift - dark contrast mode - the top two has an extra border around (should be like the bottom one)

basically i thin the hover should just be the blue around them all and thats the only state?

**Comment by ericangeles** [comment]
Hi @tmcconechy, I don't see these issues

on subtle - high contrast mode- the bottom one has an extra border around
on uplift - high contrast mode- the bottom one has an extra border around
on uplift - dark contrast mode - the top two has an extra border around (should be like the bottom one)

Do you have a screenshot to identify these?

Thanks

**Review by EdwardCoyle — APPROVED** [review]
:banana: Looked good to me, @tmcconechy seems like those issues are fixed now

**Comment by tmcconechy** [comment]
What i mean is ... In dark theme(s) we changed the border and i think it looked better before

http://localhost:4000/components/homepage/example-editable.html?theme=soho&variant=dark&colors=2578a9

Before
Screen Shot 2020-12-09 at 9 44 29 AM

Now
Screen Shot 2020-12-09 at 9 44 10 AM

I think thats all i see now.

**Comment by ericangeles** [comment]
Thanks, @tmcconechy @EdwardCoyle. All set!

**Review by EdwardCoyle — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
Thanks Eric looks good now 👍🏻  🍌

**Pull request merged**
