### PR TITLE
8410 - Charts Resize

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix the resize issues of bar, column, donut and line when using in homepage.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8410

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/homepage/test-all-charts.html
- Try to resize the browser
- Do it with the other examples below.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
I guess i see a few things. 

1. At this size the home page goes off the page. Is there a problem in the home page setup or is this a home page bug?
Screenshot 2024-03-27 at 10 45 44 AM

2. At this size the pie chart looks strange
Screenshot 2024-03-27 at 10 46 38 AM



Screenshot 2024-03-27 at 10 45 44 AM

**Review by janahintal — CHANGES_REQUESTED** [review]
Chart is getting distorted after switching back to full screen 
**https://8410-charts-resize-issues-enterprise.demo.design.infor.com/components/homepage/test-chart-donut.html?theme=classic&mode=light&colors=default**
image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The chart is not adjusting in Safari - Classic Version.

image

image

Same issue in Mac Chrome - Classic  Version.

image

**Review by n-ace-ancog — COMMENTED** [review]
Mac: charts are not resizing and no horizontal bar displays
**Safari**
image

**Chrome**
image

Counter checked on Windows Chrome via BrowserStack 
**With scroll bar**
image

**Without scroll bar, but redrawn**
image

**Comment by tmcconechy** [comment]
I also noticed the home page seems messed up see http://localhost:4000/components/homepage/example-index.html how the scroll bar cuts off the bottom.

**Comment by tjamesallen15** [comment]
I made a new example page and the resize is working on my end video below.
http://localhost:4000/components/homepage/test-all-charts.html

https://github.com/infor-design/enterprise/assets/34049950/4cd203b8-25e0-4d1a-9504-2145f505a4aa

@infor-design/qa @tmcconechy @ericangeles

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/607dbff4-00cc-4f6a-9ce6-698531fa7476

**Comment by jbrcna** [comment]
image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
