### PR TITLE
6530 - add setting ariaDescribedBy in the column to override the aria-describedby value

### LINKED ISSUE #6530: Datagrid: redundant aria-describedby attributes at cells.
**Describe the bug**
Table cells each have an aria-describedby attribute which references their column header. This information is redundant. 

**To Reproduce**

1. Go to http://localhost:4000/components/datagrid/test-landmark.html
2. Inspect the cell, and check that the td attribute has a redundant aria-describedby attribute

**Expected behavior**
The datagrid cells don't need a redundant aria-describedby attribute.

**Version**

- ids-enterprise: 4.64

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Landmark 
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 100.0.2 (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-40109

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR allows overriding the `aria-describedby` value in the cells by adding the `ariaDescribedBy` setting in the column.

**Related github/jira issue (required)**:

Closes #6530 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-landmark
- Inspect the cells in `Product Name` column `td` element
- The `aria-describedby` values of all cells should be `id-row-1-cell-1 `and incrementing +1 e.g., `id-row-2-cell-1`
- Check also the `Manufacturer` Column (the first one)
- It should also be the same as the `Product Name` column but the incrementing part is in the cell, eg., `id-row-1-cell-1`, `id-row-1-cell-2`, etc.
- The rest of the column cells should start in `test-landmark`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@corpulent how do we fix the issue in File check / Test changed-files here?

**Review by tmcconechy — COMMENTED** [review]
Just a note that the pacakge-lock.json was accidentally included (maybe from the node work so should probably remove that from the PR).

Also i didnt check it yet but are the aria-described-by's possible the exact same as before (thats going to be important for them)

**Comment by ericangeles** [comment]
@tmcconechy yeah, I reverted to the original, and the setting overriding works fine.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@ericangeles just so we make sure its possible can you make the example show the exact same aria-described by's as before i was testing https://4590-enterprise.demo.design.infor.com/components/datagrid/test-landmark and its different

Screen Shot 2022-09-23 at 10 30 04 AM

Just have to maybe use the same idea as before in the example, taking the page url ect..

**Comment by tmcconechy** [comment]
right, but they might want to see that you can actually make them the same as before. the problem. being that the test scripts are broken and they need all the IDs to be the exact same as before

**Comment by ericangeles** [comment]
@tmcconechy all good!

**Review by tmcconechy — DISMISSED** [review]
Cool looks good. I think Landmark will need the type added to NG for the new setting. So maybe go ahead and PR that as well?

**Review by tjamesallen15 — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by vonnyw** [comment]
@ericangeles @tjamesallen15 how would one remove the ariaDescribedBy attribute? The initial ask for 508 compliance is to remove the attribute, due to references in test code, we need the setting to toggle it back and forth.

**Comment by ericangeles** [comment]
@vonnyw we reverted back it to the original behavior and added a setting to override the aria-describedby value.

**Comment by vonnyw** [comment]
We don't wish to override the aria-describedBy value, but remove it based on the original ticket entered https://github.com/infor-design/enterprise/issues/6530.

**Comment by tmcconechy** [comment]
@vonnyw i don’t really understand. On the original fix we removed the aria. But you said you needed it for testing still. So we added. It back as a setting you can use because it is incorrect we don’t want it by default. But. Ow you can either use the setting or not. So you have the choice and could maybe toggle it as a setting or something. I don’t see what we could change, you have the choice to use it or not.

**Comment by vonnyw** [comment]
@tmcconechy is there a setting to remove the attribute all together if we don't wish to use it?

**Comment by tmcconechy** [comment]
Yes but you either use it or don’t use it so you would need to add to to the columns of the datagrid or not add it. (So you could do a setting and add or remove the column setting)

**Comment by ericangeles** [comment]
@tmcconechy I remember we reverted back the original behavior of it (having aria-describedby property by default). The original fix was removing the property without any setting to add the aria-describedby property.

**Comment by tmcconechy** [comment]
@ericangeles so its not a column setting its just on all the time now?

**Comment by ericangeles** [comment]
Its a column setting but we reverted back the original behavior of aria-describedby which is by default it adds in the row. The first fix that we did was to remove it and we reverted it back with the addition of column setting to override it.

**Comment by tmcconechy** [comment]
ok that was my understanding. Either way Landmark can use it or not (so effectively its a setting)

**Comment by ericangeles** [comment]
I think they want to get rid of the aria-describedby and we don't have any ability to do that.

**Comment by vonnyw** [comment]
@ericangeles yes, this is what I am asking for: we want to get rid of the aria-describedby and we don't have any ability to do that.

**Comment by tmcconechy** [comment]
I guess I don’t understand then. Looking at this code you can specify ariaDesribedBy on the column https://github.com/infor-design/enterprise/pull/6843/files#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5R4861

wouldn’t that constitute a setting? So you just change the column config and reload the grid ?

**Pull request merged**
