### PR TITLE
5671 - Added setFailed status method in fileupload

### LINKED ISSUE #5671: Advanced File Upload: No way to set a file upload as failed and to display error message
In the advanced file upload component, there is no way to set an upload as failed and to display the error message received from backend.

Only following API are provided with the component:
```
interface SohoFileUploadAdvancedStatus {
  /** The file being uploaded. */
  file: File;

  setCompleted(data?: any): void;

  setProgress(percent: number): void;

  setAbort(xhr?: any): void; // xml http request object
}
```

**Expected Behavior**: Provide an API to set status as failed and to provide an error message as input.

**Actual Behavior**: No way to set an upload as failed and to display an error message

Product: Infor PIM

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added setFailed status method in fileupload, will show a custom error message when called.

**Related github/jira issue (required)**:

Closes #5671 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/fileupload-advanced/example-failed.html
- Upload a file
- Click Set Failed button

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
would this work for you @hemantg05

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@yohannahbautista - im thinking maybe we should make this function callable at anytime not just in the sendtoserver call back.

So:
- make a component method setMessage or setFailed ect
- make a button the example and call it to set a message (you might need to first upload the file tho which is fine)
- keep it in both the sendfiletoserver callback and just have an arbitrary function as well

**Review by tmcconechy — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]

**Comment by hemantg05** [comment]
@tmcconechy, is this fixed in ids-enterprise-ng as well?  I pulled latest from main branch and I did not see any setFailed method.

**Comment by tmcconechy** [comment]
not yet - can you add the types @ericangeles ?
usually before i release i go check the issues for these but dont always catch them all.

feel free to PR if you beat us to it

**Pull request merged**
