### PR TITLE
4982 - Fix missing border and dropdown list misalignment in uplift

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes missing border in the input field and dropdown list does not properly align when it opened. Removing the border right color which is transparent also fixes the alignment of the dropdown list.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4982

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-short.html
- The input field should have border now
- Open the dropdown filter
- List should be align with the input field

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I see two problems...

1. go to http://localhost:4000/components/field-filter/example-short.html
1. press on the button to open the list -> notice that the button gets bigger / arrow placement moves
1. in all themes when you focus the field the border only goes 3/4 around the field

This component isnt that critical so willing to let that go if its hard but if we really want to fix those up i would take a quick look

**Comment by EdwardCoyle** [comment]
@ericangeles I was still seeing some issues with the border/box shadow after the last round of changes.

When the menu button is focused, there's a double-border:
Screen Shot 2021-03-25 at 10 07 42 AM

When the input is focused, the box shadow seems like it's "cut off" by the button:
Screen Shot 2021-03-25 at 10 07 48 AM

**Comment by ericangeles** [comment]
@tmcconechy @EdwardCoyle, something weird was going on in the `New` / `Uplift` version. When the edges of the dropdown and input overlap or on top of one another, it is not visible for some reason. But in the `Classic` version, it behaves as expected.

Although this component is not critical or major, so I fix it in a tricky way.

**Review by EdwardCoyle — APPROVED** [review]
@ericangeles looks good, I was worried about hardcoding the z-index here but it doesn't seem to conflict with anything :banana:

**Comment by tmcconechy** [comment]
Possibly make it under 20... Like does 2-3 work? We made this "system" up over time and it could conflict with contextual toolbar

```
20 - Contextual Toolbar
500 - Side Menu, Status Bar
1000 - Overlay
1010 - Busy Indicator
1015 - Popdown
1020 - Dialogs (Modals)
3000 - Popovers
4000 - Lookup
4500 - Drop Down
6000 - Tooltips
7000 - Draggables
8000 - Slide in Message Dialog/Toast
9000 - Sticky Nav / Context Menus
10000 - Full Page Sticky Nav, Search Results
10020 - Skip link
```

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
