### PR TITLE
8444/8285 - Fix special characters converted into an encode values

### LINKED ISSUE #8285: Datagrid: Backslash in edited cell is replaced with "&bsol;"
**Describe the bug**
In Datagrid, when typing Backslash in editable cell it replace with `&bsol;`

**To Reproduce**

1. Go to [https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html)
2. Click on of the cells
3. Type or paste a text with backslash, for instance `c:\windows\temp`
4. See that it changed into `c:&bsol;windows&bsol;temp`

**Expected behavior**
backslash should remain backslash.

It worked fine in v4.82.0 - but I don't know now how to reproduce it because design.infor.com was changed

**Version**

- ids-enterprise: v4.90.0

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
Thanks!

### LINKED ISSUE #8444: Datagrid: edited cell showing encoded value when setting rowStatus
**Describe the bug**
In datagrid, after editing a cell with a special character the cellChange event listener makes a call to update rowStatus.  The encoded value is displayed in the cell.

**To Reproduce**

1. Using the attached example, 'http://localhost:4000/components/datagrid/example-editable-with-row-status.html'
2. Click on Activity cell for row 3.
3. Type in a special character (for example, '<', '>', '&')
4. Exit the cell
5. Notice the value is encoded

**Expected behavior**
Display value is not encoded.

**Version**

- ids-enterprise: v4.92

**Additional context**
Landmark will need a patch to v4.92

### PR DESCRIPTION
**Pull request by ericangeles**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes both these issues #8444 & #8285, where it converts special characters into their html character entities after a cell change.

**Related github/jira issue (required)**:

Closes #8444
Closes #8285

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to
  - http://localhost:4000/components/datagrid/example-editable-with-row-status.html (For editable with row status)
  - Type in a special character (for example, '<', '>', '&') in first cell  under `Activity` column
  - After cell out, it should not change into encode value
  - http://localhost:4000/components/datagrid/example-editable.html (Editable only)
  - Enter this value `c:\windows\temp` in a cell under `Activity` column
  - It should not change into encode values as well
  - http://localhost:4000/components/datagrid/test-editable-lookup-mask.html
  - Open the lookup modal
  - Select the cell that has script tag
  - It should not run the script

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@claudenbach, ready for testing.

**Comment by n-ace-ancog** [comment]
/example-editable-with-row-status.html
Animation

**Steps to reproduce:**
1. Populate Activity cell with '<>&' values
2. Navigate to 2nd page
3. Return back to 1st page
4. The values are encoded

**Review by glenlieorillo — APPROVED** [review]
https://8444-datagrid-edited-cell-enterprise.demo.design.infor.com/components/datagrid/example-editable-with-row-status.html

https://github.com/infor-design/enterprise/assets/102151352/87acf3e7-0088-4565-ab50-b380ee39a7b9

https://8444-datagrid-edited-cell-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

https://github.com/infor-design/enterprise/assets/102151352/bb589a95-0b28-46b0-a9d4-e9f4c71f00b1

**Comment by jbrcna** [comment]
this is working as expected. However, when you go to other page it becomes encode values
image

image

image

after going to other page
image
image

**Review by janahintal — APPROVED** [review]
image
image

**Comment by n-ace-ancog** [comment]
http://localhost:4000/components/datagrid/example-editable.html[](url) - after clicking the 1st row cell with value **<svg/>** and focusing out, a huge empty space filled the cell. Going to the next page and returning back produces the encoded values.

Animation

**Comment by claudenbach** [comment]
I've been testing with your changes and also seeing that after saving the changes and refreshing the encoded values are displayed for special characters.

**Comment by claudenbach** [comment]
Encoding-Testing

**Comment by ericangeles** [comment]
We'll push more changes as we encounter a couple of bugs in the last commit.

**Review by n-ace-ancog — APPROVED** [review]
http://localhost:4000/components/datagrid/example-editable-with-row-status.html - now **working as expected**. Navigating back and forth doesn't encode the values anymore.

Animation

http://localhost:4000/components/datagrid/example-editable.html - **working as expected**. Cell with `<svg/>` not filling up the entire cell with space anymore.

Animation

http://localhost:4000/components/datagrid/test-editable-lookup-mask.html - **working as expected**. After selecting the record with a `<script>` tag, no alert was displayed.

Animation

**Comment by tmcconechy** [comment]
Problems on this one:

1. Cant type numbers in the cells like "11.11" in the price cell
2. Not sure that the checking if a script is that safe as it could come in other ways

**Pull request closed without merging**
