### PR TITLE
5182 - Toolbar flex missing x icon mobile

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the tag text in the datagrid column is not shown properly when hovering it on Alternate Row Shading.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5182

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toolbar-flex/example-index.html
- Switch to mobile view or Open in Browserstack mobile device
- Click searchfield and enter some text

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I dont think this solved all the cases. I tried a iphone x and iphone 6/7/8plus and see

a) the icons are barely visible
b) when expanded the field is out of alignment

Screen Shot 2021-06-07 at 9 31 27 AM
Screen Shot 2021-06-07 at 9 31 34 AM

**Comment by tmcconechy** [comment]
@tjamesallen15 this is looking good but see two small issues.
Screen Shot 2021-06-08 at 9 43 40 AM

1. The expand/collapse icon sits a bit low in the button (alignment)
2. When you press the x it doesn't go away like it does on https://main-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html (the x should only be there if there are contents)

**Comment by tjamesallen15** [comment]
> * The expand/collapse icon sits a bit low in the button (alignment)
> * When you press the x it doesn't go away like it does on https://main-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html (the x should only be there if there are contents)

I'll fix this now.

**Comment by ericangeles** [comment]
Additional to what @tmcconechy just pointed out, the close button should be only visible once the input field has text.

**Comment by ericangeles** [comment]
The last commit looks good, but I just found another issues on this.

- Go to http://localhost:4000/components/toolbar-flex/example-index.html
- Open developer tools or BrowserStack
- In developer tools, toggle device toolbar then set it on iPhone 6/7/8
- Then toggle rotate (make it horizontal)
- Search on toolbar flex
- Close button is missing, and the height of searchfield is not vertically align with the collapse button


missing-x-btn


- Also on a widescreen, tab to focus the close button, focus doesn't perfectly align

widescreen

**Review by tmcconechy — APPROVED** [review]
Looks good to me now

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
