### PR TITLE
allow callOnBeforeSelect on last step

### PR DESCRIPTION
**Pull request by boehmd1**
> Explain the **details** for making this change. What existing problem does the pull request solve?

> **Related issue (required)**:

> **Steps necessary to review your pull request (required)**:

> Other Details:

### CODE REVIEW

**Comment by boehmd1** [comment]
47:8    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  48:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  49:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

Getting lots and lots of these when I run npm run eslint. Any ideas?
I did run the `git config core.autocrlf false`

**Comment by tmcconechy** [comment]
Re The test what timezone is your machine on?

**Comment by boehmd1** [comment]
@tmcconechy does this ticket require anything more

**Comment by tmcconechy** [comment]
If you resolved the cl/lf issue on your end i think its ok.
I would like to track down the test failure. What timezone is your computer on? It didnt fail on the checks which also runs it tho so maybe not a big issue.

**Comment by boehmd1** [comment]
@EdwardCoyle could you take a look at this ticket sometime today, thanks

**Comment by boehmd1** [comment]
What build is this change in

**Comment by tmcconechy** [comment]
You can take any nightly after the date it was merged... https://www.npmjs.com/package/ids-enterprise

But you probably want the latest one. Or the 4.7.0 release (EOW)

**Pull request merged**
