### PR TITLE
8363 - Fixed increment/decrement and today key being activated in range mode

### LINKED ISSUE #8363: Datagrid: Date filter with In Range and Increment with keyboard overwrites entered value
**Describe the bug**
A date picker with options:
```
var dateOptions = {
      showMonthYearPicker: 'true',
      hideDays: 'true',
      dateFormat: Soho.Locale.calendar().dateFormat.month,
      incrementWithKeyboard: true,
      todayWithKeyboard: true
    }
```

is behaving strangely when it's on a datagrid filter bar and the In Range filter type is chosen. Since the format for the field means that it displays <Month Year> (i.e. January 2021), and hideDays is true, there is no picker affordance to select a range:
image

This should be fine, since the user could type in the value they wanted. However, we also have incrementWithKeyboard and todayWithKeyboard set to true. So if the user attempts to type "October 2023", the control will see that t was typed and put in today. If they tried to type "April 2020 - May 2021", the control would see the - and decrement April 2020 instead of typing the entire string.

I realize that this is technically working as intended, but I don't believe that incrementWithKeyboard and todayWithKeyboard make sense with the In Range filter type. Would it be possible that when In Range is selected, to disconnect those event listeners? 

**To Reproduce**
1. Copy [test-filter-date-hide-days.zip](https://github.com/infor-design/enterprise/files/14013806/test-filter-date-hide-days.zip) into 
app/views/components/datagrid
2. Navigate to /components/datagrid/test-filter-date-hide-days.html
3. Change the filter type for Order Date to In Range
4. Try and type in "January 20 - April 20". See that when - is typed, it just decrements the first date.
5. Clear the field and try to type "October 20 - December 20". See that when t is typed, it defaults to today's date.

**Expected behavior**
When In range filter is chosen, it would be nice if the incrementWithKeyboard and  todayWithKeyboard events are disconnected.

**Version**

- ids-enterprise: v4.91.0-dev.0

**Screenshots**
DatePickerInRangeIncrement

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - All

### PR DESCRIPTION
**Pull request by yohannahbautista**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Increment/decrement and today keys should not be used when datepicker is in range mode

**Related github/jira issue (required)**:

Closes #8363 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-filter-date-hide-days.html
- Switch to range in date filter and type a date range
- When typing "-", "+', or "t" the date shouldn't change

**Included in this Pull Request**:
- [ ] A note to the change log.

### CODE REVIEW

**Comment by ericangeles** [comment]
@yohannahbautista, so it should only shows the strings (-, +, t)?

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working as expected.
**In Range:**
Animation

**Others**
Animation

**Review by glenlieorillo — APPROVED** [review]
**Mac Chrome**

- In Range

https://github.com/infor-design/enterprise/assets/102151352/0943e4d8-211a-49c8-b1c0-57b2c418b6d3

- Others

https://github.com/infor-design/enterprise/assets/102151352/806d3801-42a8-4b81-9988-a8c57aba1acb



**Mac Firefox**

- In Range

https://github.com/infor-design/enterprise/assets/102151352/fa4e7577-ce06-472d-8c7c-5f22a2fc3d62

- Others

https://github.com/infor-design/enterprise/assets/102151352/0a90b7ca-d7a3-4fd4-a11e-51c8e585ff99



**Safari**

- In Range

https://github.com/infor-design/enterprise/assets/102151352/3e370d94-efc2-45ef-a6c2-7cb5b3adbd67

- Others

https://github.com/infor-design/enterprise/assets/102151352/c1646604-7d61-4e89-9c1b-67d1ca605d58

However, the searchlist icon under `Product Id` is misaligned in Mac Firefox and it is missing in Safari. I will create a new issue for this bug. See screenshots below. 


image

image

**Comment by ericangeles** [comment]
Lets create a ticket for that, @glenlieorillo. Thank you.

**Comment by glenlieorillo** [comment]
> Lets create a ticket for that, @glenlieorillo. Thank you.

Yes, @ericangeles. I already have created an issue for this bug. Refer to this link: [8504](https://github.com/infor-design/enterprise/issues/8504)

**Pull request merged**
