### PR TITLE
5254 - Add swipe action component

### LINKED ISSUE #5254: Mobile: Add swipe container component
**Describe the bug**
Add the newly coming swip-container component to EP.

**To Resolve**
- Add an example to web components
- Port example code to old code

**Design**
Screen Shot 2021-06-01 at 1 34 49 PM

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR contains a port of the swipe-action web component for the jQuery lib.

**Related github/jira issue (required)**:
Fixes #5254 (Except for needs NG component)

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/swipe-action/example-index.html
- (try this on chrome with magic mouse or on a ios / android device)
- for the first one you swipe left or right 
- click the button and you should see the text change indicating the swipe "clicked" the button
- for the second one you swipe only left
- click the button and you should see the text change indicating the swipe "clicked" the button
- for the third one one you swipe  left or right 
- you should see the text change indicating the swipe "clicked" the button immediately

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — APPROVED** [review]
Looks nice 🍌 not sure it related or not
- action button on cards currently is square (is it should be round)
- popup menu for action button not close, on/after swipe

**Comment by tmcconechy** [comment]
@deep7102 Fixed both issues. Thanks!

**Review by ericangeles — APPROVED** [review]
🍌

**Review by EdwardCoyle — APPROVED** [review]
🍌

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
